/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rksF.c
 *
 * Code generation for function 'rksF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rksF.h"

/* Function Definitions */
void rksF(const real_T in1[34], const real_T in2[12], real_T s, real_T r_ks[6])
{
  (void)in1;
  (void)s;

  /* RKSF */
  /*     R_KS = RKSF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 18:10:21 */
  r_ks[0] = 0.0;
  r_ks[1] = 0.0;
  r_ks[2] = 0.0;
  r_ks[3] = in2[0];
  r_ks[4] = in2[1];
  r_ks[5] = in2[2];
}

/* End of code generation (rksF.c) */
