/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 16,    /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 17,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 20,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 21,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 22,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 27,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4_tmp;
  real_T t5_tmp;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t10;
  real_T t14_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 13:21:33 */
  st.site = &emlrtRSI;
  t2 = in1[4] * in1[4];
  st.site = &b_emlrtRSI;
  t3 = s * s;
  t4_tmp = in2[0] * t2;
  t5_tmp = in2[1] * t2;
  st.site = &c_emlrtRSI;
  t6 = in2[3] * in2[3];
  st.site = &d_emlrtRSI;
  t7 = in2[4] * in2[4];
  st.site = &e_emlrtRSI;
  t8 = in2[5] * in2[5];
  t11 = t2 * t6;
  t12 = t2 * t7;
  t13 = t2 * t8;
  t10 = ((-t11 - t12) - t13) + 1.0;
  st.site = &f_emlrtRSI;
  if (t10 < 0.0) {
    b_st.site = &h_emlrtRSI;
    error(&b_st);
  }

  t10 = muDoubleScalarSqrt(t10);
  t14_tmp = in2[2] * t2;
  r_jtip[0] = t4_tmp * t3;
  r_jtip[1] = t4_tmp;
  r_jtip[2] = t5_tmp * t3;
  r_jtip[3] = t5_tmp;
  r_jtip[4] = in1[4] * s + t14_tmp * t3;
  t3 = in1[4] + t14_tmp;
  r_jtip[5] = t3;
  r_jtip[6] = rtNaN;
  t14_tmp = in1[16] * in1[4];
  r_jtip[7] = (t4_tmp + t14_tmp * in2[4] * t10 * 2.0) + in1[16] * in2[3] * in2[5]
    * t2 * 2.0;
  r_jtip[8] = rtNaN;
  r_jtip[9] = (t5_tmp - t14_tmp * in2[3] * t10 * 2.0) + in1[16] * in2[4] * in2[5]
    * t2 * 2.0;
  r_jtip[10] = rtNaN;
  t14_tmp = in1[16] * t2;
  r_jtip[11] = (((t3 - in1[16] * (((t11 + t12) + t13) - 1.0)) - t14_tmp * t6) -
                t14_tmp * t7) + t14_tmp * t8;
}

/* End of code generation (rjtipF.c) */
