function r_jtip = rjtipF(in1,in2,s)
%RJTIPF
%    R_JTIP = RJTIPF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jan-2019 18:00:05

l_f_sym = in1(:,17);
q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q7 = in2(:,7);
q8 = in2(:,8);
q9 = in2(:,9);
q10 = in2(:,10);
q11 = in2(:,11);
q12 = in2(:,12);
t2 = q10.^2;
t3 = q11.^2;
t4 = q12.^2;
t5 = -t2-t3-t4+1.0;
t6 = sqrt(t5);
r_jtip = reshape([q1,q7,q7,q2,q8,q8,q3,q9,q9,q1,q7,q7+l_f_sym.*q10.*q12.*2.0+l_f_sym.*q11.*t6.*2.0,q2,q8,q8+l_f_sym.*q11.*q12.*2.0-l_f_sym.*q10.*t6.*2.0,q3,q9,q9-l_f_sym.*t2-l_f_sym.*t3+l_f_sym.*t4-l_f_sym.*(t2+t3+t4-1.0)],[3,6]);
