/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vdF.c
 *
 * Code generation for function 'fj_vdF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "fj_vdF.h"

/* Function Definitions */
void fj_vdF(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T fj_vd[6])
{
  (void)sp;
  (void)s;

  /* FJ_VDF */
  /*     FJ_VD = FJ_VDF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 21:11:28 */
  fj_vd[0] = -in1[5] * in2[6] * muDoubleScalarPower(muDoubleScalarAbs(in2[6]),
    in1[11] - 1.0);
  fj_vd[1] = -in1[6] * in2[7] * muDoubleScalarPower(muDoubleScalarAbs(in2[7]),
    in1[11] - 1.0);
  fj_vd[2] = -in1[7] * in2[8] * muDoubleScalarPower(muDoubleScalarAbs(in2[8]),
    in1[11] - 1.0);
  fj_vd[3] = -in1[10] * in2[9] * muDoubleScalarPower(muDoubleScalarAbs(in2[9]),
    in1[11] - 1.0);
  fj_vd[4] = -in1[8] * in2[10] * muDoubleScalarPower(muDoubleScalarAbs(in2[10]),
    in1[11] - 1.0);
  fj_vd[5] = -in1[9] * in2[11] * muDoubleScalarPower(muDoubleScalarAbs(in2[11]),
    in1[11] - 1.0);
}

/* End of code generation (fj_vdF.c) */
