%% initialize
close all
clear all
format shorte
clc
pause( 1e-2 )

addpath('./tmtdyn','./hll','./eom');


%% parameters
l_xz2 = 73e-3 / 5 ;
l_y2 = 0.8e-3 ;
m_2 = 36e-3 / 15 ;

l_x1 = 76e-3 / 2 ;
l_z1 = 30e-3 ;
l_com1 = 135e-3 ;

g = 9.81 ; % gravity

% EBA
E = 1.5e3 ;
mu_pow = 1 ; % < 1: rate thining, > 1: rate thikening
mu_v = 5e1 ;
mu_u = 5e1;
mu_link = 7e-4 ;

phi = -50 * pi/ 180 ;
 
% variables & values
syms E_sym mu_pow_sym mu_v_sym mu_u_sym phi_sym mu_link_sym
vars = [E_sym, mu_pow_sym, mu_v_sym, mu_u_sym, phi_sym, mu_link_sym];
var_vals = [E, mu_pow, mu_v, mu_u, phi, mu_link] ;


%% preprocess
G = E_sym / 3 ;
I_2 = 1 / 12 * m_2 * ...
    diag( [ l_y2^2+l_xz2^2 l_xz2^2+l_xz2^2 l_xz2^2+l_y2^2 ] ) ;
J_2 = 1 / 12 * [ l_xz2*l_y2^3 l_xz2^3*l_y2 l_xz2*l_y2^3+l_xz2^3*l_y2 ] ;
a_xy2 = l_xz2 * l_y2 ;
K_v = diag( [ G G E_sym ] ) * a_xy2 / l_xz2 ;
K_u = diag( [ E_sym E_sym G ] ) * diag( J_2 ) / l_xz2 ;


%% robot
tmtdyn()...
    .simulation()... % simulation
        .var(E_sym, E)...
        .var(mu_pow_sym, mu_pow)...
        .var(mu_v_sym, mu_v)...
        .var(mu_u_sym, mu_u)...
        .var(phi_sym, phi)...
        .var(mu_link_sym, mu_link)...
        .derive_eom()...
            .simplify_derivations()...
            .use_mex()...
            .optimize_code()...
        .analysis()...
            .static_sim('m_file', 0)...
            .dynamic_sim('m_file', 0, 1)...
        .post_process()...
            .animate()...
            .run_user_code()...
    .world()... % world
        .g([0, 0, -g])...
    .robot('fabric_pendulum')... % robot
        .body('arm')...
            .with_mass(m_2)...
            .with_center_of_mass_at([0, 0, -l_com1])...
		    .connected()...
		        .with_transformation_from()...
		            .rot_y()...
					    .initial_value(phi_sym)...
					    .parallel_damper()...
					        .viscosity(mu_link_sym)...
    .mesh('fabric')...
        .from_file('exp/exp2.iges', 1e-3)...
        .with_transformation()...
            .rot_y(phi_sym)...
            .trans_z(-l_z1)...
        .with_node('fabric')...
            .with_mass(m_2)...
            .with_inertia(I_2)...
		    .connected()...
		        .with_transformation_from()...
		            .translation([inf inf inf])...
		            .rot_non_unit_quat([inf inf inf inf])...
                    .dof(1)...
                        .initial_value(1)...
        .with_edge('fabric_links')...
            .beam_stiffness()...
                .coefficient([diag( K_v ).', diag( K_u ).'])...
                .initial_state_from_configuration()...
            .beam_damping()...
                .viscosity([mu_v_sym*ones(1,3), mu_u_sym*ones(1,3)])...
                .power(mu_pow_sym)...
    .constraint('clip_constraint_1')...
        .from_body(1)...
        .with_transformation_from()...
            .translation([l_x1, 0, -l_z1])...
        .to_body(16)...
        .fixed_directions([1, 1, 1])...
    .constraint('clip_constraint_2')...
        .from_body(1)...
        .with_transformation_from()...
            .translation([-l_x1, 0, -l_z1])...
        .to_body(14)...
        .fixed_directions([1, 1, 1])...
    .run();

