function out1 = fj_vdF(in1,in2,s,ds,t_sym)
%FJ_VDF
%    OUT1 = FJ_VDF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Jun-2021 05:42:46

out1 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
