function [out1,out2,out3,out4,out5,out6,out7,out8,out9] = nqF(in1)
%NQF
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8,OUT9] = NQF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Feb-2019 12:17:13

out1 = 2.4e1;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    t2 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
    out3 = t2;
end
if nargout > 3
    out4 = 5.0;
end
if nargout > 4
    out5 = 2.4e1;
end
if nargout > 5
    out6 = 0.0;
end
if nargout > 6
    out7 = 1.0;
end
if nargout > 7
    out8 = [0.0,0.0,0.0,0.0,0.0];
end
if nargout > 8
    out9 = t2;
end
