/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "massF2.h"
#include "error.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 27,    /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 28,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 36,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 46,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 47,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 48,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 50,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 51,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo i_emlrtRSI = { 71,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo j_emlrtRSI = { 75,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo k_emlrtRSI = { 49,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

static emlrtRSInfo l_emlrtRSI = { 61,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
            real_T s, real_T out1[36], real_T out2[72], real_T out3[72], real_T
            out4[6])
{
  real_T t2;
  real_T t3;
  real_T t9;
  real_T t12;
  real_T t15;
  real_T t18;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t155;
  real_T t25;
  real_T t26_tmp;
  real_T t26;
  real_T t27;
  real_T t131;
  real_T t29;
  real_T t30;
  real_T t31_tmp;
  real_T t31;
  real_T t32_tmp;
  real_T t147;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t40_tmp;
  real_T t40;
  real_T t132;
  real_T t67;
  real_T t89;
  real_T out2_tmp;
  real_T t152;
  real_T b_out2_tmp;
  real_T t41;
  real_T t42_tmp;
  real_T t43;
  real_T t44;
  real_T t47;
  real_T t50;
  real_T t51_tmp;
  real_T t53;
  real_T t56;
  real_T t57_tmp;
  real_T b_t57_tmp;
  real_T t59;
  real_T t62;
  real_T t64;
  real_T t66_tmp;
  real_T t69;
  real_T t70_tmp;
  real_T t71;
  real_T t73;
  real_T t74_tmp;
  real_T b_t74_tmp;
  real_T t77;
  real_T t79;
  real_T t82;
  real_T t84;
  real_T t86;
  real_T t88;
  real_T t90;
  real_T t92;
  real_T t93;
  real_T t95;
  real_T t97;
  real_T t100;
  real_T t103;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t109;
  real_T t111;
  real_T t113;
  real_T t114;
  real_T t115;
  real_T t116;
  real_T t117;
  real_T t118;
  real_T t120;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t125;
  real_T t126;
  real_T t127;
  real_T t128;
  real_T t130;
  real_T t134;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t138;
  real_T t140;
  real_T t141;
  real_T t143;
  real_T t144;
  real_T t146;
  real_T t148;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 15:00:32 */
  st.site = &emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t2 = in1[16] * in1[16];
  st.site = &b_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  st.site = &c_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t9 = in1[4] * in1[4];
  t12 = in1[4] * in2[6] + in2[7] * t9;
  t15 = in1[4] * in2[8] + in2[9] * t9;
  t18 = in1[4] * in2[10] + in2[11] * t9;
  st.site = &d_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t19 = t12 * t12;
  st.site = &e_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t20 = t15 * t15;
  st.site = &f_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t21 = t18 * t18;
  t22 = ((-t19 - t20) - t21) + 1.0;
  t2 = t22;
  st.site = &g_emlrtRSI;
  b_sqrt(&st, &t2);
  t23 = 1.0 / t2;
  t2 = t22;
  st.site = &h_emlrtRSI;
  b_sqrt(&st, &t2);
  t155 = in1[16] * in1[4];
  t25 = t155 * t2;
  t26_tmp = in1[16] * t9;
  t26 = t26_tmp * t2;
  t27 = t155 * t18;
  t131 = t26_tmp * t18;
  t29 = in1[4] * t18 * 2.0;
  t3 = in1[4] * t12;
  t30 = t3 * t15 * t23 * 2.0;
  t31_tmp = t9 * t18;
  t31 = t31_tmp * 2.0;
  t32_tmp = t9 * t12;
  t147 = t32_tmp * t15;
  t32 = t147 * t23 * 2.0;
  t33 = in1[4] * t2 * 2.0;
  t34 = t9 * t2 * 2.0;
  t35 = t3 * t18 * t23 * 2.0;
  t36 = t32_tmp * t18 * t23 * 2.0;
  t37 = t3 * 2.0;
  t2 = in1[4] * t15;
  t38 = t2 * t18 * t23 * 2.0;
  t39 = t32_tmp * 2.0;
  t40_tmp = t9 * t15;
  t40 = t40_tmp * t18 * t23 * 2.0;
  out2[0] = t9;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  t132 = in1[4] * t9;
  out2[6] = t132;
  out2[7] = 0.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = t9;
  out2[14] = 0.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = t132;
  out2[20] = 0.0;
  out2[21] = 0.0;
  out2[22] = 0.0;
  out2[23] = 0.0;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = t9;
  out2[27] = 0.0;
  out2[28] = 0.0;
  out2[29] = 0.0;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = t132;
  out2[33] = 0.0;
  out2[34] = 0.0;
  out2[35] = 0.0;
  t67 = t155 * t12;
  t89 = t67 * t15 * t23;
  out2[36] = t27 - t89;
  out2[37] = -t25 + t155 * t19 * t23;
  out2[38] = t67 * -2.0;
  out2[39] = t33 + in1[4] * t19 * t23 * 2.0;
  out2[40] = -t29 + t30;
  t2 *= 2.0;
  out2[41] = t35 + t2;
  out2_tmp = t26_tmp * t12;
  t152 = out2_tmp * t15;
  b_out2_tmp = t152 * t23;
  out2[42] = t131 - b_out2_tmp;
  out2[43] = -t26 + t26_tmp * t19 * t23;
  out2[44] = out2_tmp * -2.0;
  out2[45] = t34 + t9 * t19 * t23 * 2.0;
  out2[46] = -t31 + t32;
  t3 = t40_tmp * 2.0;
  out2[47] = t36 + t3;
  out2[48] = t25 - t155 * t20 * t23;
  out2[49] = t27 + t89;
  t89 = t155 * t15;
  out2[50] = t89 * -2.0;
  out2[51] = t29 + t30;
  out2[52] = t33 + in1[4] * t20 * t23 * 2.0;
  out2[53] = -t37 + t38;
  out2[54] = t26 - t26_tmp * t20 * t23;
  out2[55] = t131 + b_out2_tmp;
  b_out2_tmp = t26_tmp * t15;
  out2[56] = b_out2_tmp * -2.0;
  out2[57] = t31 + t32;
  out2[58] = t34 + t9 * t20 * t23 * 2.0;
  out2[59] = -t39 + t40;
  out2[60] = t67 - t89 * t18 * t23;
  out2[61] = t89 + t67 * t18 * t23;
  out2[62] = 0.0;
  out2[63] = t35 - t2;
  out2[64] = t37 + t38;
  out2[65] = t33 + in1[4] * t21 * t23 * 2.0;
  out2[66] = out2_tmp - b_out2_tmp * t18 * t23;
  out2[67] = b_out2_tmp + out2_tmp * t18 * t23;
  out2[68] = 0.0;
  out2[69] = t36 - t3;
  out2[70] = t39 + t40;
  out2[71] = t34 + t9 * t21 * t23 * 2.0;
  st.site = &i_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  if (t22 < 0.0) {
    c_st.site = &l_emlrtRSI;
    error(&c_st);
  }

  t41 = 1.0 / muDoubleScalarPower(t22, 1.5);
  t42_tmp = t155 * t9;
  t34 = t42_tmp * t12;
  t39 = t34 * t15 * t18 * t41;
  t43 = t42_tmp - t39;
  st.site = &j_emlrtRSI;
  b_st.site = &k_emlrtRSI;
  t44 = t9 * t9;
  t35 = t34 * t23;
  t47 = t35 + t34 * t20 * t41;
  t2 = t42_tmp * t15;
  t3 = t2 * t23;
  t50 = t3 + t2 * t19 * t41;
  t51_tmp = out2_tmp * t23;
  t53 = t51_tmp + out2_tmp * t20 * t41;
  t56 = t3 * 3.0 + t2 * t20 * t41;
  t57_tmp = in1[16] * t12;
  b_t57_tmp = t57_tmp * t23 * t44;
  t59 = b_t57_tmp + t57_tmp * t20 * t41 * t44;
  t37 = t42_tmp * t18;
  t38 = t37 * t23;
  t62 = t38 + t37 * t20 * t41;
  t40 = t152 * t18 * t41;
  t64 = t26_tmp - t40;
  t66_tmp = b_out2_tmp * t23;
  t67 = t131 * t23;
  t69 = t67 + t131 * t20 * t41;
  t70_tmp = in1[16] * t44;
  t89 = t57_tmp * t15 * t18 * t41 * t44;
  t71 = t70_tmp - t89;
  t73 = t3 + t2 * t21 * t41;
  t74_tmp = in1[16] * t15;
  b_t74_tmp = t74_tmp * t23 * t44;
  t2 = in1[16] * t18;
  t3 = t2 * t23 * t44;
  t77 = t3 + t2 * t20 * t41 * t44;
  t79 = t66_tmp + b_out2_tmp * t19 * t41;
  t82 = t35 * 3.0 + t34 * t19 * t41;
  t84 = b_t74_tmp + t74_tmp * t19 * t41 * t44;
  t86 = t38 + t37 * t19 * t41;
  t88 = t42_tmp + t39;
  t90 = t26_tmp + t40;
  t92 = t67 + t131 * t19 * t41;
  t93 = t70_tmp + t89;
  t95 = t35 + t34 * t21 * t41;
  t97 = t3 + t2 * t19 * t41 * t44;
  t38 = t132 * t12;
  t35 = t38 * t23 * 2.0;
  t100 = t35 + t38 * t19 * t41 * 2.0;
  t34 = t132 * t15;
  t36 = t34 * t23 * 2.0;
  t2 = t34 * t19 * t41 * 2.0;
  t103 = t36 + t2;
  t25 = t132 * t18;
  t26 = t25 * t23 * 2.0;
  t39 = t25 * t19 * t41 * 2.0;
  t106 = t26 + t39;
  t107 = t32_tmp * t23 * 2.0;
  t108 = t40_tmp * t23 * 2.0;
  t109 = t40_tmp * t19 * t41 * 2.0;
  t3 = t132 * 2.0;
  t37 = t38 * t15 * t18 * t41 * 2.0;
  t111 = t3 - t37;
  t40 = t38 * t20 * t41 * 2.0;
  t113 = t35 + t40;
  t114 = t36 - t2;
  t115 = t12 * t23 * t44 * 2.0;
  t116 = t15 * t23 * t44 * 2.0;
  t117 = t15 * t19 * t41 * t44 * 2.0;
  t118 = t9 * 2.0;
  t120 = t31_tmp * t23 * 2.0;
  t121 = t31_tmp * t19 * t41 * 2.0;
  t122 = t3 + t37;
  t123 = t44 * 2.0;
  t38 = t38 * t21 * t41 * 2.0;
  t125 = t35 + t38;
  t126 = t26 - t39;
  t127 = t18 * t23 * t44 * 2.0;
  t128 = t18 * t19 * t41 * t44 * 2.0;
  t3 = t147 * t18 * t41 * 2.0;
  t130 = t118 + t3;
  t131 = t32_tmp * t20 * t41 * 2.0;
  t132 = t108 + t109;
  t37 = t12 * t15 * t18 * t41 * t44 * 2.0;
  t134 = t123 + t37;
  t135 = t35 - t40;
  t136 = t12 * t20 * t41 * t44 * 2.0;
  t137 = t116 + t117;
  t138 = t107 + t131;
  t140 = t36 + t34 * t20 * t41 * 2.0;
  t141 = t115 + t136;
  t2 = t25 * t20 * t41 * 2.0;
  t143 = t26 + t2;
  t144 = t31_tmp * t20 * t41 * 2.0;
  t39 = t34 * t21 * t41 * 2.0;
  t146 = t36 + t39;
  t147 = t26 - t2;
  t148 = t18 * t20 * t41 * t44 * 2.0;
  t23 = t118 - t3;
  t2 = t32_tmp * t21 * t41 * 2.0;
  t3 = t120 + t121;
  t152 = t123 - t37;
  t33 = t35 - t38;
  t22 = t12 * t21 * t41 * t44 * 2.0;
  t155 = t127 + t128;
  t67 = t40_tmp * t21 * t41 * 2.0;
  t89 = t120 + t144;
  t27 = t36 - t39;
  t29 = t15 * t21 * t41 * t44 * 2.0;
  t30 = t127 + t148;
  t31 = t107 + t2;
  t32 = t108 + t67;
  t39 = t26 + t25 * t21 * t41 * 2.0;
  t40 = t115 + t22;
  t34 = t116 + t29;
  memset(&out3[0], 0, 36U * sizeof(real_T));
  t35 = t47 * in2[21];
  t36 = t50 * in2[19];
  t25 = t53 * in2[20];
  t26 = t79 * in2[18];
  out3[36] = ((((t43 * in2[23] - t35) - t36) - t25) + t64 * in2[22]) - t26;
  out3[37] = ((((t50 * in2[21] + t79 * in2[20]) + t82 * in2[19]) + t86 * in2[23])
              + t92 * in2[22]) + in2[18] * (t51_tmp * 3.0 + out2_tmp * t19 * t41);
  out3[38] = t26_tmp * in2[18] * -2.0 - t42_tmp * in2[19] * 2.0;
  out3[39] = ((((t100 * in2[19] + t103 * in2[21]) + t106 * in2[23]) + t132 *
               in2[20]) + t3 * in2[22]) + in2[18] * (t107 + t32_tmp * t19 * t41 *
    2.0);
  out3[40] = ((((t103 * in2[19] + t122 * in2[23]) + t132 * in2[18]) + t130 *
               in2[22]) - t135 * in2[21]) - in2[20] * (t107 - t131);
  out3[41] = ((((t106 * in2[19] - t111 * in2[21]) - t23 * in2[20]) + t3 * in2[18])
              - t33 * in2[23]) - in2[22] * (t107 - t2);
  t2 = t47 * in2[20];
  t3 = t50 * in2[18];
  t37 = t59 * in2[21];
  t38 = t84 * in2[19];
  out3[42] = ((((t43 * in2[22] - t2) - t3) - t37) + t71 * in2[23]) - t38;
  out3[43] = ((((t50 * in2[20] + t82 * in2[18]) + t84 * in2[21]) + t86 * in2[22])
              + t97 * in2[23]) + in2[19] * (b_t57_tmp * 3.0 + t57_tmp * t19 *
    t41 * t44);
  out3[44] = t70_tmp * in2[19] * -2.0 - t42_tmp * in2[18] * 2.0;
  out3[45] = ((((t100 * in2[18] + t103 * in2[20]) + t106 * in2[22]) + t137 *
               in2[21]) + t155 * in2[23]) + in2[19] * (t115 + t12 * t19 * t41 *
    t44 * 2.0);
  out3[46] = ((((t103 * in2[18] + t122 * in2[22]) - t135 * in2[20]) + t137 *
               in2[19]) + t134 * in2[23]) - in2[21] * (t115 - t136);
  out3[47] = ((((t106 * in2[18] - t111 * in2[20]) - t152 * in2[21]) + t155 *
               in2[19]) - t33 * in2[22]) - in2[23] * (t115 - t22);
  out3[48] = ((((-t47 * in2[19] - t53 * in2[18]) - t56 * in2[21]) - t62 * in2[23])
              - t69 * in2[22]) - in2[20] * (t66_tmp * 3.0 + b_out2_tmp * t20 *
    t41);
  out3[49] = ((((t35 + t36) + t25) + t26) + t88 * in2[23]) + t90 * in2[22];
  out3[50] = t26_tmp * in2[20] * -2.0 - t42_tmp * in2[21] * 2.0;
  out3[51] = ((((-t114 * in2[19] - t111 * in2[23]) + t113 * in2[21]) + t138 *
               in2[20]) - in2[22] * (t118 - t9 * t12 * t15 * t18 * t41 * 2.0)) -
    in2[18] * (t108 - t109);
  out3[52] = ((((t113 * in2[19] + t138 * in2[18]) + t140 * in2[21]) + t143 *
               in2[23]) + t89 * in2[22]) + in2[20] * (t108 + t40_tmp * t20 * t41
    * 2.0);
  out3[53] = ((((t122 * in2[19] + t130 * in2[18]) + t143 * in2[21]) + t89 * in2
               [20]) - t27 * in2[23]) - in2[22] * (t108 - t67);
  out3[54] = ((((-t47 * in2[18] - t56 * in2[20]) - t59 * in2[19]) - t62 * in2[22])
              - t77 * in2[23]) - in2[21] * (b_t74_tmp * 3.0 + t74_tmp * t20 *
    t41 * t44);
  out3[55] = ((((t2 + t3) + t37) + t38) + t88 * in2[22]) + t93 * in2[23];
  out3[56] = t70_tmp * in2[21] * -2.0 - t42_tmp * in2[20] * 2.0;
  out3[57] = ((((-t114 * in2[18] - t111 * in2[22]) + t113 * in2[20]) + t141 *
               in2[21]) - in2[23] * (t123 - t12 * t15 * t18 * t41 * t44 * 2.0))
    - in2[19] * (t116 - t117);
  out3[58] = ((((t113 * in2[18] + t140 * in2[20]) + t141 * in2[19]) + t143 *
               in2[22]) + t30 * in2[23]) + in2[21] * (t116 + t15 * t20 * t41 *
    t44 * 2.0);
  out3[59] = ((((t122 * in2[18] + t134 * in2[19]) + t143 * in2[20]) - t27 * in2
               [22]) + t30 * in2[21]) - in2[23] * (t116 - t29);
  out3[60] = ((((-in2[22] * (t66_tmp + b_out2_tmp * t21 * t41) + t43 * in2[19])
                + t64 * in2[18]) - t62 * in2[21]) - t69 * in2[20]) - t73 * in2
    [23];
  out3[61] = ((((in2[22] * (t51_tmp + out2_tmp * t21 * t41) + t86 * in2[19]) +
                t88 * in2[21]) + t90 * in2[20]) + t92 * in2[18]) + t95 * in2[23];
  out3[62] = 0.0;
  out3[63] = ((((t122 * in2[21] - t126 * in2[19]) + t125 * in2[23]) + t130 *
               in2[20]) + t31 * in2[22]) - in2[18] * (t120 - t121);
  out3[64] = ((((-t111 * in2[19] - t23 * in2[18]) - t147 * in2[21]) + t146 *
               in2[23]) + t32 * in2[22]) - in2[20] * (t120 - t144);
  out3[65] = ((((t125 * in2[19] + t146 * in2[21]) + t31 * in2[18]) + t32 * in2
               [20]) + t39 * in2[23]) + in2[22] * (t120 + t31_tmp * t21 * t41 *
    2.0);
  out3[66] = ((((-in2[23] * (b_t74_tmp + t74_tmp * t21 * t41 * t44) + t43 * in2
                 [18]) - t62 * in2[20]) + t71 * in2[19]) - t73 * in2[22]) - t77 *
    in2[21];
  out3[67] = ((((in2[23] * (b_t57_tmp + t57_tmp * t21 * t41 * t44) + t86 * in2
                 [18]) + t88 * in2[20]) + t93 * in2[21]) + t97 * in2[19]) + t95 *
    in2[22];
  out3[68] = 0.0;
  out3[69] = ((((t122 * in2[20] - t126 * in2[18]) + t125 * in2[22]) + t134 *
               in2[21]) + t40 * in2[23]) - in2[19] * (t127 - t128);
  out3[70] = ((((-t111 * in2[18] - t147 * in2[20]) + t146 * in2[22]) - t152 *
               in2[19]) + t34 * in2[23]) - in2[21] * (t127 - t148);
  out3[71] = ((((t125 * in2[18] + t146 * in2[20]) + t40 * in2[19]) + t39 * in2
               [22]) + t34 * in2[21]) + in2[23] * (t127 + t18 * t21 * t41 * t44 *
    2.0);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF2.c) */
