/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_kF.c
 *
 * Code generation for function 'fj_kF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "fj_kF.h"

/* Function Definitions */
void fj_kF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
           real_T s, real_T fj_k[18])
{
  real_T t2;
  real_T a;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t14_tmp_tmp;
  real_T t16;
  (void)sp;
  (void)s;

  /* FJ_KF */
  /*     FJ_K = FJ_KF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 00:06:13 */
  t2 = 1.0 / in1[33];
  a = muDoubleScalarCos(in1[20]);
  t4 = 1.0 / in1[4];
  t5 = in1[2] * in1[2];
  t6 = in1[3] * in1[3];
  t9 = in1[18] * in1[18];
  t10 = muDoubleScalarSin(in1[20]);
  t11 = 1.0 / (t10 * t10);
  t14_tmp_tmp = in1[33] * in1[33];
  a = t14_tmp_tmp * (a * a);
  t16 = t2 * (t5 - t6) - t9 * t11 * (a - 1.0) * 6.0;
  t5 = 1.0 / t14_tmp_tmp * (t5 * t5 - t6 * t6) + t9 * t9 * (1.0 /
    muDoubleScalarPower(t10, 4.0)) * ((a - 1.0) * (a - 1.0)) * 6.0;
  a = t5 * 3.1415926535897931 / 4.0 - t2 * t9 * t11 * (a - 1.0) * (in1[19] *
    in1[19]) * 3.1415926535897931 * 3.0;
  fj_k[0] = in1[1] * in2[0] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[1] = in1[1] * in2[1] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[2] = in1[1] * in2[2] * t2 * t4 * t16 * 3.1415926535897931 * 3.0;
  fj_k[3] = in1[1] * in2[3] * t2 * t4 * a * 3.0;
  fj_k[4] = in1[1] * in2[4] * t2 * t4 * a * 3.0;
  fj_k[5] = in1[1] * in2[5] * t2 * t4 * t5 * 3.1415926535897931 / 2.0;
  fj_k[6] = in1[1] * in2[6] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[7] = in1[1] * in2[7] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[8] = in1[1] * in2[8] * t2 * t4 * t16 * 3.1415926535897931 * 3.0;
  fj_k[9] = in1[1] * in2[9] * t2 * t4 * a * 3.0;
  fj_k[10] = in1[1] * in2[10] * t2 * t4 * a * 3.0;
  fj_k[11] = in1[1] * in2[11] * t2 * t4 * t5 * 3.1415926535897931 / 2.0;
  fj_k[12] = in1[1] * in2[12] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[13] = in1[1] * in2[13] * t2 * t4 * t16 * 3.1415926535897931;
  fj_k[14] = in1[1] * in2[14] * t2 * t4 * t16 * 3.1415926535897931 * 3.0;
  fj_k[15] = in1[1] * in2[15] * t2 * t4 * a * 3.0;
  fj_k[16] = in1[1] * in2[16] * t2 * t4 * a * 3.0;
  fj_k[17] = in1[1] * in2[17] * t2 * t4 * t5 * 3.1415926535897931 / 2.0;
}

/* End of code generation (fj_kF.c) */
