/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF20.c
 *
 * Code generation for function 'sprdmpF20'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF20.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo sd_emlrtRSI = { 57, /* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo td_emlrtRSI = { 63, /* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo xd_emlrtRSI = { 93, /* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo yd_emlrtRSI = { 105,/* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo te_emlrtRSI = { 310,/* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo ue_emlrtRSI = { 311,/* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

static emlrtRSInfo we_emlrtRSI = { 314,/* lineNo */
  "sprdmpF20",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF20.m"/* pathName */
};

/* Function Definitions */
void sprdmpF20(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
               real_T out1[108], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13_tmp;
  real_T t211;
  real_T t15_tmp;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t245;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t216;
  real_T t25;
  real_T t164;
  real_T t165;
  real_T t213;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t184;
  real_T t185;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t51_tmp;
  real_T b_t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t242;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t57;
  real_T t59;
  real_T t60;
  real_T t61;
  real_T t64;
  real_T t65;
  real_T t66;
  real_T t236;
  real_T t69_tmp;
  real_T t71;
  real_T t72_tmp;
  real_T t73_tmp;
  real_T t74_tmp;
  real_T t75_tmp;
  real_T t86;
  real_T t89;
  real_T t93;
  real_T t97;
  real_T t98;
  real_T t99;
  real_T t100;
  real_T t101;
  real_T t102;
  real_T t113_tmp;
  real_T t113;
  real_T t117;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t128;
  real_T t129;
  real_T t130;
  real_T t131;
  real_T t132;
  real_T t133;
  real_T t134_tmp;
  real_T b_t134_tmp;
  real_T t134;
  real_T t143_tmp;
  real_T t143;
  real_T t146;
  real_T t156;
  real_T t160;
  real_T t161;
  real_T t162;
  real_T t163;
  real_T t176;
  real_T t179;
  real_T t188;
  real_T t190;
  real_T t193;
  real_T t196;
  real_T t199;
  real_T t203;
  real_T t207;
  real_T t215;
  real_T t219;
  real_T t220;
  real_T t222;
  real_T t225;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF20 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF20(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 18:52:15 */
  t2 = in2[4] * in2[4];
  t3 = in2[5] * in2[5];
  t4 = in2[3] * in2[3];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &sd_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[5] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[3] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &td_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t13_tmp = in2[1] - in2[7];
  t211 = in2[2] - in2[8];
  t15_tmp = in2[0] - in2[6];
  t17_tmp = in2[3] * t12;
  t17 = (-in2[2] + in2[8]) + t17_tmp * t13_tmp;
  t19 = t13_tmp + t17_tmp * t211;
  t20 = t6 * t13_tmp;
  t245 = in2[3] * t211;
  t22_tmp = in2[3] * t13_tmp;
  t23_tmp = t6 * t211;
  t216 = in2[4] * t15_tmp;
  t25 = t6 * t15_tmp;
  t164 = in2[5] * t13_tmp;
  t165 = in2[4] * t211;
  t213 = t25 + t164;
  t27 = t213 - t165;
  t29_tmp = in2[4] * t12;
  t29 = (-in2[0] + in2[6]) + t29_tmp * t211;
  t31 = t211 + t29_tmp * t15_tmp;
  t184 = in2[5] * t15_tmp;
  t185 = t20 + t245;
  t32 = t185 - t184;
  t34 = (-t22_tmp + t23_tmp) + t216;
  t35 = in2[11] * 2.0;
  t36 = in2[3] - in2[9];
  t5 = ((-(in2[9] * in2[9]) - in2[10] * in2[10]) - in2[11] * in2[11]) + 1.0;
  t41 = t5;
  st.site = &xd_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[4] - in2[10];
  t43 = in2[5] - in2[11];
  t46_tmp = in2[5] * t12;
  t46 = t15_tmp + t46_tmp * t13_tmp;
  t48 = (-in2[1] + in2[7]) + t46_tmp * t15_tmp;
  t49 = in2[9] * 2.0;
  t50_tmp = in2[4] * t6 * 2.0;
  t51_tmp = in2[3] * in2[4];
  b_t51_tmp = t51_tmp * 2.0;
  t52_tmp = in2[3] * in2[5];
  t52 = t52_tmp * 2.0;
  t242 = in2[4] * in2[5];
  t53_tmp = t242 * 2.0;
  st.site = &yd_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[4] * 2.0;
  t57 = 1.0 / in1[33];
  t5 = muDoubleScalarCos(in1[20]);
  t59 = 1.0 / in1[4];
  t60 = in1[2] * in1[2];
  t61 = in1[3] * in1[3];
  t64 = in1[18] * in1[18];
  t65 = muDoubleScalarSin(in1[20]);
  t66 = 1.0 / (t65 * t65);
  t236 = in1[33] * in1[33];
  t69_tmp = t236 * (t5 * t5);
  t71 = t57 * (t60 - t61) - t64 * t66 * (t69_tmp - 1.0) * 6.0;
  t72_tmp = in2[3] * t15_tmp;
  t73_tmp = in2[4] * t13_tmp;
  t74_tmp = in2[5] * t211;
  t75_tmp = (t72_tmp + t73_tmp) + t74_tmp;
  t86 = 1.0 / t236 * (t60 * t60 - t61 * t61) + t64 * t64 * (1.0 /
    muDoubleScalarPower(t65, 4.0)) * ((t69_tmp - 1.0) * (t69_tmp - 1.0)) * 6.0;
  t89 = t6 - t41;
  t60 = t242 * t12;
  t93 = (((((t23_tmp + t216) + t6 * t31) + t29_tmp * t27) + t60 * t13_tmp) -
         in2[4] * t29) - t22_tmp * 2.0;
  t97 = (((((-t20 + t184) + t6 * t48) + in2[5] * t46) + t46_tmp * t27) - t245 *
         2.0) - t60 * t211;
  t98 = (t8 + t11) - 1.0;
  t99 = t7 + b_t51_tmp;
  t100 = t50_tmp - t52;
  t101 = in2[5] * t17;
  t102 = t17_tmp * t27;
  t113_tmp = in2[4] * t19;
  t113 = ((t75_tmp - t101) - t102) + t113_tmp;
  t117 = muDoubleScalarPower(muDoubleScalarAbs((((((((t93 * in2[22] + t97 * in2
    [23]) + t98 * in2[18]) + t100 * in2[20]) + t99 * in2[25]) - t98 * in2[24]) -
    t99 * in2[19]) - t100 * in2[26]) - t113 * in2[21]), in1[11] - 1.0);
  t122 = t6 * t17;
  t123 = in2[3] * t19;
  t124 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t128 = ((((t213 + t6 * t46) + t46_tmp * t32) + t5 * t211) - in2[5] * t48) -
    t165 * 2.0;
  t129 = (t8 + t10) - 1.0;
  t130 = t9 + t53_tmp;
  t131 = t7 - b_t51_tmp;
  t132 = in2[3] * t29;
  t133 = t29_tmp * t32;
  t134_tmp = t216 * 2.0;
  b_t134_tmp = t5 * t15_tmp;
  t134 = (((((t22_tmp - t23_tmp) + t122) + t123) + t124) - t134_tmp) -
    b_t134_tmp;
  t143_tmp = in2[5] * t31;
  t143 = ((t75_tmp - t132) - t133) + t143_tmp;
  t146 = muDoubleScalarPower(muDoubleScalarAbs((((((((t134 * in2[21] + t128 *
    in2[23]) + t129 * in2[19]) + t131 * in2[18]) + t130 * in2[26]) - t129 * in2
    [25]) - t130 * in2[20]) - t131 * in2[24]) - t143 * in2[22]), in1[11] - 1.0);
  t236 = t51_tmp * t12;
  t156 = ((((t185 + t6 * t19) + t17_tmp * t34) + t236 * t15_tmp) - in2[3] * t17)
    - t184 * 2.0;
  t160 = (((((-t25 + t165) + t6 * t29) + in2[4] * t31) + t29_tmp * t34) - t164 *
          2.0) - t236 * t13_tmp;
  t161 = (t10 + t11) - 1.0;
  t162 = t50_tmp + t52;
  t163 = t9 - t53_tmp;
  t164 = in2[4] * t48;
  t165 = t46_tmp * t34;
  t19 = in2[3] * t46;
  t176 = ((t75_tmp - t164) - t165) + t19;
  t179 = muDoubleScalarPower(muDoubleScalarAbs((((((((t156 * in2[21] + t160 *
    in2[22]) + t161 * in2[20]) + t163 * in2[19]) + t162 * in2[24]) - t161 * in2
    [26]) - t162 * in2[18]) - t163 * in2[25]) - t176 * in2[23]), in1[11] - 1.0);
  t184 = t17_tmp * t36 * 2.0;
  t185 = t29_tmp * t36 * 2.0;
  t29 = in2[10] * 2.0;
  t13_tmp = t5 * 2.0;
  t188 = (t29 + t46_tmp * t36 * 2.0) - t13_tmp;
  t190 = t55 + in2[3] * in2[9] * t54 * 2.0;
  t5 = in2[5] * 2.0;
  t193 = t5 + in2[3] * in2[10] * t54 * 2.0;
  t17 = in2[3] * in2[11] * t54 * 2.0;
  t51_tmp = t236 * 2.0;
  t196 = (t35 - t185) + t51_tmp;
  t25 = t41 * 2.0;
  t245 = t4 * t12 * 2.0;
  t199 = (-t184 + t25) + t245;
  t203 = t56 - t17;
  t207 = muDoubleScalarPower(muDoubleScalarAbs(((((t199 * in2[21] + t196 * in2
    [22]) + t203 * in2[29]) - t188 * in2[23]) - t190 * in2[27]) - t193 * in2[28]),
    in1[11] - 1.0);
  t211 = t29_tmp * t42 * 2.0;
  t20 = t17_tmp * t42 * 2.0;
  t213 = t46_tmp * t42 * 2.0;
  t215 = t55 + in2[4] * in2[10] * t54 * 2.0;
  t216 = in2[4] * in2[9] * t54 * 2.0;
  t31 = in2[3] * 2.0;
  t219 = t31 + in2[4] * in2[11] * t54 * 2.0;
  t220 = (t35 - t51_tmp) + t20;
  t65 = t2 * t12 * 2.0;
  t222 = (t25 - t211) + t65;
  t15_tmp = t60 * 2.0;
  t225 = (t49 - t213) + t15_tmp;
  t4 = t5 - t216;
  t2 = muDoubleScalarPower(muDoubleScalarAbs(((((t222 * in2[22] + t225 * in2[23])
    + t4 * in2[27]) - t220 * in2[21]) - t215 * in2[28]) - t219 * in2[29]), in1
    [11] - 1.0);
  t61 = t46_tmp * t43 * 2.0;
  t236 = t17_tmp * t43 * 2.0;
  t60 = t29_tmp * t43 * 2.0;
  t48 = t55 + in2[5] * in2[11] * t54 * 2.0;
  t46 = t56 + in2[5] * in2[9] * t54 * 2.0;
  t242 = in2[5] * in2[10] * t54 * 2.0;
  out1[0] = t98;
  out1[1] = -t7 - b_t51_tmp;
  out1[2] = t50_tmp - in2[3] * in2[5] * 2.0;
  out1[3] = ((((t101 + t102) - t73_tmp) - t72_tmp) - t74_tmp) - t113_tmp;
  out1[4] = t93;
  out1[5] = t97;
  out1[6] = (-t8 - t11) + 1.0;
  out1[7] = t99;
  out1[8] = -t50_tmp + t52;
  memset(&out1[9], 0, 9U * sizeof(real_T));
  out1[18] = t7 - in2[3] * in2[4] * 2.0;
  out1[19] = t129;
  out1[20] = -t9 - t53_tmp;
  out1[21] = (((((t22_tmp + t122) + t123) + t124) - t134_tmp) - t23_tmp) -
    b_t134_tmp;
  out1[22] = ((((t132 + t133) - t73_tmp) - t72_tmp) - t74_tmp) - t143_tmp;
  out1[23] = t128;
  out1[24] = -t7 + b_t51_tmp;
  out1[25] = (-t8 - t10) + 1.0;
  out1[26] = t130;
  memset(&out1[27], 0, 9U * sizeof(real_T));
  out1[36] = t52_tmp * -2.0 - t50_tmp;
  out1[37] = t9 - in2[4] * in2[5] * 2.0;
  out1[38] = t161;
  out1[39] = t156;
  out1[40] = t160;
  out1[41] = ((((t164 + t165) - t73_tmp) - t72_tmp) - t74_tmp) - t19;
  out1[42] = t162;
  out1[43] = -t9 + t53_tmp;
  out1[44] = (-t10 - t11) + 1.0;
  memset(&out1[45], 0, 12U * sizeof(real_T));
  out1[57] = (t41 * -2.0 + t184) - t245;
  out1[58] = (-t35 + t185) - t51_tmp;
  out1[59] = t188;
  out1[60] = 0.0;
  out1[61] = 0.0;
  out1[62] = 0.0;
  out1[63] = t190;
  out1[64] = t193;
  out1[65] = -t56 + t17;
  memset(&out1[66], 0, 9U * sizeof(real_T));
  out1[75] = (t35 + t20) - t51_tmp;
  out1[76] = (t41 * -2.0 + t211) - t65;
  out1[77] = (-t49 + t213) - t15_tmp;
  out1[78] = 0.0;
  out1[79] = 0.0;
  out1[80] = 0.0;
  out1[81] = in2[5] * -2.0 + t216;
  out1[82] = t215;
  out1[83] = t219;
  memset(&out1[84], 0, 9U * sizeof(real_T));
  out1[93] = (in2[10] * -2.0 + t236) - t13_tmp;
  out1[94] = (t49 + t60) - t15_tmp;
  t5 = t3 * t12 * 2.0;
  out1[95] = (t41 * -2.0 + t61) - t5;
  out1[96] = 0.0;
  out1[97] = 0.0;
  out1[98] = 0.0;
  out1[99] = t46;
  out1[100] = in2[3] * -2.0 + t242;
  out1[101] = t48;
  out1[102] = 0.0;
  out1[103] = 0.0;
  out1[104] = 0.0;
  out1[105] = 0.0;
  out1[106] = 0.0;
  out1[107] = 0.0;
  t213 = (t29 + t13_tmp) - t236;
  t245 = (t25 - t61) + t5;
  t20 = (t49 - t15_tmp) + t60;
  t236 = t31 - t242;
  t242 = muDoubleScalarPower(muDoubleScalarAbs(((((t245 * in2[23] + t213 * in2
    [21]) + t236 * in2[28]) - t20 * in2[22]) - t48 * in2[29]) - t46 * in2[27]),
    in1[11] - 1.0);
  t5 = in1[33];
  st.site = &te_emlrtRSI;
  b_sqrt(&st, &t5);
  t211 = 1.0 / t5;
  t5 = 70.0;
  st.site = &ue_emlrtRSI;
  b_sqrt(&st, &t5);
  t5 = in1[4] * in1[4] / 9.0;
  st.site = &we_emlrtRSI;
  b_sqrt(&st, &t5);
  t65 = -in1[1] * t57 * t59 * t71 * 3.1415926535897931;
  out2[0] = t65 * (((in2[5] * t32 - in2[4] * t34) + in2[3] * t75_tmp) + t6 * t27);
  out2[1] = t65 * (((-in2[5] * t27 + in2[3] * t34) + in2[4] * t75_tmp) + t6 *
                   t32);
  t65 = in1[1] * t57 * t59;
  out2[2] = t65 * t71 * 3.1415926535897931 * ((((t5 + in2[4] * t27) - in2[3] *
    t32) + in2[5] * t75_tmp) + t6 * t34) * -3.0;
  t5 = t65 * (t86 * 3.1415926535897931 / 4.0 - t57 * t64 * t66 * (t69_tmp - 1.0)
              * (in1[19] * in1[19]) * 3.1415926535897931 * 3.0);
  out2[3] = t5 * (((in2[4] * t43 * 2.0 - in2[5] * t42 * 2.0) + in2[3] * t89 *
                   2.0) - t6 * t36 * 2.0) * 3.0;
  out2[4] = t5 * (((in2[5] * t36 * 2.0 - in2[3] * t43 * 2.0) + in2[4] * t89 *
                   2.0) - t6 * t42 * 2.0) * 3.0;
  out2[5] = t65 * t86 * 3.1415926535897931 * (((in2[4] * t36 * 2.0 - in2[3] *
    t42 * 2.0) - in2[5] * t89 * 2.0) + t6 * t43 * 2.0) * -0.5;
  t61 = in1[5] * t98 * t117;
  t60 = in1[5] * t99 * t117;
  t5 = in1[5] * t100 * t117;
  out3[0] = (((((((-in1[5] * t93 * t117 * in2[22] - t61 * in2[18]) + t60 * in2
                  [19]) - in1[5] * t97 * t117 * in2[23]) - t5 * in2[20]) + t61 *
               in2[24]) - t60 * in2[25]) + t5 * in2[26]) + in1[5] * t113 * t117 *
    in2[21];
  t61 = in1[6] * t131 * t146;
  t60 = in1[6] * t130 * t146;
  out3[1] = (((((((-in1[6] * t129 * t146 * in2[19] - t61 * in2[18]) + t60 * in2
                  [20]) - in1[6] * t128 * t146 * in2[23]) + in1[6] * t129 * t146
                * in2[25]) + t61 * in2[24]) - in1[6] * t134 * t146 * in2[21]) -
             t60 * in2[26]) + in1[6] * t143 * t146 * in2[22];
  t61 = in1[7] * t162 * t179;
  t60 = in1[7] * t161 * t179;
  t5 = in1[7] * t163 * t179;
  out3[2] = (((((((-in1[7] * t156 * t179 * in2[21] + t61 * in2[18]) - t60 * in2
                  [20]) - in1[7] * t160 * t179 * in2[22]) - t5 * in2[19]) - t61 *
               in2[24]) + t60 * in2[26]) + t5 * in2[25]) + in1[7] * t176 * t179 *
    in2[23];
  out3[3] = ((((-in1[8] * t188 * t207 * in2[23] - in1[8] * t190 * t207 * in2[27])
               + in1[8] * t196 * t207 * in2[22]) + in1[8] * t199 * t207 * in2[21])
             - in1[8] * t193 * t207 * in2[28]) + in1[8] * t203 * t207 * in2[29];
  out3[4] = ((((-in1[9] * t220 * t2 * in2[21] - in1[9] * t215 * t2 * in2[28]) +
               in1[9] * t222 * t2 * in2[22]) - in1[9] * t219 * t2 * in2[29]) +
             in1[9] * t225 * t2 * in2[23]) + in1[9] * t4 * t2 * in2[27];
  out3[5] = ((((in1[10] * t213 * t242 * in2[21] - in1[10] * t48 * t242 * in2[29])
               - in1[10] * t46 * t242 * in2[27]) + in1[10] * t245 * t242 * in2
              [23]) - in1[10] * t20 * t242 * in2[22]) + in1[10] * t236 * t242 *
    in2[28];
  out4[0] = 0.0;
  out4[1] = 0.0;
  out4[2] = -t64 * t66 * (t69_tmp - 1.0) * 3.1415926535897931 * (((((in1[21] +
    in1[22]) + in1[23]) + in1[24]) + in1[25]) + in1[26]);
  t60 = in1[23] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211 *
    3.1415926535897931;
  t61 = in1[24] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211 *
    3.1415926535897931;
  t65 = in1[25] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211 *
    3.1415926535897931;
  t236 = in1[26] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211 *
    3.1415926535897931;
  t242 = in1[21] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211;
  t5 = in1[22] * in1[19] * t64 * t66 * (t69_tmp - 1.0) * t211;
  out4[3] = ((((t242 * 3.1415926535897931 * -0.93771626297577859 - t5 *
                3.1415926535897931 * 0.93771626297577859) + t60 *
               0.167999098695029) + t61 * 0.76971716428074954) + t65 *
             0.76971716428074932) + t236 * 0.16799909869502891;
  out4[4] = ((((t60 * 0.9857871488499218 + t61 * 0.63838506170774523) - t65 *
               0.63838506170774545) - t236 * 0.9857871488499218) - t242 *
             8.3666002653407556 * 3.1415926535897931 * 0.041522491349480967) +
    t5 * 8.3666002653407556 * 3.1415926535897931 * 0.041522491349480967;
  out4[5] = 0.0;
}

/* End of code generation (sprdmpF20.c) */
