/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_inF.c
 *
 * Code generation for function 'fj_inF'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "fj_inF.h"

/* Function Definitions */
void fj_inF(const real_T in1[34], const real_T in2[24], real_T s, real_T fj_in
            [12])
{
  (void)in1;
  (void)in2;
  (void)s;

  /* FJ_INF */
  /*     FJ_IN = FJ_INF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 15:17:25 */
  memset(&fj_in[0], 0, 12U * sizeof(real_T));
}

/* End of code generation (fj_inF.c) */
