/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF4.c
 *
 * Code generation for function 'massF4'
 *
 */

/* Include files */
#include "massF4.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void massF4(const real_T in1[60], const real_T in2[48], real_T s, real_T out1[36],
            real_T out2[144], real_T out3[144], real_T out4[6])
{
  real_T t15_tmp;
  real_T t18;
  real_T t2;
  real_T t21;
  real_T t22;
  real_T t3;
  real_T t4;
  real_T t5;

  /* MASSF4 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF4(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     10-Mar-2021 20:34:30 */
  t2 = in1[7] * in1[7];
  t3 = in1[8] * in1[8];
  t4 = s * s;
  t5 = muDoubleScalarPower(s, 3.0);
  t18 = ((in1[49] / 2.0 + in2[19] * s / 2.0) + in2[20] * t4 / 2.0) + in2[21] *
    t5 / 2.0;
  t21 = muDoubleScalarCos(t18);
  t18 = muDoubleScalarSin(t18);
  t15_tmp = -(in1[0] * (t2 + -t3) * 3.1415926535897931);
  t22 = t21 * t21;
  t18 *= t18;
  t21 = t15_tmp * (t2 / 4.0 + t3 / 4.0);
  out1[0] = t15_tmp;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t15_tmp;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t15_tmp;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t21;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t21;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t15_tmp * (t2 / 2.0 + t3 / 2.0);
  memset(&out2[0], 0, 119U * sizeof(real_T));
  out2[119] = s * t22 + s * t18;
  out2[120] = 0.0;
  out2[121] = 0.0;
  out2[122] = 0.0;
  out2[123] = 0.0;
  out2[124] = 0.0;
  out2[125] = t4 * t22 + t4 * t18;
  out2[126] = 0.0;
  out2[127] = 0.0;
  out2[128] = 0.0;
  out2[129] = 0.0;
  out2[130] = 0.0;
  out2[131] = t5 * t22 + t5 * t18;
  memset(&out2[132], 0, 12U * sizeof(real_T));
  memset(&out3[0], 0, 144U * sizeof(real_T));
  out4[0] = in1[32];
  out4[1] = in1[33];
  out4[2] = in1[34];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF4.c) */
