/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rjtipF.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T s, real_T ds, real_T t_sym, real_T out1[60])
{
  real_T t103;
  real_T t110;
  real_T t111;
  real_T t112;
  real_T t116;
  real_T t120;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t135;
  real_T t135_tmp;
  real_T t136;
  real_T t136_tmp;
  real_T t16;
  real_T t2;
  real_T t20;
  real_T t24;
  real_T t3;
  real_T t33;
  real_T t34;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46;
  real_T t47;
  real_T t48;
  real_T t5;
  real_T t6;
  real_T t96;
  real_T t97;
  real_T t98;
  real_T t99;
  (void)sp;
  (void)s;
  (void)ds;
  (void)t_sym;

  /* RJTIPF */
  /*     OUT1 = RJTIPF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     26-Feb-2021 19:42:04 */
  t2 = in1[33] * in1[3];
  t3 = in1[4] / 3.0;
  t4 = in2[3] / 2.0;
  t5 = in2[4] / 2.0;
  t6 = in2[5] / 2.0;
  t16 = in2[3] * in2[9] / 4.0;
  t20 = in2[4] * in2[10] / 4.0;
  t24 = in2[5] * in2[11] / 4.0;
  t33 = in2[8] + t3;
  t34 = in2[14] + t3;
  t40 = ((t16 + t20) + t24) - 1.0;
  t39 = (in2[7] * t4 + in2[4] * in2[6] * -0.5) + t33;
  t43 = ((-t16 + -t20) + -t24) + 1.0;
  t46 = ((t4 + in2[9] / 2.0) + in2[4] * in2[11] / 4.0) + -(in2[5] * in2[10] /
    4.0);
  t47 = ((t5 + in2[10] / 2.0) + in2[5] * in2[9] / 4.0) + -(in2[3] * in2[11] /
    4.0);
  t48 = ((t6 + in2[11] / 2.0) + in2[3] * in2[10] / 4.0) + -(in2[4] * in2[9] /
    4.0);
  t41 = (in2[7] + in2[6] * t6) + in2[3] * t33 * -0.5;
  t42 = (in2[6] + in2[5] * in2[7] * -0.5) + t5 * t33;
  t33 = (in2[6] * t4 + in2[7] * t5) + t6 * t33;
  t16 = in2[15] * t46 / 2.0;
  t20 = in2[16] * t47 / 2.0;
  t24 = in2[17] * t48 / 2.0;
  t99 = (in2[12] * t46 + in2[13] * t47) + t34 * t48;
  t103 = ((t40 + t16) + t20) + t24;
  t96 = (in2[12] * t47 + -(in2[13] * t46)) + t34 * t40;
  t97 = (in2[12] * t40 + in2[13] * t48) + -(t34 * t47);
  t98 = (in2[13] * t40 + -(in2[12] * t48)) + t34 * t46;
  t110 = ((t46 + -(in2[15] * t40 / 2.0)) + in2[17] * t47 / 2.0) + -(in2[16] *
    t48 / 2.0);
  t111 = ((t47 + -(in2[16] * t40 / 2.0)) + in2[15] * t48 / 2.0) + -(in2[17] *
    t46 / 2.0);
  t112 = ((t48 + -(in2[17] * t40 / 2.0)) + in2[16] * t46 / 2.0) + -(in2[15] *
    t47 / 2.0);
  t116 = t103 * t103;
  t123 = ((t43 + -t16) + -t20) + -t24;
  t120 = t110 * t110;
  t121 = t111 * t111;
  t122 = t112 * t112;
  t16 = in1[4] * t103;
  t135_tmp = (((in2[1] + t41) + t6 * t42) + in2[3] * t39 * -0.5) + t5 * t33;
  t20 = (((t135_tmp + t40 * t98) + t46 * t96) + t47 * t99) + -(t48 * t97);
  t135 = (t20 + t16 * t110 * 0.66666666666666663) + in1[4] * t111 * t112 *
    0.66666666666666663;
  t136_tmp = (((in2[0] + t42) + t5 * t39) + in2[5] * t41 * -0.5) + t4 * t33;
  t24 = (((t136_tmp + t40 * t97) + t48 * t98) + t46 * t99) + -(t47 * t96);
  t136 = (t24 + -(t16 * t111 * 0.66666666666666663)) + in1[4] * t110 * t112 *
    0.66666666666666663;
  t34 = (((in2[2] + t39) + t4 * t41) + in2[4] * t42 * -0.5) + t6 * t33;
  t16 = (((t34 + t40 * t96) + t47 * t97) + t48 * t99) + -(t46 * t98);
  t33 = (((t16 + t3 * t116) + t3 * t122) + in1[4] * t120 * -0.33333333333333331)
    + in1[4] * t121 * -0.33333333333333331;
  out1[0] = in2[0];
  out1[1] = t136_tmp;
  out1[2] = t24;
  out1[3] = t136;
  out1[4] = in2[1];
  out1[5] = t135_tmp;
  out1[6] = t20;
  out1[7] = t135;
  out1[8] = in2[2];
  out1[9] = t34;
  out1[10] = t16;
  out1[11] = t33;
  t20 = in1[4] * in2[3];
  out1[12] = (in2[0] + in2[4] * t3) + t20 * in2[5] / 6.0;
  t24 = in1[4] * t40;
  out1[13] = (t136_tmp - t24 * t47 * 0.66666666666666663) + in1[4] * t46 * t48 *
    0.66666666666666663;
  out1[14] = t136;
  t16 = in1[16] * t103;
  out1[15] = (t136 - t16 * t111 * 2.0) + in1[16] * t110 * t112 * 2.0;
  out1[16] = (in2[1] - t20 / 3.0) + in1[4] * in2[4] * in2[5] / 6.0;
  out1[17] = (t135_tmp + t24 * t46 * 0.66666666666666663) + in1[4] * t47 * t48 *
    0.66666666666666663;
  out1[18] = t135;
  out1[19] = (t135 + t16 * t110 * 2.0) + in1[16] * t111 * t112 * 2.0;
  out1[20] = (((in2[2] + t3) - in1[4] * (in2[3] * in2[3]) / 12.0) - in1[4] *
              (in2[4] * in2[4]) / 12.0) + in1[4] * (in2[5] * in2[5]) / 12.0;
  out1[21] = (((t34 - in1[4] * (t46 * t46) / 3.0) - in1[4] * (t47 * t47) / 3.0)
              + t3 * (t40 * t40)) + t3 * (t48 * t48);
  out1[22] = t33;
  out1[23] = (((t33 + in1[16] * t116) - in1[16] * t120) - in1[16] * t121) + in1
    [16] * t122;
  out1[24] = 1.0;
  out1[25] = t43;
  out1[26] = t123;
  out1[27] = t123;
  out1[28] = t4;
  out1[29] = t46;
  out1[30] = t110;
  out1[31] = t110;
  out1[32] = t5;
  out1[33] = t47;
  out1[34] = t111;
  out1[35] = t111;
  out1[36] = t6;
  out1[37] = t48;
  out1[38] = t112;
  out1[39] = t112;
  out1[40] = 1.0;
  out1[41] = t43;
  out1[42] = t123;
  out1[43] = t123;
  out1[44] = t4;
  out1[45] = t46;
  out1[46] = t110;
  out1[47] = t110;
  out1[48] = t5;
  out1[49] = t47;
  out1[50] = t111;
  out1[51] = t111;
  out1[52] = t6;
  out1[53] = t48;
  out1[54] = t112;
  out1[55] = t112;
  out1[56] = t2;
  out1[57] = t2;
  out1[58] = t2;
  out1[59] = in1[17];
}

/* End of code generation (rjtipF.c) */
