function fj_in = fj_inF(in1,in2,s)
%FJ_INF
%    FJ_IN = FJ_INF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Jan-2019 21:59:39

fj_in = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
