function fj_vd = fj_vdF(in1,in2,s)
%FJ_VDF
%    FJ_VD = FJ_VDF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Jan-2019 21:59:39

fj_vd = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
