/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * EOM.c
 *
 * Code generation for function 'EOM'
 *
 */

/* Include files */
#include "EOM.h"
#include "EOM_types.h"
#include "loadsF1.h"
#include "massF1.h"
#include "massF2.h"
#include "massF3.h"
#include "massF4.h"
#include "mtimes.h"
#include "pinv.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 6,     /* lineNo */
  "EOM",                               /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\EOM.m"/* pathName */
};

static emlrtRSInfo q_emlrtRSI = { 50,  /* lineNo */
  "EOM",                               /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\EOM.m"/* pathName */
};

static emlrtDCInfo emlrtDCI = { 10,    /* lineNo */
  34,                                  /* colNo */
  "dyn_mid_step",                      /* fName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\dyn_mid_step.m",/* pName */
  1                                    /* checkKind */
};

static emlrtBCInfo emlrtBCI = { 1,     /* iFirst */
  1094,                                /* iLast */
  10,                                  /* lineNo */
  34,                                  /* colNo */
  "par_mex.user_pars.f_ex",            /* aName */
  "dyn_mid_step",                      /* fName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\dyn_mid_step.m",/* pName */
  0                                    /* checkKind */
};

/* Function Definitions */
void EOM(const emlrtStack *sp, real_T t, const real_T z[36], const struct0_T
         *par_mex, real_T dz[36], real_T *flag)
{
  static const int8_T iv[6] = { 0, 0, 1, 1, 2, 2 };

  emlrtStack st;
  real_T b_y[324];
  real_T d_y[324];
  real_T f_y[324];
  real_T h_y[324];
  real_T Dd[108];
  real_T T[108];
  real_T Tt[108];
  real_T b_Dd[108];
  real_T c_Dd[108];
  real_T c_y[108];
  real_T d_Dd[108];
  real_T e_y[108];
  real_T g_y[108];
  real_T y[108];
  real_T M[36];
  real_T par_mex_var[34];
  real_T b_par_mex_var[18];
  real_T c_par_mex_var[18];
  real_T dv[18];
  real_T dv1[18];
  real_T dv2[18];
  real_T i_y[18];
  real_T b_fg[6];
  real_T c_fg[6];
  real_T d_fg[6];
  real_T e_Dd[6];
  real_T fg[6];
  real_T ftau_ex[6];
  real_T a_tmp;
  real_T b_t13;
  real_T b_t32;
  real_T b_t32_tmp;
  real_T step;
  real_T t13;
  real_T t20_tmp;
  real_T t32;
  real_T t32_tmp;
  real_T t33;
  real_T t41_tmp;
  real_T t41_tmp_tmp;
  real_T t8;
  real_T t9;
  int32_T i;
  int32_T i1;
  int32_T i2;
  st.prev = sp;
  st.tls = sp->tls;
  st.site = &emlrtRSI;
  memcpy(&par_mex_var[0], &par_mex->var[0], 34U * sizeof(real_T));

  /*  parameters */
  /*  inputs: internal pressure & external forces/torques */
  /*  temp = interp1( par.f_ex(:,1) , [ par.f_ex(:,2:7) par.p(:,2:4) ] , t , 'nearest' ) ; */
  step = muDoubleScalarFloor(t / 0.05);
  if (step == 0.0) {
    step = 1.0;
  }

  if (step != (int32_T)step) {
    emlrtIntegerCheckR2012b(step, &emlrtDCI, &st);
  }

  if (((int32_T)step < 1) || ((int32_T)step > 1094)) {
    emlrtDynamicBoundsCheckR2012b((int32_T)step, 1, 1094, &emlrtBCI, &st);
  }

  /*  cross-section deformation */
  /*  In this case it causes numerical instability, so commented */
  /*  axial stretch */
  /*  l = 0 ; */
  /*  for i = 0 : par_mex.user_pars.n_l - 2 */
  /*      l = l + z(i*6+3) ; */
  /*  end */
  /*  lambda = 1 + l / par_mex.var(5) ; */
  /*  update simulation parameters */
  for (i = 0; i < 6; i++) {
    par_mex_var[i + 21] = par_mex->user_pars.p[((int32_T)step + 1094 * (iv[i] +
      1)) - 1];
    par_mex_var[i + 27] = par_mex->user_pars.f_ex[((int32_T)step + 1094 * (i + 1))
      - 1];
  }

  par_mex_var[33] = 1.0;

  /* FJ_KF */
  /*     OUT1 = FJ_KF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 01:21:25 */
  a_tmp = muDoubleScalarCos(par_mex_var[20]);
  step = muDoubleScalarSin(par_mex_var[20]);
  t32 = par_mex_var[18] * par_mex_var[18];
  t8 = par_mex_var[2] * par_mex_var[2];
  t9 = par_mex_var[3] * par_mex_var[3];
  t13 = 1.0 / par_mex_var[4];
  step = 1.0 / (step * step);
  t20_tmp = a_tmp * a_tmp;
  b_t32 = (t8 + -t9) + -(t32 * step * (t20_tmp - 1.0) * 6.0);
  t33 = (t8 * t8 + -(t9 * t9)) + t32 * t32 * (step * step) * ((t20_tmp - 1.0) *
    (t20_tmp - 1.0)) * 6.0;
  t41_tmp_tmp = par_mex_var[19] * par_mex_var[19] * t32 * step * (t20_tmp - 1.0)
    * 3.1415926535897931;
  t41_tmp = t33 * 3.1415926535897931 / 4.0 + -(t41_tmp_tmp * 3.0);

  /* FJ_VDF */
  /*     OUT1 = FJ_VDF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 01:21:25 */
  /* FJ_INF */
  /*     OUT1 = FJ_INF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 01:21:26 */
  b_t13 = t32 * step * (((((par_mex_var[21] + par_mex_var[22]) + par_mex_var[23])
    + par_mex_var[24]) + par_mex_var[25]) + par_mex_var[26]) * (t20_tmp - 1.0) *
    3.1415926535897931;
  a_tmp = par_mex_var[22] * par_mex_var[19] * t32 * step;
  t8 = par_mex_var[21] * par_mex_var[19] * t32 * step;
  t9 = par_mex_var[23] * par_mex_var[19] * t32 * step * (t20_tmp - 1.0) *
    3.1415926535897931;
  t32_tmp = par_mex_var[24] * par_mex_var[19] * t32 * step * (t20_tmp - 1.0) *
    3.1415926535897931;
  b_t32_tmp = par_mex_var[26] * par_mex_var[19] * t32 * step * (t20_tmp - 1.0) *
    3.1415926535897931;
  step = par_mex_var[25] * par_mex_var[19] * t32 * step * (t20_tmp - 1.0) *
    3.1415926535897931;
  t32 = ((((-(t8 * (t20_tmp - 1.0) * 3.1415926535897931 * 0.93771626297577859) +
            -(a_tmp * (t20_tmp - 1.0) * 3.1415926535897931 * 0.93771626297577859))
           + step * 0.76971716428074932) + t32_tmp * 0.76971716428074954) +
         b_t32_tmp * 0.16799909869502891) + t9 * 0.167999098695029;
  t8 = ((((a_tmp * 8.3666002653407556 * (t20_tmp - 1.0) * 3.1415926535897931 *
           0.041522491349480967 + -(t8 * 8.3666002653407556 * (t20_tmp - 1.0) *
            3.1415926535897931 * 0.041522491349480967)) + t9 *
          0.9857871488499218) + t32_tmp * 0.63838506170774523) + -(b_t32_tmp *
         0.9857871488499218)) + -(step * 0.63838506170774545);
  massF1(par_mex_var, z, M, T, Dd, fg);
  for (i = 0; i < 6; i++) {
    for (i1 = 0; i1 < 18; i1++) {
      Tt[i1 + 18 * i] = T[i + 6 * i1];
    }
  }

  mtimes(Tt, M, y);
  b_mtimes(y, T, b_y);
  mtimes(Tt, M, y);
  massF2(par_mex_var, z, M, T, b_Dd, b_fg);
  for (i = 0; i < 6; i++) {
    for (i1 = 0; i1 < 18; i1++) {
      Tt[i1 + 18 * i] = T[i + 6 * i1];
    }
  }

  mtimes(Tt, M, c_y);
  b_mtimes(c_y, T, d_y);
  mtimes(Tt, M, c_y);
  massF3(par_mex_var, z, M, T, c_Dd, c_fg);
  for (i = 0; i < 6; i++) {
    for (i1 = 0; i1 < 18; i1++) {
      Tt[i1 + 18 * i] = T[i + 6 * i1];
    }
  }

  mtimes(Tt, M, e_y);
  b_mtimes(e_y, T, f_y);
  mtimes(Tt, M, e_y);
  massF4(par_mex_var, z, M, T, d_Dd, d_fg);
  for (i = 0; i < 6; i++) {
    for (i1 = 0; i1 < 18; i1++) {
      Tt[i1 + 18 * i] = T[i + 6 * i1];
    }
  }

  mtimes(Tt, M, g_y);
  b_mtimes(g_y, T, h_y);
  mtimes(Tt, M, g_y);
  loadsF1(par_mex_var, z, T, ftau_ex);

  /*  EOM */
  for (i = 0; i < 324; i++) {
    d_y[i] = ((b_y[i] + d_y[i]) + f_y[i]) + h_y[i];
  }

  st.site = &q_emlrtRSI;
  pinv(&st, d_y, b_y);
  for (i = 0; i < 108; i++) {
    Dd[i] = -Dd[i];
  }

  for (i = 0; i < 6; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 18; i1++) {
      step += Dd[i + 6 * i1] * z[i1 + 18];
    }

    e_Dd[i] = step + fg[i];
  }

  for (i = 0; i < 108; i++) {
    b_Dd[i] = -b_Dd[i];
  }

  for (i = 0; i < 6; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 18; i1++) {
      step += b_Dd[i + 6 * i1] * z[i1 + 18];
    }

    fg[i] = step + b_fg[i];
  }

  for (i = 0; i < 18; i++) {
    step = 0.0;
    a_tmp = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      i2 = i + 18 * i1;
      step += y[i2] * e_Dd[i1];
      a_tmp += c_y[i2] * fg[i1];
    }

    i_y[i] = a_tmp;
    dv[i] = step;
  }

  for (i = 0; i < 108; i++) {
    c_Dd[i] = -c_Dd[i];
  }

  for (i = 0; i < 6; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 18; i1++) {
      step += c_Dd[i + 6 * i1] * z[i1 + 18];
    }

    e_Dd[i] = step + c_fg[i];
  }

  for (i = 0; i < 108; i++) {
    d_Dd[i] = -d_Dd[i];
  }

  for (i = 0; i < 6; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 18; i1++) {
      step += d_Dd[i + 6 * i1] * z[i1 + 18];
    }

    fg[i] = step + d_fg[i];
  }

  for (i = 0; i < 18; i++) {
    step = 0.0;
    a_tmp = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      i2 = i + 18 * i1;
      step += e_y[i2] * e_Dd[i1];
      a_tmp += g_y[i2] * fg[i1];
    }

    dv1[i] = (dv[i] + i_y[i]) + step;
    i_y[i] = a_tmp;
  }

  b_par_mex_var[0] = par_mex_var[1] * z[0] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[1] = par_mex_var[1] * z[1] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[2] = par_mex_var[1] * z[2] * t13 * b_t32 * 3.1415926535897931 *
    3.0;
  step = t41_tmp_tmp - t33 * 3.1415926535897931 / 2.0;
  b_par_mex_var[3] = -par_mex_var[1] * z[3] * t13 * step;
  b_par_mex_var[4] = par_mex_var[1] * z[4] * t13 * t41_tmp * 3.0;
  b_par_mex_var[5] = par_mex_var[1] * z[5] * t13 * t41_tmp * 3.0;
  b_par_mex_var[6] = par_mex_var[1] * z[6] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[7] = par_mex_var[1] * z[7] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[8] = par_mex_var[1] * z[8] * t13 * b_t32 * 3.1415926535897931 *
    3.0;
  b_par_mex_var[9] = -par_mex_var[1] * z[9] * t13 * step;
  b_par_mex_var[10] = par_mex_var[1] * z[10] * t13 * t41_tmp * 3.0;
  b_par_mex_var[11] = par_mex_var[1] * z[11] * t13 * t41_tmp * 3.0;
  b_par_mex_var[12] = par_mex_var[1] * z[12] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[13] = par_mex_var[1] * z[13] * t13 * b_t32 * 3.1415926535897931;
  b_par_mex_var[14] = par_mex_var[1] * z[14] * t13 * b_t32 * 3.1415926535897931 *
    3.0;
  b_par_mex_var[15] = -par_mex_var[1] * z[15] * t13 * step;
  b_par_mex_var[16] = par_mex_var[1] * z[16] * t13 * t41_tmp * 3.0;
  b_par_mex_var[17] = par_mex_var[1] * z[17] * t13 * t41_tmp * 3.0;
  c_par_mex_var[0] = -par_mex_var[5] * z[18];
  c_par_mex_var[1] = -par_mex_var[6] * z[19];
  c_par_mex_var[2] = -par_mex_var[7] * z[20];
  c_par_mex_var[3] = -par_mex_var[10] * z[21];
  c_par_mex_var[4] = -par_mex_var[8] * z[22];
  c_par_mex_var[5] = -par_mex_var[9] * z[23];
  c_par_mex_var[6] = -par_mex_var[5] * z[24];
  c_par_mex_var[7] = -par_mex_var[6] * z[25];
  c_par_mex_var[8] = -par_mex_var[7] * z[26];
  c_par_mex_var[9] = -par_mex_var[10] * z[27];
  c_par_mex_var[10] = -par_mex_var[8] * z[28];
  c_par_mex_var[11] = -par_mex_var[9] * z[29];
  c_par_mex_var[12] = -par_mex_var[5] * z[30];
  c_par_mex_var[13] = -par_mex_var[6] * z[31];
  c_par_mex_var[14] = -par_mex_var[7] * z[32];
  c_par_mex_var[15] = -par_mex_var[10] * z[33];
  c_par_mex_var[16] = -par_mex_var[8] * z[34];
  c_par_mex_var[17] = -par_mex_var[9] * z[35];
  dv[0] = 0.0;
  dv[1] = 0.0;
  dv[2] = -b_t13;
  dv[3] = 0.0;
  dv[4] = t32;
  dv[5] = t8;
  dv[6] = 0.0;
  dv[7] = 0.0;
  dv[8] = -b_t13;
  dv[9] = 0.0;
  dv[10] = t32;
  dv[11] = t8;
  dv[12] = 0.0;
  dv[13] = 0.0;
  dv[14] = -b_t13;
  dv[15] = 0.0;
  dv[16] = t32;
  dv[17] = t8;
  for (i = 0; i < 18; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 6; i1++) {
      step += T[i + 18 * i1] * ftau_ex[i1];
    }

    dv2[i] = ((((dv1[i] + i_y[i]) + b_par_mex_var[i]) + c_par_mex_var[i]) + dv[i])
      + step;
  }

  for (i = 0; i < 18; i++) {
    step = 0.0;
    for (i1 = 0; i1 < 18; i1++) {
      step += b_y[i + 18 * i1] * dv2[i1];
    }

    dz[i] = z[i + 18];
    dz[i + 18] = step;
  }

  *flag = 0.0;
}

/* End of code generation (EOM.c) */
