/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF5.c
 *
 * Code generation for function 'cnstF5'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF5.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo gfb_emlrtRSI = { 18,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo hfb_emlrtRSI = { 19,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo ifb_emlrtRSI = { 20,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo jfb_emlrtRSI = { 22,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo kfb_emlrtRSI = { 24,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo lfb_emlrtRSI = { 26,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

static emlrtRSInfo mfb_emlrtRSI = { 28,/* lineNo */
  "cnstF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF5.m"/* pathName */
};

/* Function Definitions */
void cnstF5(const emlrtStack *sp, const real_T in2[206], real_T out1[91], real_T
            out2[91], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t14;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T out2_tmp;
  real_T b_out2_tmp;
  real_T c_out2_tmp;
  real_T d_out2_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* CNSTF5 */
  /*     [OUT1,OUT2,OUT3] = CNSTF5(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:04 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarSin(t2);
  st.site = &gfb_emlrtRSI;
  t4 = in2[75] * in2[75];
  st.site = &hfb_emlrtRSI;
  t5 = in2[76] * in2[76];
  st.site = &ifb_emlrtRSI;
  t6 = in2[77] * in2[77];
  t7 = ((-t4 - t5) - t6) + 1.0;
  st.site = &jfb_emlrtRSI;
  if (t7 < 0.0) {
    b_st.site = &gh_emlrtRSI;
    b_error(&b_st);
  }

  t14 = muDoubleScalarSqrt(t7);
  t8 = 1.0 / t14;
  t9 = muDoubleScalarCos(t2);
  st.site = &kfb_emlrtRSI;
  t10 = 1.0 / muDoubleScalarPower(t7, 1.5);
  t11 = in2[76] - t3;
  st.site = &lfb_emlrtRSI;
  t7 = t9 - t14;
  st.site = &mfb_emlrtRSI;
  st.site = &mfb_emlrtRSI;
  memset(&out1[0], 0, 75U * sizeof(real_T));
  out1[75] = in2[75] * t3 * t8 * 2.0;
  out1[76] = t9 * 2.0 + in2[76] * t3 * t8 * 2.0;
  out1[77] = in2[77] * t3 * t8 * 2.0;
  memset(&out1[78], 0, 12U * sizeof(real_T));
  out1[90] = ((-t3 * t11 + t9 * t7) - t3 * t3) - t9 * t9;
  t14 = t3 - in2[76] * t8 * t9;
  memset(&out2[0], 0, 75U * sizeof(real_T));
  out2_tmp = t3 * t8;
  b_out2_tmp = in2[75] * in2[76] * t3 * t10;
  c_out2_tmp = in2[75] * in2[77] * t3 * t10;
  d_out2_tmp = in2[75] * t8 * t9;
  out2[75] = (((out2_tmp * in2[178] * 2.0 + d_out2_tmp * in2[193]) + t3 * t4 *
               t10 * in2[178] * 2.0) + b_out2_tmp * in2[179] * 2.0) + c_out2_tmp
    * in2[180] * 2.0;
  t2 = in2[76] * in2[77] * t3 * t10;
  out2[76] = ((in2[179] * (out2_tmp * 2.0 + t3 * t5 * t10 * 2.0) - t14 * in2[193])
              + b_out2_tmp * in2[178] * 2.0) + t2 * in2[180] * 2.0;
  b_out2_tmp = in2[77] * t8 * t9;
  out2[77] = (((out2_tmp * in2[180] * 2.0 + b_out2_tmp * in2[193]) + t3 * t6 *
               t10 * in2[180] * 2.0) + c_out2_tmp * in2[178] * 2.0) + t2 * in2
    [179] * 2.0;
  memset(&out2[78], 0, 12U * sizeof(real_T));
  out2[90] = ((-t14 * in2[179] - in2[193] * (t3 * t7 / 2.0 + t9 * t11 / 2.0)) +
              d_out2_tmp * in2[178]) + b_out2_tmp * in2[180];
  *out3 = 0.0;
}

/* End of code generation (cnstF5.c) */
