/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF11.c
 *
 * Code generation for function 'cnstF11'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF11.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo sfb_emlrtRSI = { 18,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo tfb_emlrtRSI = { 19,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo ufb_emlrtRSI = { 20,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo vfb_emlrtRSI = { 22,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo wfb_emlrtRSI = { 24,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo xfb_emlrtRSI = { 26,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

static emlrtRSInfo yfb_emlrtRSI = { 28,/* lineNo */
  "cnstF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF11.m"/* pathName */
};

/* Function Definitions */
void cnstF11(const emlrtStack *sp, const real_T in2[206], real_T out1[91],
             real_T out2[91], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t14;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T out2_tmp;
  real_T b_out2_tmp;
  real_T c_out2_tmp;
  real_T d_out2_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* CNSTF11 */
  /*     [OUT1,OUT2,OUT3] = CNSTF11(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:07 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarSin(t2);
  st.site = &sfb_emlrtRSI;
  t4 = in2[87] * in2[87];
  st.site = &tfb_emlrtRSI;
  t5 = in2[88] * in2[88];
  st.site = &ufb_emlrtRSI;
  t6 = in2[89] * in2[89];
  t7 = ((-t4 - t5) - t6) + 1.0;
  st.site = &vfb_emlrtRSI;
  if (t7 < 0.0) {
    b_st.site = &gh_emlrtRSI;
    b_error(&b_st);
  }

  t14 = muDoubleScalarSqrt(t7);
  t8 = 1.0 / t14;
  t9 = muDoubleScalarCos(t2);
  st.site = &wfb_emlrtRSI;
  t10 = 1.0 / muDoubleScalarPower(t7, 1.5);
  t11 = in2[88] - t3;
  st.site = &xfb_emlrtRSI;
  t7 = t9 - t14;
  st.site = &yfb_emlrtRSI;
  st.site = &yfb_emlrtRSI;
  memset(&out1[0], 0, 87U * sizeof(real_T));
  out1[87] = in2[87] * t3 * t8 * 2.0;
  out1[88] = t9 * 2.0 + in2[88] * t3 * t8 * 2.0;
  out1[89] = in2[89] * t3 * t8 * 2.0;
  out1[90] = ((-t3 * t11 + t9 * t7) - t3 * t3) - t9 * t9;
  t14 = t3 - in2[88] * t8 * t9;
  memset(&out2[0], 0, 87U * sizeof(real_T));
  out2_tmp = t3 * t8;
  b_out2_tmp = in2[87] * in2[88] * t3 * t10;
  c_out2_tmp = in2[87] * in2[89] * t3 * t10;
  d_out2_tmp = in2[87] * t8 * t9;
  out2[87] = (((out2_tmp * in2[190] * 2.0 + d_out2_tmp * in2[193]) + t3 * t4 *
               t10 * in2[190] * 2.0) + b_out2_tmp * in2[191] * 2.0) + c_out2_tmp
    * in2[192] * 2.0;
  t2 = in2[88] * in2[89] * t3 * t10;
  out2[88] = ((in2[191] * (out2_tmp * 2.0 + t3 * t5 * t10 * 2.0) - t14 * in2[193])
              + b_out2_tmp * in2[190] * 2.0) + t2 * in2[192] * 2.0;
  b_out2_tmp = in2[89] * t8 * t9;
  out2[89] = (((out2_tmp * in2[192] * 2.0 + b_out2_tmp * in2[193]) + t3 * t6 *
               t10 * in2[192] * 2.0) + c_out2_tmp * in2[190] * 2.0) + t2 * in2
    [191] * 2.0;
  out2[90] = ((-t14 * in2[191] - in2[193] * (t3 * t7 / 2.0 + t9 * t11 / 2.0)) +
              d_out2_tmp * in2[190]) + b_out2_tmp * in2[192];
  *out3 = 0.0;
}

/* End of code generation (cnstF11.c) */
