/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF4.c
 *
 * Code generation for function 'massF4'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF4.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo nh_emlrtRSI = { 16, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

static emlrtRSInfo oh_emlrtRSI = { 17, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

static emlrtRSInfo ph_emlrtRSI = { 18, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

static emlrtRSInfo qh_emlrtRSI = { 20, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

static emlrtRSInfo rh_emlrtRSI = { 23, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

static emlrtRSInfo sh_emlrtRSI = { 31, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF4.m"/* pathName */
};

/* Function Definitions */
void massF4(const emlrtStack *sp, const real_T in2[206], real_T out2[546],
            real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF4 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF4(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:09:35 */
  st.site = &nh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[15] * in2[15];
  st.site = &oh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[16] * in2[16];
  st.site = &ph_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[17] * in2[17];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &qh_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[17] * 2.0;
  t28 = in2[15] * in2[16];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &rh_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[15] * in2[17] * t6 * 2.0;
  t12 = in2[15] * 2.0;
  t13 = in2[16] * in2[17] * t6 * 2.0;
  memset(&out2[0], 0, 72U * sizeof(real_T));
  out2[72] = 1.0;
  out2[73] = 0.0;
  out2[74] = 0.0;
  out2[75] = 0.0;
  out2[76] = 0.0;
  out2[77] = 0.0;
  out2[78] = 0.0;
  out2[79] = 1.0;
  out2[80] = 0.0;
  out2[81] = 0.0;
  out2[82] = 0.0;
  out2[83] = 0.0;
  out2[84] = 0.0;
  out2[85] = 0.0;
  out2[86] = 1.0;
  out2[87] = 0.0;
  out2[88] = 0.0;
  out2[89] = 0.0;
  out2[90] = 0.0;
  out2[91] = 0.0;
  out2[92] = 0.0;
  out2[93] = t9 + t2 * t6 * 2.0;
  out2[94] = -t7 + t8;
  out2[95] = in2[16] * 2.0 + t11;
  out2[96] = 0.0;
  out2[97] = 0.0;
  out2[98] = 0.0;
  out2[99] = t7 + t8;
  out2[100] = t9 + t3 * t6 * 2.0;
  out2[101] = -t12 + t13;
  out2[102] = 0.0;
  out2[103] = 0.0;
  out2[104] = 0.0;
  out2[105] = in2[16] * -2.0 + t11;
  out2[106] = t12 + t13;
  out2[107] = t9 + t4 * t6 * 2.0;
  memset(&out2[108], 0, 438U * sizeof(real_T));
  st.site = &sh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[16] * t6 * 2.0;
  t16 = in2[16] * t2 * t14 * 2.0;
  t17 = in2[15] * t6 * 2.0;
  t18 = t28 * in2[17] * t14 * 2.0;
  t9 = in2[17] * t6 * 2.0;
  t11 = in2[17] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[15] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[17] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[15] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[16] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 93U * sizeof(real_T));
  out3[93] = (t12 * in2[119] + t5 * in2[120]) + in2[118] * (t17 + in2[15] * t2 *
    t14 * 2.0);
  out3[94] = (t12 * in2[118] + (t18 + 2.0) * in2[120]) - in2[119] * (t17 - t13);
  out3[95] = ((t18 - 2.0) * in2[119] + t5 * in2[118]) - in2[120] * (t17 - t28);
  out3[96] = 0.0;
  out3[97] = 0.0;
  out3[98] = 0.0;
  out3[99] = (t7 * in2[119] + (t18 - 2.0) * in2[120]) - in2[118] * (t15 - t16);
  out3[100] = (t7 * in2[118] + t6 * in2[120]) + in2[119] * (t15 + in2[16] * t3 *
    t14 * 2.0);
  out3[101] = ((t18 + 2.0) * in2[118] + t6 * in2[119]) - in2[120] * (t15 - t30);
  out3[102] = 0.0;
  out3[103] = 0.0;
  out3[104] = 0.0;
  out3[105] = ((t18 + 2.0) * in2[119] + t31 * in2[120]) - in2[118] * (t9 - t11);
  out3[106] = ((t18 - 2.0) * in2[118] + t32 * in2[120]) - in2[119] * (t9 - t8);
  out3[107] = (t31 * in2[118] + t32 * in2[119]) + in2[120] * (t9 + in2[17] * t4 *
    t14 * 2.0);
  memset(&out3[108], 0, 438U * sizeof(real_T));
}

/* End of code generation (massF4.c) */
