/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF102.c
 *
 * Code generation for function 'sprdmpF102'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF102.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo kt_emlrtRSI = { 41, /* lineNo */
  "sprdmpF102",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF102.m"/* pathName */
};

static emlrtRSInfo lt_emlrtRSI = { 47, /* lineNo */
  "sprdmpF102",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF102.m"/* pathName */
};

static emlrtRSInfo pt_emlrtRSI = { 77, /* lineNo */
  "sprdmpF102",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF102.m"/* pathName */
};

static emlrtRSInfo qt_emlrtRSI = { 89, /* lineNo */
  "sprdmpF102",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF102.m"/* pathName */
};

static emlrtRSInfo du_emlrtRSI = { 297,/* lineNo */
  "sprdmpF102",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF102.m"/* pathName */
};

/* Function Definitions */
void sprdmpF102(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t189;
  real_T t205;
  real_T t186;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t204;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t24_tmp;
  real_T t25;
  real_T t233;
  real_T t156;
  real_T t208;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t177;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t51_tmp;
  real_T b_t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t227;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t60;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63_tmp;
  real_T t64_tmp;
  real_T a_tmp;
  real_T t72;
  real_T t73;
  real_T t75;
  real_T t77;
  real_T a;
  real_T t79;
  real_T b_a_tmp;
  real_T c_a_tmp;
  real_T b_a;
  real_T t81;
  real_T t85;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t105_tmp;
  real_T t105;
  real_T t109;
  real_T t114;
  real_T t115;
  real_T t116;
  real_T t120;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t125;
  real_T t126_tmp;
  real_T b_t126_tmp;
  real_T t126;
  real_T t135_tmp;
  real_T t135;
  real_T t138;
  real_T t148;
  real_T t152;
  real_T t153;
  real_T t154;
  real_T t155;
  real_T t168;
  real_T t171;
  real_T t180;
  real_T t182;
  real_T t185;
  real_T t188;
  real_T t191;
  real_T t195;
  real_T t199;
  real_T t207;
  real_T t211;
  real_T t212;
  real_T t214;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF102 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF102(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:26:19 */
  t2 = in2[34] * in2[34];
  t3 = in2[35] * in2[35];
  t4 = in2[33] * in2[33];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &kt_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[35] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[33] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &lt_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t189 = in2[31] - in2[37];
  t205 = in2[32] - in2[38];
  t186 = in2[30] - in2[36];
  t17_tmp = in2[33] * t12;
  t17 = (-in2[32] + in2[38]) + t17_tmp * t189;
  t19 = t189 + t17_tmp * t205;
  t20 = t6 * t189;
  t204 = in2[33] * t205;
  t22_tmp = in2[33] * t189;
  t23_tmp = t6 * t205;
  t24_tmp = in2[34] * t186;
  t25 = t6 * t186;
  t233 = in2[35] * t189;
  t156 = in2[34] * t205;
  t208 = t25 + t233;
  t27 = t208 - t156;
  t29_tmp = in2[34] * t12;
  t29 = (-in2[30] + in2[36]) + t29_tmp * t205;
  t31 = t205 + t29_tmp * t186;
  t177 = in2[35] * t186;
  t32_tmp = t20 + t204;
  t32 = t32_tmp - t177;
  t34 = (-t22_tmp + t23_tmp) + t24_tmp;
  t35 = in2[41] * 2.0;
  t36 = in2[33] - in2[39];
  t5 = ((-(in2[39] * in2[39]) - in2[40] * in2[40]) - in2[41] * in2[41]) + 1.0;
  t41 = t5;
  st.site = &pt_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[34] - in2[40];
  t43 = in2[35] - in2[41];
  t46_tmp = in2[35] * t12;
  t46 = t186 + t46_tmp * t189;
  t48 = (-in2[31] + in2[37]) + t46_tmp * t186;
  t49 = in2[39] * 2.0;
  t50_tmp = in2[34] * t6 * 2.0;
  t51_tmp = in2[33] * in2[34];
  b_t51_tmp = t51_tmp * 2.0;
  t52_tmp = in2[33] * in2[35];
  t52 = t52_tmp * 2.0;
  t227 = in2[34] * in2[35];
  t53_tmp = t227 * 2.0;
  st.site = &qt_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[34] * 2.0;
  t5 = in1[4] / 2.0;
  t58 = muDoubleScalarCos(t5);
  t59 = t58 / 25.0;
  t60 = muDoubleScalarSin(t5);
  t61_tmp = in2[33] * t186;
  t62_tmp = in2[34] * t189;
  t63_tmp = in2[35] * t205;
  t64_tmp = (t61_tmp + t62_tmp) + t63_tmp;
  a_tmp = t58 * t58 * 2.573707911E-14 + t60 * t60 * 2.573707911E-14;
  t5 = t60 / 25.0;
  t72 = t58 / 4.0 - t5;
  t73 = t58 * 0.333;
  t75 = t59 + t60 / 4.0;
  t77 = t59 + t60 * 0.333;
  t5 -= t73;
  a = ((t58 * t72 + t58 * t5) - t60 * t75) + t60 * t77;
  t79 = t58 * t77;
  b_a_tmp = t60 * t72;
  c_a_tmp = t58 * t75;
  b_a = ((-t79 + c_a_tmp) + b_a_tmp) + t60 * t5;
  t81 = t6 - t41;
  t77 = t227 * t12;
  t85 = (((((t23_tmp + t24_tmp) + t6 * t31) + t29_tmp * t27) + t77 * t189) -
         in2[34] * t29) - t22_tmp * 2.0;
  t89 = (((((-t20 + t177) + t6 * t48) + in2[35] * t46) + t46_tmp * t27) - t204 *
         2.0) - t77 * t205;
  t90 = (t8 + t11) - 1.0;
  t91 = t7 + b_t51_tmp;
  t92 = t50_tmp - t52;
  t93 = in2[35] * t17;
  t94 = t17_tmp * t27;
  t105_tmp = in2[34] * t19;
  t105 = ((t64_tmp - t93) - t94) + t105_tmp;
  t109 = muDoubleScalarPower(muDoubleScalarAbs((((((((t85 * in2[137] + t89 *
    in2[138]) + t90 * in2[133]) + t92 * in2[135]) + t91 * in2[140]) - t90 * in2
    [139]) - t91 * in2[134]) - t92 * in2[141]) - t105 * in2[136]), in1[1] - 1.0);
  t114 = t6 * t17;
  t115 = in2[33] * t19;
  t116 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t120 = ((((t208 + t6 * t46) + t46_tmp * t32) + t5 * t205) - in2[35] * t48) -
    t156 * 2.0;
  t121 = (t8 + t10) - 1.0;
  t122 = t9 + t53_tmp;
  t123 = t7 - b_t51_tmp;
  t124 = in2[33] * t29;
  t125 = t29_tmp * t32;
  t126_tmp = t24_tmp * 2.0;
  b_t126_tmp = t5 * t186;
  t126 = (((((t22_tmp - t23_tmp) + t114) + t115) + t116) - t126_tmp) -
    b_t126_tmp;
  t135_tmp = in2[35] * t31;
  t135 = ((t64_tmp - t124) - t125) + t135_tmp;
  t138 = muDoubleScalarPower(muDoubleScalarAbs((((((((t126 * in2[136] + t120 *
    in2[138]) + t121 * in2[134]) + t123 * in2[133]) + t122 * in2[141]) - t121 *
    in2[140]) - t122 * in2[135]) - t123 * in2[139]) - t135 * in2[137]), in1[1] -
    1.0);
  t59 = t51_tmp * t12;
  t148 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t59 * t186) - in2[33] * t17)
    - t177 * 2.0;
  t152 = (((((-t25 + t156) + t6 * t29) + in2[34] * t31) + t29_tmp * t34) - t233 *
          2.0) - t59 * t189;
  t153 = (t10 + t11) - 1.0;
  t154 = t50_tmp + t52;
  t155 = t9 - t53_tmp;
  t156 = in2[34] * t48;
  t29 = t46_tmp * t34;
  t17 = in2[33] * t46;
  t168 = ((t64_tmp - t156) - t29) + t17;
  t171 = muDoubleScalarPower(muDoubleScalarAbs((((((((t148 * in2[136] + t152 *
    in2[137]) + t153 * in2[135]) + t155 * in2[134]) + t154 * in2[139]) - t153 *
    in2[141]) - t154 * in2[133]) - t155 * in2[140]) - t168 * in2[138]), in1[1] -
    1.0);
  t19 = t17_tmp * t36 * 2.0;
  t177 = t29_tmp * t36 * 2.0;
  t31 = in2[40] * 2.0;
  t32_tmp = t5 * 2.0;
  t180 = (t31 + t46_tmp * t36 * 2.0) - t32_tmp;
  t182 = t55 + in2[33] * in2[39] * t54 * 2.0;
  t5 = in2[35] * 2.0;
  t185 = t5 + in2[33] * in2[40] * t54 * 2.0;
  t186 = in2[33] * in2[41] * t54 * 2.0;
  t24_tmp = t59 * 2.0;
  t188 = (t35 - t177) + t24_tmp;
  t189 = t41 * 2.0;
  t58 = t4 * t12 * 2.0;
  t191 = (-t19 + t189) + t58;
  t195 = t56 - t186;
  t199 = muDoubleScalarPower(muDoubleScalarAbs(((((t191 * in2[136] + t188 * in2
    [137]) + t195 * in2[144]) - t180 * in2[138]) - t182 * in2[142]) - t185 *
    in2[143]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t204 = t17_tmp * t42 * 2.0;
  t205 = t46_tmp * t42 * 2.0;
  t207 = t55 + in2[34] * in2[40] * t54 * 2.0;
  t208 = in2[34] * in2[39] * t54 * 2.0;
  t48 = in2[33] * 2.0;
  t211 = t48 + in2[34] * in2[41] * t54 * 2.0;
  t212 = (t35 - t24_tmp) + t204;
  t75 = t2 * t12 * 2.0;
  t214 = (t189 - t20) + t75;
  t51_tmp = t77 * 2.0;
  t2 = (t49 - t205) + t51_tmp;
  t46 = t5 - t208;
  t4 = muDoubleScalarPower(muDoubleScalarAbs(((((t214 * in2[137] + t2 * in2[138])
    + t46 * in2[142]) - t212 * in2[136]) - t207 * in2[143]) - t211 * in2[144]),
    in1[1] - 1.0);
  t227 = t46_tmp * t43 * 2.0;
  t59 = t17_tmp * t43 * 2.0;
  t72 = t29_tmp * t43 * 2.0;
  t25 = t55 + in2[35] * in2[41] * t54 * 2.0;
  t233 = t56 + in2[35] * in2[39] * t54 * 2.0;
  t77 = in2[35] * in2[40] * t54 * 2.0;
  memset(&out1[0], 0, 30U * sizeof(real_T));
  out1[30] = t90;
  out1[31] = -t7 - b_t51_tmp;
  out1[32] = t50_tmp - in2[33] * in2[35] * 2.0;
  out1[33] = ((((t93 + t94) - t62_tmp) - t61_tmp) - t63_tmp) - t105_tmp;
  out1[34] = t85;
  out1[35] = t89;
  out1[36] = (-t8 - t11) + 1.0;
  out1[37] = t91;
  out1[38] = -t50_tmp + t52;
  memset(&out1[39], 0, 82U * sizeof(real_T));
  out1[121] = t7 - in2[33] * in2[34] * 2.0;
  out1[122] = t121;
  out1[123] = -t9 - t53_tmp;
  out1[124] = (((((t22_tmp + t114) + t115) + t116) - t126_tmp) - t23_tmp) -
    b_t126_tmp;
  out1[125] = ((((t124 + t125) - t62_tmp) - t61_tmp) - t63_tmp) - t135_tmp;
  out1[126] = t120;
  out1[127] = -t7 + b_t51_tmp;
  out1[128] = (-t8 - t10) + 1.0;
  out1[129] = t122;
  memset(&out1[130], 0, 82U * sizeof(real_T));
  out1[212] = t52_tmp * -2.0 - t50_tmp;
  out1[213] = t9 - in2[34] * in2[35] * 2.0;
  out1[214] = t153;
  out1[215] = t148;
  out1[216] = t152;
  out1[217] = ((((t156 + t29) - t62_tmp) - t61_tmp) - t63_tmp) - t17;
  out1[218] = t154;
  out1[219] = -t9 + t53_tmp;
  out1[220] = (-t10 - t11) + 1.0;
  memset(&out1[221], 0, 85U * sizeof(real_T));
  out1[306] = (t41 * -2.0 + t19) - t58;
  out1[307] = (-t35 + t177) - t24_tmp;
  out1[308] = t180;
  out1[309] = 0.0;
  out1[310] = 0.0;
  out1[311] = 0.0;
  out1[312] = t182;
  out1[313] = t185;
  out1[314] = -t56 + t186;
  memset(&out1[315], 0, 82U * sizeof(real_T));
  out1[397] = (t35 + t204) - t24_tmp;
  out1[398] = (t41 * -2.0 + t20) - t75;
  out1[399] = (-t49 + t205) - t51_tmp;
  out1[400] = 0.0;
  out1[401] = 0.0;
  out1[402] = 0.0;
  out1[403] = in2[35] * -2.0 + t208;
  out1[404] = t207;
  out1[405] = t211;
  memset(&out1[406], 0, 82U * sizeof(real_T));
  out1[488] = (in2[40] * -2.0 + t59) - t32_tmp;
  out1[489] = (t49 + t72) - t51_tmp;
  t5 = t3 * t12 * 2.0;
  out1[490] = (t41 * -2.0 + t227) - t5;
  out1[491] = 0.0;
  out1[492] = 0.0;
  out1[493] = 0.0;
  out1[494] = t233;
  out1[495] = in2[33] * -2.0 + t77;
  out1[496] = t25;
  memset(&out1[497], 0, 49U * sizeof(real_T));
  t20 = (t31 + t32_tmp) - t59;
  t227 = (t189 - t227) + t5;
  t58 = (t49 - t51_tmp) + t72;
  t72 = t48 - t77;
  t75 = muDoubleScalarPower(muDoubleScalarAbs(((((t227 * in2[138] + t20 * in2
    [136]) + t72 * in2[143]) - t58 * in2[137]) - t25 * in2[144]) - t233 * in2
    [142]), in1[1] - 1.0);
  t5 = (a_tmp * a_tmp + a * a) + b_a * b_a;
  st.site = &du_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * (((((((t79 + in2[35] * t32) - in2[34] * t34) + in2[33] *
    t64_tmp) + t6 * t27) - b_a_tmp) - c_a_tmp) - t60 * (t60 / 25.0 - t73)) *
    0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp - in2[35] * t27) + in2[33] * t34) + in2[34] *
                       t64_tmp) + t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((t5 + in2[34] * t27) - in2[33] * t32) + in2[35] *
                       t64_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[34] * t43 * 2.0 - in2[35] * t42 * 2.0) + in2[33] *
                       t81 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[35] * t36 * 2.0 - in2[33] * t43 * 2.0) + in2[34] *
                       t81 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[34] * t36 * 2.0 - in2[33] * t42 * 2.0) - in2[35] *
                       t81 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t77 = in1[2] * t90 * t109;
  t59 = in1[2] * t91 * t109;
  t5 = in1[2] * t92 * t109;
  out3[0] = (((((((-in1[2] * t85 * t109 * in2[137] - t77 * in2[133]) + t59 *
                  in2[134]) - in1[2] * t89 * t109 * in2[138]) - t5 * in2[135]) +
               t77 * in2[139]) - t59 * in2[140]) + t5 * in2[141]) + in1[2] *
    t105 * t109 * in2[136];
  t77 = in1[2] * t123 * t138;
  t59 = in1[2] * t122 * t138;
  out3[1] = (((((((-in1[2] * t121 * t138 * in2[134] - t77 * in2[133]) + t59 *
                  in2[135]) - in1[2] * t120 * t138 * in2[138]) + in1[2] * t121 *
                t138 * in2[140]) + t77 * in2[139]) - in1[2] * t126 * t138 * in2
              [136]) - t59 * in2[141]) + in1[2] * t135 * t138 * in2[137];
  t77 = in1[2] * t154 * t171;
  t59 = in1[2] * t153 * t171;
  t5 = in1[2] * t155 * t171;
  out3[2] = (((((((-in1[2] * t148 * t171 * in2[136] + t77 * in2[133]) - t59 *
                  in2[135]) - in1[2] * t152 * t171 * in2[137]) - t5 * in2[134])
               - t77 * in2[139]) + t59 * in2[141]) + t5 * in2[140]) + in1[2] *
    t168 * t171 * in2[138];
  out3[3] = ((((-in1[3] * t180 * t199 * in2[138] - in1[3] * t182 * t199 * in2
                [142]) + in1[3] * t188 * t199 * in2[137]) + in1[3] * t191 * t199
              * in2[136]) - in1[3] * t185 * t199 * in2[143]) + in1[3] * t195 *
    t199 * in2[144];
  out3[4] = ((((-in1[3] * t212 * t4 * in2[136] - in1[3] * t207 * t4 * in2[143])
               + in1[3] * t214 * t4 * in2[137]) - in1[3] * t211 * t4 * in2[144])
             + in1[3] * t2 * t4 * in2[138]) + in1[3] * t46 * t4 * in2[142];
  out3[5] = ((((in1[3] * t20 * t75 * in2[136] - in1[3] * t25 * t75 * in2[144]) -
               in1[3] * t233 * t75 * in2[142]) + in1[3] * t227 * t75 * in2[138])
             - in1[3] * t58 * t75 * in2[137]) + in1[3] * t72 * t75 * in2[143];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF102.c) */
