function out1 = sprdmpDir11(in1,in2,s,ds,t_sym)
%SPRDMPDIR11
%    OUT1 = SPRDMPDIR11(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:58:56

out1 = 1.0;
