function out1 = sprdmpTt6(in1,in2,s,ds,t_sym)
%SPRDMPTT6
%    OUT1 = SPRDMPTT6(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:46:30

out1 = [0.0;0.0;0.0;0.0;0.0;1.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
