/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF127.c
 *
 * Code generation for function 'sprdmpF127'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "sprdmpF127.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo c_emlrtRSI = { 70,  /* lineNo */
  "sprdmpF127",                        /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v2.0 HLL/Fabric/eom/sprdmpF127.m"/* pathName */
};

/* Function Definitions */
void sprdmpF127(const emlrtStack *sp, const real_T in1[6], const real_T in2[224],
                real_T s, real_T out1[318], real_T out2[3], real_T out3[3],
                real_T out4[3], real_T *out5, real_T out6[318], real_T out7[318],
                real_T *out8)
{
  real_T t3;
  real_T t2;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t11;
  real_T t14;
  real_T t17;
  real_T t20;
  real_T t44;
  real_T t25;
  real_T t28;
  real_T t33;
  real_T t39;
  emlrtStack st;
  (void)in1;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF127 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF127(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jul-2019 08:26:47 */
  t3 = in2[105] / 2.0;
  t2 = muDoubleScalarCos(t3);
  t4 = muDoubleScalarSin(t3);
  t5 = t2 * t2;
  t6 = t4 * t4;
  t7 = t2 * t4 * 2.0;
  t8 = t5 - t6;
  t11 = t2 * 0.03 - t4 * 0.038;
  t14 = t2 * 0.038 + t4 * 0.03;
  t17 = t2 * 0.019 + t4 * 0.015;
  t20 = t2 * 0.015 - t4 * 0.019;
  t3 = t2 * t14;
  t44 = t4 * t11;
  t25 = ((t3 / 2.0 + t2 * t17) + t44 / 2.0) + t4 * t20;
  t28 = (in2[84] + t3) + t44;
  t44 = t2 * t11;
  t3 = t4 * t14;
  t14 = ((t44 / 2.0 + t2 * t20) - t3 / 2.0) - t4 * t17;
  t33 = (in2[86] + t44) - t3;
  t3 = t2 * t28;
  t11 = t4 * t33;
  t39 = ((t2 * t25 + t11 / 2.0) - t3 / 2.0) - t4 * t14;
  t17 = t2 * t33;
  t20 = t4 * t28;
  t14 = ((t2 * t14 + t4 * t25) - t20 / 2.0) - t17 / 2.0;
  t44 = t3 - t11;
  t3 = t17 + t20;
  memset(&out1[0], 0, 84U * sizeof(real_T));
  out1[84] = t8;
  out1[85] = 0.0;
  out1[86] = -t7;
  memset(&out1[87], 0, 18U * sizeof(real_T));
  out1[105] = ((t4 * t39 + t2 * t14) - t4 * t44 / 2.0) - t2 * t3 / 2.0;
  memset(&out1[106], 0, 85U * sizeof(real_T));
  out1[191] = t5 + t6;
  memset(&out1[192], 0, 104U * sizeof(real_T));
  out1[296] = t7;
  out1[297] = 0.0;
  out1[298] = t8;
  memset(&out1[299], 0, 18U * sizeof(real_T));
  out1[317] = ((-t2 * t39 + t2 * t44 / 2.0) + t4 * t14) - t4 * t3 / 2.0;
  out2[0] = 0.0;
  out3[0] = 0.0;
  out4[0] = 0.0;
  out2[1] = 0.0;
  out3[1] = 0.0;
  out4[1] = 0.0;
  out2[2] = 0.0;
  out3[2] = 0.0;
  out4[2] = 0.0;
  *out5 = (in2[85] * in2[85] + t28 * t28) + t33 * t33;
  st.site = &c_emlrtRSI;
  b_sqrt(&st, out5);
  memset(&out6[0], 0, 318U * sizeof(real_T));
  memset(&out7[0], 0, 318U * sizeof(real_T));
  *out8 = 1.0;
}

/* End of code generation (sprdmpF127.c) */
