function [out1,out2] = loadsF1(phi_sym,in2,s)
%LOADSF1
%    [OUT1,OUT2] = LOADSF1(PHI_SYM,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Jul-2019 03:32:31

out1 = zeros(0,0);
if nargout > 1
    out2 = zeros(0,0);
end
