/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rjtipF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo g_emlrtRSI = { 48,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 51,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo i_emlrtRSI = { 54,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo j_emlrtRSI = { 57,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo k_emlrtRSI = { 70,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRTEInfo emlrtRTEI = { 13,  /* lineNo */
  9,                                   /* colNo */
  "sqrt",                              /* fName */
  "C:\\Program Files\\MATLAB\\R2020b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[10],
            real_T s, real_T ds, real_T t_sym, real_T out1[30])
{
  emlrtStack st;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t26;
  real_T t27;
  real_T t29;
  real_T t3;
  real_T t30;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t37;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t46_tmp_tmp;
  real_T t47_tmp_tmp;
  real_T t6;
  real_T t7;
  real_T t9;
  (void)ds;
  (void)t_sym;
  st.prev = sp;
  st.tls = sp->tls;

  /* RJTIPF */
  /*     OUT1 = RJTIPF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     27-Feb-2021 16:28:44 */
  t3 = in1[4] * in1[4];
  t6 = s * s;
  t7 = in1[4] * in2[2] * 2.0;
  t13 = in1[4] * in2[3] / 2.0;
  t9 = in2[0] * t3;
  t10 = in2[1] * t3;
  t11 = in2[2] * t3;
  t12 = s * t7;
  t17 = in2[4] * t3 / 2.0;
  t19 = t3 * (in2[0] * in2[0]) * 4.0;
  t20 = t3 * (in2[1] * in2[1]) * 4.0;
  t3 = t13 + t17;
  t26 = muDoubleScalarCos(t3);
  t27 = muDoubleScalarSin(t3);
  t3 = s * t13 + t6 * t17;
  t29 = muDoubleScalarCos(t3);
  t30 = muDoubleScalarSin(t3);
  st.site = &g_emlrtRSI;
  t3 = ((t7 + 1.0) * (t7 + 1.0) + t19) + t20;
  if (t3 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t32 = 1.0 / muDoubleScalarSqrt(t3);
  t34 = (t7 + 1.0) * t32;
  st.site = &h_emlrtRSI;
  t3 = ((t12 + 1.0) * (t12 + 1.0) + t6 * t19) + t6 * t20;
  if (t3 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t35 = 1.0 / muDoubleScalarSqrt(t3);
  st.site = &i_emlrtRSI;
  if (t34 + 1.0 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t37 = muDoubleScalarSqrt(t34 + 1.0);
  t17 = 1.0 / t37;
  st.site = &j_emlrtRSI;
  t3 = (t12 + 1.0) * t35 + 1.0;
  if (t3 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t41 = muDoubleScalarSqrt(t3);
  t43 = 1.4142135623730951 * t26 * t37 / 2.0;
  t44 = 1.4142135623730951 * t27 * t37 / 2.0;
  t42 = 1.0 / t41;
  t46_tmp_tmp = in1[4] * in2[1];
  t3 = t46_tmp_tmp * 1.4142135623730951;
  t7 = t3 * t26 * t32 * t17;
  t47_tmp_tmp = in1[4] * in2[0];
  t13 = t47_tmp_tmp * 1.4142135623730951;
  t20 = t13 * t27 * t32 * t17;
  t19 = t13 * t26 * t32 * t17 + t3 * t27 * t32 * t17;
  t12 = t7 + -t20;
  t7 = t20 + -t7;
  st.site = &k_emlrtRSI;
  if (in1[33] < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  out1[0] = t6 * t9;
  out1[1] = t9;
  out1[2] = t6 * t10;
  out1[3] = t10;
  out1[4] = in1[4] * s + t6 * t11;
  t13 = in1[4] + t11;
  out1[5] = t13;
  out1[6] = rtNaN;
  t17 = in1[16] * 1.4142135623730951 * t26 * t37;
  t3 = in1[16] * 1.4142135623730951 * t27 * t37;
  out1[7] = (t9 + t17 * t19) - t3 * t12;
  out1[8] = rtNaN;
  out1[9] = (t10 + t17 * t12) + t3 * t19;
  out1[10] = rtNaN;
  out1[11] = (((t13 - in1[16] * (t19 * t19)) - in1[16] * (t12 * t12)) + in1[16] *
              (t26 * t26) * (t34 + 1.0) / 2.0) + in1[16] * (t27 * t27) * (t34 +
    1.0) / 2.0;
  out1[12] = 1.4142135623730951 * t29 * t41 / 2.0;
  out1[13] = t43;
  t13 = t47_tmp_tmp * s * 1.4142135623730951;
  t17 = t46_tmp_tmp * s * 1.4142135623730951;
  out1[14] = t13 * t30 * t35 * t42 - t17 * t29 * t35 * t42;
  out1[15] = t7;
  out1[16] = t13 * t29 * t35 * t42 + t17 * t30 * t35 * t42;
  out1[17] = t19;
  out1[18] = 1.4142135623730951 * t30 * t41 / 2.0;
  out1[19] = t44;
  out1[20] = rtNaN;
  out1[21] = t43;
  out1[22] = rtNaN;
  out1[23] = t7;
  out1[24] = rtNaN;
  out1[25] = t19;
  out1[26] = rtNaN;
  out1[27] = t44;
  out1[28] = 1.0 / muDoubleScalarSqrt(in1[33]) * in1[3];
  out1[29] = in1[17];
}

/* End of code generation (rjtipF.c) */
