/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF4.c
 *
 * Code generation for function 'massF4'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF4.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo rc_emlrtRSI = { 23, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo sc_emlrtRSI = { 25, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo tc_emlrtRSI = { 26, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo uc_emlrtRSI = { 33, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo vc_emlrtRSI = { 34, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo wc_emlrtRSI = { 40, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo xc_emlrtRSI = { 41, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo yc_emlrtRSI = { 42, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo ad_emlrtRSI = { 44, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo bd_emlrtRSI = { 47, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

static emlrtRSInfo cd_emlrtRSI = { 55, /* lineNo */
  "massF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF4.m"/* pathName */
};

/* Function Definitions */
void massF4(const emlrtStack *sp, const real_T in1[34], const real_T in2[60],
            real_T out1[36], real_T out2[180], real_T out3[180], real_T out4[6])
{
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t16;
  real_T t20;
  real_T t22;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t21;
  real_T t43;
  real_T t23;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t45;
  real_T t46;
  real_T t47;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF4 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF4(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 19:49:55 */
  st.site = &rc_emlrtRSI;
  st.site = &sc_emlrtRSI;
  t4 = in1[2] * in1[2];
  st.site = &tc_emlrtRSI;
  t5 = in1[3] * in1[3];
  t7 = 1.0 / in1[33];
  st.site = &uc_emlrtRSI;
  st.site = &vc_emlrtRSI;
  t16 = t4 - t5;
  t20 = -in1[0] * ((in1[18] * in1[18] * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t20;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t20;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t20;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t22 = in1[4] * in1[0];
  t20 = t22 * (t7 * (t4 * 3.0 + t5 * 3.0) / 12.0 + in1[4] * in1[4] * (in1[33] *
    in1[33]) / 300.0) * t16 * 3.1415926535897931 * -0.2;
  out1[21] = t20;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t20;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t22 * t7 * t16 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0) * -0.2;
  st.site = &wc_emlrtRSI;
  t17 = in2[21] * in2[21];
  st.site = &xc_emlrtRSI;
  t18 = in2[22] * in2[22];
  st.site = &yc_emlrtRSI;
  t19 = in2[23] * in2[23];
  t20 = ((-t17 - t18) - t19) + 1.0;
  st.site = &ad_emlrtRSI;
  if (t20 < 0.0) {
    b_st.site = &pb_emlrtRSI;
    error(&b_st);
  }

  t4 = muDoubleScalarSqrt(t20);
  t21 = 1.0 / t4;
  t22 = in2[23] * 2.0;
  t43 = in2[21] * in2[22];
  t23 = t43 * t21 * 2.0;
  st.site = &bd_emlrtRSI;
  t4 *= 2.0;
  t5 = in2[21] * in2[23] * t21 * 2.0;
  t7 = in2[21] * 2.0;
  t16 = in2[22] * in2[23] * t21 * 2.0;
  memset(&out2[0], 0, 108U * sizeof(real_T));
  out2[108] = 1.0;
  out2[109] = 0.0;
  out2[110] = 0.0;
  out2[111] = 0.0;
  out2[112] = 0.0;
  out2[113] = 0.0;
  out2[114] = 0.0;
  out2[115] = 1.0;
  out2[116] = 0.0;
  out2[117] = 0.0;
  out2[118] = 0.0;
  out2[119] = 0.0;
  out2[120] = 0.0;
  out2[121] = 0.0;
  out2[122] = 1.0;
  out2[123] = 0.0;
  out2[124] = 0.0;
  out2[125] = 0.0;
  out2[126] = 0.0;
  out2[127] = 0.0;
  out2[128] = 0.0;
  out2[129] = t4 + t17 * t21 * 2.0;
  out2[130] = -t22 + t23;
  out2[131] = in2[22] * 2.0 + t5;
  out2[132] = 0.0;
  out2[133] = 0.0;
  out2[134] = 0.0;
  out2[135] = t22 + t23;
  out2[136] = t4 + t18 * t21 * 2.0;
  out2[137] = -t7 + t16;
  out2[138] = 0.0;
  out2[139] = 0.0;
  out2[140] = 0.0;
  out2[141] = in2[22] * -2.0 + t5;
  out2[142] = t7 + t16;
  out2[143] = t4 + t19 * t21 * 2.0;
  memset(&out2[144], 0, 36U * sizeof(real_T));
  st.site = &cd_emlrtRSI;
  t29 = 1.0 / muDoubleScalarPower(t20, 1.5);
  t30 = in2[22] * t21 * 2.0;
  t31 = in2[22] * t17 * t29 * 2.0;
  t32 = in2[21] * t21 * 2.0;
  t33 = t43 * in2[23] * t29 * 2.0;
  t4 = in2[23] * t21 * 2.0;
  t5 = in2[23] * t17 * t29 * 2.0;
  t7 = t30 + t31;
  t16 = in2[21] * t18 * t29 * 2.0;
  t20 = t32 + t16;
  t22 = in2[23] * t18 * t29 * 2.0;
  t23 = t4 + t5;
  t43 = in2[21] * t19 * t29 * 2.0;
  t21 = t4 + t22;
  t45 = in2[22] * t19 * t29 * 2.0;
  t46 = t32 + t43;
  t47 = t30 + t45;
  memset(&out3[0], 0, 129U * sizeof(real_T));
  out3[129] = (t7 * in2[52] + t23 * in2[53]) + in2[51] * (t32 + in2[21] * t17 *
    t29 * 2.0);
  out3[130] = (t7 * in2[51] + (t33 + 2.0) * in2[53]) - in2[52] * (t32 - t16);
  out3[131] = ((t33 - 2.0) * in2[52] + t23 * in2[51]) - in2[53] * (t32 - t43);
  out3[132] = 0.0;
  out3[133] = 0.0;
  out3[134] = 0.0;
  out3[135] = (t20 * in2[52] + (t33 - 2.0) * in2[53]) - in2[51] * (t30 - t31);
  out3[136] = (t20 * in2[51] + t21 * in2[53]) + in2[52] * (t30 + in2[22] * t18 *
    t29 * 2.0);
  out3[137] = ((t33 + 2.0) * in2[51] + t21 * in2[52]) - in2[53] * (t30 - t45);
  out3[138] = 0.0;
  out3[139] = 0.0;
  out3[140] = 0.0;
  out3[141] = ((t33 + 2.0) * in2[52] + t46 * in2[53]) - in2[51] * (t4 - t5);
  out3[142] = ((t33 - 2.0) * in2[51] + t47 * in2[53]) - in2[52] * (t4 - t22);
  out3[143] = (t46 * in2[51] + t47 * in2[52]) + in2[53] * (t4 + in2[23] * t19 *
    t29 * 2.0);
  memset(&out3[144], 0, 36U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF4.c) */
