/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF6.c
 *
 * Code generation for function 'massF6'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF6.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo od_emlrtRSI = { 20, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo pd_emlrtRSI = { 21, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo qd_emlrtRSI = { 29, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo rd_emlrtRSI = { 30, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo sd_emlrtRSI = { 31, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo td_emlrtRSI = { 33, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo ud_emlrtRSI = { 34, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

static emlrtRSInfo vd_emlrtRSI = { 46, /* lineNo */
  "massF6",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF6.m"/* pathName */
};

/* Function Definitions */
void massF6(const emlrtStack *sp, const real_T in1[34], const real_T in2[60],
            real_T out1[36], real_T out2[180], real_T out3[180], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t15;
  real_T t53;
  real_T t17;
  real_T t54;
  real_T t18;
  real_T t21;
  real_T t22;
  real_T out2_tmp;
  real_T t52;
  real_T b_out2_tmp;
  real_T t23;
  real_T t24_tmp;
  real_T t26;
  real_T t27;
  real_T t30;
  real_T t31_tmp;
  real_T t33;
  real_T t35;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T out3_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF6 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF6(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 19:49:56 */
  st.site = &od_emlrtRSI;
  t2 = in1[16] * in1[16];
  st.site = &pd_emlrtRSI;
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  st.site = &qd_emlrtRSI;
  t9 = in2[27] * in2[27];
  st.site = &rd_emlrtRSI;
  t10 = in2[28] * in2[28];
  st.site = &sd_emlrtRSI;
  t11 = in2[29] * in2[29];
  t12 = ((-t9 - t10) - t11) + 1.0;
  st.site = &td_emlrtRSI;
  if (t12 < 0.0) {
    b_st.site = &pb_emlrtRSI;
    error(&b_st);
  }

  t2 = muDoubleScalarSqrt(t12);
  t13 = 1.0 / t2;
  st.site = &ud_emlrtRSI;
  t15 = in1[16] * t2;
  t53 = in1[16] * in2[29];
  t17 = in2[29] * 2.0;
  t54 = in2[27] * in2[28];
  t18 = t54 * t13 * 2.0;
  t2 *= 2.0;
  t3 = in2[27] * in2[29] * t13 * 2.0;
  t21 = in2[27] * 2.0;
  t22 = in2[28] * in2[29] * t13 * 2.0;
  memset(&out2[0], 0, 144U * sizeof(real_T));
  out2[144] = 1.0;
  out2[145] = 0.0;
  out2[146] = 0.0;
  out2[147] = 0.0;
  out2[148] = 0.0;
  out2[149] = 0.0;
  out2[150] = 0.0;
  out2[151] = 1.0;
  out2[152] = 0.0;
  out2[153] = 0.0;
  out2[154] = 0.0;
  out2[155] = 0.0;
  out2[156] = 0.0;
  out2[157] = 0.0;
  out2[158] = 1.0;
  out2[159] = 0.0;
  out2[160] = 0.0;
  out2[161] = 0.0;
  out2_tmp = in1[16] * in2[27];
  t52 = out2_tmp * in2[28];
  b_out2_tmp = t52 * t13;
  out2[162] = t53 - b_out2_tmp;
  out2[163] = -t15 + in1[16] * t9 * t13;
  out2[164] = out2_tmp * -2.0;
  out2[165] = t2 + t9 * t13 * 2.0;
  out2[166] = -t17 + t18;
  out2[167] = in2[28] * 2.0 + t3;
  out2[168] = t15 - in1[16] * t10 * t13;
  out2[169] = t53 + b_out2_tmp;
  b_out2_tmp = in1[16] * in2[28];
  out2[170] = b_out2_tmp * -2.0;
  out2[171] = t17 + t18;
  out2[172] = t2 + t10 * t13 * 2.0;
  out2[173] = -t21 + t22;
  out2[174] = out2_tmp - b_out2_tmp * in2[29] * t13;
  out2[175] = b_out2_tmp + out2_tmp * in2[29] * t13;
  out2[176] = 0.0;
  out2[177] = in2[28] * -2.0 + t3;
  out2[178] = t21 + t22;
  out2[179] = t2 + t11 * t13 * 2.0;
  st.site = &vd_emlrtRSI;
  t23 = 1.0 / muDoubleScalarPower(t12, 1.5);
  t24_tmp = out2_tmp * t13;
  t26 = t24_tmp + out2_tmp * t10 * t23;
  t2 = t52 * in2[29] * t23;
  t27 = in1[16] - t2;
  t3 = t53 * t13;
  t30 = t3 + t53 * t10 * t23;
  t31_tmp = b_out2_tmp * t13;
  t33 = t31_tmp + b_out2_tmp * t9 * t23;
  t35 = in1[16] + t2;
  t37 = t3 + t53 * t9 * t23;
  t38 = in2[28] * t13 * 2.0;
  t39 = in2[28] * t9 * t23 * 2.0;
  t40 = in2[27] * t13 * 2.0;
  t41 = t54 * in2[29] * t23 * 2.0;
  t2 = in2[29] * t13 * 2.0;
  t3 = in2[29] * t9 * t23 * 2.0;
  t21 = t38 + t39;
  t22 = in2[27] * t10 * t23 * 2.0;
  t12 = t40 + t22;
  t15 = in2[29] * t10 * t23 * 2.0;
  t17 = t2 + t3;
  t18 = in2[27] * t11 * t23 * 2.0;
  t52 = t2 + t15;
  t53 = in2[28] * t11 * t23 * 2.0;
  t54 = t40 + t18;
  t13 = t38 + t53;
  memset(&out3[0], 0, 162U * sizeof(real_T));
  out3_tmp = t33 * in2[57];
  out3[162] = (-t26 * in2[58] + t27 * in2[59]) - out3_tmp;
  out3[163] = (in2[57] * (t24_tmp * 3.0 + out2_tmp * t9 * t23) + t33 * in2[58])
    + t37 * in2[59];
  out3[164] = in1[16] * in2[57] * -2.0;
  out3[165] = (t21 * in2[58] + t17 * in2[59]) + in2[57] * (t40 + in2[27] * t9 *
    t23 * 2.0);
  out3[166] = (t21 * in2[57] + (t41 + 2.0) * in2[59]) - in2[58] * (t40 - t22);
  out3[167] = ((t41 - 2.0) * in2[58] + t17 * in2[57]) - in2[59] * (t40 - t18);
  out3[168] = (-in2[58] * (t31_tmp * 3.0 + b_out2_tmp * t10 * t23) - t26 * in2
               [57]) - t30 * in2[59];
  out3[169] = (t26 * in2[58] + out3_tmp) + t35 * in2[59];
  out3[170] = in1[16] * in2[58] * -2.0;
  out3[171] = (t12 * in2[58] + (t41 - 2.0) * in2[59]) - in2[57] * (t38 - t39);
  out3[172] = (t12 * in2[57] + t52 * in2[59]) + in2[58] * (t38 + in2[28] * t10 *
    t23 * 2.0);
  out3[173] = ((t41 + 2.0) * in2[57] + t52 * in2[58]) - in2[59] * (t38 - t53);
  out3[174] = (t27 * in2[57] - t30 * in2[58]) - in2[59] * (t31_tmp + b_out2_tmp *
    t11 * t23);
  out3[175] = (t35 * in2[58] + t37 * in2[57]) + in2[59] * (t24_tmp + out2_tmp *
    t11 * t23);
  out3[176] = 0.0;
  out3[177] = ((t41 + 2.0) * in2[58] + t54 * in2[59]) - in2[57] * (t2 - t3);
  out3[178] = ((t41 - 2.0) * in2[57] + t13 * in2[59]) - in2[58] * (t2 - t15);
  out3[179] = (t54 * in2[57] + t13 * in2[58]) + in2[59] * (t2 + in2[29] * t11 *
    t23 * 2.0);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF6.c) */
