/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * romF.c
 *
 * Code generation for function 'romF'
 *
 */

/* Include files */
#include "romF.h"
#include "rt_nonfinite.h"
#include <string.h>

/* Function Definitions */
void romF(const real_T in1[60], real_T out1[10], real_T out2[87])
{
  real_T t2;
  real_T t7;
  real_T t8;
  real_T t9;

  /* ROMF */
  /*     [OUT1,OUT2] = ROMF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     10-Mar-2021 20:34:04 */
  t2 = in1[48] + in1[38];
  t7 = in1[36] + -in1[50];
  t9 = (in1[50] + in1[39]) - t2;
  t8 = (in1[48] + -in1[35]) + t7;
  out1[0] = 0.0;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = t8;
  out1[4] = 0.0;
  out1[5] = t7;
  out1[6] = t2;
  out1[7] = t9;
  out1[8] = t7;
  out1[9] = t2;
  memset(&out2[0], 0, 27U * sizeof(real_T));
  out2[27] = t8;
  memset(&out2[28], 0, 25U * sizeof(real_T));
  out2[53] = t7;
  out2[54] = t2;
  out2[55] = t9;
  out2[56] = t7;
  out2[57] = t2;
  memset(&out2[58], 0, 29U * sizeof(real_T));
}

/* End of code generation (romF.c) */
