function out1 = sprdmpTt17(in1,in2,s,ds,t_sym)
%SPRDMPTT17
%    OUT1 = SPRDMPTT17(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 23:46:16

out1 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.0;0.0];
