function out1 = sprdmpKx15(in1,in2,s,ds,t_sym)
%SPRDMPKX15
%    OUT1 = SPRDMPKX15(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 23:57:09

out1 = 0.0;
