/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_modal.h"
#include "massF2.h"
#include "error.h"
#include "EOM_modal_data.h"

/* Variable Definitions */
static emlrtRSInfo ac_emlrtRSI = { 21, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo bc_emlrtRSI = { 22, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo cc_emlrtRSI = { 30, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo dc_emlrtRSI = { 31, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo ec_emlrtRSI = { 32, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo fc_emlrtRSI = { 33, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo gc_emlrtRSI = { 38, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo hc_emlrtRSI = { 39, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T out1[36], real_T out2[36])
{
  real_T t2;
  real_T t3;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t17;
  real_T t19_tmp;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t25;
  real_T t26;
  real_T out2_tmp_tmp;
  real_T out2_tmp;
  real_T b_out2_tmp;
  real_T c_out2_tmp;
  real_T d_out2_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 11:19:36 */
  st.site = &ac_emlrtRSI;
  t2 = in1[16] * in1[16];
  st.site = &bc_emlrtRSI;
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  st.site = &cc_emlrtRSI;
  t9 = in1[4] * in1[4];
  st.site = &dc_emlrtRSI;
  t10 = in2[3] * in2[3];
  st.site = &ec_emlrtRSI;
  t11 = in2[4] * in2[4];
  st.site = &fc_emlrtRSI;
  t12 = in2[5] * in2[5];
  t2 = ((-(t9 * t10) - t9 * t11) - t9 * t12) + 1.0;
  st.site = &gc_emlrtRSI;
  if (t2 < 0.0) {
    b_st.site = &kb_emlrtRSI;
    b_error(&b_st);
  }

  t2 = muDoubleScalarSqrt(t2);
  t17 = 1.0 / t2;
  st.site = &hc_emlrtRSI;
  t19_tmp = in1[16] * in1[4];
  t19 = t19_tmp * t2;
  t20 = in1[16] * in2[5] * t9;
  t21 = in2[5] * t9 * 2.0;
  t3 = in1[4] * in2[3];
  t22 = t3 * in2[4] * t9 * t17 * 2.0;
  t23 = in1[4] * t2 * 2.0;
  t3 = t3 * in2[5] * t9 * t17 * 2.0;
  t25 = in2[3] * t9 * 2.0;
  t26 = in1[4] * in2[4] * in2[5] * t9 * t17 * 2.0;
  out2[0] = t9;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = t9;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = t9;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2_tmp_tmp = t19_tmp * in2[3];
  out2_tmp = out2_tmp_tmp * in2[4] * t9 * t17;
  out2[18] = t20 - out2_tmp;
  b_out2_tmp = t19_tmp * t9;
  out2[19] = -t19 + b_out2_tmp * t10 * t17;
  c_out2_tmp = in1[16] * in2[3] * t9;
  out2[20] = c_out2_tmp * -2.0;
  d_out2_tmp = in1[4] * t9;
  out2[21] = t23 + d_out2_tmp * t10 * t17 * 2.0;
  out2[22] = -t21 + t22;
  t2 = in2[4] * t9 * 2.0;
  out2[23] = t3 + t2;
  out2[24] = t19 - b_out2_tmp * t11 * t17;
  out2[25] = t20 + out2_tmp;
  out2_tmp = in1[16] * in2[4] * t9;
  out2[26] = out2_tmp * -2.0;
  out2[27] = t21 + t22;
  out2[28] = t23 + d_out2_tmp * t11 * t17 * 2.0;
  out2[29] = -t25 + t26;
  out2[30] = c_out2_tmp - t19_tmp * in2[4] * in2[5] * t9 * t17;
  out2[31] = out2_tmp + out2_tmp_tmp * in2[5] * t9 * t17;
  out2[32] = 0.0;
  out2[33] = t3 - t2;
  out2[34] = t25 + t26;
  out2[35] = t23 + d_out2_tmp * t12 * t17 * 2.0;
}

/* End of code generation (massF2.c) */
