/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rksF.c
 *
 * Code generation for function 'rksF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rksF.h"

/* Function Definitions */
void rksF(const real_T in1[34], const real_T in2[24], real_T s, real_T r_ks[12])
{
  real_T dv0[12];
  int32_T i0;
  int32_T i1;
  (void)in1;
  (void)s;

  /* RKSF */
  /*     R_KS = RKSF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     30-Jan-2019 18:00:06 */
  dv0[0] = 0.0;
  dv0[1] = in2[0];
  dv0[2] = 0.0;
  dv0[3] = in2[1];
  dv0[4] = 0.0;
  dv0[5] = in2[2];
  dv0[6] = in2[0];
  dv0[7] = in2[6];
  dv0[8] = in2[1];
  dv0[9] = in2[7];
  dv0[10] = in2[2];
  dv0[11] = in2[8];
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 2; i1++) {
      r_ks[i1 + (i0 << 1)] = dv0[i1 + (i0 << 1)];
    }
  }
}

/* End of code generation (rksF.c) */
