/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * loadsF1.c
 *
 * Code generation for function 'loadsF1'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "loadsF1.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo tc_emlrtRSI = { 19, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

static emlrtRSInfo uc_emlrtRSI = { 20, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

static emlrtRSInfo vc_emlrtRSI = { 21, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

static emlrtRSInfo wc_emlrtRSI = { 22, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

static emlrtRSInfo xc_emlrtRSI = { 27, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

static emlrtRSInfo yc_emlrtRSI = { 28, /* lineNo */
  "loadsF1",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/loadsF1.m"/* pathName */
};

/* Function Definitions */
void loadsF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
             real_T out1[36], real_T out2[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t10_tmp;
  real_T t12;
  real_T t13_tmp;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17_tmp;
  real_T t17;
  real_T out1_tmp;
  real_T out1_tmp_tmp;
  real_T b_out1_tmp;
  real_T c_out1_tmp;
  real_T d_out1_tmp;
  real_T e_out1_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* LOADSF1 */
  /*     [OUT1,OUT2] = LOADSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 13:21:32 */
  st.site = &tc_emlrtRSI;
  t2 = in1[4] * in1[4];
  st.site = &uc_emlrtRSI;
  t3 = in2[3] * in2[3];
  st.site = &vc_emlrtRSI;
  t4 = in2[4] * in2[4];
  st.site = &wc_emlrtRSI;
  t5 = in2[5] * in2[5];
  t6 = ((-(t2 * t3) - t2 * t4) - t2 * t5) + 1.0;
  st.site = &xc_emlrtRSI;
  if (t6 < 0.0) {
    b_st.site = &qb_emlrtRSI;
    b_error(&b_st);
  }

  t10_tmp = muDoubleScalarSqrt(t6);
  t6 = 1.0 / t10_tmp;
  st.site = &yc_emlrtRSI;
  t12 = in1[16] * in2[5] * t2 * 2.0;
  t13_tmp = in1[4] * in2[3];
  t13 = t13_tmp * in2[4] * t2 * t6 * 2.0;
  t14 = in1[4] * t10_tmp * 2.0;
  t15 = in2[4] * t2 * 2.0;
  t16 = t13_tmp * in2[5] * t2 * t6 * 2.0;
  t17_tmp = in1[4] * in2[4];
  t17 = t17_tmp * in2[5] * t2 * t6 * 2.0;
  out1[0] = t2;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1_tmp = in1[16] * in1[4];
  out1_tmp_tmp = out1_tmp * in2[3];
  b_out1_tmp = out1_tmp_tmp * in2[4] * t2 * t6 * 2.0;
  out1[3] = t12 - b_out1_tmp;
  c_out1_tmp = out1_tmp * t10_tmp;
  d_out1_tmp = out1_tmp * t2;
  out1[4] = c_out1_tmp * 2.0 - d_out1_tmp * t4 * t6 * 2.0;
  e_out1_tmp = in1[16] * in2[3] * t2;
  out1[5] = e_out1_tmp * 2.0 - out1_tmp * in2[4] * in2[5] * t2 * t6 * 2.0;
  out1[6] = 0.0;
  out1[7] = t2;
  out1[8] = 0.0;
  out1[9] = c_out1_tmp * -2.0 + d_out1_tmp * t3 * t6 * 2.0;
  out1[10] = t12 + b_out1_tmp;
  out1_tmp = in1[16] * in2[4] * t2;
  out1[11] = out1_tmp * 2.0 + out1_tmp_tmp * in2[5] * t2 * t6 * 2.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t2;
  out1[15] = e_out1_tmp * -4.0;
  out1[16] = out1_tmp * -4.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1_tmp = in1[4] * t2;
  out1[21] = t14 + out1_tmp * t3 * t6 * 2.0;
  b_out1_tmp = in2[5] * t2 * 2.0;
  out1[22] = t13 + b_out1_tmp;
  out1[23] = -t15 + t16;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = t13 - b_out1_tmp;
  out1[28] = t14 + out1_tmp * t4 * t6 * 2.0;
  b_out1_tmp = in2[3] * t2 * 2.0;
  out1[29] = t17 + b_out1_tmp;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = t15 + t16;
  out1[34] = t17 - b_out1_tmp;
  out1[35] = t14 + out1_tmp * t5 * t6 * 2.0;
  t6 = in1[4] * in2[5];
  t12 = (t10_tmp * in1[31] + t13_tmp * in1[32]) - t6 * in1[30];
  t13 = (t10_tmp * in1[32] + t17_tmp * in1[30]) - t13_tmp * in1[31];
  t14 = (t10_tmp * in1[30] + t6 * in1[31]) - t17_tmp * in1[32];
  t15 = (t13_tmp * in1[30] + t17_tmp * in1[31]) + t6 * in1[32];
  out2[0] = in1[27];
  out2[1] = in1[28];
  out2[2] = in1[29];
  out2[3] = ((t10_tmp * t14 + t6 * t12) - t17_tmp * t13) + t13_tmp * t15;
  out2[4] = ((t10_tmp * t12 + t13_tmp * t13) - t6 * t14) + t17_tmp * t15;
  out2[5] = ((t10_tmp * t13 - t13_tmp * t12) + t17_tmp * t14) + t6 * t15;
}

/* End of code generation (loadsF1.c) */
