/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF1.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo rb_emlrtRSI = { 24, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo sb_emlrtRSI = { 26, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo tb_emlrtRSI = { 27, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo ub_emlrtRSI = { 30, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo vb_emlrtRSI = { 32, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo wb_emlrtRSI = { 33, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo xb_emlrtRSI = { 42, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo yb_emlrtRSI = { 44, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo ac_emlrtRSI = { 46, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo bc_emlrtRSI = { 47, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo cc_emlrtRSI = { 48, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo dc_emlrtRSI = { 49, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo ec_emlrtRSI = { 54, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo fc_emlrtRSI = { 57, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo gc_emlrtRSI = { 65, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo hc_emlrtRSI = { 66, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T out1[36], real_T out2[36], real_T out3[36], real_T
            out4[6])
{
  real_T t2;
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t8;
  real_T t34;
  real_T t36;
  real_T t37;
  real_T t18;
  real_T t21;
  real_T t31;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t51;
  real_T t38;
  real_T t39;
  real_T t40_tmp;
  real_T t40;
  real_T t41;
  real_T t42_tmp;
  real_T t42;
  real_T t43;
  real_T t44_tmp;
  real_T t44;
  real_T t45;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 13:20:01 */
  st.site = &rb_emlrtRSI;
  t2 = in1[18] * in1[18];
  st.site = &sb_emlrtRSI;
  t4 = in1[2] * in1[2];
  st.site = &tb_emlrtRSI;
  t5 = in1[3] * in1[3];
  t7 = muDoubleScalarSin(in1[20]);
  st.site = &ub_emlrtRSI;
  t8 = 1.0 / (t7 * t7);
  t34 = muDoubleScalarCos(in1[20]);
  st.site = &vb_emlrtRSI;
  st.site = &wb_emlrtRSI;
  t36 = in1[33] * in1[33] * (t34 * t34);
  t37 = in1[0] * (t4 - t5);
  t18 = t37 * (t4 / 4.0 - t5 / 4.0) * 3.1415926535897931;
  st.site = &xb_emlrtRSI;
  t21 = t2 * t8 * (t36 - 1.0) * 1.5;
  st.site = &yb_emlrtRSI;
  st.site = &yb_emlrtRSI;
  st.site = &yb_emlrtRSI;
  t31 = -in1[0] * ((t2 * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t31;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t31;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t31;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t31 = 1.0 / in1[33] * (in1[19] * in1[19]);
  t34 = in1[0] * t2 * t8 * (t36 - 1.0) * 3.1415926535897931;
  out1[21] = t18 - t34 * (t21 + t31 * 3.0);
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t18 - t34 * (t21 + t31 * 2.9999999999999991);
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t37 * 3.1415926535897931 * (t4 / 2.0 - t5 / 2.0) - in1[0] * (t2 *
    t2) / muDoubleScalarPower(t7, 4.0) * ((t36 - 1.0) * (t36 - 1.0)) *
    3.1415926535897931 * 3.0;
  st.site = &ac_emlrtRSI;
  t5 = s * s;
  st.site = &bc_emlrtRSI;
  t23 = in2[3] * in2[3];
  st.site = &cc_emlrtRSI;
  t24 = in2[4] * in2[4];
  st.site = &dc_emlrtRSI;
  t25 = in2[5] * in2[5];
  t4 = ((-(t5 * t23) - t5 * t24) - t5 * t25) + 1.0;
  st.site = &ec_emlrtRSI;
  if (t4 < 0.0) {
    b_st.site = &qb_emlrtRSI;
    b_error(&b_st);
  }

  t34 = muDoubleScalarSqrt(t4);
  t7 = 1.0 / t34;
  t31 = in2[5] * t5 * 2.0;
  t51 = in2[3] * in2[4];
  t2 = t51 * s * t5 * t7 * 2.0;
  st.site = &fc_emlrtRSI;
  t34 = s * t34 * 2.0;
  t8 = in2[3] * in2[5] * s * t5 * t7 * 2.0;
  t36 = in2[3] * t5 * 2.0;
  t37 = in2[4] * in2[5] * s * t5 * t7 * 2.0;
  out2[0] = t5;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = t5;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = t5;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = 0.0;
  out2[20] = 0.0;
  t18 = s * t5;
  out2[21] = t34 + t18 * t23 * t7 * 2.0;
  out2[22] = -t31 + t2;
  t21 = in2[4] * t5 * 2.0;
  out2[23] = t8 + t21;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = 0.0;
  out2[27] = t31 + t2;
  out2[28] = t34 + t18 * t24 * t7 * 2.0;
  out2[29] = -t36 + t37;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = 0.0;
  out2[33] = t8 - t21;
  out2[34] = t36 + t37;
  out2[35] = t34 + t18 * t25 * t7 * 2.0;
  st.site = &gc_emlrtRSI;
  t38 = t5 * t5;
  st.site = &hc_emlrtRSI;
  t39 = 1.0 / muDoubleScalarPower(t4, 1.5);
  t40_tmp = in2[4] * s;
  t40 = t40_tmp * t5 * t7 * 2.0;
  t41 = t40_tmp * t23 * t38 * t39 * 2.0;
  t42_tmp = in2[3] * s;
  t42 = t42_tmp * t5 * t7 * 2.0;
  t43 = t5 * 2.0;
  t44_tmp = in2[5] * s;
  t44 = t44_tmp * t5 * t7 * 2.0;
  t45 = t44_tmp * t23 * t38 * t39 * 2.0;
  t8 = t51 * in2[5] * s * t38 * t39 * 2.0;
  t34 = t43 + t8;
  t36 = t40 + t41;
  t37 = t42_tmp * t24 * t38 * t39 * 2.0;
  t31 = t42 + t37;
  t51 = t44_tmp * t24 * t38 * t39 * 2.0;
  t8 = t43 - t8;
  t18 = t44 + t45;
  t21 = t42_tmp * t25 * t38 * t39 * 2.0;
  t2 = t44 + t51;
  t4 = t40_tmp * t25 * t38 * t39 * 2.0;
  t5 = t42 + t21;
  t7 = t40 + t4;
  memset(&out3[0], 0, 21U * sizeof(real_T));
  out3[21] = (in2[9] * (t42 + t42_tmp * t23 * t38 * t39 * 2.0) + t36 * in2[10])
    + t18 * in2[11];
  out3[22] = (t36 * in2[9] + t34 * in2[11]) - in2[10] * (t42 - t37);
  out3[23] = (-t8 * in2[10] + t18 * in2[9]) - in2[11] * (t42 - t21);
  out3[24] = 0.0;
  out3[25] = 0.0;
  out3[26] = 0.0;
  out3[27] = (t31 * in2[10] - in2[9] * (t40 - t41)) - in2[11] * (t43 - in2[3] *
    in2[4] * in2[5] * s * t38 * t39 * 2.0);
  out3[28] = (in2[10] * (t40 + t40_tmp * t24 * t38 * t39 * 2.0) + t31 * in2[9])
    + t2 * in2[11];
  out3[29] = (t34 * in2[9] + t2 * in2[10]) - in2[11] * (t40 - t4);
  out3[30] = 0.0;
  out3[31] = 0.0;
  out3[32] = 0.0;
  out3[33] = (t34 * in2[10] + t5 * in2[11]) - in2[9] * (t44 - t45);
  out3[34] = (-t8 * in2[9] + t7 * in2[11]) - in2[10] * (t44 - t51);
  out3[35] = (in2[11] * (t44 + t44_tmp * t25 * t38 * t39 * 2.0) + t5 * in2[9]) +
    t7 * in2[10];
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
