/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_k_matF.c
 *
 * Code generation for function 'fj_k_matF'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "fj_k_matF.h"

/* Function Definitions */
void fj_k_matF(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
               real_T s, real_T fj_k_mat[144])
{
  real_T t2;
  real_T a;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t14_tmp_tmp;
  real_T t27;
  real_T t30_tmp;
  real_T fj_k_mat_tmp_tmp_tmp;
  (void)sp;
  (void)in2;
  (void)s;

  /* FJ_K_MATF */
  /*     FJ_K_MAT = FJ_K_MATF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 23:05:52 */
  t2 = 1.0 / in1[33];
  a = muDoubleScalarCos(in1[20]);
  t4 = 1.0 / in1[4];
  t5 = in1[2] * in1[2];
  t6 = in1[3] * in1[3];
  t9 = in1[18] * in1[18];
  t10 = muDoubleScalarSin(in1[20]);
  t11 = 1.0 / (t10 * t10);
  t14_tmp_tmp = in1[33] * in1[33];
  a = t14_tmp_tmp * (a * a);
  t27 = 1.0 / t14_tmp_tmp * (t5 * t5 - t6 * t6) + t9 * t9 * (1.0 /
    muDoubleScalarPower(t10, 4.0)) * ((a - 1.0) * (a - 1.0)) * 6.0;
  t30_tmp = t27 * 3.1415926535897931 / 4.0 - t2 * t9 * t11 * (a - 1.0) * (in1[19]
    * in1[19]) * 3.1415926535897931 * 3.0;
  fj_k_mat_tmp_tmp_tmp = in1[1] * t2 * t4;
  a = fj_k_mat_tmp_tmp_tmp * (t2 * (t5 - t6) - t9 * t11 * (a - 1.0) * 6.0) *
    3.1415926535897931;
  t5 = a * -0.66666666666666663;
  fj_k_mat[0] = t5;
  memset(&fj_k_mat[1], 0, 12U * sizeof(real_T));
  fj_k_mat[13] = t5;
  memset(&fj_k_mat[14], 0, 12U * sizeof(real_T));
  t10 = a * -2.0;
  fj_k_mat[26] = t10;
  memset(&fj_k_mat[27], 0, 12U * sizeof(real_T));
  t14_tmp_tmp = fj_k_mat_tmp_tmp_tmp * t30_tmp * -2.0;
  fj_k_mat[39] = t14_tmp_tmp;
  memset(&fj_k_mat[40], 0, 12U * sizeof(real_T));
  fj_k_mat[52] = in1[1] * t2 * t4 * t30_tmp * -2.0;
  memset(&fj_k_mat[53], 0, 12U * sizeof(real_T));
  a = fj_k_mat_tmp_tmp_tmp * t27 * 3.1415926535897931 * -0.33333333333333331;
  fj_k_mat[65] = a;
  memset(&fj_k_mat[66], 0, 12U * sizeof(real_T));
  fj_k_mat[78] = t5;
  memset(&fj_k_mat[79], 0, 12U * sizeof(real_T));
  fj_k_mat[91] = t5;
  memset(&fj_k_mat[92], 0, 12U * sizeof(real_T));
  fj_k_mat[104] = t10;
  memset(&fj_k_mat[105], 0, 12U * sizeof(real_T));
  fj_k_mat[117] = t14_tmp_tmp;
  memset(&fj_k_mat[118], 0, 12U * sizeof(real_T));
  fj_k_mat[130] = in1[1] * t2 * t4 * t30_tmp * -2.0;
  memset(&fj_k_mat[131], 0, 12U * sizeof(real_T));
  fj_k_mat[143] = a;
}

/* End of code generation (fj_k_matF.c) */
