/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_modal.h"
#include "massF1.h"
#include "error.h"
#include "EOM_modal_data.h"

/* Variable Definitions */
static emlrtRSInfo lb_emlrtRSI = { 24, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo mb_emlrtRSI = { 26, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo nb_emlrtRSI = { 27, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo ob_emlrtRSI = { 30, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo pb_emlrtRSI = { 32, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo qb_emlrtRSI = { 33, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo rb_emlrtRSI = { 42, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo sb_emlrtRSI = { 44, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo tb_emlrtRSI = { 46, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo ub_emlrtRSI = { 47, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo vb_emlrtRSI = { 48, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo wb_emlrtRSI = { 49, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo xb_emlrtRSI = { 54, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

static emlrtRSInfo yb_emlrtRSI = { 57, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T out1[36], real_T out2[36])
{
  real_T t2;
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t8;
  real_T t26;
  real_T t35;
  real_T t36;
  real_T t18;
  real_T t21;
  real_T t22;
  real_T t24;
  real_T t25;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 11:19:35 */
  st.site = &lb_emlrtRSI;
  t2 = in1[18] * in1[18];
  st.site = &mb_emlrtRSI;
  t4 = in1[2] * in1[2];
  st.site = &nb_emlrtRSI;
  t5 = in1[3] * in1[3];
  t7 = muDoubleScalarSin(in1[20]);
  st.site = &ob_emlrtRSI;
  t8 = 1.0 / (t7 * t7);
  t26 = muDoubleScalarCos(in1[20]);
  st.site = &pb_emlrtRSI;
  st.site = &qb_emlrtRSI;
  t35 = in1[33] * in1[33] * (t26 * t26);
  t36 = in1[0] * (t4 - t5);
  t18 = t36 * (t4 / 4.0 - t5 / 4.0) * 3.1415926535897931;
  st.site = &rb_emlrtRSI;
  t21 = t2 * t8 * (t35 - 1.0) * 1.5;
  st.site = &sb_emlrtRSI;
  st.site = &sb_emlrtRSI;
  st.site = &sb_emlrtRSI;
  t22 = -in1[0] * ((t2 * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t22;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t22;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t22;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t22 = 1.0 / in1[33] * (in1[19] * in1[19]);
  t26 = in1[0] * t2 * t8 * (t35 - 1.0) * 3.1415926535897931;
  out1[21] = t18 - t26 * (t21 + t22 * 3.0);
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t18 - t26 * (t21 + t22 * 2.9999999999999991);
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t36 * 3.1415926535897931 * (t4 / 2.0 - t5 / 2.0) - in1[0] * (t2 *
    t2) / muDoubleScalarPower(t7, 4.0) * ((t35 - 1.0) * (t35 - 1.0)) *
    3.1415926535897931 * 3.0;
  st.site = &tb_emlrtRSI;
  t22 = s * s;
  st.site = &ub_emlrtRSI;
  t2 = in2[3] * in2[3];
  st.site = &vb_emlrtRSI;
  t24 = in2[4] * in2[4];
  st.site = &wb_emlrtRSI;
  t25 = in2[5] * in2[5];
  t26 = ((-(t22 * t2) - t22 * t24) - t22 * t25) + 1.0;
  st.site = &xb_emlrtRSI;
  if (t26 < 0.0) {
    b_st.site = &kb_emlrtRSI;
    b_error(&b_st);
  }

  t26 = muDoubleScalarSqrt(t26);
  t4 = 1.0 / t26;
  t5 = in2[5] * t22 * 2.0;
  t7 = in2[3] * in2[4] * s * t22 * t4 * 2.0;
  st.site = &yb_emlrtRSI;
  t8 = s * t26 * 2.0;
  t35 = in2[3] * in2[5] * s * t22 * t4 * 2.0;
  t36 = in2[3] * t22 * 2.0;
  t18 = in2[4] * in2[5] * s * t22 * t4 * 2.0;
  out2[0] = t22;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = t22;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = t22;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = 0.0;
  out2[20] = 0.0;
  t21 = s * t22;
  out2[21] = t8 + t21 * t2 * t4 * 2.0;
  out2[22] = -t5 + t7;
  t26 = in2[4] * t22 * 2.0;
  out2[23] = t35 + t26;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = 0.0;
  out2[27] = t5 + t7;
  out2[28] = t8 + t21 * t24 * t4 * 2.0;
  out2[29] = -t36 + t18;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = 0.0;
  out2[33] = t35 - t26;
  out2[34] = t36 + t18;
  out2[35] = t8 + t21 * t25 * t4 * 2.0;
}

/* End of code generation (massF1.c) */
