/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T s, real_T r_jtip[24])
{
  real_T t2;
  real_T t3;
  real_T t15;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t13;
  real_T t12;
  real_T t18_tmp;
  real_T t14;
  real_T t17_tmp;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t25_tmp;
  real_T t29_tmp;
  real_T t34_tmp;
  real_T t38_tmp;
  real_T t42_tmp;
  real_T t76_tmp;
  real_T t66_tmp;
  real_T b_t66_tmp;
  real_T c_t66_tmp;
  real_T t78_tmp;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 00:06:22 */
  t2 = in1[4] / 3.0;
  t3 = in2[2] + t2;
  t15 = in2[8] + t2;
  t8 = (in2[3] * in2[6] / 2.0 + in2[4] * in2[7] / 2.0) + in2[5] * t15 / 2.0;
  t9 = in2[5] * in2[6] / 2.0;
  t10 = in2[4] * t15 / 2.0;
  t11 = in2[3] * in2[7] / 2.0;
  t13 = in2[4] * in2[6] / 2.0;
  t12 = (t15 + t11) - t13;
  t18_tmp = in2[3] * t15 / 2.0;
  t14 = (in2[7] + t9) - t18_tmp;
  t17_tmp = in2[5] * in2[7] / 2.0;
  t15 = (in2[6] + t10) - t17_tmp;
  t19 = in2[4] * t12 / 2.0;
  t20 = in2[4] * t8 / 2.0;
  t21 = in2[5] * t15 / 2.0;
  t25_tmp = ((((((in2[2] + in2[8]) + t11) - t13) + in1[4] * 0.66666666666666663)
              + in2[5] * t8 / 2.0) + in2[3] * t14 / 2.0) - in2[4] * t15 / 2.0;
  t29_tmp = ((in2[4] / 2.0 + in2[10] / 2.0) + in2[5] * in2[9] / 4.0) - in2[3] *
    in2[11] / 4.0;
  t15 = in2[14] + t2;
  t34_tmp = ((in2[3] / 2.0 + in2[9] / 2.0) + in2[4] * in2[11] / 4.0) - in2[5] *
    in2[10] / 4.0;
  t38_tmp = (in2[3] * in2[9] / 4.0 + in2[4] * in2[10] / 4.0) + in2[5] * in2[11] /
    4.0;
  t42_tmp = ((in2[5] / 2.0 + in2[11] / 2.0) + in2[3] * in2[10] / 4.0) - in2[4] *
    in2[9] / 4.0;
  t11 = (t15 * (t38_tmp - 1.0) + in2[12] * t29_tmp) - in2[13] * t34_tmp;
  t13 = (in2[13] * t42_tmp + in2[12] * (t38_tmp - 1.0)) - t29_tmp * t15;
  t2 = (in2[12] * t34_tmp + in2[13] * t29_tmp) + t15 * t42_tmp;
  t15 = (t15 * t34_tmp + in2[13] * (t38_tmp - 1.0)) - in2[12] * t42_tmp;
  t76_tmp = in2[5] * t14 / 2.0;
  t66_tmp = ((in2[0] + in2[6]) + t10) + in2[3] * t8 / 2.0;
  b_t66_tmp = (t66_tmp - t17_tmp) + t19;
  c_t66_tmp = ((((b_t66_tmp + t42_tmp * t15) + t34_tmp * t2) + (t38_tmp - 1.0) *
                t13) - t29_tmp * t11) - t76_tmp;
  t78_tmp = in2[3] * t12 / 2.0;
  t10 = (in2[1] + in2[7]) + t9;
  t12 = ((t10 - t18_tmp) + t20) + t21;
  t9 = ((((t12 + t34_tmp * t11) + t29_tmp * t2) + (t38_tmp - 1.0) * t15) -
        t42_tmp * t13) - t78_tmp;
  t13 = (((t25_tmp + t29_tmp * t13) + t42_tmp * t2) + (t38_tmp - 1.0) * t11) -
    t34_tmp * t15;
  t2 = ((t34_tmp + in2[17] * t29_tmp / 2.0) - in2[16] * t42_tmp / 2.0) - in2[15]
    * (t38_tmp - 1.0) / 2.0;
  t14 = (((t38_tmp + in2[15] * t34_tmp / 2.0) + in2[16] * t29_tmp / 2.0) + in2
         [17] * t42_tmp / 2.0) - 1.0;
  t8 = ((t29_tmp + in2[15] * t42_tmp / 2.0) - in2[17] * t34_tmp / 2.0) - in2[16]
    * (t38_tmp - 1.0) / 2.0;
  t11 = ((t42_tmp + in2[16] * t34_tmp / 2.0) - in2[15] * t29_tmp / 2.0) - in2[17]
    * (t38_tmp - 1.0) / 2.0;
  r_jtip[0] = in2[0];
  r_jtip[1] = ((t66_tmp + t19) - t17_tmp) - t76_tmp;
  r_jtip[2] = c_t66_tmp;
  r_jtip[3] = c_t66_tmp;
  r_jtip[4] = in2[1];
  r_jtip[5] = (((t10 + t20) + t21) - t18_tmp) - t78_tmp;
  r_jtip[6] = t9;
  r_jtip[7] = t9;
  r_jtip[8] = t3;
  r_jtip[9] = t25_tmp;
  r_jtip[10] = t13;
  r_jtip[11] = t13;
  r_jtip[12] = in2[0];
  r_jtip[13] = b_t66_tmp - t76_tmp;
  r_jtip[14] = c_t66_tmp;
  t15 = in1[16] * t2;
  r_jtip[15] = (c_t66_tmp + t15 * t11 * 2.0) - in1[16] * t14 * t8 * 2.0;
  r_jtip[16] = in2[1];
  r_jtip[17] = t12 - t78_tmp;
  r_jtip[18] = t9;
  r_jtip[19] = (t9 + t15 * t14 * 2.0) + in1[16] * t8 * t11 * 2.0;
  r_jtip[20] = t3;
  r_jtip[21] = t25_tmp;
  r_jtip[22] = t13;
  r_jtip[23] = (((t13 - in1[16] * (t2 * t2)) + in1[16] * (t14 * t14)) - in1[16] *
                (t8 * t8)) + in1[16] * (t11 * t11);
}

/* End of code generation (rjtipF.c) */
