/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "EOM_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo v_emlrtRSI = { 113, /* lineNo */
  "massF1",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF1.m"/* pathName */
};

static emlrtRSInfo x_emlrtRSI = { 122, /* lineNo */
  "massF1",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[18],
            real_T s, real_T out1[36], real_T out2[54], real_T out3[54], real_T
            out4[6])
{
  emlrtStack st;
  real_T b_t199_tmp;
  real_T b_t203_tmp;
  real_T t101;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t108_tmp;
  real_T t109;
  real_T t109_tmp;
  real_T t11;
  real_T t110;
  real_T t140_tmp;
  real_T t143;
  real_T t144;
  real_T t156;
  real_T t157;
  real_T t169;
  real_T t170;
  real_T t173;
  real_T t174;
  real_T t18;
  real_T t187;
  real_T t188;
  real_T t189;
  real_T t191;
  real_T t192;
  real_T t196;
  real_T t196_tmp;
  real_T t197;
  real_T t198;
  real_T t199;
  real_T t199_tmp;
  real_T t2;
  real_T t202;
  real_T t203;
  real_T t203_tmp;
  real_T t4;
  real_T t41;
  real_T t43;
  real_T t49;
  real_T t5;
  real_T t55;
  real_T t59;
  real_T t6;
  real_T t60;
  real_T t62;
  real_T t65;
  real_T t7;
  real_T t71;
  real_T t73;
  real_T t75;
  real_T t82;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t87;
  real_T t89;
  real_T t93_tmp;
  real_T t94;
  real_T t95;
  real_T t96;
  st.prev = sp;
  st.tls = sp->tls;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     27-Feb-2021 16:40:59 */
  t2 = in2[6] * s;
  t4 = in1[2] * in1[2];
  t5 = in1[3] * in1[3];
  t6 = s * 2.0;
  t7 = s * s;
  t11 = 1.0 / in1[33];
  t18 = in2[7] * t7;
  t41 = (s - 0.025) * (s - 0.025);
  t43 = t4 + -t5;
  t65 = -(in1[0] * t11 * t43 * (t4 / 4.0 + t5 / 4.0) * 3.1415926535897931);
  t49 = 1.0 / (muDoubleScalarExp(-(s * 200.0) + 5.0) + 1.0);
  t55 = -(in1[0] * (in1[18] * in1[18] * 6.0 + t43) * 3.1415926535897931);
  out1[0] = t55;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t55;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t55;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t65;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t65;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = -in1[0] * t11 * t43 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0);
  t59 = (t6 - 0.05) * t49;
  t60 = t41 * t49;
  t55 = t49 * ((t7 + -(s / 20.0)) + 0.000625);
  t65 = in2[0] * t6 + t49 * ((in2[0] * s * -2.0 + in2[0] / 20.0) + in2[1] * (t6
    - 0.05));
  t73 = in2[2] * t6 + t49 * ((in2[2] * s * -2.0 + in2[2] / 20.0) + in2[3] * (t6
    - 0.05));
  t75 = (in2[4] * t6 + t49 * ((in2[4] * s * -2.0 + in2[4] / 20.0) + in2[5] * (t6
           - 0.05))) + 1.0;
  t4 = (t2 / 2.0 + t18 / 2.0) + t49 * (((((-t2 + in2[6] / 40.0) + -t18) + in2[7]
    / 1600.0) + in2[8] * t41) + (s - 0.025) * (in2[6] + in2[7] / 20.0)) / 2.0;
  t62 = t6 + -t59;
  t71 = t7 + -t55;
  t2 = t65 * t65;
  t41 = t73 * t73;
  t5 = t75 * t75;
  t82 = muDoubleScalarCos(t4);
  t83 = muDoubleScalarSin(t4);
  t84 = t82 * t82;
  t85 = t83 * t83;
  t4 = (t2 + t41) + t5;
  t87 = 1.0 / (t4 * t4);
  st.site = &v_emlrtRSI;
  if (t4 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t43 = 1.0 / muDoubleScalarSqrt(t4);
  t89 = muDoubleScalarPower(t43, 3.0);
  t4 = t59 * t43;
  t11 = t62 * t43;
  t93_tmp = t75 * t43 + 1.0;
  st.site = &x_emlrtRSI;
  if (t93_tmp < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t94 = muDoubleScalarSqrt(t93_tmp);
  t101 = t4 + -t59 * t5 * t89;
  t95 = 1.0 / t94;
  t102 = t11 + -(t62 * t5 * t89);
  t96 = muDoubleScalarPower(t95, 3.0);
  t103 = 1.4142135623730951 * t82 * t4 * t95 / 2.0;
  t104 = 1.4142135623730951 * t83 * t4 * t95 / 2.0;
  t105 = 1.4142135623730951 * t82 * t11 * t95 / 2.0;
  t106 = 1.4142135623730951 * t83 * t11 * t95 / 2.0;
  t11 = 1.4142135623730951 * t65 * t82 * t43;
  t107 = t11 * t95;
  t108_tmp = 1.4142135623730951 * t73 * t82 * t43;
  t108 = t108_tmp * t95;
  t109_tmp = 1.4142135623730951 * t65 * t83 * t43;
  t109 = t109_tmp * t95;
  t43 *= 1.4142135623730951 * t73 * t83;
  t110 = t43 * t95;
  t18 = 1.4142135623730951 * t59 * t65;
  t4 = t18 * t73;
  t143 = t4 * t82 * t89 * t95 / 2.0;
  t144 = t4 * t83 * t89 * t95 / 2.0;
  t6 = 1.4142135623730951 * t62 * t65;
  t5 = t6 * t73;
  t156 = t5 * t82 * t89 * t95 / 2.0;
  t157 = t5 * t83 * t89 * t95 / 2.0;
  t140_tmp = t7 / 2.0 - t55 / 2.0;
  t4 *= t75;
  t169 = t4 * t82 * t87 * t96 / 4.0;
  t170 = t4 * t83 * t87 * t96 / 4.0;
  t4 = t5 * t75;
  t173 = t4 * t82 * t87 * t96 / 4.0;
  t174 = t4 * t83 * t87 * t96 / 4.0;
  t187 = t107 + t110;
  t188 = t108 + -t109;
  t189 = s * t107 / 4.0 + s * t110 / 4.0;
  t191 = t60 * t107 / 4.0 + t60 * t110 / 4.0;
  t4 = 1.4142135623730951 * t59 * t75;
  t198 = 1.4142135623730951 * t59 * t41;
  t196_tmp = t4 * t41;
  t196 = (((t104 + -(t198 * t83 * t89 * t95 / 2.0)) + -t143) + t196_tmp * t83 *
          t87 * t96 / 4.0) + t169;
  t7 = 1.4142135623730951 * t59 * t2;
  t49 = t4 * t2;
  t197 = (((t103 + -(t7 * t82 * t89 * t95 / 2.0)) + -t144) + t49 * t82 * t87 *
          t96 / 4.0) + t170;
  t4 = 1.4142135623730951 * t62 * t75;
  t199_tmp = 1.4142135623730951 * t62 * t2;
  b_t199_tmp = t4 * t2;
  t199 = (((t105 + -(t199_tmp * t82 * t89 * t95 / 2.0)) + -t157) + b_t199_tmp *
          t82 * t87 * t96 / 4.0) + t174;
  t2 = 1.4142135623730951 * t62 * t41;
  t65 = t4 * t41;
  t202 = (((t106 + -(t2 * t83 * t89 * t95 / 2.0)) + -t156) + t65 * t83 * t87 *
          t96 / 4.0) + t173;
  t5 = t11 * t96;
  t4 = t43 * t96;
  t41 = 1.4142135623730951 * t59 * t73 * t75;
  t55 = t18 * t75;
  t203_tmp = t55 * t82 * t89 * t95;
  b_t203_tmp = t41 * t83 * t89 * t95;
  t203 = ((t203_tmp / 2.0 + b_t203_tmp / 2.0) + t5 * t101 / 4.0) + t4 * t101 /
    4.0;
  t18 = 1.4142135623730951 * t62 * t73 * t75;
  t11 = t6 * t75;
  t59 = t11 * t82 * t89 * t95;
  t62 = t18 * t83 * t89 * t95;
  t73 = ((t59 / 2.0 + t62 / 2.0) + t5 * t102 / 4.0) + t4 * t102 / 4.0;
  t75 = s * t108 / 4.0 + -(s * t109 / 4.0);
  t192 = t60 * t108 / 4.0 + -(t60 * t109 / 4.0);
  t169 = (((t104 + -(t7 * t83 * t89 * t95 / 2.0)) + t143) + t49 * t83 * t87 *
          t96 / 4.0) + -t169;
  t198 = (((t103 + -(t198 * t82 * t89 * t95 / 2.0)) + t144) + t196_tmp * t82 *
          t87 * t96 / 4.0) + -t170;
  t7 = (((t105 + -(t2 * t82 * t89 * t95 / 2.0)) + t157) + t65 * t82 * t87 * t96 /
        4.0) + -t174;
  t49 = (((t106 + -(t199_tmp * t83 * t89 * t95 / 2.0)) + t156) + b_t199_tmp *
         t83 * t87 * t96 / 4.0) + -t173;
  t43 = t108_tmp * t96;
  t5 = t109_tmp * t96;
  t65 = t55 * t83 * t89 * t95;
  t41 = t41 * t82 * t89 * t95;
  t6 = ((t41 / 2.0 + -(t65 / 2.0)) + t43 * t101 / 4.0) + -(t5 * t101 / 4.0);
  t11 = t11 * t83 * t89 * t95;
  t4 = t18 * t82 * t89 * t95;
  t55 = ((t4 / 2.0 + -(t11 / 2.0)) + t43 * t102 / 4.0) + -(t5 * t102 / 4.0);
  out2[0] = t71;
  out2[1] = 0.0;
  out2[2] = 0.0;
  t2 = 1.4142135623730951 * t82 * t94;
  t18 = 1.4142135623730951 * t83 * t94;
  out2[3] = ((t18 * t199 + t2 * t49) - t59 * t188 / 4.0) + t11 * t187 / 4.0;
  out2[4] = ((t2 * t199 - t18 * t49) + t59 * t187 / 4.0) + t11 * t188 / 4.0;
  out2[5] = t188 * t199 + t187 * t49;
  out2[6] = t60;
  out2[7] = 0.0;
  out2[8] = 0.0;
  out2[9] = ((t2 * t169 + t18 * t197) - t203_tmp * t188 / 4.0) + t65 * t187 /
    4.0;
  out2[10] = ((-1.4142135623730951 * t83 * t94 * t169 + t2 * t197) + t203_tmp *
              t187 / 4.0) + t65 * t188 / 4.0;
  out2[11] = t187 * t169 + t188 * t197;
  out2[12] = 0.0;
  out2[13] = t71;
  out2[14] = 0.0;
  t65 = -1.4142135623730951 * t82 * t94;
  out2[15] = ((t65 * t7 + t18 * t202) - t4 * t188 / 4.0) + t62 * t187 / 4.0;
  out2[16] = ((t18 * t7 + t2 * t202) + t4 * t187 / 4.0) + t62 * t188 / 4.0;
  out2[17] = -t187 * t7 + t188 * t202;
  out2[18] = 0.0;
  out2[19] = t60;
  out2[20] = 0.0;
  out2[21] = ((t18 * t196 - t2 * t198) - t41 * t188 / 4.0) + b_t203_tmp * t187 /
    4.0;
  out2[22] = ((t2 * t196 + t18 * t198) + t41 * t187 / 4.0) + b_t203_tmp * t188 /
    4.0;
  out2[23] = t188 * t196 - t187 * t198;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = t71;
  t11 = 1.4142135623730951 * t82 * t95;
  t43 = t11 * t102;
  t5 = 1.4142135623730951 * t83 * t95;
  t4 = t5 * t102;
  out2[27] = ((t2 * t55 - t18 * t73) + t43 * t188 / 4.0) - t4 * t187 / 4.0;
  out2[28] = ((t65 * t73 - t18 * t55) - t43 * t187 / 4.0) - t4 * t188 / 4.0;
  out2[29] = t187 * t55 - t188 * t73;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = t60;
  t43 = t11 * t101;
  t4 = t5 * t101;
  out2[33] = ((t2 * t6 - t18 * t203) + t43 * t188 / 4.0) - t4 * t187 / 4.0;
  out2[34] = ((t65 * t203 - t18 * t6) - t43 * t187 / 4.0) - t4 * t188 / 4.0;
  out2[35] = t187 * t6 - t188 * t203;
  out2[36] = 0.0;
  out2[37] = 0.0;
  out2[38] = 0.0;
  t65 = s * 1.4142135623730951 * t82 * t94;
  t43 = s * 1.4142135623730951 * t83 * t94;
  out2[39] = ((t2 * t189 + t18 * t75) - t65 * t187 / 4.0) - t43 * t188 / 4.0;
  out2[40] = ((t2 * t75 - t18 * t189) - t65 * t188 / 4.0) + t43 * t187 / 4.0;
  out2[41] = ((t187 * t189 + t188 * t75) + s * t84 * t93_tmp / 2.0) + s * t85 *
    t93_tmp / 2.0;
  out2[42] = 0.0;
  out2[43] = 0.0;
  out2[44] = 0.0;
  t65 = t109 * t140_tmp * -0.5 + t108 * t140_tmp / 2.0;
  t43 = t107 * t140_tmp / 2.0 + t110 * t140_tmp / 2.0;
  out2[45] = ((t18 * t65 + t2 * t43) - t2 * t187 * t140_tmp / 2.0) - t18 * t188 *
    t140_tmp / 2.0;
  out2[46] = ((t2 * t65 - t18 * t43) - t2 * t188 * t140_tmp / 2.0) + t18 * t187 *
    t140_tmp / 2.0;
  out2[47] = ((t188 * t65 + t187 * t43) + t84 * t93_tmp * t140_tmp) + t85 *
    t93_tmp * t140_tmp;
  out2[48] = 0.0;
  out2[49] = 0.0;
  out2[50] = 0.0;
  t65 = 1.4142135623730951 * t60 * t82 * t94;
  t43 = 1.4142135623730951 * t60 * t83 * t94;
  out2[51] = ((t2 * t191 + t18 * t192) - t65 * t187 / 4.0) - t43 * t188 / 4.0;
  out2[52] = ((t2 * t192 - t18 * t191) - t65 * t188 / 4.0) + t43 * t187 / 4.0;
  out2[53] = ((t187 * t191 + t188 * t192) + t60 * t84 * t93_tmp / 2.0) + t60 *
    t85 * t93_tmp / 2.0;
  memset(&out3[0], 0, 54U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
