function r_jtip = rjtipF(in1,in2,s)
%RJTIPF
%    R_JTIP = RJTIPF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jan-2019 18:02:20

l_f_sym = in1(:,17);
q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q7 = in2(:,7);
q8 = in2(:,8);
q9 = in2(:,9);
q13 = in2(:,13);
q14 = in2(:,14);
q15 = in2(:,15);
q16 = in2(:,16);
q17 = in2(:,17);
q18 = in2(:,18);
t2 = q16.^2;
t3 = q17.^2;
t4 = q18.^2;
t5 = -t2-t3-t4+1.0;
t6 = sqrt(t5);
r_jtip = reshape([q1,q7,q13,q13,q2,q8,q14,q14,q3,q9,q15,q15,q1,q7,q13,q13+l_f_sym.*q16.*q18.*2.0+l_f_sym.*q17.*t6.*2.0,q2,q8,q14,q14+l_f_sym.*q17.*q18.*2.0-l_f_sym.*q16.*t6.*2.0,q3,q9,q15,q15-l_f_sym.*t2-l_f_sym.*t3+l_f_sym.*t4-l_f_sym.*(t2+t3+t4-1.0)],[4,6]);
