/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "massF1.h"

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T out1[36], real_T out2[36], real_T out3[36], real_T
            out4[6])
{
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t16;
  real_T t35;
  real_T t58;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t28_tmp;
  real_T b_t28_tmp;
  real_T t28;
  real_T t33_tmp;
  real_T t66;
  real_T t33;
  real_T t36_tmp;
  real_T t37;
  real_T t104;
  real_T t38_tmp;
  real_T t40_tmp;
  real_T b_t40_tmp;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t45;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t50;
  real_T t51;
  real_T t52;
  real_T t55_tmp;
  real_T t59;
  real_T t67;
  real_T t72;
  real_T t74;
  real_T t76;
  real_T t77;
  real_T t81;
  real_T t82;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t86_tmp;
  real_T t92;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  real_T t98;
  real_T t99;
  real_T t100;
  real_T t101;
  real_T t105;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t112;
  real_T t113_tmp;
  real_T t114_tmp;
  real_T t116_tmp;
  real_T t117;
  real_T out3_tmp;
  (void)sp;
  (void)s;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 21:10:49 */
  t4 = in1[2] * in1[2];
  t5 = in1[3] * in1[3];
  t7 = 1.0 / in1[33];
  t16 = t4 - t5;
  t35 = -in1[0] * ((in1[18] * in1[18] * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t35;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t35;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t35;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t58 = -in1[4] * in1[0];
  t35 = t58 * (t7 * (t4 * 3.0 + t5 * 3.0) / 12.0 + in1[4] * in1[4] * (in1[33] *
    in1[33]) / 12.0) * t16 * 3.1415926535897931;
  out1[21] = t35;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t35;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t58 * t7 * t16 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0);
  t7 = in2[5] / 2.0;
  t4 = in2[3] / 2.0;
  t5 = in2[4] / 2.0;
  t20 = muDoubleScalarSin(t4);
  t21 = muDoubleScalarSin(t5);
  t22 = muDoubleScalarSin(t7);
  t23 = muDoubleScalarCos(t4);
  t24 = muDoubleScalarCos(t5);
  t25 = muDoubleScalarCos(t7);
  t28_tmp = t22 * t23 * t24;
  t4 = t20 * t21;
  b_t28_tmp = t4 * t25;
  t28 = t28_tmp + b_t28_tmp;
  t5 = t28_tmp / 2.0;
  t7 = b_t28_tmp / 2.0;
  t33_tmp = t20 * t24 * t25;
  t66 = t21 * t22 * t23;
  t33 = t33_tmp + t66;
  t16 = t33_tmp / 2.0;
  t35 = t66 / 2.0;
  t36_tmp = t20 * t22 * t24;
  t37 = t36_tmp / 2.0;
  t104 = t21 * t23 * t25;
  t38_tmp = t36_tmp - t104;
  t40_tmp = t4 * t22;
  b_t40_tmp = t23 * t24 * t25;
  t40 = t40_tmp - b_t40_tmp;
  t41 = t40_tmp / 2.0;
  t42 = t104 / 2.0;
  t4 = b_t40_tmp / 2.0;
  t45 = t5 + t7;
  t47 = t16 + t35;
  t48 = t41 - t4;
  t49 = t37 + t42;
  t50 = t41 + t4;
  t51 = t5 - t7;
  t52 = t16 - t35;
  t4 = t28 * t45 * 2.0;
  t5 = t33 * t47 * 2.0;
  t55_tmp = t37 - t42;
  t7 = t40 * t48 * 2.0;
  t16 = t28 * t47 * 2.0;
  t58 = t33 * t45 * 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = 0.0;
  out2[20] = 0.0;
  out2[21] = ((t38_tmp * t47 * -2.0 + t40 * t45 * 2.0) - t33 * (t37 - t21 * t23 *
    t25 / 2.0) * 2.0) + t28 * (t41 - t23 * t24 * t25 / 2.0) * 2.0;
  out2[22] = ((t16 + t58) + t40 * t55_tmp * 2.0) + t48 * t38_tmp * 2.0;
  out2[23] = ((-t4 + t5) + t7) - t38_tmp * t55_tmp * 2.0;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = 0.0;
  out2[27] = ((t28 * t51 * -2.0 + t33 * t52 * 2.0) - t38_tmp * t49 * 2.0) - t40 *
    t50 * 2.0;
  out2[28] = ((t28 * t49 * 2.0 - t33 * t50 * 2.0) - t38_tmp * t51 * 2.0) - t40 *
    t52 * 2.0;
  out2[29] = ((t28 * t50 * 2.0 + t33 * t49 * 2.0) - t40 * t51 * 2.0) + t52 *
    t38_tmp * 2.0;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = 0.0;
  out2[33] = ((t33 * t48 * -2.0 + t28 * t55_tmp * 2.0) - t38_tmp * t45 * 2.0) +
    t40 * t47 * 2.0;
  out2[34] = ((t4 + t5) + t7) + t55_tmp * t38_tmp * 2.0;
  out2[35] = ((-t16 + t58) - t38_tmp * t48 * 2.0) + t40 * (t37 - t42) * 2.0;
  t59 = t66 / 4.0;
  t37 = b_t28_tmp / 4.0;
  t16 = t40_tmp / 4.0;
  t7 = b_t40_tmp / 4.0;
  t5 = t104 / 4.0;
  t4 = t36_tmp / 4.0;
  t35 = t28_tmp / 4.0;
  t66 = t37 + t35;
  t67 = t33_tmp / 4.0;
  t58 = t59 + t67;
  t41 = t5 - t4;
  t42 = t16 - t7;
  t72 = t5 + t4;
  t74 = t16 + t7;
  t76 = t51 * t55_tmp * 2.0;
  t77 = t59 - t67;
  t81 = ((t28 * t58 * 2.0 + t42 * t38_tmp * 2.0) + t40 * t41 * 2.0) - t33 * t66 *
    2.0;
  t82 = t38_tmp * t77 * 2.0;
  t83 = t45 * t50 * 2.0;
  t84 = t47 * t49 * 2.0;
  t85 = t52 * t55_tmp * 2.0;
  t86_tmp = t37 - t35;
  t92 = t45 * t45 * 2.0;
  t94 = t47 * t47;
  t95 = t48 * t48;
  t96 = t28 * t86_tmp * 2.0;
  t97 = t33 * t77 * 2.0;
  t98 = t40 * t74 * 2.0;
  t99 = t45 * t51 * 2.0;
  t100 = t47 * t52 * 2.0;
  t101 = t49 * t55_tmp * 2.0;
  t16 = t33 * t41 * 2.0;
  t35 = t38_tmp * t58 * 2.0;
  t104 = t40 * t66 * 2.0;
  t105 = t40 * t72 * 2.0;
  t106 = t47 * t51 * 2.0;
  t107 = t45 * t52 * 2.0;
  t108 = t48 * t49 * 2.0;
  t4 = t40 * t58 * 2.0;
  t5 = t33 * t42 * 2.0;
  t7 = t28 * t41 * 2.0 + t66 * t38_tmp * 2.0;
  t112 = (t7 + t4) - t5;
  t113_tmp = t28 * t77 * 2.0;
  t114_tmp = t38_tmp * t74 * 2.0;
  t116_tmp = t48 * t50 * 2.0;
  t117 = (t7 - t4) + t5;
  t4 = t28 * t42 * 2.0;
  memset(&out3[0], 0, 21U * sizeof(real_T));
  out3_tmp = t28 * t72 * 2.0 + t33 * t74 * 2.0;
  t28_tmp = t45 * t49 * 2.0;
  t33_tmp = t47 * t50 * 2.0;
  t36_tmp = t48 * t52 * 2.0;
  t21 = (t33 * t58 * 2.0 + t38_tmp * t41 * 2.0) + t40 * t42 * 2.0;
  b_t40_tmp = t28 * t66 * 2.0;
  out3[21] = (-in2[11] * (((((t21 + t92) - t94 * 2.0) - t95 * 2.0) - b_t40_tmp)
    + t55_tmp * t55_tmp * 2.0) + in2[10] * ((((((out3_tmp + t76) - t28_tmp) -
    t33_tmp) - t36_tmp) + t38_tmp * (t37 - t22 * t23 * t24 / 4.0) * 2.0) - t40 *
    (t59 - t20 * t24 * t25 / 4.0) * 2.0)) + t81 * in2[9];
  t37 = (t96 + t97) + t98;
  b_t28_tmp = t38_tmp * t72 * 2.0;
  t40_tmp = ((t16 + t35) + t104) - t4;
  out3[22] = (t112 * in2[11] - in2[10] * (((((t37 + t99) + t100) + t101) -
    t116_tmp) - b_t28_tmp)) + in2[9] * t40_tmp;
  t42 = t50 * t55_tmp * 2.0;
  t66 = t33 * t86_tmp * 2.0;
  t41 = ((t16 - t35) + t104) + t4;
  t58 = t45 * t48 * 4.0;
  t35 = t47 * t55_tmp * 4.0;
  out3[23] = (in2[11] * ((t41 - t58) + t35) - t117 * in2[9]) + in2[10] *
    (((((((t105 - t106) + t107) - t108) + t113_tmp) + t114_tmp) - t42) - t66);
  out3[24] = 0.0;
  out3[25] = 0.0;
  out3[26] = 0.0;
  t16 = t48 * t51 * 2.0;
  t4 = t28 * t74 * 2.0;
  t5 = t33 * t72 * 2.0;
  t7 = t40 * t86_tmp * 2.0;
  out3[27] = (in2[11] * (((((((t82 + t83) + t84) + t85) - t16) - t4) - t5) - t7)
              + t81 * in2[10]) + in2[9] * ((((((out3_tmp - t76) + t28_tmp) +
    t33_tmp) + t36_tmp) - t40 * t77 * 2.0) + t86_tmp * t38_tmp * 2.0);
  out3_tmp = t105 + t106;
  out3[28] = (in2[11] * ((((((out3_tmp + t107) + t108) - t113_tmp) - t42) -
    t114_tmp) - t66) - in2[9] * (((((t37 - t99) - t100) - t101) + t116_tmp) -
    b_t28_tmp)) + in2[10] * t40_tmp;
  out3[29] = (in2[9] * ((((((out3_tmp - t107) + t108) + t113_tmp) + t114_tmp) +
    t42) - t66) - t117 * in2[10]) + in2[11] * (((((((t96 - t98) + t99) - t100) +
    t101) + t116_tmp) - t72 * t38_tmp * 2.0) - t33 * (t59 - t67) * 2.0);
  out3[30] = 0.0;
  out3[31] = 0.0;
  out3[32] = 0.0;
  out3[33] = (t81 * in2[11] - in2[10] * (((((((-t82 + t83) + t84) + t85) - t16)
    + t4) + t5) + t7)) - in2[9] * (((((t21 - t92) + t94 * 2.0) + t95 * 2.0) -
    b_t40_tmp) - t55_tmp * t55_tmp * 2.0);
  out3[34] = (t112 * in2[9] + in2[11] * t40_tmp) - in2[10] * (((((((-t105 + t106)
    + t107) + t108) + t113_tmp) + t114_tmp) - t42) + t66);
  out3[35] = (-t117 * in2[11] - in2[10] * (((((((-t96 + t97) + t98) + t99) -
    t100) + t101) + t116_tmp) + b_t28_tmp)) + in2[9] * ((t41 + t58) - t35);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
