function [out1,out2] = loadsF1(in1,in2,s)
%LOADSF1
%    [OUT1,OUT2] = LOADSF1(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-May-2019 14:15:56

f_tx_sym = in1(:,28);
f_ty_sym = in1(:,29);
f_tz_sym = in1(:,30);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
tau_tx_sym = in1(:,31);
tau_ty_sym = in1(:,32);
tau_tz_sym = in1(:,33);
t2 = q4.^2;
t3 = q5.^2;
t4 = q6.^2;
t5 = -t2-t3-t4+1.0;
t6 = 1.0./sqrt(t5);
t7 = sqrt(t5);
t8 = q6.*(2.9e1./1.0e3);
t9 = q4.*q5.*t6.*2.0;
t10 = t7.*2.0;
t11 = q5.*2.0;
t12 = q4.*q6.*t6.*2.0;
t13 = q5.*q6.*t6.*2.0;
out1 = reshape([1.0,0.0,0.0,t8-q4.*q5.*t6.*(2.9e1./1.0e3),t7.*(2.9e1./1.0e3)-t3.*t6.*(2.9e1./1.0e3),q4.*(2.9e1./1.0e3)-q5.*q6.*t6.*(2.9e1./1.0e3),0.0,1.0,0.0,t7.*(-2.9e1./1.0e3)+t2.*t6.*(2.9e1./1.0e3),t8+q4.*q5.*t6.*(2.9e1./1.0e3),q5.*(2.9e1./1.0e3)+q4.*q6.*t6.*(2.9e1./1.0e3),0.0,0.0,1.0,q4.*(-2.9e1./5.0e2),q5.*(-2.9e1./5.0e2),0.0,0.0,0.0,0.0,t10+t2.*t6.*2.0,q6.*2.0+t9,-t11+t12,0.0,0.0,0.0,q6.*-2.0+t9,t10+t3.*t6.*2.0,q4.*2.0+t13,0.0,0.0,0.0,t11+t12,q4.*-2.0+t13,t10+t4.*t6.*2.0],[6,6]);
if nargout > 1
    t14 = t7.*tau_ty_sym;
    t15 = q4.*tau_tz_sym;
    t28 = q6.*tau_tx_sym;
    t16 = t14+t15-t28;
    t17 = t7.*tau_tz_sym;
    t18 = q5.*tau_tx_sym;
    t27 = q4.*tau_ty_sym;
    t19 = t17+t18-t27;
    t20 = t7.*tau_tx_sym;
    t21 = q6.*tau_ty_sym;
    t29 = q5.*tau_tz_sym;
    t22 = t20+t21-t29;
    t23 = q4.*tau_tx_sym;
    t24 = q5.*tau_ty_sym;
    t25 = q6.*tau_tz_sym;
    t26 = t23+t24+t25;
    out2 = [f_tx_sym;f_ty_sym;f_tz_sym;q6.*t16-q5.*t19+q4.*t26+t7.*t22;q4.*t19-q6.*t22+q5.*t26+t7.*t16;-q4.*t16+q5.*t22+q6.*t26+t7.*t19];
end
