function out1 = sprdmpTt7(in1,in2,s,ds,t_sym)
%SPRDMPTT7
%    OUT1 = SPRDMPTT7(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 18:54:14

out1 = [0.0;0.0;0.0;0.0;0.0;0.0;1.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
