function out1 = sprdmpDl5(in1,in2,s,ds,t_sym)
%SPRDMPDL5
%    OUT1 = SPRDMPDL5(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:06:38

q5 = in2(5,:);
out1 = q5;
