function out1 = sprdmpIn12(in1,in2,s,ds,t_sym)
%SPRDMPIN12
%    OUT1 = SPRDMPIN12(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:06:36

out1 = 0.0;
