function out1 = sprdmpDir4(in1,in2,s,ds,t_sym)
%SPRDMPDIR4
%    OUT1 = SPRDMPDIR4(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:06:34

out1 = 1.0;
