function out1 = sprdmpKx11(in1,in2,s,ds,t_sym)
%SPRDMPKX11
%    OUT1 = SPRDMPKX11(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 18:59:00

out1 = 0.0;
