function out1 = sprdmpVd15(in1,in2,s,ds,t_sym)
%SPRDMPVD15
%    OUT1 = SPRDMPVD15(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 18:59:12

out1 = 0.0;
