function out1 = sprdmpDl2(in1,in2,s,ds,t_sym)
%SPRDMPDL2
%    OUT1 = SPRDMPDL2(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:06:38

q2 = in2(2,:);
out1 = q2;
