function out1 = sprdmpDl17(in1,in2,s,ds,t_sym)
%SPRDMPDL17
%    OUT1 = SPRDMPDL17(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:06:39

q17 = in2(17,:);
out1 = q17;
