function out1 = Tj_uF(in1,in2,s,ds,t_sym)
%TJ_UF
%    OUT1 = TJ_UF(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 19:07:18

out1 = zeros(0,0);
