/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include "massF2.h"
#include "EOM_eq_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo mc_emlrtRSI = { 103,/* lineNo */
  "massF2",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF2.m"/* pathName */
};

static emlrtRSInfo oc_emlrtRSI = { 112,/* lineNo */
  "massF2",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF2.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[18],
            real_T out1[36], real_T out2[54], real_T out3[54], real_T out4[6])
{
  emlrtStack st;
  real_T b_t193_tmp;
  real_T b_t197_tmp;
  real_T b_t201_tmp;
  real_T b_t203_tmp;
  real_T c_t201_tmp;
  real_T c_t203_tmp;
  real_T d_t203_tmp;
  real_T t100;
  real_T t100_tmp;
  real_T t103;
  real_T t104;
  real_T t106;
  real_T t139;
  real_T t139_tmp_tmp;
  real_T t140;
  real_T t152;
  real_T t152_tmp_tmp;
  real_T t153;
  real_T t16;
  real_T t165;
  real_T t166;
  real_T t169;
  real_T t170;
  real_T t183;
  real_T t184;
  real_T t185;
  real_T t186;
  real_T t187;
  real_T t188;
  real_T t189;
  real_T t190;
  real_T t193;
  real_T t193_tmp;
  real_T t196;
  real_T t197;
  real_T t197_tmp;
  real_T t2;
  real_T t200;
  real_T t200_tmp;
  real_T t201;
  real_T t201_tmp;
  real_T t203;
  real_T t203_tmp;
  real_T t204;
  real_T t3;
  real_T t37;
  real_T t4;
  real_T t5;
  real_T t53;
  real_T t54;
  real_T t56;
  real_T t57;
  real_T t6;
  real_T t63;
  real_T t64;
  real_T t66;
  real_T t68;
  real_T t73;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T t78;
  real_T t80;
  real_T t84_tmp;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  real_T t98_tmp;
  real_T t99;
  real_T t99_tmp;
  st.prev = sp;
  st.tls = sp->tls;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     27-Feb-2021 16:41:05 */
  t2 = in1[4] * in2[6];
  t3 = in1[4] * 2.0;
  t4 = in1[16] * in1[16];
  t5 = in1[4] * in1[4];
  t6 = in1[17] * in1[17];
  t16 = in2[7] * t5;
  t37 = (in1[4] - 0.025) * (in1[4] - 0.025);
  t4 = in1[15] * t4 / 4.0 + in1[15] * (t4 + t6 * 3.0) / 12.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t4;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t4;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t6 / 2.0;
  t4 = 1.0 / (muDoubleScalarExp(-(in1[4] * 200.0) + 5.0) + 1.0);
  t53 = (t3 - 0.05) * t4;
  t54 = t37 * t4;
  t57 = t4 * ((t5 + -(in1[4] / 20.0)) + 0.000625);
  t63 = in2[0] * t3 + t4 * ((in1[4] * in2[0] * -2.0 + in2[0] / 20.0) + in2[1] *
    (t3 - 0.05));
  t64 = in2[2] * t3 + t4 * ((in1[4] * in2[2] * -2.0 + in2[2] / 20.0) + in2[3] *
    (t3 - 0.05));
  t66 = (in2[4] * t3 + t4 * ((in1[4] * in2[4] * -2.0 + in2[4] / 20.0) + in2[5] *
          (t3 - 0.05))) + 1.0;
  t4 = (t2 / 2.0 + t16 / 2.0) + t4 * (((((-t2 + in2[6] / 40.0) + -t16) + in2[7] /
    1600.0) + in2[8] * t37) + (in1[4] - 0.025) * (in2[6] + in2[7] / 20.0)) / 2.0;
  t56 = t3 + -t53;
  t3 = t63 * t63;
  t68 = t64 * t64;
  t6 = t66 * t66;
  t73 = muDoubleScalarCos(t4);
  t74 = muDoubleScalarSin(t4);
  t75 = t73 * t73;
  t76 = t74 * t74;
  t4 = (t3 + t68) + t6;
  t78 = 1.0 / (t4 * t4);
  st.site = &mc_emlrtRSI;
  if (t4 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t16 = 1.0 / muDoubleScalarSqrt(t4);
  t80 = muDoubleScalarPower(t16, 3.0);
  t4 = t53 * t16;
  t2 = t56 * t16;
  t84_tmp = t66 * t16 + 1.0;
  st.site = &oc_emlrtRSI;
  if (t84_tmp < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t85 = muDoubleScalarSqrt(t84_tmp);
  t92 = t4 + -t53 * t6 * t80;
  t86 = 1.0 / t85;
  t93 = t2 + -(t56 * t6 * t80);
  t87 = muDoubleScalarPower(t86, 3.0);
  t94 = 1.4142135623730951 * t73 * t4 * t86 / 2.0;
  t95 = 1.4142135623730951 * t74 * t4 * t86 / 2.0;
  t96 = 1.4142135623730951 * t73 * t2 * t86 / 2.0;
  t97 = 1.4142135623730951 * t74 * t2 * t86 / 2.0;
  t98_tmp = 1.4142135623730951 * t63 * t73 * t16;
  t37 = t98_tmp * t86;
  t99_tmp = 1.4142135623730951 * t64 * t73 * t16;
  t99 = t99_tmp * t86;
  t100_tmp = 1.4142135623730951 * t63 * t74 * t16;
  t100 = t100_tmp * t86;
  t16 *= 1.4142135623730951 * t64 * t74;
  t2 = t16 * t86;
  t139_tmp_tmp = 1.4142135623730951 * t53 * t63;
  t4 = t139_tmp_tmp * t64;
  t139 = t4 * t73 * t80 * t86 / 2.0;
  t140 = t4 * t74 * t80 * t86 / 2.0;
  t152_tmp_tmp = 1.4142135623730951 * t56 * t63;
  t6 = t152_tmp_tmp * t64;
  t152 = t6 * t73 * t80 * t86 / 2.0;
  t153 = t6 * t74 * t80 * t86 / 2.0;
  t103 = t37 / 2.0;
  t104 = t99 / 2.0;
  t106 = t2 / 2.0;
  t4 *= t66;
  t165 = t4 * t73 * t78 * t87 / 4.0;
  t166 = t4 * t74 * t78 * t87 / 4.0;
  t4 = t6 * t66;
  t169 = t4 * t73 * t78 * t87 / 4.0;
  t170 = t4 * t74 * t78 * t87 / 4.0;
  t183 = t37 + t2;
  t184 = t99 + -t100;
  t185 = t103 + t106;
  t187 = in1[4] * t37 / 4.0 + in1[4] * t2 / 4.0;
  t189 = t54 * t37 / 4.0 + t54 * t2 / 4.0;
  t4 = 1.4142135623730951 * t53 * t66;
  t193_tmp = 1.4142135623730951 * t53 * t3;
  b_t193_tmp = t4 * t3;
  t193 = (((t94 + -(t193_tmp * t73 * t80 * t86 / 2.0)) + -t140) + b_t193_tmp *
          t73 * t78 * t87 / 4.0) + t166;
  t204 = 1.4142135623730951 * t53 * t68;
  t37 = t4 * t68;
  t196 = (((t95 + -(t204 * t74 * t80 * t86 / 2.0)) + -t139) + t37 * t74 * t78 *
          t87 / 4.0) + t165;
  t4 = 1.4142135623730951 * t56 * t66;
  t197_tmp = 1.4142135623730951 * t56 * t3;
  b_t197_tmp = t4 * t3;
  t197 = (((t96 + -(t197_tmp * t73 * t80 * t86 / 2.0)) + b_t197_tmp * t73 * t78 *
           t87 / 4.0) + -t153) + t170;
  t200_tmp = 1.4142135623730951 * t56 * t68;
  t2 = t4 * t68;
  t200 = (((t97 + -(t200_tmp * t74 * t80 * t86 / 2.0)) + t2 * t74 * t78 * t87 /
           4.0) + -t152) + t169;
  t6 = t98_tmp * t87;
  t4 = t16 * t87;
  t201_tmp = 1.4142135623730951 * t53 * t64 * t66;
  t3 = t139_tmp_tmp * t66;
  b_t201_tmp = t3 * t73 * t80 * t86;
  c_t201_tmp = t201_tmp * t74 * t80 * t86;
  t201 = ((b_t201_tmp / 2.0 + c_t201_tmp / 2.0) + t6 * t92 / 4.0) + t4 * t92 /
    4.0;
  t203_tmp = 1.4142135623730951 * t56 * t64 * t66;
  b_t203_tmp = t152_tmp_tmp * t66;
  c_t203_tmp = b_t203_tmp * t73 * t80 * t86;
  d_t203_tmp = t203_tmp * t74 * t80 * t86;
  t203 = ((c_t203_tmp / 2.0 + d_t203_tmp / 2.0) + t6 * t93 / 4.0) + t4 * t93 /
    4.0;
  t186 = t104 + -(t100 / 2.0);
  t188 = in1[4] * t99 / 4.0 + -(in1[4] * t100 / 4.0);
  t190 = t54 * t99 / 4.0 + -(t54 * t100 / 4.0);
  t94 = (((t94 + -(t204 * t73 * t80 * t86 / 2.0)) + t140) + t37 * t73 * t78 *
         t87 / 4.0) + -t166;
  t165 = (((t95 + -(t193_tmp * t74 * t80 * t86 / 2.0)) + t139) + b_t193_tmp *
          t74 * t78 * t87 / 4.0) + -t165;
  t140 = (((t96 + -(t200_tmp * t73 * t80 * t86 / 2.0)) + t153) + t2 * t73 * t78 *
          t87 / 4.0) + -t170;
  t16 = (((t97 + -(t197_tmp * t74 * t80 * t86 / 2.0)) + t152) + b_t197_tmp * t74
         * t78 * t87 / 4.0) + -t169;
  t6 = t99_tmp * t87;
  t4 = t100_tmp * t87;
  t166 = t3 * t74 * t80 * t86;
  t170 = t201_tmp * t73 * t80 * t86;
  t99 = ((t170 / 2.0 + -(t166 / 2.0)) + t6 * t92 / 4.0) + -(t4 * t92 / 4.0);
  t2 = b_t203_tmp * t74 * t80 * t86;
  t152_tmp_tmp = t203_tmp * t73 * t80 * t86;
  t204 = ((t152_tmp_tmp / 2.0 + -(t2 / 2.0)) + t6 * t93 / 4.0) + -(t4 * t93 /
    4.0);
  t200_tmp = in1[16] * 1.4142135623730951 * t56;
  t193_tmp = t200_tmp * t63 * t66;
  b_t193_tmp = in1[16] * 1.4142135623730951 * t74;
  b_t197_tmp = b_t193_tmp * t85;
  t201_tmp = in1[16] * 1.4142135623730951 * t73;
  b_t203_tmp = t201_tmp * t85;
  t197_tmp = t193_tmp * t73 * t80 * t86;
  t193_tmp = t193_tmp * t74 * t80 * t86;
  t203_tmp = t5 + -t57;
  out2[0] = (((t203_tmp + b_t203_tmp * t197 / 2.0) + b_t197_tmp * t16 / 2.0) -
             t197_tmp * t185 / 4.0) + t193_tmp * t186 / 4.0;
  out2[1] = ((b_t197_tmp * t197 / 2.0 - b_t203_tmp * t16 / 2.0) - t197_tmp *
             t186 / 4.0) - t193_tmp * t185 / 4.0;
  t98_tmp = in1[16] * t56;
  t193_tmp = t98_tmp * t63 * t66;
  t197_tmp = -in1[16] * t185;
  t139_tmp_tmp = in1[16] * t186;
  out2[2] = ((t197_tmp * t197 + t139_tmp_tmp * t16) - t193_tmp * t75 * t80 / 4.0)
    - t193_tmp * t76 * t80 / 4.0;
  t193_tmp = 1.4142135623730951 * t73 * t85;
  t68 = 1.4142135623730951 * t74 * t85;
  out2[3] = ((t68 * t197 + t193_tmp * t16) - c_t203_tmp * t184 / 4.0) + t2 *
    t183 / 4.0;
  out2[4] = ((t193_tmp * t197 - t68 * t16) + c_t203_tmp * t183 / 4.0) + t2 *
    t184 / 4.0;
  out2[5] = t184 * t197 + t183 * t16;
  t4 = in1[16] * 1.4142135623730951 * t53;
  t37 = t4 * t63 * t66;
  t3 = t37 * t73 * t80 * t86;
  t37 = t37 * t74 * t80 * t86;
  out2[6] = (((t54 + b_t203_tmp * t193 / 2.0) + b_t197_tmp * t165 / 2.0) - t3 *
             t185 / 4.0) + t37 * t186 / 4.0;
  out2[7] = ((b_t197_tmp * t193 / 2.0 - b_t203_tmp * t165 / 2.0) - t3 * t186 /
             4.0) - t37 * t185 / 4.0;
  t16 = in1[16] * t53;
  t37 = t16 * t63 * t66;
  out2[8] = ((t197_tmp * t193 + t139_tmp_tmp * t165) - t37 * t75 * t80 / 4.0) -
    t37 * t76 * t80 / 4.0;
  out2[9] = ((t68 * t193 + t193_tmp * t165) - b_t201_tmp * t184 / 4.0) + t166 *
    t183 / 4.0;
  out2[10] = ((t193_tmp * t193 - t68 * t165) + b_t201_tmp * t183 / 4.0) + t166 *
    t184 / 4.0;
  out2[11] = t184 * t193 + t183 * t165;
  t37 = t200_tmp * t64 * t66;
  t3 = t37 * t73 * t80 * t86;
  t37 = t37 * t74 * t80 * t86;
  out2[12] = ((b_t197_tmp * t140 * -0.5 + b_t203_tmp * t200 / 2.0) - t3 * t185 /
              4.0) + t37 * t186 / 4.0;
  out2[13] = (((t203_tmp + b_t203_tmp * t140 / 2.0) + b_t197_tmp * t200 / 2.0) -
              t3 * t186 / 4.0) - t37 * t185 / 4.0;
  t37 = t98_tmp * t64 * t66;
  t3 = -in1[16] * t186;
  t2 = in1[16] * t185;
  out2[14] = ((t3 * t140 - t2 * t200) - t37 * t75 * t80 / 4.0) - t37 * t76 * t80
    / 4.0;
  t37 = -1.4142135623730951 * t73 * t85;
  out2[15] = ((t37 * t140 + t68 * t200) - t152_tmp_tmp * t184 / 4.0) +
    d_t203_tmp * t183 / 4.0;
  out2[16] = ((t68 * t140 + t193_tmp * t200) + t152_tmp_tmp * t183 / 4.0) +
    d_t203_tmp * t184 / 4.0;
  out2[17] = -t183 * t140 + t184 * t200;
  t4 = t4 * t64 * t66;
  t6 = t4 * t73 * t80 * t86;
  t4 = t4 * t74 * t80 * t86;
  out2[18] = ((b_t197_tmp * t94 * -0.5 + b_t203_tmp * t196 / 2.0) - t6 * t185 /
              4.0) + t4 * t186 / 4.0;
  out2[19] = (((t54 + b_t203_tmp * t94 / 2.0) + b_t197_tmp * t196 / 2.0) - t6 *
              t186 / 4.0) - t4 * t185 / 4.0;
  t4 = t16 * t64 * t66;
  out2[20] = ((t3 * t94 - t2 * t196) - t4 * t75 * t80 / 4.0) - t4 * t76 * t80 /
    4.0;
  out2[21] = ((t37 * t94 + t68 * t196) - t170 * t184 / 4.0) + c_t201_tmp * t183 /
    4.0;
  out2[22] = ((t68 * t94 + t193_tmp * t196) + t170 * t183 / 4.0) + c_t201_tmp *
    t184 / 4.0;
  out2[23] = -t183 * t94 + t184 * t196;
  t200_tmp = t201_tmp * t86;
  t3 = t200_tmp * t93;
  b_t193_tmp *= t86;
  t4 = b_t193_tmp * t93;
  out2[24] = ((b_t203_tmp * t203 * -0.5 + b_t197_tmp * t204 / 2.0) + t3 * t185 /
              4.0) - t4 * t186 / 4.0;
  out2[25] = ((b_t203_tmp * t204 * -0.5 - b_t197_tmp * t203 / 2.0) + t3 * t186 /
              4.0) + t4 * t185 / 4.0;
  t3 = in1[16] * t75;
  t4 = in1[16] * t76;
  out2[26] = (((t203_tmp + t3 * t93 / 4.0) + t4 * t93 / 4.0) + t2 * t203) +
    t139_tmp_tmp * t204;
  t201_tmp = 1.4142135623730951 * t73 * t86;
  t203_tmp = t201_tmp * t93;
  t98_tmp = 1.4142135623730951 * t74 * t86;
  t6 = t98_tmp * t93;
  out2[27] = ((t193_tmp * t204 - t68 * t203) + t203_tmp * t184 / 4.0) - t6 *
    t183 / 4.0;
  out2[28] = ((t37 * t203 - t68 * t204) - t203_tmp * t183 / 4.0) - t6 * t184 /
    4.0;
  out2[29] = t183 * t204 - t184 * t203;
  t203_tmp = t200_tmp * t92;
  t6 = b_t193_tmp * t92;
  out2[30] = ((b_t203_tmp * t201 * -0.5 + b_t197_tmp * t99 / 2.0) + t203_tmp *
              t185 / 4.0) - t6 * t186 / 4.0;
  out2[31] = ((b_t203_tmp * t99 * -0.5 - b_t197_tmp * t201 / 2.0) + t203_tmp *
              t186 / 4.0) + t6 * t185 / 4.0;
  out2[32] = (((t54 + t3 * t92 / 4.0) + t4 * t92 / 4.0) + t2 * t201) +
    t139_tmp_tmp * t99;
  t203_tmp = t201_tmp * t92;
  t3 = t98_tmp * t92;
  out2[33] = ((t193_tmp * t99 - t68 * t201) + t203_tmp * t184 / 4.0) - t3 * t183
    / 4.0;
  out2[34] = ((t37 * t201 - t68 * t99) - t203_tmp * t183 / 4.0) - t3 * t184 /
    4.0;
  out2[35] = t183 * t99 - t184 * t201;
  t203_tmp = in1[16] * in1[4] * 1.4142135623730951;
  t37 = t203_tmp * t73 * t85;
  t203_tmp = t203_tmp * t74 * t85;
  out2[36] = ((b_t203_tmp * t188 / 2.0 + b_t197_tmp * t187 / 2.0) - t37 * t186 /
              4.0) - t203_tmp * t185 / 4.0;
  out2[37] = ((b_t203_tmp * t187 * -0.5 + b_t197_tmp * t188 / 2.0) + t37 * t185 /
              4.0) - t203_tmp * t186 / 4.0;
  out2[38] = t197_tmp * t188 + t139_tmp_tmp * t187;
  t203_tmp = in1[4] * 1.4142135623730951 * t73 * t85;
  t37 = in1[4] * 1.4142135623730951 * t74 * t85;
  out2[39] = ((t193_tmp * t187 + t68 * t188) - t203_tmp * t183 / 4.0) - t37 *
    t184 / 4.0;
  out2[40] = ((t193_tmp * t188 - t68 * t187) - t203_tmp * t184 / 4.0) + t37 *
    t183 / 4.0;
  out2[41] = ((t183 * t187 + t184 * t188) + in1[4] * t75 * t84_tmp / 2.0) + in1
    [4] * t76 * t84_tmp / 2.0;
  t203_tmp = t5 / 2.0 - t57 / 2.0;
  t37 = t103 * t203_tmp + t106 * t203_tmp;
  t3 = t104 * t203_tmp + -(t100 / 2.0) * t203_tmp;
  out2[42] = ((b_t197_tmp * t37 / 2.0 + b_t203_tmp * t3 / 2.0) - b_t203_tmp *
              t186 * t203_tmp / 2.0) - b_t197_tmp * t185 * t203_tmp / 2.0;
  out2[43] = ((b_t203_tmp * t37 * -0.5 + b_t197_tmp * t3 / 2.0) + b_t203_tmp *
              t185 * t203_tmp / 2.0) - b_t197_tmp * t186 * t203_tmp / 2.0;
  out2[44] = t139_tmp_tmp * t37 - t2 * t3;
  out2[45] = ((t193_tmp * t37 + t68 * t3) - t193_tmp * t183 * t203_tmp / 2.0) -
    t68 * t184 * t203_tmp / 2.0;
  out2[46] = ((-1.4142135623730951 * t74 * t85 * t37 + t193_tmp * t3) - t193_tmp
              * t184 * t203_tmp / 2.0) + t68 * t183 * t203_tmp / 2.0;
  out2[47] = ((t183 * t37 + t184 * t3) + t75 * t84_tmp * t203_tmp) + t76 *
    t84_tmp * t203_tmp;
  t203_tmp = in1[16] * 1.4142135623730951 * t54;
  t37 = t203_tmp * t73 * t85;
  t203_tmp = t203_tmp * t74 * t85;
  out2[48] = ((b_t203_tmp * t190 / 2.0 + b_t197_tmp * t189 / 2.0) - t37 * t186 /
              4.0) - t203_tmp * t185 / 4.0;
  out2[49] = ((b_t203_tmp * t189 * -0.5 + b_t197_tmp * t190 / 2.0) + t37 * t185 /
              4.0) - t203_tmp * t186 / 4.0;
  out2[50] = t197_tmp * t190 + t139_tmp_tmp * t189;
  b_t197_tmp = 1.4142135623730951 * t54 * t73 * t85;
  b_t203_tmp = 1.4142135623730951 * t54 * t74 * t85;
  out2[51] = ((t193_tmp * t189 + t68 * t190) - b_t197_tmp * t183 / 4.0) -
    b_t203_tmp * t184 / 4.0;
  out2[52] = ((t193_tmp * t190 - t68 * t189) - b_t197_tmp * t184 / 4.0) +
    b_t203_tmp * t183 / 4.0;
  out2[53] = ((t183 * t189 + t184 * t190) + t54 * t75 * t84_tmp / 2.0) + t54 *
    t76 * t84_tmp / 2.0;
  memset(&out3[0], 0, 54U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF2.c) */
