/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rksF.c
 *
 * Code generation for function 'rksF'
 *
 */

/* Include files */
#include "rksF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo j_emlrtRSI = { 56,  /* lineNo */
  "rksF",                              /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rksF.m"/* pathName */
};

static emlrtRSInfo k_emlrtRSI = { 57,  /* lineNo */
  "rksF",                              /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rksF.m"/* pathName */
};

static emlrtRSInfo l_emlrtRSI = { 58,  /* lineNo */
  "rksF",                              /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rksF.m"/* pathName */
};

static emlrtRSInfo m_emlrtRSI = { 59,  /* lineNo */
  "rksF",                              /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rksF.m"/* pathName */
};

static emlrtRTEInfo emlrtRTEI = { 13,  /* lineNo */
  9,                                   /* colNo */
  "sqrt",                              /* fName */
  "C:\\Program Files\\MATLAB\\R2020b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pName */
};

/* Function Definitions */
void rksF(const emlrtStack *sp, const real_T in1[34], const real_T in2[48],
          real_T s, real_T ds, real_T t_sym, real_T out1[60])
{
  emlrtStack st;
  real_T t2;
  real_T t24;
  real_T t25;
  real_T t26;
  real_T x;
  (void)s;
  (void)ds;
  (void)t_sym;
  st.prev = sp;
  st.tls = sp->tls;

  /* RKSF */
  /*     OUT1 = RKSF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     26-Feb-2021 21:20:52 */
  t2 = in1[33] * in1[3];
  st.site = &j_emlrtRSI;
  x = ((-(in2[3] * in2[3]) + -(in2[4] * in2[4])) + -(in2[5] * in2[5])) + 1.0;
  if (x < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t24 = muDoubleScalarSqrt(x);
  st.site = &k_emlrtRSI;
  x = ((-(in2[9] * in2[9]) + -(in2[10] * in2[10])) + -(in2[11] * in2[11])) + 1.0;
  if (x < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t25 = muDoubleScalarSqrt(x);
  st.site = &l_emlrtRSI;
  x = ((-(in2[15] * in2[15]) + -(in2[16] * in2[16])) + -(in2[17] * in2[17])) +
    1.0;
  if (x < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t26 = muDoubleScalarSqrt(x);
  st.site = &m_emlrtRSI;
  x = ((-(in2[21] * in2[21]) - in2[22] * in2[22]) - in2[23] * in2[23]) + 1.0;
  if (x < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  out1[0] = 0.0;
  out1[1] = in2[0];
  out1[2] = in2[6];
  out1[3] = in2[12];
  out1[4] = 0.0;
  out1[5] = in2[1];
  out1[6] = in2[7];
  out1[7] = in2[13];
  out1[8] = 0.0;
  out1[9] = in2[2];
  out1[10] = in2[8];
  out1[11] = in2[14];
  out1[12] = in2[0];
  out1[13] = in2[6];
  out1[14] = in2[12];
  out1[15] = in2[18];
  out1[16] = in2[1];
  out1[17] = in2[7];
  out1[18] = in2[13];
  out1[19] = in2[19];
  out1[20] = in2[2];
  out1[21] = in2[8];
  out1[22] = in2[14];
  out1[23] = in2[20];
  out1[24] = 1.0;
  out1[25] = t24;
  out1[26] = t25;
  out1[27] = t26;
  out1[28] = 0.0;
  out1[29] = in2[3];
  out1[30] = in2[9];
  out1[31] = in2[15];
  out1[32] = 0.0;
  out1[33] = in2[4];
  out1[34] = in2[10];
  out1[35] = in2[16];
  out1[36] = 0.0;
  out1[37] = in2[5];
  out1[38] = in2[11];
  out1[39] = in2[17];
  out1[40] = t24;
  out1[41] = t25;
  out1[42] = t26;
  out1[43] = muDoubleScalarSqrt(x);
  out1[44] = in2[3];
  out1[45] = in2[9];
  out1[46] = in2[15];
  out1[47] = in2[21];
  out1[48] = in2[4];
  out1[49] = in2[10];
  out1[50] = in2[16];
  out1[51] = in2[22];
  out1[52] = in2[5];
  out1[53] = in2[11];
  out1[54] = in2[17];
  out1[55] = in2[23];
  out1[56] = t2;
  out1[57] = t2;
  out1[58] = t2;
  out1[59] = t2;
}

/* End of code generation (rksF.c) */
