/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * loadsF1.c
 *
 * Code generation for function 'loadsF1'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "EOM.h"
#include "loadsF1.h"

/* Function Definitions */
void loadsF1(const real_T in1[34], const real_T in2[36], real_T out1[108],
             real_T out2[6])
{
  real_T t2;
  real_T t5_tmp;
  real_T t17_tmp;
  real_T t6_tmp;
  real_T t7;
  real_T t10_tmp;
  real_T t18_tmp;
  real_T t11_tmp;
  real_T t258;
  real_T t259;
  real_T t15_tmp;
  real_T t16;
  real_T t19_tmp;
  real_T t20_tmp;
  real_T t257;
  real_T t22_tmp;
  real_T t26_tmp;
  real_T t26;
  real_T t30;
  real_T t31;
  real_T t33;
  real_T t34;
  real_T t36;
  real_T t185;
  real_T t39_tmp;
  real_T b_t39_tmp;
  real_T t39;
  real_T t161;
  real_T t167;
  real_T t42_tmp;
  real_T t42;
  real_T t46;
  real_T t50;
  real_T t51;
  real_T t52;
  real_T t54;
  real_T t56;
  real_T t57;
  real_T t58;
  real_T t60;
  real_T t62;
  real_T t63;
  real_T t64;
  real_T t66;
  real_T t68;
  real_T t273;
  real_T t163;
  real_T t164;
  real_T t72;
  real_T t75_tmp;
  real_T t78;
  real_T t160;
  real_T t219;
  real_T t81;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t98;
  real_T t99_tmp;
  real_T t99;
  real_T t100;
  real_T t103;
  real_T t104;
  real_T t107;
  real_T t118_tmp;
  real_T b_t118_tmp;
  real_T c_t118_tmp;
  real_T t118;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t125;
  real_T t126;
  real_T t127;
  real_T t128;
  real_T t129;
  real_T t130;
  real_T t131;
  real_T t132;
  real_T t133;
  real_T t134_tmp;
  real_T t134;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t138;
  real_T t139;
  real_T t140;
  real_T t141;
  real_T t142;
  real_T t147;
  real_T t148;
  real_T t149;
  real_T t150;
  real_T t151_tmp;
  real_T t152;
  real_T t154;
  real_T t155;
  real_T t156;
  real_T t157;
  real_T t158;
  real_T t159;
  real_T t162;
  real_T t165;
  real_T t166_tmp;
  real_T t168;
  real_T t169;
  real_T t171;
  real_T t173;
  real_T t189;
  real_T t174;
  real_T t175;
  real_T t176;
  real_T t190;
  real_T t177;
  real_T t178;
  real_T t179;
  real_T t180;
  real_T t181;
  real_T t182;
  real_T t183;
  real_T t191;
  real_T t184;
  real_T t186_tmp;
  real_T t188_tmp;
  real_T t192;
  real_T t193;
  real_T t194;
  real_T t195;
  real_T t196;
  real_T t197;
  real_T t198;
  real_T t199;
  real_T t200;
  real_T t201;
  real_T t202;
  real_T t203;
  real_T t204_tmp;
  real_T t205;
  real_T t206;
  real_T t207;
  real_T t208;
  real_T t209;
  real_T t210;
  real_T t211;
  real_T t212;
  real_T t213;
  real_T t214;
  real_T t215;
  real_T t216;
  real_T t217;
  real_T t218_tmp;
  real_T t220;
  real_T t221;
  real_T t222;
  real_T t223;
  real_T t224;
  real_T t225;
  real_T t226;
  real_T t230;
  real_T t232;
  real_T t234;

  /* LOADSF1 */
  /*     [OUT1,OUT2] = LOADSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 00:06:08 */
  t2 = in1[4] / 3.0;
  t5_tmp = in2[3] * in2[10];
  t17_tmp = in2[4] * in2[9];
  t6_tmp = ((in2[5] / 2.0 + in2[11] / 2.0) + t5_tmp / 4.0) - t17_tmp / 4.0;
  t7 = in2[14] + t2;
  t10_tmp = in2[5] * in2[9];
  t18_tmp = in2[3] * in2[11];
  t11_tmp = ((in2[4] / 2.0 + in2[10] / 2.0) + t10_tmp / 4.0) - t18_tmp / 4.0;
  t258 = in2[4] * in2[11];
  t259 = in2[5] * in2[10];
  t15_tmp = ((in2[3] / 2.0 + in2[9] / 2.0) + t258 / 4.0) - t259 / 4.0;
  t16 = in1[4] / 6.0;
  t19_tmp = in2[3] * in2[9];
  t20_tmp = in2[4] * in2[10];
  t257 = in2[5] * in2[11];
  t22_tmp = (t19_tmp / 4.0 + t20_tmp / 4.0) + t257 / 4.0;
  t26_tmp = t16 + in2[14] / 2.0;
  t26 = (t26_tmp + in2[9] * in2[13] / 4.0) - in2[10] * in2[12] / 4.0;
  t30 = (in2[9] * in2[12] / 4.0 + in2[10] * in2[13] / 4.0) + in2[11] * t7 / 4.0;
  t31 = in2[13] / 2.0;
  t33 = (t31 + in2[11] * in2[12] / 4.0) - in2[9] * t7 / 4.0;
  t34 = in2[12] / 2.0;
  t36 = (t34 + in2[10] * t7 / 4.0) - in2[11] * in2[13] / 4.0;
  t185 = in2[12] * t6_tmp;
  t39_tmp = t7 * t15_tmp;
  b_t39_tmp = in2[13] * (t22_tmp - 1.0);
  t39 = (t39_tmp + b_t39_tmp) - t185;
  t161 = in2[13] * t6_tmp;
  t167 = in2[12] * (t22_tmp - 1.0);
  t42_tmp = t7 * t11_tmp;
  t42 = (t161 + t167) - t42_tmp;
  t46 = ((in2[9] * in2[15] / 8.0 + in2[10] * in2[16] / 8.0) + in2[11] * in2[17] /
         8.0) - 0.5;
  t50 = (((t22_tmp + in2[15] * t15_tmp / 2.0) + in2[16] * t11_tmp / 2.0) + in2
         [17] * t6_tmp / 2.0) - 1.0;
  t51 = in2[9] / 4.0;
  t52 = in2[15] / 4.0;
  t54 = ((t51 + t52) + in2[10] * in2[17] / 8.0) - in2[11] * in2[16] / 8.0;
  t56 = ((t15_tmp + in2[17] * t11_tmp / 2.0) - in2[16] * t6_tmp / 2.0) - in2[15]
    * (t22_tmp - 1.0) / 2.0;
  t57 = in2[10] / 4.0;
  t58 = in2[16] / 4.0;
  t60 = ((t57 + t58) + in2[11] * in2[15] / 8.0) - in2[9] * in2[17] / 8.0;
  t62 = ((t11_tmp + in2[15] * t6_tmp / 2.0) - in2[17] * t15_tmp / 2.0) - in2[16]
    * (t22_tmp - 1.0) / 2.0;
  t63 = in2[11] / 4.0;
  t64 = in2[17] / 4.0;
  t66 = ((t63 + t64) + in2[9] * in2[16] / 8.0) - in2[10] * in2[15] / 8.0;
  t68 = ((t6_tmp + in2[16] * t15_tmp / 2.0) - in2[15] * t11_tmp / 2.0) - in2[17]
    * (t22_tmp - 1.0) / 2.0;
  t273 = in2[12] * t15_tmp;
  t163 = in2[13] * t11_tmp;
  t164 = t6_tmp * t7;
  t72 = (t273 + t163) + t164;
  t75_tmp = in2[8] + t2;
  t78 = t16 + in2[8] / 2.0;
  t160 = t7 * (t22_tmp - 1.0);
  t219 = in2[12] * t11_tmp;
  t16 = in2[13] * t15_tmp;
  t81 = (t160 + t219) - t16;
  t92 = (t22_tmp - 1.0) * t26;
  t93 = t160 / 2.0;
  t94 = in2[4] * in2[6] / 2.0;
  t95 = t219 / 2.0;
  t96 = t11_tmp * t36;
  t98 = in2[9] * t39 / 4.0;
  t99_tmp = in1[16] * t54;
  t99 = t99_tmp * t56 * 2.0;
  t160 = in1[16] * t60;
  t100 = t160 * t62 * 2.0;
  t103 = t273 / 2.0;
  t104 = t163 / 2.0;
  t107 = t164 / 2.0;
  t118_tmp = in1[16] * t46;
  b_t118_tmp = in1[16] * t50;
  c_t118_tmp = in1[16] * t56;
  t118 = ((((((((((((((((in2[3] * in2[6] / 2.0 + in2[4] * in2[7] / 2.0) + t103)
                       + t104) + t6_tmp * t26) + in2[5] * t75_tmp / 4.0) + t107)
                   + t11_tmp * t33) + t15_tmp * t36) + in2[5] * t78 / 2.0) +
                (t22_tmp - 1.0) * t30) + in2[9] * t42 / 4.0) + in2[10] * t39 /
              4.0) + in2[11] * t81 / 4.0) + c_t118_tmp * t60 * 2.0) + b_t118_tmp
           * t66 * 2.0) - t118_tmp * t68 * 2.0) - t99_tmp * t62 * 2.0;
  t121 = t50 * t66 * 2.0;
  t122 = t46 * t68 * 2.0;
  t123 = t54 * t56 * 2.0;
  t124 = t46 * t50 * 2.0;
  t125 = t11_tmp * t30;
  t126 = in2[5] * in2[6] / 2.0;
  t127 = t185 / 2.0;
  t128 = in2[10] * t72 / 4.0;
  t129 = t6_tmp * t36;
  t130 = in2[9] * t81 / 4.0;
  t131 = t118_tmp * t56 * 2.0;
  t132 = b_t118_tmp * t54 * 2.0;
  t133 = t160 * t68 * 2.0;
  t134_tmp = in1[16] * t62;
  t134 = t134_tmp * t66 * 2.0;
  t135 = in2[5] * in2[7] / 2.0;
  t136 = t161 / 2.0;
  t137 = (t22_tmp - 1.0) * t36;
  t138 = t6_tmp * t33;
  t139 = t167 / 2.0;
  t140 = in2[10] * t81 / 4.0;
  t141 = t118_tmp * t62 * 2.0;
  t142 = b_t118_tmp * t60 * 2.0;
  t147 = t50 * t54 * 2.0;
  t148 = t60 * t68 * 2.0;
  t149 = t62 * t66 * 2.0;
  t150 = t46 * t56 * 2.0;
  t151_tmp = t60 * t62 * 2.0;
  t152 = in2[3] * in2[4] / 2.0;
  t154 = in2[3] * in2[3] / 4.0;
  t155 = in2[4] * in2[4];
  t156 = in2[5] * in2[5];
  t157 = in2[3] * in2[5] / 2.0;
  t158 = in2[4] * in2[5] / 2.0;
  t159 = t155 / 4.0;
  t160 = in2[3] * in2[13] / 4.0;
  t161 = in2[4] * in2[12] / 4.0;
  t162 = (t26_tmp + t160) + t161;
  t163 = in2[4] * in2[13] / 4.0;
  t164 = in2[5] * t7 / 4.0;
  t185 = in2[3] * in2[12] / 4.0;
  t165 = (t163 + t164) - t185;
  t166_tmp = t16 / 2.0;
  t167 = in2[5] * in2[12] / 4.0;
  t168 = in2[3] * t7 / 4.0;
  t169 = (-t31 + t167) + t168;
  t36 = in2[5] * in2[13] / 4.0;
  t16 = in2[4] * t7 / 4.0;
  t219 = t34 + t36;
  t171 = t219 - t16;
  t7 = in2[4] * in2[16] / 8.0;
  t173 = in2[5] * in2[17] / 8.0;
  t189 = in2[3] * in2[15] / 8.0;
  t174 = ((t7 + t173) - t189) + 0.5;
  t175 = in2[3] / 4.0;
  t176 = in2[5] * in2[16] / 8.0;
  t190 = in2[4] * in2[17] / 8.0;
  t177 = ((t52 + t175) + t176) - t190;
  t178 = in2[4] / 4.0;
  t179 = in2[3] * in2[17] / 8.0;
  t180 = in2[5] * in2[15] / 8.0;
  t181 = ((-t58 + t178) + t179) + t180;
  t182 = in2[3] * in2[16] / 8.0;
  t183 = in2[4] * in2[15] / 8.0;
  t191 = in2[5] / 4.0;
  t184 = ((t64 + t182) + t183) - t191;
  t186_tmp = t39_tmp / 2.0;
  t188_tmp = b_t39_tmp / 2.0;
  t192 = in2[5] * t72 / 4.0;
  t193 = in2[3] * t39 / 4.0;
  t194 = in2[4] * t42 / 4.0;
  t273 = t26_tmp - t160;
  t195 = t273 - t161;
  t196 = (t31 - t167) + t168;
  t197 = t219 + t16;
  t198 = (-t163 + t164) + t185;
  t199 = in2[3] * t42 / 4.0;
  t200 = ((-t7 + t173) + t189) + 0.5;
  t201 = ((t52 - t175) + t176) + t190;
  t202 = ((t58 + t178) + t179) - t180;
  t203 = ((-t64 + t182) + t183) + t191;
  t204_tmp = t42_tmp / 2.0;
  t205 = in2[3] * t81 / 4.0;
  t206 = in2[5] * t42 / 4.0;
  t207 = (t163 - t164) + t185;
  t208 = in2[3] * t72 / 4.0;
  t209 = t273 + t161;
  t210 = (-t34 + t36) + t16;
  t211 = (t31 + t167) + t168;
  t212 = in2[4] * t81 / 4.0;
  t213 = in2[5] * t39 / 4.0;
  t214 = ((t7 - t173) + t189) + 0.5;
  t215 = ((-t52 + t175) + t176) + t190;
  t216 = ((t58 - t178) + t179) + t180;
  t217 = ((t64 - t182) + t183) + t191;
  t218_tmp = in2[4] * t39 / 4.0;
  t219 = t11_tmp * t15_tmp * 2.0;
  t220 = (t22_tmp - 1.0) * (t22_tmp - 1.0);
  t221 = t15_tmp * t15_tmp;
  t222 = t11_tmp * t11_tmp;
  t223 = t6_tmp * t6_tmp;
  t224 = t11_tmp * (t22_tmp - 1.0) * 2.0;
  t225 = t6_tmp * t15_tmp * 2.0;
  t226 = t6_tmp * t11_tmp * 2.0;
  t230 = ((t19_tmp / 8.0 + t20_tmp / 8.0) + t257 / 8.0) - 0.5;
  t232 = ((t51 + t175) + t258 / 8.0) - t259 / 8.0;
  t234 = ((t57 + t178) + t10_tmp / 8.0) - t18_tmp / 8.0;
  t179 = ((t63 + t191) + t5_tmp / 8.0) - t17_tmp / 8.0;
  t180 = c_t118_tmp * t232 * 2.0;
  t42_tmp = in1[16] * t68;
  t182 = t42_tmp * t179 * 2.0;
  t183 = t62 * t232 * 2.0;
  t34 = t68 * t230 * 2.0;
  t31 = ((t56 * t232 * 2.0 + t62 * t234 * 2.0) + t68 * t179 * 2.0) + t50 * t230 *
    2.0;
  t52 = c_t118_tmp * t230 * 2.0;
  t175 = b_t118_tmp * t232 * 2.0;
  t58 = t134_tmp * t230 * 2.0;
  t178 = t42_tmp * t232 * 2.0;
  t64 = b_t118_tmp * t234 * 2.0;
  t191 = c_t118_tmp * t179 * 2.0;
  t19_tmp = t134_tmp * t232 * 2.0;
  t20_tmp = c_t118_tmp * t234 * 2.0;
  t257 = t68 * t232 * 2.0;
  t258 = t50 * t234 * 2.0;
  t259 = t68 * t234 * 2.0;
  t51 = t56 * t230 * 2.0;
  out1[0] = 1.0;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = t118;
  t10_tmp = in2[3] * in2[7] / 2.0;
  t18_tmp = in2[10] * t42 / 4.0;
  t57 = in2[11] * t72 / 4.0;
  t5_tmp = t6_tmp * t30;
  t17_tmp = t15_tmp * t33;
  t176 = t118_tmp * t50 * 2.0;
  t190 = in1[16] * t66 * t68 * 2.0;
  out1[4] = (((((((((((((((t75_tmp - t92) - t93) - t94) - t95) - t96) - t98) -
                     t99) - t100) + t166_tmp) + t10_tmp) + t18_tmp) + t57) +
               t5_tmp) + t17_tmp) + t176) + t190;
  t167 = in2[11] * t42 / 4.0;
  t168 = in2[3] * t75_tmp / 4.0;
  t173 = in2[3] * t78 / 2.0;
  t189 = t15_tmp * t26;
  t161 = (t22_tmp - 1.0) * t33;
  out1[5] = ((((((((((((((((-in2[7] - t125) - t126) - t127) - t128) - t129) -
                       t130) - t131) - t132) - t133) - t134) + t186_tmp) +
                 t188_tmp) + t167) + t168) + t173) + t189) + t161;
  out1[6] = ((t154 - t155 / 4.0) - t156 / 4.0) + 1.0;
  out1[7] = -in2[5] + t152;
  out1[8] = in2[4] + t157;
  t185 = (t103 + t104) + t107;
  t16 = in2[5] * t81 / 4.0;
  out1[9] = ((((((((((t185 + t199) - t218_tmp) - t16) + t6_tmp * t162) - t11_tmp
                  * t169) + t15_tmp * t171) - (t22_tmp - 1.0) * t165) +
               b_t118_tmp * t184 * 2.0) - c_t118_tmp * t181 * 2.0) - t134_tmp *
             t177 * 2.0) + t42_tmp * t174 * 2.0;
  out1[10] = ((((((((((((-t93 - t95) + t166_tmp) - t192) + t193) + t194) -
                    t6_tmp * t198) - t11_tmp * t197) + t15_tmp * t196) -
                 (t22_tmp - 1.0) * t195) - b_t118_tmp * t200 * 2.0) - c_t118_tmp
               * t201 * 2.0) - t134_tmp * t202 * 2.0) - t42_tmp * t203 * 2.0;
  t36 = in2[4] * t72 / 4.0;
  out1[11] = ((((((((((((-t127 + t186_tmp) + t188_tmp) + t205) + t206) + t36) +
                    t6_tmp * t210) + t11_tmp * t207) + t15_tmp * t209) +
                 (t22_tmp - 1.0) * t211) + b_t118_tmp * t215 * 2.0) + c_t118_tmp
               * t214 * 2.0) - t134_tmp * t217 * 2.0) - t42_tmp * t216 * 2.0;
  out1[12] = ((t220 + t221) - t222) - t223;
  t7 = t6_tmp * (t22_tmp - 1.0) * 2.0;
  out1[13] = t219 + t7;
  out1[14] = -t224 + t225;
  t160 = b_t118_tmp * t179;
  t39_tmp = t42_tmp * t230 * 2.0;
  out1[15] = ((t160 * -2.0 - t20_tmp) - t19_tmp) - t39_tmp;
  b_t39_tmp = b_t118_tmp * t230 * 2.0;
  t26_tmp = t134_tmp * t234 * 2.0;
  out1[16] = ((t180 - t182) + b_t39_tmp) - t26_tmp;
  t163 = t134_tmp * t179 * 2.0;
  t164 = t42_tmp * t234 * 2.0;
  out1[17] = ((-t52 + t175) - t163) + t164;
  out1[18] = 0.0;
  out1[19] = 1.0;
  out1[20] = 0.0;
  out1[21] = ((((((((((((((((-in2[8] - t2) + t92) + t93) + t94) + t95) + t96) +
                       t98) + t99) + t100) - t10_tmp) - t166_tmp) - t18_tmp) -
                 t57) - t5_tmp) - t17_tmp) - t176) - t190;
  out1[22] = t118;
  t10_tmp = in2[11] * t39 / 4.0;
  t18_tmp = in2[4] * t75_tmp / 4.0;
  t57 = in2[9] * t72 / 4.0;
  t5_tmp = in2[4] * t78 / 2.0;
  t17_tmp = t11_tmp * t26;
  t176 = t15_tmp * t30;
  t190 = t99_tmp * t68 * 2.0;
  t273 = c_t118_tmp * t66 * 2.0;
  out1[23] = ((((((((((((((((in2[6] - t135) - t136) - t137) - t138) - t139) -
                        t140) - t141) - t142) + t204_tmp) + t10_tmp) + t18_tmp)
                  + t57) + t5_tmp) + t17_tmp) + t176) + t190) + t273;
  out1[24] = in2[5] + t152;
  out1[25] = ((-t154 - t156 / 4.0) + t159) + 1.0;
  out1[26] = -in2[3] + t158;
  out1[27] = ((((((((((((t93 + t95) - t166_tmp) + t192) + t193) + t194) + t6_tmp
                    * t165) + t11_tmp * t171) + t15_tmp * t169) + (t22_tmp - 1.0)
                 * t162) + b_t118_tmp * t174 * 2.0) + c_t118_tmp * t177 * 2.0) -
              t134_tmp * t181 * 2.0) - t42_tmp * t184 * 2.0;
  t185 -= t199;
  out1[28] = (((((((((t185 + t218_tmp) - t16) + t6_tmp * t195) + t11_tmp * t196)
                  + t15_tmp * t197) - (t22_tmp - 1.0) * t198) - b_t118_tmp *
                t203 * 2.0) + c_t118_tmp * t202 * 2.0) - t134_tmp * t201 * 2.0)
    + t42_tmp * t200 * 2.0;
  out1[29] = ((((((((((((-t136 - t139) + t204_tmp) - t208) + t212) + t213) -
                    t6_tmp * t211) + t11_tmp * t209) - t15_tmp * t207) +
                 (t22_tmp - 1.0) * t210) - b_t118_tmp * t216 * 2.0) + c_t118_tmp
               * t217 * 2.0) + t134_tmp * t214 * 2.0) - t42_tmp * t215 * 2.0;
  out1[30] = t219 - t7;
  t7 = t220 - t221;
  out1[31] = (t7 + t222) - t223;
  t219 = t15_tmp * (t22_tmp - 1.0) * 2.0;
  out1[32] = t226 + t219;
  out1[33] = ((t180 + t182) - b_t39_tmp) - t26_tmp;
  t160 *= 2.0;
  out1[34] = ((t19_tmp + t20_tmp) - t160) - t39_tmp;
  out1[35] = ((-t58 - t178) + t64) + t191;
  out1[36] = 0.0;
  out1[37] = 0.0;
  out1[38] = 1.0;
  out1[39] = ((((((((((((((((in2[7] + t125) + t126) + t127) + t128) + t129) +
                        t130) + t131) + t132) + t133) + t134) - t188_tmp) - t167)
                 - t168) - t173) - t186_tmp) - t189) - t161;
  out1[40] = ((((((((((((((((-in2[6] + t135) + t136) + t137) + t138) + t139) +
                        t140) + t141) + t142) - t10_tmp) - t18_tmp) - t57) -
                  t5_tmp) - t204_tmp) - t17_tmp) - t176) - t190) - t273;
  out1[41] = t118;
  out1[42] = -in2[4] + t157;
  out1[43] = in2[3] + t158;
  out1[44] = ((-t154 + t156 / 4.0) - t159) + 1.0;
  out1[45] = ((((((((((((t127 - t186_tmp) - t188_tmp) + t205) + t206) - t36) -
                    t11_tmp * t165) + t6_tmp * t171) - t15_tmp * t162) +
                 (t22_tmp - 1.0) * t169) + b_t118_tmp * t177 * 2.0) - c_t118_tmp
               * t174 * 2.0) + t134_tmp * t184 * 2.0) - t42_tmp * t181 * 2.0;
  out1[46] = ((((((((((((t136 + t139) - t204_tmp) + t208) + t212) + t213) +
                    t6_tmp * t196) - t11_tmp * t195) + t15_tmp * t198) +
                 (t22_tmp - 1.0) * t197) + b_t118_tmp * t202 * 2.0) + c_t118_tmp
               * t203 * 2.0) - t134_tmp * t200 * 2.0) - t42_tmp * t201 * 2.0;
  out1[47] = (((((((((t185 - t218_tmp) + t16) + t6_tmp * t209) + t11_tmp * t211)
                  - t15_tmp * t210) - (t22_tmp - 1.0) * t207) + b_t118_tmp *
                t217 * 2.0) + c_t118_tmp * t216 * 2.0) + t134_tmp * t215 * 2.0)
    + t42_tmp * t214 * 2.0;
  out1[48] = t224 + t225;
  out1[49] = t226 - t219;
  out1[50] = (t7 - t222) + t223;
  out1[51] = ((t52 + t175) - t163) - t164;
  out1[52] = ((t58 + t178) + t64) + t191;
  out1[53] = ((t19_tmp - t20_tmp) + t160) - t39_tmp;
  out1[54] = 0.0;
  out1[55] = 0.0;
  out1[56] = 0.0;
  t10_tmp = t66 * t68 * 2.0;
  out1[57] = ((t123 + t124) - t151_tmp) - t10_tmp;
  t18_tmp = t54 * t62 * 2.0 + t56 * t60 * 2.0;
  out1[58] = (t18_tmp - t121) - t122;
  t57 = t54 * t68 * 2.0 + t56 * t66 * 2.0;
  t5_tmp = t46 * t62 * 2.0;
  t17_tmp = t50 * t60 * 2.0;
  out1[59] = (t57 + t5_tmp) + t17_tmp;
  out1[60] = 0.0;
  out1[61] = 0.0;
  out1[62] = 0.0;
  out1[63] = ((t50 * t174 * -2.0 + t56 * t177 * 2.0) + t62 * t181 * 2.0) - t68 *
    t184 * 2.0;
  out1[64] = ((t50 * t203 * 2.0 + t56 * t202 * 2.0) + t62 * t201 * 2.0) + t68 *
    t200 * 2.0;
  out1[65] = ((t50 * t216 * 2.0 + t56 * t217 * 2.0) - t62 * t214 * 2.0) - t68 *
    t215 * 2.0;
  out1[66] = 0.0;
  out1[67] = 0.0;
  out1[68] = 0.0;
  out1[69] = t31;
  t176 = t50 * t179 * 2.0;
  t190 = t56 * t234 * 2.0;
  out1[70] = ((-t183 - t34) + t176) + t190;
  t167 = t56 * t179 * 2.0;
  t168 = t62 * t230 * 2.0;
  out1[71] = ((-t257 - t258) + t167) + t168;
  out1[72] = 0.0;
  out1[73] = 0.0;
  out1[74] = 0.0;
  out1[75] = (t18_tmp + t121) + t122;
  t18_tmp = -t123 + t124;
  out1[76] = (t18_tmp + t151_tmp) - t10_tmp;
  out1[77] = ((-t147 + t148) + t149) - t150;
  out1[78] = 0.0;
  out1[79] = 0.0;
  out1[80] = 0.0;
  out1[81] = ((t50 * t184 * 2.0 - t56 * t181 * 2.0) + t62 * t177 * 2.0) - t68 *
    t174 * 2.0;
  out1[82] = ((t50 * t200 * -2.0 - t56 * t201 * 2.0) + t62 * t202 * 2.0) + t68 *
    t203 * 2.0;
  out1[83] = ((t50 * t215 * 2.0 + t56 * t214 * 2.0) + t62 * t217 * 2.0) + t68 *
    t216 * 2.0;
  out1[84] = 0.0;
  out1[85] = 0.0;
  out1[86] = 0.0;
  out1[87] = ((t183 + t34) - t176) - t190;
  out1[88] = t31;
  t176 = t50 * t232 * 2.0;
  t190 = t62 * t179 * 2.0;
  out1[89] = ((-t259 - t51) + t176) + t190;
  out1[90] = 0.0;
  out1[91] = 0.0;
  out1[92] = 0.0;
  out1[93] = (t57 - t5_tmp) - t17_tmp;
  out1[94] = ((t147 + t148) + t149) + t150;
  out1[95] = (t18_tmp - t151_tmp) + t10_tmp;
  out1[96] = 0.0;
  out1[97] = 0.0;
  out1[98] = 0.0;
  out1[99] = ((t50 * t181 * 2.0 + t62 * t174 * 2.0) + t56 * t184 * 2.0) + t68 *
    t177 * 2.0;
  out1[100] = ((t50 * t201 * 2.0 - t56 * t200 * 2.0) - t62 * t203 * 2.0) + t68 *
    t202 * 2.0;
  out1[101] = ((t50 * t214 * -2.0 + t56 * t215 * 2.0) - t62 * t216 * 2.0) + t68 *
    t217 * 2.0;
  out1[102] = 0.0;
  out1[103] = 0.0;
  out1[104] = 0.0;
  out1[105] = ((t257 + t258) - t167) - t168;
  out1[106] = ((t259 + t51) - t176) - t190;
  out1[107] = t31;
  t16 = (t56 * in1[30] + t62 * in1[31]) + t68 * in1[32];
  t160 = (t68 * in1[30] + t50 * in1[31]) - t56 * in1[32];
  t219 = (t50 * in1[30] + t62 * in1[32]) - t68 * in1[31];
  t273 = (t56 * in1[31] + t50 * in1[32]) - t62 * in1[30];
  out2[0] = in1[27];
  out2[1] = in1[28];
  out2[2] = in1[29];
  out2[3] = ((t50 * t219 + t56 * t16) + t62 * t273) - t68 * t160;
  out2[4] = ((t50 * t160 + t62 * t16) - t56 * t273) + t68 * t219;
  out2[5] = ((t50 * t273 + t56 * t160) - t62 * t219) + t68 * t16;
}

/* End of code generation (loadsF1.c) */
