/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
            real_T s, real_T r_jtip[18])
{
  real_T t2;
  real_T t3_tmp;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t11;
  real_T t12;
  real_T t14;
  real_T t17;
  real_T t19;
  real_T t22;
  real_T t24;
  real_T t26;
  real_T t34;
  real_T t35;
  real_T t39_tmp;
  real_T t42_tmp;
  real_T t48_tmp;
  real_T t52_tmp;
  real_T t54_tmp;
  real_T b_t54_tmp;
  real_T t68_tmp;
  real_T t69;
  real_T t72;
  real_T t75;
  real_T t93;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 07:54:24 */
  t2 = in1[4] / 2.0;
  t3_tmp = in2[2] + t2;
  t4 = in2[4] / 2.0;
  t5 = in2[3] / 2.0;
  t6 = in2[5] / 2.0;
  t7 = muDoubleScalarCos(t5);
  t8 = muDoubleScalarCos(t6);
  t9 = muDoubleScalarSin(t4);
  t11 = muDoubleScalarCos(t4);
  t12 = muDoubleScalarSin(t5);
  t6 = muDoubleScalarSin(t6);
  t4 = t7 * t8;
  t14 = t4 * t9 - t11 * t12 * t6;
  t17 = t7 * t11 * t6 + t8 * t9 * t12;
  t19 = in2[8] + t2;
  t22 = t8 * t11 * t12 + t7 * t9 * t6;
  t5 = t4 * t11;
  t4 = t9 * t12 * t6;
  t24 = t5 - t4;
  t26 = -t5 + t4;
  t4 = (in2[6] * t14 + in2[7] * t17) + t19 * t22;
  t5 = (in2[6] * t26 + in2[7] * t22) - t17 * t19;
  t34 = in2[7] * t14;
  t35 = in2[6] * t22;
  t39_tmp = t14 * t19;
  t6 = (-t35 + in2[7] * t26) + t39_tmp;
  t42_tmp = in2[6] * t17;
  t2 = (-t34 + t42_tmp) + t19 * t26;
  t48_tmp = (((in2[1] + t17 * t4) + t14 * t2) + t26 * t6) - t22 * t5;
  t52_tmp = (((t3_tmp + t22 * t4) + t17 * t5) + t26 * t2) - t14 * t6;
  t54_tmp = (in2[0] + t14 * t4) + t26 * t5;
  b_t54_tmp = (t54_tmp + t22 * t6) - t17 * t2;
  t6 = in2[11] / 2.0;
  t4 = in2[9] / 2.0;
  t5 = in2[10] / 2.0;
  t7 = muDoubleScalarCos(t5);
  t12 = muDoubleScalarCos(t6);
  t8 = muDoubleScalarSin(t4);
  t11 = muDoubleScalarCos(t4);
  t2 = muDoubleScalarSin(t5);
  t5 = muDoubleScalarSin(t6);
  t4 = t7 * t12;
  t68_tmp = t4 * t11 - t8 * t2 * t5;
  t69 = t7 * t8 * t5;
  t72 = t4 * t8 + t11 * t2 * t5;
  t75 = t7 * t11 * t5 + t12 * t8 * t2;
  t4 = t12 * t11 * t2;
  t2 = t69 - t4;
  t7 = ((t17 * t2 + t22 * t68_tmp) + t14 * t75) - t26 * t72;
  t5 = t17 * t68_tmp;
  t6 = t14 * t72 + t26 * t75;
  t8 = (t6 + t22 * t2) - t5;
  t11 = t17 * t75 + t22 * t72;
  t12 = t14 * t2;
  t9 = t26 * t68_tmp;
  t93 = (t11 + t9) - t12;
  t6 = (t6 - t5) + t22 * (t69 - t4);
  t5 = ((t17 * t72 + t14 * t68_tmp) + t26 * t2) - t22 * t75;
  r_jtip[0] = in2[0];
  r_jtip[1] = (t54_tmp + t17 * ((t34 - t42_tmp) + t19 * t24)) - t22 * ((t35 +
    in2[7] * t24) - t39_tmp);
  r_jtip[2] = b_t54_tmp;
  r_jtip[3] = in2[1];
  r_jtip[4] = t48_tmp;
  r_jtip[5] = t48_tmp;
  r_jtip[6] = t3_tmp;
  r_jtip[7] = t52_tmp;
  r_jtip[8] = t52_tmp;
  r_jtip[9] = in2[0];
  r_jtip[10] = b_t54_tmp;
  t4 = in1[16] * t7;
  r_jtip[11] = (b_t54_tmp + in1[16] * t8 * ((t11 - t12) + t9) * 2.0) + t4 * t5 *
    2.0;
  r_jtip[12] = in2[1];
  r_jtip[13] = t48_tmp;
  r_jtip[14] = (t48_tmp + in1[16] * t93 * t5 * 2.0) - t4 * t8 * 2.0;
  r_jtip[15] = t3_tmp;
  r_jtip[16] = t52_tmp;
  r_jtip[17] = (((t52_tmp + in1[16] * (t93 * t93)) + in1[16] * (t7 * t7)) - in1
                [16] * (t6 * t6)) - in1[16] * (t5 * t5);
}

/* End of code generation (rjtipF.c) */
