/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vdF.c
 *
 * Code generation for function 'fj_vdF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "fj_vdF.h"

/* Function Definitions */
void fj_vdF(const real_T in1[34], const real_T in2[12], real_T s, real_T fj_vd[6])
{
  int32_T i;
  (void)in1;
  (void)in2;
  (void)s;

  /* FJ_VDF */
  /*     FJ_VD = FJ_VDF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 13:21:33 */
  for (i = 0; i < 6; i++) {
    fj_vd[i] = 0.0;
  }
}

/* End of code generation (fj_vdF.c) */
