function out1 = sprdmpDl8(in1,in2,s,ds,t_sym)
%SPRDMPDL8
%    OUT1 = SPRDMPDL8(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:59:00

q8 = in2(8,:);
out1 = q8;
