function out1 = sprdmpIn3(in1,in2,s,ds,t_sym)
%SPRDMPIN3
%    OUT1 = SPRDMPIN3(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:58:57

out1 = 0.0;
