function out1 = sprdmpKx17(in1,in2,s,ds,t_sym)
%SPRDMPKX17
%    OUT1 = SPRDMPKX17(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:51:30

out1 = 0.0;
