/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF10.c
 *
 * Code generation for function 'cnstF10'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF10.h"

/* Function Definitions */
void cnstF10(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
             *out3)
{
  real_T t2;
  real_T t3;

  /* CNSTF10 */
  /*     [OUT1,OUT2,OUT3] = CNSTF10(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:08 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t2 = muDoubleScalarSin(t2);
  memset(&out1[0], 0, 87U * sizeof(real_T));
  out1[87] = t3 * 2.0;
  out1[88] = 0.0;
  out1[89] = t2 * -2.0;
  out1[90] = -in2[87] * t2 - in2[89] * t3;
  memset(&out2[0], 0, 87U * sizeof(real_T));
  out2[87] = -t2 * in2[193];
  out2[88] = 0.0;
  out2[89] = -t3 * in2[193];
  out2[90] = (-t2 * in2[190] - t3 * in2[192]) - in2[193] * (in2[87] * t3 / 2.0 -
    in2[89] * t2 / 2.0);
  *out3 = 0.0;
}

/* End of code generation (cnstF10.c) */
