/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF105.c
 *
 * Code generation for function 'sprdmpF105'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF105.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo bw_emlrtRSI = { 41, /* lineNo */
  "sprdmpF105",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF105.m"/* pathName */
};

static emlrtRSInfo fw_emlrtRSI = { 50, /* lineNo */
  "sprdmpF105",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF105.m"/* pathName */
};

static emlrtRSInfo gw_emlrtRSI = { 58, /* lineNo */
  "sprdmpF105",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF105.m"/* pathName */
};

static emlrtRSInfo hw_emlrtRSI = { 87, /* lineNo */
  "sprdmpF105",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF105.m"/* pathName */
};

static emlrtRSInfo tw_emlrtRSI = { 286,/* lineNo */
  "sprdmpF105",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF105.m"/* pathName */
};

/* Function Definitions */
void sprdmpF105(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7_tmp;
  real_T t7;
  real_T t8;
  real_T t232;
  real_T t9;
  real_T t171;
  real_T t10;
  real_T t14;
  real_T t60;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18_tmp;
  real_T t19;
  real_T t20_tmp;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24_tmp;
  real_T t225;
  real_T t26_tmp;
  real_T t28_tmp;
  real_T t28;
  real_T t30;
  real_T t31;
  real_T t32_tmp;
  real_T t33;
  real_T t34_tmp;
  real_T t35;
  real_T t36_tmp;
  real_T t46_tmp;
  real_T t37_tmp;
  real_T t37;
  real_T t39_tmp;
  real_T t39;
  real_T t41;
  real_T t53_tmp;
  real_T t45_tmp;
  real_T t45;
  real_T t58_tmp;
  real_T t197;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t51;
  real_T t52;
  real_T t55_tmp;
  real_T t55;
  real_T t57;
  real_T t59;
  real_T t63_tmp;
  real_T t64;
  real_T t65;
  real_T t66;
  real_T t67;
  real_T a;
  real_T b_a;
  real_T a_tmp;
  real_T t73;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T t220;
  real_T t77;
  real_T t78;
  real_T t79;
  real_T t80;
  real_T t82;
  real_T t86_tmp;
  real_T b_t86_tmp;
  real_T c_t86_tmp;
  real_T t86;
  real_T t91_tmp;
  real_T b_t91_tmp;
  real_T c_t91_tmp;
  real_T t91;
  real_T t101;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t109;
  real_T t110;
  real_T t111;
  real_T t112;
  real_T t114;
  real_T t118_tmp;
  real_T b_t118_tmp;
  real_T c_t118_tmp;
  real_T t118;
  real_T t123_tmp;
  real_T b_t123_tmp;
  real_T c_t123_tmp;
  real_T t123;
  real_T t132;
  real_T t137;
  real_T t138;
  real_T t139;
  real_T t140;
  real_T t141;
  real_T t142;
  real_T t143;
  real_T t145;
  real_T t149_tmp;
  real_T b_t149_tmp;
  real_T t149;
  real_T t154;
  real_T t163;
  real_T t170;
  real_T t173;
  real_T t177;
  real_T t181;
  real_T t186;
  real_T t188;
  real_T t192;
  real_T t196;
  real_T t198;
  real_T t200;
  real_T t202;
  real_T t205;
  real_T t210;
  real_T t212;
  real_T t216;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF105 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF105(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:19:32 */
  t2 = in2[82] * in2[82];
  t3 = in2[83] * in2[83];
  t4 = in2[81] * in2[81];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &bw_emlrtRSI;
  b_sqrt(&st, &t6);
  t7_tmp = in2[81] * in2[82];
  t7 = t7_tmp * 2.0;
  t8 = in2[82] * t6 * 2.0;
  t232 = in2[81] * in2[83];
  t9 = t232 * 2.0;
  t171 = in2[82] * in2[83];
  t10 = t171 * 2.0;
  t14 = ((-(in2[57] * in2[57]) - in2[58] * in2[58]) - in2[59] * in2[59]) + 1.0;
  t60 = t14;
  st.site = &fw_emlrtRSI;
  b_sqrt(&st, &t60);
  t15 = 1.0 / t60;
  t16 = t6 * 2.0;
  t17 = in2[82] * 2.0;
  t18_tmp = in2[83] * t6 * 2.0;
  t19 = t3 * 2.0;
  t20_tmp = in2[81] * t6 * 2.0;
  t21 = t4 * 2.0;
  t22 = t2 * 2.0;
  st.site = &gw_emlrtRSI;
  b_sqrt(&st, &t5);
  t23 = 1.0 / t5;
  t24_tmp = in2[55] - in2[79];
  t225 = in2[56] - in2[80];
  t26_tmp = in2[54] - in2[78];
  t28_tmp = in2[81] * t23;
  t28 = (-in2[56] + in2[80]) + t28_tmp * t24_tmp;
  t30 = t24_tmp + t28_tmp * t225;
  t31 = t6 * t24_tmp;
  t32_tmp = in2[81] * t225;
  t33 = t6 * t225;
  t34_tmp = in2[82] * t26_tmp;
  t35 = t6 * t26_tmp;
  t36_tmp = in2[83] * t24_tmp;
  t46_tmp = in2[82] * t225;
  t37_tmp = t35 + t36_tmp;
  t37 = t37_tmp - t46_tmp;
  t39_tmp = in2[82] * t23;
  t39 = (-in2[54] + in2[78]) + t39_tmp * t225;
  t41 = t225 + t39_tmp * t26_tmp;
  t53_tmp = in2[83] * t26_tmp;
  t45_tmp = t31 + t32_tmp;
  t45 = t45_tmp - t53_tmp;
  t58_tmp = in2[81] * t24_tmp;
  t197 = t33 + t34_tmp;
  t47 = t197 - t58_tmp;
  t48 = in2[59] * 2.0;
  t49 = in2[57] - in2[81];
  st.site = &hw_emlrtRSI;
  b_sqrt(&st, &t14);
  t51 = in2[58] - in2[82];
  t52 = in2[59] - in2[83];
  t55_tmp = in2[83] * t23;
  t55 = t26_tmp + t55_tmp * t24_tmp;
  t57 = (-in2[55] + in2[79]) + t55_tmp * t26_tmp;
  t59 = in2[57] * 2.0;
  t5 = in1[4] / 2.0;
  t60 = muDoubleScalarCos(t5);
  t5 = muDoubleScalarSin(t5);
  t63_tmp = (in2[81] * t26_tmp + in2[82] * t24_tmp) + in2[83] * t225;
  t64 = t60 * t60;
  t65 = t5 * t5;
  t66 = t64 * 7.1054273579999992E-18;
  t5 *= t60;
  t67 = t5 * 0.154;
  a = (t66 + t67) - t65 * 7.1054273579999992E-18;
  b_a = (-(t64 * 0.077) + t65 * 0.077) + t5 * 1.4210854716E-17;
  a_tmp = t64 * 0.010174174174 + t65 * 0.010174174174;
  t73 = t6 - t14;
  t74 = in2[82] * t39;
  t75 = t58_tmp * 2.0;
  t76 = t32_tmp * 2.0;
  t220 = t171 * t23;
  t77 = t220 * t225;
  t78 = (t19 + t22) - 1.0;
  t79 = t7 + t18_tmp;
  t80 = t8 - t9;
  t82 = ((t63_tmp + in2[82] * t30) - in2[83] * t28) - t28_tmp * t37;
  t86_tmp = t6 * t41;
  b_t86_tmp = t39_tmp * t37;
  c_t86_tmp = t220 * t24_tmp;
  t86 = ((((t197 - t74) - t75) + t86_tmp) + b_t86_tmp) + c_t86_tmp;
  t91_tmp = in2[83] * t55;
  b_t91_tmp = t6 * t57;
  c_t91_tmp = t55_tmp * t37;
  t91 = (((((-t31 + t53_tmp) - t76) - t77) + b_t91_tmp) + t91_tmp) + c_t91_tmp;
  t101 = muDoubleScalarPower(muDoubleScalarAbs((((((((t86 * in2[185] + t91 *
    in2[186]) + t78 * in2[157]) + t80 * in2[159]) + t79 * in2[182]) - t78 * in2
    [181]) - t79 * in2[158]) - t80 * in2[183]) - t82 * in2[184]), in1[1] - 1.0);
  t106 = t34_tmp * 2.0;
  t60 = t232 * t23;
  t107 = t60 * t26_tmp;
  t108 = in2[83] * t57;
  t109 = t46_tmp * 2.0;
  t110 = (t19 + t21) - 1.0;
  t111 = -t7 + t18_tmp;
  t112 = t10 + t20_tmp;
  t114 = ((t63_tmp + in2[83] * t41) - in2[81] * t39) - t39_tmp * t45;
  t118_tmp = in2[81] * t30;
  b_t118_tmp = t6 * t28;
  c_t118_tmp = t28_tmp * t45;
  t118 = (((((-t33 + t58_tmp) - t106) - t107) + b_t118_tmp) + t118_tmp) +
    c_t118_tmp;
  t123_tmp = t6 * t55;
  b_t123_tmp = t55_tmp * t45;
  c_t123_tmp = t60 * t225;
  t123 = ((((t37_tmp - t108) - t109) + t123_tmp) + b_t123_tmp) + c_t123_tmp;
  t132 = muDoubleScalarPower(muDoubleScalarAbs((((((((t118 * in2[184] + t123 *
    in2[186]) + t110 * in2[158]) + t111 * in2[157]) + t112 * in2[183]) - t110 *
    in2[182]) - t112 * in2[159]) - t111 * in2[181]) - t114 * in2[185]), in1[1] -
    1.0);
  t137 = in2[81] * t28;
  t138 = t53_tmp * 2.0;
  t139 = t36_tmp * 2.0;
  t5 = t7_tmp * t23;
  t140 = t5 * t24_tmp;
  t141 = (t21 + t22) - 1.0;
  t142 = t8 + t9;
  t143 = -t10 + t20_tmp;
  t145 = ((t63_tmp + in2[81] * t55) - in2[82] * t57) - t55_tmp * t47;
  t149_tmp = t6 * t30;
  b_t149_tmp = t28_tmp * t47;
  t26_tmp *= t5;
  t149 = ((((t45_tmp - t137) - t138) + t149_tmp) + b_t149_tmp) + t26_tmp;
  t55 = in2[82] * t41;
  t7_tmp = t6 * t39;
  t21 = t39_tmp * t47;
  t154 = (((((-t35 + t46_tmp) - t139) - t140) + t7_tmp) + t55) + t21;
  t163 = muDoubleScalarPower(muDoubleScalarAbs((((((((t149 * in2[184] + t154 *
    in2[185]) + t141 * in2[159]) + t143 * in2[158]) + t142 * in2[181]) - t141 *
    in2[183]) - t142 * in2[157]) - t143 * in2[182]) - t145 * in2[186]), in1[1] -
    1.0);
  t41 = in2[58] * 2.0;
  t170 = t16 + in2[57] * in2[81] * t15 * 2.0;
  t171 = in2[83] * 2.0;
  t173 = t171 + in2[58] * in2[81] * t15 * 2.0;
  t22 = in2[59] * in2[81] * t15 * 2.0;
  t19 = t5 * 2.0;
  t37_tmp = t39_tmp * t49 * 2.0;
  t177 = (t48 + t19) + t37_tmp;
  t39 = t14 * 2.0;
  t28 = t4 * t23 * 2.0;
  t24_tmp = t28_tmp * t49 * 2.0;
  t181 = (t39 + t28) + t24_tmp;
  t30 = t60 * 2.0;
  t60 = t55_tmp * t49 * 2.0;
  t186 = (-t41 + t30) + t60;
  t188 = t17 - t22;
  t192 = muDoubleScalarPower(muDoubleScalarAbs(((((t181 * in2[184] + t177 * in2
    [185]) + t186 * in2[186]) + t188 * in2[162]) - t170 * in2[160]) - t173 *
    in2[161]), in1[1] - 1.0);
  t196 = t16 + in2[58] * in2[82] * t15 * 2.0;
  t197 = in2[57] * in2[82] * t15 * 2.0;
  t198 = in2[81] * 2.0;
  t200 = t198 + in2[59] * in2[82] * t15 * 2.0;
  t64 = t28_tmp * t51 * 2.0;
  t202 = (-t48 + t19) + t64;
  t232 = t2 * t23 * 2.0;
  t225 = t39_tmp * t51 * 2.0;
  t205 = (t39 + t232) + t225;
  t45_tmp = t220 * 2.0;
  t5 = t55_tmp * t51 * 2.0;
  t210 = (t59 + t45_tmp) + t5;
  t212 = t171 - t197;
  t216 = muDoubleScalarPower(muDoubleScalarAbs(((((t205 * in2[185] + t202 * in2
    [184]) + t210 * in2[186]) + t212 * in2[160]) - t196 * in2[161]) - t200 *
    in2[162]), in1[1] - 1.0);
  t220 = t16 + in2[59] * in2[83] * t15 * 2.0;
  t16 = t17 + in2[57] * in2[83] * t15 * 2.0;
  t57 = in2[58] * in2[83] * t15 * 2.0;
  memset(&out1[0], 0, 54U * sizeof(real_T));
  out1[54] = (t2 * -2.0 - t3 * 2.0) + 1.0;
  out1[55] = t79;
  out1[56] = -t8 + t9;
  memset(&out1[57], 0, 21U * sizeof(real_T));
  out1[78] = t78;
  out1[79] = -t7 - t18_tmp;
  out1[80] = t80;
  out1[81] = t82;
  out1[82] = (((((-t33 - t34_tmp) + t74) + t75) - t86_tmp) - b_t86_tmp) -
    c_t86_tmp;
  out1[83] = (((((t31 - t53_tmp) + t76) + t77) - t91_tmp) - b_t91_tmp) -
    c_t91_tmp;
  memset(&out1[84], 0, 61U * sizeof(real_T));
  out1[145] = t7 - t18_tmp;
  out1[146] = (t3 * -2.0 - t4 * 2.0) + 1.0;
  out1[147] = t112;
  memset(&out1[148], 0, 21U * sizeof(real_T));
  out1[169] = t111;
  out1[170] = t110;
  out1[171] = -t10 - t20_tmp;
  out1[172] = (((((t33 + t106) + t107) - t58_tmp) - t118_tmp) - b_t118_tmp) -
    c_t118_tmp;
  out1[173] = t114;
  out1[174] = (((((-t35 - t36_tmp) + t108) + t109) - t123_tmp) - b_t123_tmp) -
    c_t123_tmp;
  memset(&out1[175], 0, 61U * sizeof(real_T));
  out1[236] = t142;
  out1[237] = t10 - t20_tmp;
  out1[238] = (t2 * -2.0 - t4 * 2.0) + 1.0;
  memset(&out1[239], 0, 21U * sizeof(real_T));
  out1[260] = -t8 - t9;
  out1[261] = t143;
  out1[262] = t141;
  out1[263] = (((((-t31 - t32_tmp) + t137) + t138) - t149_tmp) - b_t149_tmp) -
    t26_tmp;
  out1[264] = (((((t35 - t46_tmp) + t139) + t140) - t55) - t7_tmp) - t21;
  out1[265] = t145;
  memset(&out1[266], 0, sizeof(real_T) << 6);
  out1[330] = t170;
  out1[331] = t173;
  out1[332] = -t17 + t22;
  memset(&out1[333], 0, 21U * sizeof(real_T));
  out1[354] = (t14 * -2.0 - t28) - t24_tmp;
  out1[355] = (-t48 - t19) - t37_tmp;
  out1[356] = (t41 - t30) - t60;
  memset(&out1[357], 0, sizeof(real_T) << 6);
  out1[421] = in2[83] * -2.0 + t197;
  out1[422] = t196;
  out1[423] = t200;
  memset(&out1[424], 0, 21U * sizeof(real_T));
  out1[445] = (t48 - t19) - t64;
  out1[446] = (t14 * -2.0 - t232) - t225;
  out1[447] = (-t59 - t45_tmp) - t5;
  memset(&out1[448], 0, sizeof(real_T) << 6);
  out1[512] = t16;
  out1[513] = in2[81] * -2.0 + t57;
  out1[514] = t220;
  memset(&out1[515], 0, 21U * sizeof(real_T));
  t171 = t28_tmp * t52 * 2.0;
  out1[536] = (in2[58] * -2.0 - t30) - t171;
  t197 = t39_tmp * t52 * 2.0;
  out1[537] = (t59 - t45_tmp) - t197;
  t60 = t3 * t23 * 2.0;
  t5 = t55_tmp * t52 * 2.0;
  out1[538] = (t14 * -2.0 - t60) - t5;
  out1[539] = 0.0;
  out1[540] = 0.0;
  out1[541] = 0.0;
  out1[542] = 0.0;
  out1[543] = 0.0;
  out1[544] = 0.0;
  out1[545] = 0.0;
  t225 = (t41 + t30) + t171;
  t19 = (t39 + t60) + t5;
  t232 = (-t59 + t45_tmp) + t197;
  t171 = t198 - t57;
  t197 = muDoubleScalarPower(muDoubleScalarAbs(((((t19 * in2[186] + t225 * in2
    [184]) + t232 * in2[185]) + t171 * in2[161]) - t220 * in2[162]) - t16 * in2
    [160]), in1[1] - 1.0);
  t5 = (a * a + b_a * b_a) + a_tmp * a_tmp;
  st.site = &tw_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * ((((((t65 * -7.1054273579999992E-18 + t66) + t67) + in2[83]
    * t45) - in2[82] * t47) + in2[81] * t63_tmp) + t6 * t37) *
    -0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp - in2[83] * t37) + in2[81] * t47) + in2[82] *
                       t63_tmp) + t6 * t45) * -0.00026666666666666668;
  out2[2] = in1[0] * ((((-t5 + in2[82] * t37) - in2[81] * t45) + in2[83] *
                       t63_tmp) + t6 * t47) * -0.0008;
  out2[3] = in1[0] * (((in2[82] * t52 * -2.0 + in2[83] * t51 * 2.0) + in2[81] *
                       t73 * 2.0) + t6 * t49 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[83] * t49 * -2.0 + in2[81] * t52 * 2.0) + in2[82] *
                       t73 * 2.0) + t6 * t51 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[82] * t49 * 2.0 - in2[81] * t51 * 2.0) + in2[83] *
                       t73 * 2.0) + t6 * t52 * 2.0) * -4.75111111111111E-9;
  t64 = in1[2] * t78 * t101;
  t5 = in1[2] * t79 * t101;
  t60 = in1[2] * t80 * t101;
  out3[0] = (((((((t64 * in2[157] - t5 * in2[158]) + t60 * in2[159]) - t64 *
                 in2[181]) + t5 * in2[182]) - t60 * in2[183]) - in1[2] * t82 *
              t101 * in2[184]) + in1[2] * t86 * t101 * in2[185]) + in1[2] * t91 *
    t101 * in2[186];
  t64 = in1[2] * t110 * t132;
  t5 = in1[2] * t111 * t132;
  t60 = in1[2] * t112 * t132;
  out3[1] = (((((((t64 * in2[158] + t5 * in2[157]) - t60 * in2[159]) - t64 *
                 in2[182]) - t5 * in2[181]) + t60 * in2[183]) - in1[2] * t114 *
              t132 * in2[185]) + in1[2] * t118 * t132 * in2[184]) + in1[2] *
    t123 * t132 * in2[186];
  t64 = in1[2] * t141 * t163;
  t5 = in1[2] * t143 * t163;
  out3[2] = (((((((-in1[2] * t142 * t163 * in2[157] + t64 * in2[159]) + t5 *
                  in2[158]) + in1[2] * t142 * t163 * in2[181]) - t64 * in2[183])
               - t5 * in2[182]) - in1[2] * t145 * t163 * in2[186]) + in1[2] *
             t149 * t163 * in2[184]) + in1[2] * t154 * t163 * in2[185];
  out3[3] = ((((-in1[3] * t170 * t192 * in2[160] - in1[3] * t173 * t192 * in2
                [161]) + in1[3] * t188 * t192 * in2[162]) + in1[3] * t177 * t192
              * in2[185]) + in1[3] * t181 * t192 * in2[184]) + in1[3] * t186 *
    t192 * in2[186];
  out3[4] = ((((-in1[3] * t196 * t216 * in2[161] - in1[3] * t200 * t216 * in2
                [162]) + in1[3] * t212 * t216 * in2[160]) + in1[3] * t202 * t216
              * in2[184]) + in1[3] * t205 * t216 * in2[185]) + in1[3] * t210 *
    t216 * in2[186];
  out3[5] = ((((-in1[3] * t220 * t197 * in2[162] - in1[3] * t16 * t197 * in2[160])
               + in1[3] * t171 * t197 * in2[161]) + in1[3] * t225 * t197 * in2
              [184]) + in1[3] * t19 * t197 * in2[186]) + in1[3] * t232 * t197 *
    in2[185];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF105.c) */
