/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF115.c
 *
 * Code generation for function 'sprdmpF115'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF115.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo yeb_emlrtRSI = { 27,/* lineNo */
  "sprdmpF115",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF115.m"/* pathName */
};

static emlrtRSInfo afb_emlrtRSI = { 67,/* lineNo */
  "sprdmpF115",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF115.m"/* pathName */
};

/* Function Definitions */
void sprdmpF115(const emlrtStack *sp, const real_T in2[206], real_T out1[546],
                real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t3;
  real_T t2;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t18;
  real_T t21;
  real_T t24;
  real_T t27;
  real_T t30_tmp;
  real_T t30;
  real_T t32;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF115 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF115(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:32:49 */
  t3 = in2[90] / 2.0;
  t2 = muDoubleScalarCos(t3);
  t4 = muDoubleScalarSin(t3);
  t5 = t2 * t2;
  t6 = t4 * t4;
  t7 = t2 * t4 * 2.0;
  t8 = t5 - t6;
  t9 = t2 * 2.0;
  t13 = ((-(in2[87] * in2[87]) - in2[88] * in2[88]) - in2[89] * in2[89]) + 1.0;
  t3 = t13;
  st.site = &yeb_emlrtRSI;
  b_sqrt(&st, &t3);
  t14 = 1.0 / t3;
  t15 = t4 * 2.0;
  t18 = t2 * 0.03 + t4 * 0.038;
  t21 = t2 * 0.038 - t4 * 0.03;
  t24 = t2 * 0.019 - t4 * 0.015;
  t27 = t2 * 0.015 + t4 * 0.019;
  t3 = t4 * t18;
  t30_tmp = t2 * t21;
  t30 = ((t3 / 2.0 + t4 * t27) - t30_tmp / 2.0) - t2 * t24;
  t32 = (in2[84] + t3) - t30_tmp;
  t30_tmp = t2 * t18;
  t3 = t4 * t21;
  t27 = ((t30_tmp / 2.0 + t2 * t27) + t3 / 2.0) + t4 * t24;
  t18 = (in2[86] + t30_tmp) + t3;
  t3 = t2 * t32;
  t30_tmp = t4 * t18;
  t24 = ((t2 * t30 + t30_tmp / 2.0) - t3 / 2.0) - t4 * t27;
  t21 = t3 - t30_tmp;
  t30_tmp = t4 * t32;
  t3 = t2 * t18;
  t18 = t3 + t30_tmp;
  st.site = &afb_emlrtRSI;
  b_sqrt(&st, &t13);
  memset(&out1[0], 0, 84U * sizeof(real_T));
  out1[84] = t8;
  out1[85] = 0.0;
  out1[86] = -t7;
  out1[87] = 0.0;
  out1[88] = 0.0;
  out1[89] = 0.0;
  t3 = ((t2 * t27 + t4 * t30) - t30_tmp / 2.0) - t3 / 2.0;
  out1[90] = ((t4 * t24 - t4 * t21 / 2.0) - t2 * t18 / 2.0) + t2 * t3;
  memset(&out1[91], 0, 85U * sizeof(real_T));
  out1[176] = t5 + t6;
  memset(&out1[177], 0, 89U * sizeof(real_T));
  out1[266] = t7;
  out1[267] = 0.0;
  out1[268] = t8;
  out1[269] = 0.0;
  out1[270] = 0.0;
  out1[271] = 0.0;
  out1[272] = ((-t2 * t24 + t2 * t21 / 2.0) - t4 * t18 / 2.0) + t4 * t3;
  memset(&out1[273], 0, 87U * sizeof(real_T));
  out1[360] = t9;
  out1[361] = 0.0;
  out1[362] = -t15;
  out1[363] = -in2[87] * t4 - in2[89] * t2;
  memset(&out1[364], 0, 87U * sizeof(real_T));
  out1[451] = in2[87] * t4 * t14 * 2.0;
  out1[452] = t9 + in2[88] * t4 * t14 * 2.0;
  t3 = in2[89] * t4;
  out1[453] = t3 * t14 * 2.0;
  out1[454] = ((-t5 - t6) - t4 * (in2[88] - t4)) + t2 * (t2 - t13);
  memset(&out1[455], 0, 87U * sizeof(real_T));
  out1[542] = t15;
  out1[543] = 0.0;
  out1[544] = t9;
  out1[545] = in2[87] * t2 - t3;
  for (i = 0; i < 6; i++) {
    out2[i] = 0.0;
    out3[i] = 0.0;
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF115.c) */
