/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "EOM_eq_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo cb_emlrtRSI = { 56, /* lineNo */
  "massF1",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T out1[36], real_T out2[108], real_T out3[108], real_T out4[6])
{
  emlrtStack st;
  real_T t10;
  real_T t11;
  real_T t13;
  real_T t14;
  real_T t16;
  real_T t17;
  real_T t35;
  real_T t35_tmp;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t46;
  real_T t46_tmp;
  real_T t47;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  st.prev = sp;
  st.tls = sp->tls;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 01:39:21 */
  t47 = muDoubleScalarCos(in1[20]);
  t43 = muDoubleScalarSin(in1[20]);
  t5 = in1[33] * in1[33];
  t6 = in2[3] * 2.0;
  t7 = in2[4] * 2.0;
  t8 = in2[5] * 2.0;
  t9 = in2[3] * in2[3];
  t10 = in2[4] * in2[4];
  t11 = in2[5] * in2[5];
  t13 = in1[2] * in1[2];
  t14 = in1[3] * in1[3];
  t16 = 1.0 / in1[33];
  t17 = in1[18] * in1[18] * 6.0;
  t36 = ((-t9 + -t10) + -t11) + 1.0;
  st.site = &cb_emlrtRSI;
  if (t36 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t36 = muDoubleScalarSqrt(t36);
  t35_tmp = in1[4] * in1[0];
  t35 = -(t35_tmp * ((t13 + t17) + -t14) * 3.1415926535897931 / 3.0);
  t37 = 1.0 / t36;
  t39 = t36 * 2.0;
  t38 = muDoubleScalarPower(t37, 3.0);
  t40 = t6 * t37;
  t41 = t7 * t37;
  t42 = t8 * t37;
  t47 = (t14 + -t13) + t17 * (1.0 / (t43 * t43)) * (t5 * (t47 * t47) - 1.0);
  t43 = in2[4] * t40;
  t44 = in2[5] * t40;
  t37 = in2[5] * t41;
  t46_tmp = in2[4] * in2[5];
  t46 = t46_tmp * t6 * t38;
  t36 = t35_tmp * t47 * (in1[4] * in1[4] * t5 / 108.0 + t16 * (t13 * 3.0 + t14 *
    3.0) / 12.0) * 3.1415926535897931 / 3.0;
  out1[0] = t35;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t35;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t35;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t36;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t36;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t35_tmp * t16 * t47 * 3.1415926535897931 * (t13 / 2.0 + t14 / 2.0) /
    3.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = 0.0;
  out2[20] = 0.0;
  out2[21] = t39 + in2[3] * t40;
  out2[22] = -t8 + t43;
  out2[23] = t7 + t44;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = 0.0;
  out2[27] = t8 + t43;
  out2[28] = t39 + in2[4] * t41;
  out2[29] = -t6 + t37;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = 0.0;
  out2[33] = -t7 + t44;
  out2[34] = t6 + t37;
  out2[35] = t39 + in2[5] * t42;
  memset(&out2[36], 0, 72U * sizeof(real_T));
  t37 = t40 + t6 * t10 * t38;
  t47 = t40 + t6 * t11 * t38;
  t43 = t41 + in2[3] * in2[4] * t6 * t38;
  t17 = t41 + t7 * t11 * t38;
  t44 = t42 + in2[3] * in2[5] * t6 * t38;
  t36 = t42 + t46_tmp * t7 * t38;
  memset(&out3[0], 0, 21U * sizeof(real_T));
  out3[21] = (t43 * in2[22] + t44 * in2[23]) + in2[21] * (t40 + t6 * t9 * t38);
  out3[22] = ((t46 + 2.0) * in2[23] + t43 * in2[21]) - in2[22] * (t40 - in2[3] *
    t10 * t38 * 2.0);
  out3[23] = ((t46 - 2.0) * in2[22] + t44 * in2[21]) - in2[23] * (t40 - in2[3] *
    t11 * t38 * 2.0);
  out3[24] = 0.0;
  out3[25] = 0.0;
  out3[26] = 0.0;
  out3[27] = ((t46 - 2.0) * in2[23] + t37 * in2[22]) - in2[21] * (t41 - in2[4] *
    t9 * t38 * 2.0);
  out3[28] = (t37 * in2[21] + t36 * in2[23]) + in2[22] * (t41 + t7 * t10 * t38);
  out3[29] = ((t46 + 2.0) * in2[21] + t36 * in2[22]) - in2[23] * (t41 - in2[4] *
    t11 * t38 * 2.0);
  out3[30] = 0.0;
  out3[31] = 0.0;
  out3[32] = 0.0;
  out3[33] = ((t46 + 2.0) * in2[22] + t47 * in2[23]) - in2[21] * (t42 - in2[5] *
    t9 * t38 * 2.0);
  out3[34] = ((t46 - 2.0) * in2[21] + t17 * in2[23]) - in2[22] * (t42 - in2[5] *
    t10 * t38 * 2.0);
  out3[35] = (t47 * in2[21] + t17 * in2[22]) + in2[23] * (t42 + t8 * t11 * t38);
  memset(&out3[36], 0, 72U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
