/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF5.c
 *
 * Code generation for function 'massF5'
 *
 */

/* Include files */
#include "massF5.h"
#include "EOM_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo xc_emlrtRSI = { 39, /* lineNo */
  "massF5",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF5.m"/* pathName */
};

/* Function Definitions */
void massF5(const emlrtStack *sp, const real_T in1[34], const real_T in2[48],
            real_T out1[36], real_T out2[144], real_T out3[144], real_T out4[6])
{
  emlrtStack st;
  real_T t11;
  real_T t12;
  real_T t2;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t27;
  real_T t28;
  real_T t29;
  real_T t3;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t37_tmp;
  real_T t4;
  real_T t49;
  real_T t5;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t57;
  real_T t59;
  real_T t6;
  real_T t63;
  real_T t7;
  real_T t9;
  st.prev = sp;
  st.tls = sp->tls;

  /* MASSF5 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF5(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     26-Feb-2021 21:07:19 */
  t2 = in1[16] * in2[23];
  t3 = in1[16] * in1[16];
  t4 = in2[21] * 2.0;
  t5 = in2[22] * 2.0;
  t6 = in2[23] * 2.0;
  t7 = in2[21] * in2[21];
  t9 = in2[22] * in2[22];
  t11 = in2[23] * in2[23];
  t12 = in1[17] * in1[17];
  t22 = ((-t7 + -t9) + -t11) + 1.0;
  st.site = &xc_emlrtRSI;
  if (t22 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t22 = muDoubleScalarSqrt(t22);
  t3 = in1[15] * t3 / 4.0 + in1[15] * (t3 + t12 * 3.0) / 12.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t3;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t3;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t12 / 2.0;
  t23 = 1.0 / t22;
  t25 = in1[16] * t22;
  t3 = t22 * 2.0;
  t24 = muDoubleScalarPower(t23, 3.0);
  t27 = t4 * t23;
  t28 = t5 * t23;
  t29 = t6 * t23;
  t63 = in1[16] * in2[21];
  t30 = t63 * t23;
  t57 = in1[16] * in2[22];
  t31 = t57 * t23;
  t32 = t2 * t23;
  t12 = in2[22] * t27;
  t22 = in2[23] * t27;
  t35 = in2[23] * t28;
  t36 = in2[22] * t30;
  memset(&out2[0], 0, 108U * sizeof(real_T));
  out2[108] = 1.0;
  out2[109] = 0.0;
  out2[110] = 0.0;
  out2[111] = 0.0;
  out2[112] = 0.0;
  out2[113] = 0.0;
  out2[114] = 0.0;
  out2[115] = 1.0;
  out2[116] = 0.0;
  out2[117] = 0.0;
  out2[118] = 0.0;
  out2[119] = 0.0;
  out2[120] = 0.0;
  out2[121] = 0.0;
  out2[122] = 1.0;
  out2[123] = 0.0;
  out2[124] = 0.0;
  out2[125] = 0.0;
  out2[126] = t2 - t36;
  out2[127] = -t25 + in1[16] * t7 * t23;
  out2[128] = t63 * -2.0;
  out2[129] = t3 + in2[21] * t27;
  out2[130] = -t6 + t12;
  out2[131] = t5 + t22;
  out2[132] = t25 + in1[16] * -t9 * t23;
  out2[133] = t2 + t36;
  out2[134] = t57 * -2.0;
  out2[135] = t6 + t12;
  out2[136] = t3 + in2[22] * t28;
  out2[137] = -t4 + t35;
  out2[138] = t63 - in2[22] * t32;
  out2[139] = t57 + in2[21] * t32;
  out2[140] = 0.0;
  out2[141] = -t5 + t22;
  out2[142] = t4 + t35;
  out2[143] = t3 + in2[23] * t29;
  t37_tmp = in2[22] * in2[23];
  t37 = t37_tmp * t4 * t24;
  t3 = in2[21] * in2[22];
  t12 = t3 * t2 * t24;
  t49 = in1[16] + t12;
  t54 = t30 + t63 * t9 * t24;
  t55 = t31 + t57 * t7 * t24;
  t56 = t32 + t2 * t7 * t24;
  t57 = t32 + t2 * t9 * t24;
  t32 = t27 + t4 * t9 * t24;
  t59 = t27 + t4 * t11 * t24;
  t35 = t28 + t3 * t4 * t24;
  t36 = t28 + t5 * t11 * t24;
  t23 = in2[21] * in2[23];
  t25 = t29 + t23 * t4 * t24;
  t63 = t29 + t37_tmp * t5 * t24;
  t3 = in1[16] + -t12;
  t12 = t55 * in2[45];
  t22 = t54 * in2[46];
  memset(&out3[0], 0, 126U * sizeof(real_T));
  out3[126] = (-t12 - t22) + t3 * in2[47];
  out3[127] = (t55 * in2[46] + t56 * in2[47]) + in2[45] * (t30 * 3.0 + in1[16] *
    muDoubleScalarPower(in2[21], 3.0) * t24);
  out3[128] = in1[16] * in2[45] * -2.0;
  out3[129] = (t35 * in2[46] + t25 * in2[47]) + in2[45] * (t27 + t4 * t7 * t24);
  out3[130] = ((t37 + 2.0) * in2[47] + t35 * in2[45]) - in2[46] * (t27 - in2[21]
    * t9 * t24 * 2.0);
  out3[131] = ((t37 - 2.0) * in2[46] + t25 * in2[45]) - in2[47] * (t27 - in2[21]
    * t11 * t24 * 2.0);
  out3[132] = (-t54 * in2[45] - t57 * in2[47]) - in2[46] * (t31 * 3.0 + in1[16] *
    muDoubleScalarPower(in2[22], 3.0) * t24);
  out3[133] = (t12 + t22) + t49 * in2[47];
  out3[134] = in1[16] * in2[46] * -2.0;
  out3[135] = ((t37 - 2.0) * in2[47] + t32 * in2[46]) - in2[45] * (t28 - in2[22]
    * t7 * t24 * 2.0);
  out3[136] = (t32 * in2[45] + t63 * in2[47]) + in2[46] * (t28 + t5 * t9 * t24);
  out3[137] = ((t37 + 2.0) * in2[45] + t63 * in2[46]) - in2[47] * (t28 - in2[22]
    * t11 * t24 * 2.0);
  out3[138] = (t3 * in2[45] - t57 * in2[46]) - in2[47] * (t31 + t37_tmp * t2 *
    t24);
  out3[139] = (t49 * in2[46] + t56 * in2[45]) + in2[47] * (t30 + t23 * t2 * t24);
  out3[140] = 0.0;
  out3[141] = ((t37 + 2.0) * in2[46] + t59 * in2[47]) - in2[45] * (t29 - in2[23]
    * t7 * t24 * 2.0);
  out3[142] = ((t37 - 2.0) * in2[45] + t36 * in2[47]) - in2[46] * (t29 - in2[23]
    * t9 * t24 * 2.0);
  out3[143] = (t59 * in2[45] + t36 * in2[46]) + in2[47] * (t29 + t6 * t11 * t24);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF5.c) */
