/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * loadsF1.c
 *
 * Code generation for function 'loadsF1'
 *
 */

/* Include files */
#include "loadsF1.h"
#include "EOM_eq_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo mf_emlrtRSI = { 138,/* lineNo */
  "loadsF1",                           /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\loadsF1.m"/* pathName */
};

static emlrtRSInfo of_emlrtRSI = { 152,/* lineNo */
  "loadsF1",                           /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\loadsF1.m"/* pathName */
};

/* Function Definitions */
void loadsF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[34],
             real_T out1[102], real_T out2[6])
{
  emlrtStack st;
  real_T b_out1_tmp;
  real_T b_t223_tmp;
  real_T b_t224_tmp;
  real_T b_t226_tmp;
  real_T b_t227_tmp;
  real_T b_t248_tmp;
  real_T b_t249_tmp;
  real_T b_t257_tmp;
  real_T b_t328_tmp;
  real_T b_t334_tmp;
  real_T b_t342_tmp;
  real_T out1_tmp;
  real_T t101;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t114_tmp;
  real_T t115;
  real_T t116;
  real_T t117;
  real_T t124_tmp;
  real_T t127_tmp;
  real_T t129_tmp;
  real_T t133;
  real_T t134;
  real_T t135;
  real_T t137;
  real_T t138;
  real_T t138_tmp;
  real_T t139;
  real_T t140;
  real_T t140_tmp;
  real_T t141;
  real_T t142;
  real_T t145_tmp;
  real_T t146;
  real_T t146_tmp;
  real_T t147;
  real_T t147_tmp;
  real_T t148_tmp;
  real_T t15;
  real_T t150;
  real_T t151;
  real_T t153;
  real_T t154;
  real_T t16;
  real_T t2;
  real_T t212;
  real_T t213;
  real_T t214;
  real_T t215;
  real_T t223;
  real_T t223_tmp;
  real_T t224;
  real_T t224_tmp;
  real_T t226;
  real_T t226_tmp;
  real_T t227;
  real_T t227_tmp;
  real_T t238;
  real_T t239;
  real_T t248;
  real_T t248_tmp;
  real_T t249;
  real_T t249_tmp;
  real_T t251_tmp;
  real_T t252_tmp;
  real_T t256_tmp;
  real_T t256_tmp_tmp;
  real_T t257;
  real_T t257_tmp;
  real_T t263;
  real_T t263_tmp;
  real_T t263_tmp_tmp;
  real_T t264;
  real_T t265;
  real_T t266;
  real_T t267;
  real_T t272;
  real_T t273;
  real_T t276_tmp;
  real_T t277_tmp;
  real_T t3;
  real_T t300;
  real_T t301;
  real_T t302;
  real_T t303;
  real_T t307;
  real_T t311;
  real_T t314;
  real_T t315;
  real_T t316;
  real_T t317;
  real_T t326;
  real_T t326_tmp;
  real_T t327;
  real_T t328;
  real_T t328_tmp;
  real_T t329;
  real_T t330;
  real_T t331;
  real_T t332;
  real_T t333;
  real_T t334;
  real_T t334_tmp;
  real_T t335;
  real_T t336;
  real_T t337;
  real_T t337_tmp;
  real_T t342;
  real_T t342_tmp;
  real_T t343;
  real_T t343_tmp;
  real_T t344;
  real_T t344_tmp;
  real_T t345;
  real_T t345_tmp;
  real_T t346;
  real_T t346_tmp;
  real_T t347_tmp;
  real_T t349;
  real_T t349_tmp;
  real_T t4;
  real_T t45;
  real_T t46;
  real_T t5;
  real_T t65;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t75;
  real_T t77;
  real_T t81;
  real_T t9;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  st.prev = sp;
  st.tls = sp->tls;

  /* LOADSF1 */
  /*     [OUT1,OUT2,OUT3] = LOADSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 05:42:44 */
  t2 = in1[4] * in2[12];
  t3 = in1[4] * 2.0;
  t4 = in1[4] * in1[4];
  t5 = muDoubleScalarPower(in1[4], 3.0);
  t9 = t4 * 3.0;
  t15 = in2[13] * t4;
  t16 = in2[14] * t5;
  t45 = (in1[4] - 0.022) * (in1[4] - 0.022);
  t46 = muDoubleScalarPower(in1[4] - 0.022, 3.0);
  t65 = 1.0 / (muDoubleScalarExp(-(in1[4] * 200.0) + 4.4) + 1.0);
  t69 = (t3 - 0.044) * t65;
  t70 = t45 * t65;
  t71 = t46 * t65;
  t77 = t65 * ((t4 + -(in1[4] * 0.044)) + 0.000484);
  t81 = t65 * ((t5 + -(in1[4] * 0.001452)) + 2.1296E-5);
  t92 = (in2[0] * t3 + in2[1] * t9) + t65 * (((((in1[4] * in2[0] * -2.0 + in2[1]
    * t4 * -3.0) + in2[0] * 0.044) + in2[1] * 0.001452) + in2[2] * (t3 - 0.044))
    + in2[3] * t45 * 3.0);
  t93 = (in2[4] * t3 + in2[5] * t9) + t65 * (((((in1[4] * in2[4] * -2.0 + in2[5]
    * t4 * -3.0) + in2[4] * 0.044) + in2[5] * 0.001452) + in2[6] * (t3 - 0.044))
    + in2[7] * t45 * 3.0);
  t94 = ((in2[8] * t3 + in2[9] * t9) + t65 * (((((in1[4] * in2[8] * -2.0 + in2[9]
              * t4 * -3.0) + in2[8] * 0.044) + in2[9] * 0.001452) + in2[10] *
           (t3 - 0.044)) + in2[11] * t45 * 3.0)) + 1.0;
  t2 = ((t2 / 2.0 + t15 / 2.0) + t16 / 2.0) + t65 * ((((((((-t2 + -t15) + -t16)
    + in2[12] * 0.022) + in2[13] * 0.000484) + in2[15] * t45) + in2[16] * t46) +
    in2[14] * 1.0648E-5) + (in1[4] - 0.022) * ((in2[12] + in2[13] * 0.044) +
    in2[14] * 0.001452)) / 2.0;
  t75 = t3 + -t69;
  t95 = t92 * t92;
  t96 = t93 * t93;
  t97 = t94 * t94;
  t101 = muDoubleScalarCos(t2);
  t102 = muDoubleScalarSin(t2);
  t103 = t101 * t101;
  t104 = t102 * t102;
  t2 = (t95 + t96) + t97;
  t106 = 1.0 / (t2 * t2);
  st.site = &mf_emlrtRSI;
  if (t2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t107 = 1.0 / muDoubleScalarSqrt(t2);
  t108 = muDoubleScalarPower(t107, 3.0);
  t2 = t69 * t107;
  t15 = t75 * t107;
  t114_tmp = t94 * t107 + 1.0;
  t124_tmp = t9 - t65 * (t9 - 0.001452);
  st.site = &of_emlrtRSI;
  if (t114_tmp < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t115 = muDoubleScalarSqrt(t114_tmp);
  t133 = t2 + -t69 * t97 * t108;
  t116 = 1.0 / t115;
  t127_tmp = 1.4142135623730951 * t101 * t115;
  t129_tmp = 1.4142135623730951 * t102 * t115;
  t134 = t70 * t107 * 3.0 + -(t70 * t97 * t108 * 3.0);
  t135 = t15 + -(t75 * t97 * t108);
  t117 = muDoubleScalarPower(t116, 3.0);
  t137 = 1.4142135623730951 * t101 * t2 * t116 / 2.0;
  t138_tmp = 1.4142135623730951 * t70 * t101;
  t138 = t138_tmp * t107 * t116 * 1.5;
  t139 = 1.4142135623730951 * t102 * t2 * t116 / 2.0;
  t140_tmp = 1.4142135623730951 * t70 * t102;
  t140 = t140_tmp * t107 * t116 * 1.5;
  t141 = 1.4142135623730951 * t101 * t15 * t116 / 2.0;
  t142 = 1.4142135623730951 * t102 * t15 * t116 / 2.0;
  t145_tmp = 1.4142135623730951 * t92 * t101 * t107;
  t9 = t145_tmp * t116;
  t146_tmp = 1.4142135623730951 * t93 * t101 * t107;
  t146 = t146_tmp * t116;
  t147_tmp = 1.4142135623730951 * t92 * t102 * t107;
  t147 = t147_tmp * t116;
  t148_tmp = 1.4142135623730951 * t93 * t102 * t107;
  t65 = t148_tmp * t116;
  t2 = 1.4142135623730951 * t69 * t92;
  t16 = t2 * t93;
  t212 = t16 * t101 * t108 * t116 / 2.0;
  t15 = 1.4142135623730951 * t70 * t92;
  t45 = t15 * t93;
  t213 = t45 * t101 * t108 * t116 * 1.5;
  t214 = t16 * t102 * t108 * t116 / 2.0;
  t215 = t45 * t102 * t108 * t116 * 1.5;
  t223_tmp = t2 * t94;
  b_t223_tmp = t223_tmp * t102 * t108 * t116;
  t223 = b_t223_tmp / 2.0;
  t224_tmp = 1.4142135623730951 * t69 * t93 * t94;
  b_t224_tmp = t224_tmp * t102 * t108 * t116;
  t224 = b_t224_tmp / 2.0;
  t226_tmp = t15 * t94;
  b_t226_tmp = t226_tmp * t102 * t108 * t116;
  t226 = b_t226_tmp * 1.5;
  t227_tmp = 1.4142135623730951 * t70 * t93 * t94;
  b_t227_tmp = t227_tmp * t102 * t108 * t116;
  t227 = b_t227_tmp * 1.5;
  t2 = 1.4142135623730951 * t75 * t92;
  t46 = t2 * t93;
  t238 = t46 * t101 * t108 * t116 / 2.0;
  t239 = t46 * t102 * t108 * t116 / 2.0;
  t248_tmp = t2 * t94;
  b_t248_tmp = t248_tmp * t102 * t108 * t116;
  t248 = b_t248_tmp / 2.0;
  t249_tmp = 1.4142135623730951 * t75 * t93 * t94;
  b_t249_tmp = t249_tmp * t102 * t108 * t116;
  t249 = b_t249_tmp / 2.0;
  t3 = 1.4142135623730951 * t92 * t93;
  t251_tmp = t3 * t101 * t108 * t116 * t124_tmp;
  t252_tmp = t3 * t102 * t108 * t116 * t124_tmp;
  t2 = 1.4142135623730951 * t92 * t94;
  t256_tmp_tmp = t2 * t101 * t108 * t116;
  t256_tmp = t256_tmp_tmp * t124_tmp;
  t257_tmp = 1.4142135623730951 * t93 * t94;
  b_t257_tmp = t257_tmp * t101 * t108 * t116;
  t257 = b_t257_tmp * t124_tmp * -0.5;
  t263_tmp_tmp = t2 * t102 * t108 * t116;
  t263_tmp = t263_tmp_tmp * t124_tmp;
  t263 = t263_tmp / 2.0;
  t150 = t9 / 2.0;
  t151 = t146 / 2.0;
  t153 = t65 / 2.0;
  t2 = t16 * t94;
  t264 = t2 * t101 * t106 * t117 / 4.0;
  t15 = t45 * t94;
  t265 = t15 * t101 * t106 * t117 * 0.75;
  t266 = t2 * t102 * t106 * t117 / 4.0;
  t267 = t15 * t102 * t106 * t117 * 0.75;
  t2 = t46 * t94;
  t272 = t2 * t101 * t106 * t117 / 4.0;
  t273 = t2 * t102 * t106 * t117 / 4.0;
  t2 = t3 * t94;
  t276_tmp = t2 * t101 * t106 * t117 * t124_tmp;
  t277_tmp = t2 * t102 * t106 * t117 * t124_tmp;
  t300 = t9 + t65;
  t154 = -(t147 / 2.0);
  t301 = t146 + -t147;
  t302 = t150 + t153;
  t307 = in1[4] * t9 / 4.0 + in1[4] * t65 / 4.0;
  t314 = t70 * t9 / 4.0 + t70 * t65 / 4.0;
  t315 = t71 * t9 / 4.0 + t71 * t65 / 4.0;
  t2 = 1.4142135623730951 * t69 * t94;
  t65 = 1.4142135623730951 * t69 * t95;
  t326_tmp = t2 * t95;
  t326 = (((t137 + -(t65 * t101 * t108 * t116 / 2.0)) + -t214) + t326_tmp * t101
          * t106 * t117 / 4.0) + t266;
  t15 = 1.4142135623730951 * t70 * t94;
  t328_tmp = 1.4142135623730951 * t70 * t95;
  b_t328_tmp = t15 * t95;
  t328 = (((t138 + -(t328_tmp * t101 * t108 * t116 * 1.5)) + -t215) + b_t328_tmp
          * t101 * t106 * t117 * 0.75) + t267;
  t45 = 1.4142135623730951 * t69 * t96;
  t16 = t2 * t96;
  t331 = (((t139 + -(t45 * t102 * t108 * t116 / 2.0)) + -t212) + t16 * t102 *
          t106 * t117 / 4.0) + t264;
  t46 = 1.4142135623730951 * t70 * t96;
  t15 *= t96;
  t333 = (((t140 + -(t46 * t102 * t108 * t116 * 1.5)) + -t213) + t15 * t102 *
          t106 * t117 * 0.75) + t265;
  t2 = 1.4142135623730951 * t75 * t94;
  t334_tmp = 1.4142135623730951 * t75 * t95;
  b_t334_tmp = t2 * t95;
  t334 = (((t141 + -(t334_tmp * t101 * t108 * t116 / 2.0)) + b_t334_tmp * t101 *
           t106 * t117 / 4.0) + -t239) + t273;
  t337_tmp = 1.4142135623730951 * t75 * t96;
  t3 = t2 * t96;
  t337 = (((t142 + -(t337_tmp * t102 * t108 * t116 / 2.0)) + t3 * t102 * t106 *
           t117 / 4.0) + -t238) + t272;
  t342_tmp = t145_tmp * t117;
  t145_tmp = t148_tmp * t117;
  b_t342_tmp = t223_tmp * t101 * t108 * t116;
  t342 = ((b_t342_tmp / 2.0 + t224) + t342_tmp * t133 / 4.0) + t145_tmp * t133 /
    4.0;
  t344_tmp = t226_tmp * t101 * t108 * t116;
  t344 = ((t344_tmp * 1.5 + t227) + t342_tmp * t134 / 4.0) + t145_tmp * t134 /
    4.0;
  t346_tmp = t248_tmp * t101 * t108 * t116;
  t346 = ((t346_tmp / 2.0 + t249) + t342_tmp * t135 / 4.0) + t145_tmp * t135 /
    4.0;
  t349_tmp = -t97 * t108 * t124_tmp + t107 * t124_tmp;
  t9 = t146_tmp * t117;
  t2 = t147_tmp * t117;
  t349 = ((t257 + t263) + t9 * t349_tmp * -0.25) + t2 * t349_tmp / 4.0;
  t303 = t151 + -(t147 / 2.0);
  t311 = in1[4] * t146 / 4.0 + -(in1[4] * t147 / 4.0);
  t316 = t70 * t146 / 4.0 + -(t70 * t147 / 4.0);
  t317 = t71 * t146 / 4.0 + -(t71 * t147 / 4.0);
  t327 = (((t137 + -(t45 * t101 * t108 * t116 / 2.0)) + t214) + t16 * t101 *
          t106 * t117 / 4.0) + -t266;
  t329 = (((t138 + -(t46 * t101 * t108 * t116 * 1.5)) + t215) + t15 * t101 *
          t106 * t117 * 0.75) + -t267;
  t330 = (((t139 + -(t65 * t102 * t108 * t116 / 2.0)) + t212) + t326_tmp * t102 *
          t106 * t117 / 4.0) + -t264;
  t332 = (((t140 + -(t328_tmp * t102 * t108 * t116 * 1.5)) + t213) + b_t328_tmp *
          t102 * t106 * t117 * 0.75) + -t265;
  t335 = (((t141 + -(t337_tmp * t101 * t108 * t116 / 2.0)) + t239) + t3 * t101 *
          t106 * t117 / 4.0) + -t273;
  t336 = (((t142 + -(t334_tmp * t102 * t108 * t116 / 2.0)) + t238) + b_t334_tmp *
          t102 * t106 * t117 / 4.0) + -t272;
  t343_tmp = t224_tmp * t101 * t108 * t116;
  t343 = ((t343_tmp / 2.0 + -t223) + t9 * t133 / 4.0) + -(t2 * t133 / 4.0);
  t345_tmp = t227_tmp * t101 * t108 * t116;
  t345 = ((t345_tmp * 1.5 + -t226) + t9 * t134 / 4.0) + -(t2 * t134 / 4.0);
  t347_tmp = t249_tmp * t101 * t108 * t116;
  t140 = ((t347_tmp / 2.0 + -t248) + t9 * t135 / 4.0) + -(t2 * t135 / 4.0);
  t141 = in1[16] * 1.4142135623730951 * t101;
  t142 = t141 * t115;
  t2 = in1[16] * 1.4142135623730951 * t102;
  t224_tmp = t2 * t115;
  t227_tmp = in1[16] * 1.4142135623730951 * t75;
  t249_tmp = t227_tmp * t92 * t94;
  out1_tmp = t249_tmp * t101 * t108 * t116;
  b_out1_tmp = t4 + -t77;
  out1[0] = (((b_out1_tmp + in1[16] * t248 * t303) + t142 * t334) + t224_tmp *
             t336) - out1_tmp * t302 / 2.0;
  t213 = 1.4142135623730951 * t94 * t95;
  t238 = 1.4142135623730951 * t102 * t107 * t116 * t124_tmp / 2.0;
  t239 = 1.4142135623730951 * t101 * t107 * t116 * t124_tmp / 2.0;
  t138 = in1[16] * (t256_tmp * -0.5);
  t139 = (((1.4142135623730951 * t95 * t101 * t108 * t116 * t124_tmp * -0.5 +
            t252_tmp * -0.5) + t277_tmp / 4.0) + t239) + t213 * t101 * t106 *
    t117 * t124_tmp / 4.0;
  t213 = (((1.4142135623730951 * t95 * t102 * t108 * t116 * t124_tmp * -0.5 +
            t251_tmp / 2.0) + t276_tmp * -0.25) + t238) + t213 * t102 * t106 *
    t117 * t124_tmp / 4.0;
  t212 = t5 + -t81;
  out1[1] = (((t212 + t138 * t302) + in1[16] * t263 * t303) + t142 * t139) +
    t224_tmp * t213;
  t214 = in1[16] * 1.4142135623730951 * t69;
  t215 = t214 * t92 * t94;
  t137 = t215 * t101 * t108 * t116;
  out1[2] = (((t70 + in1[16] * t223 * t303) + t142 * t326) + t224_tmp * t330) -
    t137 * t302 / 2.0;
  t97 = in1[16] * 1.4142135623730951 * t70;
  t146 = t97 * t92 * t94;
  t147 = t146 * t101 * t108 * t116;
  out1[3] = (((t71 + in1[16] * t226 * t303) + t142 * t328) + t224_tmp * t332) -
    t147 * t302 * 1.5;
  t265 = t227_tmp * t93 * t94;
  t227_tmp = t265 * t101 * t108 * t116;
  out1[4] = ((in1[16] * t249 * t303 - t224_tmp * t335) + t142 * t337) - t227_tmp
    * t302 / 2.0;
  t264 = 1.4142135623730951 * t94 * t96;
  t272 = in1[16] * t257;
  t238 = (((1.4142135623730951 * t96 * t102 * t108 * t116 * t124_tmp * -0.5 +
            t251_tmp * -0.5) + t276_tmp / 4.0) + t238) + t264 * t102 * t106 *
    t117 * t124_tmp / 4.0;
  t239 = (((1.4142135623730951 * t96 * t101 * t108 * t116 * t124_tmp * -0.5 +
            t252_tmp / 2.0) + t277_tmp * -0.25) + t239) + t264 * t101 * t106 *
    t117 * t124_tmp / 4.0;
  out1[5] = ((t272 * t302 + t142 * t238) - t224_tmp * t239) + in1[16] *
    1.4142135623730951 * t93 * t94 * t102 * t108 * t116 * t303 * t124_tmp / 2.0;
  t273 = t214 * t93 * t94;
  t214 = t273 * t101 * t108 * t116;
  out1[6] = ((in1[16] * t224 * t303 - t224_tmp * t327) + t142 * t331) - t214 *
    t302 / 2.0;
  t147_tmp = t97 * t93 * t94;
  t264 = t147_tmp * t101 * t108 * t116;
  out1[7] = ((in1[16] * t227 * t303 - t224_tmp * t329) + t142 * t333) - t264 *
    t302 * 1.5;
  t266 = -in1[16] * 1.4142135623730951;
  t267 = t141 * t116;
  b_t328_tmp = t2 * t116;
  t334_tmp = t266 * t101 * t115;
  b_t334_tmp = t267 * t135;
  t146_tmp = b_t328_tmp * t135;
  out1[8] = ((t334_tmp * t346 + t224_tmp * t140) + b_t334_tmp * t302 / 2.0) -
    t146_tmp * t303 / 2.0;
  t141 = t257_tmp * t102 * t108 * t116;
  t328_tmp = t141 * t124_tmp;
  t337_tmp = ((t342_tmp * t349_tmp / 4.0 + t145_tmp * t349_tmp / 4.0) + t256_tmp
              / 2.0) + t328_tmp / 2.0;
  out1[9] = ((t266 * t102 * t115 * t349 - t142 * t337_tmp) + t267 * t302 *
             t349_tmp / 2.0) - b_t328_tmp * t303 * t349_tmp / 2.0;
  t266 = t267 * t133;
  t148_tmp = b_t328_tmp * t133;
  out1[10] = ((t334_tmp * t342 + t224_tmp * t343) + t266 * t302 / 2.0) -
    t148_tmp * t303 / 2.0;
  t223_tmp = t267 * t134;
  t226_tmp = b_t328_tmp * t134;
  out1[11] = ((t334_tmp * t344 + t224_tmp * t345) + t223_tmp * t302 / 2.0) -
    t226_tmp * t303 / 2.0;
  t248_tmp = in1[16] * in1[4] * 1.4142135623730951;
  t326_tmp = t248_tmp * t101 * t115;
  t248_tmp = t248_tmp * t102 * t115;
  out1[12] = ((t224_tmp * t307 + t142 * t311) - t326_tmp * t303 / 2.0) -
    t248_tmp * t302 / 2.0;
  t9 = t4 / 2.0 - t77 / 2.0;
  t46 = t142 * t303;
  t3 = t224_tmp * t302;
  t65 = t150 * t9 + t153 * t9;
  t145_tmp = t151 * t9 + t154 * t9;
  out1[13] = ((t224_tmp * t65 + t142 * t145_tmp) - t46 * t9) - t3 * t9;
  t45 = t5 / 2.0 - t81 / 2.0;
  t16 = t150 * t45 + t153 * t45;
  t15 = t151 * t45 + t154 * t45;
  out1[14] = ((t224_tmp * t16 + t142 * t15) - t46 * t45) - t3 * t45;
  t46 = t97 * t101 * t115;
  t97 = t97 * t102 * t115;
  out1[15] = ((t224_tmp * t314 + t142 * t316) - t46 * t303 / 2.0) - t97 * t302 /
    2.0;
  t3 = in1[16] * 1.4142135623730951 * t71;
  t2 = t3 * t101 * t115;
  t3 = t3 * t102 * t115;
  out1[16] = ((t224_tmp * t315 + t142 * t317) - t2 * t303 / 2.0) - t3 * t302 /
    2.0;
  out1[17] = ((t224_tmp * t334 - t142 * t336) - out1_tmp * t303 / 2.0) -
    t249_tmp * t102 * t108 * t116 * t302 / 2.0;
  out1[18] = ((t138 * t303 + in1[16] * (t263_tmp * -0.5) * t302) + t224_tmp *
              t139) - t142 * t213;
  out1[19] = ((t224_tmp * t326 - t142 * t330) - t137 * t303 / 2.0) - t215 * t102
    * t108 * t116 * t302 / 2.0;
  out1[20] = ((t224_tmp * t328 - t142 * t332) - t147 * t303 * 1.5) - t146 * t102
    * t108 * t116 * t302 * 1.5;
  out1[21] = (((b_out1_tmp + t142 * t335) + t224_tmp * t337) - t227_tmp * t303 /
              2.0) - t265 * t102 * t108 * t116 * t302 / 2.0;
  out1[22] = (((t212 + t272 * t303) + in1[16] * (t328_tmp * -0.5) * t302) +
              t224_tmp * t238) + t142 * t239;
  out1[23] = (((t70 + t142 * t327) + t224_tmp * t331) - t214 * t303 / 2.0) -
    t273 * t102 * t108 * t116 * t302 / 2.0;
  out1[24] = (((t71 + t142 * t329) + t224_tmp * t333) - t264 * t303 * 1.5) -
    t147_tmp * t102 * t108 * t116 * t302 * 1.5;
  out1[25] = ((t334_tmp * t140 - t224_tmp * t346) + b_t334_tmp * t303 / 2.0) +
    t146_tmp * t302 / 2.0;
  out1[26] = ((t142 * t349 - t224_tmp * t337_tmp) + t267 * t303 * t349_tmp / 2.0)
    + b_t328_tmp * t302 * t349_tmp / 2.0;
  out1[27] = ((t334_tmp * t343 - t224_tmp * t342) + t266 * t303 / 2.0) +
    t148_tmp * t302 / 2.0;
  out1[28] = ((t334_tmp * t345 - t224_tmp * t344) + t223_tmp * t303 / 2.0) +
    t226_tmp * t302 / 2.0;
  out1[29] = ((t334_tmp * t307 + t224_tmp * t311) + t326_tmp * t302 / 2.0) -
    t248_tmp * t303 / 2.0;
  t142 *= t302;
  t227_tmp = t224_tmp * t303;
  out1[30] = ((t334_tmp * t65 + t224_tmp * t145_tmp) + t142 * t9) - t227_tmp *
    t9;
  out1[31] = ((t334_tmp * t16 + t224_tmp * t15) + t142 * t45) - t227_tmp * t45;
  out1[32] = ((t334_tmp * t314 + t224_tmp * t316) + t46 * t302 / 2.0) - t97 *
    t303 / 2.0;
  out1[33] = ((t334_tmp * t315 + t224_tmp * t317) + t2 * t302 / 2.0) - t3 * t303
    / 2.0;
  t2 = in1[16] * t75;
  t142 = t2 * t92 * t94;
  t224_tmp = in1[16] * t302;
  t227_tmp = in1[16] * t303;
  out1[34] = ((t224_tmp * t334 * -2.0 + t227_tmp * t336 * 2.0) - t142 * t103 *
              t108 / 2.0) - t142 * t104 * t108 / 2.0;
  t142 = in1[16] * t92 * t94;
  out1[35] = ((t224_tmp * t139 * -2.0 + t227_tmp * t213 * 2.0) - t142 * t103 *
              t108 * t124_tmp / 2.0) - t142 * t104 * t108 * t124_tmp / 2.0;
  t249_tmp = in1[16] * t69;
  t142 = t249_tmp * t92 * t94;
  out1[36] = ((t224_tmp * t326 * -2.0 + t227_tmp * t330 * 2.0) - t142 * t103 *
              t108 / 2.0) - t142 * t104 * t108 / 2.0;
  t215 = in1[16] * t70;
  t142 = t215 * t92 * t94;
  out1[37] = ((t224_tmp * t328 * -2.0 + t227_tmp * t332 * 2.0) - t142 * t103 *
              t108 * 1.5) - t142 * t104 * t108 * 1.5;
  t142 = t2 * t93 * t94;
  out1[38] = ((t227_tmp * t335 * -2.0 - t224_tmp * t337 * 2.0) - t142 * t103 *
              t108 / 2.0) - t142 * t104 * t108 / 2.0;
  t142 = in1[16] * t93 * t94;
  out1[39] = ((t224_tmp * t238 * -2.0 - t227_tmp * t239 * 2.0) - t142 * t103 *
              t108 * t124_tmp / 2.0) - t142 * t104 * t108 * t124_tmp / 2.0;
  t142 = t249_tmp * t93 * t94;
  out1[40] = ((t227_tmp * t327 * -2.0 - t224_tmp * t331 * 2.0) - t142 * t103 *
              t108 / 2.0) - t142 * t104 * t108 / 2.0;
  t142 = t215 * t93 * t94;
  out1[41] = ((t227_tmp * t329 * -2.0 - t224_tmp * t333 * 2.0) - t142 * t103 *
              t108 * 1.5) - t142 * t104 * t108 * 1.5;
  t142 = in1[16] * t103;
  out1_tmp = in1[16] * t104;
  out1[42] = (((b_out1_tmp + t142 * t135 / 2.0) + out1_tmp * t135 / 2.0) +
              t224_tmp * t346 * 2.0) + t227_tmp * t140 * 2.0;
  out1[43] = (((t212 + t142 * t349_tmp / 2.0) + out1_tmp * t349_tmp / 2.0) -
              t227_tmp * t349 * 2.0) + t224_tmp * t337_tmp * 2.0;
  out1[44] = (((t70 + t142 * t133 / 2.0) + out1_tmp * t133 / 2.0) + t224_tmp *
              t342 * 2.0) + t227_tmp * t343 * 2.0;
  out1[45] = (((t71 + t142 * t134 / 2.0) + out1_tmp * t134 / 2.0) + t224_tmp *
              t344 * 2.0) + t227_tmp * t345 * 2.0;
  out1[46] = t227_tmp * t307 * 2.0 - t224_tmp * t311 * 2.0;
  out1[47] = t227_tmp * t65 * 2.0 - t224_tmp * t145_tmp * 2.0;
  out1[48] = t227_tmp * t16 * 2.0 - t224_tmp * t15 * 2.0;
  out1[49] = t227_tmp * t314 * 2.0 - t224_tmp * t316 * 2.0;
  out1[50] = t227_tmp * t315 * 2.0 - t224_tmp * t317 * 2.0;
  out1[51] = ((t129_tmp * t334 + t127_tmp * t336) - t346_tmp * t301 / 4.0) +
    b_t248_tmp * t300 / 4.0;
  out1[52] = ((t129_tmp * t139 + t127_tmp * t213) - t256_tmp_tmp * t301 *
              t124_tmp / 4.0) + t263_tmp_tmp * t300 * t124_tmp / 4.0;
  out1[53] = ((t129_tmp * t326 + t127_tmp * t330) - b_t342_tmp * t301 / 4.0) +
    b_t223_tmp * t300 / 4.0;
  out1[54] = ((t129_tmp * t328 + t127_tmp * t332) - t344_tmp * t301 * 0.75) +
    b_t226_tmp * t300 * 0.75;
  t142 = -1.4142135623730951 * t101 * t115;
  out1[55] = ((t142 * t335 + t129_tmp * t337) - t347_tmp * t301 / 4.0) +
    b_t249_tmp * t300 / 4.0;
  out1[56] = ((t129_tmp * t238 - t127_tmp * t239) - b_t257_tmp * t301 * t124_tmp
              / 4.0) + t141 * t300 * t124_tmp / 4.0;
  out1[57] = ((t142 * t327 + t129_tmp * t331) - t343_tmp * t301 / 4.0) +
    b_t224_tmp * t300 / 4.0;
  out1[58] = ((t142 * t329 + t129_tmp * t333) - t345_tmp * t301 * 0.75) +
    b_t227_tmp * t300 * 0.75;
  t224_tmp = 1.4142135623730951 * t101 * t116;
  t227_tmp = 1.4142135623730951 * t102 * t116;
  out1_tmp = t224_tmp * t135;
  b_out1_tmp = t227_tmp * t135;
  out1[59] = ((t127_tmp * t140 - t129_tmp * t346) + out1_tmp * t301 / 4.0) -
    b_out1_tmp * t300 / 4.0;
  out1[60] = ((t142 * t349 - t129_tmp * t337_tmp) + t224_tmp * t301 * t349_tmp /
              4.0) - t227_tmp * t300 * t349_tmp / 4.0;
  t138 = t224_tmp * t133;
  t212 = t227_tmp * t133;
  out1[61] = ((t127_tmp * t343 - t129_tmp * t342) + t138 * t301 / 4.0) - t212 *
    t300 / 4.0;
  t214 = t224_tmp * t134;
  t137 = t227_tmp * t134;
  out1[62] = ((t127_tmp * t345 - t129_tmp * t344) + t214 * t301 / 4.0) - t137 *
    t300 / 4.0;
  t97 = in1[4] * 1.4142135623730951 * t101 * t115;
  t147 = in1[4] * 1.4142135623730951 * t102 * t115;
  out1[63] = ((t127_tmp * t307 + t129_tmp * t311) - t97 * t300 / 4.0) - t147 *
    t301 / 4.0;
  t264 = t127_tmp * t300;
  t272 = t129_tmp * t301;
  out1[64] = ((t127_tmp * t65 + t129_tmp * t145_tmp) - t264 * t9 / 2.0) - t272 *
    t9 / 2.0;
  out1[65] = ((t127_tmp * t16 + t129_tmp * t15) - t264 * t45 / 2.0) - t272 * t45
    / 2.0;
  t264 = t138_tmp * t115;
  t272 = t140_tmp * t115;
  out1[66] = ((t127_tmp * t314 + t129_tmp * t316) - t264 * t300 / 4.0) - t272 *
    t301 / 4.0;
  t266 = 1.4142135623730951 * t71 * t101 * t115;
  t267 = 1.4142135623730951 * t71 * t102 * t115;
  out1[67] = ((t127_tmp * t315 + t129_tmp * t317) - t266 * t300 / 4.0) - t267 *
    t301 / 4.0;
  out1[68] = ((t127_tmp * t334 - t129_tmp * t336) + t346_tmp * t300 / 4.0) +
    b_t248_tmp * t301 / 4.0;
  out1[69] = ((t127_tmp * t139 - t129_tmp * t213) + t256_tmp_tmp * t300 *
              t124_tmp / 4.0) + t263_tmp_tmp * t301 * t124_tmp / 4.0;
  out1[70] = ((t127_tmp * t326 - t129_tmp * t330) + b_t342_tmp * t300 / 4.0) +
    b_t223_tmp * t301 / 4.0;
  out1[71] = ((t127_tmp * t328 - t129_tmp * t332) + t344_tmp * t300 * 0.75) +
    b_t226_tmp * t301 * 0.75;
  out1[72] = ((t129_tmp * t335 + t127_tmp * t337) + t347_tmp * t300 / 4.0) +
    b_t249_tmp * t301 / 4.0;
  out1[73] = ((t127_tmp * t238 + t129_tmp * t239) + b_t257_tmp * t300 * t124_tmp
              / 4.0) + t141 * t301 * t124_tmp / 4.0;
  out1[74] = ((t129_tmp * t327 + t127_tmp * t331) + t343_tmp * t300 / 4.0) +
    b_t224_tmp * t301 / 4.0;
  out1[75] = ((t129_tmp * t329 + t127_tmp * t333) + t345_tmp * t300 * 0.75) +
    b_t227_tmp * t301 * 0.75;
  out1[76] = ((t142 * t346 - t129_tmp * t140) - out1_tmp * t300 / 4.0) -
    b_out1_tmp * t301 / 4.0;
  out1[77] = ((t129_tmp * t349 - t127_tmp * t337_tmp) - t224_tmp * t300 *
              t349_tmp / 4.0) - t227_tmp * t301 * t349_tmp / 4.0;
  out1[78] = ((t142 * t342 - t129_tmp * t343) - t138 * t300 / 4.0) - t212 * t301
    / 4.0;
  out1[79] = ((t142 * t344 - t129_tmp * t345) - t214 * t300 / 4.0) - t137 * t301
    / 4.0;
  t142 = -1.4142135623730951 * t102 * t115;
  out1[80] = ((t142 * t307 + t127_tmp * t311) - t97 * t301 / 4.0) + t147 * t300 /
    4.0;
  t224_tmp = t127_tmp * t301;
  t227_tmp = t129_tmp * t300;
  out1[81] = ((t142 * t65 + t127_tmp * t145_tmp) - t224_tmp * t9 / 2.0) +
    t227_tmp * t9 / 2.0;
  out1[82] = ((t142 * t16 + t127_tmp * t15) - t224_tmp * t45 / 2.0) + t227_tmp *
    t45 / 2.0;
  out1[83] = ((t142 * t314 + t127_tmp * t316) - t264 * t301 / 4.0) + t272 * t300
    / 4.0;
  out1[84] = ((t142 * t315 + t127_tmp * t317) - t266 * t301 / 4.0) + t267 * t300
    / 4.0;
  out1[85] = t301 * t334 + t300 * t336;
  out1[86] = t301 * t139 + t300 * t213;
  out1[87] = t301 * t326 + t300 * t330;
  out1[88] = t301 * t328 + t300 * t332;
  out1[89] = -t300 * t335 + t301 * t337;
  out1[90] = t301 * t238 - t300 * t239;
  out1[91] = -t300 * t327 + t301 * t331;
  out1[92] = -t300 * t329 + t301 * t333;
  out1[93] = t300 * t140 - t301 * t346;
  out1[94] = -t300 * t349 - t301 * t337_tmp;
  out1[95] = t300 * t343 - t301 * t342;
  out1[96] = t300 * t345 - t301 * t344;
  out1[97] = ((t300 * t307 + t301 * t311) + in1[4] * t103 * t114_tmp / 2.0) +
    in1[4] * t104 * t114_tmp / 2.0;
  t142 = t103 * t114_tmp;
  t224_tmp = t104 * t114_tmp;
  out1[98] = ((t300 * t65 + t301 * t145_tmp) + t142 * t9) + t224_tmp * t9;
  out1[99] = ((t300 * t16 + t301 * t15) + t142 * t45) + t224_tmp * t45;
  out1[100] = ((t300 * t314 + t301 * t316) + t70 * t103 * t114_tmp / 2.0) + t70 *
    t104 * t114_tmp / 2.0;
  out1[101] = ((t300 * t315 + t301 * t317) + t71 * t103 * t114_tmp / 2.0) + t71 *
    t104 * t114_tmp / 2.0;
  t2 = (t127_tmp * in1[30] / 2.0 + t129_tmp * in1[31] / 2.0) + -(t302 * in1[32]);
  t15 = (t127_tmp * in1[32] / 2.0 + t302 * in1[30]) + t303 * in1[31];
  t16 = (t129_tmp * in1[32] / 2.0 + t302 * in1[31]) + -(t303 * in1[30]);
  out2[0] = in1[27];
  out2[1] = in1[28];
  out2[2] = in1[29];
  t45 = (-(t127_tmp * in1[31] / 2.0) + t129_tmp * in1[30] / 2.0) + t303 * in1[32];
  out2[3] = ((-t302 * t15 - t303 * t16) + t127_tmp * t2 / 2.0) - t129_tmp * t45 /
    2.0;
  out2[4] = ((t302 * t16 - t303 * t15) - t129_tmp * t2 / 2.0) - t127_tmp * t45 /
    2.0;
  out2[5] = ((t302 * t2 - t303 * t45) + t127_tmp * t15 / 2.0) + t129_tmp * t16 /
    2.0;
}

/* End of code generation (loadsF1.c) */
