/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF3.c
 *
 * Code generation for function 'cnstF3'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "cnstF3.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo sab_emlrtRSI = { 26,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

static emlrtRSInfo tab_emlrtRSI = { 27,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

static emlrtRSInfo uab_emlrtRSI = { 28,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

static emlrtRSInfo vab_emlrtRSI = { 30,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

static emlrtRSInfo wab_emlrtRSI = { 31,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

static emlrtRSInfo xab_emlrtRSI = { 116,/* lineNo */
  "cnstF3",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF3.m"/* pathName */
};

/* Function Definitions */
void cnstF3(const emlrtStack *sp, const real_T in2[198], real_T out1[91], real_T
            out2[91], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t218;
  real_T t7;
  real_T t10_tmp;
  real_T t11;
  real_T t12;
  real_T t13_tmp;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18_tmp;
  real_T t19;
  real_T t21_tmp;
  real_T t22_tmp;
  real_T t48_tmp;
  real_T t23_tmp;
  real_T t210;
  real_T t25_tmp;
  real_T t25;
  real_T t26_tmp;
  real_T b_t26_tmp;
  real_T t27_tmp;
  real_T t28;
  real_T t41;
  real_T t42_tmp;
  real_T t29;
  real_T t238;
  real_T t235;
  real_T t234;
  real_T t33;
  real_T t34_tmp;
  real_T t34;
  real_T t35_tmp;
  real_T t44;
  real_T t45_tmp_tmp;
  real_T t45_tmp;
  real_T t45;
  real_T t36;
  real_T t37_tmp;
  real_T t38_tmp;
  real_T t39_tmp;
  real_T t46_tmp;
  real_T t40_tmp;
  real_T t209;
  real_T t49_tmp;
  real_T t50_tmp;
  real_T t50;
  real_T t52;
  real_T t54_tmp;
  real_T t55_tmp;
  real_T t56_tmp;
  real_T t57_tmp;
  real_T t58_tmp;
  real_T t63_tmp;
  real_T t64_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t65_tmp;
  real_T t62;
  real_T t69;
  real_T t70;
  real_T t71_tmp_tmp;
  real_T t71_tmp;
  real_T t71;
  real_T t72_tmp;
  real_T b_t72_tmp;
  real_T t73;
  real_T t75;
  real_T t76_tmp;
  real_T t77_tmp;
  real_T t78;
  real_T t79;
  real_T t80_tmp;
  real_T t81;
  real_T t84_tmp;
  real_T t84;
  real_T t82_tmp;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t97;
  real_T t102;
  real_T t103;
  real_T t104_tmp;
  real_T t104;
  real_T t106;
  real_T t111_tmp;
  real_T t112;
  real_T t115;
  real_T t117;
  real_T t119;
  real_T t121;
  real_T t123;
  real_T t127_tmp;
  real_T t127;
  real_T t128;
  real_T t129;
  real_T t135;
  real_T t274;
  real_T t139;
  real_T t141;
  real_T t144;
  real_T t148;
  real_T t150;
  real_T t151;
  real_T t154_tmp;
  real_T t154;
  real_T t156;
  real_T t158;
  real_T t297;
  real_T t188;
  real_T t189;
  real_T t191;
  real_T t192;
  real_T t196;
  real_T t200;
  real_T t202;
  real_T t206;
  real_T t207;
  real_T t273;
  real_T out1_tmp;
  real_T b_out1_tmp;
  real_T c_out1_tmp;
  real_T d_out1_tmp;
  real_T e_out1_tmp;
  real_T f_out1_tmp;
  real_T g_out1_tmp;
  real_T h_out1_tmp;
  real_T i_out1_tmp;
  real_T j_out1_tmp;
  real_T k_out1_tmp;
  real_T l_out1_tmp;
  real_T t211;
  real_T t212;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* CNSTF3 */
  /*     [OUT1,OUT2,OUT3] = CNSTF3(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:48:18 */
  st.site = &sab_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[4] * in2[4];
  st.site = &tab_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[5] * in2[5];
  st.site = &uab_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[3] * in2[3];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &vab_emlrtRSI;
  b_sqrt(&st, &t6);
  t218 = t5;
  st.site = &wab_emlrtRSI;
  b_sqrt(&st, &t218);
  t7 = 1.0 / t218;
  t10_tmp = in2[4] * 0.03 + t6 * 0.038;
  t11 = in2[4] * 0.038;
  t12 = t6 * 0.03;
  t13_tmp = t11 - t12;
  t14 = in2[3] * 0.038;
  t15 = in2[3] * 0.03;
  t16 = in2[5] * 0.038;
  t17 = t15 - t16;
  t18_tmp = t6 * t10_tmp;
  t19 = in2[5] * 0.03;
  t218 = t14 + t19;
  t21_tmp = in2[3] * t218;
  t22_tmp = in2[5] * t17;
  t48_tmp = in2[4] * t13_tmp;
  t23_tmp = ((((-in2[0] + in2[72]) + t18_tmp) + t21_tmp) + t22_tmp) - t48_tmp;
  t210 = in2[3] * in2[4];
  t25_tmp = t210 * t7;
  t25 = t25_tmp * 0.038;
  t26_tmp = in2[3] * t7;
  b_t26_tmp = t26_tmp * t13_tmp;
  t27_tmp = ((in2[5] * 0.076 + t25) + b_t26_tmp) - in2[3] * 0.09;
  t28 = in2[5] * 0.06;
  t41 = t25_tmp * 0.03;
  t42_tmp = t26_tmp * t10_tmp;
  t29 = ((t14 + t28) - t41) - t42_tmp;
  t238 = in2[3] * t13_tmp;
  t235 = in2[5] * t10_tmp;
  t234 = in2[4] * t218;
  t33 = in2[4] * 0.076;
  t34_tmp = t4 * t7;
  t34 = t34_tmp * 0.03;
  t35_tmp = t26_tmp * t17;
  t44 = t6 * 0.06;
  t45_tmp_tmp = in2[3] * in2[5];
  t45_tmp = t45_tmp_tmp * t7;
  t45 = t45_tmp * 0.038;
  t36 = (((t33 + t34) + t35_tmp) - t44) - t45;
  t37_tmp = t6 * t13_tmp;
  t38_tmp = in2[4] * t10_tmp;
  t39_tmp = in2[3] * t17;
  t46_tmp = in2[5] * t218;
  t40_tmp = ((((in2[2] - in2[74]) + t37_tmp) + t38_tmp) + t39_tmp) - t46_tmp;
  t209 = t6 * t17;
  t49_tmp = ((((-in2[1] + in2[73]) + t238) + t235) + t234) - t209;
  t50_tmp = in2[4] * t7;
  t50 = t50_tmp * 0.03;
  t52 = t50_tmp * 0.038;
  t54_tmp = t6 * (t52 - 0.03);
  t55_tmp = in2[4] * (t50 + 0.038);
  t56_tmp = t50_tmp * t10_tmp;
  t57_tmp = ((t13_tmp + t54_tmp) + t55_tmp) + t56_tmp;
  t58_tmp = t6 * (t50 + 0.038);
  t63_tmp = in2[4] * (t52 - 0.03);
  t64_tmp = t50_tmp * t13_tmp;
  t59_tmp = ((t10_tmp + t58_tmp) - t63_tmp) - t64_tmp;
  t60_tmp = in2[3] * (t50 + 0.038);
  t61_tmp = t50_tmp * t17;
  t65_tmp = in2[5] * (t52 - 0.03);
  t62 = ((t218 + t60_tmp) + t61_tmp) - t65_tmp;
  t69 = (t6 * t23_tmp + in2[5] * t49_tmp) + in2[4] * t40_tmp;
  t70 = in2[3] * 0.076;
  t71_tmp_tmp = in2[4] * in2[5];
  t71_tmp = t71_tmp_tmp * t7;
  t71 = t71_tmp * 0.038;
  t72_tmp = in2[5] * t7;
  b_t72_tmp = t72_tmp * t13_tmp;
  t73 = ((t19 + t70) + t71) + b_t72_tmp;
  t75 = t71_tmp * 0.03;
  t76_tmp = t72_tmp * t10_tmp;
  t77_tmp = ((in2[5] * 0.114 + t75) + t76_tmp) - in2[3] * 0.06;
  t78 = in2[4] * 0.06;
  t79 = t6 * 0.076;
  t80_tmp = t72_tmp * t17;
  t81 = t45_tmp * 0.03;
  t84_tmp = t3 * t7;
  t84 = t84_tmp * 0.038;
  t82_tmp = (((t78 + t79) + t80_tmp) + t81) - t84;
  t85 = t2 * 2.0;
  t86 = t3 * 2.0;
  t87 = in2[4] * t6 * 2.0;
  t88 = t6 * 2.0;
  t89 = in2[3] * 2.0;
  t90 = t6 * t27_tmp;
  t91 = in2[4] * t29;
  st.site = &xab_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t92 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t93 = in2[4] * t62;
  t94 = t26_tmp * 0.03;
  t218 = in2[3] * t2 * t92;
  t97 = ((t94 + t218 * 0.03) + t210 * t10_tmp * t92) - t26_tmp * (t52 - 0.03);
  t102 = ((t26_tmp * 0.038 + t26_tmp * (t50 + 0.038)) + t218 * 0.038) + t210 *
    t13_tmp * t92;
  t103 = t50_tmp * 0.06;
  t104_tmp = in2[4] * t4 * t92;
  t104 = t104_tmp * 0.03;
  t218 = t210 * in2[5] * t92;
  t5 = t218 * 0.038;
  t106 = (((t103 + t104) + t210 * t17 * t92) - t5) + 0.076;
  t111_tmp = ((in2[4] * t27_tmp + t26_tmp * t23_tmp) - t6 * t29) - in2[5] * t36;
  t112 = t26_tmp * t40_tmp;
  t115 = (((t40_tmp + in2[4] * t59_tmp) + in2[5] * t62) - t6 * t57_tmp) -
    t50_tmp * t23_tmp;
  t117 = 1.0 / (((t2 + t3) + t4) - 1.0);
  t119 = t218 * 0.03;
  t218 = t45_tmp_tmp * t117;
  t121 = ((t218 * 0.038 + t119) + t45_tmp_tmp * t10_tmp * t92) - 0.06;
  t123 = ((t5 + t45_tmp_tmp * t13_tmp * t92) - t218 * 0.03) + 0.076;
  t218 = in2[5] * t4 * t92;
  t127_tmp = in2[3] * t3 * t92;
  t127 = (((t72_tmp * 0.06 + t218 * 0.03) + t45_tmp_tmp * t17 * t92) - t26_tmp *
          0.076) - t127_tmp * 0.038;
  t128 = in2[5] * t29;
  t129 = in2[3] * t77_tmp;
  t135 = t26_tmp * t49_tmp;
  t274 = ((((in2[1] - in2[73]) - t238) - t235) - t234) + t209;
  t139 = (((t274 + t6 * t77_tmp) + in2[4] * t73) + t72_tmp * t23_tmp) - in2[5] *
    t82_tmp;
  t141 = in2[4] * 2.0 - t45_tmp * 2.0;
  t144 = in2[5] * 2.0 + t25_tmp * 2.0;
  t148 = t7 * t17;
  t5 = t72_tmp * 0.038;
  t150 = ((((t26_tmp * 0.15 + in2[3] * t4 * t92 * 0.03) + t148) + t4 * t17 * t92)
          - t5) - t218 * 0.038;
  t151 = t7 * t13_tmp;
  t218 = t4 * t117;
  t154_tmp = t52 + t151;
  t154 = (((t154_tmp + t4 * t13_tmp * t92) + t104_tmp * 0.038) - t218 * 0.03) -
    0.09;
  t156 = t7 * t10_tmp;
  t158 = ((((t50 + t104) + t218 * 0.038) + t156) + t4 * t10_tmp * t92) - 0.038;
  t297 = in2[3] * t36;
  t104_tmp = in2[3] * t57_tmp;
  t104 = in2[5] * t59_tmp;
  t188 = ((((((((((((((((((in2[73] * -2.0 + t90) + t91) - t93) + t112) + in2[1] *
                       2.0) + t104_tmp) + t104) + in2[5] * ((((((t59_tmp +
    t50_tmp * t36) + t26_tmp * t62) + t210 * t49_tmp * t92) - in2[5] * t97) -
    in2[3] * t102) - t6 * t106)) + t6 * ((((((t27_tmp + t6 * t97) + in2[4] *
    t102) + t50_tmp * t29) + t210 * t23_tmp * t92) - in2[5] * t106) - t26_tmp *
    t57_tmp)) + t209 * 2.0) + in2[3] * ((((((((((-t11 + t12) - t34) - t35_tmp) +
    t45) + t54_tmp) + t55_tmp) + t56_tmp) + in2[3] * t97) - in2[5] * t102) -
    in2[4] * t106)) + t26_tmp * t115) + t210 * t69 * t92) - t235 * 2.0) - t238 *
             2.0) - t234 * 2.0) - t297) - in2[4] * (((((((((((-t19 + t41) +
    t42_tmp) + t60_tmp) + t61_tmp) - t65_tmp) + in2[4] * t97) + in2[3] * t106) +
              t50_tmp * t27_tmp) - t6 * t102) - t26_tmp * t59_tmp) - t210 *
           t40_tmp * t92)) - t50_tmp * t111_tmp;
  t189 = t88 - t2 * t7 * 2.0;
  t191 = in2[3] * t59_tmp;
  t192 = in2[4] * t77_tmp;
  t218 = in2[5] * t2 * t92;
  t196 = ((t72_tmp * 0.03 + t218 * 0.03) + t71_tmp_tmp * t10_tmp * t92) -
    t72_tmp * (t52 - 0.03);
  t200 = ((t5 + t72_tmp * (t50 + 0.038)) + t218 * 0.038) + t71_tmp_tmp * t13_tmp
    * t92;
  t102 = t50_tmp * 0.076;
  t11 = in2[4] * t3 * t92;
  t12 = t11 * 0.038;
  t202 = (((t119 + t71_tmp_tmp * t17 * t92) - t102) - t12) + 0.06;
  t206 = in2[3] * t82_tmp;
  t207 = t50_tmp * t49_tmp;
  out1[0] = (t85 + t86) - 1.0;
  t209 = in2[5] * t6 * 2.0;
  out1[1] = t210 * -2.0 - t209;
  t273 = t45_tmp_tmp * 2.0;
  out1[2] = t87 - t273;
  t119 = in2[3] * t27_tmp;
  out1_tmp = t6 * t36;
  b_out1_tmp = in2[3] * t29;
  c_out1_tmp = in2[5] * t27_tmp;
  d_out1_tmp = in2[4] * t36;
  out1[3] = ((((((-in2[4] * ((((t274 + t90) + t91) + t112) - t297) - in2[5] *
                  ((((t40_tmp + t128) + t135) - t119) - out1_tmp)) + in2[4] *
                 (((((-in2[1] + in2[73]) + t238) + t235) + t234) - t6 * t17)) +
                in2[3] * t23_tmp) - in2[5] * t40_tmp) - t6 * t111_tmp) + in2[3] *
             (((t23_tmp + b_out1_tmp) + c_out1_tmp) + d_out1_tmp)) - t26_tmp *
    t69;
  t5 = ((((in2[0] - in2[72]) - t18_tmp) - t21_tmp) - t22_tmp) + t48_tmp;
  t106 = in2[5] * t57_tmp;
  t97 = t6 * t62;
  e_out1_tmp = in2[4] * t57_tmp;
  f_out1_tmp = in2[3] * t62;
  g_out1_tmp = t6 * t59_tmp;
  h_out1_tmp = t50_tmp * t40_tmp;
  out1[4] = ((((((-in2[4] * t23_tmp + in2[3] * t49_tmp) + t6 * t40_tmp) + t6 *
                t115) + in2[3] * (((t49_tmp + t93) - t104_tmp) - t104)) - in2[5]
              * (((t191 + t207) - t106) - t97)) + in2[4] * ((((t5 + e_out1_tmp)
    + f_out1_tmp) + g_out1_tmp) - h_out1_tmp)) - t50_tmp * t69;
  t297 = in2[5] * t73;
  t274 = in2[4] * t82_tmp;
  t104_tmp = t6 * t73;
  t104 = t72_tmp * t40_tmp;
  i_out1_tmp = in2[3] * t73;
  j_out1_tmp = in2[5] * t77_tmp;
  k_out1_tmp = t6 * t82_tmp;
  l_out1_tmp = t72_tmp * t49_tmp;
  out1[5] = ((((((in2[4] * (((t192 + t206) - t104_tmp) - t104) - in2[5] *
                  t23_tmp) - in2[3] * t40_tmp) + t6 * t49_tmp) - t6 * t139) -
              in2[3] * (((t40_tmp + t129) - t297) - t274)) + in2[5] * ((((t5 +
    i_out1_tmp) + j_out1_tmp) + k_out1_tmp) - l_out1_tmp)) - t72_tmp * t69;
  memset(&out1[6], 0, 66U * sizeof(real_T));
  out1[72] = (-t85 - t86) + 1.0;
  out1[73] = t210 * 2.0 + t209;
  out1[74] = -t87 + t273;
  memset(&out1[75], 0, sizeof(real_T) << 4);
  t209 = t71_tmp * 2.0;
  t210 = t89 - t209;
  t211 = in2[72] * 2.0;
  t212 = t7 * t23_tmp;
  t218 = t2 * t92;
  t5 = t7 * 0.038 + t218 * 0.038;
  t218 = t7 * 0.03 + t218 * 0.03;
  t87 = ((t148 + in2[3] * t218) + t2 * t17 * t92) - in2[5] * t5;
  t86 = (((((t103 + t156) + t6 * t5) + in2[4] * t218) + t2 * t10_tmp * t92) -
         t50_tmp * (t52 - 0.03) * 2.0) + 0.076;
  t85 = (((((t151 + t102) + in2[4] * t5) + t2 * t13_tmp * t92) + t50_tmp * (t50
           + 0.038) * 2.0) - t6 * t218) - 0.06;
  t93 = t18_tmp * 2.0;
  t234 = t21_tmp * 2.0;
  t235 = t22_tmp * 2.0;
  t238 = ((((t94 + t148) + t3 * t17 * t92) + t127_tmp * 0.03) - t72_tmp * 0.19)
    - in2[5] * t3 * t92 * 0.038;
  t218 = t3 * t117;
  t91 = ((((t50 + t156) + t218 * 0.038) + t3 * t10_tmp * t92) + t11 * 0.03) +
    0.114;
  t112 = (((t154_tmp + t12) + t3 * t13_tmp * t92) - t218 * 0.03) + 0.03;
  t90 = t7 * t69;
  t273 = ((((((((((((((((((t128 + t129) + t135) + in2[2] * 2.0) - in2[74] * 2.0)
                       + t37_tmp * 2.0) + t38_tmp * 2.0) + t39_tmp * 2.0) + in2
                    [3] * ((((((((t15 + t16) - t25) - b_t26_tmp) + t75) +
    t76_tmp) + in2[3] * t121) - in2[5] * t123) - in2[4] * t127)) + t6 *
                   ((((((((((-t33 - t34) - t35_tmp) + t44) + t45) + in2[4] *
    t123) + t6 * t121) + t72_tmp * t29) + t45_tmp_tmp * t23_tmp * t92) - in2[5] *
                     t127) - t26_tmp * t77_tmp)) + t45_tmp_tmp * t69 * t92) -
                 t46_tmp * 2.0) - t119) - t297) - t274) - in2[4] * ((((((t82_tmp
    + in2[4] * t121) + in2[3] * t127) + t26_tmp * t73) + t72_tmp * t27_tmp) - t6
    * t123) - t45_tmp_tmp * t40_tmp * t92)) - in2[5] * (((((((((((t14 - t19) +
    t41) + t42_tmp) + t71) + b_t72_tmp) + in2[5] * t121) + in2[3] * t123) + t6 *
    t127) - t72_tmp * t36) - t26_tmp * t82_tmp) - t45_tmp_tmp * t49_tmp * t92))
           - out1_tmp) - t72_tmp * t111_tmp) - t26_tmp * t139;
  t274 = t88 - t84_tmp * 2.0;
  t297 = (((((((((((((-t191 + t192) + t206) - t207) + t106) + t97) + in2[5] *
                 ((((((t57_tmp + in2[5] * t196) + in2[3] * t200) + t6 * t202) -
                    t72_tmp * t62) - t50_tmp * t82_tmp) - t71_tmp_tmp * t49_tmp *
                  t92)) + in2[3] * (((((((((t10_tmp - t58_tmp) + t63_tmp) +
    t64_tmp) + t80_tmp) + t81) - t84) + in2[5] * t200) + in2[4] * t202) - in2[3]
    * t196)) + in2[4] * ((((((t77_tmp + in2[4] * t196) + in2[3] * t202) +
    t50_tmp * t73) - t6 * t200) - t72_tmp * t59_tmp) - t71_tmp_tmp * t40_tmp *
    t92)) + t50_tmp * t139) - t104_tmp) - t6 * (((((((((((t14 - t60_tmp) -
    t61_tmp) + t65_tmp) + t71) + b_t72_tmp) + t6 * t196) + in2[4] * t200) +
    t71_tmp_tmp * t23_tmp * t92) - in2[5] * t202) - t72_tmp * t57_tmp) - t50_tmp
             * t77_tmp)) - t104) - t72_tmp * t115) - t71_tmp_tmp * t69 * t92;
  t97 = t89 + t209;
  t11 = in2[4] * in2[103] * 4.0;
  t12 = in2[5] * in2[104] * 4.0;
  t209 = t189 * in2[103];
  out2[0] = t11 + t12;
  t119 = t274 * in2[104];
  out2[1] = (-t141 * in2[102] - t119) - in2[103] * (t89 - in2[4] * in2[5] * t7 *
    2.0);
  t104 = t144 * in2[102];
  t102 = t97 * in2[104];
  out2[2] = (t209 - t104) - t102;
  t106 = (((in2[0] * -2.0 + t211) + t93) + t234) + t235;
  t5 = t48_tmp * 2.0;
  t104_tmp = t7 * t40_tmp;
  t218 = t7 * t49_tmp;
  out2[3] = (((((-t141 * in2[100] - t144 * in2[101]) - t188 * in2[103]) + t141 *
               in2[172]) + t144 * in2[173]) - t273 * in2[104]) + in2[102] *
    (((((((((((t106 + in2[4] * ((((((((((in2[4] * 0.152 - t6 * 0.12) + in2[3] *
    t150) + in2[4] * t158) + t34_tmp * 0.06) - t104_tmp) - t6 * t154) - t45_tmp *
    0.076) + t35_tmp * 2.0) + t26_tmp * t27_tmp * 2.0) - t4 * t40_tmp * t92)) -
              t5) + b_out1_tmp * 2.0) + c_out1_tmp * 2.0) + d_out1_tmp * 2.0) -
          t90) + in2[3] * ((((((in2[5] * 0.12 + t70) + in2[4] * t150) + in2[5] *
             t154) - in2[3] * t158) - t25_tmp * 0.06) - t42_tmp * 2.0)) + in2[5]
        * (((((((((in2[3] * -0.18 + in2[5] * 0.152) + in2[3] * t154) + in2[5] *
                 t158) - t218) + t6 * t150) + t25_tmp * 0.076) + b_t26_tmp * 2.0)
            - t26_tmp * t36 * 2.0) - t4 * t49_tmp * t92)) - t6 * (((((t212 -
            in2[5] * t150) + in2[4] * t154) + t6 * t158) + t26_tmp * t29 * 2.0)
        + t4 * t23_tmp * t92)) + t26_tmp * t111_tmp * 2.0) - t4 * t69 * t92);
  out2[4] = (((((((in2[4] * in2[99] * 4.0 - in2[4] * in2[171] * 4.0) - t188 *
                  in2[102]) + t189 * in2[101]) - t210 * in2[100]) - t189 * in2
               [173]) + t210 * in2[172]) + t297 * in2[104]) - in2[103] *
    ((((((((((((t106 + t90) - in2[3] * (((((((t28 + t70) + t60_tmp * 2.0) -
    t65_tmp * 2.0) + in2[4] * t87) - in2[3] * t86) + in2[5] * t85) + t61_tmp *
    2.0)) - t5) - e_out1_tmp * 2.0) - f_out1_tmp * 2.0) - in2[4] * ((((((((((t33
    - t44) + t55_tmp * 2.0) + in2[3] * t87) + in2[4] * t86) - t104_tmp) +
    t54_tmp * 2.0) - t6 * t85) + t56_tmp * 2.0) - t50_tmp * t59_tmp * 2.0) - t2 *
            t40_tmp * t92)) - g_out1_tmp * 2.0) - in2[5] * (((((in2[5] * t86 +
              in2[3] * t85) - t218) + t6 * t87) - t50_tmp * t62 * 2.0) - t2 *
          t49_tmp * t92)) + t6 * ((((((((((-t78 - t79) + t212) + t63_tmp * 2.0)
    - in2[5] * t87) + in2[4] * t85) - t58_tmp * 2.0) + t6 * t86) + t64_tmp * 2.0)
          - t50_tmp * t57_tmp * 2.0) + t2 * t23_tmp * t92)) + h_out1_tmp * 2.0)
      + t50_tmp * t115 * 2.0) + t2 * t69 * t92);
  out2[5] = (((((((in2[104] * ((((((((((((((((in2[0] * 2.0 - t211) - t93) - t234)
    - t235) - t90) + t5) + i_out1_tmp * 2.0) + j_out1_tmp * 2.0) + k_out1_tmp *
    2.0) + t6 * ((((((((((in2[4] * 0.12 + t6 * 0.152) - t212) + in2[5] * t238) -
    in2[4] * t112) - t84_tmp * 0.076) - t6 * t91) + t45_tmp * 0.06) + t80_tmp *
                   2.0) + t72_tmp * t77_tmp * 2.0) - t3 * t23_tmp * t92)) + in2
    [3] * ((((((in2[3] * 0.152 + t28) + in2[4] * t238) - in2[3] * t91) + in2[5] *
             t112) + t71_tmp * 0.076) + b_t72_tmp * 2.0)) + in2[4] * (((((in2[3]
    * t238 + in2[4] * t91) - t104_tmp) - t6 * t112) + t72_tmp * t73 * 2.0) - t3 *
    t40_tmp * t92)) + in2[5] * (((((((((in2[3] * -0.12 + in2[5] * 0.228) + in2[3]
    * t112) + in2[5] * t91) - t218) + t6 * t238) + t71_tmp * 0.06) + t76_tmp *
    2.0) - t72_tmp * t82_tmp * 2.0) - t3 * t49_tmp * t92)) - l_out1_tmp * 2.0) +
    t72_tmp * t139 * 2.0) - t3 * t69 * t92) + in2[5] * in2[99] * 4.0) - in2[5] *
                  in2[171] * 4.0) - t274 * in2[100]) - t273 * in2[102]) - t97 *
               in2[101]) + t297 * in2[103]) + t274 * in2[172]) + t97 * in2[173];
  memset(&out2[6], 0, 66U * sizeof(real_T));
  out2[72] = -t11 - t12;
  out2[73] = (t141 * in2[102] + t210 * in2[103]) + t119;
  out2[74] = (-t209 + t104) + t102;
  memset(&out2[75], 0, sizeof(real_T) << 4);
  *out3 = 0.0;
}

/* End of code generation (cnstF3.c) */
