/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "massF1.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo ng_emlrtRSI = { 16, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

static emlrtRSInfo og_emlrtRSI = { 17, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

static emlrtRSInfo pg_emlrtRSI = { 18, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

static emlrtRSInfo qg_emlrtRSI = { 20, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

static emlrtRSInfo rg_emlrtRSI = { 23, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

static emlrtRSInfo sg_emlrtRSI = { 31, /* lineNo */
  "massF1",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in2[198], real_T out2[546],
            real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:21:06 */
  st.site = &ng_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[3] * in2[3];
  st.site = &og_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[4] * in2[4];
  st.site = &pg_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[5] * in2[5];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &qg_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[5] * 2.0;
  t28 = in2[3] * in2[4];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &rg_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[3] * in2[5] * t6 * 2.0;
  t12 = in2[3] * 2.0;
  t13 = in2[4] * in2[5] * t6 * 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = 0.0;
  out2[20] = 0.0;
  out2[21] = t9 + t2 * t6 * 2.0;
  out2[22] = -t7 + t8;
  out2[23] = in2[4] * 2.0 + t11;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = 0.0;
  out2[27] = t7 + t8;
  out2[28] = t9 + t3 * t6 * 2.0;
  out2[29] = -t12 + t13;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = 0.0;
  out2[33] = in2[4] * -2.0 + t11;
  out2[34] = t12 + t13;
  out2[35] = t9 + t4 * t6 * 2.0;
  memset(&out2[36], 0, 510U * sizeof(real_T));
  st.site = &sg_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[4] * t6 * 2.0;
  t16 = in2[4] * t2 * t14 * 2.0;
  t17 = in2[3] * t6 * 2.0;
  t18 = t28 * in2[5] * t14 * 2.0;
  t9 = in2[5] * t6 * 2.0;
  t11 = in2[5] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[3] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[5] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[3] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[4] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 21U * sizeof(real_T));
  out3[21] = (t12 * in2[103] + t5 * in2[104]) + in2[102] * (t17 + in2[3] * t2 *
    t14 * 2.0);
  out3[22] = (t12 * in2[102] + (t18 + 2.0) * in2[104]) - in2[103] * (t17 - t13);
  out3[23] = ((t18 - 2.0) * in2[103] + t5 * in2[102]) - in2[104] * (t17 - t28);
  out3[24] = 0.0;
  out3[25] = 0.0;
  out3[26] = 0.0;
  out3[27] = (t7 * in2[103] + (t18 - 2.0) * in2[104]) - in2[102] * (t15 - t16);
  out3[28] = (t7 * in2[102] + t6 * in2[104]) + in2[103] * (t15 + in2[4] * t3 *
    t14 * 2.0);
  out3[29] = ((t18 + 2.0) * in2[102] + t6 * in2[103]) - in2[104] * (t15 - t30);
  out3[30] = 0.0;
  out3[31] = 0.0;
  out3[32] = 0.0;
  out3[33] = ((t18 + 2.0) * in2[103] + t31 * in2[104]) - in2[102] * (t9 - t11);
  out3[34] = ((t18 - 2.0) * in2[102] + t32 * in2[104]) - in2[103] * (t9 - t8);
  out3[35] = (t31 * in2[102] + t32 * in2[103]) + in2[104] * (t9 + in2[5] * t4 *
    t14 * 2.0);
  memset(&out3[36], 0, 510U * sizeof(real_T));
}

/* End of code generation (massF1.c) */
