/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "massF1.h"

/* Function Definitions */
void massF1(real_T phi_sym, const real_T in2[2], real_T s, real_T out1[36],
            real_T out2[6], real_T out3[6], real_T out4[6])
{
  static const real_T dv0[36] = { 0.0024, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0024,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0024, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0E-9,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0E-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0E-9 };

  int32_T i;
  static const real_T dv1[6] = { 0.0, 0.0, -9.81, 0.0, 0.0, 0.0 };

  real_T t2;
  real_T t3;
  (void)phi_sym;
  (void)s;
  memcpy(&out1[0], &dv0[0], 36U * sizeof(real_T));
  for (i = 0; i < 6; i++) {
    out4[i] = dv1[i];
  }

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(PHI_SYM,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jul-2019 03:44:28 */
  t2 = muDoubleScalarSin(in2[0]);
  t3 = muDoubleScalarCos(in2[0]);
  out2[0] = t3 * 0.135;
  out2[1] = 0.0;
  out2[2] = t2 * -0.135;
  out2[3] = 0.0;
  out2[4] = 1.0;
  out2[5] = 0.0;
  out3[0] = t2 * in2[1] * -0.135;
  out3[1] = 0.0;
  out3[2] = t3 * in2[1] * -0.135;
  out3[3] = 0.0;
  out3[4] = 0.0;
  out3[5] = 0.0;
}

/* End of code generation (massF1.c) */
