/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpKx18.c
 *
 * Code generation for function 'sprdmpKx18'
 *
 */

/* Include files */
#include "sprdmpKx18.h"
#include "EOM_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo ad_emlrtRSI = { 155,/* lineNo */
  "sprdmpKx18",                        /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\Friends\\Research\\Tendon Robot - Izad\\Model\\Izad TMTDyn\\eom\\sprdmpKx18.m"/* pathName */
};

static emlrtRSInfo cd_emlrtRSI = { 161,/* lineNo */
  "sprdmpKx18",                        /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\Friends\\Research\\Tendon Robot - Izad\\Model\\Izad TMTDyn\\eom\\sprdmpKx18.m"/* pathName */
};

/* Function Definitions */
void sprdmpKx18(const emlrtStack *sp, const real_T in1[27], const real_T in2[34],
                real_T s, real_T out1[6])
{
  emlrtStack st;
  real_T t10;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t105_tmp;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t109;
  real_T t115;
  real_T t12;
  real_T t120;
  real_T t121;
  real_T t125;
  real_T t13;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t49;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t6;
  real_T t65;
  real_T t66;
  real_T t67;
  real_T t72;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T t77;
  real_T t8;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPKX18 */
  /*     OUT1 = SPRDMPKX18(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     30-Apr-2021 15:51:29 */
  t6 = in2[1] * s;
  t8 = in2[5] * s;
  t10 = in2[9] * s;
  t12 = in2[13] * s;
  t13 = in2[14] * s;
  t15 = in1[16] * 2.0;
  t16 = in2[0] * 2.0;
  t17 = in2[4] * 2.0;
  t18 = in2[8] * 2.0;
  t49 = in2[12] / 2.0;
  t74 = in1[16] + -s;
  t54 = in2[1] + -in2[3];
  t55 = in2[5] + -in2[7];
  t56 = in2[9] + -in2[11];
  t65 = t15 + -(s * 2.0);
  t66 = t74 * t74;
  t67 = muDoubleScalarPower(in1[6], 4.0) + -muDoubleScalarPower(in1[7], 4.0);
  t74 = ((((in2[0] + in1[16] * in2[3]) + t6) + in2[1] * t15) + -in2[2]) + -(in2
    [3] * s);
  t75 = ((((in2[4] + in1[16] * in2[7]) + t8) + in2[5] * t15) + -in2[6]) + -(in2
    [7] * s);
  t76 = ((((in2[8] + in1[16] * in2[11]) + t10) + in2[9] * t15) + -in2[10]) +
    -(in2[11] * s);
  t77 = ((((in2[13] + in1[16] * in2[16]) + t13) + in2[14] * t15) + -in2[15]) +
    -(in2[16] * s);
  t72 = 1.0 / (muDoubleScalarExp(in1[16] * 200.0 + -(s * 200.0)) + 1.0);
  t102 = ((s * t49 + s * t12 / 2.0) + t13 * (s * s) / 2.0) + -(t66 * t72 * t77 /
    2.0);
  t105_tmp = in1[3] * (t72 - 1.0);
  t105 = in1[2] * t67 * 3.1415926535897931 / 4.0 + t105_tmp *
    2.5854448509802781E-11;
  t106 = ((t16 + t6 * 6.0) + t54 * t65 * t72 * 2.0) + -(t72 * t74 * 2.0);
  t107 = ((t17 + t8 * 6.0) + t55 * t65 * t72 * 2.0) + -(t72 * t75 * 2.0);
  t108 = ((t18 + t10 * 6.0) + t56 * t65 * t72 * 2.0) + -(t72 * t76 * 2.0);
  t15 = t65 * t72;
  t109 = ((s * t16 + s * t6 * 3.0) + -(t54 * t66 * t72)) + t15 * t74;
  t16 = ((s * t17 + s * t8 * 3.0) + -(t55 * t66 * t72)) + t15 * t75;
  t74 = (((s * t18 + s * t10 * 3.0) + -(t56 * t66 * t72)) + t15 * t76) + 1.0;
  t115 = (((t12 + t49) + s * t13 * 1.5) + -((in2[14] + -in2[16]) * t66 * t72 /
           2.0)) + t15 * t77 / 2.0;
  t103 = muDoubleScalarCos(t102);
  t104 = muDoubleScalarSin(t102);
  t102 = (t106 * t109 * 2.0 + t107 * t16 * 2.0) + t108 * t74 * 2.0;
  st.site = &ad_emlrtRSI;
  t65 = (t109 * t109 + t16 * t16) + t74 * t74;
  if (t65 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &c_emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t120 = 1.0 / muDoubleScalarSqrt(t65);
  t121 = muDoubleScalarPower(t120, 3.0);
  st.site = &cd_emlrtRSI;
  t65 = t74 * t120 / 2.0 + 0.5;
  if (t65 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &c_emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t125 = muDoubleScalarSqrt(t65);
  t49 = 1.0 / t125;
  t55 = t108 * t120 / 2.0 + -(t74 * t121 * t102 / 4.0);
  t76 = muDoubleScalarPower(t49, 3.0);
  t6 = t103 * t109;
  t54 = t6 * t120;
  t77 = t54 * t49;
  t10 = t103 * t16;
  t18 = t10 * t120;
  t75 = t18 * t49;
  t8 = t104 * t109;
  t17 = t8 * t120;
  t74 = t17 * t49;
  t15 = t104 * t16;
  t65 = t15 * t120;
  t16 = t65 * t49;
  t56 = t77 + t16;
  t66 = t103 * t115 * t125 + t104 * t49 * t55 / 2.0;
  t12 = t75 + -t74;
  t13 = t104 * t115 * t125 + -(t103 * t49 * t55 / 2.0);
  t6 = ((((((-(t103 * t106 * t120 * t49 / 2.0) + -(t104 * t107 * t120 * t49 /
              2.0)) + t115 * t74 / 2.0) + -(t115 * t75 / 2.0)) + t6 * t121 * t49
          * t102 / 4.0) + t15 * t121 * t49 * t102 / 4.0) + t54 * t76 * t55 / 4.0)
    + t65 * t76 * t55 / 4.0;
  t15 = ((((((t104 * t106 * t120 * t49 / 2.0 + -(t103 * t107 * t120 * t49 / 2.0))
             + t115 * t77 / 2.0) + t115 * t16 / 2.0) + t10 * t121 * t49 * t102 /
           4.0) + -(t8 * t121 * t49 * t102 / 4.0)) + t18 * t76 * t55 / 4.0) +
    -(t17 * t76 * t55 / 4.0);
  out1[0] = 0.0;
  out1[1] = 0.0;
  out1[2] = (1.0 / t120 - 1.0) * (in1[2] * 3.1415926535897931 * (in1[6] * in1[6]
    - in1[7] * in1[7]) - t105_tmp * 3.1415926535897931 * (in1[8] * in1[8] - in1
    [9] * in1[9]));
  t65 = t103 * t125;
  t74 = t104 * t125;
  out1[3] = -t105 * ((((-in1[19] * (t72 - 1.0) + t56 * t66) + t12 * t13) - t65 *
                      t15 * 2.0) + t74 * t6 * 2.0);
  out1[4] = -t105 * ((((-in1[20] * (t72 - 1.0) - t56 * t13) + t12 * t66) + t65 *
                      t6 * 2.0) + t74 * t15 * 2.0);
  out1[5] = (in1[4] * t67 * 3.1415926535897931 / 2.0 - in1[5] * (t72 - 1.0) *
             3.1415926535897931 * (muDoubleScalarPower(in1[8], 4.0) -
              muDoubleScalarPower(in1[9], 4.0)) / 2.0) * (((t56 * t15 - t12 * t6)
    + t65 * t66 * 2.0) + t74 * t13 * 2.0);
}

/* End of code generation (sprdmpKx18.c) */
