function out1 = cnstR2(in1,in2,s,ds,t_sym)
%CNSTR2
%    OUT1 = CNSTR2(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-May-2021 00:17:19

l_s1_ = in1(:,16);
l_s2_ = in1(:,17);
q5 = in2(5,:);
q6 = in2(6,:);
q7 = in2(7,:);
q8 = in2(8,:);
q18 = in2(18,:);
t2 = l_s1_+q18;
out1 = -q5.*t2.^2-q6.*t2.^3+((l_s2_-t2).^2.*(q5-q7+l_s2_.*q6.*2.0+l_s2_.*q8+q6.*t2-q8.*t2))./(exp(l_s2_.*2.0e+2-t2.*2.0e+2)+1.0);
