function out1 = sprdmpKx2(in1,in2,s,ds,t_sym)
%SPRDMPKX2
%    OUT1 = SPRDMPKX2(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 23:57:08

out1 = 0.0;
