function out1 = sprdmpDl18(in1,in2,s,ds,t_sym)
%SPRDMPDL18
%    OUT1 = SPRDMPDL18(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:39:33

dl_ = in1(:,19);
l_s1_ = in1(:,16);
l_s2_ = in1(:,17);
q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
q4 = in2(4,:);
q5 = in2(5,:);
q6 = in2(6,:);
q7 = in2(7,:);
q8 = in2(8,:);
q9 = in2(9,:);
q10 = in2(10,:);
q11 = in2(11,:);
q12 = in2(12,:);
t2 = dl_+l_s1_;
t3 = -l_s2_;
t6 = dl_.*2.0e+2;
t7 = l_s1_.*2.0e+2;
t8 = l_s2_.*2.0e+2;
t4 = t2.^2;
t5 = t2.^3;
t9 = -t6;
t10 = -t7;
t11 = t2+t3;
t12 = (l_s2_-t2).^2;
t13 = t2.*-2.0e+2+t8;
t14 = exp(t13);
t15 = t14+1.0;
t16 = 1.0./t15;
out1 = sqrt((q1.*t4+q2.*t5-t12.*t16.*(q1-q3+l_s2_.*q2.*2.0+l_s2_.*q4+q2.*t2-q4.*t2)).^2+(q5.*t4+q6.*t5-t12.*t16.*(q5-q7+l_s2_.*q6.*2.0+l_s2_.*q8+q6.*t2-q8.*t2)).^2+(t2+q9.*t4+q10.*t5-t12.*t16.*(q9-q11+l_s2_.*q10.*2.0+l_s2_.*q12+q10.*t2-q12.*t2)).^2);
