function out1 = sprdmpDir8(in1,in2,s,ds,t_sym)
%SPRDMPDIR8
%    OUT1 = SPRDMPDIR8(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:34:27

out1 = 1.0;
