function out1 = sprdmpTtu18(in1,in2,s,ds,t_sym)
%SPRDMPTTU18
%    OUT1 = SPRDMPTTU18(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:39:31

out1 = zeros(0,0);
