/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void massF1(const real_T in1[34], const real_T in2[36], real_T out1[36], real_T
            out2[108], real_T out3[108], real_T out4[6])
{
  real_T t10;
  real_T t100;
  real_T t101;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t109;
  real_T t11;
  real_T t110;
  real_T t115;
  real_T t116;
  real_T t123;
  real_T t124;
  real_T t125;
  real_T t126;
  real_T t127;
  real_T t128;
  real_T t129;
  real_T t131;
  real_T t132;
  real_T t133;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t138;
  real_T t140;
  real_T t141;
  real_T t142;
  real_T t143;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t147;
  real_T t148;
  real_T t149;
  real_T t15;
  real_T t150;
  real_T t156;
  real_T t157;
  real_T t159;
  real_T t16;
  real_T t161;
  real_T t163;
  real_T t165;
  real_T t166;
  real_T t167;
  real_T t168;
  real_T t17;
  real_T t171;
  real_T t172;
  real_T t173;
  real_T t174;
  real_T t175;
  real_T t176;
  real_T t177;
  real_T t178;
  real_T t179;
  real_T t180;
  real_T t182;
  real_T t183;
  real_T t184;
  real_T t185;
  real_T t186;
  real_T t187;
  real_T t197;
  real_T t199;
  real_T t20;
  real_T t201;
  real_T t203;
  real_T t205;
  real_T t205_tmp;
  real_T t206;
  real_T t207;
  real_T t208;
  real_T t209_tmp;
  real_T t21;
  real_T t210;
  real_T t211;
  real_T t212;
  real_T t22;
  real_T t224;
  real_T t23;
  real_T t256_tmp;
  real_T t261;
  real_T t271;
  real_T t278;
  real_T t278_tmp;
  real_T t279;
  real_T t280;
  real_T t280_tmp;
  real_T t281;
  real_T t281_tmp;
  real_T t298_tmp;
  real_T t299;
  real_T t31;
  real_T t310;
  real_T t310_tmp;
  real_T t316;
  real_T t316_tmp;
  real_T t317;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t5;
  real_T t57;
  real_T t58;
  real_T t59;
  real_T t60;
  real_T t61;
  real_T t64;
  real_T t65;
  real_T t66;
  real_T t68;
  real_T t69;
  real_T t7;
  real_T t70;
  real_T t71;
  real_T t78;
  real_T t8;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  real_T t98;
  real_T t99;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     15-Jun-2021 00:49:41 */
  t156 = muDoubleScalarCos(in1[20]);
  t207 = muDoubleScalarSin(in1[20]);
  t5 = in1[33] * in1[33];
  t7 = in1[2] * in1[2];
  t8 = in1[3] * in1[3];
  t10 = 1.0 / in1[33];
  t15 = in2[3] / 2.0;
  t16 = in2[4] / 2.0;
  t17 = in2[5] / 2.0;
  t11 = in1[18] * in1[18] * 6.0;
  t20 = muDoubleScalarCos(t15);
  t21 = muDoubleScalarCos(t16);
  t22 = muDoubleScalarCos(t17);
  t23 = muDoubleScalarSin(t15);
  t16 = muDoubleScalarSin(t16);
  t15 = muDoubleScalarSin(t17);
  t17 = t20 * t21;
  t31 = t17 * t15;
  t32 = t20 * t22 * t16;
  t33 = t21 * t22 * t23;
  t34 = t20 * t16 * t15;
  t35 = t21 * t23 * t15;
  t20 = t22 * t23 * t16;
  t21 = t23 * t16 * t15;
  t15 = t17 * t22;
  t16 = t31 / 2.0;
  t23 = t32 / 2.0;
  t57 = t33 / 2.0;
  t58 = t31 / 4.0;
  t59 = t32 / 4.0;
  t60 = t33 / 4.0;
  t61 = t34 / 2.0;
  t22 = t35 / 2.0;
  t17 = t20 / 2.0;
  t64 = t34 / 4.0;
  t65 = t35 / 4.0;
  t66 = t20 / 4.0;
  t68 = t21 / 2.0;
  t69 = t21 / 4.0;
  t70 = t15 / 2.0;
  t71 = t15 / 4.0;
  t83 = t31 + t20;
  t84 = t32 + t35;
  t85 = t33 + t34;
  t86 = t21 + t15;
  t299 = in1[4] * in1[0];
  t78 = -(t299 * ((t7 + t11) + -t8) * 3.1415926535897931 / 3.0);
  t87 = t31 + -t20;
  t88 = t32 + -t35;
  t89 = t33 + -t34;
  t90 = t21 + -t15;
  t91 = t31 * 2.0 + t20 * 2.0;
  t92 = t33 * 2.0 + t34 * 2.0;
  t95 = t16 + t17;
  t96 = t23 + t22;
  t97 = t57 + t61;
  t98 = t68 + t70;
  t99 = t58 + t66;
  t100 = t59 + t65;
  t101 = t60 + t64;
  t102 = t69 + t71;
  t20 = (t8 + -t7) + t11 * (1.0 / (t207 * t207)) * (t5 * (t156 * t156) - 1.0);
  t93 = t32 * 2.0 + -(t35 * 2.0);
  t94 = t21 * 2.0 + -(t15 * 2.0);
  t103 = t16 + -t17;
  t104 = t23 + -t22;
  t105 = t57 + -t61;
  t106 = t68 + -t70;
  t107 = t58 + -t66;
  t108 = t59 + -t65;
  t109 = t60 + -t64;
  t110 = t69 + -t71;
  t123 = t83 * t95;
  t124 = t83 * t97;
  t125 = t85 * t95;
  t126 = t85 * t97;
  t140 = t87 * t97;
  t141 = t88 * t95;
  t142 = t88 * t96;
  t143 = t88 * t97;
  t144 = t88 * t98;
  t145 = t89 * t95;
  t146 = t89 * t97;
  t147 = t90 * t95;
  t148 = t90 * t96;
  t149 = t90 * t97;
  t150 = t90 * t98;
  t70 = t91 * t95;
  t58 = t91 * t97;
  t66 = t92 * t95;
  t156 = t92 * t97;
  t157 = t91 * t99;
  t159 = t91 * t101;
  t161 = t92 * t99;
  t163 = t92 * t101;
  t205_tmp = in1[4] * t83;
  t205 = t205_tmp * t99 / 3.0;
  t206 = t205_tmp * t100 / 3.0;
  t207 = t205_tmp * t101 / 3.0;
  t208 = t205_tmp * t102 / 3.0;
  t209_tmp = in1[4] * t85;
  t11 = t209_tmp * t99 / 3.0;
  t210 = t209_tmp * t100 / 3.0;
  t211 = t209_tmp * t101 / 3.0;
  t212 = t209_tmp * t102 / 3.0;
  t256_tmp = in1[4] * t90;
  t278_tmp = in1[4] * t95;
  t278 = t278_tmp * t96 / 3.0;
  t279 = t278_tmp * t98 / 3.0;
  t280_tmp = in1[4] * t96;
  t280 = t280_tmp * t97 / 3.0;
  t281_tmp = in1[4] * t97;
  t281 = t281_tmp * t98 / 3.0;
  t115 = in1[4] * (t95 * t95) / 3.0;
  t116 = in1[4] * (t97 * t97) / 3.0;
  t15 = t299 * t20 * (in1[4] * in1[4] * t5 / 108.0 + t10 * (t7 * 3.0 + t8 * 3.0)
                      / 12.0) * 3.1415926535897931 / 3.0;
  out1[0] = t78;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t78;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t78;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t15;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t15;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t299 * t10 * t20 * 3.1415926535897931 * (t7 / 2.0 + t8 / 2.0) / 3.0;
  t127 = t83 * t103;
  t128 = t83 * t104;
  t129 = t83 * t105;
  t8 = t83 * t106;
  t131 = t84 * t104;
  t132 = t84 * t106;
  t133 = t85 * t103;
  t10 = t85 * t104;
  t135 = t85 * t105;
  t136 = t85 * t106;
  t137 = t86 * t104;
  t138 = t86 * t106;
  t165 = t88 * t104;
  t166 = t88 * t106;
  t167 = t90 * t104;
  t168 = t90 * t106;
  t171 = t91 * t107;
  t172 = t91 * t108;
  t173 = t91 * t109;
  t174 = t91 * t110;
  t175 = t93 * t99;
  t176 = t93 * t100;
  t177 = t93 * t101;
  t178 = t93 * t102;
  t179 = t92 * t107;
  t180 = t92 * t108;
  t182 = t92 * t110;
  t183 = t94 * t99;
  t184 = t94 * t100;
  t185 = t94 * t101;
  t186 = t94 * t102;
  t187 = -(t87 * t95);
  t16 = t93 * t104;
  t17 = t93 * t106;
  t20 = t94 * t106;
  t197 = t93 * t108;
  t199 = t93 * t110;
  t201 = t94 * t108;
  t203 = t94 * t110;
  t21 = in1[4] * t141 / 3.0;
  t23 = in1[4] * t143 / 3.0;
  t22 = in1[4] * t147 / 3.0;
  t31 = in1[4] * t149 / 3.0;
  t64 = in1[4] * t88;
  t32 = t64 * t107 / 3.0;
  t261 = t64 * t108 / 3.0;
  t69 = t64 * t109 / 3.0;
  t34 = t64 * t110 / 3.0;
  t71 = t256_tmp * t107 / 3.0;
  t33 = t256_tmp * t108 / 3.0;
  t59 = t256_tmp * t109 / 3.0;
  t271 = t256_tmp * t110 / 3.0;
  t298_tmp = in1[4] * t103;
  t65 = t298_tmp * t104 / 3.0;
  t299 = t298_tmp * t106 / 3.0;
  t15 = in1[4] * t104;
  t78 = t15 * t105 / 3.0;
  t60 = in1[4] * t105 * t106 / 3.0;
  t7 = in1[4] * (t104 * t104) / 3.0;
  t224 = -(t92 * t109);
  t57 = in1[4] * t128 / 3.0;
  t61 = in1[4] * t8 / 3.0;
  t35 = in1[4] * t10 / 3.0;
  t68 = -(t94 * t104);
  t310_tmp = ((t207 + t11) + t34) + t33;
  t310 = (t310_tmp + t278_tmp * t97 * 0.66666666666666663) + t15 * t106 *
    0.66666666666666663;
  t316_tmp = in1[4] * t98;
  t316 = ((((((t205_tmp * t107 / 3.0 + t209_tmp * t109 / 3.0) + t64 * t100 / 3.0)
             + t256_tmp * t102 / 3.0) + t278_tmp * t103 / 3.0) + t280_tmp * t104
           / 3.0) + t281_tmp * t105 / 3.0) + t316_tmp * t106 / 3.0;
  t317 = ((((((t206 + t212) + t32) + t59) + t278) + t281) + t65) + t60;
  t5 = -(in1[4] * (t106 * t106) / 3.0);
  t15 = -(in1[4] * t136 / 3.0);
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = ((in1[4] * t124 * -0.33333333333333331 - in1[4] * t125 / 3.0) -
              in1[4] * t166 / 3.0) - in1[4] * t167 / 3.0;
  out2[19] = ((-t61 + t35) + t23) - t22;
  out2[20] = ((-t57 + t15) + t21) + t31;
  out2[21] = ((t94 * t95 + t93 * t97) + t92 * t104) + t91 * t106;
  out2[22] = ((t58 + t66) - t17) + t68;
  out2[23] = ((-t70 + t156) - t16) + t20;
  out2[24] = ((t205_tmp * t96 * -0.33333333333333331 + t209_tmp * t98 / 3.0) +
              t64 * t103 / 3.0) - t256_tmp * t105 / 3.0;
  out2[25] = ((in1[4] * t127 / 3.0 + in1[4] * t135 / 3.0) + in1[4] * t142 / 3.0)
    + in1[4] * t150 / 3.0;
  out2[26] = ((in1[4] * t129 * -0.33333333333333331 + in1[4] * t133 / 3.0) -
              in1[4] * t144 / 3.0) + in1[4] * t148 / 3.0;
  out2[27] = ((t93 * t96 - t94 * t98) - t91 * t103) + t92 * t105;
  out2[28] = ((t91 * t96 - t92 * t98) + t93 * t103) - t94 * t105;
  out2[29] = ((t92 * t96 + t91 * t98) - t94 * t103) - t93 * t105;
  out2[30] = ((in1[4] * t123 * -0.33333333333333331 - in1[4] * t126 / 3.0) +
              in1[4] * t165 / 3.0) + in1[4] * t168 / 3.0;
  out2[31] = ((t57 + t15) + t21) - t31;
  out2[32] = ((t61 + t35) + t23) + t22;
  out2[33] = ((t93 * t95 + t94 * t97) - t91 * t104) - t92 * t106;
  out2[34] = ((t70 + t156) + t16) + t20;
  out2[35] = ((-t58 + t66) + t17) + t68;
  memset(&out2[36], 0, 72U * sizeof(real_T));
  t58 = ((t207 + -t11) + t33) + -t34;
  t66 = ((((t205_tmp * t108 / 3.0 + -(t209_tmp * t110 / 3.0)) + t64 * t99 / 3.0)
          + -(t256_tmp * t101 / 3.0)) + t278_tmp * t104 * 0.66666666666666663) +
    -(t281_tmp * t106 * 0.66666666666666663);
  t61 = ((t205_tmp * t110 / 3.0 + -(t209_tmp * t108 / 3.0)) + t256_tmp * t99 /
         3.0) + -(t64 * t101 / 3.0);
  t35 = (t61 + t278_tmp * t106 * 0.66666666666666663) + -(t281_tmp * t104 *
    0.66666666666666663);
  t68 = ((((((t128 + t149) + -t136) + t175) + t182) + -t141) + -t172) + -t185;
  t70 = ((((((t8 + t143) + -t10) + t180) + t183) + -t147) + -t174) + -t177;
  t57 = ((((((t206 + -t212) + t59) + -t32) + t278) + -t281) + t60) + -t65;
  t34 = ((((((t205_tmp * t109 / 3.0 + t209_tmp * t107 / 3.0) + -(t64 * t102 /
              3.0)) + -(t256_tmp * t100 / 3.0)) + t281_tmp * t103 / 3.0) +
          t278_tmp * t105 / 3.0) + -(t316_tmp * t104 / 3.0)) + -(t280_tmp * t106
    / 3.0);
  t33 = ((((((t208 + -t210) + t69) + -t71) + t279) + -t280) + t78) + -t299;
  t15 = ((((((t208 + t210) + -t69) + -t71) + -t279) + -t280) + t299) + t78;
  t31 = ((((((t115 + t116) + -t7) + t5) + t205) + t211) + -t261) + -t271;
  memset(&out3[0], 0, 18U * sizeof(real_T));
  out3[18] = (t35 * in2[21] - t66 * in2[23]) - t316 * in2[22];
  out3[19] = (-t310 * in2[21] - t31 * in2[23]) - t57 * in2[22];
  t23 = ((t115 + t7) + -t116) + t5;
  out3[20] = (-in2[21] * ((((t23 - t205) + t211) + t271) + -t261) + t58 * in2[23])
    - t15 * in2[22];
  t22 = ((t91 * t100 + t92 * t102) + t93 * t107) + t94 * t109;
  t21 = t123 + -t126;
  t20 = t124 + -t125;
  out3[21] = (in2[22] * ((((t22 - t83 * t96) - t85 * t98) - t88 * t103) - t90 *
    t105) - in2[23] * ((((((t21 - t157) + t163) + t165) - t197) + t203) + -t168))
    - in2[21] * ((((((t20 + t161) + t167) + t199) + -t159) + -t166) + -t201);
  out3[22] = (-in2[22] * (((((((t127 + t135) - t150) + t176) + t186) + -t142) +
    -t171) + t224) + t70 * in2[21]) - t68 * in2[23];
  t17 = ((t8 + t10) + t143) + t147;
  t16 = t128 + t136;
  out3[23] = (in2[21] * ((((((t16 + t175) - t182) + t185) + -t141) + -t149) +
    -t172) + in2[22] * (((((((t129 - t133) + t144) - t148) + t179) + t184) +
    -t173) + -t178)) - in2[23] * ((((t17 + -t174) + -t177) + -t180) + -t183);
  out3[24] = (-t316 * in2[21] - t34 * in2[23]) + in2[22] * ((t61 - t280_tmp *
    t105 * 0.66666666666666663) + t316_tmp * t103 * 0.66666666666666663);
  out3[25] = (-t57 * in2[21] + t33 * in2[23]) - in2[22] * ((t310_tmp - t280_tmp *
    t98 * 0.66666666666666663) - t298_tmp * t105 * 0.66666666666666663);
  out3[26] = (t317 * in2[23] - t15 * in2[21]) + in2[22] * (((((((t205 + -t211) +
    t261) + -t271) + in1[4] * (t96 * t96) / 3.0) - in1[4] * (t98 * t98) / 3.0) +
    in1[4] * (t103 * t103) / 3.0) - in1[4] * (t105 * t105) / 3.0);
  t15 = ((t91 * t102 + t92 * t100) - t93 * t109) - t94 * t107;
  out3[27] = (in2[21] * ((((t22 + t84 * t95) + t86 * t97) + t87 * t104) + t89 *
    t106) + in2[22] * (((((((t159 - t161) - t199) + t201) - t84 * t98) + t86 *
    t96) + t87 * t105) - t89 * t103)) - in2[23] * ((((t15 - t84 * t97) - t86 *
    t95) + t87 * t106) + t89 * t104);
  out3[28] = (-in2[22] * (((((((t174 + t177) + -t180) + -t183) + t87 * t98) -
    t89 * t96) + t84 * t105) - t86 * t103) - in2[21] * (((((((t131 + t138) -
    t146) + t176) + t186) + t187) + -t171) + t224)) + in2[23] * (((((((t132 +
    t137) + t140) + t145) + t173) + t178) + t179) + t184);
  out3[29] = (-in2[22] * (((((((t172 + t182) + -t175) + -t185) - t87 * t96) +
    t84 * t103) - t89 * t98) + t86 * t105) - in2[23] * (((((((t131 - t138) +
    t146) + t171) + t186) + t187) + -t176) + t224)) + in2[21] * (((((((t132 -
    t137) + t140) - t145) + t179) + t184) + -t173) + -t178);
  out3[30] = (-t66 * in2[21] + t35 * in2[23]) - t34 * in2[22];
  out3[31] = (-t310 * in2[23] - t31 * in2[21]) + t33 * in2[22];
  out3[32] = (t58 * in2[21] + t317 * in2[22]) + in2[23] * ((((t23 + t205) +
    -t211) + t261) + -t271);
  out3[33] = (in2[21] * ((((((t21 + t157) - t163) + t165) + t197) - t203) +
    -t168) + in2[23] * ((((((t20 + t159) - t161) + t167) - t199) + t201) + -t166))
    - in2[22] * ((((t15 + t83 * t98) + t85 * t96) - t88 * t105) - t90 * t103);
  out3[34] = (-t68 * in2[21] + t70 * in2[23]) - in2[22] * (((((((t129 + t133) +
    t144) + t148) - t179) - t184) + -t173) + -t178);
  out3[35] = (-in2[22] * (((((((t127 - t135) + t150) + t171) + t186) + -t142) +
    -t176) + t224) + in2[21] * ((((t17 + t174) + t177) + t180) + t183)) - in2[23]
    * ((((((t16 + t172) + t182) + -t141) + -t149) + -t175) + -t185);
  memset(&out3[36], 0, 72U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
