/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T b_in2[12];
  int32_T i0;
  int32_T i1;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     30-Jan-2019 17:24:26 */
  t2 = in1[4] + in2[2];
  t3 = in2[3] * in2[3];
  t4 = in2[4] * in2[4];
  t5 = in2[5] * in2[5];
  b_in2[0] = in2[0];
  b_in2[1] = in2[0];
  b_in2[2] = in2[1];
  b_in2[3] = in2[1];
  b_in2[4] = t2;
  b_in2[5] = t2;
  b_in2[6] = (in2[0] + in1[4] * in2[4]) + in1[4] * in2[3] * in2[5] * 0.5;
  b_in2[7] = (in2[0] + in1[16] * in2[4]) + in1[16] * in2[3] * in2[5] * 0.5;
  b_in2[8] = (in2[1] - in1[4] * in2[3]) + in1[4] * in2[4] * in2[5] * 0.5;
  b_in2[9] = (in2[1] - in1[16] * in2[3]) + in1[16] * in2[4] * in2[5] * 0.5;
  b_in2[10] = (((in1[4] * 2.0 + in2[2]) - in1[4] * t3 * 0.25) - in1[4] * t4 *
               0.25) + in1[4] * t5 * 0.25;
  b_in2[11] = ((((in1[16] + in1[4]) + in2[2]) - in1[16] * t3 * 0.25) - in1[16] *
               t4 * 0.25) + in1[16] * t5 * 0.25;
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 2; i1++) {
      r_jtip[i1 + (i0 << 1)] = b_in2[i1 + (i0 << 1)];
    }
  }
}

/* End of code generation (rjtipF.c) */
