/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * loadsF1.c
 *
 * Code generation for function 'loadsF1'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "loadsF1.h"

/* Function Definitions */
void loadsF1(real_T phi_sym, const real_T in2[2], real_T s)
{
  (void)phi_sym;
  (void)in2;
  (void)s;

  /* LOADSF1 */
  /*     [OUT1,OUT2] = LOADSF1(PHI_SYM,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jul-2019 03:32:31 */
}

/* End of code generation (loadsF1.c) */
