/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF11.c
 *
 * Code generation for function 'massF11'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "massF11.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo fj_emlrtRSI = { 16, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

static emlrtRSInfo gj_emlrtRSI = { 17, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

static emlrtRSInfo hj_emlrtRSI = { 18, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

static emlrtRSInfo ij_emlrtRSI = { 20, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

static emlrtRSInfo jj_emlrtRSI = { 23, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

static emlrtRSInfo kj_emlrtRSI = { 31, /* lineNo */
  "massF11",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF11.m"/* pathName */
};

/* Function Definitions */
void massF11(const emlrtStack *sp, const real_T in2[198], real_T out2[546],
             real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF11 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF11(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:21:11 */
  st.site = &fj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[63] * in2[63];
  st.site = &gj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[64] * in2[64];
  st.site = &hj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[65] * in2[65];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &ij_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[65] * 2.0;
  t28 = in2[63] * in2[64];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &jj_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[63] * in2[65] * t6 * 2.0;
  t12 = in2[63] * 2.0;
  t13 = in2[64] * in2[65] * t6 * 2.0;
  memset(&out2[0], 0, 360U * sizeof(real_T));
  out2[360] = 1.0;
  out2[361] = 0.0;
  out2[362] = 0.0;
  out2[363] = 0.0;
  out2[364] = 0.0;
  out2[365] = 0.0;
  out2[366] = 0.0;
  out2[367] = 1.0;
  out2[368] = 0.0;
  out2[369] = 0.0;
  out2[370] = 0.0;
  out2[371] = 0.0;
  out2[372] = 0.0;
  out2[373] = 0.0;
  out2[374] = 1.0;
  out2[375] = 0.0;
  out2[376] = 0.0;
  out2[377] = 0.0;
  out2[378] = 0.0;
  out2[379] = 0.0;
  out2[380] = 0.0;
  out2[381] = t9 + t2 * t6 * 2.0;
  out2[382] = -t7 + t8;
  out2[383] = in2[64] * 2.0 + t11;
  out2[384] = 0.0;
  out2[385] = 0.0;
  out2[386] = 0.0;
  out2[387] = t7 + t8;
  out2[388] = t9 + t3 * t6 * 2.0;
  out2[389] = -t12 + t13;
  out2[390] = 0.0;
  out2[391] = 0.0;
  out2[392] = 0.0;
  out2[393] = in2[64] * -2.0 + t11;
  out2[394] = t12 + t13;
  out2[395] = t9 + t4 * t6 * 2.0;
  memset(&out2[396], 0, 150U * sizeof(real_T));
  st.site = &kj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[64] * t6 * 2.0;
  t16 = in2[64] * t2 * t14 * 2.0;
  t17 = in2[63] * t6 * 2.0;
  t18 = t28 * in2[65] * t14 * 2.0;
  t9 = in2[65] * t6 * 2.0;
  t11 = in2[65] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[63] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[65] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[63] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[64] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 381U * sizeof(real_T));
  out3[381] = (t12 * in2[163] + t5 * in2[164]) + in2[162] * (t17 + in2[63] * t2 *
    t14 * 2.0);
  out3[382] = (t12 * in2[162] + (t18 + 2.0) * in2[164]) - in2[163] * (t17 - t13);
  out3[383] = ((t18 - 2.0) * in2[163] + t5 * in2[162]) - in2[164] * (t17 - t28);
  out3[384] = 0.0;
  out3[385] = 0.0;
  out3[386] = 0.0;
  out3[387] = (t7 * in2[163] + (t18 - 2.0) * in2[164]) - in2[162] * (t15 - t16);
  out3[388] = (t7 * in2[162] + t6 * in2[164]) + in2[163] * (t15 + in2[64] * t3 *
    t14 * 2.0);
  out3[389] = ((t18 + 2.0) * in2[162] + t6 * in2[163]) - in2[164] * (t15 - t30);
  out3[390] = 0.0;
  out3[391] = 0.0;
  out3[392] = 0.0;
  out3[393] = ((t18 + 2.0) * in2[163] + t31 * in2[164]) - in2[162] * (t9 - t11);
  out3[394] = ((t18 - 2.0) * in2[162] + t32 * in2[164]) - in2[163] * (t9 - t8);
  out3[395] = (t31 * in2[162] + t32 * in2[163]) + in2[164] * (t9 + in2[65] * t4 *
    t14 * 2.0);
  memset(&out3[396], 0, 150U * sizeof(real_T));
}

/* End of code generation (massF11.c) */
