/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF113.c
 *
 * Code generation for function 'sprdmpF113'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "sprdmpF113.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo nx_emlrtRSI = { 24, /* lineNo */
  "sprdmpF113",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF113.m"/* pathName */
};

static emlrtRSInfo ox_emlrtRSI = { 30, /* lineNo */
  "sprdmpF113",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF113.m"/* pathName */
};

static emlrtRSInfo sx_emlrtRSI = { 144,/* lineNo */
  "sprdmpF113",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF113.m"/* pathName */
};

static emlrtRSInfo tx_emlrtRSI = { 187,/* lineNo */
  "sprdmpF113",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF113.m"/* pathName */
};

/* Function Definitions */
void sprdmpF113(const emlrtStack *sp, const real_T in2[198], real_T out1[546],
                real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t147;
  real_T t164;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t124;
  real_T t26;
  real_T t27;
  real_T t53;
  real_T t28_tmp;
  real_T t32_tmp_tmp;
  real_T t32_tmp;
  real_T b_t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t41_tmp_tmp;
  real_T t41_tmp;
  real_T b_t41_tmp;
  real_T t45_tmp;
  real_T t54_tmp;
  real_T t57;
  real_T t63_tmp;
  real_T t63;
  real_T t67;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t74;
  real_T t76_tmp;
  real_T t79_tmp;
  real_T t80_tmp;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96_tmp;
  real_T t98;
  real_T t99;
  real_T t102;
  real_T t106;
  real_T t109;
  real_T t128_tmp;
  real_T t110_tmp;
  real_T t110;
  real_T t118_tmp;
  real_T t119;
  real_T t120;
  real_T t125;
  real_T t126;
  real_T t127;
  real_T t132_tmp;
  real_T b_t132_tmp;
  real_T t141_tmp;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF113 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF113(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:40:44 */
  t2 = in2[4] * in2[4];
  t3 = in2[5] * in2[5];
  t4 = in2[3] * in2[3];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &nx_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[5] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[3] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &ox_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t147 = in2[4] * 0.03 + t6 * 0.038;
  t164 = in2[4] * 0.038 - t6 * 0.03;
  t5 = in2[3] * 0.038;
  t22 = in2[3] * 0.03 - in2[5] * 0.038;
  t23 = t6 * t147;
  t24 = in2[5] * 0.03;
  t124 = t5 + t24;
  t26 = in2[3] * t124;
  t27 = in2[5] * t22;
  t53 = in2[4] * t164;
  t28_tmp = ((((-in2[0] + in2[72]) + t23) + t26) + t27) - t53;
  t32_tmp_tmp = in2[3] * in2[4];
  t32_tmp = t32_tmp_tmp * t12;
  b_t32_tmp = in2[3] * t12;
  t32 = ((in2[5] * 0.076 + t32_tmp * 0.038) + b_t32_tmp * t164) - in2[3] * 0.09;
  t34 = ((t5 + in2[5] * 0.06) - t32_tmp * 0.03) - b_t32_tmp * t147;
  t35 = in2[3] * t164;
  t36 = in2[5] * t147;
  t37 = in2[4] * t124;
  t41_tmp_tmp = in2[3] * in2[5];
  t41_tmp = t41_tmp_tmp * t12;
  b_t41_tmp = t4 * t12;
  t4 = (((in2[4] * 0.076 + b_t41_tmp * 0.03) + b_t32_tmp * t22) - t6 * 0.06) -
    t41_tmp * 0.038;
  t45_tmp = ((((in2[2] - in2[74]) + t6 * t164) + in2[4] * t147) + in2[3] * t22)
    - in2[5] * t124;
  t5 = t6 * t22;
  t54_tmp = ((((-in2[1] + in2[73]) + t35) + t36) + t37) - t5;
  t57 = (((t45_tmp + in2[5] * t34) + b_t32_tmp * t54_tmp) - in2[3] * t32) - t6 *
    t4;
  t63_tmp = ((((in2[1] - in2[73]) - t35) - t36) - t37) + t5;
  t63 = (((t63_tmp + t6 * t32) + in2[4] * t34) + b_t32_tmp * t45_tmp) - in2[3] *
    t4;
  t67 = ((t28_tmp + in2[3] * t34) + in2[5] * t32) + in2[4] * t4;
  t69 = ((in2[4] * t32 + b_t32_tmp * t28_tmp) - in2[5] * t4) - t6 * t34;
  t70 = in2[5] * t28_tmp;
  t71 = in2[3] * t45_tmp;
  t74 = in2[4] * t28_tmp;
  t76_tmp = in2[4] * t12;
  t5 = t76_tmp * 0.03 + 0.038;
  t4 = t76_tmp * 0.038 - 0.03;
  t79_tmp = t6 * t45_tmp;
  t80_tmp = in2[3] * t54_tmp;
  t34 = ((t164 + t6 * t4) + in2[4] * t5) + t76_tmp * t147;
  t32 = ((t147 + t6 * t5) - in2[4] * t4) - t76_tmp * t164;
  t5 = ((t124 + in2[3] * t5) + t76_tmp * t22) - in2[5] * t4;
  t93 = t6 * t28_tmp;
  t94 = in2[5] * t54_tmp;
  t95 = in2[4] * t45_tmp;
  t96_tmp = (t93 + t94) + t95;
  t98 = ((t54_tmp + in2[4] * t5) - in2[3] * t34) - in2[5] * t32;
  t99 = in2[3] * t28_tmp;
  t102 = ((in2[3] * t32 + t76_tmp * t54_tmp) - in2[5] * t34) - t6 * t5;
  t23 = ((((in2[0] - in2[72]) - t23) - t26) - t27) + t53;
  t106 = (((t23 + t6 * t32) + in2[4] * t34) + in2[3] * t5) - t76_tmp * t45_tmp;
  t109 = (((t45_tmp + in2[4] * t32) + in2[5] * t5) - t6 * t34) - t76_tmp *
    t28_tmp;
  t128_tmp = t6 * t54_tmp;
  t110_tmp = t70 + t71;
  t110 = t110_tmp - t128_tmp;
  t118_tmp = (-t74 + t79_tmp) + t80_tmp;
  t119 = in2[77] * 2.0;
  t120 = in2[3] - in2[75];
  t124 = ((-(in2[75] * in2[75]) - in2[76] * in2[76]) - in2[77] * in2[77]) + 1.0;
  t125 = t124;
  st.site = &sx_emlrtRSI;
  b_sqrt(&st, &t125);
  t126 = in2[4] - in2[76];
  t127 = in2[5] - in2[77];
  t32 = in2[4] * in2[5];
  t132_tmp = t32 * t12;
  b_t132_tmp = in2[5] * t12;
  t34 = ((t24 + in2[3] * 0.076) + t132_tmp * 0.038) + b_t132_tmp * t164;
  t4 = ((in2[5] * 0.114 + t132_tmp * 0.03) + b_t132_tmp * t147) - in2[3] * 0.06;
  t141_tmp = t3 * t12;
  t5 = (((in2[4] * 0.06 + t6 * 0.076) + b_t132_tmp * t22) + t41_tmp * 0.03) -
    t141_tmp * 0.038;
  t147 = (((t23 + in2[5] * t4) + in2[3] * t34) + t6 * t5) - b_t132_tmp * t54_tmp;
  t3 = ((in2[4] * t4 + in2[3] * t5) - t6 * t34) - b_t132_tmp * t45_tmp;
  t24 = (((t63_tmp + t6 * t4) + in2[4] * t34) + b_t132_tmp * t28_tmp) - in2[5] *
    t5;
  t53 = ((t45_tmp + in2[3] * t4) - in2[5] * t34) - in2[4] * t5;
  t26 = in2[4] * t54_tmp;
  t164 = in2[75] * 2.0;
  t27 = in2[4] * t6 * 2.0;
  t4 = t32_tmp_tmp * 2.0;
  t34 = t41_tmp_tmp * 2.0;
  t5 = t32 * 2.0;
  st.site = &tx_emlrtRSI;
  b_sqrt(&st, &t124);
  t32 = 1.0 / t124;
  t124 = t6 * 2.0;
  t23 = in2[4] * 2.0;
  out1[0] = (t8 + t11) - 1.0;
  out1[1] = -t7 - t4;
  out1[2] = t27 - t34;
  out1[3] = ((((((t99 + in2[4] * (((((-in2[1] + in2[73]) + t35) + t36) + t37) -
    t6 * t22)) - in2[5] * t45_tmp) - in2[5] * t57) - in2[4] * t63) + in2[3] *
              t67) - t6 * t69) - b_t32_tmp * t96_tmp;
  out1[4] = ((((t118_tmp + in2[3] * t98) - in2[5] * t102) + in2[4] * t106) + t6 *
             t109) - t76_tmp * t96_tmp;
  out1[5] = ((((((-t70 - t71) + t128_tmp) + in2[5] * t147) + in2[4] * t3) - in2
              [3] * t53) - t6 * t24) - b_t132_tmp * t96_tmp;
  memset(&out1[6], 0, 66U * sizeof(real_T));
  out1[72] = (-t8 - t11) + 1.0;
  out1[73] = t7 + t4;
  out1[74] = -t27 + t34;
  memset(&out1[75], 0, sizeof(real_T) << 4);
  out1[91] = t7 - t4;
  out1[92] = (t8 + t10) - 1.0;
  out1[93] = -t9 - t5;
  out1[94] = ((((((t74 - t80_tmp) + in2[3] * t63) + in2[4] * t67) + in2[5] * t69)
               - t79_tmp) - t6 * t57) + b_t32_tmp * t110;
  out1[95] = ((((((t99 + t26) - in2[5] * t45_tmp) + in2[4] * t98) - in2[3] *
                t106) - in2[5] * t109) - t6 * t102) + t76_tmp * t110;
  out1[96] = ((((((-t93 - t94) - t95) - in2[3] * t3) + in2[5] * t24) - in2[4] *
               t53) + t6 * t147) + b_t132_tmp * t110;
  memset(&out1[97], 0, 66U * sizeof(real_T));
  out1[163] = -t7 + t4;
  out1[164] = (-t8 - t10) + 1.0;
  out1[165] = t9 + t5;
  memset(&out1[166], 0, sizeof(real_T) << 4);
  out1[182] = t41_tmp_tmp * -2.0 - t27;
  out1[183] = t9 - t5;
  out1[184] = (t10 + t11) - 1.0;
  out1[185] = (((((t110_tmp + in2[3] * t57) + in2[5] * t67) - in2[4] * t69) -
                t128_tmp) + t6 * t63) + b_t32_tmp * t118_tmp;
  out1[186] = ((((t96_tmp + in2[5] * t98) + in2[3] * t102) + in2[4] * t109) - t6
               * t106) + t76_tmp * t118_tmp;
  out1[187] = ((((((t99 + t26) - in2[5] * t45_tmp) - in2[3] * t147) - in2[4] *
                 t24) - in2[5] * t53) - t6 * t3) + b_t132_tmp * t118_tmp;
  memset(&out1[188], 0, 66U * sizeof(real_T));
  out1[254] = t27 + t34;
  out1[255] = -t9 + t5;
  out1[256] = (-t10 - t11) + 1.0;
  memset(&out1[257], 0, 19U * sizeof(real_T));
  out1[276] = (t125 * -2.0 - b_t41_tmp * 2.0) + b_t32_tmp * t120 * 2.0;
  t4 = t32_tmp * 2.0;
  out1[277] = (-t119 - t4) + t76_tmp * t120 * 2.0;
  t5 = t41_tmp * 2.0;
  out1[278] = (in2[76] * 2.0 - t5) + b_t132_tmp * t120 * 2.0;
  memset(&out1[279], 0, 69U * sizeof(real_T));
  out1[348] = t124 + in2[3] * in2[75] * t32 * 2.0;
  out1[349] = in2[5] * 2.0 + in2[3] * in2[76] * t32 * 2.0;
  out1[350] = -t23 + in2[3] * in2[77] * t32 * 2.0;
  memset(&out1[351], 0, sizeof(real_T) << 4);
  out1[367] = (t119 - t4) + b_t32_tmp * t126 * 2.0;
  out1[368] = (t125 * -2.0 - t2 * t12 * 2.0) + t76_tmp * t126 * 2.0;
  t4 = t132_tmp * 2.0;
  out1[369] = (-t164 - t4) + b_t132_tmp * t126 * 2.0;
  memset(&out1[370], 0, 69U * sizeof(real_T));
  out1[439] = in2[5] * -2.0 + in2[4] * in2[75] * t32 * 2.0;
  out1[440] = t124 + in2[4] * in2[76] * t32 * 2.0;
  out1[441] = in2[3] * 2.0 + in2[4] * in2[77] * t32 * 2.0;
  memset(&out1[442], 0, sizeof(real_T) << 4);
  out1[458] = (in2[76] * -2.0 - t5) + b_t32_tmp * t127 * 2.0;
  out1[459] = (t164 - t4) + t76_tmp * t127 * 2.0;
  out1[460] = (t125 * -2.0 - t141_tmp * 2.0) + b_t132_tmp * t127 * 2.0;
  memset(&out1[461], 0, 69U * sizeof(real_T));
  out1[530] = t23 + in2[5] * in2[75] * t32 * 2.0;
  out1[531] = in2[3] * -2.0 + in2[5] * in2[76] * t32 * 2.0;
  out1[532] = t124 + in2[5] * in2[77] * t32 * 2.0;
  memset(&out1[533], 0, 13U * sizeof(real_T));
  for (i = 0; i < 6; i++) {
    out2[i] = 0.0;
    out3[i] = 0.0;
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF113.c) */
