/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_kF.c
 *
 * Code generation for function 'fj_kF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "fj_kF.h"

/* Function Definitions */
void fj_kF(const real_T in1[34], const real_T in2[12], real_T s, real_T fj_k[6])
{
  int32_T i;
  (void)in1;
  (void)in2;
  (void)s;

  /* FJ_KF */
  /*     FJ_K = FJ_KF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 13:21:32 */
  for (i = 0; i < 6; i++) {
    fj_k[i] = 0.0;
  }
}

/* End of code generation (fj_kF.c) */
