/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void massF1(const real_T in1[60], const real_T in2[48], real_T s, real_T out1[36],
            real_T out2[144], real_T out3[144], real_T out4[6])
{
  real_T t15_tmp;
  real_T t18;
  real_T t2;
  real_T t21;
  real_T t22;
  real_T t3;
  real_T t4;
  real_T t5;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     10-Mar-2021 20:34:05 */
  t2 = in1[9] * in1[9];
  t3 = in1[10] * in1[10];
  t4 = s * s;
  t5 = muDoubleScalarPower(s, 3.0);
  t18 = ((in1[51] / 2.0 + in2[0] * s / 2.0) + in2[1] * t4 / 2.0) + in2[2] * t5 /
    2.0;
  t21 = muDoubleScalarCos(t18);
  t18 = muDoubleScalarSin(t18);
  t15_tmp = -(in1[0] * (t2 + -t3) * 3.1415926535897931);
  t22 = t21 * t21;
  t18 *= t18;
  t21 = t15_tmp * (t2 / 4.0 + t3 / 4.0);
  out1[0] = t15_tmp;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t15_tmp;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t15_tmp;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t21;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t21;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t15_tmp * (t2 / 2.0 + t3 / 2.0);
  out2[0] = 0.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = s * t22 + s * t18;
  out2[6] = 0.0;
  out2[7] = 0.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = t4 * t22 + t4 * t18;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 0.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = t5 * t22 + t5 * t18;
  memset(&out2[18], 0, 126U * sizeof(real_T));
  memset(&out3[0], 0, 144U * sizeof(real_T));
  out4[0] = in1[32];
  out4[1] = in1[33];
  out4[2] = in1[34];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
