%% initialize
close all
clear all
format shorte
clc
pause( 1e-2 )

addpath('./tmtdyn','./hll','./eom');


%% parameters
l_xz2 = 73e-3 / 5 ;
l_y2 = 0.8e-3 ;
m_2 = 36e-3 / 15 ;

l_x1 = 76e-3 / 2 ;
l_z1 = 30e-3 ;
l_com1 = 135e-3 ;

g = 9.81 ; % gravity

% EBA
E = 1.5e3 ;
mu_pow = 1 ; % < 1: rate thining, > 1: rate thikening
mu_v = 5e1 ;
mu_u = 5e1;
mu_link = 7e-4 ;

phi = -50 * pi/ 180 ;
 
% variables & values
syms E_sym mu_pow_sym mu_v_sym mu_u_sym phi_sym mu_link_sym
vars = [E_sym, mu_pow_sym, mu_v_sym, mu_u_sym, phi_sym, mu_link_sym];
var_vals = [E, mu_pow, mu_v, mu_u, phi, mu_link] ;


%% preprocess
G = E_sym / 3 ;
I_2 = 1 / 12 * m_2 * ...
    diag( [ l_y2^2+l_xz2^2 l_xz2^2+l_xz2^2 l_xz2^2+l_y2^2 ] ) ;
J_2 = 1 / 12 * [ l_xz2*l_y2^3 l_xz2^3*l_y2 l_xz2*l_y2^3+l_xz2^3*l_y2 ] ;
a_xy2 = l_xz2 * l_y2 ;
K_v = diag( [ G G E_sym ] ) * a_xy2 / l_xz2 ;
K_u = diag( [ E_sym E_sym G ] ) * diag( J_2 ) / l_xz2 ;


%% simple arm
tmtdyn()...
    .simulation()... % simulation
        .var(phi_sym, phi)...
        .derive_eom()...
            .simplify_derivations()...
            .use_mex()...
            .optimize_code()...
        .analysis()...
            .dynamic_sim('m_file', 0, 1)...
        .post_process()...
            .animate()...
            .run_user_code()...
    .world()... % world
        .g([ 0 0 -g ])...
    .robot('fabric_pendulum')... % robot
        .body('arm1')...
            .with_mass(m_2)...
            .with_center_of_mass_at([0 0 l_com1])...
		    .connected()...
		        .with_transformation_from()...
		            .rot_y()...
					    .initial_value(phi_sym)...
        .body('arm2')...
            .with_mass(m_2)...
            .with_center_of_mass_at([0 0 l_com1])...
		    .connected()...
                .from_body(1)...
		        .with_transformation_from()...
                    .trans_z(2*l_com1)...
		            .rot_y()...
					    .initial_value(phi_sym)...
    .run();

