/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 40,    /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 41,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 42,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 43,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 72,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 73,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 74,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 76,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\ss17282\\Desktop\\1. STIFF-FLOP\\code\\rjtipF.m"/* pathName */
};

static emlrtRSInfo i_emlrtRSI = { 49,  /* lineNo */
  "power",                             /* fcnName */
  "C:\\Program Files\\MATLAB\\R2017b\\toolbox\\eml\\lib\\matlab\\ops\\power.m"/* pathName */
};

static emlrtRSInfo j_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "C:\\Program Files\\MATLAB\\R2017b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pathName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[60],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t16;
  real_T t17;
  real_T t23;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T b_in2[12];
  int32_T i0;
  int32_T i1;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     11-Jan-2019 21:59:40 */
  st.site = &emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t2 = in1[4] * in1[4];
  st.site = &b_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t3 = s * s;
  st.site = &c_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t4 = t2 * t2;
  st.site = &d_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t5 = t3 * t3;
  t6 = in2[0] * t2;
  t7 = in1[4] * in2[1] * t2;
  t8 = in2[2] * t4;
  t9 = in1[4] * in2[3] * t4;
  t10 = in2[4] * t2 * t4;
  t16 = (((in1[4] * in2[15] + in2[16] * t2) + in1[4] * in2[17] * t2) + in2[18] *
         t4) + in1[4] * in2[19] * t4;
  t17 = (((in1[4] * in2[20] + in2[21] * t2) + in1[4] * in2[22] * t2) + in2[23] *
         t4) + in1[4] * in2[24] * t4;
  t23 = (((in1[4] * in2[25] + in2[26] * t2) + in1[4] * in2[27] * t2) + in2[28] *
         t4) + in1[4] * in2[29] * t4;
  t29 = in2[5] * t2;
  t30 = in1[4] * in2[6] * t2;
  t31 = in2[7] * t4;
  t32 = in1[4] * in2[8] * t4;
  t33 = in2[9] * t2 * t4;
  st.site = &e_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t34 = t16 * t16;
  st.site = &f_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t35 = t17 * t17;
  st.site = &g_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t36 = t23 * t23;
  t37 = ((-t34 - t35) - t36) + 1.0;
  st.site = &h_emlrtRSI;
  if (t37 < 0.0) {
    b_st.site = &j_emlrtRSI;
    c_st.site = &j_emlrtRSI;
    error(&c_st);
  }

  t37 = muDoubleScalarSqrt(t37);
  t39 = in2[10] * t2;
  t40 = in1[4] * in2[11] * t2;
  t41 = in2[12] * t4;
  t42 = in1[4] * in2[13] * t4;
  t43 = in2[14] * t2 * t4;
  b_in2[0] = (((in2[0] * t2 * t3 + in2[2] * t4 * t5) + in1[4] * in2[1] * s * t2 *
               t3) + in1[4] * in2[3] * s * t4 * t5) + in2[4] * t2 * t3 * t4 * t5;
  b_in2[1] = (((t6 + t7) + t8) + t9) + t10;
  b_in2[2] = (((in2[5] * t2 * t3 + in2[7] * t4 * t5) + in1[4] * in2[6] * s * t2 *
               t3) + in1[4] * in2[8] * s * t4 * t5) + in2[9] * t2 * t3 * t4 * t5;
  b_in2[3] = (((t29 + t30) + t31) + t32) + t33;
  b_in2[4] = ((((in1[4] * s + in2[10] * t2 * t3) + in2[12] * t4 * t5) + in1[4] *
               in2[11] * s * t2 * t3) + in1[4] * in2[13] * s * t4 * t5) + in2[14]
    * t2 * t3 * t4 * t5;
  b_in2[5] = ((((in1[4] + t39) + t40) + t41) + t42) + t43;
  b_in2[6] = rtNaN;
  b_in2[7] = (((((t6 + t7) + t8) + t9) + t10) + in1[16] * t16 * t23 * 2.0) +
    in1[16] * t17 * t37 * 2.0;
  b_in2[8] = rtNaN;
  b_in2[9] = (((((t29 + t30) + t31) + t32) + t33) + in1[16] * t17 * t23 * 2.0) -
    in1[16] * t16 * t37 * 2.0;
  b_in2[10] = rtNaN;
  b_in2[11] = ((((((((in1[4] + t39) + t40) + t41) + t42) + t43) - in1[16] * t34)
                - in1[16] * t35) + in1[16] * t36) - in1[16] * (((t34 + t35) +
    t36) - 1.0);
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 2; i1++) {
      r_jtip[i1 + (i0 << 1)] = b_in2[i1 + (i0 << 1)];
    }
  }
}

/* End of code generation (rjtipF.c) */
