tmtdyn()...
	.study_parameters_are()...
		.variables(symbolic_vars_vec, var_values_vec)...
		.user_parameters(value_vac)...
		.derive_eom(bool)...
			.use_cpu_cores(core_no)...
			.use_single_cpu_core()...
			.collect_terms(collection_type)... % collection_type 1: single struct., 2: seperte struct.s, 3: seperate func.s, 4: C func.s
			.simplify_derivations()...
			.optimize_code()...
			.assume_sparse_matrix()...
			.use_mex()...
		.perform_these_analysis()...
			.static_simulation(method, times_vec)... % method in {'generate_m_file', 'edited_m_file', 'generate_mex_file', 'old_mex_file', 'generate_mex_file_from_edited_m_file'}
			.dynamic_simulation(method, solver, start_time, end_time)... % method in {'generate_m_file', 'edited_m_file', 'generate_mex_file', 'old_mex_file', 'generate_mex_file_from_edited_m_file'}
			...													  		 % solver in {'matlab', 'sundials_ode', 'sundials_dae', 'radau', 'radau_mex'}
			.modal_analysis(method, time_vec)... % method in {'generate_m_file', 'edited_m_file', 'generate_mex_file', 'old_mex_file', 'generate_mex_file_from_edited_m_file'}
			.report_progress_every_sec(time)...
			.set_spatial_integration_step(steps_int)...
			.set_results_sample_rate(rate_int)...
		.post_process_results()...
			.animate_results(anim_frame)... % anim_frame in {null, 'show_frame'}
			.set_plotting_points_per_body(point_no)...
			.record_video()...
			.run_code_provided_by_user()...
			.perform_it_every_sec(report_time)...
			.perform_instances(report_no)...		
	.physical_world()...
		.has_gravity(gravity_vec)...
	.robot(name)...
		.has_body(name)...
			.with_mass(mass)...
			.with_inertia(inertia_matrix)...
			.with_tip_at(tip_vec)...
			.with_center_of_mass_at(com_vec)...
			.connected_with_joint()... % >> joint()
		.has_joint(name)...
			.which_is_reduced_order_continous_body()...
				.with_default_order(order_int)...
				.with_length(length)...
				.with_reference_frame_type(condition)... % condition in {'relative', 'absolute'}
				.has_free_base()...
				.with_these_default_axial_locations_to_define_it(val_vec)...
			.starts_from_body(body_no)...
			.ends_at_body(body_no)...
			.starts_with_transformation_from_body(body_no)... % >> aka transformation()
				.with_translation_vector(trans_vec)...
				.with_translation_along_x_axis(val_or_inf)...
				.with_translation_along_y_axis(val_or_inf)...
				.with_translation_along_z_axis(val_or_inf)...
				.with_angle_axis_rotation(angle_axis_vec)...
				.with_rotation_about_x_axis(val_or_inf)...
				.with_rotation_about_y_axis(val_or_inf)...
				.with_rotation_about_z_axis(val_or_inf)...
				.with_strain_rotation(strain_vec)...
				.with_unit_quaternion_rotation(unit_quat_vec)...
				.with_non_unit_quaternion_rotation(non_unit_quat_vec)...
				.properties_of_dof()...
					.with_initial_value(init, init_type)... % init_type in {'state', 'cartesian_configuration'}
					.initial_value_axial_locations_are(init_s_vec)...
					.use_initial_value_from_kinematic_constraint()...
					.is_equal_to(vec, n_r)...
					.is_similar_to_dof(i_j, i_h, i_d)...
					.its_coefficient_with_order(n_r)
						.is_simlar_to_coefficient_of_other_dof_with_order(i_j, i_h, i_r, i_d)...
						.is_simlar_to_value_of_other_dof_at_axial_location(i_j, i_h, l, i_d)...
						.is_set_to_fixed_value(value)...
						.has_direct_input(input_type, input_val)... % input_type in {'force', 'position}
					.has_value_at_base(value)...
					.has_base_director(director_double)...
					.has_parallel_spring()... % >> spring
					.has_parallel_damper()... % >> damper
					.parallel_elements_active_direction_is(dir_bool_vec)...
					.has_direct_input(input_type, input_val)... % input_type in {'force', 'position}
					.has_reduced_order_model_with_order(order_int)...
					.is_not_continuum()...
			.ends_with_transformation_at_body(body_no)... % >> aka transformation()
			.with_active_directions(dir_bool)...
			.with_fixed_directions(dir_vec)...
			.follows_this_desired_trajectory(input_vec)...			
			.constraints_are_wrt_body_frame(body_no)...
			.is_a_beam_with_x_axis_in_local_frame(x_axis_vec)...
			.is_a_beam_with_stiffness()... % aka spring
				.with_elastic_coefficient(coeff)...
				.with_compression_ratio(ratio)...
				.with_relaxed_configuration(init_vals, init_type)... % init_type in {'state', 'cartesian_configuration'}
				.the_relaxed_configuration_axial_locations_are(vec)...
				.with_relaxed_state_similar_to_initial_condition()...
				.with_boundary_condition(equal2_vec}
				.with_boundary_condition_for_coefficient(n_r, value)...
				.with_boundary_condition_at_base(value)...				
			.is_a_beam_with_damping()... % >> aka damper
				.with_viscosity(val)...
				.with_flow_consistency_index(val)...
				.with_flow_behavior_index(val)...
			.is_a_beam_with_internal_actuation(input_vec)...
		.has_constraint(name)... % >> joint()
		.has_jacobian_inverse_controller(name)... % >> joint()
		.has_body_mesh(name)...
			.import_from_file(file_name, tolerance_val)...
			.import_with_tolerance(tolerance_val)...
			.with_global_transformation()... % >> transformation()
			.has_body_at_nodes(name)... >> body()
			.has_joints(name)... >> joint()...
			.has_dof_for_nodes(name)... >> joint()
			.has_edge(name)... >> joint
		.has_external_load(name)...
			.exerted_on_body(body_no)...
			.exerted_wrt_body(body_no)...
			.exerted_with_transformation_on_body(body_no)... % >> transformation
			.with_force_vector(force_vec)...
			.with_moment_vector(monet_vec)...
	.run_the_study()
	
	