/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_inF.c
 *
 * Code generation for function 'fj_inF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "fj_inF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo y_emlrtRSI = { 19,  /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo ab_emlrtRSI = { 21, /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo bb_emlrtRSI = { 22, /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo cb_emlrtRSI = { 23, /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo db_emlrtRSI = { 26, /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo eb_emlrtRSI = { 27, /* lineNo */
  "fj_inF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_inF.m"/* pathName */
};

static emlrtRSInfo fb_emlrtRSI = { 12, /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void fj_inF(const emlrtStack *sp, const real_T in1[34], real_T fj_in[6])
{
  real_T t10;
  real_T t3;
  real_T t8;
  real_T t5;
  real_T fj_in_tmp;
  real_T b_fj_in_tmp;
  real_T c_fj_in_tmp;
  real_T d_fj_in_tmp;
  real_T e_fj_in_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* FJ_INF */
  /*     FJ_IN = FJ_INF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 22:48:52 */
  t10 = muDoubleScalarCos(in1[20]);
  st.site = &y_emlrtRSI;
  t3 = in1[18] * in1[18];
  t8 = muDoubleScalarSin(in1[20]);
  st.site = &ab_emlrtRSI;
  t5 = 1.0 / (t8 * t8);
  st.site = &bb_emlrtRSI;
  st.site = &cb_emlrtRSI;
  t8 = in1[33] * in1[33] * (t10 * t10);
  st.site = &db_emlrtRSI;
  if (in1[33] < 0.0) {
    b_st.site = &fb_emlrtRSI;
    error(&b_st);
  }

  t10 = 1.0 / muDoubleScalarSqrt(in1[33]);
  st.site = &eb_emlrtRSI;
  fj_in[0] = 0.0;
  fj_in[1] = 0.0;
  fj_in[2] = -t3 * t5 * (t8 - 1.0) * 3.1415926535897931 * (((((in1[21] + in1[22])
    + in1[23]) + in1[24]) + in1[25]) + in1[26]);
  fj_in_tmp = in1[23] * in1[19] * t3 * t5 * (t8 - 1.0) * t10 *
    3.1415926535897931;
  b_fj_in_tmp = in1[24] * in1[19] * t3 * t5 * (t8 - 1.0) * t10 *
    3.1415926535897931;
  c_fj_in_tmp = in1[25] * in1[19] * t3 * t5 * (t8 - 1.0) * t10 *
    3.1415926535897931;
  d_fj_in_tmp = in1[26] * in1[19] * t3 * t5 * (t8 - 1.0) * t10 *
    3.1415926535897931;
  e_fj_in_tmp = in1[21] * in1[19] * t3 * t5 * (t8 - 1.0) * t10;
  t8 = in1[22] * in1[19] * t3 * t5 * (t8 - 1.0) * t10;
  fj_in[3] = ((((e_fj_in_tmp * 3.1415926535897931 * -0.93771626297577859 - t8 *
                 3.1415926535897931 * 0.93771626297577859) + fj_in_tmp *
                0.167999098695029) + b_fj_in_tmp * 0.76971716428074954) +
              c_fj_in_tmp * 0.76971716428074932) + d_fj_in_tmp *
    0.16799909869502891;
  fj_in[4] = ((((fj_in_tmp * 0.9857871488499218 + b_fj_in_tmp *
                 0.63838506170774523) - c_fj_in_tmp * 0.63838506170774545) -
               d_fj_in_tmp * 0.9857871488499218) - e_fj_in_tmp *
              8.3666002653407556 * 3.1415926535897931 * 0.041522491349480967) +
    t8 * 8.3666002653407556 * 3.1415926535897931 * 0.041522491349480967;
  fj_in[5] = 0.0;
}

/* End of code generation (fj_inF.c) */
