/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF16.c
 *
 * Code generation for function 'sprdmpF16'
 *
 */

/* Include files */
#include "sprdmpF16.h"
#include "EOM_eq_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo qb_emlrtRSI = { 76, /* lineNo */
  "sprdmpF16",                         /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\sprdmpF16.m"/* pathName */
};

static emlrtRSInfo dc_emlrtRSI = { 254,/* lineNo */
  "sprdmpF16",                         /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\sprdmpF16.m"/* pathName */
};

/* Function Definitions */
void sprdmpF16(const emlrtStack *sp, const real_T in1[34], const real_T in2[30],
               real_T s, real_T out1[90], real_T out2[6], real_T out3[6], real_T
               out4[6], real_T *out6)
{
  emlrtStack st;
  real_T t105;
  real_T t106_tmp;
  real_T t107;
  real_T t108_tmp;
  real_T t109;
  real_T t11;
  real_T t110_tmp;
  real_T t117;
  real_T t118;
  real_T t119;
  real_T t12;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t127;
  real_T t128;
  real_T t129;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t147;
  real_T t15;
  real_T t151;
  real_T t152;
  real_T t158;
  real_T t159;
  real_T t16;
  real_T t160;
  real_T t161;
  real_T t162;
  real_T t163;
  real_T t164;
  real_T t165;
  real_T t167;
  real_T t168;
  real_T t169;
  real_T t170;
  real_T t171;
  real_T t172;
  real_T t173;
  real_T t174;
  real_T t175;
  real_T t176;
  real_T t177;
  real_T t178;
  real_T t179;
  real_T t180;
  real_T t181;
  real_T t182;
  real_T t183;
  real_T t184;
  real_T t185;
  real_T t187;
  real_T t189;
  real_T t190;
  real_T t192;
  real_T t195;
  real_T t196;
  real_T t198;
  real_T t200;
  real_T t204;
  real_T t205;
  real_T t206;
  real_T t207;
  real_T t208;
  real_T t209;
  real_T t210;
  real_T t211;
  real_T t215;
  real_T t216;
  real_T t217;
  real_T t218;
  real_T t220;
  real_T t223;
  real_T t224;
  real_T t225;
  real_T t228;
  real_T t229;
  real_T t245;
  real_T t246;
  real_T t27;
  real_T t29;
  real_T t296;
  real_T t297;
  real_T t300;
  real_T t301;
  real_T t302;
  real_T t303;
  real_T t306;
  real_T t307;
  real_T t31;
  real_T t312;
  real_T t313;
  real_T t316;
  real_T t317;
  real_T t32;
  real_T t320;
  real_T t321;
  real_T t322;
  real_T t323;
  real_T t324;
  real_T t325;
  real_T t326;
  real_T t327;
  real_T t328;
  real_T t329;
  real_T t33;
  real_T t330;
  real_T t333;
  real_T t334;
  real_T t335;
  real_T t336;
  real_T t337;
  real_T t34;
  real_T t342;
  real_T t346;
  real_T t347;
  real_T t35;
  real_T t36;
  real_T t4;
  real_T t413;
  real_T t414;
  real_T t415;
  real_T t416;
  real_T t417;
  real_T t418;
  real_T t419;
  real_T t420;
  real_T t421;
  real_T t422;
  real_T t423;
  real_T t424;
  real_T t428;
  real_T t429;
  real_T t430;
  real_T t434;
  real_T t435;
  real_T t436;
  real_T t437;
  real_T t438;
  real_T t439;
  real_T t447;
  real_T t450;
  real_T t452;
  real_T t473;
  real_T t479;
  real_T t479_tmp;
  real_T t480;
  real_T t480_tmp;
  real_T t488;
  real_T t489;
  real_T t5;
  real_T t500;
  real_T t501;
  real_T t502;
  real_T t503;
  real_T t51;
  real_T t518;
  real_T t518_tmp;
  real_T t519;
  real_T t519_tmp;
  real_T t520;
  real_T t520_tmp;
  real_T t521;
  real_T t522;
  real_T t523;
  real_T t524;
  real_T t525;
  real_T t526;
  real_T t527;
  real_T t528;
  real_T t529;
  real_T t53;
  real_T t530;
  real_T t56;
  real_T t57;
  real_T t59;
  real_T t6;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t64;
  real_T t65;
  real_T t66;
  real_T t67;
  real_T t68;
  real_T t69;
  real_T t7;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T t74_tmp;
  real_T t75;
  real_T t75_tmp;
  real_T t76;
  real_T t76_tmp;
  real_T t79;
  real_T t80;
  real_T t81;
  real_T t82;
  real_T t83;
  real_T t87;
  real_T t87_tmp;
  real_T t88;
  real_T t88_tmp;
  real_T t89;
  real_T t89_tmp;
  real_T t9;
  real_T t90;
  real_T t90_tmp;
  real_T t91;
  real_T t92;
  real_T t92_tmp;
  real_T t93;
  real_T t93_tmp;
  real_T t94;
  real_T t95;
  real_T t95_tmp;
  real_T t96;
  real_T t96_tmp;
  real_T t97;
  real_T t98;
  real_T t98_tmp;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF16 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7] = SPRDMPF16(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     27-Feb-2021 15:53:37 */
  t189 = muDoubleScalarCos(in1[20]);
  t34 = muDoubleScalarSin(in1[20]);
  t4 = in2[6] * s;
  t5 = in2[9] * s;
  t6 = in2[12] * s;
  t7 = in1[33] * in1[33];
  t9 = in1[18] * in1[18];
  t11 = in1[2] * in1[2];
  t12 = in1[3] * in1[3];
  t15 = s * s;
  t16 = muDoubleScalarPower(s, 3.0);
  t27 = 1.0 / in1[33];
  st.site = &qb_emlrtRSI;
  if (in1[33] < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t51 = 1.0 / muDoubleScalarSqrt(in1[33]);
  t29 = 1.0 / (t34 * t34);
  t31 = in2[7] * t15;
  t32 = in2[8] * t16;
  t33 = in2[10] * t15;
  t34 = in2[11] * t16;
  t35 = in2[13] * t15;
  t36 = in2[14] * t16;
  t53 = t7 * (t189 * t189);
  t56 = in2[0] * s * 2.0 + in2[1] * t15 * 3.0;
  t57 = in2[2] * s * 2.0 + in2[3] * t15 * 3.0;
  t59 = (in2[4] * s * 2.0 + in2[5] * t15 * 3.0) + 1.0;
  t60 = (in2[6] + in2[7] * s * 2.0) + in2[8] * t15 * 3.0;
  t61 = (in2[9] + in2[10] * s * 2.0) + in2[11] * t15 * 3.0;
  t62 = (in2[12] + in2[13] * s * 2.0) + in2[14] * t15 * 3.0;
  t67 = (t4 + t31) + t32;
  t68 = (t5 + t33) + t34;
  t69 = (t6 + t35) + t36;
  t64 = s * t56;
  t65 = s * t57;
  t66 = s * t59;
  t70 = t15 * t56;
  t71 = t16 * t56;
  t72 = t15 * t57;
  t73 = t16 * t57;
  t74_tmp = s * t60;
  t74 = t74_tmp * 2.0;
  t75_tmp = s * t61;
  t75 = t75_tmp * 2.0;
  t76_tmp = s * t62;
  t76 = t76_tmp * 2.0;
  t79 = t67 * t67;
  t80 = t68 * t68;
  t81 = t69 * t69;
  t82 = t15 * t59;
  t83 = t16 * t59;
  t87_tmp = s * t67;
  t87 = t87_tmp * 4.0;
  t88_tmp = s * t68;
  t88 = t88_tmp * 4.0;
  t89_tmp = s * t69;
  t89 = t89_tmp * 4.0;
  t90_tmp = t15 * t60;
  t90 = t90_tmp * 2.0;
  t91 = (t4 * 2.0 + t31 * 2.0) + t32 * 2.0;
  t92_tmp = t16 * t60;
  t92 = t92_tmp * 2.0;
  t93_tmp = t15 * t61;
  t93 = t93_tmp * 2.0;
  t94 = (t5 * 2.0 + t33 * 2.0) + t34 * 2.0;
  t95_tmp = t16 * t61;
  t95 = t95_tmp * 2.0;
  t96_tmp = t15 * t62;
  t96 = t96_tmp * 2.0;
  t97 = (t6 * 2.0 + t35 * 2.0) + t36 * 2.0;
  t98_tmp = t16 * t62;
  t98 = t98_tmp * 2.0;
  t106_tmp = t15 * t67;
  t31 = t106_tmp * 6.0;
  t108_tmp = t15 * t68;
  t32 = t108_tmp * 6.0;
  t110_tmp = t15 * t69;
  t4 = t110_tmp * 6.0;
  t105 = s * t79 * 2.0;
  t107 = s * t80 * 2.0;
  t109 = s * t81 * 2.0;
  t117 = s * t91 * 2.0;
  t118 = s * t94 * 2.0;
  t119 = s * t97 * 2.0;
  t121 = t15 * t79 * 3.0;
  t122 = t15 * t80 * 3.0;
  t123 = t15 * t81 * 3.0;
  t127 = t15 * t91 * 3.0;
  t128 = t15 * t94 * 3.0;
  t129 = t15 * t97 * 3.0;
  t144 = t65 * t67;
  t145 = t64 * t68;
  t146 = t64 * t69;
  t147 = t65 * t69;
  t151 = t66 * t67;
  t152 = t66 * t68;
  t158 = t67 * t72;
  t159 = t67 * t73;
  t160 = t68 * t70;
  t161 = t68 * t71;
  t162 = t69 * t70;
  t163 = t69 * t71;
  t164 = t69 * t72;
  t165 = t69 * t73;
  t167 = t67 * t82;
  t168 = t67 * t83;
  t169 = t68 * t82;
  t170 = t68 * t83;
  t171 = t68 * t87;
  t172 = t69 * t87;
  t173 = t69 * t88;
  t174 = t74 + t91;
  t175 = t75 + t94;
  t176 = t76 + t97;
  t177 = t68 * t31;
  t178 = t69 * t31;
  t179 = t69 * t32;
  t180 = t87 + t90;
  t181 = t88 + t93;
  t182 = t89 + t96;
  t183 = t92 + t31;
  t184 = t95 + t32;
  t185 = t98 + t4;
  t189 = ((t79 + t80) + t81) - 1.0;
  t204 = (t56 * t67 + t57 * t68) + t59 * t69;
  t217 = (t60 * t67 * 2.0 + t61 * t68 * 2.0) + t62 * t69 * 2.0;
  t190 = s * t189 * 2.0;
  t192 = t15 * t189 * 3.0;
  t211 = s * t204;
  t215 = t15 * t204;
  t216 = t16 * t204;
  t187 = 1.0 / t7 * (t11 * t11 + -(t12 * t12)) + t9 * t9 * (t29 * t29) * ((t53 -
    1.0) * (t53 - 1.0)) * 6.0;
  t195 = ((-t79 + -t80) + -t81) + 1.0;
  st.site = &dc_emlrtRSI;
  if (t195 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t195 = muDoubleScalarSqrt(t195);
  t196 = 1.0 / t195;
  t198 = t195 * 2.0;
  t7 = s * t195 * 4.0;
  t200 = t15 * t195 * 6.0;
  t205 = t87 * t195;
  t206 = t88 * t195;
  t207 = t89 * t195;
  t208 = t31 * t195;
  t209 = t32 * t195;
  t210 = t4 * t195;
  t81 = muDoubleScalarPower(t196, 3.0);
  t218 = t144 * t196;
  t32 = t145 * t196;
  t220 = t146 * t196;
  t31 = t147 * t196;
  t4 = t151 * t196;
  t223 = t152 * t196;
  t224 = t158 * t196;
  t225 = t159 * t196;
  t36 = t160 * t196;
  t6 = t161 * t196;
  t228 = t162 * t196;
  t229 = t163 * t196;
  t33 = t164 * t196;
  t34 = t165 * t196;
  t5 = t167 * t196;
  t35 = t168 * t196;
  t245 = t169 * t196;
  t246 = t170 * t196;
  t328 = t173 + t205;
  t329 = t172 + t206;
  t330 = t171 + t207;
  t335 = t177 + t210;
  t336 = t178 + t209;
  t337 = t179 + t208;
  t342 = t94 * t174 * t196 / 2.0;
  t346 = t91 * t176 * t196 / 2.0;
  t347 = t97 * t175 * t196 / 2.0;
  t413 = (t56 * t68 + -(t57 * t67)) + t59 * t195;
  t414 = (t59 * t67 + -(t56 * t69)) + t57 * t195;
  t415 = (t57 * t69 + -(t59 * t68)) + t56 * t195;
  t189 = s * t196 * t217;
  t79 = t15 * t196 * t217;
  t80 = t16 * t196 * t217;
  t296 = t64 + t31;
  t297 = t67 * t32;
  t300 = t68 * t31;
  t301 = t65 + t4;
  t302 = t66 + t32;
  t303 = t69 * t4;
  t306 = t67 * t36;
  t307 = t67 * t6;
  t312 = t68 * t33;
  t313 = t68 * t34;
  t316 = t69 * t5;
  t317 = t69 * t35;
  t320 = t70 + t33;
  t321 = t71 + t34;
  t322 = t72 + t5;
  t323 = t73 + t35;
  t324 = t82 + t36;
  t325 = t83 + t6;
  t416 = s * t413;
  t417 = s * t414;
  t418 = s * t415;
  t419 = t15 * t413;
  t420 = t16 * t413;
  t421 = t15 * t414;
  t422 = t16 * t414;
  t423 = t15 * t415;
  t424 = t16 * t415;
  t447 = t87_tmp * t94 * t81 * t217 / 2.0;
  t450 = t89_tmp * t91 * t81 * t217 / 2.0;
  t452 = t88_tmp * t97 * t81 * t217 / 2.0;
  t6 = t65 + -t220;
  t35 = t66 + -t218;
  t36 = t64 + -t223;
  t326 = t72 + -t228;
  t327 = t73 + -t229;
  t34 = t82 + -t224;
  t5 = t83 + -t225;
  t333 = t70 + -t245;
  t334 = t71 + -t246;
  t428 = t195 * t296;
  t429 = t195 * t301;
  t430 = t195 * t302;
  t434 = t195 * t320;
  t435 = t195 * t321;
  t436 = t195 * t322;
  t437 = t195 * t323;
  t438 = t195 * t324;
  t439 = t195 * t325;
  t33 = t67 * t196;
  t473 = t33 * t416;
  t479_tmp = t69 * t196;
  t479 = t479_tmp * t417;
  t480_tmp = t68 * t196;
  t480 = t480_tmp * t418;
  t488 = t33 * t419;
  t489 = t33 * t420;
  t500 = t479_tmp * t421;
  t501 = t480_tmp * t423;
  t502 = t479_tmp * t422;
  t503 = t480_tmp * t424;
  t518_tmp = -t75 + t94;
  t518 = ((t518_tmp + t76_tmp * t67 * t196 * -2.0) + t97 * t174 * t196 / 2.0) +
    t87_tmp * t97 * t81 * t217 / 2.0;
  t519_tmp = -t76 + t97;
  t519 = ((t519_tmp + t74_tmp * t68 * t196 * -2.0) + t91 * t175 * t196 / 2.0) +
    t88_tmp * t91 * t81 * t217 / 2.0;
  t520_tmp = -t74 + t91;
  t520 = ((t520_tmp + t75_tmp * t69 * t196 * -2.0) + t94 * t176 * t196 / 2.0) +
    t89_tmp * t94 * t81 * t217 / 2.0;
  t521 = (((t96 + -t119) + t93_tmp * t67 * t196 * -2.0) + t94 * t180 * t196 /
          2.0) + t106_tmp * t94 * t81 * t217 / 2.0;
  t522 = (((-t93 + t118) + t96_tmp * t67 * t196 * -2.0) + t97 * t180 * t196 /
          2.0) + t106_tmp * t97 * t81 * t217 / 2.0;
  t523 = (((-t96 + t119) + t90_tmp * t68 * t196 * -2.0) + t91 * t181 * t196 /
          2.0) + t108_tmp * t91 * t81 * t217 / 2.0;
  t524 = (((t90 + -t117) + t96_tmp * t68 * t196 * -2.0) + t97 * t181 * t196 /
          2.0) + t108_tmp * t97 * t81 * t217 / 2.0;
  t525 = (((t93 + -t118) + t90_tmp * t69 * t196 * -2.0) + t91 * t182 * t196 /
          2.0) + t110_tmp * t91 * t81 * t217 / 2.0;
  t526 = (((-t90 + t117) + t93_tmp * t69 * t196 * -2.0) + t94 * t182 * t196 /
          2.0) + t110_tmp * t94 * t81 * t217 / 2.0;
  t32 = t16 * t67;
  t527 = (((t98 + -t129) + t95_tmp * t67 * t196 * -2.0) + t94 * t183 * t196 /
          2.0) + t32 * t94 * t81 * t217 / 2.0;
  t528 = (((-t95 + t128) + t98_tmp * t67 * t196 * -2.0) + t97 * t183 * t196 /
          2.0) + t32 * t97 * t81 * t217 / 2.0;
  t4 = t16 * t68;
  t529 = (((-t98 + t129) + t92_tmp * t68 * t196 * -2.0) + t91 * t184 * t196 /
          2.0) + t4 * t91 * t81 * t217 / 2.0;
  t530 = (((t92 + -t127) + t98_tmp * t68 * t196 * -2.0) + t97 * t184 * t196 /
          2.0) + t4 * t97 * t81 * t217 / 2.0;
  t31 = t16 * t69;
  t95 = (((t95 + -t128) + t92_tmp * t69 * t196 * -2.0) + t91 * t185 * t196 / 2.0)
    + t31 * t91 * t81 * t217 / 2.0;
  t90 = (((-t92 + t127) + t95_tmp * t69 * t196 * -2.0) + t94 * t185 * t196 / 2.0)
    + t31 * t94 * t81 * t217 / 2.0;
  t128 = (((t198 + t74_tmp * t67 * t196 * -2.0) + t91 * t174 * t196 / 2.0) +
          t189) + t87_tmp * t91 * t81 * t217 / 2.0;
  t129 = (((t198 + t75_tmp * t68 * t196 * -2.0) + t94 * t175 * t196 / 2.0) +
          t189) + t88_tmp * t94 * t81 * t217 / 2.0;
  t98 = (((t198 + t76_tmp * t69 * t196 * -2.0) + t97 * t176 * t196 / 2.0) + t189)
    + t89_tmp * t97 * t81 * t217 / 2.0;
  t93 = (((t7 + t90_tmp * t67 * t196 * -2.0) + t91 * t180 * t196 / 2.0) + t79) +
    t106_tmp * t91 * t81 * t217 / 2.0;
  t117 = (((t7 + t93_tmp * t68 * t196 * -2.0) + t94 * t181 * t196 / 2.0) + t79)
    + t108_tmp * t94 * t81 * t217 / 2.0;
  t96 = (((t7 + t96_tmp * t69 * t196 * -2.0) + t97 * t182 * t196 / 2.0) + t79) +
    t110_tmp * t97 * t81 * t217 / 2.0;
  t118 = (((t200 + t92_tmp * t67 * t196 * -2.0) + t91 * t183 * t196 / 2.0) + t80)
    + t32 * t91 * t81 * t217 / 2.0;
  t119 = (((t200 + t95_tmp * t68 * t196 * -2.0) + t94 * t184 * t196 / 2.0) + t80)
    + t4 * t94 * t81 * t217 / 2.0;
  t57 = (((t200 + t98_tmp * t69 * t196 * -2.0) + t97 * t185 * t196 / 2.0) + t80)
    + t31 * t97 * t81 * t217 / 2.0;
  t59 = t69 * t6;
  t15 = t67 * t35;
  t65 = t68 * t36;
  t66 = t69 * t326;
  t64 = t69 * t327;
  t72 = t67 * t34;
  t73 = t67 * t5;
  t82 = t68 * t333;
  t83 = t68 * t334;
  t70 = ((t211 + t67 * t296) + t68 * t6) + -(t479_tmp * t416);
  t71 = ((t211 + t68 * t301) + t69 * t35) + -(t33 * t418);
  t87 = ((t211 + t69 * t302) + t67 * t36) + -(t480_tmp * t417);
  t88 = ((t215 + t67 * t320) + t68 * t326) + -(t479_tmp * t419);
  t89 = ((t216 + t67 * t321) + t68 * t327) + -(t479_tmp * t420);
  t56 = ((t215 + t68 * t322) + t69 * t34) + -(t33 * t423);
  t81 = ((t215 + t69 * t324) + t67 * t333) + -(t480_tmp * t421);
  t7 = ((t216 + t68 * t323) + t69 * t5) + -(t33 * t424);
  t80 = ((t216 + t69 * t325) + t67 * t334) + -(t480_tmp * t422);
  t79 = ((((t145 + t67 * t220) + -(t67 * t301)) + t416) + t195 * t35) + -(t33 *
    t417);
  t189 = ((((t147 + t68 * t218) + -(t68 * t302)) + t418) + t195 * t36) +
    -(t480_tmp * t416);
  t6 = ((((t151 + t69 * t223) + -(t69 * t296)) + t417) + t195 * t6) + -(t479_tmp
    * t418);
  t36 = ((((t160 + t67 * t228) + -(t67 * t322)) + t419) + t195 * t34) + -(t33 *
    t421);
  t35 = ((((t161 + t67 * t229) + -(t67 * t323)) + t420) + t195 * t5) + -(t33 *
    t422);
  t5 = ((((t164 + t68 * t224) + -(t68 * t324)) + t423) + t195 * t333) +
    -(t480_tmp * t419);
  t34 = ((((t165 + t68 * t225) + -(t68 * t325)) + t424) + t195 * t334) +
    -(t480_tmp * t420);
  t33 = ((((t167 + t69 * t245) + -(t69 * t320)) + t421) + t195 * t326) +
    -(t479_tmp * t423);
  t4 = ((((t168 + t69 * t246) + -(t69 * t321)) + t422) + t195 * t327) +
    -(t479_tmp * t424);
  out1[0] = ((t105 + -t107) + -t109) + -t190;
  out1[1] = ((t121 + -t122) + -t123) + -t192;
  out1[2] = t330;
  out1[3] = t335;
  out1[4] = t172 - t88_tmp * t195 * 4.0;
  out1[5] = t178 + t108_tmp * t195 * -6.0;
  out1[6] = t71;
  out1[7] = t56;
  out1[8] = t7;
  out1[9] = ((((t144 - t300) - t65) - t416) - t430) - t480;
  out1[10] = ((((t158 - t312) - t82) - t419) - t438) - t501;
  out1[11] = ((((t159 - t313) - t83) - t420) - t439) - t503;
  out1[12] = t6;
  out1[13] = t33;
  out1[14] = t4;
  out1[15] = t171 - t89_tmp * t195 * 4.0;
  out1[16] = t177 + t110_tmp * t195 * -6.0;
  out1[17] = ((t107 + -t105) + -t109) + -t190;
  out1[18] = ((t122 + -t121) + -t123) + -t192;
  out1[19] = t328;
  out1[20] = t337;
  out1[21] = t79;
  out1[22] = t36;
  out1[23] = t35;
  out1[24] = t87;
  out1[25] = t81;
  out1[26] = t80;
  out1[27] = ((((t152 - t303) - t59) - t418) - t428) - t479;
  out1[28] = ((((t169 - t316) - t66) - t423) - t434) - t500;
  out1[29] = ((((t170 - t317) - t64) - t424) - t435) - t502;
  out1[30] = t329;
  out1[31] = t336;
  out1[32] = t173 - t87_tmp * t195 * 4.0;
  out1[33] = t179 + t106_tmp * t195 * -6.0;
  out1[34] = ((t109 + -t105) + -t107) + -t190;
  out1[35] = ((t123 + -t121) + -t122) + -t192;
  out1[36] = ((((t146 - t297) - t15) - t417) - t429) - t473;
  out1[37] = ((((t162 - t306) - t72) - t421) - t436) - t488;
  out1[38] = ((((t163 - t307) - t73) - t422) - t437) - t489;
  out1[39] = t189;
  out1[40] = t5;
  out1[41] = t34;
  out1[42] = t70;
  out1[43] = t88;
  out1[44] = t89;
  out1[45] = 0.0;
  out1[46] = 0.0;
  out1[47] = 0.0;
  out1[48] = 0.0;
  out1[49] = 0.0;
  out1[50] = 0.0;
  out1[51] = t128;
  out1[52] = t93;
  out1[53] = t118;
  out1[54] = t519;
  out1[55] = t523;
  out1[56] = t529;
  out1[57] = (((t75 - t94) + t346) + t450) - t74_tmp * t69 * t196 * 2.0;
  out1[58] = t525;
  out1[59] = t95;
  out1[60] = 0.0;
  out1[61] = 0.0;
  out1[62] = 0.0;
  out1[63] = 0.0;
  out1[64] = 0.0;
  out1[65] = 0.0;
  out1[66] = (((t76 - t97) + t342) + t447) - t75_tmp * t67 * t196 * 2.0;
  out1[67] = t521;
  out1[68] = t527;
  out1[69] = t129;
  out1[70] = t117;
  out1[71] = t119;
  out1[72] = t520;
  out1[73] = t526;
  out1[74] = t90;
  out1[75] = 0.0;
  out1[76] = 0.0;
  out1[77] = 0.0;
  out1[78] = 0.0;
  out1[79] = 0.0;
  out1[80] = 0.0;
  out1[81] = t518;
  out1[82] = t522;
  out1[83] = t528;
  out1[84] = (((t74 - t91) + t347) + t452) - t76_tmp * t68 * t196 * 2.0;
  out1[85] = t524;
  out1[86] = t530;
  out1[87] = t98;
  out1[88] = t96;
  out1[89] = t57;
  t32 = in1[1] * t27;
  t31 = t32 * (t27 * (t11 + -t12) + -(t9 * t29 * (t53 - 1.0) * 6.0)) *
    3.1415926535897931;
  out2[0] = t31 * (((t67 * t204 - t68 * t413) + t69 * t414) + t195 * t415) / 3.0;
  out2[1] = t31 * (((t68 * t204 + t67 * t413) - t69 * t415) + t195 * t414) / 3.0;
  out2[2] = t31 * ((((t69 * t204 - t67 * t414) + t68 * t415) + t195 * t413) -
                   1.0);
  t31 = t32 * (t187 * 3.1415926535897931 / 4.0 - in1[19] * in1[19] * t9 * t27 *
               t29 * (t53 - 1.0) * 3.1415926535897931 * 3.0);
  out2[3] = t31 * (((-t62 * t94 + t61 * t97) + t60 * t198) + t91 * t196 * t217 /
                   2.0);
  out2[4] = t31 * (((t62 * t91 - t60 * t97) + t61 * t198) + t94 * t196 * t217 /
                   2.0);
  out2[5] = t32 * t187 * 3.1415926535897931 * (((-t61 * t91 + t60 * t94) + t62 *
    t198) + t97 * t196 * t217 / 2.0) / 6.0;
  out3[0] = -in1[5] * ((((((((((((((-in2[15] * (((t107 + t109) + -t105) + t190)
    - in2[16] * (((t122 + t123) + -t121) + t192)) + t330 * in2[17]) + t335 *
    in2[18]) + t71 * in2[21]) + t56 * in2[22]) + t7 * in2[23]) + t6 * in2[27]) +
    t33 * in2[28]) + t4 * in2[29]) - in2[24] * (((((-t144 + t300) + t65) + t416)
    + t430) + t480)) - in2[25] * (((((-t158 + t312) + t82) + t419) + t438) +
    t501)) - in2[26] * (((((-t159 + t313) + t83) + t420) + t439) + t503)) - in2
                        [19] * (t206 - t87_tmp * t69 * 4.0)) - in2[20] * (t209 -
    t106_tmp * t69 * 6.0));
  out3[1] = -in1[6] * ((((((((((((((-in2[17] * (((t105 + t109) + -t107) + t190)
    - in2[18] * (((t121 + t123) + -t122) + t192)) + t328 * in2[19]) + t337 *
    in2[20]) + t87 * in2[24]) + t81 * in2[25]) + t80 * in2[26]) + t79 * in2[21])
    + t36 * in2[22]) + t35 * in2[23]) - in2[27] * (((((-t152 + t303) + t59) +
    t418) + t428) + t479)) - in2[28] * (((((-t169 + t316) + t66) + t423) + t434)
    + t500)) - in2[29] * (((((-t170 + t317) + t64) + t424) + t435) + t502)) -
                        in2[15] * (t207 - t87_tmp * t68 * 4.0)) - in2[16] *
                       (t210 - t106_tmp * t68 * 6.0));
  out3[2] = -in1[7] * ((((((((((((((-in2[19] * (((t105 + t107) + -t109) + t190)
    - in2[20] * (((t121 + t122) + -t123) + t192)) + t329 * in2[15]) + t336 *
    in2[16]) + t70 * in2[27]) + t88 * in2[28]) + t89 * in2[29]) + t189 * in2[24])
    + t5 * in2[25]) + t34 * in2[26]) - in2[21] * (((((-t146 + t297) + t15) +
    t417) + t429) + t473)) - in2[22] * (((((-t162 + t306) + t72) + t421) + t436)
    + t488)) - in2[23] * (((((-t163 + t307) + t73) + t422) + t437) + t489)) -
                        in2[17] * (t205 - t88_tmp * t69 * 4.0)) - in2[18] *
                       (t208 - t108_tmp * t69 * 6.0));
  out3[3] = -in1[8] * ((((((((-in2[27] * (((t518_tmp + t69 * t74 * t196) - t346)
    - t450) + t519 * in2[24]) + t523 * in2[25]) + t525 * in2[28]) + t529 * in2
    [26]) + t95 * in2[29]) + t128 * in2[21]) + t93 * in2[22]) + t118 * in2[23]);
  out3[4] = -in1[9] * ((((((((-in2[21] * (((t519_tmp + t67 * t75 * t196) - t342)
    - t447) + t521 * in2[22]) + t520 * in2[27]) + t527 * in2[23]) + t526 * in2
    [28]) + t90 * in2[29]) + t129 * in2[24]) + t117 * in2[25]) + t119 * in2[26]);
  out3[5] = -in1[10] * ((((((((-in2[24] * (((t520_tmp + t68 * t76 * t196) - t347)
    - t452) + t518 * in2[21]) + t522 * in2[22]) + t524 * in2[25]) + t528 * in2
    [23]) + t530 * in2[26]) + t98 * in2[27]) + t96 * in2[28]) + t57 * in2[29]);
  out4[0] = 0.0;
  out4[1] = 0.0;
  out4[2] = -t9 * t29 * (t53 - 1.0) * 3.1415926535897931 * (((((in1[21] + in1[22])
    + in1[23]) + in1[24]) + in1[25]) + in1[26]);
  t189 = in1[23] * in1[19] * t9 * t29 * t51 * (t53 - 1.0) * 3.1415926535897931;
  t31 = in1[24] * in1[19] * t9 * t29 * t51 * (t53 - 1.0) * 3.1415926535897931;
  t32 = in1[25] * in1[19] * t9 * t29 * t51 * (t53 - 1.0) * 3.1415926535897931;
  t4 = in1[26] * in1[19] * t9 * t29 * t51 * (t53 - 1.0) * 3.1415926535897931;
  t33 = in1[21] * in1[19] * t9 * t29 * t51;
  t34 = in1[22] * in1[19] * t9 * t29 * t51;
  out4[3] = ((((t33 * (t53 - 1.0) * 3.1415926535897931 * -0.93771626297577859 -
                t34 * (t53 - 1.0) * 3.1415926535897931 * 0.93771626297577859) +
               t189 * 0.167999098695029) + t31 * 0.76971716428074954) + t32 *
             0.76971716428074932) + t4 * 0.16799909869502891;
  out4[4] = ((((t189 * 0.9857871488499218 + t31 * 0.63838506170774523) - t32 *
               0.63838506170774545) - t4 * 0.9857871488499218) - t33 *
             8.3666002653407556 * (t53 - 1.0) * 3.1415926535897931 *
             0.041522491349480967) + t34 * 8.3666002653407556 * (t53 - 1.0) *
    3.1415926535897931 * 0.041522491349480967;
  out4[5] = 0.0;
  *out6 = 1.0;
}

/* End of code generation (sprdmpF16.c) */
