/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
            real_T s, real_T r_jtip[96])
{
  real_T t2;
  real_T t3;
  (void)sp;
  (void)in1;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:15 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t2 = muDoubleScalarSin(t2);
  r_jtip[0] = 0.0;
  r_jtip[1] = in2[0];
  r_jtip[2] = in2[6];
  r_jtip[3] = in2[12];
  r_jtip[4] = in2[18];
  r_jtip[5] = in2[24];
  r_jtip[6] = in2[30];
  r_jtip[7] = in2[36];
  r_jtip[8] = in2[42];
  r_jtip[9] = in2[48];
  r_jtip[10] = in2[54];
  r_jtip[11] = in2[60];
  r_jtip[12] = in2[66];
  r_jtip[13] = in2[72];
  r_jtip[14] = in2[78];
  r_jtip[15] = in2[84];
  r_jtip[16] = 0.0;
  r_jtip[17] = in2[1];
  r_jtip[18] = in2[7];
  r_jtip[19] = in2[13];
  r_jtip[20] = in2[19];
  r_jtip[21] = in2[25];
  r_jtip[22] = in2[31];
  r_jtip[23] = in2[37];
  r_jtip[24] = in2[43];
  r_jtip[25] = in2[49];
  r_jtip[26] = in2[55];
  r_jtip[27] = in2[61];
  r_jtip[28] = in2[67];
  r_jtip[29] = in2[73];
  r_jtip[30] = in2[79];
  r_jtip[31] = in2[85];
  r_jtip[32] = 0.0;
  r_jtip[33] = in2[2];
  r_jtip[34] = in2[8];
  r_jtip[35] = in2[14];
  r_jtip[36] = in2[20];
  r_jtip[37] = in2[26];
  r_jtip[38] = in2[32];
  r_jtip[39] = in2[38];
  r_jtip[40] = in2[44];
  r_jtip[41] = in2[50];
  r_jtip[42] = in2[56];
  r_jtip[43] = in2[62];
  r_jtip[44] = in2[68];
  r_jtip[45] = in2[74];
  r_jtip[46] = in2[80];
  r_jtip[47] = in2[86];
  r_jtip[48] = t3 * t2 * -0.54;
  r_jtip[49] = in2[0];
  r_jtip[50] = in2[6];
  r_jtip[51] = in2[12];
  r_jtip[52] = in2[18];
  r_jtip[53] = in2[24];
  r_jtip[54] = in2[30];
  r_jtip[55] = in2[36];
  r_jtip[56] = in2[42];
  r_jtip[57] = in2[48];
  r_jtip[58] = in2[54];
  r_jtip[59] = in2[60];
  r_jtip[60] = in2[66];
  r_jtip[61] = in2[72];
  r_jtip[62] = in2[78];
  r_jtip[63] = in2[84];
  r_jtip[64] = 0.0;
  r_jtip[65] = in2[1];
  r_jtip[66] = in2[7];
  r_jtip[67] = in2[13];
  r_jtip[68] = in2[19];
  r_jtip[69] = in2[25];
  r_jtip[70] = in2[31];
  r_jtip[71] = in2[37];
  r_jtip[72] = in2[43];
  r_jtip[73] = in2[49];
  r_jtip[74] = in2[55];
  r_jtip[75] = in2[61];
  r_jtip[76] = in2[67];
  r_jtip[77] = in2[73];
  r_jtip[78] = in2[79];
  r_jtip[79] = in2[85];
  r_jtip[80] = t3 * t3 * -0.27 + t2 * t2 * 0.27;
  r_jtip[81] = in2[2];
  r_jtip[82] = in2[8];
  r_jtip[83] = in2[14];
  r_jtip[84] = in2[20];
  r_jtip[85] = in2[26];
  r_jtip[86] = in2[32];
  r_jtip[87] = in2[38];
  r_jtip[88] = in2[44];
  r_jtip[89] = in2[50];
  r_jtip[90] = in2[56];
  r_jtip[91] = in2[62];
  r_jtip[92] = in2[68];
  r_jtip[93] = in2[74];
  r_jtip[94] = in2[80];
  r_jtip[95] = in2[86];
}

/* End of code generation (rjtipF.c) */
