/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF4.c
 *
 * Code generation for function 'cnstF4'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "cnstF4.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo yab_emlrtRSI = { 26,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

static emlrtRSInfo abb_emlrtRSI = { 27,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

static emlrtRSInfo bbb_emlrtRSI = { 28,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

static emlrtRSInfo cbb_emlrtRSI = { 30,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

static emlrtRSInfo dbb_emlrtRSI = { 35,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

static emlrtRSInfo ebb_emlrtRSI = { 117,/* lineNo */
  "cnstF4",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF4.m"/* pathName */
};

/* Function Definitions */
void cnstF4(const emlrtStack *sp, const real_T in2[198], real_T out1[91], real_T
            out2[91], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t10_tmp;
  real_T t107;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14_tmp;
  real_T t15_tmp;
  real_T t16_tmp;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t20_tmp;
  real_T t21;
  real_T t23;
  real_T t263;
  real_T t42_tmp;
  real_T t42;
  real_T t43_tmp;
  real_T t24;
  real_T t26;
  real_T t27_tmp;
  real_T b_t27_tmp;
  real_T t28_tmp;
  real_T t29;
  real_T t30_tmp;
  real_T t30;
  real_T t31_tmp;
  real_T t45;
  real_T t46_tmp_tmp;
  real_T t46_tmp;
  real_T t46;
  real_T t32;
  real_T t273;
  real_T t270;
  real_T t266;
  real_T t221;
  real_T t36_tmp;
  real_T t37_tmp;
  real_T t38_tmp;
  real_T t39_tmp;
  real_T t264;
  real_T t40_tmp;
  real_T t49_tmp;
  real_T t47_tmp_tmp;
  real_T t47_tmp;
  real_T t50_tmp;
  real_T t50;
  real_T t52;
  real_T t54_tmp;
  real_T t63_tmp;
  real_T t64_tmp;
  real_T t55_tmp;
  real_T t56_tmp;
  real_T t57_tmp;
  real_T t58_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t65_tmp;
  real_T t62;
  real_T t68;
  real_T t69;
  real_T t70_tmp_tmp;
  real_T t70_tmp;
  real_T t70;
  real_T t71_tmp;
  real_T b_t71_tmp;
  real_T t72;
  real_T t74;
  real_T t75_tmp;
  real_T t76_tmp;
  real_T t77;
  real_T t78;
  real_T t79_tmp;
  real_T t80;
  real_T t83_tmp;
  real_T t83;
  real_T t81_tmp;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  real_T t100;
  real_T t105;
  real_T t106;
  real_T t225;
  real_T t111;
  real_T t109;
  real_T t112;
  real_T t113;
  real_T t114;
  real_T t117;
  real_T t119;
  real_T t121;
  real_T t166;
  real_T t123;
  real_T t124;
  real_T t127_tmp;
  real_T t127;
  real_T t130;
  real_T t133;
  real_T t132;
  real_T t229;
  real_T t136_tmp;
  real_T t136;
  real_T t137;
  real_T t140;
  real_T t144_tmp;
  real_T t144;
  real_T t146;
  real_T t148;
  real_T t152;
  real_T t153;
  real_T t154;
  real_T t155;
  real_T t161;
  real_T t162;
  real_T t163;
  real_T t172;
  real_T t173;
  real_T t177;
  real_T t178;
  real_T t182;
  real_T t186;
  real_T t187;
  real_T t214;
  real_T out1_tmp;
  real_T b_out1_tmp;
  real_T c_out1_tmp;
  real_T d_out1_tmp;
  real_T e_out1_tmp;
  real_T f_out1_tmp;
  real_T g_out1_tmp;
  real_T h_out1_tmp;
  real_T i_out1_tmp;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* CNSTF4 */
  /*     [OUT1,OUT2,OUT3] = CNSTF4(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:50:43 */
  st.site = &yab_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[3] * in2[3];
  st.site = &abb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[5] * in2[5];
  st.site = &bbb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[4] * in2[4];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &cbb_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[3] * 0.038;
  t10_tmp = in2[4] * 0.03 + t6 * 0.038;
  t107 = t5;
  st.site = &dbb_emlrtRSI;
  b_sqrt(&st, &t107);
  t11 = 1.0 / t107;
  t12 = in2[4] * 0.038;
  t13 = t6 * 0.03;
  t14_tmp = t12 - t13;
  t15_tmp = t6 * t14_tmp;
  t16_tmp = in2[4] * t10_tmp;
  t17 = in2[3] * 0.03;
  t18 = in2[5] * 0.038;
  t19 = t17 - t18;
  t20_tmp = in2[3] * t19;
  t21 = in2[5] * 0.03;
  t107 = t7 + t21;
  t23 = in2[5] * 0.06;
  t263 = in2[3] * in2[4];
  t42_tmp = t263 * t11;
  t42 = t42_tmp * 0.03;
  t43_tmp = in2[3] * t10_tmp * t11;
  t24 = ((t7 + t23) - t42) - t43_tmp;
  t26 = t42_tmp * 0.038;
  t27_tmp = in2[3] * t11;
  b_t27_tmp = t27_tmp * t14_tmp;
  t28_tmp = ((in2[5] * 0.076 + t26) + b_t27_tmp) - in2[3] * 0.09;
  t29 = in2[4] * 0.076;
  t30_tmp = t2 * t11;
  t30 = t30_tmp * 0.03;
  t31_tmp = t27_tmp * t19;
  t45 = t6 * 0.06;
  t46_tmp_tmp = in2[3] * in2[5];
  t46_tmp = t46_tmp_tmp * t11;
  t46 = t46_tmp * 0.038;
  t32 = (((t29 + t30) + t31_tmp) - t45) - t46;
  t273 = t6 * t10_tmp;
  t270 = in2[3] * t107;
  t266 = in2[5] * t19;
  t221 = in2[4] * t14_tmp;
  t36_tmp = ((((-in2[0] + in2[72]) + t273) + t270) + t266) - t221;
  t37_tmp = in2[3] * t14_tmp;
  t38_tmp = in2[5] * t10_tmp;
  t39_tmp = in2[4] * t107;
  t264 = t6 * t19;
  t40_tmp = ((((-in2[1] + in2[73]) + t37_tmp) + t38_tmp) + t39_tmp) - t264;
  t49_tmp = in2[5] * t107;
  t47_tmp_tmp = (((in2[2] - in2[74]) + t15_tmp) + t16_tmp) + t20_tmp;
  t47_tmp = t47_tmp_tmp - t49_tmp;
  t50_tmp = in2[4] * t11;
  t50 = t50_tmp * 0.03;
  t52 = t50_tmp * 0.038;
  t54_tmp = t6 * (t50 + 0.038);
  t63_tmp = in2[4] * (t52 - 0.03);
  t64_tmp = t50_tmp * t14_tmp;
  t55_tmp = ((t10_tmp + t54_tmp) - t63_tmp) - t64_tmp;
  t56_tmp = t6 * (t52 - 0.03);
  t57_tmp = in2[4] * (t50 + 0.038);
  t58_tmp = t16_tmp * t11;
  t59_tmp = ((t14_tmp + t56_tmp) + t57_tmp) + t58_tmp;
  t60_tmp = in2[3] * (t50 + 0.038);
  t61_tmp = t50_tmp * t19;
  t65_tmp = in2[5] * (t52 - 0.03);
  t62 = ((t107 + t60_tmp) + t61_tmp) - t65_tmp;
  t68 = (in2[5] * t36_tmp + in2[3] * t47_tmp) - t6 * t40_tmp;
  t69 = in2[3] * 0.076;
  t70_tmp_tmp = in2[4] * in2[5];
  t70_tmp = t70_tmp_tmp * t11;
  t70 = t70_tmp * 0.038;
  t71_tmp = in2[5] * t11;
  b_t71_tmp = t71_tmp * t14_tmp;
  t72 = ((t21 + t69) + t70) + b_t71_tmp;
  t74 = t70_tmp * 0.03;
  t75_tmp = t38_tmp * t11;
  t76_tmp = ((in2[5] * 0.114 + t74) + t75_tmp) - in2[3] * 0.06;
  t77 = in2[4] * 0.06;
  t78 = t6 * 0.076;
  t79_tmp = t71_tmp * t19;
  t80 = t46_tmp * 0.03;
  t83_tmp = t3 * t11;
  t83 = t83_tmp * 0.038;
  t81_tmp = (((t77 + t78) + t79_tmp) + t80) - t83;
  t85 = in2[5] * t6 * 2.0;
  t86 = t2 * 2.0;
  t87 = t3 * 2.0;
  t88 = t6 * 2.0;
  t89 = in2[4] * 2.0;
  t90 = t46_tmp * 2.0;
  t91 = t6 * t55_tmp;
  t92 = in2[4] * t59_tmp;
  st.site = &ebb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t93 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t94 = in2[3] * t24;
  t95 = in2[5] * t28_tmp;
  t96 = in2[3] * t62;
  t97 = t27_tmp * 0.03;
  t107 = in2[3] * t4 * t93;
  t100 = ((t97 + t107 * 0.03) + t263 * t10_tmp * t93) - t27_tmp * (t52 - 0.03);
  t105 = ((t27_tmp * 0.038 + t27_tmp * (t50 + 0.038)) + t107 * 0.038) + t263 *
    t14_tmp * t93;
  t106 = t50_tmp * 0.06;
  t5 = in2[4] * t2 * t93;
  t107 = t5 * 0.03;
  t225 = t263 * in2[5] * t93;
  t111 = t225 * 0.038;
  t109 = (((t106 + t107) + t263 * t19 * t93) - t111) + 0.076;
  t112 = in2[4] * t32;
  t113 = in2[5] * t24;
  t114 = t27_tmp * t40_tmp;
  t117 = ((in2[3] * t55_tmp + t50_tmp * t40_tmp) - in2[5] * t59_tmp) - t6 * t62;
  t119 = 1.0 / (((t2 + t3) + t4) - 1.0);
  t121 = t10_tmp * t11;
  t166 = t2 * t119;
  t123 = ((((t50 + t107) + t166 * 0.038) + t121) + t2 * t10_tmp * t93) - 0.038;
  t124 = t11 * t14_tmp;
  t127_tmp = t52 + t124;
  t127 = (((t127_tmp + t2 * t14_tmp * t93) + t5 * 0.038) - t166 * 0.03) - 0.09;
  t130 = t11 * t19;
  t133 = t71_tmp * 0.038;
  t5 = in2[5] * t2 * t93;
  t132 = ((((t27_tmp * 0.15 + in2[3] * t2 * t93 * 0.03) + t130) + t2 * t19 * t93)
          - t133) - t5 * 0.038;
  t229 = in2[3] * t28_tmp;
  t136_tmp = t6 * t32;
  t136 = (((t47_tmp + t113) + t114) - t229) - t136_tmp;
  t137 = t88 - t30_tmp * 2.0;
  t166 = t46_tmp_tmp * t119;
  t140 = ((t111 + t46_tmp_tmp * t14_tmp * t93) - t166 * 0.03) + 0.076;
  t144_tmp = in2[3] * t3 * t93;
  t144 = (((t71_tmp * 0.06 + t5 * 0.03) + t46_tmp_tmp * t19 * t93) - t27_tmp *
          0.076) - t144_tmp * 0.038;
  t146 = t225 * 0.03;
  t148 = ((t166 * 0.038 + t146) + t46_tmp_tmp * t10_tmp * t93) - 0.06;
  t152 = in2[4] * t76_tmp;
  t153 = in2[4] * t28_tmp;
  t154 = in2[3] * t81_tmp;
  t155 = t27_tmp * t36_tmp;
  t225 = ((((in2[0] - in2[72]) - t273) - t270) - t266) + t221;
  t161 = (((t225 + in2[5] * t76_tmp) + in2[3] * t72) + t6 * t81_tmp) - t71_tmp *
    t40_tmp;
  t162 = t89 + t90;
  t163 = in2[1] * 2.0;
  t5 = t4 * t93;
  t166 = t11 * 0.038 + t5 * 0.038;
  t5 = t11 * 0.03 + t5 * 0.03;
  t172 = ((t130 + in2[3] * t5) + t4 * t19 * t93) - in2[5] * t166;
  t173 = t11 * t36_tmp;
  t177 = (((((t106 + t121) + t6 * t166) + in2[4] * t5) + t4 * t10_tmp * t93) -
          t50_tmp * (t52 - 0.03) * 2.0) + 0.076;
  t178 = t50_tmp * 0.076;
  t182 = (((((t124 + t178) + in2[4] * t166) + t4 * t14_tmp * t93) + t50_tmp *
           (t50 + 0.038) * 2.0) - t6 * t5) - 0.06;
  t186 = t264 * 2.0;
  t187 = t11 * t68;
  t107 = t50_tmp * t47_tmp;
  t214 = ((((((((((((((((((in2[0] * -2.0 - t91) - t92) + t94) + t95) - t96) +
                      t112) + in2[72] * 2.0) + t273 * 2.0) + in2[5] *
                   ((((((t28_tmp + t6 * t100) + in2[4] * t105) + t50_tmp * t24)
                      + t263 * t36_tmp * t93) - in2[5] * t109) - t27_tmp *
                    t59_tmp)) + t270 * 2.0) + t266 * 2.0) + t107) + t50_tmp *
               t136) + t27_tmp * t117) + t263 * t68 * t93) - t221 * 2.0) - in2[4]
           * ((((((((((-t12 + t13) - t30) - t31_tmp) + t46) + t56_tmp) + t57_tmp)
                 + t58_tmp) + in2[3] * t100) - in2[5] * t105) - in2[4] * t109))
          - in2[3] * (((((((((((-t21 + t42) + t43_tmp) + t60_tmp) + t61_tmp) -
    t65_tmp) + in2[4] * t100) + in2[3] * t109) + t50_tmp * t28_tmp) - t6 * t105)
                       - t27_tmp * t55_tmp) - t263 * t47_tmp * t93)) - t6 *
    ((((((t55_tmp + t50_tmp * t32) + t27_tmp * t62) + t263 * t40_tmp * t93) -
       in2[5] * t100) - in2[3] * t105) - t6 * t109);
  t124 = in2[4] * t55_tmp;
  t109 = in2[3] * t76_tmp;
  t100 = in2[5] * t62;
  t270 = t263 * 2.0;
  out1[0] = t85 - t270;
  out1[1] = (t86 + t87) - 1.0;
  t266 = in2[3] * t6 * 2.0;
  out1[2] = t70_tmp_tmp * -2.0 - t266;
  t5 = ((((in2[1] - in2[73]) - t37_tmp) - t38_tmp) - t39_tmp) + t264;
  out1_tmp = in2[5] * t32;
  b_out1_tmp = t6 * t24;
  c_out1_tmp = in2[4] * t24;
  d_out1_tmp = in2[3] * t32;
  e_out1_tmp = t6 * t28_tmp;
  f_out1_tmp = t27_tmp * t47_tmp;
  out1[3] = ((((((in2[4] * t36_tmp - in2[3] * t40_tmp) - t6 * t47_tmp) - t6 *
                (((((t47_tmp_tmp + t113) + t114) - t49_tmp) - t229) - t136_tmp))
               + in2[5] * (((t153 + t155) - out1_tmp) - b_out1_tmp)) + in2[3] *
              ((((t5 + c_out1_tmp) - d_out1_tmp) + e_out1_tmp) + f_out1_tmp)) +
             in2[4] * (((t36_tmp + t94) + t95) + t112)) + t27_tmp * t68;
  t111 = t6 * t59_tmp;
  t273 = t50_tmp * t36_tmp;
  g_out1_tmp = in2[5] * t55_tmp;
  h_out1_tmp = in2[3] * t59_tmp;
  i_out1_tmp = in2[4] * t62;
  out1[4] = ((((((in2[3] * t36_tmp + in2[4] * t40_tmp) - in2[5] * t47_tmp) - t6 *
                t117) + in2[4] * (((t40_tmp - g_out1_tmp) - h_out1_tmp) +
    i_out1_tmp)) - in2[3] * ((((t225 + t91) + t92) + t96) - t107)) - in2[5] *
             ((((t47_tmp + t124) + t100) - t111) - t273)) + t50_tmp * t68;
  t105 = in2[5] * t72;
  t107 = in2[4] * t81_tmp;
  t166 = t6 * t72;
  t106 = t71_tmp * t47_tmp;
  t114 = in2[4] * t72;
  t94 = in2[5] * t81_tmp;
  t95 = t6 * t76_tmp;
  t47_tmp_tmp = t71_tmp * t36_tmp;
  out1[5] = ((((((-in2[3] * (((t152 + t154) - t166) - t106) - in2[5] * t40_tmp)
                 - in2[4] * t47_tmp) - t6 * t36_tmp) + t6 * t161) - in2[4] *
              (((t47_tmp + t109) - t105) - t107)) + in2[5] * ((((t5 + t114) -
    t94) + t95) + t47_tmp_tmp)) + t71_tmp * t68;
  memset(&out1[6], 0, 66U * sizeof(real_T));
  out1[72] = -t85 + t270;
  out1[73] = (-t86 - t87) + 1.0;
  out1[74] = t70_tmp_tmp * 2.0 + t266;
  memset(&out1[75], 0, sizeof(real_T) << 4);
  t5 = in2[5] * t4 * t93;
  t221 = ((t71_tmp * 0.03 + t5 * 0.03) + t70_tmp_tmp * t10_tmp * t93) - t71_tmp *
    (t52 - 0.03);
  t225 = ((t133 + t71_tmp * (t50 + 0.038)) + t5 * 0.038) + t70_tmp_tmp * t14_tmp
    * t93;
  t136_tmp = in2[4] * t3 * t93;
  t229 = t136_tmp * 0.038;
  t5 = (((t146 - t178) + t70_tmp_tmp * t19 * t93) - t229) + 0.06;
  t112 = in2[3] * 2.0 + t70_tmp * 2.0;
  t113 = in2[5] * 2.0 - t42_tmp * 2.0;
  t263 = ((((((((((((((((((in2[2] * -2.0 - t124) - t109) - t100) + in2[74] * 2.0)
                       + t111) + t6 * ((((((t59_tmp + in2[5] * t221) + in2[3] *
    t225) + t6 * t5) - t71_tmp * t62) - t50_tmp * t81_tmp) - t70_tmp_tmp *
    t40_tmp * t93)) + t105) + in2[4] * (((((((((t10_tmp - t54_tmp) + t63_tmp) +
    t64_tmp) + t79_tmp) + t80) - t83) + in2[5] * t225) + in2[4] * t5) - in2[3] *
    t221)) + in2[5] * (((((((((((t7 - t60_tmp) - t61_tmp) + t65_tmp) + t70) +
    b_t71_tmp) + t6 * t221) + in2[4] * t225) + t70_tmp_tmp * t36_tmp * t93) -
    in2[5] * t5) - t71_tmp * t59_tmp) - t50_tmp * t76_tmp)) + t49_tmp * 2.0) +
                 t107) + t273) + t71_tmp * t117) + t70_tmp_tmp * t68 * t93) -
             t16_tmp * 2.0) - t20_tmp * 2.0) - in2[3] * ((((((t76_tmp + in2[4] *
    t221) + in2[3] * t5) + t50_tmp * t72) - t6 * t225) - t71_tmp * t55_tmp) -
            t70_tmp_tmp * t47_tmp * t93)) - t15_tmp * 2.0) - t50_tmp * t161;
  t264 = in2[73] * 2.0;
  t5 = t3 * t119;
  t266 = (((t127_tmp + t229) + t3 * t14_tmp * t93) - t5 * 0.03) + 0.03;
  t270 = ((((t50 + t121) + t5 * 0.038) + t3 * t10_tmp * t93) + t136_tmp * 0.03)
    + 0.114;
  t273 = ((((t97 + t130) + t3 * t19 * t93) + t144_tmp * 0.03) - t71_tmp * 0.19)
    - in2[5] * t3 * t93 * 0.038;
  t13 = t37_tmp * 2.0;
  t12 = t38_tmp * 2.0;
  t100 = t39_tmp * 2.0;
  t109 = t88 - t83_tmp * 2.0;
  t105 = (((((((((((((-t152 + t153) - t154) + t155) + t6 * (((((((((((t7 - t21)
    + t42) + t43_tmp) + t70) + b_t71_tmp) + in2[5] * t148) + in2[3] * t140) + t6
    * t144) - t71_tmp * t32) - t27_tmp * t81_tmp) - t46_tmp_tmp * t40_tmp * t93))
                  + in2[5] * ((((((((((-t29 - t30) - t31_tmp) + t45) + t46) +
    in2[4] * t140) + t6 * t148) + t71_tmp * t24) + t46_tmp_tmp * t36_tmp * t93)
    - in2[5] * t144) - t27_tmp * t76_tmp)) + t166) + t106) + t71_tmp * t136) +
              t46_tmp_tmp * t68 * t93) - out1_tmp) - in2[3] * ((((((t81_tmp +
    in2[4] * t148) + in2[3] * t144) + t27_tmp * t72) + t71_tmp * t28_tmp) - t6 *
              t140) - t46_tmp_tmp * t47_tmp * t93)) - in2[4] * ((((((((t17 + t18)
    - t26) - b_t27_tmp) + t74) + t75_tmp) + in2[3] * t148) - in2[5] * t140) -
            in2[4] * t144)) - b_out1_tmp) - t27_tmp * t161;
  t5 = t89 - t90;
  t166 = t109 * in2[104];
  t111 = in2[3] * in2[102] * 4.0;
  t225 = in2[5] * in2[104] * 4.0;
  t221 = t162 * in2[102];
  t229 = t112 * in2[103];
  out2[0] = (t166 - t221) - t229;
  out2[1] = t111 + t225;
  t136_tmp = t113 * in2[103];
  t106 = t5 * in2[104];
  out2[2] = (-t137 * in2[102] - t136_tmp) - t106;
  t124 = t11 * t47_tmp;
  t107 = t11 * t40_tmp;
  out2[3] = (((((((in2[3] * in2[100] * 4.0 - in2[3] * in2[172] * 4.0) - t137 *
                  in2[101]) - t162 * in2[99]) + t137 * in2[173]) + t214 * in2
               [103]) + t162 * in2[171]) + t105 * in2[104]) + in2[102] *
    ((((((((((((((((in2[73] * -2.0 + t163) + t186) + t187) - in2[3] *
                 ((((((((((in2[4] * 0.152 - t6 * 0.12) + in2[4] * t123) + in2[3]
    * t132) + t30_tmp * 0.06) - t124) - t6 * t127) - t46_tmp * 0.076) + t31_tmp *
                    2.0) + t27_tmp * t28_tmp * 2.0) - t2 * t47_tmp * t93)) - t12)
               - t13) - t100) + c_out1_tmp * 2.0) - d_out1_tmp * 2.0) +
           e_out1_tmp * 2.0) + in2[4] * ((((((in2[5] * 0.12 + t69) - in2[3] *
    t123) + in2[5] * t127) + in2[4] * t132) - t42_tmp * 0.06) - t43_tmp * 2.0))
         + t6 * (((((((((in2[3] * -0.18 + in2[5] * 0.152) + in2[5] * t123) +
                       in2[3] * t127) - t107) + t6 * t132) + t42_tmp * 0.076) +
                   b_t27_tmp * 2.0) - t27_tmp * t32 * 2.0) - t2 * t40_tmp * t93))
        + in2[5] * (((((t173 + in2[4] * t127) - in2[5] * t132) + t6 * t123) +
                     t27_tmp * t24 * 2.0) + t2 * t36_tmp * t93)) + f_out1_tmp *
       2.0) + t27_tmp * t136 * 2.0) + t2 * t68 * t93);
  out2[4] = (((((t214 * in2[102] - t112 * in2[99]) - t113 * in2[101]) + t263 *
               in2[104]) + t112 * in2[171]) + t113 * in2[173]) + in2[103] *
    (((((((((((((((-t163 - t186) + t187) + t264) + t13) + t12) + t100) + in2[4] *
             (((((((t23 + t69) + t60_tmp * 2.0) - t65_tmp * 2.0) + in2[4] * t172)
                - in2[3] * t177) + in2[5] * t182) + t61_tmp * 2.0)) - g_out1_tmp
            * 2.0) - h_out1_tmp * 2.0) + i_out1_tmp * 2.0) - in2[3] *
         ((((((((((t29 - t45) + t57_tmp * 2.0) + in2[3] * t172) + in2[4] * t177)
               - t124) + t56_tmp * 2.0) - t6 * t182) + t58_tmp * 2.0) - t50_tmp *
           t55_tmp * 2.0) - t4 * t47_tmp * t93)) + t6 * (((((in2[5] * t177 +
             in2[3] * t182) - t107) + t6 * t172) - t50_tmp * t62 * 2.0) - t4 *
         t40_tmp * t93)) + in2[5] * ((((((((((-t77 - t78) + t173) + t63_tmp *
    2.0) - in2[5] * t172) + in2[4] * t182) - t54_tmp * 2.0) + t6 * t177) +
          t64_tmp * 2.0) - t50_tmp * t59_tmp * 2.0) + t4 * t36_tmp * t93)) +
      t50_tmp * t117 * 2.0) + t4 * t68 * t93);
  out2[5] = (((((((in2[5] * in2[100] * 4.0 - in2[5] * in2[172] * 4.0) + t263 *
                  in2[103]) + t109 * in2[99]) + t105 * in2[102]) - t5 * in2[101])
              - t109 * in2[171]) + t5 * in2[173]) + in2[104] *
    ((((((((((((((((t163 + t186) + t187) - t264) - t13) - t12) - t100) + t114 *
              2.0) - t94 * 2.0) + t95 * 2.0) - in2[5] * ((((((((((in2[4] * 0.12
    + t6 * 0.152) - t173) - in2[4] * t266) + in2[5] * t273) - t83_tmp * 0.076) -
    t6 * t270) + t46_tmp * 0.06) + t79_tmp * 2.0) + t71_tmp * t76_tmp * 2.0) -
            t3 * t36_tmp * t93)) + in2[4] * ((((((in2[3] * 0.152 + t23) + in2[5]
    * t266) - in2[3] * t270) + in2[4] * t273) + t70_tmp * 0.076) + b_t71_tmp *
           2.0)) - in2[3] * (((((in2[4] * t270 + in2[3] * t273) - t124) - t6 *
            t266) + t71_tmp * t72 * 2.0) - t3 * t47_tmp * t93)) + t6 *
        (((((((((in2[3] * -0.12 + in2[5] * 0.228) + in2[3] * t266) + in2[5] *
               t270) - t107) + t6 * t273) + t70_tmp * 0.06) + t75_tmp * 2.0) -
          t71_tmp * t81_tmp * 2.0) - t3 * t40_tmp * t93)) + t47_tmp_tmp * 2.0) -
      t71_tmp * t161 * 2.0) + t3 * t68 * t93);
  memset(&out2[6], 0, 66U * sizeof(real_T));
  out2[72] = (-t166 + t221) + t229;
  out2[73] = -t111 - t225;
  out2[74] = (t137 * in2[102] + t136_tmp) + t106;
  memset(&out2[75], 0, sizeof(real_T) << 4);
  *out3 = 0.0;
}

/* End of code generation (cnstF4.c) */
