/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF2.c
 *
 * Code generation for function 'cnstF2'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "cnstF2.h"

/* Function Definitions */
void cnstF2(const real_T in2[198], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  /* CNSTF2 */
  /*     [OUT1,OUT2,OUT3] = CNSTF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:48:21 */
  out1[0] = 0.0;
  out1[1] = 0.0;
  out1[2] = 1.0;
  out1[3] = in2[3] * 0.54;
  out1[4] = in2[4] * 0.54;
  memset(&out1[5], 0, 86U * sizeof(real_T));
  out2[0] = 0.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = in2[102] * 0.54;
  out2[4] = in2[103] * 0.54;
  memset(&out2[5], 0, 86U * sizeof(real_T));
  *out3 = 0.0;
}

/* End of code generation (cnstF2.c) */
