/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF108.c
 *
 * Code generation for function 'sprdmpF108'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "sprdmpF108.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo iu_emlrtRSI = { 40, /* lineNo */
  "sprdmpF108",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF108.m"/* pathName */
};

static emlrtRSInfo ju_emlrtRSI = { 46, /* lineNo */
  "sprdmpF108",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF108.m"/* pathName */
};

static emlrtRSInfo nu_emlrtRSI = { 76, /* lineNo */
  "sprdmpF108",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF108.m"/* pathName */
};

static emlrtRSInfo ou_emlrtRSI = { 88, /* lineNo */
  "sprdmpF108",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF108.m"/* pathName */
};

/* Function Definitions */
void sprdmpF108(const emlrtStack *sp, const real_T in1[6], const real_T in2[198],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t166;
  real_T t214;
  real_T t184;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t208;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t217;
  real_T t25;
  real_T t213;
  real_T t33_tmp;
  real_T t209;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t44_tmp;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t183;
  real_T t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t207;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t57_tmp;
  real_T t58_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61;
  real_T t65;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T t85_tmp;
  real_T t85;
  real_T t89;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t100;
  real_T t101;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t106_tmp;
  real_T b_t106_tmp;
  real_T t106;
  real_T t115_tmp;
  real_T t115;
  real_T t118;
  real_T t128;
  real_T t132;
  real_T t133;
  real_T t134;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t148;
  real_T t151;
  real_T t158;
  real_T t160;
  real_T t162;
  real_T t165;
  real_T t168;
  real_T t171;
  real_T t175;
  real_T t179;
  real_T t187;
  real_T t191;
  real_T t192;
  real_T t194;
  real_T t197;
  real_T t203;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF108 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF108(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:26:21 */
  t2 = in2[58] * in2[58];
  t3 = in2[59] * in2[59];
  t4 = in2[57] * in2[57];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &iu_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[59] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[57] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &ju_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t166 = in2[55] - in2[61];
  t214 = in2[56] - in2[62];
  t184 = in2[54] - in2[60];
  t17_tmp = in2[57] * t12;
  t17 = (-in2[56] + in2[62]) + t17_tmp * t166;
  t19 = t166 + t17_tmp * t214;
  t20 = t6 * t166;
  t208 = in2[57] * t214;
  t22_tmp = in2[57] * t166;
  t23_tmp = t6 * t214;
  t217 = in2[58] * t184;
  t25 = t6 * t184;
  t213 = in2[59] * t166;
  t33_tmp = in2[58] * t214;
  t209 = t25 + t213;
  t27 = t209 - t33_tmp;
  t29_tmp = in2[58] * t12;
  t29 = (-in2[54] + in2[60]) + t29_tmp * t214;
  t31 = t214 + t29_tmp * t184;
  t44_tmp = in2[59] * t184;
  t32_tmp = t20 + t208;
  t32 = t32_tmp - t44_tmp;
  t34 = (-t22_tmp + t23_tmp) + t217;
  t35 = in2[65] * 2.0;
  t36 = in2[57] - in2[63];
  t5 = ((-(in2[63] * in2[63]) - in2[64] * in2[64]) - in2[65] * in2[65]) + 1.0;
  t41 = t5;
  st.site = &nu_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[58] - in2[64];
  t43 = in2[59] - in2[65];
  t46_tmp = in2[59] * t12;
  t46 = t184 + t46_tmp * t166;
  t48 = (-in2[55] + in2[61]) + t46_tmp * t184;
  t49 = in2[63] * 2.0;
  t50_tmp = in2[58] * t6 * 2.0;
  t183 = in2[57] * in2[58];
  t51_tmp = t183 * 2.0;
  t52_tmp = in2[57] * in2[59];
  t52 = t52_tmp * 2.0;
  t207 = in2[58] * in2[59];
  t53_tmp = t207 * 2.0;
  st.site = &ou_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[58] * 2.0;
  t57_tmp = in2[57] * t184;
  t58_tmp = in2[58] * t166;
  t59_tmp = in2[59] * t214;
  t60_tmp = (t57_tmp + t58_tmp) + t59_tmp;
  t61 = t6 - t41;
  t207 *= t12;
  t65 = (((((t23_tmp + t217) + t6 * t31) + t29_tmp * t27) + t207 * t166) - in2
         [58] * t29) - t22_tmp * 2.0;
  t69 = (((((-t20 + t44_tmp) + t6 * t48) + in2[59] * t46) + t46_tmp * t27) -
         t208 * 2.0) - t207 * t214;
  t70 = (t8 + t11) - 1.0;
  t71 = t7 + t51_tmp;
  t72 = t50_tmp - t52;
  t73 = in2[59] * t17;
  t74 = t17_tmp * t27;
  t85_tmp = in2[58] * t19;
  t85 = ((t60_tmp - t73) - t74) + t85_tmp;
  t89 = muDoubleScalarPower(muDoubleScalarAbs((((((((t65 * in2[157] + t69 * in2
    [158]) + t70 * in2[153]) + t72 * in2[155]) + t71 * in2[160]) - t70 * in2[159])
    - t71 * in2[154]) - t72 * in2[161]) - t85 * in2[156]), in1[1] - 1.0);
  t94 = t6 * t17;
  t95 = in2[57] * t19;
  t96 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t100 = ((((t209 + t6 * t46) + t46_tmp * t32) + t5 * t214) - in2[59] * t48) -
    t33_tmp * 2.0;
  t101 = (t8 + t10) - 1.0;
  t102 = t9 + t53_tmp;
  t103 = t7 - t51_tmp;
  t104 = in2[57] * t29;
  t105 = t29_tmp * t32;
  t106_tmp = t217 * 2.0;
  b_t106_tmp = t5 * t184;
  t106 = (((((t22_tmp - t23_tmp) + t94) + t95) + t96) - t106_tmp) - b_t106_tmp;
  t115_tmp = in2[59] * t31;
  t115 = ((t60_tmp - t104) - t105) + t115_tmp;
  t118 = muDoubleScalarPower(muDoubleScalarAbs((((((((t106 * in2[156] + t100 *
    in2[158]) + t101 * in2[154]) + t103 * in2[153]) + t102 * in2[161]) - t101 *
    in2[160]) - t102 * in2[155]) - t103 * in2[159]) - t115 * in2[157]), in1[1] -
    1.0);
  t208 = t183 * t12;
  t128 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t208 * t184) - in2[57] * t17)
    - t44_tmp * 2.0;
  t132 = (((((-t25 + t33_tmp) + t6 * t29) + in2[58] * t31) + t29_tmp * t34) -
          t213 * 2.0) - t208 * t166;
  t133 = (t10 + t11) - 1.0;
  t134 = t50_tmp + t52;
  t135 = t9 - t53_tmp;
  t136 = in2[58] * t48;
  t137 = t46_tmp * t34;
  t33_tmp = in2[57] * t46;
  t148 = ((t60_tmp - t136) - t137) + t33_tmp;
  t151 = muDoubleScalarPower(muDoubleScalarAbs((((((((t128 * in2[156] + t132 *
    in2[157]) + t133 * in2[155]) + t135 * in2[154]) + t134 * in2[159]) - t133 *
    in2[161]) - t134 * in2[153]) - t135 * in2[160]) - t148 * in2[158]), in1[1] -
    1.0);
  t29 = t17_tmp * t36 * 2.0;
  t31 = t29_tmp * t36 * 2.0;
  t158 = in2[64] * 2.0;
  t48 = t5 * 2.0;
  t160 = (t158 + t46_tmp * t36 * 2.0) - t48;
  t162 = t55 + in2[57] * in2[63] * t54 * 2.0;
  t5 = in2[59] * 2.0;
  t165 = t5 + in2[57] * in2[64] * t54 * 2.0;
  t166 = in2[57] * in2[65] * t54 * 2.0;
  t44_tmp = t208 * 2.0;
  t168 = (t35 - t31) + t44_tmp;
  t46 = t41 * 2.0;
  t20 = t4 * t12 * 2.0;
  t171 = (-t29 + t46) + t20;
  t175 = t56 - t166;
  t179 = muDoubleScalarPower(muDoubleScalarAbs(((((t171 * in2[156] + t168 * in2
    [157]) + t175 * in2[164]) - t160 * in2[158]) - t162 * in2[162]) - t165 *
    in2[163]), in1[1] - 1.0);
  t183 = t29_tmp * t42 * 2.0;
  t184 = t17_tmp * t42 * 2.0;
  t17 = t46_tmp * t42 * 2.0;
  t187 = t55 + in2[58] * in2[64] * t54 * 2.0;
  t19 = in2[58] * in2[63] * t54 * 2.0;
  t4 = in2[57] * 2.0;
  t191 = t4 + in2[58] * in2[65] * t54 * 2.0;
  t192 = (t35 - t44_tmp) + t184;
  t217 = t2 * t12 * 2.0;
  t194 = (t46 - t183) + t217;
  t32_tmp = t207 * 2.0;
  t197 = (t49 - t17) + t32_tmp;
  t2 = t5 - t19;
  t203 = muDoubleScalarPower(muDoubleScalarAbs(((((t194 * in2[157] + t197 * in2
    [158]) + t2 * in2[162]) - t192 * in2[156]) - t187 * in2[163]) - t191 * in2
    [164]), in1[1] - 1.0);
  t207 = t46_tmp * t43 * 2.0;
  t208 = t17_tmp * t43 * 2.0;
  t209 = t29_tmp * t43 * 2.0;
  t25 = t55 + in2[59] * in2[65] * t54 * 2.0;
  t213 = t56 + in2[59] * in2[63] * t54 * 2.0;
  t214 = in2[59] * in2[64] * t54 * 2.0;
  memset(&out1[0], 0, 54U * sizeof(real_T));
  out1[54] = t70;
  out1[55] = -t7 - t51_tmp;
  out1[56] = t50_tmp - in2[57] * in2[59] * 2.0;
  out1[57] = ((((t73 + t74) - t58_tmp) - t57_tmp) - t59_tmp) - t85_tmp;
  out1[58] = t65;
  out1[59] = t69;
  out1[60] = (-t8 - t11) + 1.0;
  out1[61] = t71;
  out1[62] = -t50_tmp + t52;
  memset(&out1[63], 0, 82U * sizeof(real_T));
  out1[145] = t7 - in2[57] * in2[58] * 2.0;
  out1[146] = t101;
  out1[147] = -t9 - t53_tmp;
  out1[148] = (((((t22_tmp + t94) + t95) + t96) - t106_tmp) - t23_tmp) -
    b_t106_tmp;
  out1[149] = ((((t104 + t105) - t58_tmp) - t57_tmp) - t59_tmp) - t115_tmp;
  out1[150] = t100;
  out1[151] = -t7 + t51_tmp;
  out1[152] = (-t8 - t10) + 1.0;
  out1[153] = t102;
  memset(&out1[154], 0, 82U * sizeof(real_T));
  out1[236] = t52_tmp * -2.0 - t50_tmp;
  out1[237] = t9 - in2[58] * in2[59] * 2.0;
  out1[238] = t133;
  out1[239] = t128;
  out1[240] = t132;
  out1[241] = ((((t136 + t137) - t58_tmp) - t57_tmp) - t59_tmp) - t33_tmp;
  out1[242] = t134;
  out1[243] = -t9 + t53_tmp;
  out1[244] = (-t10 - t11) + 1.0;
  memset(&out1[245], 0, 85U * sizeof(real_T));
  out1[330] = (t41 * -2.0 + t29) - t20;
  out1[331] = (-t35 + t31) - t44_tmp;
  out1[332] = t160;
  out1[333] = 0.0;
  out1[334] = 0.0;
  out1[335] = 0.0;
  out1[336] = t162;
  out1[337] = t165;
  out1[338] = -t56 + t166;
  memset(&out1[339], 0, 82U * sizeof(real_T));
  out1[421] = (t35 + t184) - t44_tmp;
  out1[422] = (t41 * -2.0 + t183) - t217;
  out1[423] = (-t49 + t17) - t32_tmp;
  out1[424] = 0.0;
  out1[425] = 0.0;
  out1[426] = 0.0;
  out1[427] = in2[59] * -2.0 + t19;
  out1[428] = t187;
  out1[429] = t191;
  memset(&out1[430], 0, 82U * sizeof(real_T));
  out1[512] = (in2[64] * -2.0 + t208) - t48;
  out1[513] = (t49 + t209) - t32_tmp;
  t5 = t3 * t12 * 2.0;
  out1[514] = (t41 * -2.0 + t207) - t5;
  out1[515] = 0.0;
  out1[516] = 0.0;
  out1[517] = 0.0;
  out1[518] = t213;
  out1[519] = in2[57] * -2.0 + t214;
  out1[520] = t25;
  memset(&out1[521], 0, 25U * sizeof(real_T));
  t183 = (t158 + t48) - t208;
  t217 = (t46 - t207) + t5;
  t209 += t49 - t32_tmp;
  t208 = t4 - t214;
  t214 = muDoubleScalarPower(muDoubleScalarAbs(((((t217 * in2[158] + t183 * in2
    [156]) + t208 * in2[163]) - t209 * in2[157]) - t25 * in2[164]) - t213 * in2
    [162]), in1[1] - 1.0);
  out2[0] = in1[0] * (((in2[59] * t32 - in2[58] * t34) + in2[57] * t60_tmp) + t6
                      * t27) * 0.00026666666666666668;
  out2[1] = in1[0] * (((-in2[59] * t27 + in2[57] * t34) + in2[58] * t60_tmp) +
                      t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((85.738792591009769 + in2[58] * t27) - in2[57] * t32) +
                       in2[59] * t60_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[58] * t43 * 2.0 - in2[59] * t42 * 2.0) + in2[57] *
                       t61 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[59] * t36 * 2.0 - in2[57] * t43 * 2.0) + in2[58] *
                       t61 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[58] * t36 * 2.0 - in2[57] * t42 * 2.0) - in2[59] *
                       t61 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t20 = in1[2] * t70 * t89;
  t207 = in1[2] * t71 * t89;
  t5 = in1[2] * t72 * t89;
  out3[0] = (((((((-in1[2] * t65 * t89 * in2[157] - t20 * in2[153]) + t207 *
                  in2[154]) - in1[2] * t69 * t89 * in2[158]) - t5 * in2[155]) +
               t20 * in2[159]) - t207 * in2[160]) + t5 * in2[161]) + in1[2] *
    t85 * t89 * in2[156];
  t20 = in1[2] * t103 * t118;
  t207 = in1[2] * t102 * t118;
  out3[1] = (((((((-in1[2] * t101 * t118 * in2[154] - t20 * in2[153]) + t207 *
                  in2[155]) - in1[2] * t100 * t118 * in2[158]) + in1[2] * t101 *
                t118 * in2[160]) + t20 * in2[159]) - in1[2] * t106 * t118 * in2
              [156]) - t207 * in2[161]) + in1[2] * t115 * t118 * in2[157];
  t20 = in1[2] * t134 * t151;
  t207 = in1[2] * t133 * t151;
  t5 = in1[2] * t135 * t151;
  out3[2] = (((((((-in1[2] * t128 * t151 * in2[156] + t20 * in2[153]) - t207 *
                  in2[155]) - in1[2] * t132 * t151 * in2[157]) - t5 * in2[154])
               - t20 * in2[159]) + t207 * in2[161]) + t5 * in2[160]) + in1[2] *
    t148 * t151 * in2[158];
  out3[3] = ((((-in1[3] * t160 * t179 * in2[158] - in1[3] * t162 * t179 * in2
                [162]) + in1[3] * t168 * t179 * in2[157]) + in1[3] * t171 * t179
              * in2[156]) - in1[3] * t165 * t179 * in2[163]) + in1[3] * t175 *
    t179 * in2[164];
  out3[4] = ((((-in1[3] * t192 * t203 * in2[156] - in1[3] * t187 * t203 * in2
                [163]) + in1[3] * t194 * t203 * in2[157]) - in1[3] * t191 * t203
              * in2[164]) + in1[3] * t197 * t203 * in2[158]) + in1[3] * t2 *
    t203 * in2[162];
  out3[5] = ((((in1[3] * t183 * t214 * in2[156] - in1[3] * t25 * t214 * in2[164])
               - in1[3] * t213 * t214 * in2[162]) + in1[3] * t217 * t214 * in2
              [158]) - in1[3] * t209 * t214 * in2[157]) + in1[3] * t208 * t214 *
    in2[163];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF108.c) */
