/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF94.c
 *
 * Code generation for function 'sprdmpF94'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "sprdmpF94.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo ul_emlrtRSI = { 18, /* lineNo */
  "sprdmpF94",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF94.m"/* pathName */
};

static emlrtRSInfo vl_emlrtRSI = { 19, /* lineNo */
  "sprdmpF94",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF94.m"/* pathName */
};

/* Function Definitions */
void sprdmpF94(const emlrtStack *sp, const real_T in2[198], real_T out1[546],
               real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t5;
  real_T t8;
  real_T t6;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF94 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF94(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:36:06 */
  t2 = in2[3] * in2[3];
  t3 = in2[4] * in2[4];
  t5 = ((-t2 - t3) - in2[5] * in2[5]) + 1.0;
  t8 = t5;
  st.site = &ul_emlrtRSI;
  b_sqrt(&st, &t8);
  t6 = 1.0 / t8;
  st.site = &vl_emlrtRSI;
  b_sqrt(&st, &t5);
  t8 = t5 * 0.27;
  t5 = in2[3] * in2[4] * t6 * 0.27;
  out1[0] = 1.0;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = in2[5] * -0.27 + t5;
  out1[4] = -t8 + t3 * t6 * 0.27;
  out1[5] = in2[3] * -0.27 + in2[4] * in2[5] * t6 * 0.27;
  memset(&out1[6], 0, 86U * sizeof(real_T));
  out1[92] = 1.0;
  out1[93] = 0.0;
  out1[94] = t8 - t2 * t6 * 0.27;
  out1[95] = in2[5] * -0.27 - t5;
  out1[96] = in2[4] * -0.27 - in2[3] * in2[5] * t6 * 0.27;
  memset(&out1[97], 0, 87U * sizeof(real_T));
  out1[184] = 1.0;
  out1[185] = in2[3] * 0.54;
  out1[186] = in2[4] * 0.54;
  memset(&out1[187], 0, 89U * sizeof(real_T));
  out1[276] = 2.0;
  memset(&out1[277], 0, 91U * sizeof(real_T));
  out1[368] = 2.0;
  memset(&out1[369], 0, 91U * sizeof(real_T));
  out1[460] = 2.0;
  memset(&out1[461], 0, 85U * sizeof(real_T));
  for (i = 0; i < 6; i++) {
    out2[i] = 0.0;
    out3[i] = 0.0;
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF94.c) */
