/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rksF.c
 *
 * Code generation for function 'rksF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rksF.h"

/* Function Definitions */
void rksF(const real_T in1[34], const real_T in2[48], real_T s)
{
  (void)in1;
  (void)in2;
  (void)s;

  /* RKSF */
  /*     R_KS = RKSF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 04:40:37 */
}

/* End of code generation (rksF.c) */
