/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 28,    /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 29,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 30,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 31,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 50,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 51,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 52,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 54,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo j_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6_tmp;
  real_T t7_tmp;
  real_T t8_tmp;
  real_T t9;
  real_T t13;
  real_T t14;
  real_T t21_tmp;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t24;
  real_T t25;
  real_T t26;
  real_T t28;
  real_T t29_tmp;
  real_T t30_tmp;
  real_T r_jtip_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 17:12:22 */
  st.site = &emlrtRSI;
  t2 = in1[4] * in1[4];
  st.site = &b_emlrtRSI;
  t3 = s * s;
  st.site = &c_emlrtRSI;
  t4 = t2 * t2;
  st.site = &d_emlrtRSI;
  t5 = t3 * t3;
  t6_tmp = in2[0] * t2;
  t7_tmp = in1[4] * in2[1];
  t8_tmp = in2[2] * t4;
  t9 = (in1[4] * in2[9] + in2[10] * t2) + in1[4] * in2[11] * t2;
  t13 = (in1[4] * in2[12] + in2[13] * t2) + in1[4] * in2[14] * t2;
  t14 = (in1[4] * in2[15] + in2[16] * t2) + in1[4] * in2[17] * t2;
  t21_tmp = in2[3] * t2;
  t22_tmp = in1[4] * in2[4];
  t23_tmp = in2[5] * t4;
  st.site = &e_emlrtRSI;
  t24 = t9 * t9;
  st.site = &f_emlrtRSI;
  t25 = t13 * t13;
  st.site = &g_emlrtRSI;
  t26 = t14 * t14;
  t28 = ((-t24 - t25) - t26) + 1.0;
  st.site = &h_emlrtRSI;
  if (t28 < 0.0) {
    b_st.site = &j_emlrtRSI;
    error(&b_st);
  }

  t28 = muDoubleScalarSqrt(t28);
  t29_tmp = in2[6] * t2;
  t30_tmp = in1[4] * in2[7];
  t4 *= in2[8];
  r_jtip[0] = (t6_tmp * t3 + t8_tmp * t5) + t7_tmp * s * t2 * t3;
  r_jtip_tmp = (t6_tmp + t7_tmp * t2) + t8_tmp;
  r_jtip[1] = r_jtip_tmp;
  r_jtip[2] = (t21_tmp * t3 + t23_tmp * t5) + t22_tmp * s * t2 * t3;
  t8_tmp = (t21_tmp + t22_tmp * t2) + t23_tmp;
  r_jtip[3] = t8_tmp;
  r_jtip[4] = ((in1[4] * s + t29_tmp * t3) + t4 * t5) + t30_tmp * s * t2 * t3;
  t7_tmp = ((in1[4] + t29_tmp) + t30_tmp * t2) + t4;
  r_jtip[5] = t7_tmp;
  r_jtip[6] = rtNaN;
  t6_tmp = in1[16] * t13;
  t4 = in1[16] * t9;
  r_jtip[7] = (r_jtip_tmp + t4 * t14 * 2.0) + t6_tmp * t28 * 2.0;
  r_jtip[8] = rtNaN;
  r_jtip[9] = (t8_tmp + t6_tmp * t14 * 2.0) - t4 * t28 * 2.0;
  r_jtip[10] = rtNaN;
  r_jtip[11] = (((t7_tmp - in1[16] * t24) - in1[16] * t25) + in1[16] * t26) -
    in1[16] * (((t24 + t25) + t26) - 1.0);
}

/* End of code generation (rjtipF.c) */
