function r_jtip = rjtipF(in1,in2,s)
%RJTIPF
%    R_JTIP = RJTIPF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jan-2019 13:21:33

l_f_sym = in1(:,17);
l_s_sym = in1(:,5);
q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = l_s_sym.^2;
t3 = s.^2;
t4 = q1.*t2;
t5 = q2.*t2;
t6 = q4.^2;
t7 = q5.^2;
t8 = q6.^2;
t11 = t2.*t6;
t12 = t2.*t7;
t13 = t2.*t8;
t9 = -t11-t12-t13+1.0;
t10 = sqrt(t9);
t14 = q3.*t2;
r_jtip = reshape([q1.*t2.*t3,t4,q2.*t2.*t3,t5,l_s_sym.*s+q3.*t2.*t3,l_s_sym+t14,NaN,t4+l_f_sym.*l_s_sym.*q5.*t10.*2.0+l_f_sym.*q4.*q6.*t2.*2.0,NaN,t5-l_f_sym.*l_s_sym.*q4.*t10.*2.0+l_f_sym.*q5.*q6.*t2.*2.0,NaN,l_s_sym+t14-l_f_sym.*(t11+t12+t13-1.0)-l_f_sym.*t2.*t6-l_f_sym.*t2.*t7+l_f_sym.*t2.*t8],[2,6]);
