/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rjtipF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo m_emlrtRSI = { 62,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo n_emlrtRSI = { 63,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo o_emlrtRSI = { 64,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRSInfo p_emlrtRSI = { 65,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\rjtipF.m"/* pathName */
};

static emlrtRTEInfo emlrtRTEI = { 13,  /* lineNo */
  9,                                   /* colNo */
  "sqrt",                              /* fName */
  "C:\\Program Files\\MATLAB\\R2020b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[48],
            real_T s, real_T ds, real_T t_sym, real_T out1[75])
{
  emlrtStack st;
  real_T b_out1_tmp;
  real_T out1_tmp;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  (void)s;
  (void)ds;
  (void)t_sym;
  st.prev = sp;
  st.tls = sp->tls;

  /* RJTIPF */
  /*     OUT1 = RJTIPF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     26-Feb-2021 21:20:53 */
  t11 = in2[21] * in2[21];
  t12 = in2[22] * in2[22];
  t13 = in2[23] * in2[23];
  st.site = &m_emlrtRSI;
  t33 = ((-(in2[3] * in2[3]) + -(in2[4] * in2[4])) + -(in2[5] * in2[5])) + 1.0;
  if (t33 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t30 = muDoubleScalarSqrt(t33);
  st.site = &n_emlrtRSI;
  t33 = ((-(in2[9] * in2[9]) + -(in2[10] * in2[10])) + -(in2[11] * in2[11])) +
    1.0;
  if (t33 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t31 = muDoubleScalarSqrt(t33);
  st.site = &o_emlrtRSI;
  t33 = ((-(in2[15] * in2[15]) + -(in2[16] * in2[16])) + -(in2[17] * in2[17])) +
    1.0;
  if (t33 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t32 = muDoubleScalarSqrt(t33);
  st.site = &p_emlrtRSI;
  t33 = ((-t11 + -t12) + -t13) + 1.0;
  if (t33 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t33 = muDoubleScalarSqrt(t33);
  out1[0] = in2[0];
  out1[1] = in2[6];
  out1[2] = in2[12];
  out1[3] = in2[18];
  out1[4] = in2[18];
  out1[5] = in2[1];
  out1[6] = in2[7];
  out1[7] = in2[13];
  out1[8] = in2[19];
  out1[9] = in2[19];
  out1[10] = in2[2];
  out1[11] = in2[8];
  out1[12] = in2[14];
  out1[13] = in2[20];
  out1[14] = in2[20];
  out1[15] = in2[0];
  out1[16] = in2[6];
  out1[17] = in2[12];
  out1[18] = in2[18];
  out1_tmp = in1[16] * in2[22];
  b_out1_tmp = in1[16] * in2[21];
  out1[19] = (in2[18] + b_out1_tmp * in2[23] * 2.0) + out1_tmp * t33 * 2.0;
  out1[20] = in2[1];
  out1[21] = in2[7];
  out1[22] = in2[13];
  out1[23] = in2[19];
  out1[24] = (in2[19] + out1_tmp * in2[23] * 2.0) - b_out1_tmp * t33 * 2.0;
  out1[25] = in2[2];
  out1[26] = in2[8];
  out1[27] = in2[14];
  out1[28] = in2[20];
  out1[29] = (((in2[20] + in1[16] * t13) + in1[16] * -t11) + in1[16] * -t12) -
    in1[16] * (((t11 + t12) + t13) - 1.0);
  out1[30] = t30;
  out1[31] = t31;
  out1[32] = t32;
  out1[33] = t33;
  out1[34] = t33;
  out1[35] = in2[3];
  out1[36] = in2[9];
  out1[37] = in2[15];
  out1[38] = in2[21];
  out1[39] = in2[21];
  out1[40] = in2[4];
  out1[41] = in2[10];
  out1[42] = in2[16];
  out1[43] = in2[22];
  out1[44] = in2[22];
  out1[45] = in2[5];
  out1[46] = in2[11];
  out1[47] = in2[17];
  out1[48] = in2[23];
  out1[49] = in2[23];
  out1[50] = t30;
  out1[51] = t31;
  out1[52] = t32;
  out1[53] = t33;
  out1[54] = t33;
  out1[55] = in2[3];
  out1[56] = in2[9];
  out1[57] = in2[15];
  out1[58] = in2[21];
  out1[59] = in2[21];
  out1[60] = in2[4];
  out1[61] = in2[10];
  out1[62] = in2[16];
  out1[63] = in2[22];
  out1[64] = in2[22];
  out1[65] = in2[5];
  out1[66] = in2[11];
  out1[67] = in2[17];
  out1[68] = in2[23];
  out1[69] = in2[23];
  out1[70] = 0.001;
  out1[71] = 0.001;
  out1[72] = 0.001;
  out1[73] = 0.001;
  out1[74] = in1[17];
}

/* End of code generation (rjtipF.c) */
