/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF3.c
 *
 * Code generation for function 'massF3'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF3.h"

/* Function Definitions */
void massF3(const real_T in1[34], const real_T in2[24], real_T out1[36], real_T
            out2[72], real_T out3[72], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t10_tmp;
  real_T t10;
  real_T t11_tmp;
  real_T t11;
  real_T t12_tmp;
  real_T t12;
  real_T t13_tmp;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16_tmp;
  real_T t16;
  real_T t26_tmp;
  real_T t26;
  real_T t17_tmp_tmp;
  real_T b_t17_tmp_tmp;
  real_T t86;
  real_T t18;
  real_T t19;
  real_T t20_tmp;
  real_T t20;
  real_T t32_tmp;
  real_T t32;
  real_T t21_tmp_tmp_tmp;
  real_T t21_tmp_tmp;
  real_T t152;
  real_T t23;
  real_T t24_tmp;
  real_T t24;
  real_T t31_tmp;
  real_T t31;
  real_T t25_tmp_tmp;
  real_T b_t25_tmp_tmp;
  real_T t153;
  real_T t122;
  real_T t30_tmp;
  real_T t123;
  real_T t33;
  real_T t116;
  real_T t34;
  real_T t35;
  real_T t120;
  real_T t36;
  real_T t43_tmp;
  real_T t103;
  real_T t43;
  real_T t44;
  real_T t45;
  real_T t46;
  real_T t47;
  real_T t48;
  real_T t49_tmp_tmp;
  real_T t176;
  real_T t50_tmp;
  real_T t50;
  real_T t119;
  real_T t51;
  real_T t52;
  real_T t53;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t57;
  real_T t59;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t63_tmp;
  real_T t63;
  real_T t64;
  real_T t65_tmp;
  real_T t65;
  real_T t155;
  real_T t154;
  real_T t68;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t112;
  real_T t76;
  real_T t77;
  real_T t78;
  real_T t79;
  real_T t80;
  real_T t81;
  real_T t130;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t128;
  real_T t87;
  real_T t115;
  real_T t187;
  real_T t113;
  real_T t114;
  real_T t127;
  real_T t181;
  real_T t126;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t95;
  real_T t99;
  real_T t100;
  real_T t101;
  real_T t102;

  /* MASSF3 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF3(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 23:05:35 */
  t2 = in1[16] * in1[16];
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  t2 = in1[4] / 2.0;
  t10_tmp = in2[3] * in2[9];
  t10 = t10_tmp / 4.0;
  t11_tmp = in2[4] * in2[10];
  t11 = t11_tmp / 4.0;
  t12_tmp = in2[5] * in2[11];
  t12 = t12_tmp / 4.0;
  t13_tmp = t10 + t11;
  t13 = (t13_tmp + t12) - 1.0;
  t14 = in2[3] / 2.0;
  t15 = in2[9] / 2.0;
  t16_tmp = in2[4] * in2[11];
  t16 = t16_tmp / 4.0;
  t26_tmp = in2[5] * in2[10];
  t26 = t26_tmp / 4.0;
  t17_tmp_tmp = t14 + t15;
  b_t17_tmp_tmp = t17_tmp_tmp + t16;
  t86 = b_t17_tmp_tmp - t26;
  t18 = in2[4] / 2.0;
  t19 = in2[10] / 2.0;
  t20_tmp = in2[5] * in2[9];
  t20 = t20_tmp / 4.0;
  t32_tmp = in2[3] * in2[11];
  t32 = t32_tmp / 4.0;
  t21_tmp_tmp_tmp = t18 + t19;
  t21_tmp_tmp = t21_tmp_tmp_tmp + t20;
  t152 = t21_tmp_tmp - t32;
  t3 = in2[5] / 2.0;
  t23 = in2[11] / 2.0;
  t24_tmp = in2[3] * in2[10];
  t24 = t24_tmp / 4.0;
  t31_tmp = in2[4] * in2[9];
  t31 = t31_tmp / 4.0;
  t25_tmp_tmp = t3 + t23;
  b_t25_tmp_tmp = t25_tmp_tmp + t24;
  t153 = b_t25_tmp_tmp - t31;
  t122 = in2[8] + t2;
  t30_tmp = in1[4] / 4.0 + in2[8] / 2.0;
  t123 = in1[16] * t153;
  t33 = t123 / 2.0;
  t116 = in1[16] * t86;
  t34 = t116 / 2.0;
  t35 = in2[3] * in2[7] / 2.0;
  t120 = in1[16] * in2[11];
  t36 = t120 * t153 / 4.0;
  t43_tmp = in1[16] * in2[9];
  t103 = in1[16] * in2[10];
  t43 = ((((((t33 + in2[3] * in2[6] / 2.0) + in2[4] * in2[7] / 2.0) + in2[5] *
            t122 / 4.0) + in2[5] * t30_tmp / 2.0) + t120 * t13 / 4.0) + t103 *
         t86 / 4.0) - t43_tmp * t152 / 4.0;
  t44 = in2[3] * in2[4] / 2.0;
  t45 = in2[3] * in2[3];
  t46 = t45 / 4.0;
  t47 = in2[4] * in2[4];
  t48 = in2[5] * in2[5];
  t49_tmp_tmp = in1[16] * t13;
  t176 = t49_tmp_tmp / 2.0;
  t50_tmp = in1[16] * in2[3];
  t50 = t50_tmp * t86 / 4.0;
  t119 = in1[16] * t152;
  t51 = t119 / 2.0;
  t52 = in2[3] * t122 / 4.0;
  t53 = in2[3] * t30_tmp / 2.0;
  t54 = in2[4] * t122 / 4.0;
  t55 = in2[4] * t30_tmp / 2.0;
  t56 = t43_tmp * t153 / 4.0;
  t57 = t120 * t86 / 4.0;
  t59 = in2[3] * in2[5] / 2.0;
  t60 = in2[4] * in2[5] / 2.0;
  t61 = t47 / 4.0;
  t62 = t50_tmp * t13 / 4.0;
  t63_tmp = in1[16] * in2[4];
  t63 = t63_tmp * t153 / 4.0;
  t64 = t63_tmp * t13 / 4.0;
  t65_tmp = in1[16] * in2[5];
  t65 = t65_tmp * t86 / 4.0;
  t155 = t50_tmp * t152 / 4.0;
  t154 = t63_tmp * t86 / 4.0;
  t68 = in2[9] * t152 / 2.0;
  t69 = in2[10] * t86 / 2.0;
  t70 = in2[9] * t86 / 2.0;
  t71 = in2[4] * t86 / 2.0;
  t72 = in2[5] * t13 / 2.0;
  t112 = (-t10 - t11) - t12;
  t76 = (((t112 + in2[3] * t86 / 2.0) + in2[4] * t152 / 2.0) + in2[5] * t153 /
         2.0) + 1.0;
  t77 = in2[9] * t153 / 2.0;
  t78 = in2[11] * t86 / 2.0;
  t79 = in2[10] * t13 / 2.0;
  t80 = in2[10] * t153 / 2.0;
  t81 = in2[11] * t152 / 2.0;
  t130 = in2[10] * t152 / 2.0;
  t83 = in2[5] * t86 / 2.0;
  t84 = in2[5] * t152 / 2.0;
  t85 = in2[3] * t13 / 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = t43;
  t128 = in2[4] * in2[6] / 2.0;
  t87 = t43_tmp * t86 / 4.0;
  t115 = t103 * t152 / 4.0;
  out2[19] = ((((((-in2[8] - t2) - t35) - t36) + t176) + t128) + t87) + t115;
  t187 = in2[5] * in2[6] / 2.0;
  t113 = t43_tmp * t13 / 4.0;
  t114 = t120 * t152 / 4.0;
  t127 = t103 * t153 / 4.0;
  out2[20] = ((((((in2[7] - t34) - t52) - t53) + t187) + t113) + t114) + t127;
  t181 = in2[11] * t153 / 2.0;
  out2[21] = (((t112 + t70) - t130) - t181) + 1.0;
  t126 = in2[11] * t13 / 2.0;
  t3 = ((-t3 - t23) - t24) + t31;
  out2[22] = ((t3 + t68) + t69) + t126;
  out2[23] = ((t152 + t77) + t78) - t79;
  out2[24] = (((((t122 + t35) + t36) - t176) - t128) - t87) - t115;
  out2[25] = t43;
  t128 = in2[5] * in2[7] / 2.0;
  t87 = t103 * t13 / 4.0;
  out2[26] = ((((((-in2[6] - t51) - t54) - t55) - t56) - t57) + t128) + t87;
  out2[27] = ((t153 + t68) + t69) - t126;
  t115 = t112 - t70;
  out2[28] = ((t115 + t130) - t181) + 1.0;
  t126 = in2[9] * t13 / 2.0;
  t2 = ((-t14 - t15) - t16) + t26;
  out2[29] = ((t2 + t80) + t81) + t126;
  out2[30] = ((((((-in2[7] + t34) + t52) + t53) - t187) - t113) - t114) - t127;
  out2[31] = ((((((in2[6] + t51) + t54) + t55) + t56) + t57) - t128) - t87;
  out2[32] = t43;
  t128 = ((-t18 - t19) - t20) + t32;
  out2[33] = ((t128 + t77) + t78) + t79;
  out2[34] = ((t86 + t80) + t81) - t126;
  out2[35] = ((t115 - t130) + t181) + 1.0;
  out2[36] = ((t46 - t47 / 4.0) - t48 / 4.0) + 1.0;
  out2[37] = in2[5] + t44;
  out2[38] = -in2[4] + t59;
  out2[39] = 0.0;
  out2[40] = 0.0;
  out2[41] = 0.0;
  out2[42] = -in2[5] + t44;
  out2[43] = ((-t46 - t48 / 4.0) + t61) + 1.0;
  out2[44] = in2[3] + t60;
  out2[45] = 0.0;
  out2[46] = 0.0;
  out2[47] = 0.0;
  out2[48] = in2[4] + t59;
  out2[49] = -in2[3] + t60;
  out2[50] = ((-t46 + t48 / 4.0) - t61) + 1.0;
  out2[51] = 0.0;
  out2[52] = 0.0;
  out2[53] = 0.0;
  t87 = t65_tmp * t13 / 4.0;
  out2[54] = ((t33 - t87) - t154) - t155;
  t115 = t63_tmp * t152 / 4.0;
  t187 = t65_tmp * t153 / 4.0;
  out2[55] = ((t176 + t50) - t115) + t187;
  t113 = t65_tmp * t152 / 4.0;
  out2[56] = ((-t34 + t62) - t63) - t113;
  out2[57] = t76;
  t114 = in2[3] * t152 / 2.0;
  out2[58] = ((t3 - t71) - t72) + t114;
  t127 = in2[4] * t13 / 2.0;
  t181 = in2[3] * t153 / 2.0;
  out2[59] = ((t152 - t83) + t127) + t181;
  out2[60] = ((t50 - t176) - t115) - t187;
  t115 = t33 + t155;
  out2[61] = (t115 + t154) - t87;
  t187 = t50_tmp * t153 / 4.0;
  out2[62] = ((-t51 + t64) + t65) + t187;
  out2[63] = ((t153 + t71) + t72) - t114;
  out2[64] = t76;
  t114 = in2[4] * t153 / 2.0;
  out2[65] = ((t2 - t84) - t85) + t114;
  out2[66] = ((t34 + t62) + t63) - t113;
  out2[67] = ((t51 + t64) + t65) - t187;
  out2[68] = (t115 - t154) + t87;
  out2[69] = ((t128 + t83) - t127) - t181;
  out2[70] = ((t86 + t84) + t85) - t114;
  out2[71] = t76;
  t86 = in1[16] / 4.0;
  t87 = t50_tmp / 8.0;
  t83 = t116 / 4.0;
  t84 = t63_tmp * in2[11] / 16.0;
  t90 = t63_tmp / 8.0;
  t91 = t119 / 4.0;
  t92 = t65_tmp * in2[9] / 16.0;
  t95 = (in2[7] / 2.0 + t103 * in2[11] / 8.0) - t43_tmp / 4.0;
  t99 = (in2[6] / 2.0 + t103 / 4.0) + t43_tmp * in2[11] / 8.0;
  t100 = t120 / 8.0;
  t101 = t123 / 4.0;
  t102 = t50_tmp * in2[10] / 16.0;
  t103 /= 8.0;
  t43 = in2[9] * in2[9];
  t44 = in2[10] * in2[10];
  t53 = in2[11] * in2[11];
  t18 = (((t30_tmp + t86) + in1[16] * t53 / 16.0) - in1[16] * t43 / 16.0) - in1
    [16] * t44 / 16.0;
  t2 = t49_tmp_tmp / 4.0;
  t69 = t50_tmp * in2[9] / 16.0;
  t70 = t63_tmp * in2[10] / 16.0;
  t112 = t65_tmp * in2[11] / 16.0;
  t113 = t43_tmp / 8.0;
  t114 = t65_tmp * in2[10] / 16.0;
  t187 = (t87 + t83) + t84;
  t115 = (t187 + t113) + t114;
  t35 = -t86 + t2;
  t116 = ((t35 + t69) - t70) + t112;
  t33 = t63_tmp / 4.0;
  t34 = t50_tmp * in2[5] / 8.0;
  t119 = t33 + t34;
  t126 = t50_tmp * in2[11] / 16.0;
  t181 = t90 + t91;
  t120 = ((t181 - t92) + t103) - t126;
  t14 = t65_tmp / 8.0;
  t122 = t63_tmp * in2[9] / 16.0;
  t13 = t100 + t101;
  t3 = t13 + t102;
  t123 = (t3 + t14) + t122;
  t36 = t65_tmp / 4.0;
  t68 = t50_tmp * in2[4] / 8.0;
  t85 = t36 - t68;
  t127 = in1[16] * t45 / 16.0;
  t152 = in1[16] * t47 / 16.0;
  t153 = in1[16] * t48 / 16.0;
  t128 = ((t86 + t127) - t152) - t153;
  t81 = (((t86 + t2) + t69) + t70) + t112;
  t130 = in2[3] * in2[19] / 2.0;
  t79 = (t3 - t14) - t122;
  t80 = t95 * in2[15];
  t77 = (t187 - t113) - t114;
  t78 = in2[3] * in2[15] / 2.0;
  t76 = ((t181 + t92) - t103) - t126;
  t72 = ((t13 - t102) + t14) - t122;
  t14 = t50_tmp / 4.0;
  t3 = t63_tmp * in2[5] / 8.0;
  t71 = t14 - t3;
  t154 = ((t35 - t69) + t70) + t112;
  t155 = t36 + t68;
  t65 = (((-t87 + t83) + t84) + t113) - t114;
  t2 = t86 - t127;
  t63 = (t2 + t152) - t153;
  t64 = in2[3] * in2[20] / 2.0;
  t56 = (((-t90 + t91) + t92) + t103) - t126;
  t57 = t18 * in2[15];
  t59 = in2[4] * in2[20] / 2.0;
  t60 = t72 * in2[21];
  t61 = t65 * in2[23];
  t62 = t18 * in2[16];
  t35 = (((((in2[3] * in2[18] / 2.0 + in2[4] * in2[19] / 2.0) + in2[5] * in2[20]
            / 2.0) + t18 * in2[17]) + t99 * in2[15]) + t95 * in2[16]) + t81 *
    in2[23];
  t54 = (t35 + t77 * in2[22]) - t76 * in2[21];
  t55 = in2[4] * in2[16] / 2.0;
  t52 = (t2 - t152) + t153;
  t51 = t33 - t34;
  t46 = t14 + t3;
  t13 = in2[9] * in2[11] / 4.0;
  t176 = t19 - t13;
  t3 = in2[9] * in2[10] / 4.0;
  t50 = t23 + t3;
  t122 = t43 / 8.0;
  t14 = t44 / 8.0;
  t181 = t53 / 8.0;
  t2 = t122 - t14;
  t44 = (t2 - t181) + 0.5;
  t34 = ((t45 / 8.0 + t47 / 8.0) + t48 / 8.0) + 0.5;
  t187 = in2[10] * in2[11] / 4.0;
  t43 = t15 + t187;
  t33 = t23 - t3;
  t18 = (t2 + t181) - 0.5;
  t86 = (t17_tmp_tmp - t26) * in2[16];
  t126 = (t13_tmp - 1.0) * in2[17];
  t127 = (((t15 + t16) - t26) * in2[15] + ((t19 + t20) - t32) * in2[16]) + ((t23
    + t24) - t31) * in2[17];
  t114 = ((t122 + t14) - t181) - 0.5;
  t113 = t15 - t187;
  t112 = t19 + t13;
  t69 = b_t17_tmp_tmp * in2[17];
  t70 = t34 * in2[22];
  t68 = (t21_tmp_tmp_tmp - t32) * in2[17];
  t36 = ((t11 + t12) - 1.0) * in2[15];
  memset(&out3[0], 0, 18U * sizeof(real_T));
  out3[18] = (t35 + in2[22] * ((((t87 + t83) + t84) - in1[16] * in2[9] / 8.0) -
    in1[16] * in2[5] * in2[10] / 16.0)) - in2[21] * ((((t90 + t91) + t92) - in1
    [16] * in2[10] / 8.0) - in1[16] * in2[3] * in2[11] / 16.0);
  t181 = in2[4] * in2[18] / 2.0;
  t14 = t99 * in2[16];
  t122 = t115 * in2[21];
  t13 = t120 * in2[22];
  out3[19] = ((((((-t130 - t80) - in2[20]) + t181) + t14) + t122) + t13) - t79 *
    in2[23];
  t35 = in2[5] * in2[18] / 2.0;
  t2 = t99 * in2[17];
  t3 = t116 * in2[21];
  t187 = t123 * in2[22];
  out3[20] = ((((((-t64 - t57) + in2[19]) + t35) + t2) + t3) + t187) + t56 *
    in2[23];
  out3[21] = (((in2[3] * in2[21] / 2.0 + t176 * in2[16]) + t50 * in2[17]) -
              t24_tmp * in2[23] / 4.0) + t32_tmp * in2[22] / 4.0;
  out3[22] = (((in2[3] * in2[22] / 2.0 - t43 * in2[16]) - t18 * in2[17]) +
              t10_tmp * in2[23] / 4.0) - t32_tmp * in2[21] / 4.0;
  out3[23] = (((in2[3] * in2[23] / 2.0 + t114 * in2[16]) - t113 * in2[17]) -
              t10_tmp * in2[22] / 4.0) + t24_tmp * in2[21] / 4.0;
  out3[24] = ((((((t130 + t80) + in2[20]) - t181) - t14) - t122) - t13) + in2[23]
    * ((((t100 + t101) + t102) - in1[16] * in2[5] / 8.0) - in1[16] * in2[4] *
       in2[9] / 16.0);
  out3[25] = t54;
  t181 = in2[5] * in2[19] / 2.0;
  t14 = t95 * in2[17];
  t122 = t154 * in2[22];
  out3[26] = ((((((-t59 - t60) - t61) - t62) - in2[18]) + t181) + t14) + t122;
  out3[27] = (((in2[4] * in2[21] / 2.0 - t176 * in2[15]) - t44 * in2[17]) -
              t11_tmp * in2[23] / 4.0) + t16_tmp * in2[22] / 4.0;
  out3[28] = (((in2[4] * in2[22] / 2.0 + t43 * in2[15]) + t33 * in2[17]) +
              t31_tmp * in2[23] / 4.0) - t16_tmp * in2[21] / 4.0;
  out3[29] = (((in2[4] * in2[23] / 2.0 - t114 * in2[15]) - t112 * in2[17]) -
              t31_tmp * in2[22] / 4.0) + t11_tmp * in2[21] / 4.0;
  out3[30] = ((((((t64 + t57) - in2[19]) - in2[23] * ((((-t90 + t91) + t92) +
    t103) - in1[16] * in2[3] * in2[11] / 16.0)) - t35) - t2) - t3) - t187;
  out3[31] = ((((((t59 + t60) + t61) + t62) + in2[18]) - t181) - t14) - t122;
  out3[32] = t54;
  out3[33] = (((in2[5] * in2[21] / 2.0 - t50 * in2[15]) + t44 * in2[16]) -
              t26_tmp * in2[23] / 4.0) + t12_tmp * in2[22] / 4.0;
  out3[34] = (((in2[5] * in2[22] / 2.0 - t33 * in2[16]) + t18 * in2[15]) +
              t20_tmp * in2[23] / 4.0) - t12_tmp * in2[21] / 4.0;
  out3[35] = (((in2[5] * in2[23] / 2.0 + t113 * in2[15]) + t112 * in2[16]) -
              t20_tmp * in2[22] / 4.0) + t26_tmp * in2[21] / 4.0;
  t181 = in2[5] * in2[17] / 2.0;
  out3[36] = (t78 - t55) - t181;
  t14 = in2[3] * in2[16] / 2.0 + in2[4] * in2[15] / 2.0;
  out3[37] = t14 + in2[17];
  t122 = in2[3] * in2[17] / 2.0 + in2[5] * in2[15] / 2.0;
  out3[38] = t122 - in2[16];
  out3[39] = 0.0;
  out3[40] = 0.0;
  out3[41] = 0.0;
  out3[42] = t14 - in2[17];
  out3[43] = (-t78 + t55) - t181;
  t14 = in2[4] * in2[17] / 2.0 + in2[5] * in2[16] / 2.0;
  out3[44] = t14 + in2[15];
  out3[45] = 0.0;
  out3[46] = 0.0;
  out3[47] = 0.0;
  out3[48] = t122 + in2[16];
  out3[49] = t14 - in2[15];
  out3[50] = (-t78 - t55) + t181;
  out3[51] = 0.0;
  out3[52] = 0.0;
  out3[53] = 0.0;
  out3[54] = (((-in2[15] * ((((t90 + t91) + t92) - t103) - in1[16] * in2[3] *
    in2[11] / 16.0) - t115 * in2[16]) - t116 * in2[17]) - t119 * in2[21]) + t128
    * in2[23];
  out3[55] = (((t115 * in2[15] - t76 * in2[16]) + t72 * in2[17]) + t71 * in2[21])
    + t155 * in2[23];
  out3[56] = (((t116 * in2[15] - t76 * in2[17]) - t72 * in2[16]) - t52 * in2[21])
    - t51 * in2[23];
  out3[57] = t127;
  t181 = t21_tmp_tmp * in2[15];
  t14 = t34 * in2[23];
  out3[58] = ((-t86 - t126) + t181) + t14;
  t122 = (t25_tmp_tmp - t31) * in2[15];
  t13 = ((t10 + t12) - 1.0) * in2[16];
  out3[59] = ((-t69 - t70) + t122) + t13;
  out3[60] = (((-t120 * in2[16] - t123 * in2[17]) - t119 * in2[22]) - t85 * in2
              [23]) + t77 * in2[15];
  out3[61] = (((t120 * in2[15] + t77 * in2[16]) - t154 * in2[17]) + t71 * in2[22])
    + t63 * in2[23];
  out3[62] = (((t123 * in2[15] + t77 * in2[17]) + t154 * in2[16]) - t52 * in2[22])
    + t46 * in2[23];
  out3[63] = ((t86 + t126) - t181) - t14;
  out3[64] = t127;
  t181 = t34 * in2[21];
  t14 = b_t25_tmp_tmp * in2[16];
  out3[65] = ((-t68 - t36) + t181) + t14;
  out3[66] = ((((t119 * in2[23] + t81 * in2[15]) - t85 * in2[22]) + t79 * in2[16])
              + t128 * in2[21]) - t56 * in2[17];
  out3[67] = ((((t81 * in2[16] - t79 * in2[15]) - t71 * in2[23]) + t65 * in2[17])
              + t155 * in2[21]) + t63 * in2[22];
  out3[68] = ((((t81 * in2[17] - t65 * in2[16]) + t56 * in2[15]) - t51 * in2[21])
              + t52 * in2[23]) + t46 * in2[22];
  out3[69] = ((t69 + t70) - t122) - t13;
  out3[70] = ((t68 + t36) - t181) - t14;
  out3[71] = t127;
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF3.c) */
