/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vd_matF.c
 *
 * Code generation for function 'fj_vd_matF'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "fj_vd_matF.h"

/* Function Definitions */
void fj_vd_matF(const real_T in1[34], const real_T in2[36], real_T s, real_T
                fj_vd_mat[324])
{
  (void)in2;
  (void)s;

  /* FJ_VD_MATF */
  /*     FJ_VD_MAT = FJ_VD_MATF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 00:06:25 */
  fj_vd_mat[0] = -in1[5];
  memset(&fj_vd_mat[1], 0, 18U * sizeof(real_T));
  fj_vd_mat[19] = -in1[6];
  memset(&fj_vd_mat[20], 0, 18U * sizeof(real_T));
  fj_vd_mat[38] = -in1[7];
  memset(&fj_vd_mat[39], 0, 18U * sizeof(real_T));
  fj_vd_mat[57] = -in1[8];
  memset(&fj_vd_mat[58], 0, 18U * sizeof(real_T));
  fj_vd_mat[76] = -in1[9];
  memset(&fj_vd_mat[77], 0, 18U * sizeof(real_T));
  fj_vd_mat[95] = -in1[10];
  memset(&fj_vd_mat[96], 0, 18U * sizeof(real_T));
  fj_vd_mat[114] = -in1[5];
  memset(&fj_vd_mat[115], 0, 18U * sizeof(real_T));
  fj_vd_mat[133] = -in1[6];
  memset(&fj_vd_mat[134], 0, 18U * sizeof(real_T));
  fj_vd_mat[152] = -in1[7];
  memset(&fj_vd_mat[153], 0, 18U * sizeof(real_T));
  fj_vd_mat[171] = -in1[8];
  memset(&fj_vd_mat[172], 0, 18U * sizeof(real_T));
  fj_vd_mat[190] = -in1[9];
  memset(&fj_vd_mat[191], 0, 18U * sizeof(real_T));
  fj_vd_mat[209] = -in1[10];
  memset(&fj_vd_mat[210], 0, 18U * sizeof(real_T));
  fj_vd_mat[228] = -in1[5];
  memset(&fj_vd_mat[229], 0, 18U * sizeof(real_T));
  fj_vd_mat[247] = -in1[6];
  memset(&fj_vd_mat[248], 0, 18U * sizeof(real_T));
  fj_vd_mat[266] = -in1[7];
  memset(&fj_vd_mat[267], 0, 18U * sizeof(real_T));
  fj_vd_mat[285] = -in1[8];
  memset(&fj_vd_mat[286], 0, 18U * sizeof(real_T));
  fj_vd_mat[304] = -in1[9];
  memset(&fj_vd_mat[305], 0, 18U * sizeof(real_T));
  fj_vd_mat[323] = -in1[10];
}

/* End of code generation (fj_vd_matF.c) */
