/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF2.c
 *
 * Code generation for function 'sprdmpF2'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "sprdmpF2.h"

/* Function Definitions */
void sprdmpF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
              real_T s, real_T out1[6], real_T *out2, real_T *out3, real_T *out4,
              real_T *out5, real_T out6[6], real_T out7[6], real_T *out8)
{
  int32_T i;
  static const int8_T iv0[6] = { 0, 1, 0, 0, 0, 0 };

  real_T t2;
  real_T t16;
  real_T t4;
  real_T a;
  (void)sp;
  (void)s;
  for (i = 0; i < 6; i++) {
    out1[i] = iv0[i];
  }

  /* SPRDMPF2 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 22:47:10 */
  t2 = 1.0 / in1[33];
  t16 = muDoubleScalarCos(in1[20]);
  t4 = 1.0 / in1[4];
  a = muDoubleScalarSin(in1[20]);
  t16 = t2 * (in1[2] * in1[2] - in1[3] * in1[3]) - in1[18] * in1[18] * (1.0 / (a
    * a)) * (in1[33] * in1[33] * (t16 * t16) - 1.0) * 6.0;
  *out2 = in1[1] * in2[1] * t2 * t4 * t16 * 3.1415926535897931 / 3.0;
  *out3 = -in1[6] * in2[7];
  *out4 = 0.0;
  *out5 = in2[1];
  out6[0] = 0.0;
  out6[1] = in1[1] * t2 * t4 * t16 * 3.1415926535897931 * -0.33333333333333331;
  out6[2] = 0.0;
  out6[3] = 0.0;
  out6[4] = 0.0;
  out6[5] = 0.0;
  out7[0] = 0.0;
  out7[1] = -in1[6];
  out7[2] = 0.0;
  out7[3] = 0.0;
  out7[4] = 0.0;
  out7[5] = 0.0;
  *out8 = 1.0;
}

/* End of code generation (sprdmpF2.c) */
