/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: romF.c
 *
 * MATLAB Coder version            : 4.2
 * C/C++ source code generated on  : 14-Oct-2020 16:42:47
 */

/* Include Files */
#include <string.h>
#include "EOM.h"
#include "EOM_input.h"
#include "romF.h"

/* Function Definitions */

/*
 * ROMF
 *     [OUT1,OUT2] = ROMF(IN1,IN2,S)
 * Arguments    : const double in1[58]
 *                double out1[4]
 *                double out2[68]
 * Return Type  : void
 */
void romF(const double in1[58], double out1[4], double out2[68])
{
  double t2;
  double t3;

  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     14-Oct-2020 02:35:51 */
  t2 = in1[45] + in1[39];
  t3 = in1[47] + in1[40];
  out1[0] = 0.0;
  out1[1] = 0.0;
  out1[2] = t3;
  out1[3] = t2;
  memset(&out2[0], 0, 66U * sizeof(double));
  out2[66] = t3;
  out2[67] = t2;
}

/*
 * File trailer for romF.c
 *
 * [EOF]
 */
