/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vd_matF.c
 *
 * Code generation for function 'fj_vd_matF'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "fj_vd_matF.h"

/* Function Definitions */
void fj_vd_matF(const real_T in1[34], const real_T in2[24], real_T s, real_T
                fj_vd_mat[144])
{
  (void)in1;
  (void)in2;
  (void)s;

  /* FJ_VD_MATF */
  /*     FJ_VD_MAT = FJ_VD_MATF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 15:17:27 */
  memset(&fj_vd_mat[0], 0, 144U * sizeof(real_T));
}

/* End of code generation (fj_vd_matF.c) */
