/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF4.c
 *
 * Code generation for function 'cnstF4'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "cnstF4.h"

/* Function Definitions */
void cnstF4(const real_T in1[6], const real_T in2[224], real_T s, real_T out1
            [106], real_T out2[106], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t7;
  real_T t10;
  real_T t13;
  real_T t16;
  (void)in1;
  (void)s;

  /* CNSTF4 */
  /*     [OUT1,OUT2,OUT3] = CNSTF4(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jul-2019 09:16:42 */
  t2 = in2[105] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t2 = muDoubleScalarSin(t2);
  t7 = t3 * 0.038 - t2 * 0.03;
  t10 = t3 * 0.019 - t2 * 0.015;
  t13 = t3 * 0.03 + t2 * 0.038;
  t16 = t3 * 0.015 + t2 * 0.019;
  memset(&out1[0], 0, 98U * sizeof(real_T));
  out1[98] = 1.0;
  out1[99] = 0.0;
  out1[100] = 0.0;
  out1[101] = 0.0;
  out1[102] = 0.0;
  out1[103] = 0.0;
  out1[104] = 0.0;
  out1[105] = ((t2 * t7 / 2.0 + t2 * t10) + t3 * t13 / 2.0) + t3 * t16;
  memset(&out2[0], 0, 105U * sizeof(real_T));
  out2[105] = in2[217] * (((((t3 * t7 / 4.0 + t3 * t10) - t2 * t13 / 4.0) - t2 *
    t16) + t3 * (t3 * 0.0095 - t2 * 0.0075)) - t2 * (t3 * 0.0075 + t2 * 0.0095));
  *out3 = 0.0;
}

/* End of code generation (cnstF4.c) */
