/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF25.c
 *
 * Code generation for function 'sprdmpF25'
 *
 */

/* Include files */
#include "sprdmpF25.h"
#include "EOM_eq_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo ed_emlrtRSI = { 51, /* lineNo */
  "sprdmpF25",                         /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\sprdmpF25.m"/* pathName */
};

/* Function Definitions */
void sprdmpF25(const emlrtStack *sp, const real_T in1[34], const real_T in2[48],
               real_T out2[6], real_T out3[6], real_T out4[6], real_T *out6)
{
  emlrtStack st;
  real_T t13;
  real_T t14;
  real_T t16;
  real_T t20;
  real_T t22;
  real_T t32;
  real_T t33;
  real_T t4;
  real_T t6;
  real_T t8;
  real_T t9;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF25 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = SPRDMPF25(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     26-Feb-2021 21:07:23 */
  t33 = muDoubleScalarCos(in1[20]);
  t32 = muDoubleScalarSin(in1[20]);
  t4 = in1[33] * in1[33];
  t6 = in1[18] * in1[18];
  t8 = in1[2] * in1[2];
  t9 = in1[3] * in1[3];
  t13 = 1.0 / in1[4];
  t14 = 1.0 / in1[33];
  st.site = &ed_emlrtRSI;
  if (in1[33] < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t20 = 1.0 / muDoubleScalarSqrt(in1[33]);
  t16 = 1.0 / (t32 * t32);
  t22 = t4 * (t33 * t33);
  t32 = t14 * (t8 + -t9) + -(t6 * t16 * (t22 - 1.0) * 6.0);
  t33 = 1.0 / t4 * (t8 * t8 + -(t9 * t9)) + t6 * t6 * (t16 * t16) * ((t22 - 1.0)
    * (t22 - 1.0)) * 6.0;
  out2[0] = in1[1] * in2[0] * t13 * t14 * t32 * 3.1415926535897931 *
    1.3333333333333333;
  out2[1] = in1[1] * in2[1] * t13 * t14 * t32 * 3.1415926535897931 *
    1.3333333333333333;
  out2[2] = in1[1] * t13 * t14 * t32 * 3.1415926535897931 * (in1[4] / 4.0 - in2
    [2]) * -4.0;
  t32 = t33 * 3.1415926535897931 / 4.0 - in1[19] * in1[19] * t6 * t14 * t16 *
    (t22 - 1.0) * 3.1415926535897931 * 3.0;
  out2[3] = in1[1] * in2[3] * t13 * t14 * t32 * 8.0;
  out2[4] = in1[1] * in2[4] * t13 * t14 * t32 * 8.0;
  out2[5] = in1[1] * in2[5] * t13 * t14 * t33 * 3.1415926535897931 *
    1.3333333333333333;
  out3[0] = -in1[5] * in2[24];
  out3[1] = -in1[6] * in2[25];
  out3[2] = -in1[7] * in2[26];
  out3[3] = in1[8] * in2[27] * -2.0;
  out3[4] = in1[9] * in2[28] * -2.0;
  out3[5] = in1[10] * in2[29] * -2.0;
  out4[0] = 0.0;
  out4[1] = 0.0;
  out4[2] = -t6 * t16 * (t22 - 1.0) * 3.1415926535897931 * (((((in1[21] + in1[22])
    + in1[23]) + in1[24]) + in1[25]) + in1[26]);
  t33 = in1[23] * in1[19] * t6 * t16 * t20 * (t22 - 1.0) * 3.1415926535897931;
  t4 = in1[24] * in1[19] * t6 * t16 * t20 * (t22 - 1.0) * 3.1415926535897931;
  t8 = in1[25] * in1[19] * t6 * t16 * t20 * (t22 - 1.0) * 3.1415926535897931;
  t9 = in1[26] * in1[19] * t6 * t16 * t20 * (t22 - 1.0) * 3.1415926535897931;
  t13 = in1[21] * in1[19] * t6 * t16 * t20;
  t32 = in1[22] * in1[19] * t6 * t16 * t20;
  out4[3] = ((((t13 * (t22 - 1.0) * 3.1415926535897931 * -0.93771626297577859 -
                t32 * (t22 - 1.0) * 3.1415926535897931 * 0.93771626297577859) +
               t33 * 0.167999098695029) + t4 * 0.76971716428074954) + t8 *
             0.76971716428074932) + t9 * 0.16799909869502891;
  out4[4] = ((((t33 * 0.9857871488499218 + t4 * 0.63838506170774523) - t8 *
               0.63838506170774545) - t9 * 0.9857871488499218) - t13 *
             8.3666002653407556 * (t22 - 1.0) * 3.1415926535897931 *
             0.041522491349480967) + t32 * 8.3666002653407556 * (t22 - 1.0) *
    3.1415926535897931 * 0.041522491349480967;
  out4[5] = 0.0;
  *out6 = 1.0;
}

/* End of code generation (sprdmpF25.c) */
