/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_kF.c
 *
 * Code generation for function 'fj_kF'
 *
 */

/* Include files */
#include "fj_kF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Function Definitions */
void fj_kF(const real_T in1[34], const real_T in2[36], real_T out1[18])
{
  real_T a;
  real_T t13;
  real_T t14;
  real_T t16;
  real_T t20;
  real_T t32;
  real_T t33;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t8;
  real_T t9;

  /* FJ_KF */
  /*     OUT1 = FJ_KF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     14-Jun-2021 23:16:02 */
  a = muDoubleScalarCos(in1[20]);
  t33 = muDoubleScalarSin(in1[20]);
  t4 = in1[33] * in1[33];
  t5 = in1[19] * in1[19];
  t6 = in1[18] * in1[18];
  t8 = in1[2] * in1[2];
  t9 = in1[3] * in1[3];
  t13 = 1.0 / in1[4];
  t14 = 1.0 / in1[33];
  t16 = 1.0 / (t33 * t33);
  t20 = t4 * (a * a);
  t32 = t14 * (t8 + -t9) + -(t6 * t16 * (t20 - 1.0) * 6.0);
  t33 = 1.0 / t4 * (t8 * t8 + -(t9 * t9)) + t6 * t6 * (t16 * t16) * ((t20 - 1.0)
    * (t20 - 1.0)) * 6.0;
  a = t33 * 3.1415926535897931 / 4.0 + -(t5 * t6 * t14 * t16 * (t20 - 1.0) *
    3.1415926535897931 * 3.0);
  out1[0] = in1[1] * in2[0] * t13 * t14 * t32 * 3.1415926535897931;
  out1[1] = in1[1] * in2[1] * t13 * t14 * t32 * 3.1415926535897931;
  out1[2] = in1[1] * in2[2] * t13 * t14 * t32 * 3.1415926535897931 * 3.0;
  out1[3] = in1[1] * in2[3] * t13 * t14 * a * 3.0;
  out1[4] = in1[1] * in2[4] * t13 * t14 * a * 3.0;
  t33 = in1[33] * t5 * t6 * t16 * (t20 - 1.0) * 3.1415926535897931 - t33 *
    3.1415926535897931 / 2.0;
  out1[5] = -in1[1] * in2[5] * t13 * t14 * t33;
  out1[6] = in1[1] * in2[6] * t13 * t14 * t32 * 3.1415926535897931;
  out1[7] = in1[1] * in2[7] * t13 * t14 * t32 * 3.1415926535897931;
  out1[8] = in1[1] * in2[8] * t13 * t14 * t32 * 3.1415926535897931 * 3.0;
  out1[9] = in1[1] * in2[9] * t13 * t14 * a * 3.0;
  out1[10] = in1[1] * in2[10] * t13 * t14 * a * 3.0;
  out1[11] = -in1[1] * in2[11] * t13 * t14 * t33;
  out1[12] = in1[1] * in2[12] * t13 * t14 * t32 * 3.1415926535897931;
  out1[13] = in1[1] * in2[13] * t13 * t14 * t32 * 3.1415926535897931;
  out1[14] = in1[1] * in2[14] * t13 * t14 * t32 * 3.1415926535897931 * 3.0;
  out1[15] = in1[1] * in2[15] * t13 * t14 * a * 3.0;
  out1[16] = in1[1] * in2[16] * t13 * t14 * a * 3.0;
  out1[17] = -in1[1] * in2[17] * t13 * t14 * t33;
}

/* End of code generation (fj_kF.c) */
