/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
            real_T s, real_T r_jtip[18])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t13;
  real_T t16;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t23;
  real_T t25;
  real_T t30;
  real_T t33;
  real_T t36;
  real_T t39;
  real_T t43;
  real_T t44;
  real_T t45;
  real_T t55;
  real_T t65;
  real_T t56;
  real_T t57;
  real_T t63;
  real_T t64;
  real_T t67;
  real_T t68;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T t77;
  real_T t85;
  real_T t80;
  real_T t82;
  real_T t84;
  real_T t86;
  real_T t88;
  real_T t99;
  real_T t89;
  real_T t103;
  real_T t104;
  real_T b_in2[18];
  int32_T i0;
  int32_T i1;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     16-Jan-2019 13:23:15 */
  t2 = in2[5] * 0.5;
  t3 = in2[3] * 0.5;
  t4 = in2[4] * 0.5;
  t5 = muDoubleScalarSin(t3);
  t6 = muDoubleScalarSin(t4);
  t7 = muDoubleScalarSin(t2);
  t8 = muDoubleScalarCos(t3);
  t3 = muDoubleScalarCos(t4);
  t4 = muDoubleScalarCos(t2);
  t13 = t7 * t8 * t3 + t5 * t6 * t4;
  t16 = t5 * t3 * t4 + t6 * t7 * t8;
  t2 = t5 * t7 * t3;
  t19 = t5 * t6 * t7 - t8 * t3 * t4;
  t3 = t6 * t8 * t4;
  t20 = t2 - t3;
  t21 = in1[4] * 0.5;
  t23 = t2 - t3;
  t25 = -t2 + t3;
  t3 = in2[8] + t21;
  t30 = (in2[6] * t25 + in2[7] * t13) + t16 * t3;
  t33 = (in2[6] * t19 + in2[7] * t16) - t13 * t3;
  t36 = (in2[6] * t13 + t19 * t3) - in2[7] * t25;
  t39 = (in2[7] * t19 + t25 * t3) - in2[6] * t16;
  t43 = t25 * t30;
  t44 = t16 * t39;
  t45 = t19 * t33;
  t2 = in2[11] * 0.5;
  t3 = in2[9] * 0.5;
  t4 = in2[10] * 0.5;
  t5 = muDoubleScalarCos(t4);
  t6 = muDoubleScalarCos(t2);
  t7 = muDoubleScalarSin(t3);
  t8 = muDoubleScalarCos(t3);
  t4 = muDoubleScalarSin(t4);
  t3 = muDoubleScalarSin(t2);
  t55 = t5 * t6 * t8;
  t65 = t7 * t4 * t3;
  t56 = t55 - t65;
  t57 = t5 * t7 * t3;
  t2 = t5 * t6 * t7 + t8 * t4 * t3;
  t63 = t5 * t8 * t3 + t6 * t7 * t4;
  t4 *= t6 * t8;
  t64 = t57 - t4;
  t67 = t13 * t30;
  t68 = t25 * t36;
  t69 = t19 * t39;
  t70 = t13 * t63;
  t71 = t16 * t2;
  t72 = t13 * t2;
  t73 = t25 * t56;
  t74 = t19 * t64;
  t75 = t13 * t64;
  t76 = t16 * t56;
  t77 = t25 * t63;
  t5 = t25 * t2;
  t7 = t19 * t63;
  t85 = t19 * t2;
  t80 = ((t75 + t76) + t77) - t85;
  t3 = t13 * t56;
  t82 = ((t5 + t7) + t16 * t64) - t3;
  t84 = ((t70 + t71) + t19 * (t55 - t65)) - t25 * t64;
  t86 = ((t75 + t76) + t77) - t85;
  t88 = ((t5 + t7) - t3) + t16 * (t57 - t4);
  t99 = t16 * t63;
  t89 = ((t72 + t73) + t74) - t99;
  t3 = t16 * t30;
  t4 = t13 * t33;
  t2 = t19 * t36;
  t5 = t13 * t36;
  t7 = (((in2[0] + t43) + t44) + t45) - t5;
  t8 = t16 * t33;
  t6 = (((in2[1] + t67) + t68) + t69) - t8;
  t55 = t25 * t39;
  t65 = ((((in2[2] + t21) + t3) + t4) + t2) - t55;
  t57 = t84 * t84;
  t30 = ((t75 + t76) + t77) - t85;
  t103 = t88 * t88;
  t104 = ((t72 + t73) + t74) - t99;
  b_in2[0] = in2[0];
  b_in2[1] = t7;
  b_in2[2] = t7;
  b_in2[3] = in2[1];
  b_in2[4] = t6;
  b_in2[5] = t6;
  b_in2[6] = in2[2] + t21;
  b_in2[7] = t65;
  b_in2[8] = t65;
  b_in2[9] = (in2[0] - in1[4] * t13 * t19) - in1[4] * t16 * t20;
  b_in2[10] = (((((in2[0] + t43) + t44) + t45) - t13 * t36) + in1[4] * t82 *
               (((t70 + t71) + t19 * t56) - t25 * t64)) + in1[4] * t80 * (((t72
    + t73) + t74) - t16 * t63);
  b_in2[11] = (((((in2[0] + t43) + t44) + t45) - t5) + in1[16] * t84 * t88 * 2.0)
    + in1[16] * (((t75 + t76) + t77) - t85) * (((t72 + t73) + t74) - t99) * 2.0;
  b_in2[12] = (in2[1] + in1[4] * t13 * t16) - in1[4] * t19 * t20;
  b_in2[13] = (((((in2[1] + t67) + t68) + t69) - t16 * t33) + in1[4] * t84 *
               (((t72 + t73) + t74) - t16 * t63)) - in1[4] * t80 * t82;
  b_in2[14] = (((((in2[1] + t67) + t68) + t69) - t8) - in1[16] * t80 * t88 * 2.0)
    + in1[16] * t84 * (((t72 + t73) + t74) - t99) * 2.0;
  b_in2[15] = ((((in2[2] + t21) - in1[4] * (t13 * t13) * 0.5) + in1[4] * (t16 *
    t16) * 0.5) + in1[4] * (t19 * t19) * 0.5) - in1[4] * (t23 * t23) * 0.5;
  b_in2[16] = ((((((((in2[2] + t21) + t3) + t4) + t2) + in1[4] * t57 * 0.5) -
                 in1[4] * t103 * 0.5) - t25 * t39) + in1[4] * (t86 * t86) * 0.5)
    - in1[4] * (t89 * t89) * 0.5;
  b_in2[17] = ((((((((in2[2] + t21) + t3) + t4) + t2) - t55) + in1[16] * t57) -
                in1[16] * t103) + in1[16] * (t30 * t30)) - in1[16] * (t104 *
    t104);
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 3; i1++) {
      r_jtip[i1 + 3 * i0] = b_in2[i1 + 3 * i0];
    }
  }
}

/* End of code generation (rjtipF.c) */
