function out1 = sprdmpDir10(in1,in2,s,ds,t_sym)
%SPRDMPDIR10
%    OUT1 = SPRDMPDIR10(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-May-2021 00:11:17

out1 = 1.0;
