function out1 = sprdmpTtu3(in1,in2,s,ds,t_sym)
%SPRDMPTTU3
%    OUT1 = SPRDMPTTU3(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-May-2021 00:11:27

out1 = zeros(0,0);
