function out1 = sprdmpDl3(in1,in2,s,ds,t_sym)
%SPRDMPDL3
%    OUT1 = SPRDMPDL3(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-May-2021 00:17:16

q3 = in2(3,:);
out1 = q3;
