function out1 = sprdmpDl16(in1,in2,s,ds,t_sym)
%SPRDMPDL16
%    OUT1 = SPRDMPDL16(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    08-May-2021 00:17:16

q16 = in2(16,:);
out1 = q16;
