/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include "massF1.h"
#include "EOM_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Variable Definitions */
static emlrtRSInfo eb_emlrtRSI = { 101,/* lineNo */
  "massF1",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\Tutorial\\eom\\massF1.m"/* pathName */
};

/* Function Definitions */
void massF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[30],
            real_T s, real_T out1[36], real_T out2[90], real_T out3[90], real_T
            out4[6])
{
  emlrtStack st;
  real_T t10;
  real_T t102;
  real_T t11;
  real_T t12;
  real_T t130;
  real_T t131;
  real_T t132;
  real_T t133;
  real_T t134;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t138;
  real_T t139;
  real_T t140;
  real_T t141;
  real_T t142;
  real_T t143;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t147;
  real_T t150;
  real_T t151;
  real_T t152;
  real_T t153;
  real_T t154;
  real_T t155;
  real_T t156;
  real_T t157;
  real_T t158;
  real_T t159;
  real_T t16;
  real_T t160;
  real_T t161;
  real_T t163;
  real_T t165;
  real_T t166;
  real_T t167;
  real_T t168;
  real_T t169;
  real_T t170;
  real_T t171;
  real_T t172;
  real_T t173;
  real_T t174;
  real_T t18;
  real_T t19;
  real_T t2;
  real_T t20;
  real_T t202;
  real_T t203;
  real_T t204;
  real_T t205;
  real_T t206;
  real_T t207;
  real_T t208;
  real_T t209;
  real_T t21;
  real_T t210;
  real_T t22;
  real_T t220;
  real_T t221;
  real_T t222;
  real_T t223;
  real_T t224;
  real_T t225;
  real_T t226;
  real_T t227;
  real_T t228;
  real_T t229;
  real_T t230;
  real_T t231;
  real_T t232;
  real_T t233;
  real_T t234;
  real_T t235;
  real_T t236;
  real_T t237;
  real_T t238;
  real_T t239;
  real_T t240;
  real_T t241;
  real_T t242;
  real_T t243;
  real_T t244;
  real_T t245;
  real_T t246;
  real_T t247;
  real_T t248;
  real_T t249;
  real_T t250;
  real_T t251;
  real_T t252;
  real_T t253;
  real_T t254;
  real_T t255;
  real_T t256;
  real_T t257;
  real_T t258;
  real_T t259;
  real_T t260;
  real_T t261;
  real_T t262;
  real_T t263;
  real_T t264;
  real_T t3;
  real_T t38;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t44;
  real_T t45;
  real_T t46;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t6;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t63;
  real_T t69;
  real_T t7;
  real_T t73;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T t77;
  real_T t78;
  real_T t79;
  real_T t8;
  real_T t80;
  real_T t81;
  real_T t82;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t9;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t97;
  real_T t98;
  real_T t99;
  st.prev = sp;
  st.tls = sp->tls;

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     27-Feb-2021 15:53:27 */
  t2 = in2[6] * s;
  t3 = in2[9] * s;
  t4 = in2[12] * s;
  t6 = in1[2] * in1[2];
  t7 = in1[3] * in1[3];
  t8 = s * s;
  t9 = muDoubleScalarPower(s, 3.0);
  t11 = muDoubleScalarPower(s, 5.0);
  t16 = 1.0 / in1[33];
  t10 = t8 * t8;
  t12 = muDoubleScalarPower(t8, 3.0);
  t18 = t8 * 2.0;
  t19 = t9 * 2.0;
  t21 = t11 * 2.0;
  t20 = t10 * 2.0;
  t22 = t12 * 2.0;
  t38 = t6 + -t7;
  t39 = (t2 + in2[7] * t8) + in2[8] * t9;
  t40 = (t3 + in2[10] * t8) + in2[11] * t9;
  t41 = (t4 + in2[13] * t8) + in2[14] * t9;
  t44 = t39 * t39;
  t45 = t40 * t40;
  t46 = t41 * t41;
  t47 = (t2 * 2.0 + in2[7] * t18) + in2[8] * t19;
  t48 = (t3 * 2.0 + in2[10] * t18) + in2[11] * t19;
  t49 = (t4 * 2.0 + in2[13] * t18) + in2[14] * t19;
  t54 = s * t47;
  t55 = s * t48;
  t56 = s * t49;
  t58 = t8 * t47;
  t59 = t9 * t47;
  t60 = t8 * t48;
  t61 = t9 * t48;
  t62 = t8 * t49;
  t63 = t9 * t49;
  t2 = -(in1[0] * t16 * t38 * (t6 / 4.0 + t7 / 4.0) * 3.1415926535897931);
  t3 = -(in1[0] * (in1[18] * in1[18] * 6.0 + t38) * 3.1415926535897931);
  out1[0] = t3;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t3;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t3;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = -in1[0] * t16 * t38 * 3.1415926535897931 * (t6 / 2.0 + t7 / 2.0);
  t2 = ((-t44 + -t45) + -t46) + 1.0;
  st.site = &eb_emlrtRSI;
  if (t2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t2 = muDoubleScalarSqrt(t2);
  t6 = 1.0 / t2;
  t3 = s * t2 * 2.0;
  t4 = t18 * t2;
  t2 *= t19;
  t69 = muDoubleScalarPower(t6, 3.0);
  t73 = t18 * t39 * t6;
  t74 = t19 * t39 * t6;
  t75 = t20 * t39 * t6;
  t76 = t21 * t39 * t6;
  t77 = t22 * t39 * t6;
  t78 = t18 * t40 * t6;
  t79 = t19 * t40 * t6;
  t80 = t20 * t40 * t6;
  t81 = t21 * t40 * t6;
  t82 = t22 * t40 * t6;
  t83 = t18 * t41 * t6;
  t84 = t19 * t41 * t6;
  t85 = t20 * t41 * t6;
  t86 = t21 * t41 * t6;
  t87 = t22 * t41 * t6;
  t88 = t58 * t6;
  t89 = t59 * t6;
  t90 = t10 * t47 * t6;
  t91 = t11 * t47 * t6;
  t92 = t12 * t47 * t6;
  t93 = t60 * t6;
  t94 = t61 * t6;
  t95 = t10 * t48 * t6;
  t96 = t11 * t48 * t6;
  t97 = t12 * t48 * t6;
  t98 = t62 * t6;
  t99 = t63 * t6;
  out2[0] = t8;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = t9;
  out2[7] = 0.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = t8;
  out2[14] = 0.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = 0.0;
  out2[19] = t9;
  out2[20] = 0.0;
  out2[21] = 0.0;
  out2[22] = 0.0;
  out2[23] = 0.0;
  out2[24] = 0.0;
  out2[25] = 0.0;
  out2[26] = t8;
  out2[27] = 0.0;
  out2[28] = 0.0;
  out2[29] = 0.0;
  out2[30] = 0.0;
  out2[31] = 0.0;
  out2[32] = t9;
  out2[33] = 0.0;
  out2[34] = 0.0;
  out2[35] = 0.0;
  out2[36] = 0.0;
  out2[37] = 0.0;
  out2[38] = 0.0;
  out2[39] = t3 + t39 * t54 * t6;
  out2[40] = -t56 + t39 * t55 * t6;
  out2[41] = t55 + t39 * t56 * t6;
  out2[42] = 0.0;
  out2[43] = 0.0;
  out2[44] = 0.0;
  out2[45] = t4 + t39 * t88;
  out2[46] = -t62 + t39 * t93;
  out2[47] = t60 + t39 * t98;
  out2[48] = 0.0;
  out2[49] = 0.0;
  out2[50] = 0.0;
  out2[51] = t2 + t39 * t89;
  out2[52] = -t63 + t39 * t94;
  out2[53] = t61 + t39 * t99;
  out2[54] = 0.0;
  out2[55] = 0.0;
  out2[56] = 0.0;
  out2[57] = t56 + t40 * t54 * t6;
  out2[58] = t3 + t40 * t55 * t6;
  out2[59] = -t54 + t40 * t56 * t6;
  out2[60] = 0.0;
  out2[61] = 0.0;
  out2[62] = 0.0;
  out2[63] = t62 + t40 * t88;
  out2[64] = t4 + t40 * t93;
  out2[65] = -t58 + t40 * t98;
  out2[66] = 0.0;
  out2[67] = 0.0;
  out2[68] = 0.0;
  out2[69] = t63 + t40 * t89;
  out2[70] = t2 + t40 * t94;
  out2[71] = -t59 + t40 * t99;
  out2[72] = 0.0;
  out2[73] = 0.0;
  out2[74] = 0.0;
  out2[75] = -t55 + t41 * t54 * t6;
  out2[76] = t54 + t41 * t55 * t6;
  out2[77] = t3 + t41 * t56 * t6;
  out2[78] = 0.0;
  out2[79] = 0.0;
  out2[80] = 0.0;
  out2[81] = -t60 + t41 * t88;
  out2[82] = t58 + t41 * t93;
  out2[83] = t4 + t41 * t98;
  out2[84] = 0.0;
  out2[85] = 0.0;
  out2[86] = 0.0;
  out2[87] = -t61 + t41 * t89;
  out2[88] = t59 + t41 * t94;
  out2[89] = t2 + t41 * t99;
  t56 = t10 * t49 * t6;
  t8 = t11 * t49 * t6;
  t102 = t12 * t49 * t6;
  t6 = t39 * t40;
  t130 = t6 * t58 * t69;
  t131 = t6 * t59 * t69;
  t2 = t10 * t39;
  t7 = t2 * t40;
  t132 = t7 * t47 * t69;
  t3 = t11 * t39;
  t16 = t3 * t40;
  t133 = t16 * t47 * t69;
  t4 = t12 * t39;
  t38 = t4 * t40;
  t134 = t38 * t47 * t69;
  t54 = t39 * t41;
  t135 = t54 * t58 * t69;
  t136 = t6 * t60 * t69;
  t137 = t54 * t59 * t69;
  t138 = t6 * t61 * t69;
  t2 *= t41;
  t139 = t2 * t47 * t69;
  t140 = t7 * t48 * t69;
  t3 *= t41;
  t141 = t3 * t47 * t69;
  t142 = t16 * t48 * t69;
  t4 *= t41;
  t143 = t4 * t47 * t69;
  t144 = t38 * t48 * t69;
  t145 = t6 * t62 * t69;
  t146 = t54 * t60 * t69;
  t55 = t40 * t41;
  t147 = t55 * t58 * t69;
  t9 = t6 * t63 * t69;
  t39 = t54 * t61 * t69;
  t150 = t55 * t59 * t69;
  t151 = t7 * t49 * t69;
  t152 = t2 * t48 * t69;
  t7 = t10 * t40 * t41;
  t153 = t7 * t47 * t69;
  t154 = t16 * t49 * t69;
  t155 = t3 * t48 * t69;
  t16 = t11 * t40 * t41;
  t156 = t16 * t47 * t69;
  t157 = t38 * t49 * t69;
  t158 = t4 * t48 * t69;
  t6 = t12 * t40 * t41;
  t159 = t6 * t47 * t69;
  t160 = t54 * t62 * t69;
  t161 = t55 * t60 * t69;
  t38 = t54 * t63 * t69;
  t163 = t55 * t61 * t69;
  t54 = t2 * t49 * t69;
  t165 = t7 * t48 * t69;
  t166 = t3 * t49 * t69;
  t167 = t16 * t48 * t69;
  t168 = t4 * t49 * t69;
  t169 = t6 * t48 * t69;
  t170 = t55 * t62 * t69;
  t171 = t55 * t63 * t69;
  t172 = t7 * t49 * t69;
  t173 = t16 * t49 * t69;
  t174 = t6 * t49 * t69;
  t202 = t19 + t9;
  t203 = t19 + t39;
  t204 = t19 + t150;
  t205 = t20 + t151;
  t206 = t20 + t152;
  t207 = t20 + t153;
  t208 = t21 + t154;
  t209 = t21 + t155;
  t210 = t21 + t156;
  t220 = t89 + t44 * t59 * t69;
  t2 = t10 * t44;
  t221 = t90 + t2 * t47 * t69;
  t3 = t11 * t44;
  t222 = t91 + t3 * t47 * t69;
  t223 = t89 + t45 * t59 * t69;
  t6 = t10 * t45;
  t224 = t90 + t6 * t47 * t69;
  t16 = t11 * t45;
  t225 = t91 + t16 * t47 * t69;
  t226 = t89 + t46 * t59 * t69;
  t227 = t94 + t44 * t61 * t69;
  t7 = t10 * t46;
  t228 = t90 + t7 * t47 * t69;
  t229 = t95 + t2 * t48 * t69;
  t4 = t11 * t46;
  t230 = t91 + t4 * t47 * t69;
  t231 = t96 + t3 * t48 * t69;
  t232 = t94 + t45 * t61 * t69;
  t233 = t95 + t6 * t48 * t69;
  t234 = t96 + t16 * t48 * t69;
  t235 = t94 + t46 * t61 * t69;
  t236 = t99 + t44 * t63 * t69;
  t237 = t95 + t7 * t48 * t69;
  t238 = t56 + t2 * t49 * t69;
  t239 = t96 + t4 * t48 * t69;
  t240 = t8 + t3 * t49 * t69;
  t241 = t99 + t45 * t63 * t69;
  t242 = t56 + t6 * t49 * t69;
  t243 = t8 + t16 * t49 * t69;
  t244 = t99 + t46 * t63 * t69;
  t245 = t56 + t7 * t49 * t69;
  t246 = t8 + t4 * t49 * t69;
  t247 = t74 + t138;
  t248 = t79 + t131;
  t249 = t75 + t140;
  t250 = t80 + t132;
  t251 = t76 + t142;
  t252 = t81 + t133;
  t253 = t74 + t38;
  t254 = t84 + t137;
  t255 = t75 + t54;
  t256 = t85 + t139;
  t257 = t76 + t166;
  t258 = t86 + t141;
  t259 = t79 + t171;
  t260 = t84 + t163;
  t261 = t80 + t172;
  t262 = t85 + t165;
  t263 = t81 + t173;
  t264 = t86 + t167;
  t99 = t19 + -t9;
  t63 = t19 + -t39;
  t61 = t19 + -t150;
  t96 = t20 + -t151;
  t11 = t20 + -t152;
  t95 = t20 + -t153;
  t10 = t21 + -t154;
  t94 = t21 + -t155;
  t59 = t21 + -t156;
  t90 = t74 + -t138;
  t91 = t79 + -t131;
  t89 = t75 + -t140;
  t41 = t80 + -t132;
  t40 = t76 + -t142;
  t39 = t81 + -t133;
  t2 = t74 + -t38;
  t9 = t84 + -t137;
  t8 = t75 + -t54;
  t56 = t85 + -t139;
  t55 = t76 + -t166;
  t54 = t86 + -t141;
  t38 = t79 + -t171;
  t16 = t84 + -t163;
  t7 = t80 + -t172;
  t6 = t85 + -t165;
  t4 = t81 + -t173;
  t3 = t86 + -t167;
  memset(&out3[0], 0, 39U * sizeof(real_T));
  out3[39] = (((((((in2[24] * (t78 + t130) + in2[27] * (t83 + t135)) + t220 *
                   in2[22]) + t221 * in2[23]) + t248 * in2[25]) + t250 * in2[26])
               + t254 * in2[28]) + t256 * in2[29]) + in2[21] * (t88 + t44 * t58 *
    t69);
  out3[40] = (((((((in2[27] * (t18 + t146) + t203 * in2[28]) + t206 * in2[29]) +
                  t227 * in2[22]) + t229 * in2[23]) - t90 * in2[25]) - t89 *
               in2[26]) + in2[21] * (t93 + t44 * t60 * t69)) - in2[24] * (t73 -
    t136);
  out3[41] = (((((((-t99 * in2[25] - t96 * in2[26]) + t236 * in2[22]) + t238 *
                  in2[23]) - t2 * in2[28]) - t8 * in2[29]) + in2[21] * (t98 +
    t44 * t62 * t69)) - in2[24] * (t18 - t145)) - in2[27] * (t73 - t160);
  out3[42] = 0.0;
  out3[43] = 0.0;
  out3[44] = 0.0;
  out3[45] = (((((((t220 * in2[21] + t221 * in2[22]) + t222 * in2[23]) + t248 *
                  in2[24]) + t250 * in2[25]) + t252 * in2[26]) + t254 * in2[27])
              + t256 * in2[28]) + t258 * in2[29];
  out3[46] = (((((((t203 * in2[27] + t206 * in2[28]) + t209 * in2[29]) + t227 *
                  in2[21]) + t229 * in2[22]) + t231 * in2[23]) - t90 * in2[24])
              - t89 * in2[25]) - t40 * in2[26];
  out3[47] = (((((((-t99 * in2[24] - t96 * in2[25]) - t10 * in2[26]) + t236 *
                  in2[21]) + t238 * in2[22]) + t240 * in2[23]) - t2 * in2[27]) -
              t8 * in2[28]) - t55 * in2[29];
  out3[48] = 0.0;
  out3[49] = 0.0;
  out3[50] = 0.0;
  t2 = t12 * t44;
  out3[51] = (((((((in2[26] * (t82 + t134) + in2[29] * (t87 + t143)) + t221 *
                   in2[21]) + t222 * in2[22]) + t250 * in2[24]) + t252 * in2[25])
               + t256 * in2[27]) + t258 * in2[28]) + in2[23] * (t92 + t2 * t47 *
    t69);
  out3[52] = (((((((in2[29] * (t22 + t158) + t206 * in2[27]) + t209 * in2[28]) +
                  t229 * in2[21]) + t231 * in2[22]) - t89 * in2[24]) - t40 *
               in2[25]) - in2[26] * (t77 - t144)) + in2[23] * (t97 + t2 * t48 *
    t69);
  out3[53] = (((((((-t96 * in2[24] - t10 * in2[25]) + t238 * in2[21]) + t240 *
                  in2[22]) - t8 * in2[27]) - t55 * in2[28]) - in2[26] * (t22 -
    t157)) - in2[29] * (t77 - t168)) + in2[23] * (t102 + t2 * t49 * t69);
  out3[54] = 0.0;
  out3[55] = 0.0;
  out3[56] = 0.0;
  out3[57] = (((((((-t61 * in2[28] - t95 * in2[29]) + t223 * in2[25]) + t224 *
                  in2[26]) - t91 * in2[22]) - t41 * in2[23]) + in2[24] * (t88 +
    t45 * t58 * t69)) - in2[27] * (t18 - t147)) - in2[21] * (t78 - t130);
  out3[58] = (((((((in2[21] * (t73 + t136) + in2[27] * (t83 + t161)) + t232 *
                   in2[25]) + t233 * in2[26]) + t247 * in2[22]) + t249 * in2[23])
               + t260 * in2[28]) + t262 * in2[29]) + in2[24] * (t93 + t45 * t60 *
    t69);
  out3[59] = (((((((in2[21] * (t18 + t145) + t202 * in2[22]) + t205 * in2[23]) +
                  t241 * in2[25]) + t242 * in2[26]) - t38 * in2[28]) - t7 * in2
               [29]) + in2[24] * (t98 + t45 * t62 * t69)) - in2[27] * (t78 -
    t170);
  out3[60] = 0.0;
  out3[61] = 0.0;
  out3[62] = 0.0;
  out3[63] = (((((((-t61 * in2[27] - t95 * in2[28]) + t223 * in2[24]) - t59 *
                  in2[29]) + t224 * in2[25]) + t225 * in2[26]) - t91 * in2[21])
              - t41 * in2[22]) - t39 * in2[23];
  out3[64] = (((((((t232 * in2[24] + t233 * in2[25]) + t234 * in2[26]) + t247 *
                  in2[21]) + t249 * in2[22]) + t251 * in2[23]) + t260 * in2[27])
              + t262 * in2[28]) + t264 * in2[29];
  out3[65] = (((((((t202 * in2[21] + t205 * in2[22]) + t208 * in2[23]) + t241 *
                  in2[24]) + t242 * in2[25]) + t243 * in2[26]) - t38 * in2[27])
              - t7 * in2[28]) - t4 * in2[29];
  out3[66] = 0.0;
  out3[67] = 0.0;
  out3[68] = 0.0;
  t2 = t12 * t45;
  out3[69] = (((((((-t95 * in2[27] - t59 * in2[28]) + t224 * in2[24]) + t225 *
                  in2[25]) - t41 * in2[21]) - t39 * in2[22]) - in2[29] * (t22 -
    t159)) - in2[23] * (t82 - t134)) + in2[26] * (t92 + t2 * t47 * t69);
  out3[70] = (((((((in2[23] * (t77 + t144) + in2[29] * (t87 + t169)) + t233 *
                   in2[24]) + t234 * in2[25]) + t249 * in2[21]) + t251 * in2[22])
               + t262 * in2[27]) + t264 * in2[28]) + in2[26] * (t97 + t2 * t48 *
    t69);
  out3[71] = (((((((in2[23] * (t22 + t157) + t205 * in2[21]) + t208 * in2[22]) +
                  t242 * in2[24]) + t243 * in2[25]) - t7 * in2[27]) - t4 * in2
               [28]) - in2[29] * (t82 - t174)) + in2[26] * (t102 + t2 * t49 *
    t69);
  out3[72] = 0.0;
  out3[73] = 0.0;
  out3[74] = 0.0;
  out3[75] = (((((((in2[24] * (t18 + t147) + t204 * in2[25]) + t207 * in2[26]) +
                  t226 * in2[28]) + t228 * in2[29]) - t9 * in2[22]) - t56 * in2
               [23]) + in2[27] * (t88 + t46 * t58 * t69)) - in2[21] * (t83 -
    t135);
  out3[76] = (((((((-t63 * in2[22] - t11 * in2[23]) + t235 * in2[28]) + t237 *
                  in2[29]) - t16 * in2[25]) - t6 * in2[26]) + in2[27] * (t93 +
    t46 * t60 * t69)) - in2[21] * (t18 - t146)) - in2[24] * (t83 - t161);
  out3[77] = (((((((in2[21] * (t73 + t160) + in2[24] * (t78 + t170)) + t244 *
                   in2[28]) + t245 * in2[29]) + t253 * in2[22]) + t255 * in2[23])
               + t259 * in2[25]) + t261 * in2[26]) + in2[27] * (t98 + t46 * t62 *
    t69);
  out3[78] = 0.0;
  out3[79] = 0.0;
  out3[80] = 0.0;
  out3[81] = (((((((t204 * in2[24] + t207 * in2[25]) + t210 * in2[26]) + t226 *
                  in2[27]) + t228 * in2[28]) + t230 * in2[29]) - t9 * in2[21]) -
              t56 * in2[22]) - t54 * in2[23];
  out3[82] = (((((((-t63 * in2[21] - t11 * in2[22]) - t94 * in2[23]) + t235 *
                  in2[27]) + t237 * in2[28]) + t239 * in2[29]) - t16 * in2[24])
              - t6 * in2[25]) - t3 * in2[26];
  out3[83] = (((((((t244 * in2[27] + t245 * in2[28]) + t253 * in2[21]) + t246 *
                  in2[29]) + t255 * in2[22]) + t257 * in2[23]) + t259 * in2[24])
              + t261 * in2[25]) + t263 * in2[26];
  out3[84] = 0.0;
  out3[85] = 0.0;
  out3[86] = 0.0;
  t2 = t12 * t46;
  out3[87] = (((((((in2[26] * (t22 + t159) + t207 * in2[24]) + t210 * in2[25]) +
                  t228 * in2[27]) + t230 * in2[28]) - t56 * in2[21]) - t54 *
               in2[22]) - in2[23] * (t87 - t143)) + in2[29] * (t92 + t2 * t47 *
    t69);
  out3[88] = (((((((-t11 * in2[21] - t94 * in2[22]) + t237 * in2[27]) + t239 *
                  in2[28]) - t6 * in2[24]) - t3 * in2[25]) - in2[23] * (t22 -
    t158)) - in2[26] * (t87 - t169)) + in2[29] * (t97 + t2 * t48 * t69);
  out3[89] = (((((((in2[23] * (t77 + t168) + in2[26] * (t82 + t174)) + t245 *
                   in2[27]) + t246 * in2[28]) + t255 * in2[21]) + t257 * in2[22])
               + t261 * in2[24]) + t263 * in2[25]) + in2[29] * (t102 + t2 * t49 *
    t69);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF1.c) */
