/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vdF.c
 *
 * Code generation for function 'fj_vdF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "EOM.h"
#include "fj_vdF.h"

/* Function Definitions */
void fj_vdF(const real_T in1[34], const real_T in2[12], real_T fj_vd[6])
{
  /* FJ_VDF */
  /*     FJ_VD = FJ_VDF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 22:48:53 */
  fj_vd[0] = -in1[5] * in2[6];
  fj_vd[1] = -in1[6] * in2[7];
  fj_vd[2] = -in1[7] * in2[8];
  fj_vd[3] = -in1[8] * in2[9];
  fj_vd[4] = -in1[9] * in2[10];
  fj_vd[5] = -in1[10] * in2[11];
}

/* End of code generation (fj_vdF.c) */
