/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vdF.c
 *
 * Code generation for function 'fj_vdF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "fj_vdF.h"

/* Function Definitions */
void fj_vdF(const real_T in1[34], const real_T in2[24], real_T fj_vd[12])
{
  /* FJ_VDF */
  /*     FJ_VD = FJ_VDF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 07:54:16 */
  fj_vd[0] = -in1[5] * in2[12] * muDoubleScalarPower(muDoubleScalarAbs(in2[12]),
    in1[11] - 1.0);
  fj_vd[1] = -in1[6] * in2[13] * muDoubleScalarPower(muDoubleScalarAbs(in2[13]),
    in1[11] - 1.0);
  fj_vd[2] = -in1[7] * in2[14] * muDoubleScalarPower(muDoubleScalarAbs(in2[14]),
    in1[11] - 1.0);
  fj_vd[3] = -in1[10] * in2[15] * muDoubleScalarPower(muDoubleScalarAbs(in2[15]),
    in1[11] - 1.0);
  fj_vd[4] = -in1[8] * in2[16] * muDoubleScalarPower(muDoubleScalarAbs(in2[16]),
    in1[11] - 1.0);
  fj_vd[5] = -in1[9] * in2[17] * muDoubleScalarPower(muDoubleScalarAbs(in2[17]),
    in1[11] - 1.0);
  fj_vd[6] = -in1[5] * in2[18] * muDoubleScalarPower(muDoubleScalarAbs(in2[18]),
    in1[11] - 1.0);
  fj_vd[7] = -in1[6] * in2[19] * muDoubleScalarPower(muDoubleScalarAbs(in2[19]),
    in1[11] - 1.0);
  fj_vd[8] = -in1[7] * in2[20] * muDoubleScalarPower(muDoubleScalarAbs(in2[20]),
    in1[11] - 1.0);
  fj_vd[9] = -in1[10] * in2[21] * muDoubleScalarPower(muDoubleScalarAbs(in2[21]),
    in1[11] - 1.0);
  fj_vd[10] = -in1[8] * in2[22] * muDoubleScalarPower(muDoubleScalarAbs(in2[22]),
    in1[11] - 1.0);
  fj_vd[11] = -in1[9] * in2[23] * muDoubleScalarPower(muDoubleScalarAbs(in2[23]),
    in1[11] - 1.0);
}

/* End of code generation (fj_vdF.c) */
