/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF2.h"

/* Function Definitions */
void massF2(const real_T in1[34], const real_T in2[36], real_T out1[36], real_T
            out2[108], real_T out3[108], real_T out4[6])
{
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t16;
  real_T t47;
  real_T t111;
  real_T t21;
  real_T t27;
  real_T t28;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t41;
  real_T t42_tmp;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t45_tmp;
  real_T t45;
  real_T t51_tmp;
  real_T t51;
  real_T t46_tmp_tmp_tmp;
  real_T t46_tmp_tmp;
  real_T t78;
  real_T t48;
  real_T t49_tmp;
  real_T t49;
  real_T t53_tmp;
  real_T t53;
  real_T t50_tmp_tmp;
  real_T b_t50_tmp_tmp;
  real_T t85;
  real_T t58_tmp_tmp;
  real_T t58_tmp;
  real_T t52_tmp_tmp;
  real_T t52_tmp;
  real_T t88;
  real_T t54_tmp_tmp;
  real_T t54_tmp;
  real_T t55_tmp_tmp;
  real_T t55_tmp;
  real_T t56_tmp_tmp;
  real_T t56_tmp;
  real_T t57_tmp;
  real_T t57;
  real_T t59;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t63;
  real_T t129;
  real_T t67;
  real_T t68;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t73_tmp;
  real_T t74;
  real_T t75;
  real_T t76;
  real_T out2_tmp;
  real_T t128;
  real_T t120;
  real_T t127;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 23:25:59 */
  t4 = in1[2] * in1[2];
  t5 = in1[3] * in1[3];
  t7 = 1.0 / in1[33];
  t16 = t4 - t5;
  t47 = -in1[0] * ((in1[18] * in1[18] * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t47;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t47;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t47;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t111 = in1[4] * in1[0];
  t47 = t111 * (t7 * (t4 * 3.0 + t5 * 3.0) / 12.0 + in1[4] * in1[4] * (in1[33] *
    in1[33]) / 108.0) * t16 * 3.1415926535897931 * -0.33333333333333331;
  out1[21] = t47;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t47;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t111 * t7 * t16 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0) *
    -0.33333333333333331;
  t4 = in1[4] / 3.0;
  t7 = in2[8] + t4;
  t21 = in1[4] / 6.0 + in2[8] / 2.0;
  t16 = in2[3] * in2[7] / 2.0;
  t27 = ((in2[3] * in2[6] / 2.0 + in2[4] * in2[7] / 2.0) + in2[5] * t7 / 4.0) +
    in2[5] * t21 / 2.0;
  t28 = in2[3] * in2[4] / 2.0;
  t29 = in2[3] * in2[3];
  t30 = t29 / 4.0;
  t31 = in2[4] * in2[4];
  t32 = in2[5] * in2[5];
  t33 = in2[3] * t7 / 4.0;
  t34 = in2[3] * t21 / 2.0;
  t35 = in2[4] * t7 / 4.0;
  t36 = in2[4] * t21 / 2.0;
  t37 = in2[3] * in2[5] / 2.0;
  t38 = in2[4] * in2[5] / 2.0;
  t39 = t31 / 4.0;
  t5 = in2[5] / 2.0;
  t41 = in2[11] / 2.0;
  t42_tmp = in2[3] * in2[10];
  t42 = t42_tmp / 4.0;
  t43 = in2[4] / 2.0;
  t44 = in2[10] / 2.0;
  t45_tmp = in2[5] * in2[9];
  t45 = t45_tmp / 4.0;
  t51_tmp = in2[3] * in2[11];
  t51 = t51_tmp / 4.0;
  t46_tmp_tmp_tmp = t43 + t44;
  t46_tmp_tmp = t46_tmp_tmp_tmp + t45;
  t78 = t46_tmp_tmp - t51;
  t47 = in2[3] / 2.0;
  t48 = in2[9] / 2.0;
  t49_tmp = in2[4] * in2[11];
  t49 = t49_tmp / 4.0;
  t53_tmp = in2[5] * in2[10];
  t53 = t53_tmp / 4.0;
  t50_tmp_tmp = t47 + t48;
  b_t50_tmp_tmp = t50_tmp_tmp + t49;
  t85 = b_t50_tmp_tmp - t53;
  t58_tmp_tmp = in2[4] * in2[9];
  t58_tmp = t58_tmp_tmp / 4.0;
  t52_tmp_tmp = t5 + t41;
  t52_tmp = t52_tmp_tmp + t42;
  t88 = t52_tmp - t58_tmp;
  t54_tmp_tmp = in2[3] * in2[9];
  t54_tmp = t54_tmp_tmp / 4.0;
  t55_tmp_tmp = in2[4] * in2[10];
  t55_tmp = t55_tmp_tmp / 4.0;
  t56_tmp_tmp = in2[5] * in2[11];
  t56_tmp = t56_tmp_tmp / 4.0;
  t57_tmp = t54_tmp + t55_tmp;
  t57 = (t57_tmp + t56_tmp) - 1.0;
  t59 = in2[9] * t78 / 2.0;
  t60 = in2[10] * t85 / 2.0;
  t61 = in2[9] * t85 / 2.0;
  t62 = in2[4] * t85 / 2.0;
  t63 = in2[5] * t57 / 2.0;
  t129 = (-t54_tmp - t55_tmp) - t56_tmp;
  t67 = (((t129 + in2[3] * t85 / 2.0) + in2[4] * t78 / 2.0) + in2[5] * t88 / 2.0)
    + 1.0;
  t68 = in2[9] * t88 / 2.0;
  t69 = in2[11] * t85 / 2.0;
  t70 = in2[10] * t57 / 2.0;
  t71 = in2[10] * t88 / 2.0;
  t72 = in2[11] * t78 / 2.0;
  t73_tmp = in2[10] * t78 / 2.0;
  t74 = in2[5] * t85 / 2.0;
  t75 = in2[5] * t78 / 2.0;
  t76 = in2[3] * t57 / 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2[18] = t27;
  out2_tmp = in2[4] * in2[6] / 2.0;
  out2[19] = ((-in2[8] - t4) - t16) + out2_tmp;
  t111 = in2[5] * in2[6] / 2.0;
  out2[20] = ((in2[7] - t33) - t34) + t111;
  t128 = in2[11] * t88 / 2.0;
  out2[21] = (((((t61 - t54_tmp) - t55_tmp) - t56_tmp) - t73_tmp) - t128) + 1.0;
  t120 = in2[11] * t57 / 2.0;
  t127 = ((-t5 - t41) - t42) + t58_tmp;
  out2[22] = ((t127 + t59) + t60) + t120;
  out2[23] = ((t78 + t68) + t69) - t70;
  out2[24] = (t7 + t16) - out2_tmp;
  out2[25] = t27;
  out2_tmp = in2[5] * in2[7] / 2.0;
  out2[26] = ((-in2[6] - t35) - t36) + out2_tmp;
  out2[27] = (((t52_tmp + t59) + t60) - t58_tmp) - t120;
  t120 = t129 - t61;
  out2[28] = ((t120 + t73_tmp) - t128) + 1.0;
  t5 = in2[9] * t57 / 2.0;
  t4 = ((-t47 - t48) - t49) + t53;
  out2[29] = ((t4 + t71) + t72) + t5;
  out2[30] = ((-in2[7] + t33) + t34) - t111;
  out2[31] = ((in2[6] + t35) + t36) - out2_tmp;
  out2[32] = t27;
  out2_tmp = ((-t43 - t44) - t45) + t51;
  out2[33] = ((out2_tmp + t68) + t69) + t70;
  out2[34] = ((t85 + t71) + t72) - t5;
  out2[35] = ((t120 - t73_tmp) + t128) + 1.0;
  out2[36] = ((t30 - t31 / 4.0) - t32 / 4.0) + 1.0;
  out2[37] = in2[5] + t28;
  out2[38] = -in2[4] + t37;
  out2[39] = 0.0;
  out2[40] = 0.0;
  out2[41] = 0.0;
  out2[42] = -in2[5] + t28;
  out2[43] = ((-t30 - t32 / 4.0) + t39) + 1.0;
  out2[44] = in2[3] + t38;
  out2[45] = 0.0;
  out2[46] = 0.0;
  out2[47] = 0.0;
  out2[48] = in2[4] + t37;
  out2[49] = -in2[3] + t38;
  out2[50] = ((-t30 + t32 / 4.0) - t39) + 1.0;
  out2[51] = 0.0;
  out2[52] = 0.0;
  out2[53] = 0.0;
  out2[54] = 0.0;
  out2[55] = 0.0;
  out2[56] = 0.0;
  out2[57] = t67;
  t111 = in2[3] * t78 / 2.0;
  out2[58] = ((t127 - t62) - t63) + t111;
  t128 = in2[3] * t88 / 2.0;
  t120 = in2[4] * t57 / 2.0;
  out2[59] = ((t78 - t74) + t128) + t120;
  out2[60] = 0.0;
  out2[61] = 0.0;
  out2[62] = 0.0;
  out2[63] = ((t88 + t62) + t63) - t111;
  out2[64] = t67;
  t111 = in2[4] * t88 / 2.0;
  out2[65] = ((t4 - t75) - t76) + t111;
  out2[66] = 0.0;
  out2[67] = 0.0;
  out2[68] = 0.0;
  out2[69] = ((out2_tmp + t74) - t128) - t120;
  out2[70] = ((t85 + t75) + t76) - t111;
  out2[71] = t67;
  memset(&out2[72], 0, 36U * sizeof(real_T));
  t43 = in2[3] * in2[25] / 2.0;
  t78 = in2[7] * in2[21] / 2.0;
  t85 = ((((in2[3] * in2[24] / 2.0 + in2[6] * in2[21] / 2.0) + in2[4] * in2[25] /
           2.0) + in2[7] * in2[22] / 2.0) + in2[5] * in2[26] / 2.0) + t21 * in2
    [23];
  t88 = in2[3] * in2[21] / 2.0;
  t57 = in2[3] * in2[26] / 2.0;
  t62 = t21 * in2[21];
  t63 = in2[4] * in2[26] / 2.0;
  t35 = t21 * in2[22];
  t36 = in2[4] * in2[22] / 2.0;
  t128 = in2[9] * in2[11] / 4.0;
  t37 = t44 - t128;
  t4 = in2[9] * in2[10] / 4.0;
  t38 = t41 + t4;
  t16 = in2[9] * in2[9] / 8.0;
  t47 = in2[10] * in2[10] / 8.0;
  t111 = in2[11] * in2[11] / 8.0;
  t5 = t16 - t47;
  t39 = (t5 - t111) + 0.5;
  t33 = ((t29 / 8.0 + t31 / 8.0) + t32 / 8.0) + 0.5;
  t7 = in2[10] * in2[11] / 4.0;
  t34 = t48 + t7;
  t30 = t41 - t4;
  t28 = (t5 + t111) - 0.5;
  t27 = (t50_tmp_tmp - t53) * in2[22];
  t120 = (t57_tmp - 1.0) * in2[23];
  t127 = (((t48 + t49) - t53) * in2[21] + ((t44 + t45) - t51) * in2[22]) + ((t41
    + t42) - t58_tmp) * in2[23];
  t129 = ((t16 + t47) - t111) - 0.5;
  t61 = t48 - t7;
  t60 = t44 + t128;
  t128 = b_t50_tmp_tmp * in2[23];
  t59 = t33 * in2[28];
  t111 = (t46_tmp_tmp_tmp - t51) * in2[23];
  t4 = ((t55_tmp + t56_tmp) - 1.0) * in2[21];
  memset(&out3[0], 0, 18U * sizeof(real_T));
  out3[18] = t85;
  t5 = in2[4] * in2[24] / 2.0;
  t7 = in2[6] * in2[22] / 2.0;
  out3[19] = (((-t43 - t78) - in2[26]) + t5) + t7;
  t16 = in2[5] * in2[24] / 2.0;
  t47 = in2[6] * in2[23] / 2.0;
  out3[20] = (((-t57 - t62) + in2[25]) + t16) + t47;
  out3[21] = (((in2[3] * in2[27] / 2.0 + t37 * in2[22]) + t38 * in2[23]) -
              t42_tmp * in2[29] / 4.0) + t51_tmp * in2[28] / 4.0;
  out3[22] = (((in2[3] * in2[28] / 2.0 - t34 * in2[22]) - t28 * in2[23]) +
              t54_tmp_tmp * in2[29] / 4.0) - t51_tmp * in2[27] / 4.0;
  out3[23] = (((in2[3] * in2[29] / 2.0 + t129 * in2[22]) - t61 * in2[23]) -
              t54_tmp_tmp * in2[28] / 4.0) + t42_tmp * in2[27] / 4.0;
  out3[24] = (((t43 + t78) + in2[26]) - t5) - t7;
  out3[25] = t85;
  t5 = in2[5] * in2[25] / 2.0;
  t7 = in2[7] * in2[23] / 2.0;
  out3[26] = (((-t63 - t35) - in2[24]) + t5) + t7;
  out3[27] = (((in2[4] * in2[27] / 2.0 - t37 * in2[21]) - t39 * in2[23]) -
              t55_tmp_tmp * in2[29] / 4.0) + t49_tmp * in2[28] / 4.0;
  out3[28] = (((in2[4] * in2[28] / 2.0 + t34 * in2[21]) + t30 * in2[23]) +
              t58_tmp_tmp * in2[29] / 4.0) - t49_tmp * in2[27] / 4.0;
  out3[29] = (((in2[4] * in2[29] / 2.0 - t129 * in2[21]) - t60 * in2[23]) -
              t58_tmp_tmp * in2[28] / 4.0) + t55_tmp_tmp * in2[27] / 4.0;
  out3[30] = (((t57 + t62) - in2[25]) - t16) - t47;
  out3[31] = (((t63 + t35) + in2[24]) - t5) - t7;
  out3[32] = t85;
  out3[33] = (((in2[5] * in2[27] / 2.0 - t38 * in2[21]) + t39 * in2[22]) -
              t53_tmp * in2[29] / 4.0) + t56_tmp_tmp * in2[28] / 4.0;
  out3[34] = (((in2[5] * in2[28] / 2.0 - t30 * in2[22]) + t28 * in2[21]) +
              t45_tmp * in2[29] / 4.0) - t56_tmp_tmp * in2[27] / 4.0;
  out3[35] = (((in2[5] * in2[29] / 2.0 + t61 * in2[21]) + t60 * in2[22]) -
              t45_tmp * in2[28] / 4.0) + t53_tmp * in2[27] / 4.0;
  t5 = in2[5] * in2[23] / 2.0;
  out3[36] = (t88 - t36) - t5;
  t7 = in2[3] * in2[22] / 2.0 + in2[4] * in2[21] / 2.0;
  out3[37] = t7 + in2[23];
  t16 = in2[3] * in2[23] / 2.0 + in2[5] * in2[21] / 2.0;
  out3[38] = t16 - in2[22];
  out3[39] = 0.0;
  out3[40] = 0.0;
  out3[41] = 0.0;
  out3[42] = t7 - in2[23];
  out3[43] = (-t88 + t36) - t5;
  t7 = in2[4] * in2[23] / 2.0 + in2[5] * in2[22] / 2.0;
  out3[44] = t7 + in2[21];
  out3[45] = 0.0;
  out3[46] = 0.0;
  out3[47] = 0.0;
  out3[48] = t16 + in2[22];
  out3[49] = t7 - in2[21];
  out3[50] = (-t88 - t36) + t5;
  out3[51] = 0.0;
  out3[52] = 0.0;
  out3[53] = 0.0;
  out3[54] = 0.0;
  out3[55] = 0.0;
  out3[56] = 0.0;
  out3[57] = t127;
  t5 = t46_tmp_tmp * in2[21];
  t7 = t33 * in2[29];
  out3[58] = ((-t27 - t120) + t5) + t7;
  t16 = (t52_tmp_tmp - t58_tmp) * in2[21];
  t47 = ((t54_tmp + t56_tmp) - 1.0) * in2[22];
  out3[59] = ((-t128 - t59) + t16) + t47;
  out3[60] = 0.0;
  out3[61] = 0.0;
  out3[62] = 0.0;
  out3[63] = ((t27 + t120) - t5) - t7;
  out3[64] = t127;
  t5 = t33 * in2[27];
  t7 = t52_tmp * in2[22];
  out3[65] = ((-t111 - t4) + t5) + t7;
  out3[66] = 0.0;
  out3[67] = 0.0;
  out3[68] = 0.0;
  out3[69] = ((t128 + t59) - t16) - t47;
  out3[70] = ((t111 + t4) - t5) - t7;
  out3[71] = t127;
  memset(&out3[72], 0, 36U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF2.c) */
