/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t13;
  real_T t16;
  real_T t17;
  real_T t19;
  real_T b_in2[12];
  int32_T i0;
  int32_T i1;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     16-Jan-2019 11:57:01 */
  t2 = in2[5] * 0.5;
  t3 = in2[3] * 0.5;
  t4 = in2[4] * 0.5;
  t5 = muDoubleScalarSin(t3);
  t6 = muDoubleScalarSin(t4);
  t7 = muDoubleScalarSin(t2);
  t8 = muDoubleScalarCos(t3);
  t3 = muDoubleScalarCos(t4);
  t4 = muDoubleScalarCos(t2);
  t13 = t7 * t8 * t3 + t5 * t6 * t4;
  t16 = t5 * t3 * t4 + t6 * t7 * t8;
  t17 = t5 * t7 * t3;
  t19 = t5 * t6 * t7 - t8 * t3 * t4;
  t3 = t6 * t8 * t4;
  t2 = t17 - t3;
  t5 = t17 - t3;
  t7 = in1[4] + in2[2];
  t8 = t13 * t13;
  t6 = t16 * t16;
  t3 = t17 - t3;
  t4 = t19 * t19;
  b_in2[0] = in2[0];
  b_in2[1] = in2[0];
  b_in2[2] = in2[1];
  b_in2[3] = in2[1];
  b_in2[4] = t7;
  b_in2[5] = t7;
  b_in2[6] = (in2[0] - in1[4] * t13 * t19 * 2.0) - in1[4] * t16 * t2 * 2.0;
  b_in2[7] = (in2[0] - in1[16] * t13 * t19 * 2.0) - in1[16] * t16 * t2 * 2.0;
  b_in2[8] = (in2[1] + in1[4] * t13 * t16 * 2.0) - in1[4] * t19 * t2 * 2.0;
  b_in2[9] = (in2[1] + in1[16] * t13 * t16 * 2.0) - in1[16] * t19 * t2 * 2.0;
  b_in2[10] = ((((in1[4] + in2[2]) - in1[4] * t8) + in1[4] * t6) + in1[4] * t4)
    - in1[4] * (t5 * t5);
  b_in2[11] = ((((in1[4] + in2[2]) - in1[16] * t8) + in1[16] * t6) + in1[16] *
               t4) - in1[16] * (t3 * t3);
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 2; i1++) {
      r_jtip[i1 + (i0 << 1)] = b_in2[i1 + (i0 << 1)];
    }
  }
}

/* End of code generation (rjtipF.c) */
