/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF2.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo ub_emlrtRSI = { 23, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo vb_emlrtRSI = { 25, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo wb_emlrtRSI = { 26, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo xb_emlrtRSI = { 33, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo yb_emlrtRSI = { 34, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo ac_emlrtRSI = { 40, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo bc_emlrtRSI = { 41, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo cc_emlrtRSI = { 42, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo dc_emlrtRSI = { 44, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo ec_emlrtRSI = { 47, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

static emlrtRSInfo fc_emlrtRSI = { 55, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF2.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[60],
            real_T out1[36], real_T out2[180], real_T out3[180], real_T out4[6])
{
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t16;
  real_T t20;
  real_T t22;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t21;
  real_T t43;
  real_T t23;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t45;
  real_T t46;
  real_T t47;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 19:49:53 */
  st.site = &ub_emlrtRSI;
  st.site = &vb_emlrtRSI;
  t4 = in1[2] * in1[2];
  st.site = &wb_emlrtRSI;
  t5 = in1[3] * in1[3];
  t7 = 1.0 / in1[33];
  st.site = &xb_emlrtRSI;
  st.site = &yb_emlrtRSI;
  t16 = t4 - t5;
  t20 = -in1[0] * ((in1[18] * in1[18] * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t20;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t20;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t20;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t22 = in1[4] * in1[0];
  t20 = t22 * (t7 * (t4 * 3.0 + t5 * 3.0) / 12.0 + in1[4] * in1[4] * (in1[33] *
    in1[33]) / 300.0) * t16 * 3.1415926535897931 * -0.2;
  out1[21] = t20;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t20;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t22 * t7 * t16 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0) * -0.2;
  st.site = &ac_emlrtRSI;
  t17 = in2[9] * in2[9];
  st.site = &bc_emlrtRSI;
  t18 = in2[10] * in2[10];
  st.site = &cc_emlrtRSI;
  t19 = in2[11] * in2[11];
  t20 = ((-t17 - t18) - t19) + 1.0;
  st.site = &dc_emlrtRSI;
  if (t20 < 0.0) {
    b_st.site = &pb_emlrtRSI;
    error(&b_st);
  }

  t4 = muDoubleScalarSqrt(t20);
  t21 = 1.0 / t4;
  t22 = in2[11] * 2.0;
  t43 = in2[9] * in2[10];
  t23 = t43 * t21 * 2.0;
  st.site = &ec_emlrtRSI;
  t4 *= 2.0;
  t5 = in2[9] * in2[11] * t21 * 2.0;
  t7 = in2[9] * 2.0;
  t16 = in2[10] * in2[11] * t21 * 2.0;
  memset(&out2[0], 0, 36U * sizeof(real_T));
  out2[36] = 1.0;
  out2[37] = 0.0;
  out2[38] = 0.0;
  out2[39] = 0.0;
  out2[40] = 0.0;
  out2[41] = 0.0;
  out2[42] = 0.0;
  out2[43] = 1.0;
  out2[44] = 0.0;
  out2[45] = 0.0;
  out2[46] = 0.0;
  out2[47] = 0.0;
  out2[48] = 0.0;
  out2[49] = 0.0;
  out2[50] = 1.0;
  out2[51] = 0.0;
  out2[52] = 0.0;
  out2[53] = 0.0;
  out2[54] = 0.0;
  out2[55] = 0.0;
  out2[56] = 0.0;
  out2[57] = t4 + t17 * t21 * 2.0;
  out2[58] = -t22 + t23;
  out2[59] = in2[10] * 2.0 + t5;
  out2[60] = 0.0;
  out2[61] = 0.0;
  out2[62] = 0.0;
  out2[63] = t22 + t23;
  out2[64] = t4 + t18 * t21 * 2.0;
  out2[65] = -t7 + t16;
  out2[66] = 0.0;
  out2[67] = 0.0;
  out2[68] = 0.0;
  out2[69] = in2[10] * -2.0 + t5;
  out2[70] = t7 + t16;
  out2[71] = t4 + t19 * t21 * 2.0;
  memset(&out2[72], 0, 108U * sizeof(real_T));
  st.site = &fc_emlrtRSI;
  t29 = 1.0 / muDoubleScalarPower(t20, 1.5);
  t30 = in2[10] * t21 * 2.0;
  t31 = in2[10] * t17 * t29 * 2.0;
  t32 = in2[9] * t21 * 2.0;
  t33 = t43 * in2[11] * t29 * 2.0;
  t4 = in2[11] * t21 * 2.0;
  t5 = in2[11] * t17 * t29 * 2.0;
  t7 = t30 + t31;
  t16 = in2[9] * t18 * t29 * 2.0;
  t20 = t32 + t16;
  t22 = in2[11] * t18 * t29 * 2.0;
  t23 = t4 + t5;
  t43 = in2[9] * t19 * t29 * 2.0;
  t21 = t4 + t22;
  t45 = in2[10] * t19 * t29 * 2.0;
  t46 = t32 + t43;
  t47 = t30 + t45;
  memset(&out3[0], 0, 57U * sizeof(real_T));
  out3[57] = (t7 * in2[40] + t23 * in2[41]) + in2[39] * (t32 + in2[9] * t17 *
    t29 * 2.0);
  out3[58] = (t7 * in2[39] + (t33 + 2.0) * in2[41]) - in2[40] * (t32 - t16);
  out3[59] = ((t33 - 2.0) * in2[40] + t23 * in2[39]) - in2[41] * (t32 - t43);
  out3[60] = 0.0;
  out3[61] = 0.0;
  out3[62] = 0.0;
  out3[63] = (t20 * in2[40] + (t33 - 2.0) * in2[41]) - in2[39] * (t30 - t31);
  out3[64] = (t20 * in2[39] + t21 * in2[41]) + in2[40] * (t30 + in2[10] * t18 *
    t29 * 2.0);
  out3[65] = ((t33 + 2.0) * in2[39] + t21 * in2[40]) - in2[41] * (t30 - t45);
  out3[66] = 0.0;
  out3[67] = 0.0;
  out3[68] = 0.0;
  out3[69] = ((t33 + 2.0) * in2[40] + t46 * in2[41]) - in2[39] * (t4 - t5);
  out3[70] = ((t33 - 2.0) * in2[39] + t47 * in2[41]) - in2[40] * (t4 - t22);
  out3[71] = (t46 * in2[39] + t47 * in2[40]) + in2[41] * (t4 + in2[11] * t19 *
    t29 * 2.0);
  memset(&out3[72], 0, 108U * sizeof(real_T));
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF2.c) */
