/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF5.c
 *
 * Code generation for function 'massF5'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF5.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo dd_emlrtRSI = { 23, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo ed_emlrtRSI = { 25, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo fd_emlrtRSI = { 26, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo gd_emlrtRSI = { 33, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo hd_emlrtRSI = { 34, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo id_emlrtRSI = { 40, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo jd_emlrtRSI = { 41, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo kd_emlrtRSI = { 42, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo ld_emlrtRSI = { 44, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo md_emlrtRSI = { 47, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo nd_emlrtRSI = { 55, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

/* Function Definitions */
void massF5(const emlrtStack *sp, const real_T in1[34], const real_T in2[60],
            real_T out1[36], real_T out2[180], real_T out3[180], real_T out4[6])
{
  real_T t4;
  real_T t5;
  real_T t7;
  real_T t16;
  real_T t20;
  real_T t22;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t21;
  real_T t43;
  real_T t23;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t45;
  real_T t46;
  real_T t47;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF5 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF5(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 19:49:54 */
  st.site = &dd_emlrtRSI;
  st.site = &ed_emlrtRSI;
  t4 = in1[2] * in1[2];
  st.site = &fd_emlrtRSI;
  t5 = in1[3] * in1[3];
  t7 = 1.0 / in1[33];
  st.site = &gd_emlrtRSI;
  st.site = &hd_emlrtRSI;
  t16 = t4 - t5;
  t20 = -in1[0] * ((in1[18] * in1[18] * 6.0 + t4) - t5) * 3.1415926535897931;
  out1[0] = t20;
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = t20;
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = t20;
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  t22 = in1[4] * in1[0];
  t20 = t22 * (t7 * (t4 * 3.0 + t5 * 3.0) / 12.0 + in1[4] * in1[4] * (in1[33] *
    in1[33]) / 300.0) * t16 * 3.1415926535897931 * -0.2;
  out1[21] = t20;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t20;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = t22 * t7 * t16 * 3.1415926535897931 * (t4 / 2.0 + t5 / 2.0) * -0.2;
  st.site = &id_emlrtRSI;
  t17 = in2[27] * in2[27];
  st.site = &jd_emlrtRSI;
  t18 = in2[28] * in2[28];
  st.site = &kd_emlrtRSI;
  t19 = in2[29] * in2[29];
  t20 = ((-t17 - t18) - t19) + 1.0;
  st.site = &ld_emlrtRSI;
  if (t20 < 0.0) {
    b_st.site = &pb_emlrtRSI;
    error(&b_st);
  }

  t4 = muDoubleScalarSqrt(t20);
  t21 = 1.0 / t4;
  t22 = in2[29] * 2.0;
  t43 = in2[27] * in2[28];
  t23 = t43 * t21 * 2.0;
  st.site = &md_emlrtRSI;
  t4 *= 2.0;
  t5 = in2[27] * in2[29] * t21 * 2.0;
  t7 = in2[27] * 2.0;
  t16 = in2[28] * in2[29] * t21 * 2.0;
  memset(&out2[0], 0, 144U * sizeof(real_T));
  out2[144] = 1.0;
  out2[145] = 0.0;
  out2[146] = 0.0;
  out2[147] = 0.0;
  out2[148] = 0.0;
  out2[149] = 0.0;
  out2[150] = 0.0;
  out2[151] = 1.0;
  out2[152] = 0.0;
  out2[153] = 0.0;
  out2[154] = 0.0;
  out2[155] = 0.0;
  out2[156] = 0.0;
  out2[157] = 0.0;
  out2[158] = 1.0;
  out2[159] = 0.0;
  out2[160] = 0.0;
  out2[161] = 0.0;
  out2[162] = 0.0;
  out2[163] = 0.0;
  out2[164] = 0.0;
  out2[165] = t4 + t17 * t21 * 2.0;
  out2[166] = -t22 + t23;
  out2[167] = in2[28] * 2.0 + t5;
  out2[168] = 0.0;
  out2[169] = 0.0;
  out2[170] = 0.0;
  out2[171] = t22 + t23;
  out2[172] = t4 + t18 * t21 * 2.0;
  out2[173] = -t7 + t16;
  out2[174] = 0.0;
  out2[175] = 0.0;
  out2[176] = 0.0;
  out2[177] = in2[28] * -2.0 + t5;
  out2[178] = t7 + t16;
  out2[179] = t4 + t19 * t21 * 2.0;
  st.site = &nd_emlrtRSI;
  t29 = 1.0 / muDoubleScalarPower(t20, 1.5);
  t30 = in2[28] * t21 * 2.0;
  t31 = in2[28] * t17 * t29 * 2.0;
  t32 = in2[27] * t21 * 2.0;
  t33 = t43 * in2[29] * t29 * 2.0;
  t4 = in2[29] * t21 * 2.0;
  t5 = in2[29] * t17 * t29 * 2.0;
  t7 = t30 + t31;
  t16 = in2[27] * t18 * t29 * 2.0;
  t20 = t32 + t16;
  t22 = in2[29] * t18 * t29 * 2.0;
  t23 = t4 + t5;
  t43 = in2[27] * t19 * t29 * 2.0;
  t21 = t4 + t22;
  t45 = in2[28] * t19 * t29 * 2.0;
  t46 = t32 + t43;
  t47 = t30 + t45;
  memset(&out3[0], 0, 165U * sizeof(real_T));
  out3[165] = (t7 * in2[58] + t23 * in2[59]) + in2[57] * (t32 + in2[27] * t17 *
    t29 * 2.0);
  out3[166] = (t7 * in2[57] + (t33 + 2.0) * in2[59]) - in2[58] * (t32 - t16);
  out3[167] = ((t33 - 2.0) * in2[58] + t23 * in2[57]) - in2[59] * (t32 - t43);
  out3[168] = 0.0;
  out3[169] = 0.0;
  out3[170] = 0.0;
  out3[171] = (t20 * in2[58] + (t33 - 2.0) * in2[59]) - in2[57] * (t30 - t31);
  out3[172] = (t20 * in2[57] + t21 * in2[59]) + in2[58] * (t30 + in2[28] * t18 *
    t29 * 2.0);
  out3[173] = ((t33 + 2.0) * in2[57] + t21 * in2[58]) - in2[59] * (t30 - t45);
  out3[174] = 0.0;
  out3[175] = 0.0;
  out3[176] = 0.0;
  out3[177] = ((t33 + 2.0) * in2[58] + t46 * in2[59]) - in2[57] * (t4 - t5);
  out3[178] = ((t33 - 2.0) * in2[57] + t47 * in2[59]) - in2[58] * (t4 - t22);
  out3[179] = (t46 * in2[57] + t47 * in2[58]) + in2[59] * (t4 + in2[29] * t19 *
    t29 * 2.0);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF5.c) */
