/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "massF2.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 16,    /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 17,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 18,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 20,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 21,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 33,  /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/massF2.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T out1[36], real_T out2[36], real_T out3[36], real_T
            out4[6])
{
  static const real_T dv0[36] = { 0.01347, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01347,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01347, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    1.133444375E-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.133444375E-6, 0.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 3.7884375E-7 };

  int32_T i;
  static const real_T dv1[6] = { 0.0, 0.0, 9.81, 0.0, 0.0, 0.0 };

  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t22;
  real_T t6;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t36;
  real_T t11_tmp;
  real_T t11;
  real_T t12;
  real_T t43;
  real_T t13;
  real_T t14;
  real_T t45;
  real_T t15;
  real_T t16;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t24;
  real_T t25_tmp;
  real_T t25;
  real_T t27;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  emlrtStack st;
  emlrtStack b_st;
  (void)in1;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  memcpy(&out1[0], &dv0[0], 36U * sizeof(real_T));
  for (i = 0; i < 6; i++) {
    out4[i] = dv1[i];
  }

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     15-May-2019 14:15:52 */
  st.site = &emlrtRSI;
  t2 = in2[3] * in2[3];
  st.site = &b_emlrtRSI;
  t3 = in2[4] * in2[4];
  st.site = &c_emlrtRSI;
  t4 = in2[5] * in2[5];
  t5 = ((-t2 - t3) - t4) + 1.0;
  st.site = &d_emlrtRSI;
  if (t5 < 0.0) {
    b_st.site = &h_emlrtRSI;
    error(&b_st);
  }

  t22 = muDoubleScalarSqrt(t5);
  t6 = 1.0 / t22;
  st.site = &e_emlrtRSI;
  t8 = t22 * 0.0145;
  t9 = in2[5] * 0.0145;
  t10 = in2[5] * 2.0;
  t36 = in2[3] * in2[4];
  t11_tmp = t36 * t6;
  t11 = t11_tmp * 2.0;
  t12 = t22 * 2.0;
  t43 = in2[3] * in2[5] * t6;
  t13 = t43 * 2.0;
  t14 = in2[3] * 2.0;
  t45 = in2[4] * in2[5] * t6;
  t15 = t45 * 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  t22 = t11_tmp * 0.0145;
  out2[18] = t9 - t22;
  t11_tmp = t2 * t6;
  out2[19] = -t8 + t11_tmp * 0.0145;
  out2[20] = in2[3] * -0.029;
  out2[21] = t12 + t11_tmp * 2.0;
  out2[22] = -t10 + t11;
  out2[23] = in2[4] * 2.0 + t13;
  t11_tmp = t3 * t6;
  out2[24] = t8 - t11_tmp * 0.0145;
  out2[25] = t9 + t22;
  out2[26] = in2[4] * -0.029;
  out2[27] = t10 + t11;
  out2[28] = t12 + t11_tmp * 2.0;
  out2[29] = -t14 + t15;
  out2[30] = in2[3] * 0.0145 - t45 * 0.0145;
  out2[31] = in2[4] * 0.0145 + t43 * 0.0145;
  out2[32] = 0.0;
  out2[33] = in2[4] * -2.0 + t13;
  out2[34] = t14 + t15;
  out2[35] = t12 + t4 * t6 * 2.0;
  st.site = &f_emlrtRSI;
  t16 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t17_tmp = in2[3] * t6;
  t17 = t17_tmp * 0.0145;
  t14 = in2[3] * t3 * t16;
  t19 = t17 + t14 * 0.0145;
  t12 = t36 * in2[5] * t16;
  t20 = t12 * 0.0145;
  t43 = in2[5] * t6;
  t22 = t43 * 0.0145;
  t45 = in2[5] * t3 * t16;
  t24 = t22 + t45 * 0.0145;
  t25_tmp = in2[4] * t6;
  t25 = t25_tmp * 0.0145;
  t11_tmp = in2[4] * t2 * t16;
  t27 = t25 + t11_tmp * 0.0145;
  t13 = in2[5] * t2 * t16;
  t30 = t22 + t13 * 0.0145;
  t31 = t25_tmp * 2.0;
  t32 = t11_tmp * 2.0;
  t33 = t17_tmp * 2.0;
  t34 = t12 * 2.0;
  t35 = t43 * 2.0;
  t36 = t13 * 2.0;
  t6 = t31 + t32;
  t11 = t14 * 2.0;
  t22 = t33 + t11;
  t12 = t45 * 2.0;
  t43 = t35 + t36;
  t13 = in2[3] * t4 * t16;
  t14 = t13 * 2.0;
  t45 = t35 + t12;
  t15 = in2[4] * t4 * t16;
  t5 = t15 * 2.0;
  t8 = t33 + t14;
  t9 = t31 + t5;
  memset(&out3[0], 0, 18U * sizeof(real_T));
  t10 = t27 * in2[9];
  out3[18] = (-t19 * in2[10] - (t20 - 0.0145) * in2[11]) - t10;
  t11_tmp = in2[3] * t2 * t16;
  out3[19] = (in2[9] * (t17_tmp * 0.0435 + t11_tmp * 0.0145) + t27 * in2[10]) +
    t30 * in2[11];
  out3[20] = in2[9] * -0.029;
  out3[21] = (t6 * in2[10] + t43 * in2[11]) + in2[9] * (t33 + t11_tmp * 2.0);
  out3[22] = (t6 * in2[9] + (t34 + 2.0) * in2[11]) - in2[10] * (t33 - t11);
  out3[23] = ((t34 - 2.0) * in2[10] + t43 * in2[9]) - in2[11] * (t33 - t14);
  t11_tmp = in2[4] * t3 * t16;
  out3[24] = (-in2[10] * (t25_tmp * 0.0435 + t11_tmp * 0.0145) - t19 * in2[9]) -
    t24 * in2[11];
  out3[25] = (t19 * in2[10] + t10) + (t20 + 0.0145) * in2[11];
  out3[26] = in2[10] * -0.029;
  out3[27] = (t22 * in2[10] + (t34 - 2.0) * in2[11]) - in2[9] * (t31 - t32);
  out3[28] = (t22 * in2[9] + t45 * in2[11]) + in2[10] * (t31 + t11_tmp * 2.0);
  out3[29] = ((t34 + 2.0) * in2[9] + t45 * in2[10]) - in2[11] * (t31 - t5);
  out3[30] = (-(t20 - 0.0145) * in2[9] - t24 * in2[10]) - in2[11] * (t25 + t15 *
    0.0145);
  out3[31] = ((t20 + 0.0145) * in2[10] + t30 * in2[9]) + in2[11] * (t17 + t13 *
    0.0145);
  out3[32] = 0.0;
  out3[33] = ((t34 + 2.0) * in2[10] + t8 * in2[11]) - in2[9] * (t35 - t36);
  out3[34] = ((t34 - 2.0) * in2[9] + t9 * in2[11]) - in2[10] * (t35 - t12);
  out3[35] = (t8 * in2[9] + t9 * in2[10]) + in2[11] * (t35 + in2[5] * t4 * t16 *
    2.0);
}

/* End of code generation (massF2.c) */
