/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rjtipF.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 47,    /* lineNo */
  "rjtipF",                            /* fcnName */
  "C:\\Users\\customer\\MEGAsync\\Hadi\\TMTDyn\\Code\\TMTDyn_beta\\v5_Latest_Version_Examples\\eom\\rjtipF.m"/* pathName */
};

static emlrtRTEInfo emlrtRTEI = { 13,  /* lineNo */
  9,                                   /* colNo */
  "sqrt",                              /* fName */
  "C:\\Program Files\\MATLAB\\R2020b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T s, real_T ds, real_T t_sym, real_T out1[60])
{
  emlrtStack st;
  real_T t100;
  real_T t104;
  real_T t111;
  real_T t112;
  real_T t113;
  real_T t117;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t136;
  real_T t136_tmp;
  real_T t137;
  real_T t137_tmp;
  real_T t15;
  real_T t19;
  real_T t2;
  real_T t23;
  real_T t3;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t5;
  real_T t97;
  real_T t98;
  real_T t99;
  (void)s;
  (void)ds;
  (void)t_sym;
  st.prev = sp;
  st.tls = sp->tls;

  /* RJTIPF */
  /*     OUT1 = RJTIPF(IN1,IN2,S,DS,T_SYM) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     14-Jun-2021 23:16:02 */
  t2 = in1[4] / 3.0;
  t3 = in2[3] / 2.0;
  t4 = in2[4] / 2.0;
  t5 = in2[5] / 2.0;
  t15 = in2[3] * in2[9] / 4.0;
  t19 = in2[4] * in2[10] / 4.0;
  t23 = in2[5] * in2[11] / 4.0;
  st.site = &emlrtRSI;
  if (in1[33] < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t33 = in2[8] + t2;
  t34 = in2[14] + t2;
  t35 = in1[3] * (1.0 / muDoubleScalarSqrt(in1[33]));
  t41 = ((t15 + t19) + t23) - 1.0;
  t40 = (in2[7] * t3 + in2[4] * in2[6] * -0.5) + t33;
  t44 = ((-t15 + -t19) + -t23) + 1.0;
  t47 = ((t3 + in2[9] / 2.0) + in2[4] * in2[11] / 4.0) + -(in2[5] * in2[10] /
    4.0);
  t48 = ((t4 + in2[10] / 2.0) + in2[5] * in2[9] / 4.0) + -(in2[3] * in2[11] /
    4.0);
  t49 = ((t5 + in2[11] / 2.0) + in2[3] * in2[10] / 4.0) + -(in2[4] * in2[9] /
    4.0);
  t42 = (in2[7] + in2[6] * t5) + in2[3] * t33 * -0.5;
  t43 = (in2[6] + in2[5] * in2[7] * -0.5) + t4 * t33;
  t33 = (in2[6] * t3 + in2[7] * t4) + t5 * t33;
  t15 = in2[15] * t47 / 2.0;
  t19 = in2[16] * t48 / 2.0;
  t23 = in2[17] * t49 / 2.0;
  t100 = (in2[12] * t47 + in2[13] * t48) + t34 * t49;
  t104 = ((t41 + t15) + t19) + t23;
  t97 = (in2[12] * t48 + -(in2[13] * t47)) + t34 * t41;
  t98 = (in2[12] * t41 + in2[13] * t49) + -(t34 * t48);
  t99 = (in2[13] * t41 + -(in2[12] * t49)) + t34 * t47;
  t111 = ((t47 + -(in2[15] * t41 / 2.0)) + in2[17] * t48 / 2.0) + -(in2[16] *
    t49 / 2.0);
  t112 = ((t48 + -(in2[16] * t41 / 2.0)) + in2[15] * t49 / 2.0) + -(in2[17] *
    t47 / 2.0);
  t113 = ((t49 + -(in2[17] * t41 / 2.0)) + in2[16] * t47 / 2.0) + -(in2[15] *
    t48 / 2.0);
  t117 = t104 * t104;
  t124 = ((t44 + -t15) + -t19) + -t23;
  t121 = t111 * t111;
  t122 = t112 * t112;
  t123 = t113 * t113;
  t15 = in1[4] * t104;
  t136_tmp = (((in2[1] + t42) + t5 * t43) + in2[3] * t40 * -0.5) + t4 * t33;
  t19 = (((t136_tmp + t41 * t99) + t47 * t97) + t48 * t100) + -(t49 * t98);
  t136 = (t19 + t15 * t111 * 0.66666666666666663) + in1[4] * t112 * t113 *
    0.66666666666666663;
  t137_tmp = (((in2[0] + t43) + t4 * t40) + in2[5] * t42 * -0.5) + t3 * t33;
  t23 = (((t137_tmp + t41 * t98) + t49 * t99) + t47 * t100) + -(t48 * t97);
  t137 = (t23 + -(t15 * t112 * 0.66666666666666663)) + in1[4] * t111 * t113 *
    0.66666666666666663;
  t34 = (((in2[2] + t40) + t3 * t42) + in2[4] * t43 * -0.5) + t5 * t33;
  t15 = (((t34 + t41 * t97) + t48 * t98) + t49 * t100) + -(t47 * t99);
  t33 = (((t15 + t2 * t117) + t2 * t123) + in1[4] * t121 * -0.33333333333333331)
    + in1[4] * t122 * -0.33333333333333331;
  out1[0] = in2[0];
  out1[1] = t137_tmp;
  out1[2] = t23;
  out1[3] = t137;
  out1[4] = in2[1];
  out1[5] = t136_tmp;
  out1[6] = t19;
  out1[7] = t136;
  out1[8] = in2[2];
  out1[9] = t34;
  out1[10] = t15;
  out1[11] = t33;
  t19 = in1[4] * in2[3];
  out1[12] = (in2[0] + in2[4] * t2) + t19 * in2[5] / 6.0;
  t23 = in1[4] * t41;
  out1[13] = (t137_tmp - t23 * t48 * 0.66666666666666663) + in1[4] * t47 * t49 *
    0.66666666666666663;
  out1[14] = t137;
  t15 = in1[16] * t104;
  out1[15] = (t137 - t15 * t112 * 2.0) + in1[16] * t111 * t113 * 2.0;
  out1[16] = (in2[1] - t19 / 3.0) + in1[4] * in2[4] * in2[5] / 6.0;
  out1[17] = (t136_tmp + t23 * t47 * 0.66666666666666663) + in1[4] * t48 * t49 *
    0.66666666666666663;
  out1[18] = t136;
  out1[19] = (t136 + t15 * t111 * 2.0) + in1[16] * t112 * t113 * 2.0;
  out1[20] = (((in2[2] + t2) - in1[4] * (in2[3] * in2[3]) / 12.0) - in1[4] *
              (in2[4] * in2[4]) / 12.0) + in1[4] * (in2[5] * in2[5]) / 12.0;
  out1[21] = (((t34 - in1[4] * (t47 * t47) / 3.0) - in1[4] * (t48 * t48) / 3.0)
              + t2 * (t41 * t41)) + t2 * (t49 * t49);
  out1[22] = t33;
  out1[23] = (((t33 + in1[16] * t117) - in1[16] * t121) - in1[16] * t122) + in1
    [16] * t123;
  out1[24] = 1.0;
  out1[25] = t44;
  out1[26] = t124;
  out1[27] = t124;
  out1[28] = t3;
  out1[29] = t47;
  out1[30] = t111;
  out1[31] = t111;
  out1[32] = t4;
  out1[33] = t48;
  out1[34] = t112;
  out1[35] = t112;
  out1[36] = t5;
  out1[37] = t49;
  out1[38] = t113;
  out1[39] = t113;
  out1[40] = 1.0;
  out1[41] = t44;
  out1[42] = t124;
  out1[43] = t124;
  out1[44] = t3;
  out1[45] = t47;
  out1[46] = t111;
  out1[47] = t111;
  out1[48] = t4;
  out1[49] = t48;
  out1[50] = t112;
  out1[51] = t112;
  out1[52] = t5;
  out1[53] = t49;
  out1[54] = t113;
  out1[55] = t113;
  out1[56] = t35;
  out1[57] = t35;
  out1[58] = t35;
  out1[59] = in1[17];
}

/* End of code generation (rjtipF.c) */
