/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF1.c
 *
 * Code generation for function 'sprdmpF1'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "sprdmpF1.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 24,    /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 25,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 28,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 30,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 31,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 32,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 40,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 52,  /* lineNo */
  "sprdmpF1",                          /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/sprdmpF1.m"/* pathName */
};

static emlrtRSInfo i_emlrtRSI = { 49,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

static emlrtRSInfo j_emlrtRSI = { 61,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

/* Function Definitions */
void sprdmpF1(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
              real_T s, real_T out1[6], real_T *out2, real_T *out3, real_T *out4,
              real_T *out5, real_T out6[6], real_T out7[6], real_T *out8)
{
  int32_T i;
  static const int8_T iv0[6] = { 1, 0, 0, 0, 0, 0 };

  real_T t2;
  real_T t16;
  real_T t4;
  real_T a;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out1[i] = iv0[i];
  }

  /* SPRDMPF1 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 21:11:20 */
  t2 = 1.0 / in1[33];
  t16 = muDoubleScalarCos(in1[20]);
  t4 = 1.0 / in1[4];
  st.site = &emlrtRSI;
  b_st.site = &i_emlrtRSI;
  st.site = &b_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  st.site = &c_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  a = muDoubleScalarSin(in1[20]);
  st.site = &d_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  st.site = &e_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  st.site = &f_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  t16 = t2 * (in1[2] * in1[2] - in1[3] * in1[3]) - in1[18] * in1[18] * (1.0 / (a
    * a)) * (in1[33] * in1[33] * (t16 * t16) - 1.0) * 6.0;
  *out2 = in1[1] * in2[0] * t2 * t4 * t16 * 3.1415926535897931 / 3.0;
  st.site = &g_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  *out3 = -in1[5] * in2[6] * muDoubleScalarPower(muDoubleScalarAbs(in2[6]), in1
    [11] - 1.0);
  *out4 = 0.0;
  *out5 = in2[0];
  out6[0] = in1[1] * t2 * t4 * t16 * 3.1415926535897931 * -0.33333333333333331;
  out6[1] = 0.0;
  out6[2] = 0.0;
  out6[3] = 0.0;
  out6[4] = 0.0;
  out6[5] = 0.0;
  st.site = &h_emlrtRSI;
  b_st.site = &i_emlrtRSI;
  if ((in2[6] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &j_emlrtRSI;
    error(&c_st);
  }

  out7[0] = -in1[5] * muDoubleScalarPower(in2[6], in1[11] - 1.0);
  out7[1] = 0.0;
  out7[2] = 0.0;
  out7[3] = 0.0;
  out7[4] = 0.0;
  out7[5] = 0.0;
  *out8 = 1.0;
}

/* End of code generation (sprdmpF1.c) */
