function out1 = sprdmpDl7(in1,in2,s,ds,t_sym)
%SPRDMPDL7
%    OUT1 = SPRDMPDL7(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:59:00

q7 = in2(7,:);
out1 = q7;
