function out1 = sprdmpKx12(in1,in2,s,ds,t_sym)
%SPRDMPKX12
%    OUT1 = SPRDMPKX12(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Apr-2021 15:51:21

out1 = 0.0;
