function [out1,out2,out3,out4,out5,out6,out7,out8] = sprdmpF6(in1,in2,s)
%SPRDMPF6
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF6(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Feb-2019 03:04:29

lambda_sym = in1(:,34);
q6 = in2(:,6);
u6 = in2(:,36);
out1 = [0.0;0.0;0.0;0.0;0.0;1.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
if nargout > 1
    t4 = lambda_sym.^2;
    t5 = t4.*4.439506172839557e-3;
    t2 = t5-1.0;
    t3 = 1.0./lambda_sym;
    t6 = t2.^2;
    t7 = t6.*2.36469959048496e-10;
    t8 = 1.0./lambda_sym.^2;
    t9 = t7-t8.*2.4004e-8;
    out2 = q6.*t3.*t9.*pi.*3.416666666666666e6;
end
if nargout > 2
    out3 = u6.*(-1.0./2.0);
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = q6;
end
if nargout > 5
    out6 = [0.0,0.0,0.0,0.0,0.0,t3.*t9.*pi.*(-3.416666666666666e6),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 6
    out7 = [0.0,0.0,0.0,0.0,0.0,-1.0./2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
end
if nargout > 7
    out8 = 1.0;
end
