function fj_vd_mat = fj_vd_matF(in1,in2,s)
%FJ_VD_MATF
%    FJ_VD_MAT = FJ_VD_MATF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jan-2019 17:24:25

mu_x_sym = in1(:,6);
mu_y_sym = in1(:,7);
mu_z_sym = in1(:,8);
mu_xx_sym = in1(:,9);
mu_yy_sym = in1(:,10);
mu_zz_sym = in1(:,11);
fj_vd_mat = reshape([-mu_x_sym,0.0,0.0,0.0,0.0,0.0,0.0,-mu_y_sym,0.0,0.0,0.0,0.0,0.0,0.0,-mu_z_sym,0.0,0.0,0.0,0.0,0.0,0.0,-mu_xx_sym,0.0,0.0,0.0,0.0,0.0,0.0,-mu_yy_sym,0.0,0.0,0.0,0.0,0.0,0.0,-mu_zz_sym],[6,6]);
