function [out1,out2,out3,out4,out5,out6,out7,out8] = sprdmpF10(in1,in2,s)
%SPRDMPF10
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF10(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Jan-2019 22:38:45

E_s_sym = in1(:,2);
gamma_sym = in1(:,21);
l_s_sym = in1(:,5);
lambda_sym = in1(:,34);
mu_zz_sym = in1(:,11);
mu_pow_sym = in1(:,12);
q10 = in2(:,10);
r_p1_sym = in1(:,19);
r_s1_sym = in1(:,3);
r_s2_sym = in1(:,4);
u10 = in2(:,22);
out1 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.0;0.0;0.0];
if nargout > 1
    out2 = (E_s_sym.*q10.*pi.*(1.0./lambda_sym.^2.*(r_s1_sym.^4-r_s2_sym.^4)+r_p1_sym.^4.*1.0./sin(gamma_sym).^4.*(lambda_sym.^2.*cos(gamma_sym).^2-1.0).^2.*6.0))./(l_s_sym.*lambda_sym.*3.0);
end
if nargout > 2
    out3 = -mu_zz_sym.*u10.*abs(u10).^(mu_pow_sym-1.0);
end
if nargout > 3
    out4 = 0.0;
end
if nargout > 4
    out5 = q10;
end
if nargout > 5
    out6 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(E_s_sym.*pi.*(1.0./lambda_sym.^2.*(r_s1_sym.^4-r_s2_sym.^4)+r_p1_sym.^4.*1.0./sin(gamma_sym).^4.*(lambda_sym.^2.*cos(gamma_sym).^2-1.0).^2.*6.0).*(-1.0./3.0))./(l_s_sym.*lambda_sym),0.0,0.0];
end
if nargout > 6
    out7 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-mu_zz_sym.*u10.^(mu_pow_sym-1.0),0.0,0.0];
end
if nargout > 7
    out8 = 1.0;
end
