/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF7.c
 *
 * Code generation for function 'sprdmpF7'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "sprdmpF7.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 28,    /* lineNo */
  "sprdmpF7",                          /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/sprdmpF7.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 33,  /* lineNo */
  "sprdmpF7",                          /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/sprdmpF7.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 35,  /* lineNo */
  "sprdmpF7",                          /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/sprdmpF7.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 41,  /* lineNo */
  "sprdmpF7",                          /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/sprdmpF7.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 60,  /* lineNo */
  "sprdmpF7",                          /* fcnName */
  "/home/hadi/Safe/MEGAsync/Hadi/TMTDyn/Code/TMTDyn/Beta/v1.0/Rods/1. STIFF-FLOP/code/sprdmpF7.m"/* pathName */
};

static emlrtRSInfo g_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void sprdmpF7(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
              real_T s, real_T out1[36], real_T out2[6], real_T out3[6], real_T
              out4[6], real_T *out5, real_T out6[36], real_T out7[36], real_T
              *out8)
{
  static const real_T dv0[36] = { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0 };

  real_T t2;
  real_T t4_tmp;
  real_T t6;
  real_T t8;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t17;
  real_T t18_tmp;
  real_T t18;
  real_T t19;
  real_T t20;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t26;
  emlrtStack st;
  emlrtStack b_st;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  memcpy(&out1[0], &dv0[0], 36U * sizeof(real_T));

  /* SPRDMPF7 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF7(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     15-May-2019 14:15:55 */
  t2 = 1.0 / in1[33];
  st.site = &emlrtRSI;
  t4_tmp = in1[33] * in1[33];
  t6 = (t2 * 0.000136 + t4_tmp * 1.672238728974578E-7) - 3.7667223872897458E-5;
  t8 = t4_tmp * 0.0044395061728395571;
  st.site = &b_emlrtRSI;
  st.site = &c_emlrtRSI;
  t12 = (t8 - 1.0) * (t8 - 1.0) * 2.36469959048496E-10 - 1.0 / t4_tmp *
    2.4004E-8;
  t13 = t12 * 3.1415926535897931 * 1.025E+6;
  t14 = t4_tmp * 2.7870645482909631E-8;
  st.site = &d_emlrtRSI;
  if (in1[33] < 0.0) {
    b_st.site = &g_emlrtRSI;
    error(&b_st);
  }

  t17 = 1.0 / muDoubleScalarSqrt(in1[33]);
  t18_tmp = t2 * t6 * 3.1415926535897931;
  t18 = t18_tmp * 1.366666666666667E+6;
  t8 = t2 * (t14 - 6.2778706454829094E-6) * 3.1415926535897931;
  t19 = t13 - t8 * 888.67500000000007;
  t20 = t13 - t8 * 888.675;
  out2[0] = in2[0] * t2 * t6 * 3.1415926535897931 * -1.366666666666667E+6;
  out2[1] = in2[1] * t2 * t6 * 3.1415926535897931 * -1.366666666666667E+6;
  out2[2] = t18_tmp * (in2[2] - 0.05) * -4.1E+6;
  out2[3] = in2[3] * t2 * t19 * 2.0;
  out2[4] = in2[4] * t2 * t20 * 2.0;
  out2[5] = in2[5] * t2 * t12 * 3.1415926535897931 * 1.366666666666667E+6;
  t6 = muDoubleScalarAbs(in2[6]);
  t22 = muDoubleScalarAbs(in2[7]);
  t23 = muDoubleScalarAbs(in2[8]);
  t24 = muDoubleScalarAbs(in2[9]);
  t25 = muDoubleScalarAbs(in2[10]);
  t26 = muDoubleScalarAbs(in2[11]);
  out3[0] = t6 * in2[6] * -100.0;
  out3[1] = t22 * in2[7] * -100.0;
  out3[2] = t23 * in2[8] * -100.0;
  out3[3] = t24 * in2[9] * -0.04;
  out3[4] = t25 * in2[10] * -0.04;
  out3[5] = t26 * in2[11] * -0.04;
  out4[0] = 0.0;
  out4[1] = 0.0;
  out4[2] = -(t14 - 6.2778706454829094E-6) * 3.1415926535897931 * ((in1[21] *
    2.0 + in1[23] * 2.0) + in1[25] * 2.0);
  t4_tmp = in1[21] * (t14 - 6.2778706454829094E-6) * t17 * 3.1415926535897931;
  t13 = in1[23] * (t14 - 6.2778706454829094E-6) * t17 * 3.1415926535897931;
  t8 = in1[25] * (t14 - 6.2778706454829094E-6) * t17 * 3.1415926535897931;
  out4[3] = (t4_tmp * -0.01594117647058824 + t13 * 0.0079705882352941182) + t8 *
    0.0079705882352941147;
  out4[4] = (t4_tmp * 1.3010426069826049E-18 + t13 * 0.01380546378974017) - t8 *
    0.01380546378974017;
  out4[5] = 0.0;
  st.site = &e_emlrtRSI;
  st.site = &e_emlrtRSI;
  st.site = &e_emlrtRSI;
  st.site = &e_emlrtRSI;
  t8 = (in2[0] * in2[0] + in2[1] * in2[1]) + in2[2] * in2[2];
  if (t8 < 0.0) {
    b_st.site = &g_emlrtRSI;
    error(&b_st);
  }

  t8 = muDoubleScalarSqrt(t8);
  *out5 = t8 - 0.05;
  out6[0] = t18;
  out6[1] = 0.0;
  out6[2] = 0.0;
  out6[3] = 0.0;
  out6[4] = 0.0;
  out6[5] = 0.0;
  out6[6] = 0.0;
  out6[7] = t18;
  out6[8] = 0.0;
  out6[9] = 0.0;
  out6[10] = 0.0;
  out6[11] = 0.0;
  out6[12] = 0.0;
  out6[13] = 0.0;
  out6[14] = t18_tmp * 4.1E+6;
  out6[15] = 0.0;
  out6[16] = 0.0;
  out6[17] = 0.0;
  out6[18] = 0.0;
  out6[19] = 0.0;
  out6[20] = 0.0;
  out6[21] = t2 * t19 * -2.0;
  out6[22] = 0.0;
  out6[23] = 0.0;
  out6[24] = 0.0;
  out6[25] = 0.0;
  out6[26] = 0.0;
  out6[27] = 0.0;
  out6[28] = t2 * t20 * -2.0;
  out6[29] = 0.0;
  out6[30] = 0.0;
  out6[31] = 0.0;
  out6[32] = 0.0;
  out6[33] = 0.0;
  out6[34] = 0.0;
  out6[35] = t2 * t12 * 3.1415926535897931 * -1.366666666666667E+6;
  out7[0] = t6 * -100.0;
  out7[1] = 0.0;
  out7[2] = 0.0;
  out7[3] = 0.0;
  out7[4] = 0.0;
  out7[5] = 0.0;
  out7[6] = 0.0;
  out7[7] = t22 * -100.0;
  out7[8] = 0.0;
  out7[9] = 0.0;
  out7[10] = 0.0;
  out7[11] = 0.0;
  out7[12] = 0.0;
  out7[13] = 0.0;
  out7[14] = t23 * -100.0;
  out7[15] = 0.0;
  out7[16] = 0.0;
  out7[17] = 0.0;
  out7[18] = 0.0;
  out7[19] = 0.0;
  out7[20] = 0.0;
  out7[21] = t24 * -0.04;
  out7[22] = 0.0;
  out7[23] = 0.0;
  out7[24] = 0.0;
  out7[25] = 0.0;
  out7[26] = 0.0;
  out7[27] = 0.0;
  out7[28] = t25 * -0.04;
  out7[29] = 0.0;
  out7[30] = 0.0;
  out7[31] = 0.0;
  out7[32] = 0.0;
  out7[33] = 0.0;
  out7[34] = 0.0;
  out7[35] = t26 * -0.04;
  *out8 = 1.0;
}

/* End of code generation (sprdmpF7.c) */
