/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF1.c
 *
 * Code generation for function 'cnstF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF1.h"

/* Function Definitions */
void cnstF1(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  real_T t3;
  real_T t2;
  real_T t4;
  real_T t7;
  real_T t10;
  real_T t13;
  real_T t18;
  real_T t20;
  real_T t21_tmp;
  real_T b_t21_tmp;
  real_T t21;
  real_T t24;
  real_T t26;
  real_T t36;
  real_T t27_tmp;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t48;
  real_T t38_tmp;
  real_T b_t38_tmp;
  real_T t38;
  real_T t39;
  real_T t40;
  real_T t41_tmp;
  real_T t41;

  /* CNSTF1 */
  /*     [OUT1,OUT2,OUT3] = CNSTF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:01 */
  t3 = in2[90] / 2.0;
  t2 = muDoubleScalarCos(t3);
  t4 = muDoubleScalarSin(t3);
  t7 = t2 * 0.03 - t4 * 0.038;
  t10 = t2 * 0.038 + t4 * 0.03;
  t13 = t2 * 0.019 + t4 * 0.015;
  t3 = t2 * 0.015 - t4 * 0.019;
  t18 = t2 * t13;
  t20 = t4 * t3;
  t21_tmp = t2 * t10;
  b_t21_tmp = t4 * t7;
  t21 = ((t21_tmp / 2.0 + t18) + b_t21_tmp / 2.0) + t20;
  t24 = (in2[72] + t21_tmp) + b_t21_tmp;
  t26 = t2 * t3;
  t36 = t4 * t13;
  t27_tmp = t2 * t7;
  t7 = t4 * t10;
  t3 = ((t27_tmp / 2.0 + t26) - t7 / 2.0) - t36;
  t13 = (in2[74] + t27_tmp) - t7;
  t31 = t2 * t2;
  t32 = t4 * t4;
  t33 = t31 - t32;
  t34 = t2 * t21;
  t48 = t4 * t3;
  t38_tmp = t2 * t24;
  b_t38_tmp = t4 * t13;
  t38 = ((t34 + b_t38_tmp / 2.0) - t48) - t38_tmp / 2.0;
  t39 = t2 * t3;
  t40 = t4 * t21;
  t41_tmp = t2 * t13;
  t24 *= t4;
  t41 = ((t39 + t40) - t24 / 2.0) - t41_tmp / 2.0;
  t3 = t2 * 0.0075 - t4 * 0.0095;
  t13 = t2 * 0.0095 + t4 * 0.0075;
  t21 = ((((t26 - t36) + t27_tmp / 4.0) + t2 * t3) - t7 / 4.0) - t4 * t13;
  t3 = ((((t18 + t20) + t21_tmp / 4.0) + t2 * t13) + b_t21_tmp / 4.0) + t4 * t3;
  t13 = t38_tmp - b_t38_tmp;
  t7 = t41_tmp + t24;
  memset(&out1[0], 0, 72U * sizeof(real_T));
  out1[72] = t33;
  out1[73] = 0.0;
  t10 = t2 * t4;
  out1[74] = t10 * -2.0;
  memset(&out1[75], 0, 15U * sizeof(real_T));
  out1[90] = ((t4 * t38 + t2 * t41) - t4 * t13 / 2.0) - t2 * t7 / 2.0;
  memset(&out2[0], 0, 72U * sizeof(real_T));
  out2[72] = t10 * in2[193] * -2.0;
  out2[73] = 0.0;
  out2[74] = -t33 * in2[193];
  memset(&out2[75], 0, 15U * sizeof(real_T));
  out2[90] = ((-t31 * in2[177] + t32 * in2[177]) + in2[193] * (((((t2 * t38 - t4
    * t41) - t2 * t13 / 4.0) + t4 * t7 / 4.0) + t2 * (((((t34 - t48) - t38_tmp /
    4.0) + b_t38_tmp / 4.0) + t4 * t21) - t2 * t3)) + t4 * (((((-t39 - t40) +
    t24 / 4.0) + t41_tmp / 4.0) + t2 * t21) + t4 * t3))) - t10 * in2[175] * 2.0;
  *out3 = 0.0;
}

/* End of code generation (cnstF1.c) */
