/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF7.c
 *
 * Code generation for function 'cnstF7'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF7.h"

/* Function Definitions */
void cnstF7(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  real_T t3;
  real_T t2;
  real_T t4;
  real_T t7;
  real_T t10;
  real_T t13;
  real_T t18;
  real_T t35;
  real_T t19_tmp;
  real_T b_t19_tmp;
  real_T t19;
  real_T t21;
  real_T t23;
  real_T t25;
  real_T t26;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t36;
  real_T t38;
  real_T t39;
  real_T t40_tmp;
  real_T b_t40_tmp;
  real_T t40;
  real_T t46;
  real_T t51;
  real_T t55_tmp;

  /* CNSTF7 */
  /*     [OUT1,OUT2,OUT3] = CNSTF7(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:11 */
  t3 = in2[90] / 2.0;
  t2 = muDoubleScalarCos(t3);
  t4 = muDoubleScalarSin(t3);
  t7 = t2 * 0.03 + t4 * 0.038;
  t10 = t2 * 0.038 - t4 * 0.03;
  t13 = t2 * 0.019 - t4 * 0.015;
  t3 = t2 * 0.015 + t4 * 0.019;
  t18 = t4 * t3;
  t35 = t2 * t13;
  t19_tmp = t4 * t7;
  b_t19_tmp = t2 * t10;
  t19 = ((t19_tmp / 2.0 + t18) - b_t19_tmp / 2.0) - t35;
  t21 = (in2[84] + t19_tmp) - b_t19_tmp;
  t23 = t2 * t3;
  t25 = t4 * t13;
  t13 = t2 * t7;
  t3 = t4 * t10;
  t26 = ((t13 / 2.0 + t23) + t3 / 2.0) + t25;
  t7 = (in2[86] + t13) + t3;
  t31 = t2 * t2;
  t32 = t4 * t4;
  t33 = t31 - t32;
  t36 = t2 * t19;
  t38 = t2 * t26;
  t39 = t4 * t19;
  t40_tmp = t2 * t7;
  b_t40_tmp = t4 * t21;
  t40 = ((t38 + t39) - b_t40_tmp / 2.0) - t40_tmp / 2.0;
  t10 = t2 * 0.0075 + t4 * 0.0095;
  t46 = t2 * 0.0095 - t4 * 0.0075;
  t51 = ((((t23 + t25) + t13 / 4.0) + t2 * t10) + t3 / 4.0) + t4 * t46;
  t55_tmp = t4 * t7;
  t19 = t2 * t21;
  t25 = t19 - t55_tmp;
  t23 = t40_tmp + b_t40_tmp;
  t10 = ((((t18 - t35) + t19_tmp / 4.0) + t4 * t10) - b_t19_tmp / 4.0) - t2 *
    t46;
  t3 = t4 * t26;
  t13 = ((t36 + t55_tmp / 2.0) - t3) - t19 / 2.0;
  memset(&out1[0], 0, 84U * sizeof(real_T));
  out1[84] = t33;
  out1[85] = 0.0;
  t7 = t2 * t4;
  out1[86] = t7 * -2.0;
  out1[87] = 0.0;
  out1[88] = 0.0;
  out1[89] = 0.0;
  out1[90] = ((t2 * t40 - t4 * t25 / 2.0) - t2 * t23 / 2.0) + t4 * t13;
  memset(&out2[0], 0, 84U * sizeof(real_T));
  out2[84] = t7 * in2[193] * -2.0;
  out2[85] = 0.0;
  out2[86] = -t33 * in2[193];
  out2[87] = 0.0;
  out2[88] = 0.0;
  out2[89] = 0.0;
  out2[90] = ((-t31 * in2[189] + t32 * in2[189]) + in2[193] * (((((-t4 * t40 -
    t2 * t25 / 4.0) + t2 * t13) + t4 * t23 / 4.0) + t2 * (((((t36 - t3) - t19 /
    4.0) + t55_tmp / 4.0) + t4 * t51) - t2 * t10)) + t4 * (((((-t38 - t39) +
    b_t40_tmp / 4.0) + t40_tmp / 4.0) + t2 * t51) + t4 * t10))) - t7 * in2[187] *
    2.0;
  *out3 = 0.0;
}

/* End of code generation (cnstF7.c) */
