/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF4.c
 *
 * Code generation for function 'cnstF4'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF4.h"

/* Function Definitions */
void cnstF4(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  real_T t2;
  real_T t3;

  /* CNSTF4 */
  /*     [OUT1,OUT2,OUT3] = CNSTF4(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:05 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t2 = muDoubleScalarSin(t2);
  memset(&out1[0], 0, 75U * sizeof(real_T));
  out1[75] = t3 * 2.0;
  out1[76] = 0.0;
  out1[77] = t2 * -2.0;
  memset(&out1[78], 0, 12U * sizeof(real_T));
  out1[90] = -in2[75] * t2 - in2[77] * t3;
  memset(&out2[0], 0, 75U * sizeof(real_T));
  out2[75] = -t2 * in2[193];
  out2[76] = 0.0;
  out2[77] = -t3 * in2[193];
  memset(&out2[78], 0, 12U * sizeof(real_T));
  out2[90] = (-t2 * in2[178] - t3 * in2[180]) - in2[193] * (in2[75] * t3 / 2.0 -
    in2[77] * t2 / 2.0);
  *out3 = 0.0;
}

/* End of code generation (cnstF4.c) */
