/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vdF.c
 *
 * Code generation for function 'fj_vdF'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "EOM.h"
#include "fj_vdF.h"

/* Function Definitions */
void fj_vdF(const real_T in1[6], const real_T in2[206], real_T fj_vd[91])
{
  /* FJ_VDF */
  /*     FJ_VD = FJ_VDF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:15 */
  memset(&fj_vd[0], 0, 90U * sizeof(real_T));
  fj_vd[90] = -in1[5] * in2[193];
}

/* End of code generation (fj_vdF.c) */
