/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF13.c
 *
 * Code generation for function 'massF13'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF13.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo rj_emlrtRSI = { 16, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

static emlrtRSInfo sj_emlrtRSI = { 17, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

static emlrtRSInfo tj_emlrtRSI = { 18, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

static emlrtRSInfo uj_emlrtRSI = { 20, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

static emlrtRSInfo vj_emlrtRSI = { 23, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

static emlrtRSInfo wj_emlrtRSI = { 31, /* lineNo */
  "massF13",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF13.m"/* pathName */
};

/* Function Definitions */
void massF13(const emlrtStack *sp, const real_T in2[206], real_T out2[546],
             real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF13 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF13(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:09:40 */
  st.site = &rj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[69] * in2[69];
  st.site = &sj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[70] * in2[70];
  st.site = &tj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[71] * in2[71];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &uj_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[71] * 2.0;
  t28 = in2[69] * in2[70];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &vj_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[69] * in2[71] * t6 * 2.0;
  t12 = in2[69] * 2.0;
  t13 = in2[70] * in2[71] * t6 * 2.0;
  memset(&out2[0], 0, 396U * sizeof(real_T));
  out2[396] = 1.0;
  out2[397] = 0.0;
  out2[398] = 0.0;
  out2[399] = 0.0;
  out2[400] = 0.0;
  out2[401] = 0.0;
  out2[402] = 0.0;
  out2[403] = 1.0;
  out2[404] = 0.0;
  out2[405] = 0.0;
  out2[406] = 0.0;
  out2[407] = 0.0;
  out2[408] = 0.0;
  out2[409] = 0.0;
  out2[410] = 1.0;
  out2[411] = 0.0;
  out2[412] = 0.0;
  out2[413] = 0.0;
  out2[414] = 0.0;
  out2[415] = 0.0;
  out2[416] = 0.0;
  out2[417] = t9 + t2 * t6 * 2.0;
  out2[418] = -t7 + t8;
  out2[419] = in2[70] * 2.0 + t11;
  out2[420] = 0.0;
  out2[421] = 0.0;
  out2[422] = 0.0;
  out2[423] = t7 + t8;
  out2[424] = t9 + t3 * t6 * 2.0;
  out2[425] = -t12 + t13;
  out2[426] = 0.0;
  out2[427] = 0.0;
  out2[428] = 0.0;
  out2[429] = in2[70] * -2.0 + t11;
  out2[430] = t12 + t13;
  out2[431] = t9 + t4 * t6 * 2.0;
  memset(&out2[432], 0, 114U * sizeof(real_T));
  st.site = &wj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[70] * t6 * 2.0;
  t16 = in2[70] * t2 * t14 * 2.0;
  t17 = in2[69] * t6 * 2.0;
  t18 = t28 * in2[71] * t14 * 2.0;
  t9 = in2[71] * t6 * 2.0;
  t11 = in2[71] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[69] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[71] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[69] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[70] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 417U * sizeof(real_T));
  out3[417] = (t12 * in2[173] + t5 * in2[174]) + in2[172] * (t17 + in2[69] * t2 *
    t14 * 2.0);
  out3[418] = (t12 * in2[172] + (t18 + 2.0) * in2[174]) - in2[173] * (t17 - t13);
  out3[419] = ((t18 - 2.0) * in2[173] + t5 * in2[172]) - in2[174] * (t17 - t28);
  out3[420] = 0.0;
  out3[421] = 0.0;
  out3[422] = 0.0;
  out3[423] = (t7 * in2[173] + (t18 - 2.0) * in2[174]) - in2[172] * (t15 - t16);
  out3[424] = (t7 * in2[172] + t6 * in2[174]) + in2[173] * (t15 + in2[70] * t3 *
    t14 * 2.0);
  out3[425] = ((t18 + 2.0) * in2[172] + t6 * in2[173]) - in2[174] * (t15 - t30);
  out3[426] = 0.0;
  out3[427] = 0.0;
  out3[428] = 0.0;
  out3[429] = ((t18 + 2.0) * in2[173] + t31 * in2[174]) - in2[172] * (t9 - t11);
  out3[430] = ((t18 - 2.0) * in2[172] + t32 * in2[174]) - in2[173] * (t9 - t8);
  out3[431] = (t31 * in2[172] + t32 * in2[173]) + in2[174] * (t9 + in2[71] * t4 *
    t14 * 2.0);
  memset(&out3[432], 0, 114U * sizeof(real_T));
}

/* End of code generation (massF13.c) */
