/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF92.c
 *
 * Code generation for function 'sprdmpF92'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF92.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo tk_emlrtRSI = { 41, /* lineNo */
  "sprdmpF92",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF92.m"/* pathName */
};

static emlrtRSInfo xk_emlrtRSI = { 50, /* lineNo */
  "sprdmpF92",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF92.m"/* pathName */
};

static emlrtRSInfo yk_emlrtRSI = { 58, /* lineNo */
  "sprdmpF92",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF92.m"/* pathName */
};

static emlrtRSInfo al_emlrtRSI = { 87, /* lineNo */
  "sprdmpF92",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF92.m"/* pathName */
};

static emlrtRSInfo ml_emlrtRSI = { 293,/* lineNo */
  "sprdmpF92",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF92.m"/* pathName */
};

/* Function Definitions */
void sprdmpF92(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
               real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t180;
  real_T t7;
  real_T t8;
  real_T t231;
  real_T t9;
  real_T t238;
  real_T t10;
  real_T t14;
  real_T t62;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18_tmp;
  real_T t19;
  real_T t20_tmp;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24_tmp;
  real_T t25_tmp;
  real_T t174;
  real_T t28_tmp;
  real_T t28;
  real_T t30;
  real_T t31;
  real_T t32_tmp;
  real_T t33;
  real_T t34_tmp;
  real_T t35;
  real_T t36_tmp;
  real_T t46_tmp;
  real_T t37_tmp;
  real_T t37;
  real_T t39_tmp;
  real_T t39;
  real_T t41;
  real_T t53_tmp;
  real_T t184;
  real_T t45;
  real_T t58_tmp;
  real_T t234;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t51;
  real_T t52;
  real_T t55_tmp;
  real_T t55;
  real_T t57;
  real_T t59;
  real_T t61;
  real_T t63_tmp;
  real_T t65;
  real_T t68;
  real_T t71;
  real_T t72;
  real_T t73;
  real_T a_tmp;
  real_T a;
  real_T b_a_tmp;
  real_T b_a;
  real_T t79;
  real_T t80;
  real_T t81;
  real_T t82;
  real_T t228;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t86;
  real_T t88;
  real_T t92_tmp;
  real_T b_t92_tmp;
  real_T c_t92_tmp;
  real_T t92;
  real_T t97_tmp;
  real_T b_t97_tmp;
  real_T c_t97_tmp;
  real_T t97;
  real_T t107;
  real_T t112;
  real_T t113;
  real_T t114;
  real_T t115;
  real_T t116;
  real_T t117;
  real_T t118;
  real_T t120;
  real_T t124_tmp;
  real_T b_t124_tmp;
  real_T c_t124_tmp;
  real_T t124;
  real_T t129_tmp;
  real_T b_t129_tmp;
  real_T c_t129_tmp;
  real_T t129;
  real_T t138;
  real_T t143;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t147;
  real_T t148;
  real_T t149;
  real_T t151;
  real_T t155_tmp;
  real_T b_t155_tmp;
  real_T t155;
  real_T t160;
  real_T t169;
  real_T t176;
  real_T t179;
  real_T t183;
  real_T t187;
  real_T t192;
  real_T t194;
  real_T t198;
  real_T t202;
  real_T t206;
  real_T t208;
  real_T t211;
  real_T t216;
  real_T t218;
  real_T t222;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF92 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF92(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:30:15 */
  t2 = in2[88] * in2[88];
  t3 = in2[89] * in2[89];
  t4 = in2[87] * in2[87];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &tk_emlrtRSI;
  b_sqrt(&st, &t6);
  t180 = in2[87] * in2[88];
  t7 = t180 * 2.0;
  t8 = in2[88] * t6 * 2.0;
  t231 = in2[87] * in2[89];
  t9 = t231 * 2.0;
  t238 = in2[88] * in2[89];
  t10 = t238 * 2.0;
  t14 = ((-(in2[3] * in2[3]) - in2[4] * in2[4]) - in2[5] * in2[5]) + 1.0;
  t62 = t14;
  st.site = &xk_emlrtRSI;
  b_sqrt(&st, &t62);
  t15 = 1.0 / t62;
  t16 = t6 * 2.0;
  t17 = in2[88] * 2.0;
  t18_tmp = in2[89] * t6 * 2.0;
  t19 = t3 * 2.0;
  t20_tmp = in2[87] * t6 * 2.0;
  t21 = t4 * 2.0;
  t22 = t2 * 2.0;
  st.site = &yk_emlrtRSI;
  b_sqrt(&st, &t5);
  t23 = 1.0 / t5;
  t24_tmp = in2[1] - in2[85];
  t25_tmp = in2[2] - in2[86];
  t174 = in2[0] - in2[84];
  t28_tmp = in2[87] * t23;
  t28 = (-in2[2] + in2[86]) + t28_tmp * t24_tmp;
  t30 = t24_tmp + t28_tmp * t25_tmp;
  t31 = t6 * t24_tmp;
  t32_tmp = in2[87] * t25_tmp;
  t33 = t6 * t25_tmp;
  t34_tmp = in2[88] * t174;
  t35 = t6 * t174;
  t36_tmp = in2[89] * t24_tmp;
  t46_tmp = in2[88] * t25_tmp;
  t37_tmp = t35 + t36_tmp;
  t37 = t37_tmp - t46_tmp;
  t39_tmp = in2[88] * t23;
  t39 = (-in2[0] + in2[84]) + t39_tmp * t25_tmp;
  t41 = t25_tmp + t39_tmp * t174;
  t53_tmp = in2[89] * t174;
  t184 = t31 + t32_tmp;
  t45 = t184 - t53_tmp;
  t58_tmp = in2[87] * t24_tmp;
  t234 = t33 + t34_tmp;
  t47 = t234 - t58_tmp;
  t48 = in2[5] * 2.0;
  t49 = in2[3] - in2[87];
  st.site = &al_emlrtRSI;
  b_sqrt(&st, &t14);
  t51 = in2[4] - in2[88];
  t52 = in2[5] - in2[89];
  t55_tmp = in2[89] * t23;
  t55 = t174 + t55_tmp * t24_tmp;
  t57 = (-in2[1] + in2[85]) + t55_tmp * t174;
  t59 = in2[3] * 2.0;
  t5 = in1[4] / 2.0;
  t61 = muDoubleScalarCos(t5);
  t62 = muDoubleScalarSin(t5);
  t63_tmp = (in2[87] * t174 + in2[88] * t24_tmp) + in2[89] * t25_tmp;
  t5 = t61 * t61;
  t65 = t62 * t62;
  t68 = t61 * 0.036 - t62 * 0.077;
  t71 = t61 * 0.077 + t62 * 0.036;
  t72 = t62 * t71;
  t73 = t5 * 0.036;
  a_tmp = t61 * t68;
  a = ((-t72 - t73) + a_tmp) + t65 * 0.036;
  b_a_tmp = t5 * 1.193944943E-14 + t65 * 1.193944943E-14;
  b_a = (t61 * t71 + t62 * t68) - t61 * t62 * 0.072;
  t79 = t6 - t14;
  t80 = in2[88] * t39;
  t81 = t58_tmp * 2.0;
  t82 = t32_tmp * 2.0;
  t228 = t238 * t23;
  t83 = t228 * t25_tmp;
  t84 = (t19 + t22) - 1.0;
  t85 = t7 + t18_tmp;
  t86 = t8 - t9;
  t88 = ((t63_tmp + in2[88] * t30) - in2[89] * t28) - t28_tmp * t37;
  t92_tmp = t6 * t41;
  b_t92_tmp = t39_tmp * t37;
  c_t92_tmp = t228 * t24_tmp;
  t92 = ((((t234 - t80) - t81) + t92_tmp) + b_t92_tmp) + c_t92_tmp;
  t97_tmp = in2[89] * t55;
  b_t97_tmp = t6 * t57;
  c_t97_tmp = t55_tmp * t37;
  t97 = (((((-t31 + t53_tmp) - t82) - t83) + b_t97_tmp) + t97_tmp) + c_t97_tmp;
  t107 = muDoubleScalarPower(muDoubleScalarAbs((((((((t92 * in2[191] + t97 *
    in2[192]) + t84 * in2[103]) + t86 * in2[105]) + t85 * in2[188]) - t84 * in2
    [187]) - t85 * in2[104]) - t86 * in2[189]) - t88 * in2[190]), in1[1] - 1.0);
  t112 = t34_tmp * 2.0;
  t238 = t231 * t23;
  t113 = t238 * t174;
  t114 = in2[89] * t57;
  t115 = t46_tmp * 2.0;
  t116 = (t19 + t21) - 1.0;
  t117 = -t7 + t18_tmp;
  t118 = t10 + t20_tmp;
  t120 = ((t63_tmp + in2[89] * t41) - in2[87] * t39) - t39_tmp * t45;
  t124_tmp = in2[87] * t30;
  b_t124_tmp = t6 * t28;
  c_t124_tmp = t28_tmp * t45;
  t124 = (((((-t33 + t58_tmp) - t112) - t113) + b_t124_tmp) + t124_tmp) +
    c_t124_tmp;
  t129_tmp = t6 * t55;
  b_t129_tmp = t55_tmp * t45;
  c_t129_tmp = t238 * t25_tmp;
  t129 = ((((t37_tmp - t114) - t115) + t129_tmp) + b_t129_tmp) + c_t129_tmp;
  t138 = muDoubleScalarPower(muDoubleScalarAbs((((((((t124 * in2[190] + t129 *
    in2[192]) + t116 * in2[104]) + t117 * in2[103]) + t118 * in2[189]) - t116 *
    in2[188]) - t118 * in2[105]) - t117 * in2[187]) - t120 * in2[191]), in1[1] -
    1.0);
  t143 = in2[87] * t28;
  t144 = t53_tmp * 2.0;
  t145 = t36_tmp * 2.0;
  t5 = t180 * t23;
  t146 = t5 * t24_tmp;
  t147 = (t21 + t22) - 1.0;
  t148 = t8 + t9;
  t149 = -t10 + t20_tmp;
  t151 = ((t63_tmp + in2[87] * t55) - in2[88] * t57) - t55_tmp * t47;
  t155_tmp = t6 * t30;
  b_t155_tmp = t28_tmp * t47;
  t57 = t5 * t174;
  t155 = ((((t184 - t143) - t144) + t155_tmp) + b_t155_tmp) + t57;
  t21 = in2[88] * t41;
  t28 = t6 * t39;
  t24_tmp = t39_tmp * t47;
  t160 = (((((-t35 + t46_tmp) - t145) - t146) + t28) + t21) + t24_tmp;
  t169 = muDoubleScalarPower(muDoubleScalarAbs((((((((t155 * in2[190] + t160 *
    in2[191]) + t147 * in2[105]) + t149 * in2[104]) + t148 * in2[187]) - t147 *
    in2[189]) - t148 * in2[103]) - t149 * in2[188]) - t151 * in2[192]), in1[1] -
    1.0);
  t174 = in2[4] * 2.0;
  t176 = t16 + in2[3] * in2[87] * t15 * 2.0;
  t62 = in2[89] * 2.0;
  t179 = t62 + in2[4] * in2[87] * t15 * 2.0;
  t180 = in2[5] * in2[87] * t15 * 2.0;
  t231 = t5 * 2.0;
  t19 = t39_tmp * t49 * 2.0;
  t183 = (t48 + t231) + t19;
  t184 = t14 * 2.0;
  t25_tmp = t4 * t23 * 2.0;
  t37_tmp = t28_tmp * t49 * 2.0;
  t187 = (t184 + t25_tmp) + t37_tmp;
  t55 = t238 * 2.0;
  t238 = t55_tmp * t49 * 2.0;
  t192 = (-t174 + t55) + t238;
  t194 = t17 - t180;
  t198 = muDoubleScalarPower(muDoubleScalarAbs(((((t187 * in2[190] + t183 * in2
    [191]) + t192 * in2[192]) + t194 * in2[108]) - t176 * in2[106]) - t179 *
    in2[107]), in1[1] - 1.0);
  t202 = t16 + in2[4] * in2[88] * t15 * 2.0;
  t68 = in2[3] * in2[88] * t15 * 2.0;
  t41 = in2[87] * 2.0;
  t206 = t41 + in2[5] * in2[88] * t15 * 2.0;
  t71 = t28_tmp * t51 * 2.0;
  t208 = (-t48 + t231) + t71;
  t61 = t2 * t23 * 2.0;
  t234 = t39_tmp * t51 * 2.0;
  t211 = (t184 + t61) + t234;
  t30 = t228 * 2.0;
  t5 = t55_tmp * t51 * 2.0;
  t216 = (t59 + t30) + t5;
  t218 = t62 - t68;
  t222 = muDoubleScalarPower(muDoubleScalarAbs(((((t211 * in2[191] + t208 * in2
    [190]) + t216 * in2[192]) + t218 * in2[106]) - t202 * in2[107]) - t206 *
    in2[108]), in1[1] - 1.0);
  t39 = t16 + in2[5] * in2[89] * t15 * 2.0;
  t228 = t17 + in2[3] * in2[89] * t15 * 2.0;
  t22 = in2[4] * in2[89] * t15 * 2.0;
  out1[0] = (t2 * -2.0 - t3 * 2.0) + 1.0;
  out1[1] = t85;
  out1[2] = -t8 + t9;
  memset(&out1[3], 0, 81U * sizeof(real_T));
  out1[84] = t84;
  out1[85] = -t7 - t18_tmp;
  out1[86] = t86;
  out1[87] = t88;
  out1[88] = (((((-t33 - t34_tmp) + t80) + t81) - t92_tmp) - b_t92_tmp) -
    c_t92_tmp;
  out1[89] = (((((t31 - t53_tmp) + t82) + t83) - t97_tmp) - b_t97_tmp) -
    c_t97_tmp;
  out1[90] = 0.0;
  out1[91] = t7 - t18_tmp;
  out1[92] = (t3 * -2.0 - t4 * 2.0) + 1.0;
  out1[93] = t118;
  memset(&out1[94], 0, 81U * sizeof(real_T));
  out1[175] = t117;
  out1[176] = t116;
  out1[177] = -t10 - t20_tmp;
  out1[178] = (((((t33 + t112) + t113) - t58_tmp) - t124_tmp) - b_t124_tmp) -
    c_t124_tmp;
  out1[179] = t120;
  out1[180] = (((((-t35 - t36_tmp) + t114) + t115) - t129_tmp) - b_t129_tmp) -
    c_t129_tmp;
  out1[181] = 0.0;
  out1[182] = t148;
  out1[183] = t10 - t20_tmp;
  out1[184] = (t2 * -2.0 - t4 * 2.0) + 1.0;
  memset(&out1[185], 0, 81U * sizeof(real_T));
  out1[266] = -t8 - t9;
  out1[267] = t149;
  out1[268] = t147;
  out1[269] = (((((-t31 - t32_tmp) + t143) + t144) - t155_tmp) - b_t155_tmp) -
    t57;
  out1[270] = (((((t35 - t46_tmp) + t145) + t146) - t21) - t28) - t24_tmp;
  out1[271] = t151;
  out1[272] = 0.0;
  out1[273] = 0.0;
  out1[274] = 0.0;
  out1[275] = 0.0;
  out1[276] = t176;
  out1[277] = t179;
  out1[278] = -t17 + t180;
  memset(&out1[279], 0, 81U * sizeof(real_T));
  out1[360] = (t14 * -2.0 - t25_tmp) - t37_tmp;
  out1[361] = (-t48 - t231) - t19;
  out1[362] = (t174 - t55) - t238;
  out1[363] = 0.0;
  out1[364] = 0.0;
  out1[365] = 0.0;
  out1[366] = 0.0;
  out1[367] = in2[89] * -2.0 + t68;
  out1[368] = t202;
  out1[369] = t206;
  memset(&out1[370], 0, 81U * sizeof(real_T));
  out1[451] = (t48 - t231) - t71;
  out1[452] = (t14 * -2.0 - t61) - t234;
  out1[453] = (-t59 - t30) - t5;
  out1[454] = 0.0;
  out1[455] = 0.0;
  out1[456] = 0.0;
  out1[457] = 0.0;
  out1[458] = t228;
  out1[459] = in2[87] * -2.0 + t22;
  out1[460] = t39;
  memset(&out1[461], 0, 81U * sizeof(real_T));
  t62 = t28_tmp * t52 * 2.0;
  out1[542] = (in2[4] * -2.0 - t55) - t62;
  t68 = t39_tmp * t52 * 2.0;
  out1[543] = (t59 - t30) - t68;
  t238 = t3 * t23 * 2.0;
  t5 = t55_tmp * t52 * 2.0;
  out1[544] = (t14 * -2.0 - t238) - t5;
  out1[545] = 0.0;
  t231 = (t174 + t55) + t62;
  t234 = (t184 + t238) + t5;
  t238 = (-t59 + t30) + t68;
  t71 = t41 - t22;
  t61 = muDoubleScalarPower(muDoubleScalarAbs(((((t234 * in2[192] + t231 * in2
    [190]) + t238 * in2[191]) + t71 * in2[107]) - t39 * in2[108]) - t228 * in2
    [106]), in1[1] - 1.0);
  t5 = (a * a + b_a_tmp * b_a_tmp) + b_a * b_a;
  st.site = &ml_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * (((((((t65 * -0.036 + t72) + t73) + in2[89] * t45) - in2[88]
    * t47) + in2[87] * t63_tmp) + t6 * t37) - a_tmp) * -0.00026666666666666668;
  out2[1] = in1[0] * ((((b_a_tmp - in2[89] * t37) + in2[87] * t47) + in2[88] *
                       t63_tmp) + t6 * t45) * -0.00026666666666666668;
  out2[2] = in1[0] * ((((-t5 + in2[88] * t37) - in2[87] * t45) + in2[89] *
                       t63_tmp) + t6 * t47) * -0.0008;
  out2[3] = in1[0] * (((in2[88] * t52 * -2.0 + in2[89] * t51 * 2.0) + in2[87] *
                       t79 * 2.0) + t6 * t49 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[89] * t49 * -2.0 + in2[87] * t52 * 2.0) + in2[88] *
                       t79 * 2.0) + t6 * t51 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[88] * t49 * 2.0 - in2[87] * t51 * 2.0) + in2[89] *
                       t79 * 2.0) + t6 * t52 * 2.0) * -4.75111111111111E-9;
  t68 = in1[2] * t84 * t107;
  t5 = in1[2] * t85 * t107;
  t62 = in1[2] * t86 * t107;
  out3[0] = (((((((t68 * in2[103] - t5 * in2[104]) + t62 * in2[105]) - t68 *
                 in2[187]) + t5 * in2[188]) - t62 * in2[189]) - in1[2] * t88 *
              t107 * in2[190]) + in1[2] * t92 * t107 * in2[191]) + in1[2] * t97 *
    t107 * in2[192];
  t68 = in1[2] * t116 * t138;
  t5 = in1[2] * t117 * t138;
  t62 = in1[2] * t118 * t138;
  out3[1] = (((((((t68 * in2[104] + t5 * in2[103]) - t62 * in2[105]) - t68 *
                 in2[188]) - t5 * in2[187]) + t62 * in2[189]) - in1[2] * t120 *
              t138 * in2[191]) + in1[2] * t124 * t138 * in2[190]) + in1[2] *
    t129 * t138 * in2[192];
  t68 = in1[2] * t147 * t169;
  t5 = in1[2] * t149 * t169;
  out3[2] = (((((((-in1[2] * t148 * t169 * in2[103] + t68 * in2[105]) + t5 *
                  in2[104]) + in1[2] * t148 * t169 * in2[187]) - t68 * in2[189])
               - t5 * in2[188]) - in1[2] * t151 * t169 * in2[192]) + in1[2] *
             t155 * t169 * in2[190]) + in1[2] * t160 * t169 * in2[191];
  out3[3] = ((((-in1[3] * t176 * t198 * in2[106] - in1[3] * t179 * t198 * in2
                [107]) + in1[3] * t194 * t198 * in2[108]) + in1[3] * t183 * t198
              * in2[191]) + in1[3] * t187 * t198 * in2[190]) + in1[3] * t192 *
    t198 * in2[192];
  out3[4] = ((((-in1[3] * t202 * t222 * in2[107] - in1[3] * t206 * t222 * in2
                [108]) + in1[3] * t218 * t222 * in2[106]) + in1[3] * t208 * t222
              * in2[190]) + in1[3] * t211 * t222 * in2[191]) + in1[3] * t216 *
    t222 * in2[192];
  out3[5] = ((((-in1[3] * t39 * t61 * in2[108] - in1[3] * t228 * t61 * in2[106])
               + in1[3] * t71 * t61 * in2[107]) + in1[3] * t231 * t61 * in2[190])
             + in1[3] * t234 * t61 * in2[192]) + in1[3] * t238 * t61 * in2[191];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF92.c) */
