/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF103.c
 *
 * Code generation for function 'sprdmpF103'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF103.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo hu_emlrtRSI = { 41, /* lineNo */
  "sprdmpF103",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF103.m"/* pathName */
};

static emlrtRSInfo iu_emlrtRSI = { 47, /* lineNo */
  "sprdmpF103",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF103.m"/* pathName */
};

static emlrtRSInfo mu_emlrtRSI = { 77, /* lineNo */
  "sprdmpF103",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF103.m"/* pathName */
};

static emlrtRSInfo nu_emlrtRSI = { 89, /* lineNo */
  "sprdmpF103",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF103.m"/* pathName */
};

static emlrtRSInfo av_emlrtRSI = { 297,/* lineNo */
  "sprdmpF103",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF103.m"/* pathName */
};

/* Function Definitions */
void sprdmpF103(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t190;
  real_T t206;
  real_T t187;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t205;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t24_tmp;
  real_T t25;
  real_T t234;
  real_T t157;
  real_T t209;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t178;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t51_tmp;
  real_T b_t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t238;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t60;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63_tmp;
  real_T t64_tmp;
  real_T a_tmp;
  real_T t72;
  real_T t73;
  real_T t75;
  real_T t77;
  real_T a;
  real_T b_a_tmp;
  real_T c_a_tmp;
  real_T b_a;
  real_T t82;
  real_T t86;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t94;
  real_T t95;
  real_T t106_tmp;
  real_T t106;
  real_T t110;
  real_T t115;
  real_T t116;
  real_T t117;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t125;
  real_T t126;
  real_T t127_tmp;
  real_T b_t127_tmp;
  real_T t127;
  real_T t136_tmp;
  real_T t136;
  real_T t139;
  real_T t149;
  real_T t153;
  real_T t154;
  real_T t155;
  real_T t156;
  real_T t169;
  real_T t172;
  real_T t181;
  real_T t183;
  real_T t186;
  real_T t189;
  real_T t192;
  real_T t196;
  real_T t200;
  real_T t208;
  real_T t212;
  real_T t213;
  real_T t215;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF103 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF103(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:24:06 */
  t2 = in2[40] * in2[40];
  t3 = in2[41] * in2[41];
  t4 = in2[39] * in2[39];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &hu_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[41] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[39] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &iu_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t190 = in2[37] - in2[43];
  t206 = in2[38] - in2[44];
  t187 = in2[36] - in2[42];
  t17_tmp = in2[39] * t12;
  t17 = (-in2[38] + in2[44]) + t17_tmp * t190;
  t19 = t190 + t17_tmp * t206;
  t20 = t6 * t190;
  t205 = in2[39] * t206;
  t22_tmp = in2[39] * t190;
  t23_tmp = t6 * t206;
  t24_tmp = in2[40] * t187;
  t25 = t6 * t187;
  t234 = in2[41] * t190;
  t157 = in2[40] * t206;
  t209 = t25 + t234;
  t27 = t209 - t157;
  t29_tmp = in2[40] * t12;
  t29 = (-in2[36] + in2[42]) + t29_tmp * t206;
  t31 = t206 + t29_tmp * t187;
  t178 = in2[41] * t187;
  t32_tmp = t20 + t205;
  t32 = t32_tmp - t178;
  t34 = (-t22_tmp + t23_tmp) + t24_tmp;
  t35 = in2[47] * 2.0;
  t36 = in2[39] - in2[45];
  t5 = ((-(in2[45] * in2[45]) - in2[46] * in2[46]) - in2[47] * in2[47]) + 1.0;
  t41 = t5;
  st.site = &mu_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[40] - in2[46];
  t43 = in2[41] - in2[47];
  t46_tmp = in2[41] * t12;
  t46 = t187 + t46_tmp * t190;
  t48 = (-in2[37] + in2[43]) + t46_tmp * t187;
  t49 = in2[45] * 2.0;
  t50_tmp = in2[40] * t6 * 2.0;
  t51_tmp = in2[39] * in2[40];
  b_t51_tmp = t51_tmp * 2.0;
  t52_tmp = in2[39] * in2[41];
  t52 = t52_tmp * 2.0;
  t238 = in2[40] * in2[41];
  t53_tmp = t238 * 2.0;
  st.site = &nu_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[40] * 2.0;
  t5 = in1[4] / 2.0;
  t58 = muDoubleScalarCos(t5);
  t59 = t58 / 25.0;
  t60 = muDoubleScalarSin(t5);
  t61_tmp = in2[39] * t187;
  t62_tmp = in2[40] * t190;
  t63_tmp = in2[41] * t206;
  t64_tmp = (t61_tmp + t62_tmp) + t63_tmp;
  a_tmp = t58 * t58 * 2.728750558000001E-14 + t60 * t60 * 2.728750558000001E-14;
  t5 = t60 / 25.0;
  t72 = t58 / 4.0 - t5;
  t73 = t58 * 0.162;
  t75 = t59 + t60 / 4.0;
  t77 = t59 + t60 * 0.162;
  t5 -= t73;
  a = ((t58 * t72 + t58 * t5) - t60 * t75) + t60 * t77;
  b_a_tmp = t58 * t75 + t60 * t72;
  c_a_tmp = t58 * t77;
  b_a = (b_a_tmp - c_a_tmp) + t60 * t5;
  t82 = t6 - t41;
  t72 = t238 * t12;
  t86 = (((((t23_tmp + t24_tmp) + t6 * t31) + t29_tmp * t27) + t72 * t190) -
         in2[40] * t29) - t22_tmp * 2.0;
  t90 = (((((-t20 + t178) + t6 * t48) + in2[41] * t46) + t46_tmp * t27) - t205 *
         2.0) - t72 * t206;
  t91 = (t8 + t11) - 1.0;
  t92 = t7 + b_t51_tmp;
  t93 = t50_tmp - t52;
  t94 = in2[41] * t17;
  t95 = t17_tmp * t27;
  t106_tmp = in2[40] * t19;
  t106 = ((t64_tmp - t94) - t95) + t106_tmp;
  t110 = muDoubleScalarPower(muDoubleScalarAbs((((((((t86 * in2[143] + t90 *
    in2[144]) + t91 * in2[139]) + t93 * in2[141]) + t92 * in2[146]) - t91 * in2
    [145]) - t92 * in2[140]) - t93 * in2[147]) - t106 * in2[142]), in1[1] - 1.0);
  t115 = t6 * t17;
  t116 = in2[39] * t19;
  t117 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t121 = ((((t209 + t6 * t46) + t46_tmp * t32) + t5 * t206) - in2[41] * t48) -
    t157 * 2.0;
  t122 = (t8 + t10) - 1.0;
  t123 = t9 + t53_tmp;
  t124 = t7 - b_t51_tmp;
  t125 = in2[39] * t29;
  t126 = t29_tmp * t32;
  t127_tmp = t24_tmp * 2.0;
  b_t127_tmp = t5 * t187;
  t127 = (((((t22_tmp - t23_tmp) + t115) + t116) + t117) - t127_tmp) -
    b_t127_tmp;
  t136_tmp = in2[41] * t31;
  t136 = ((t64_tmp - t125) - t126) + t136_tmp;
  t139 = muDoubleScalarPower(muDoubleScalarAbs((((((((t127 * in2[142] + t121 *
    in2[144]) + t122 * in2[140]) + t124 * in2[139]) + t123 * in2[147]) - t122 *
    in2[146]) - t123 * in2[141]) - t124 * in2[145]) - t136 * in2[143]), in1[1] -
    1.0);
  t59 = t51_tmp * t12;
  t149 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t59 * t187) - in2[39] * t17)
    - t178 * 2.0;
  t153 = (((((-t25 + t157) + t6 * t29) + in2[40] * t31) + t29_tmp * t34) - t234 *
          2.0) - t59 * t190;
  t154 = (t10 + t11) - 1.0;
  t155 = t50_tmp + t52;
  t156 = t9 - t53_tmp;
  t157 = in2[40] * t48;
  t29 = t46_tmp * t34;
  t17 = in2[39] * t46;
  t169 = ((t64_tmp - t157) - t29) + t17;
  t172 = muDoubleScalarPower(muDoubleScalarAbs((((((((t149 * in2[142] + t153 *
    in2[143]) + t154 * in2[141]) + t156 * in2[140]) + t155 * in2[145]) - t154 *
    in2[147]) - t155 * in2[139]) - t156 * in2[146]) - t169 * in2[144]), in1[1] -
    1.0);
  t19 = t17_tmp * t36 * 2.0;
  t178 = t29_tmp * t36 * 2.0;
  t31 = in2[46] * 2.0;
  t32_tmp = t5 * 2.0;
  t181 = (t31 + t46_tmp * t36 * 2.0) - t32_tmp;
  t183 = t55 + in2[39] * in2[45] * t54 * 2.0;
  t5 = in2[41] * 2.0;
  t186 = t5 + in2[39] * in2[46] * t54 * 2.0;
  t187 = in2[39] * in2[47] * t54 * 2.0;
  t24_tmp = t59 * 2.0;
  t189 = (t35 - t178) + t24_tmp;
  t190 = t41 * 2.0;
  t58 = t4 * t12 * 2.0;
  t192 = (-t19 + t190) + t58;
  t196 = t56 - t187;
  t200 = muDoubleScalarPower(muDoubleScalarAbs(((((t192 * in2[142] + t189 * in2
    [143]) + t196 * in2[150]) - t181 * in2[144]) - t183 * in2[148]) - t186 *
    in2[149]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t205 = t17_tmp * t42 * 2.0;
  t206 = t46_tmp * t42 * 2.0;
  t208 = t55 + in2[40] * in2[46] * t54 * 2.0;
  t209 = in2[40] * in2[45] * t54 * 2.0;
  t48 = in2[39] * 2.0;
  t212 = t48 + in2[40] * in2[47] * t54 * 2.0;
  t213 = (t35 - t24_tmp) + t205;
  t238 = t2 * t12 * 2.0;
  t215 = (t190 - t20) + t238;
  t51_tmp = t72 * 2.0;
  t2 = (t49 - t206) + t51_tmp;
  t46 = t5 - t209;
  t4 = muDoubleScalarPower(muDoubleScalarAbs(((((t215 * in2[143] + t2 * in2[144])
    + t46 * in2[148]) - t213 * in2[142]) - t208 * in2[149]) - t212 * in2[150]),
    in1[1] - 1.0);
  t77 = t46_tmp * t43 * 2.0;
  t59 = t17_tmp * t43 * 2.0;
  t75 = t29_tmp * t43 * 2.0;
  t25 = t55 + in2[41] * in2[47] * t54 * 2.0;
  t234 = t56 + in2[41] * in2[45] * t54 * 2.0;
  t72 = in2[41] * in2[46] * t54 * 2.0;
  memset(&out1[0], 0, 36U * sizeof(real_T));
  out1[36] = t91;
  out1[37] = -t7 - b_t51_tmp;
  out1[38] = t50_tmp - in2[39] * in2[41] * 2.0;
  out1[39] = ((((t94 + t95) - t62_tmp) - t61_tmp) - t63_tmp) - t106_tmp;
  out1[40] = t86;
  out1[41] = t90;
  out1[42] = (-t8 - t11) + 1.0;
  out1[43] = t92;
  out1[44] = -t50_tmp + t52;
  memset(&out1[45], 0, 82U * sizeof(real_T));
  out1[127] = t7 - in2[39] * in2[40] * 2.0;
  out1[128] = t122;
  out1[129] = -t9 - t53_tmp;
  out1[130] = (((((t22_tmp + t115) + t116) + t117) - t127_tmp) - t23_tmp) -
    b_t127_tmp;
  out1[131] = ((((t125 + t126) - t62_tmp) - t61_tmp) - t63_tmp) - t136_tmp;
  out1[132] = t121;
  out1[133] = -t7 + b_t51_tmp;
  out1[134] = (-t8 - t10) + 1.0;
  out1[135] = t123;
  memset(&out1[136], 0, 82U * sizeof(real_T));
  out1[218] = t52_tmp * -2.0 - t50_tmp;
  out1[219] = t9 - in2[40] * in2[41] * 2.0;
  out1[220] = t154;
  out1[221] = t149;
  out1[222] = t153;
  out1[223] = ((((t157 + t29) - t62_tmp) - t61_tmp) - t63_tmp) - t17;
  out1[224] = t155;
  out1[225] = -t9 + t53_tmp;
  out1[226] = (-t10 - t11) + 1.0;
  memset(&out1[227], 0, 85U * sizeof(real_T));
  out1[312] = (t41 * -2.0 + t19) - t58;
  out1[313] = (-t35 + t178) - t24_tmp;
  out1[314] = t181;
  out1[315] = 0.0;
  out1[316] = 0.0;
  out1[317] = 0.0;
  out1[318] = t183;
  out1[319] = t186;
  out1[320] = -t56 + t187;
  memset(&out1[321], 0, 82U * sizeof(real_T));
  out1[403] = (t35 + t205) - t24_tmp;
  out1[404] = (t41 * -2.0 + t20) - t238;
  out1[405] = (-t49 + t206) - t51_tmp;
  out1[406] = 0.0;
  out1[407] = 0.0;
  out1[408] = 0.0;
  out1[409] = in2[41] * -2.0 + t209;
  out1[410] = t208;
  out1[411] = t212;
  memset(&out1[412], 0, 82U * sizeof(real_T));
  out1[494] = (in2[46] * -2.0 + t59) - t32_tmp;
  out1[495] = (t49 + t75) - t51_tmp;
  t5 = t3 * t12 * 2.0;
  out1[496] = (t41 * -2.0 + t77) - t5;
  out1[497] = 0.0;
  out1[498] = 0.0;
  out1[499] = 0.0;
  out1[500] = t234;
  out1[501] = in2[39] * -2.0 + t72;
  out1[502] = t25;
  memset(&out1[503], 0, 43U * sizeof(real_T));
  t20 = (t31 + t32_tmp) - t59;
  t238 = (t190 - t77) + t5;
  t58 = (t49 - t51_tmp) + t75;
  t75 = t48 - t72;
  t77 = muDoubleScalarPower(muDoubleScalarAbs(((((t238 * in2[144] + t20 * in2
    [142]) + t75 * in2[149]) - t58 * in2[143]) - t25 * in2[150]) - t234 * in2
    [148]), in1[1] - 1.0);
  t5 = (a_tmp * a_tmp + a * a) + b_a * b_a;
  st.site = &av_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * ((((((b_a_tmp + in2[41] * t32) - in2[40] * t34) + in2[39] *
    t64_tmp) + t6 * t27) - c_a_tmp) + t60 * (t60 / 25.0 - t73)) *
    0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp - in2[41] * t27) + in2[39] * t34) + in2[40] *
                       t64_tmp) + t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((t5 + in2[40] * t27) - in2[39] * t32) + in2[41] *
                       t64_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[40] * t43 * 2.0 - in2[41] * t42 * 2.0) + in2[39] *
                       t82 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[41] * t36 * 2.0 - in2[39] * t43 * 2.0) + in2[40] *
                       t82 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[40] * t36 * 2.0 - in2[39] * t42 * 2.0) - in2[41] *
                       t82 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t72 = in1[2] * t91 * t110;
  t59 = in1[2] * t92 * t110;
  t5 = in1[2] * t93 * t110;
  out3[0] = (((((((-in1[2] * t86 * t110 * in2[143] - t72 * in2[139]) + t59 *
                  in2[140]) - in1[2] * t90 * t110 * in2[144]) - t5 * in2[141]) +
               t72 * in2[145]) - t59 * in2[146]) + t5 * in2[147]) + in1[2] *
    t106 * t110 * in2[142];
  t72 = in1[2] * t124 * t139;
  t59 = in1[2] * t123 * t139;
  out3[1] = (((((((-in1[2] * t122 * t139 * in2[140] - t72 * in2[139]) + t59 *
                  in2[141]) - in1[2] * t121 * t139 * in2[144]) + in1[2] * t122 *
                t139 * in2[146]) + t72 * in2[145]) - in1[2] * t127 * t139 * in2
              [142]) - t59 * in2[147]) + in1[2] * t136 * t139 * in2[143];
  t72 = in1[2] * t155 * t172;
  t59 = in1[2] * t154 * t172;
  t5 = in1[2] * t156 * t172;
  out3[2] = (((((((-in1[2] * t149 * t172 * in2[142] + t72 * in2[139]) - t59 *
                  in2[141]) - in1[2] * t153 * t172 * in2[143]) - t5 * in2[140])
               - t72 * in2[145]) + t59 * in2[147]) + t5 * in2[146]) + in1[2] *
    t169 * t172 * in2[144];
  out3[3] = ((((-in1[3] * t181 * t200 * in2[144] - in1[3] * t183 * t200 * in2
                [148]) + in1[3] * t189 * t200 * in2[143]) + in1[3] * t192 * t200
              * in2[142]) - in1[3] * t186 * t200 * in2[149]) + in1[3] * t196 *
    t200 * in2[150];
  out3[4] = ((((-in1[3] * t213 * t4 * in2[142] - in1[3] * t208 * t4 * in2[149])
               + in1[3] * t215 * t4 * in2[143]) - in1[3] * t212 * t4 * in2[150])
             + in1[3] * t2 * t4 * in2[144]) + in1[3] * t46 * t4 * in2[148];
  out3[5] = ((((in1[3] * t20 * t77 * in2[142] - in1[3] * t25 * t77 * in2[150]) -
               in1[3] * t234 * t77 * in2[148]) + in1[3] * t238 * t77 * in2[144])
             - in1[3] * t58 * t77 * in2[143]) + in1[3] * t75 * t77 * in2[149];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF103.c) */
