/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF109.c
 *
 * Code generation for function 'sprdmpF109'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF109.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo lab_emlrtRSI = { 41,/* lineNo */
  "sprdmpF109",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF109.m"/* pathName */
};

static emlrtRSInfo mab_emlrtRSI = { 47,/* lineNo */
  "sprdmpF109",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF109.m"/* pathName */
};

static emlrtRSInfo qab_emlrtRSI = { 77,/* lineNo */
  "sprdmpF109",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF109.m"/* pathName */
};

static emlrtRSInfo rab_emlrtRSI = { 89,/* lineNo */
  "sprdmpF109",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF109.m"/* pathName */
};

static emlrtRSInfo dbb_emlrtRSI = { 281,/* lineNo */
  "sprdmpF109",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF109.m"/* pathName */
};

/* Function Definitions */
void sprdmpF109(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t175;
  real_T t223;
  real_T t193;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t217;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t226;
  real_T t25;
  real_T t165;
  real_T t166;
  real_T t218;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t44_tmp;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t192;
  real_T t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t216;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t62;
  real_T t63;
  real_T t64;
  real_T t66;
  real_T a_tmp;
  real_T a;
  real_T t70;
  real_T t74;
  real_T t78;
  real_T t79;
  real_T t80;
  real_T t81;
  real_T t82;
  real_T t83;
  real_T t94_tmp;
  real_T t94;
  real_T t98;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t109;
  real_T t110;
  real_T t111;
  real_T t112;
  real_T t113;
  real_T t114;
  real_T t115_tmp;
  real_T b_t115_tmp;
  real_T t115;
  real_T t124_tmp;
  real_T t124;
  real_T t127;
  real_T t137;
  real_T t141;
  real_T t142;
  real_T t143;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t157;
  real_T t160;
  real_T t167;
  real_T t169;
  real_T t171;
  real_T t174;
  real_T t177;
  real_T t180;
  real_T t184;
  real_T t188;
  real_T t196;
  real_T t200;
  real_T t201;
  real_T t203;
  real_T t206;
  real_T t212;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF109 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF109(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:35:56 */
  t2 = in2[64] * in2[64];
  t3 = in2[65] * in2[65];
  t4 = in2[63] * in2[63];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &lab_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[65] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[63] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &mab_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t175 = in2[61] - in2[67];
  t223 = in2[62] - in2[68];
  t193 = in2[60] - in2[66];
  t17_tmp = in2[63] * t12;
  t17 = (-in2[62] + in2[68]) + t17_tmp * t175;
  t19 = t175 + t17_tmp * t223;
  t20 = t6 * t175;
  t217 = in2[63] * t223;
  t22_tmp = in2[63] * t175;
  t23_tmp = t6 * t223;
  t226 = in2[64] * t193;
  t25 = t6 * t193;
  t165 = in2[65] * t175;
  t166 = in2[64] * t223;
  t218 = t25 + t165;
  t27 = t218 - t166;
  t29_tmp = in2[64] * t12;
  t29 = (-in2[60] + in2[66]) + t29_tmp * t223;
  t31 = t223 + t29_tmp * t193;
  t44_tmp = in2[65] * t193;
  t32_tmp = t20 + t217;
  t32 = t32_tmp - t44_tmp;
  t34 = (-t22_tmp + t23_tmp) + t226;
  t35 = in2[71] * 2.0;
  t36 = in2[63] - in2[69];
  t5 = ((-(in2[69] * in2[69]) - in2[70] * in2[70]) - in2[71] * in2[71]) + 1.0;
  t41 = t5;
  st.site = &qab_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[64] - in2[70];
  t43 = in2[65] - in2[71];
  t46_tmp = in2[65] * t12;
  t46 = t193 + t46_tmp * t175;
  t48 = (-in2[61] + in2[67]) + t46_tmp * t193;
  t49 = in2[69] * 2.0;
  t50_tmp = in2[64] * t6 * 2.0;
  t192 = in2[63] * in2[64];
  t51_tmp = t192 * 2.0;
  t52_tmp = in2[63] * in2[65];
  t52 = t52_tmp * 2.0;
  t216 = in2[64] * in2[65];
  t53_tmp = t216 * 2.0;
  st.site = &rab_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[64] * 2.0;
  t5 = in1[4] / 2.0;
  t58_tmp = in2[63] * t193;
  t59_tmp = in2[64] * t175;
  t60_tmp = in2[65] * t223;
  t61_tmp = (t58_tmp + t59_tmp) + t60_tmp;
  t62 = muDoubleScalarCos(t5);
  t63 = muDoubleScalarSin(t5);
  t64 = t62 * t62;
  t66 = t63 * t63;
  a_tmp = t64 * 0.011627627628 + t66 * 0.011627627628;
  a = t64 * 0.088 - t66 * 0.088;
  t70 = t6 - t41;
  t216 *= t12;
  t74 = (((((t23_tmp + t226) + t6 * t31) + t29_tmp * t27) + t216 * t175) - in2
         [64] * t29) - t22_tmp * 2.0;
  t78 = (((((-t20 + t44_tmp) + t6 * t48) + in2[65] * t46) + t46_tmp * t27) -
         t217 * 2.0) - t216 * t223;
  t79 = (t8 + t11) - 1.0;
  t80 = t7 + t51_tmp;
  t81 = t50_tmp - t52;
  t82 = in2[65] * t17;
  t83 = t17_tmp * t27;
  t94_tmp = in2[64] * t19;
  t94 = ((t61_tmp - t82) - t83) + t94_tmp;
  t98 = muDoubleScalarPower(muDoubleScalarAbs((((((((t74 * in2[167] + t78 * in2
    [168]) + t79 * in2[163]) + t81 * in2[165]) + t80 * in2[170]) - t79 * in2[169])
    - t80 * in2[164]) - t81 * in2[171]) - t94 * in2[166]), in1[1] - 1.0);
  t103 = t6 * t17;
  t104 = in2[63] * t19;
  t105 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t109 = ((((t218 + t6 * t46) + t46_tmp * t32) + t5 * t223) - in2[65] * t48) -
    t166 * 2.0;
  t110 = (t8 + t10) - 1.0;
  t111 = t9 + t53_tmp;
  t112 = t7 - t51_tmp;
  t113 = in2[63] * t29;
  t114 = t29_tmp * t32;
  t115_tmp = t226 * 2.0;
  b_t115_tmp = t5 * t193;
  t115 = (((((t22_tmp - t23_tmp) + t103) + t104) + t105) - t115_tmp) -
    b_t115_tmp;
  t124_tmp = in2[65] * t31;
  t124 = ((t61_tmp - t113) - t114) + t124_tmp;
  t127 = muDoubleScalarPower(muDoubleScalarAbs((((((((t115 * in2[166] + t109 *
    in2[168]) + t110 * in2[164]) + t112 * in2[163]) + t111 * in2[171]) - t110 *
    in2[170]) - t111 * in2[165]) - t112 * in2[169]) - t124 * in2[167]), in1[1] -
    1.0);
  t217 = t192 * t12;
  t137 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t217 * t193) - in2[63] * t17)
    - t44_tmp * 2.0;
  t141 = (((((-t25 + t166) + t6 * t29) + in2[64] * t31) + t29_tmp * t34) - t165 *
          2.0) - t217 * t175;
  t142 = (t10 + t11) - 1.0;
  t143 = t50_tmp + t52;
  t144 = t9 - t53_tmp;
  t145 = in2[64] * t48;
  t146 = t46_tmp * t34;
  t25 = in2[63] * t46;
  t157 = ((t61_tmp - t145) - t146) + t25;
  t160 = muDoubleScalarPower(muDoubleScalarAbs((((((((t137 * in2[166] + t141 *
    in2[167]) + t142 * in2[165]) + t144 * in2[164]) + t143 * in2[169]) - t142 *
    in2[171]) - t143 * in2[163]) - t144 * in2[170]) - t157 * in2[168]), in1[1] -
    1.0);
  t165 = t17_tmp * t36 * 2.0;
  t166 = t29_tmp * t36 * 2.0;
  t167 = in2[70] * 2.0;
  t29 = t5 * 2.0;
  t169 = (t167 + t46_tmp * t36 * 2.0) - t29;
  t171 = t55 + in2[63] * in2[69] * t54 * 2.0;
  t5 = in2[65] * 2.0;
  t174 = t5 + in2[63] * in2[70] * t54 * 2.0;
  t175 = in2[63] * in2[71] * t54 * 2.0;
  t44_tmp = t217 * 2.0;
  t177 = (t35 - t166) + t44_tmp;
  t31 = t41 * 2.0;
  t20 = t4 * t12 * 2.0;
  t180 = (-t165 + t31) + t20;
  t184 = t56 - t175;
  t188 = muDoubleScalarPower(muDoubleScalarAbs(((((t180 * in2[166] + t177 * in2
    [167]) + t184 * in2[174]) - t169 * in2[168]) - t171 * in2[172]) - t174 *
    in2[173]), in1[1] - 1.0);
  t192 = t29_tmp * t42 * 2.0;
  t193 = t17_tmp * t42 * 2.0;
  t17 = t46_tmp * t42 * 2.0;
  t196 = t55 + in2[64] * in2[70] * t54 * 2.0;
  t19 = in2[64] * in2[69] * t54 * 2.0;
  t4 = in2[63] * 2.0;
  t200 = t4 + in2[64] * in2[71] * t54 * 2.0;
  t201 = (t35 - t44_tmp) + t193;
  t226 = t2 * t12 * 2.0;
  t203 = (t31 - t192) + t226;
  t32_tmp = t216 * 2.0;
  t206 = (t49 - t17) + t32_tmp;
  t2 = t5 - t19;
  t212 = muDoubleScalarPower(muDoubleScalarAbs(((((t203 * in2[167] + t206 * in2
    [168]) + t2 * in2[172]) - t201 * in2[166]) - t196 * in2[173]) - t200 * in2
    [174]), in1[1] - 1.0);
  t216 = t46_tmp * t43 * 2.0;
  t217 = t17_tmp * t43 * 2.0;
  t218 = t29_tmp * t43 * 2.0;
  t48 = t55 + in2[65] * in2[71] * t54 * 2.0;
  t46 = t56 + in2[65] * in2[69] * t54 * 2.0;
  t223 = in2[65] * in2[70] * t54 * 2.0;
  memset(&out1[0], 0, 60U * sizeof(real_T));
  out1[60] = t79;
  out1[61] = -t7 - t51_tmp;
  out1[62] = t50_tmp - in2[63] * in2[65] * 2.0;
  out1[63] = ((((t82 + t83) - t59_tmp) - t58_tmp) - t60_tmp) - t94_tmp;
  out1[64] = t74;
  out1[65] = t78;
  out1[66] = (-t8 - t11) + 1.0;
  out1[67] = t80;
  out1[68] = -t50_tmp + t52;
  memset(&out1[69], 0, 82U * sizeof(real_T));
  out1[151] = t7 - in2[63] * in2[64] * 2.0;
  out1[152] = t110;
  out1[153] = -t9 - t53_tmp;
  out1[154] = (((((t22_tmp + t103) + t104) + t105) - t115_tmp) - t23_tmp) -
    b_t115_tmp;
  out1[155] = ((((t113 + t114) - t59_tmp) - t58_tmp) - t60_tmp) - t124_tmp;
  out1[156] = t109;
  out1[157] = -t7 + t51_tmp;
  out1[158] = (-t8 - t10) + 1.0;
  out1[159] = t111;
  memset(&out1[160], 0, 82U * sizeof(real_T));
  out1[242] = t52_tmp * -2.0 - t50_tmp;
  out1[243] = t9 - in2[64] * in2[65] * 2.0;
  out1[244] = t142;
  out1[245] = t137;
  out1[246] = t141;
  out1[247] = ((((t145 + t146) - t59_tmp) - t58_tmp) - t60_tmp) - t25;
  out1[248] = t143;
  out1[249] = -t9 + t53_tmp;
  out1[250] = (-t10 - t11) + 1.0;
  memset(&out1[251], 0, 85U * sizeof(real_T));
  out1[336] = (t41 * -2.0 + t165) - t20;
  out1[337] = (-t35 + t166) - t44_tmp;
  out1[338] = t169;
  out1[339] = 0.0;
  out1[340] = 0.0;
  out1[341] = 0.0;
  out1[342] = t171;
  out1[343] = t174;
  out1[344] = -t56 + t175;
  memset(&out1[345], 0, 82U * sizeof(real_T));
  out1[427] = (t35 + t193) - t44_tmp;
  out1[428] = (t41 * -2.0 + t192) - t226;
  out1[429] = (-t49 + t17) - t32_tmp;
  out1[430] = 0.0;
  out1[431] = 0.0;
  out1[432] = 0.0;
  out1[433] = in2[65] * -2.0 + t19;
  out1[434] = t196;
  out1[435] = t200;
  memset(&out1[436], 0, 82U * sizeof(real_T));
  out1[518] = (in2[70] * -2.0 + t217) - t29;
  out1[519] = (t49 + t218) - t32_tmp;
  t5 = t3 * t12 * 2.0;
  out1[520] = (t41 * -2.0 + t216) - t5;
  out1[521] = 0.0;
  out1[522] = 0.0;
  out1[523] = 0.0;
  out1[524] = t46;
  out1[525] = in2[63] * -2.0 + t223;
  out1[526] = t48;
  memset(&out1[527], 0, 19U * sizeof(real_T));
  t192 = (t167 + t29) - t217;
  t226 = (t31 - t216) + t5;
  t218 += t49 - t32_tmp;
  t217 = t4 - t223;
  t223 = muDoubleScalarPower(muDoubleScalarAbs(((((t226 * in2[168] + t192 * in2
    [166]) + t217 * in2[173]) - t218 * in2[167]) - t48 * in2[174]) - t46 * in2
    [172]), in1[1] - 1.0);
  t5 = (a_tmp * a_tmp + t64 * t66 * 0.030976) + a * a;
  st.site = &dbb_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * ((((in2[65] * t32 - in2[64] * t34) + in2[63] * t61_tmp) +
                       t6 * t27) - t62 * t63 * 0.176) * 0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp + in2[65] * t27) - in2[63] * t34) - in2[64] *
                       t61_tmp) - t6 * t32) * -0.00026666666666666668;
  out2[2] = in1[0] * ((((t5 + in2[64] * t27) - in2[63] * t32) + in2[65] *
                       t61_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[64] * t43 * 2.0 - in2[65] * t42 * 2.0) + in2[63] *
                       t70 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[65] * t36 * 2.0 - in2[63] * t43 * 2.0) + in2[64] *
                       t70 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[64] * t36 * 2.0 - in2[63] * t42 * 2.0) - in2[65] *
                       t70 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t20 = in1[2] * t79 * t98;
  t216 = in1[2] * t80 * t98;
  t5 = in1[2] * t81 * t98;
  out3[0] = (((((((-in1[2] * t74 * t98 * in2[167] - t20 * in2[163]) + t216 *
                  in2[164]) - in1[2] * t78 * t98 * in2[168]) - t5 * in2[165]) +
               t20 * in2[169]) - t216 * in2[170]) + t5 * in2[171]) + in1[2] *
    t94 * t98 * in2[166];
  t20 = in1[2] * t112 * t127;
  t216 = in1[2] * t111 * t127;
  out3[1] = (((((((-in1[2] * t110 * t127 * in2[164] - t20 * in2[163]) + t216 *
                  in2[165]) - in1[2] * t109 * t127 * in2[168]) + in1[2] * t110 *
                t127 * in2[170]) + t20 * in2[169]) - in1[2] * t115 * t127 * in2
              [166]) - t216 * in2[171]) + in1[2] * t124 * t127 * in2[167];
  t20 = in1[2] * t143 * t160;
  t216 = in1[2] * t142 * t160;
  t5 = in1[2] * t144 * t160;
  out3[2] = (((((((-in1[2] * t137 * t160 * in2[166] + t20 * in2[163]) - t216 *
                  in2[165]) - in1[2] * t141 * t160 * in2[167]) - t5 * in2[164])
               - t20 * in2[169]) + t216 * in2[171]) + t5 * in2[170]) + in1[2] *
    t157 * t160 * in2[168];
  out3[3] = ((((-in1[3] * t169 * t188 * in2[168] - in1[3] * t171 * t188 * in2
                [172]) + in1[3] * t177 * t188 * in2[167]) + in1[3] * t180 * t188
              * in2[166]) - in1[3] * t174 * t188 * in2[173]) + in1[3] * t184 *
    t188 * in2[174];
  out3[4] = ((((-in1[3] * t201 * t212 * in2[166] - in1[3] * t196 * t212 * in2
                [173]) + in1[3] * t203 * t212 * in2[167]) - in1[3] * t200 * t212
              * in2[174]) + in1[3] * t206 * t212 * in2[168]) + in1[3] * t2 *
    t212 * in2[172];
  out3[5] = ((((in1[3] * t192 * t223 * in2[166] - in1[3] * t48 * t223 * in2[174])
               - in1[3] * t46 * t223 * in2[172]) + in1[3] * t226 * t223 * in2
              [168]) - in1[3] * t218 * t223 * in2[167]) + in1[3] * t217 * t223 *
    in2[173];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF109.c) */
