/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF106.c
 *
 * Code generation for function 'sprdmpF106'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF106.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo xw_emlrtRSI = { 41, /* lineNo */
  "sprdmpF106",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF106.m"/* pathName */
};

static emlrtRSInfo yw_emlrtRSI = { 47, /* lineNo */
  "sprdmpF106",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF106.m"/* pathName */
};

static emlrtRSInfo dx_emlrtRSI = { 77, /* lineNo */
  "sprdmpF106",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF106.m"/* pathName */
};

static emlrtRSInfo ex_emlrtRSI = { 89, /* lineNo */
  "sprdmpF106",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF106.m"/* pathName */
};

static emlrtRSInfo px_emlrtRSI = { 292,/* lineNo */
  "sprdmpF106",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF106.m"/* pathName */
};

/* Function Definitions */
void sprdmpF106(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t187;
  real_T t203;
  real_T t184;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t202;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t24_tmp;
  real_T t25;
  real_T t231;
  real_T t154;
  real_T t206;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t175;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t51_tmp;
  real_T b_t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t235;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63_tmp;
  real_T t66;
  real_T t69;
  real_T t71;
  real_T a;
  real_T a_tmp;
  real_T b_a_tmp;
  real_T c_a_tmp;
  real_T b_a;
  real_T t79;
  real_T t83;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t103_tmp;
  real_T t103;
  real_T t107;
  real_T t112;
  real_T t113;
  real_T t114;
  real_T t118;
  real_T t119;
  real_T t120;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124_tmp;
  real_T b_t124_tmp;
  real_T t124;
  real_T t133_tmp;
  real_T t133;
  real_T t136;
  real_T t146;
  real_T t150;
  real_T t151;
  real_T t152;
  real_T t153;
  real_T t166;
  real_T t169;
  real_T t178;
  real_T t180;
  real_T t183;
  real_T t186;
  real_T t189;
  real_T t193;
  real_T t197;
  real_T t205;
  real_T t209;
  real_T t210;
  real_T t212;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF106 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF106(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:17:19 */
  t2 = in2[52] * in2[52];
  t3 = in2[53] * in2[53];
  t4 = in2[51] * in2[51];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &xw_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[53] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[51] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &yw_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t187 = in2[49] - in2[55];
  t203 = in2[50] - in2[56];
  t184 = in2[48] - in2[54];
  t17_tmp = in2[51] * t12;
  t17 = (-in2[50] + in2[56]) + t17_tmp * t187;
  t19 = t187 + t17_tmp * t203;
  t20 = t6 * t187;
  t202 = in2[51] * t203;
  t22_tmp = in2[51] * t187;
  t23_tmp = t6 * t203;
  t24_tmp = in2[52] * t184;
  t25 = t6 * t184;
  t231 = in2[53] * t187;
  t154 = in2[52] * t203;
  t206 = t25 + t231;
  t27 = t206 - t154;
  t29_tmp = in2[52] * t12;
  t29 = (-in2[48] + in2[54]) + t29_tmp * t203;
  t31 = t203 + t29_tmp * t184;
  t175 = in2[53] * t184;
  t32_tmp = t20 + t202;
  t32 = t32_tmp - t175;
  t34 = (-t22_tmp + t23_tmp) + t24_tmp;
  t35 = in2[59] * 2.0;
  t36 = in2[51] - in2[57];
  t5 = ((-(in2[57] * in2[57]) - in2[58] * in2[58]) - in2[59] * in2[59]) + 1.0;
  t41 = t5;
  st.site = &dx_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[52] - in2[58];
  t43 = in2[53] - in2[59];
  t46_tmp = in2[53] * t12;
  t46 = t184 + t46_tmp * t187;
  t48 = (-in2[49] + in2[55]) + t46_tmp * t184;
  t49 = in2[57] * 2.0;
  t50_tmp = in2[52] * t6 * 2.0;
  t51_tmp = in2[51] * in2[52];
  b_t51_tmp = t51_tmp * 2.0;
  t52_tmp = in2[51] * in2[53];
  t52 = t52_tmp * 2.0;
  t235 = in2[52] * in2[53];
  t53_tmp = t235 * 2.0;
  st.site = &ex_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[52] * 2.0;
  t5 = in1[4] / 2.0;
  t58 = muDoubleScalarCos(t5);
  t59 = muDoubleScalarSin(t5);
  t60_tmp = in2[51] * t184;
  t61_tmp = in2[52] * t187;
  t62_tmp = in2[53] * t203;
  t63_tmp = (t60_tmp + t61_tmp) + t62_tmp;
  t66 = t58 * 0.077 - t59 / 25.0;
  t69 = t58 / 25.0 + t59 * 0.077;
  t5 = t58 * t58;
  t71 = t59 * t59;
  a = ((-(t58 * t66) + t59 * t69) + t5 * 0.077) - t71 * 0.077;
  a_tmp = t5 * 0.033825825826023878 + t71 * 0.033825825826023878;
  b_a_tmp = t58 * t69 + t59 * t66;
  c_a_tmp = t58 * t59 * 0.154;
  b_a = b_a_tmp - c_a_tmp;
  t79 = t6 - t41;
  t66 = t235 * t12;
  t83 = (((((t23_tmp + t24_tmp) + t6 * t31) + t29_tmp * t27) + t66 * t187) -
         in2[52] * t29) - t22_tmp * 2.0;
  t87 = (((((-t20 + t175) + t6 * t48) + in2[53] * t46) + t46_tmp * t27) - t202 *
         2.0) - t66 * t203;
  t88 = (t8 + t11) - 1.0;
  t89 = t7 + b_t51_tmp;
  t90 = t50_tmp - t52;
  t91 = in2[53] * t17;
  t92 = t17_tmp * t27;
  t103_tmp = in2[52] * t19;
  t103 = ((t63_tmp - t91) - t92) + t103_tmp;
  t107 = muDoubleScalarPower(muDoubleScalarAbs((((((((t83 * in2[155] + t87 *
    in2[156]) + t88 * in2[151]) + t90 * in2[153]) + t89 * in2[158]) - t88 * in2
    [157]) - t89 * in2[152]) - t90 * in2[159]) - t103 * in2[154]), in1[1] - 1.0);
  t112 = t6 * t17;
  t113 = in2[51] * t19;
  t114 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t118 = ((((t206 + t6 * t46) + t46_tmp * t32) + t5 * t203) - in2[53] * t48) -
    t154 * 2.0;
  t119 = (t8 + t10) - 1.0;
  t120 = t9 + t53_tmp;
  t121 = t7 - b_t51_tmp;
  t122 = in2[51] * t29;
  t123 = t29_tmp * t32;
  t124_tmp = t24_tmp * 2.0;
  b_t124_tmp = t5 * t184;
  t124 = (((((t22_tmp - t23_tmp) + t112) + t113) + t114) - t124_tmp) -
    b_t124_tmp;
  t133_tmp = in2[53] * t31;
  t133 = ((t63_tmp - t122) - t123) + t133_tmp;
  t136 = muDoubleScalarPower(muDoubleScalarAbs((((((((t124 * in2[154] + t118 *
    in2[156]) + t119 * in2[152]) + t121 * in2[151]) + t120 * in2[159]) - t119 *
    in2[158]) - t120 * in2[153]) - t121 * in2[157]) - t133 * in2[155]), in1[1] -
    1.0);
  t71 = t51_tmp * t12;
  t146 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t71 * t184) - in2[51] * t17)
    - t175 * 2.0;
  t150 = (((((-t25 + t154) + t6 * t29) + in2[52] * t31) + t29_tmp * t34) - t231 *
          2.0) - t71 * t187;
  t151 = (t10 + t11) - 1.0;
  t152 = t50_tmp + t52;
  t153 = t9 - t53_tmp;
  t154 = in2[52] * t48;
  t29 = t46_tmp * t34;
  t17 = in2[51] * t46;
  t166 = ((t63_tmp - t154) - t29) + t17;
  t169 = muDoubleScalarPower(muDoubleScalarAbs((((((((t146 * in2[154] + t150 *
    in2[155]) + t151 * in2[153]) + t153 * in2[152]) + t152 * in2[157]) - t151 *
    in2[159]) - t152 * in2[151]) - t153 * in2[158]) - t166 * in2[156]), in1[1] -
    1.0);
  t19 = t17_tmp * t36 * 2.0;
  t175 = t29_tmp * t36 * 2.0;
  t31 = in2[58] * 2.0;
  t32_tmp = t5 * 2.0;
  t178 = (t31 + t46_tmp * t36 * 2.0) - t32_tmp;
  t180 = t55 + in2[51] * in2[57] * t54 * 2.0;
  t5 = in2[53] * 2.0;
  t183 = t5 + in2[51] * in2[58] * t54 * 2.0;
  t184 = in2[51] * in2[59] * t54 * 2.0;
  t24_tmp = t71 * 2.0;
  t186 = (t35 - t175) + t24_tmp;
  t187 = t41 * 2.0;
  t58 = t4 * t12 * 2.0;
  t189 = (-t19 + t187) + t58;
  t193 = t56 - t184;
  t197 = muDoubleScalarPower(muDoubleScalarAbs(((((t189 * in2[154] + t186 * in2
    [155]) + t193 * in2[162]) - t178 * in2[156]) - t180 * in2[160]) - t183 *
    in2[161]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t202 = t17_tmp * t42 * 2.0;
  t203 = t46_tmp * t42 * 2.0;
  t205 = t55 + in2[52] * in2[58] * t54 * 2.0;
  t206 = in2[52] * in2[57] * t54 * 2.0;
  t48 = in2[51] * 2.0;
  t209 = t48 + in2[52] * in2[59] * t54 * 2.0;
  t210 = (t35 - t24_tmp) + t202;
  t235 = t2 * t12 * 2.0;
  t212 = (t187 - t20) + t235;
  t51_tmp = t66 * 2.0;
  t2 = (t49 - t203) + t51_tmp;
  t46 = t5 - t206;
  t4 = muDoubleScalarPower(muDoubleScalarAbs(((((t212 * in2[155] + t2 * in2[156])
    + t46 * in2[160]) - t210 * in2[154]) - t205 * in2[161]) - t209 * in2[162]),
    in1[1] - 1.0);
  t59 = t46_tmp * t43 * 2.0;
  t71 = t17_tmp * t43 * 2.0;
  t69 = t29_tmp * t43 * 2.0;
  t25 = t55 + in2[53] * in2[59] * t54 * 2.0;
  t231 = t56 + in2[53] * in2[57] * t54 * 2.0;
  t66 = in2[53] * in2[58] * t54 * 2.0;
  memset(&out1[0], 0, 48U * sizeof(real_T));
  out1[48] = t88;
  out1[49] = -t7 - b_t51_tmp;
  out1[50] = t50_tmp - in2[51] * in2[53] * 2.0;
  out1[51] = ((((t91 + t92) - t61_tmp) - t60_tmp) - t62_tmp) - t103_tmp;
  out1[52] = t83;
  out1[53] = t87;
  out1[54] = (-t8 - t11) + 1.0;
  out1[55] = t89;
  out1[56] = -t50_tmp + t52;
  memset(&out1[57], 0, 82U * sizeof(real_T));
  out1[139] = t7 - in2[51] * in2[52] * 2.0;
  out1[140] = t119;
  out1[141] = -t9 - t53_tmp;
  out1[142] = (((((t22_tmp + t112) + t113) + t114) - t124_tmp) - t23_tmp) -
    b_t124_tmp;
  out1[143] = ((((t122 + t123) - t61_tmp) - t60_tmp) - t62_tmp) - t133_tmp;
  out1[144] = t118;
  out1[145] = -t7 + b_t51_tmp;
  out1[146] = (-t8 - t10) + 1.0;
  out1[147] = t120;
  memset(&out1[148], 0, 82U * sizeof(real_T));
  out1[230] = t52_tmp * -2.0 - t50_tmp;
  out1[231] = t9 - in2[52] * in2[53] * 2.0;
  out1[232] = t151;
  out1[233] = t146;
  out1[234] = t150;
  out1[235] = ((((t154 + t29) - t61_tmp) - t60_tmp) - t62_tmp) - t17;
  out1[236] = t152;
  out1[237] = -t9 + t53_tmp;
  out1[238] = (-t10 - t11) + 1.0;
  memset(&out1[239], 0, 85U * sizeof(real_T));
  out1[324] = (t41 * -2.0 + t19) - t58;
  out1[325] = (-t35 + t175) - t24_tmp;
  out1[326] = t178;
  out1[327] = 0.0;
  out1[328] = 0.0;
  out1[329] = 0.0;
  out1[330] = t180;
  out1[331] = t183;
  out1[332] = -t56 + t184;
  memset(&out1[333], 0, 82U * sizeof(real_T));
  out1[415] = (t35 + t202) - t24_tmp;
  out1[416] = (t41 * -2.0 + t20) - t235;
  out1[417] = (-t49 + t203) - t51_tmp;
  out1[418] = 0.0;
  out1[419] = 0.0;
  out1[420] = 0.0;
  out1[421] = in2[53] * -2.0 + t206;
  out1[422] = t205;
  out1[423] = t209;
  memset(&out1[424], 0, 82U * sizeof(real_T));
  out1[506] = (in2[58] * -2.0 + t71) - t32_tmp;
  out1[507] = (t49 + t69) - t51_tmp;
  t5 = t3 * t12 * 2.0;
  out1[508] = (t41 * -2.0 + t59) - t5;
  out1[509] = 0.0;
  out1[510] = 0.0;
  out1[511] = 0.0;
  out1[512] = t231;
  out1[513] = in2[51] * -2.0 + t66;
  out1[514] = t25;
  memset(&out1[515], 0, 31U * sizeof(real_T));
  t20 = (t31 + t32_tmp) - t71;
  t235 = (t187 - t59) + t5;
  t58 = (t49 - t51_tmp) + t69;
  t69 = t48 - t66;
  t59 = muDoubleScalarPower(muDoubleScalarAbs(((((t235 * in2[156] + t20 * in2
    [154]) + t69 * in2[161]) - t58 * in2[155]) - t25 * in2[162]) - t231 * in2
    [160]), in1[1] - 1.0);
  t5 = (a_tmp * a_tmp + b_a * b_a) + a * a;
  st.site = &px_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * (((((b_a_tmp + in2[53] * t32) - in2[52] * t34) + in2[51] *
                        t63_tmp) + t6 * t27) - c_a_tmp) * 0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp - in2[53] * t27) + in2[51] * t34) + in2[52] *
                       t63_tmp) + t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((in2[52] * t27 - in2[51] * t32) + in2[53] * t63_tmp) +
                       t6 * t34) + t5) * 0.0008;
  out2[3] = in1[0] * (((in2[52] * t43 * 2.0 - in2[53] * t42 * 2.0) + in2[51] *
                       t79 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[53] * t36 * 2.0 - in2[51] * t43 * 2.0) + in2[52] *
                       t79 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[52] * t36 * 2.0 - in2[51] * t42 * 2.0) - in2[53] *
                       t79 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t66 = in1[2] * t88 * t107;
  t71 = in1[2] * t89 * t107;
  t5 = in1[2] * t90 * t107;
  out3[0] = (((((((-in1[2] * t83 * t107 * in2[155] - t66 * in2[151]) + t71 *
                  in2[152]) - in1[2] * t87 * t107 * in2[156]) - t5 * in2[153]) +
               t66 * in2[157]) - t71 * in2[158]) + t5 * in2[159]) + in1[2] *
    t103 * t107 * in2[154];
  t66 = in1[2] * t121 * t136;
  t71 = in1[2] * t120 * t136;
  out3[1] = (((((((-in1[2] * t119 * t136 * in2[152] - t66 * in2[151]) + t71 *
                  in2[153]) - in1[2] * t118 * t136 * in2[156]) + in1[2] * t119 *
                t136 * in2[158]) + t66 * in2[157]) - in1[2] * t124 * t136 * in2
              [154]) - t71 * in2[159]) + in1[2] * t133 * t136 * in2[155];
  t66 = in1[2] * t152 * t169;
  t71 = in1[2] * t151 * t169;
  t5 = in1[2] * t153 * t169;
  out3[2] = (((((((-in1[2] * t146 * t169 * in2[154] + t66 * in2[151]) - t71 *
                  in2[153]) - in1[2] * t150 * t169 * in2[155]) - t5 * in2[152])
               - t66 * in2[157]) + t71 * in2[159]) + t5 * in2[158]) + in1[2] *
    t166 * t169 * in2[156];
  out3[3] = ((((-in1[3] * t178 * t197 * in2[156] - in1[3] * t180 * t197 * in2
                [160]) + in1[3] * t186 * t197 * in2[155]) + in1[3] * t189 * t197
              * in2[154]) - in1[3] * t183 * t197 * in2[161]) + in1[3] * t193 *
    t197 * in2[162];
  out3[4] = ((((-in1[3] * t210 * t4 * in2[154] - in1[3] * t205 * t4 * in2[161])
               + in1[3] * t212 * t4 * in2[155]) - in1[3] * t209 * t4 * in2[162])
             + in1[3] * t2 * t4 * in2[156]) + in1[3] * t46 * t4 * in2[160];
  out3[5] = ((((in1[3] * t20 * t59 * in2[154] - in1[3] * t25 * t59 * in2[162]) -
               in1[3] * t231 * t59 * in2[160]) + in1[3] * t235 * t59 * in2[156])
             - in1[3] * t58 * t59 * in2[155]) + in1[3] * t69 * t59 * in2[161];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF106.c) */
