/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF111.c
 *
 * Code generation for function 'sprdmpF111'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF111.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo dcb_emlrtRSI = { 41,/* lineNo */
  "sprdmpF111",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF111.m"/* pathName */
};

static emlrtRSInfo ecb_emlrtRSI = { 47,/* lineNo */
  "sprdmpF111",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF111.m"/* pathName */
};

static emlrtRSInfo icb_emlrtRSI = { 77,/* lineNo */
  "sprdmpF111",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF111.m"/* pathName */
};

static emlrtRSInfo jcb_emlrtRSI = { 89,/* lineNo */
  "sprdmpF111",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF111.m"/* pathName */
};

static emlrtRSInfo vcb_emlrtRSI = { 293,/* lineNo */
  "sprdmpF111",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF111.m"/* pathName */
};

/* Function Definitions */
void sprdmpF111(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13_tmp;
  real_T t203;
  real_T t15_tmp;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t234;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t207;
  real_T t25;
  real_T t230;
  real_T t232;
  real_T t204;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t175;
  real_T t176;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t51_tmp;
  real_T b_t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t227;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63_tmp;
  real_T t64;
  real_T t68;
  real_T t69;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T a;
  real_T a_tmp;
  real_T b_a;
  real_T t80;
  real_T t84;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t104_tmp;
  real_T t104;
  real_T t108;
  real_T t113;
  real_T t114;
  real_T t115;
  real_T t119;
  real_T t120;
  real_T t121;
  real_T t122;
  real_T t123;
  real_T t124;
  real_T t125_tmp;
  real_T b_t125_tmp;
  real_T t125;
  real_T t134_tmp;
  real_T t134;
  real_T t137;
  real_T t147;
  real_T t151;
  real_T t152;
  real_T t153;
  real_T t154;
  real_T t167;
  real_T t170;
  real_T t179;
  real_T t181;
  real_T t184;
  real_T t187;
  real_T t190;
  real_T t194;
  real_T t198;
  real_T t206;
  real_T t210;
  real_T t211;
  real_T t213;
  real_T t216;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF111 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF111(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:32:34 */
  t2 = in2[52] * in2[52];
  t3 = in2[53] * in2[53];
  t4 = in2[51] * in2[51];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &dcb_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[53] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[51] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &ecb_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t13_tmp = in2[49] - in2[73];
  t203 = in2[50] - in2[74];
  t15_tmp = in2[48] - in2[72];
  t17_tmp = in2[51] * t12;
  t17 = (-in2[50] + in2[74]) + t17_tmp * t13_tmp;
  t19 = t13_tmp + t17_tmp * t203;
  t20 = t6 * t13_tmp;
  t234 = in2[51] * t203;
  t22_tmp = in2[51] * t13_tmp;
  t23_tmp = t6 * t203;
  t207 = in2[52] * t15_tmp;
  t25 = t6 * t15_tmp;
  t230 = in2[53] * t13_tmp;
  t232 = in2[52] * t203;
  t204 = t25 + t230;
  t27 = t204 - t232;
  t29_tmp = in2[52] * t12;
  t29 = (-in2[48] + in2[72]) + t29_tmp * t203;
  t31 = t203 + t29_tmp * t15_tmp;
  t175 = in2[53] * t15_tmp;
  t176 = t20 + t234;
  t32 = t176 - t175;
  t34 = (-t22_tmp + t23_tmp) + t207;
  t35 = in2[77] * 2.0;
  t36 = in2[51] - in2[75];
  t5 = ((-(in2[75] * in2[75]) - in2[76] * in2[76]) - in2[77] * in2[77]) + 1.0;
  t41 = t5;
  st.site = &icb_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[52] - in2[76];
  t43 = in2[53] - in2[77];
  t46_tmp = in2[53] * t12;
  t46 = t15_tmp + t46_tmp * t13_tmp;
  t48 = (-in2[49] + in2[73]) + t46_tmp * t15_tmp;
  t49 = in2[75] * 2.0;
  t50_tmp = in2[52] * t6 * 2.0;
  t51_tmp = in2[51] * in2[52];
  b_t51_tmp = t51_tmp * 2.0;
  t52_tmp = in2[51] * in2[53];
  t52 = t52_tmp * 2.0;
  t227 = in2[52] * in2[53];
  t53_tmp = t227 * 2.0;
  st.site = &jcb_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[52] * 2.0;
  t5 = in1[4] / 2.0;
  t58 = muDoubleScalarCos(t5);
  t59 = muDoubleScalarSin(t5);
  t60_tmp = in2[51] * t15_tmp;
  t61_tmp = in2[52] * t13_tmp;
  t62_tmp = in2[53] * t203;
  t63_tmp = (t60_tmp + t61_tmp) + t62_tmp;
  t64 = t58 * t58;
  t5 = t59 * t59;
  t68 = t58 / 25.0 + t59 * 0.077;
  t69 = t58 * t68;
  t72 = t58 * 0.077 - t59 / 25.0;
  t73 = t59 * t72;
  t74 = t5 / 25.0;
  a = ((t69 + t73) + t74) - t64 / 25.0;
  a_tmp = t64 * 2.387656739E-14 + t5 * 2.387656739E-14;
  b_a = (t58 * t72 - t59 * t68) + t58 * t59 * 0.08;
  t80 = t6 - t41;
  t59 = t227 * t12;
  t84 = (((((t23_tmp + t207) + t6 * t31) + t29_tmp * t27) + t59 * t13_tmp) -
         in2[52] * t29) - t22_tmp * 2.0;
  t88 = (((((-t20 + t175) + t6 * t48) + in2[53] * t46) + t46_tmp * t27) - t234 *
         2.0) - t59 * t203;
  t89 = (t8 + t11) - 1.0;
  t90 = t7 + b_t51_tmp;
  t91 = t50_tmp - t52;
  t92 = in2[53] * t17;
  t93 = t17_tmp * t27;
  t104_tmp = in2[52] * t19;
  t104 = ((t63_tmp - t92) - t93) + t104_tmp;
  t108 = muDoubleScalarPower(muDoubleScalarAbs((((((((t84 * in2[155] + t88 *
    in2[156]) + t89 * in2[151]) + t91 * in2[153]) + t90 * in2[176]) - t89 * in2
    [175]) - t90 * in2[152]) - t91 * in2[177]) - t104 * in2[154]), in1[1] - 1.0);
  t113 = t6 * t17;
  t114 = in2[51] * t19;
  t115 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t119 = ((((t204 + t6 * t46) + t46_tmp * t32) + t5 * t203) - in2[53] * t48) -
    t232 * 2.0;
  t120 = (t8 + t10) - 1.0;
  t121 = t9 + t53_tmp;
  t122 = t7 - b_t51_tmp;
  t123 = in2[51] * t29;
  t124 = t29_tmp * t32;
  t125_tmp = t207 * 2.0;
  b_t125_tmp = t5 * t15_tmp;
  t125 = (((((t22_tmp - t23_tmp) + t113) + t114) + t115) - t125_tmp) -
    b_t125_tmp;
  t134_tmp = in2[53] * t31;
  t134 = ((t63_tmp - t123) - t124) + t134_tmp;
  t137 = muDoubleScalarPower(muDoubleScalarAbs((((((((t125 * in2[154] + t119 *
    in2[156]) + t120 * in2[152]) + t122 * in2[151]) + t121 * in2[177]) - t120 *
    in2[176]) - t121 * in2[153]) - t122 * in2[175]) - t134 * in2[155]), in1[1] -
    1.0);
  t227 = t51_tmp * t12;
  t147 = ((((t176 + t6 * t19) + t17_tmp * t34) + t227 * t15_tmp) - in2[51] * t17)
    - t175 * 2.0;
  t151 = (((((-t25 + t232) + t6 * t29) + in2[52] * t31) + t29_tmp * t34) - t230 *
          2.0) - t227 * t13_tmp;
  t152 = (t10 + t11) - 1.0;
  t153 = t50_tmp + t52;
  t154 = t9 - t53_tmp;
  t29 = in2[52] * t48;
  t31 = t46_tmp * t34;
  t19 = in2[51] * t46;
  t167 = ((t63_tmp - t29) - t31) + t19;
  t170 = muDoubleScalarPower(muDoubleScalarAbs((((((((t147 * in2[154] + t151 *
    in2[155]) + t152 * in2[153]) + t154 * in2[152]) + t153 * in2[175]) - t152 *
    in2[177]) - t153 * in2[151]) - t154 * in2[176]) - t167 * in2[156]), in1[1] -
    1.0);
  t175 = t17_tmp * t36 * 2.0;
  t176 = t29_tmp * t36 * 2.0;
  t48 = in2[76] * 2.0;
  t13_tmp = t5 * 2.0;
  t179 = (t48 + t46_tmp * t36 * 2.0) - t13_tmp;
  t181 = t55 + in2[51] * in2[75] * t54 * 2.0;
  t5 = in2[53] * 2.0;
  t184 = t5 + in2[51] * in2[76] * t54 * 2.0;
  t17 = in2[51] * in2[77] * t54 * 2.0;
  t51_tmp = t227 * 2.0;
  t187 = (t35 - t176) + t51_tmp;
  t25 = t41 * 2.0;
  t234 = t4 * t12 * 2.0;
  t190 = (-t175 + t25) + t234;
  t194 = t56 - t17;
  t198 = muDoubleScalarPower(muDoubleScalarAbs(((((t190 * in2[154] + t187 * in2
    [155]) + t194 * in2[180]) - t179 * in2[156]) - t181 * in2[178]) - t184 *
    in2[179]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t203 = t17_tmp * t42 * 2.0;
  t204 = t46_tmp * t42 * 2.0;
  t206 = t55 + in2[52] * in2[76] * t54 * 2.0;
  t207 = in2[52] * in2[75] * t54 * 2.0;
  t46 = in2[51] * 2.0;
  t210 = t46 + in2[52] * in2[77] * t54 * 2.0;
  t211 = (t35 - t51_tmp) + t203;
  t58 = t2 * t12 * 2.0;
  t213 = (t25 - t20) + t58;
  t15_tmp = t59 * 2.0;
  t216 = (t49 - t204) + t15_tmp;
  t4 = t5 - t207;
  t2 = muDoubleScalarPower(muDoubleScalarAbs(((((t213 * in2[155] + t216 * in2
    [156]) + t4 * in2[178]) - t211 * in2[154]) - t206 * in2[179]) - t210 * in2
    [180]), in1[1] - 1.0);
  t72 = t46_tmp * t43 * 2.0;
  t227 = t17_tmp * t43 * 2.0;
  t68 = t29_tmp * t43 * 2.0;
  t230 = t55 + in2[53] * in2[77] * t54 * 2.0;
  t232 = t56 + in2[53] * in2[75] * t54 * 2.0;
  t59 = in2[53] * in2[76] * t54 * 2.0;
  memset(&out1[0], 0, 48U * sizeof(real_T));
  out1[48] = t89;
  out1[49] = -t7 - b_t51_tmp;
  out1[50] = t50_tmp - in2[51] * in2[53] * 2.0;
  out1[51] = ((((t92 + t93) - t61_tmp) - t60_tmp) - t62_tmp) - t104_tmp;
  out1[52] = t84;
  out1[53] = t88;
  memset(&out1[54], 0, 18U * sizeof(real_T));
  out1[72] = (-t8 - t11) + 1.0;
  out1[73] = t90;
  out1[74] = -t50_tmp + t52;
  memset(&out1[75], 0, sizeof(real_T) << 6);
  out1[139] = t7 - in2[51] * in2[52] * 2.0;
  out1[140] = t120;
  out1[141] = -t9 - t53_tmp;
  out1[142] = (((((t22_tmp + t113) + t114) + t115) - t125_tmp) - t23_tmp) -
    b_t125_tmp;
  out1[143] = ((((t123 + t124) - t61_tmp) - t60_tmp) - t62_tmp) - t134_tmp;
  out1[144] = t119;
  memset(&out1[145], 0, 18U * sizeof(real_T));
  out1[163] = -t7 + b_t51_tmp;
  out1[164] = (-t8 - t10) + 1.0;
  out1[165] = t121;
  memset(&out1[166], 0, sizeof(real_T) << 6);
  out1[230] = t52_tmp * -2.0 - t50_tmp;
  out1[231] = t9 - in2[52] * in2[53] * 2.0;
  out1[232] = t152;
  out1[233] = t147;
  out1[234] = t151;
  out1[235] = ((((t29 + t31) - t61_tmp) - t60_tmp) - t62_tmp) - t19;
  memset(&out1[236], 0, 18U * sizeof(real_T));
  out1[254] = t153;
  out1[255] = -t9 + t53_tmp;
  out1[256] = (-t10 - t11) + 1.0;
  memset(&out1[257], 0, 67U * sizeof(real_T));
  out1[324] = (t41 * -2.0 + t175) - t234;
  out1[325] = (-t35 + t176) - t51_tmp;
  out1[326] = t179;
  memset(&out1[327], 0, 21U * sizeof(real_T));
  out1[348] = t181;
  out1[349] = t184;
  out1[350] = -t56 + t17;
  memset(&out1[351], 0, sizeof(real_T) << 6);
  out1[415] = (t35 + t203) - t51_tmp;
  out1[416] = (t41 * -2.0 + t20) - t58;
  out1[417] = (-t49 + t204) - t15_tmp;
  memset(&out1[418], 0, 21U * sizeof(real_T));
  out1[439] = in2[53] * -2.0 + t207;
  out1[440] = t206;
  out1[441] = t210;
  memset(&out1[442], 0, sizeof(real_T) << 6);
  out1[506] = (in2[76] * -2.0 + t227) - t13_tmp;
  out1[507] = (t49 + t68) - t15_tmp;
  t5 = t3 * t12 * 2.0;
  out1[508] = (t41 * -2.0 + t72) - t5;
  memset(&out1[509], 0, 21U * sizeof(real_T));
  out1[530] = t232;
  out1[531] = in2[51] * -2.0 + t59;
  out1[532] = t230;
  memset(&out1[533], 0, 13U * sizeof(real_T));
  t234 = (t48 + t13_tmp) - t227;
  t20 = (t25 - t72) + t5;
  t227 = (t49 - t15_tmp) + t68;
  t72 = t46 - t59;
  t58 = muDoubleScalarPower(muDoubleScalarAbs(((((t20 * in2[156] + t234 * in2
    [154]) + t72 * in2[179]) - t227 * in2[155]) - t230 * in2[180]) - t232 * in2
    [178]), in1[1] - 1.0);
  t5 = (a * a + a_tmp * a_tmp) + b_a * b_a;
  st.site = &vcb_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * (((((((t64 * -0.04 + t69) + t73) + t74) + in2[53] * t32) -
                        in2[52] * t34) + in2[51] * t63_tmp) + t6 * t27) *
    0.00026666666666666668;
  out2[1] = in1[0] * ((((a_tmp - in2[53] * t27) + in2[51] * t34) + in2[52] *
                       t63_tmp) + t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((t5 + in2[52] * t27) - in2[51] * t32) + in2[53] *
                       t63_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[52] * t43 * 2.0 - in2[53] * t42 * 2.0) + in2[51] *
                       t80 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[53] * t36 * 2.0 - in2[51] * t43 * 2.0) + in2[52] *
                       t80 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[52] * t36 * 2.0 - in2[51] * t42 * 2.0) - in2[53] *
                       t80 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t68 = in1[2] * t89 * t108;
  t59 = in1[2] * t90 * t108;
  t5 = in1[2] * t91 * t108;
  out3[0] = (((((((-in1[2] * t84 * t108 * in2[155] - t68 * in2[151]) + t59 *
                  in2[152]) - in1[2] * t88 * t108 * in2[156]) - t5 * in2[153]) +
               in1[2] * t104 * t108 * in2[154]) + t68 * in2[175]) - t59 * in2
             [176]) + t5 * in2[177];
  t68 = in1[2] * t122 * t137;
  t59 = in1[2] * t121 * t137;
  out3[1] = (((((((-in1[2] * t120 * t137 * in2[152] - t68 * in2[151]) + t59 *
                  in2[153]) - in1[2] * t119 * t137 * in2[156]) - in1[2] * t125 *
                t137 * in2[154]) + in1[2] * t134 * t137 * in2[155]) + in1[2] *
              t120 * t137 * in2[176]) + t68 * in2[175]) - t59 * in2[177];
  t68 = in1[2] * t153 * t170;
  t59 = in1[2] * t152 * t170;
  t5 = in1[2] * t154 * t170;
  out3[2] = (((((((-in1[2] * t147 * t170 * in2[154] + t68 * in2[151]) - t59 *
                  in2[153]) - in1[2] * t151 * t170 * in2[155]) - t5 * in2[152])
               + in1[2] * t167 * t170 * in2[156]) - t68 * in2[175]) + t59 * in2
             [177]) + t5 * in2[176];
  out3[3] = ((((-in1[3] * t179 * t198 * in2[156] + in1[3] * t187 * t198 * in2
                [155]) + in1[3] * t190 * t198 * in2[154]) - in1[3] * t181 * t198
              * in2[178]) - in1[3] * t184 * t198 * in2[179]) + in1[3] * t194 *
    t198 * in2[180];
  out3[4] = ((((-in1[3] * t211 * t2 * in2[154] + in1[3] * t213 * t2 * in2[155])
               + in1[3] * t216 * t2 * in2[156]) - in1[3] * t206 * t2 * in2[179])
             - in1[3] * t210 * t2 * in2[180]) + in1[3] * t4 * t2 * in2[178];
  out3[5] = ((((in1[3] * t234 * t58 * in2[154] + in1[3] * t20 * t58 * in2[156])
               - in1[3] * t227 * t58 * in2[155]) - in1[3] * t230 * t58 * in2[180])
             - in1[3] * t232 * t58 * in2[178]) + in1[3] * t72 * t58 * in2[179];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF111.c) */
