function out1 = sprdmpVd1(in1,in2,s,ds,t_sym)
%SPRDMPVD1
%    OUT1 = SPRDMPVD1(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:01:34

out1 = 0.0;
