function out1 = sprdmpDl15(in1,in2,s,ds,t_sym)
%SPRDMPDL15
%    OUT1 = SPRDMPDL15(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:08:58

q15 = in2(15,:);
out1 = q15;
