function out1 = sprdmpIn16(in1,in2,s,ds,t_sym)
%SPRDMPIN16
%    OUT1 = SPRDMPIN16(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:08:55

out1 = 0.0;
