function out1 = sprdmpKx4(in1,in2,s,ds,t_sym)
%SPRDMPKX4
%    OUT1 = SPRDMPKX4(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:01:23

out1 = 0.0;
