function out1 = sprdmpTtu10(in1,in2,s,ds,t_sym)
%SPRDMPTTU10
%    OUT1 = SPRDMPTTU10(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:08:56

out1 = zeros(0,0);
