function out1 = sprdmpTtu16(in1,in2,s,ds,t_sym)
%SPRDMPTTU16
%    OUT1 = SPRDMPTTU16(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Apr-2021 13:08:57

out1 = zeros(0,0);
