/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF1.c
 *
 * Code generation for function 'sprdmpF1'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "sprdmpF1.h"

/* Function Definitions */
void sprdmpF1(real_T phi_sym, const real_T in2[2], real_T s, real_T *out1,
              real_T *out2, real_T *out3, real_T *out4, real_T *out5, real_T
              *out6, real_T *out7, real_T *out8)
{
  (void)phi_sym;
  (void)s;

  /* SPRDMPF1 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF1(PHI_SYM,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jul-2019 03:44:29 */
  *out5 = in2[0];
  *out1 = 1.0;
  *out2 = 0.0;
  *out3 = 0.0;
  *out4 = 0.0;
  *out6 = 0.0;
  *out7 = 0.0;
  *out8 = 1.0;
}

/* End of code generation (sprdmpF1.c) */
