function fj_k = fj_kF(in1,in2,s)
%FJ_KF
%    FJ_K = FJ_KF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jan-2019 18:00:05

fj_k = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
