/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_kF.c
 *
 * Code generation for function 'fj_kF'
 *
 */

/* Include files */
#include <string.h>
#include "rt_nonfinite.h"
#include "fj_kF.h"

/* Function Definitions */
void fj_kF(const real_T in1[34], const real_T in2[24], real_T s, real_T fj_k[12])
{
  (void)in1;
  (void)in2;
  (void)s;

  /* FJ_KF */
  /*     FJ_K = FJ_KF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 18:37:20 */
  memset(&fj_k[0], 0, 12U * sizeof(real_T));
}

/* End of code generation (fj_kF.c) */
