/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rksF.c
 *
 * Code generation for function 'rksF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rksF.h"

/* Function Definitions */
void rksF(const real_T in1[34], const real_T in2[72], real_T s, real_T r_ks[36])
{
  real_T dv0[36];
  int32_T i0;
  int32_T i1;
  (void)in1;
  (void)s;

  /* RKSF */
  /*     R_KS = RKSF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     30-Jan-2019 18:15:18 */
  dv0[0] = 0.0;
  dv0[1] = in2[0];
  dv0[2] = in2[6];
  dv0[3] = in2[12];
  dv0[4] = in2[18];
  dv0[5] = in2[24];
  dv0[6] = 0.0;
  dv0[7] = in2[1];
  dv0[8] = in2[7];
  dv0[9] = in2[13];
  dv0[10] = in2[19];
  dv0[11] = in2[25];
  dv0[12] = 0.0;
  dv0[13] = in2[2];
  dv0[14] = in2[8];
  dv0[15] = in2[14];
  dv0[16] = in2[20];
  dv0[17] = in2[26];
  dv0[18] = in2[0];
  dv0[19] = in2[6];
  dv0[20] = in2[12];
  dv0[21] = in2[18];
  dv0[22] = in2[24];
  dv0[23] = in2[30];
  dv0[24] = in2[1];
  dv0[25] = in2[7];
  dv0[26] = in2[13];
  dv0[27] = in2[19];
  dv0[28] = in2[25];
  dv0[29] = in2[31];
  dv0[30] = in2[2];
  dv0[31] = in2[8];
  dv0[32] = in2[14];
  dv0[33] = in2[20];
  dv0[34] = in2[26];
  dv0[35] = in2[32];
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 6; i1++) {
      r_ks[i1 + 6 * i0] = dv0[i1 + 6 * i0];
    }
  }
}

/* End of code generation (rksF.c) */
