/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[36],
            real_T s, real_T r_jtip[24])
{
  real_T t2;
  real_T t3;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t13;
  real_T t11;
  real_T t12;
  real_T t18;
  real_T t14;
  real_T t17;
  real_T t15;
  real_T t16;
  real_T t19;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t26;
  real_T t27;
  real_T t28;
  real_T t40;
  real_T t29;
  real_T t30;
  real_T t31;
  real_T t32;
  real_T t41;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t42;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t46;
  real_T t49;
  real_T t53;
  real_T t56;
  real_T t60;
  real_T t61;
  real_T t62;
  real_T t63;
  real_T t64;
  real_T t65;
  real_T t67;
  real_T t71;
  real_T t73;
  real_T t76;
  real_T b_in2[24];
  int32_T i0;
  int32_T i1;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     30-Jan-2019 17:48:34 */
  t2 = in1[4] * 0.33333333333333331;
  t3 = in2[8] + t2;
  t7 = (in2[3] * in2[6] * 0.5 + in2[4] * in2[7] * 0.5) + in2[5] * t3 * 0.5;
  t8 = in2[5] * in2[6] * 0.5;
  t9 = in2[4] * t3 * 0.5;
  t10 = in2[3] * in2[7] * 0.5;
  t13 = in2[4] * in2[6] * 0.5;
  t11 = ((in2[8] + t2) + t10) - t13;
  t12 = in1[4] * 0.66666666666666663;
  t18 = in2[3] * t3 * 0.5;
  t14 = (in2[7] + t8) - t18;
  t17 = in2[5] * in2[7] * 0.5;
  t15 = (in2[6] + t9) - t17;
  t16 = in2[3] * t7 * 0.5;
  t19 = in2[4] * t11 * 0.5;
  t20 = in2[4] * t7 * 0.5;
  t21 = in2[5] * t15 * 0.5;
  t22 = in2[3] * in2[9] * 0.25;
  t23 = in2[4] * in2[10] * 0.25;
  t24 = in2[5] * in2[11] * 0.25;
  t25 = ((t22 + t23) + t24) - 1.0;
  t26 = in2[3] * 0.5;
  t27 = in2[9] * 0.5;
  t28 = in2[4] * in2[11] * 0.25;
  t40 = in2[5] * in2[10] * 0.25;
  t29 = ((t26 + t27) + t28) - t40;
  t30 = in2[4] * 0.5;
  t31 = in2[10] * 0.5;
  t32 = in2[5] * in2[9] * 0.25;
  t41 = in2[3] * in2[11] * 0.25;
  t33 = ((t30 + t31) + t32) - t41;
  t34 = in2[5] * 0.5;
  t35 = in2[11] * 0.5;
  t36 = in2[3] * in2[10] * 0.25;
  t42 = in2[4] * in2[9] * 0.25;
  t37 = ((t34 + t35) + t36) - t42;
  t38 = in2[5] * t7 * 0.5;
  t39 = in2[3] * t14 * 0.5;
  t7 = in2[14] + t2;
  t46 = (t25 * t7 + in2[12] * t33) - in2[13] * t29;
  t49 = (in2[13] * t37 + in2[12] * t25) - t33 * t7;
  t53 = (in2[12] * t29 + in2[13] * t33) + t37 * t7;
  t56 = (t29 * t7 + in2[13] * t25) - in2[12] * t37;
  t60 = t37 * t56;
  t61 = t29 * t53;
  t62 = t25 * t49;
  t63 = t29 * t46;
  t64 = t33 * t53;
  t65 = t25 * t56;
  t67 = (((((t26 + t27) + t28) - t40) + in2[17] * t33 * 0.5) - in2[16] * t37 *
         0.5) - in2[15] * t25 * 0.5;
  t71 = (((((t22 + t23) + t24) + in2[15] * t29 * 0.5) + in2[16] * t33 * 0.5) +
         in2[17] * t37 * 0.5) - 1.0;
  t73 = (((((t30 + t31) + t32) - t41) + in2[15] * t37 * 0.5) - in2[17] * t29 *
         0.5) - in2[16] * t25 * 0.5;
  t42 = (((((t34 + t35) + t36) - t42) + in2[16] * t29 * 0.5) - in2[15] * t33 *
         0.5) - in2[17] * t25 * 0.5;
  t76 = t33 * t49;
  t7 = t37 * t53;
  t26 = t25 * t46;
  t27 = t33 * t46;
  t28 = in2[5] * t14 * 0.5;
  t40 = (((((((((in2[0] + in2[6]) + t9) + t16) - t17) + t19) + t60) + t61) + t62)
         - t27) - t28;
  t22 = t37 * t49;
  t23 = in2[3] * t11 * 0.5;
  t24 = (((((((((in2[1] + in2[7]) + t8) - t18) + t20) + t21) + t63) + t64) + t65)
         - t22) - t23;
  t30 = t29 * t56;
  t31 = in2[4] * t15 * 0.5;
  t32 = ((((((((((in2[2] + in2[8]) + t10) + t12) - t13) + t38) + t39) + t76) +
           t7) + t26) - t30) - t31;
  t41 = t67 * t67;
  t34 = t73 * t73;
  t35 = t42 * t42;
  t36 = t71 * t71;
  b_in2[0] = in2[0];
  b_in2[1] = (((((in2[0] + in2[6]) + t9) + t16) + t19) - in2[5] * in2[7] * 0.5)
    - in2[5] * t14 * 0.5;
  b_in2[2] = t40;
  b_in2[3] = t40;
  b_in2[4] = in2[1];
  b_in2[5] = (((((in2[1] + in2[7]) + t8) + t20) + t21) - in2[3] * t3 * 0.5) -
    in2[3] * t11 * 0.5;
  b_in2[6] = t24;
  b_in2[7] = t24;
  b_in2[8] = in2[2] + t2;
  b_in2[9] = ((((((in2[2] + in2[8]) + t10) + t12) - t13) + t38) + t39) - in2[4] *
    t15 * 0.5;
  b_in2[10] = t32;
  b_in2[11] = t32;
  b_in2[12] = (in2[0] + in1[4] * in2[4] * 0.33333333333333331) + in1[4] * in2[3]
    * in2[5] * 0.16666666666666666;
  b_in2[13] = (((((((in2[0] + in2[6]) + t9) + t16) - t17) + t19) - in2[5] * t14 *
                0.5) - in1[4] * t25 * t33 * 0.66666666666666663) + in1[4] * t29 *
    t37 * 0.66666666666666663;
  b_in2[14] = (((((((((((in2[0] + in2[6]) + t9) + t16) - t17) + t19) + t60) +
                   t61) + t62) - in2[5] * t14 * 0.5) - t33 * t46) + in1[4] * t67
               * t42 * 0.66666666666666663) - in1[4] * t71 * t73 *
    0.66666666666666663;
  b_in2[15] = (((((((((((in2[0] + in2[6]) + t9) + t16) - t17) + t19) + t60) +
                   t61) + t62) - t27) - t28) + in1[16] * t67 * t42 * 2.0) - in1
    [16] * t71 * t73 * 2.0;
  b_in2[16] = (in2[1] - in1[4] * in2[3] * 0.33333333333333331) + in1[4] * in2[4]
    * in2[5] * 0.16666666666666666;
  b_in2[17] = (((((((in2[1] + in2[7]) + t8) - t18) + t20) + t21) - in2[3] * t11 *
                0.5) + in1[4] * t25 * t29 * 0.66666666666666663) + in1[4] * t33 *
    t37 * 0.66666666666666663;
  b_in2[18] = (((((((((((in2[1] + in2[7]) + t8) - t18) + t20) + t21) + t63) +
                   t64) + t65) - in2[3] * t11 * 0.5) - t37 * t49) + in1[4] * t67
               * t71 * 0.66666666666666663) + in1[4] * t73 * t42 *
    0.66666666666666663;
  b_in2[19] = (((((((((((in2[1] + in2[7]) + t8) - t18) + t20) + t21) + t63) +
                   t64) + t65) - t22) - t23) + in1[16] * t67 * t71 * 2.0) + in1
    [16] * t73 * t42 * 2.0;
  b_in2[20] = (((in2[2] + t12) - in1[4] * (in2[3] * in2[3]) *
                0.083333333333333329) - in1[4] * (in2[4] * in2[4]) *
               0.083333333333333329) + in1[4] * (in2[5] * in2[5]) *
    0.083333333333333329;
  b_in2[21] = ((((((((((in2[2] + in2[8]) + t10) + t12) - t13) + t38) + t39) -
                  in2[4] * t15 * 0.5) + in1[4] * (t25 * t25) *
                 0.33333333333333331) - in1[4] * (t29 * t29) *
                0.33333333333333331) - in1[4] * (t33 * t33) *
               0.33333333333333331) + in1[4] * (t37 * t37) * 0.33333333333333331;
  b_in2[22] = ((((((((((((((in2[2] + in2[8]) + t10) + t12) - t13) + t38) + t39)
                      + t76) + t7) + t26) - in1[4] * t41 * 0.33333333333333331)
                  - in1[4] * t34 * 0.33333333333333331) + in1[4] * t35 *
                 0.33333333333333331) + in1[4] * t36 * 0.33333333333333331) -
               in2[4] * t15 * 0.5) - t29 * t56;
  b_in2[23] = ((((((((((((((in2[2] + in2[8]) + t10) + t12) - t13) + t38) + t39)
                      + t76) + t7) + t26) - t30) - t31) - in1[16] * t41) - in1
                [16] * t34) + in1[16] * t35) + in1[16] * t36;
  for (i0 = 0; i0 < 6; i0++) {
    for (i1 = 0; i1 < 4; i1++) {
      r_jtip[i1 + (i0 << 2)] = b_in2[i1 + (i0 << 2)];
    }
  }
}

/* End of code generation (rjtipF.c) */
