/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * fj_vd_matF.c
 *
 * Code generation for function 'fj_vd_matF'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "fj_vd_matF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 28,    /* lineNo */
  "fj_vd_matF",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/fj_vd_matF.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 49,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 61,  /* lineNo */
  "power",                             /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/ops/power.m"/* pathName */
};

/* Function Definitions */
void fj_vd_matF(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
                real_T s, real_T fj_vd_mat[144])
{
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  (void)s;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* FJ_VD_MATF */
  /*     FJ_VD_MAT = FJ_VD_MATF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 07:54:27 */
  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[12] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[13] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[14] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[15] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[16] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[17] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[18] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[19] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[20] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[21] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[22] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  st.site = &emlrtRSI;
  b_st.site = &b_emlrtRSI;
  if ((in2[23] < 0.0) && (!muDoubleScalarIsNaN(in1[11] - 1.0)) &&
      (muDoubleScalarFloor(in1[11] - 1.0) != in1[11] - 1.0)) {
    c_st.site = &c_emlrtRSI;
    error(&c_st);
  }

  fj_vd_mat[0] = -in1[5] * muDoubleScalarPower(in2[12], in1[11] - 1.0);
  memset(&fj_vd_mat[1], 0, 12U * sizeof(real_T));
  fj_vd_mat[13] = -in1[6] * muDoubleScalarPower(in2[13], in1[11] - 1.0);
  memset(&fj_vd_mat[14], 0, 12U * sizeof(real_T));
  fj_vd_mat[26] = -in1[7] * muDoubleScalarPower(in2[14], in1[11] - 1.0);
  memset(&fj_vd_mat[27], 0, 12U * sizeof(real_T));
  fj_vd_mat[39] = -in1[10] * muDoubleScalarPower(in2[15], in1[11] - 1.0);
  memset(&fj_vd_mat[40], 0, 12U * sizeof(real_T));
  fj_vd_mat[52] = -in1[8] * muDoubleScalarPower(in2[16], in1[11] - 1.0);
  memset(&fj_vd_mat[53], 0, 12U * sizeof(real_T));
  fj_vd_mat[65] = -in1[9] * muDoubleScalarPower(in2[17], in1[11] - 1.0);
  memset(&fj_vd_mat[66], 0, 12U * sizeof(real_T));
  fj_vd_mat[78] = -in1[5] * muDoubleScalarPower(in2[18], in1[11] - 1.0);
  memset(&fj_vd_mat[79], 0, 12U * sizeof(real_T));
  fj_vd_mat[91] = -in1[6] * muDoubleScalarPower(in2[19], in1[11] - 1.0);
  memset(&fj_vd_mat[92], 0, 12U * sizeof(real_T));
  fj_vd_mat[104] = -in1[7] * muDoubleScalarPower(in2[20], in1[11] - 1.0);
  memset(&fj_vd_mat[105], 0, 12U * sizeof(real_T));
  fj_vd_mat[117] = -in1[10] * muDoubleScalarPower(in2[21], in1[11] - 1.0);
  memset(&fj_vd_mat[118], 0, 12U * sizeof(real_T));
  fj_vd_mat[130] = -in1[8] * muDoubleScalarPower(in2[22], in1[11] - 1.0);
  memset(&fj_vd_mat[131], 0, 12U * sizeof(real_T));
  fj_vd_mat[143] = -in1[9] * muDoubleScalarPower(in2[23], in1[11] - 1.0);
}

/* End of code generation (fj_vd_matF.c) */
