/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"
#include "error.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 22,    /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo b_emlrtRSI = { 23,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo c_emlrtRSI = { 37,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo d_emlrtRSI = { 38,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo e_emlrtRSI = { 39,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo f_emlrtRSI = { 41,  /* lineNo */
  "rjtipF",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/rjtipF.m"/* pathName */
};

static emlrtRSInfo h_emlrtRSI = { 12,  /* lineNo */
  "sqrt",                              /* fcnName */
  "/usr/local/MATLAB/R2018b/toolbox/eml/lib/matlab/elfun/sqrt.m"/* pathName */
};

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[24],
            real_T s, real_T r_jtip[12])
{
  real_T t2;
  real_T t3;
  real_T t4_tmp;
  real_T t5_tmp;
  real_T t8;
  real_T t11;
  real_T t14;
  real_T t15_tmp;
  real_T t16_tmp;
  real_T t17;
  real_T t18;
  real_T t19;
  real_T t21;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T r_jtip_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     04-Jan-2019 15:17:26 */
  st.site = &emlrtRSI;
  t2 = in1[4] * in1[4];
  st.site = &b_emlrtRSI;
  t3 = s * s;
  t4_tmp = in2[0] * t2;
  t5_tmp = in1[4] * in2[1];
  t8 = in1[4] * in2[6] + in2[7] * t2;
  t11 = in1[4] * in2[8] + in2[9] * t2;
  t14 = in1[4] * in2[10] + in2[11] * t2;
  t15_tmp = in2[2] * t2;
  t16_tmp = in1[4] * in2[3];
  st.site = &c_emlrtRSI;
  t17 = t8 * t8;
  st.site = &d_emlrtRSI;
  t18 = t11 * t11;
  st.site = &e_emlrtRSI;
  t19 = t14 * t14;
  t21 = ((-t17 - t18) - t19) + 1.0;
  st.site = &f_emlrtRSI;
  if (t21 < 0.0) {
    b_st.site = &h_emlrtRSI;
    error(&b_st);
  }

  t21 = muDoubleScalarSqrt(t21);
  t22_tmp = in2[4] * t2;
  t23_tmp = in1[4] * in2[5];
  r_jtip[0] = t4_tmp * t3 + t5_tmp * s * t2 * t3;
  r_jtip_tmp = t4_tmp + t5_tmp * t2;
  r_jtip[1] = r_jtip_tmp;
  r_jtip[2] = t15_tmp * t3 + t16_tmp * s * t2 * t3;
  t16_tmp = t15_tmp + t16_tmp * t2;
  r_jtip[3] = t16_tmp;
  r_jtip[4] = (in1[4] * s + t22_tmp * t3) + t23_tmp * s * t2 * t3;
  t15_tmp = (in1[4] + t22_tmp) + t23_tmp * t2;
  r_jtip[5] = t15_tmp;
  r_jtip[6] = rtNaN;
  t5_tmp = in1[16] * t11;
  t4_tmp = in1[16] * t8;
  r_jtip[7] = (r_jtip_tmp + t4_tmp * t14 * 2.0) + t5_tmp * t21 * 2.0;
  r_jtip[8] = rtNaN;
  r_jtip[9] = (t16_tmp + t5_tmp * t14 * 2.0) - t4_tmp * t21 * 2.0;
  r_jtip[10] = rtNaN;
  r_jtip[11] = (((t15_tmp - in1[16] * t17) - in1[16] * t18) + in1[16] * t19) -
    in1[16] * (((t17 + t18) + t19) - 1.0);
}

/* End of code generation (rjtipF.c) */
