/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF2.h"

/* Function Definitions */
void massF2(const real_T in1[34], const real_T in2[12], real_T out1[36], real_T
            out2[36], real_T out3[36], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t9;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t123;
  real_T t124;
  real_T t20;
  real_T t21_tmp;
  real_T t21;
  real_T t24_tmp;
  real_T t101;
  real_T t24;
  real_T t25_tmp;
  real_T t25;
  real_T t35_tmp;
  real_T t29_tmp;
  real_T t33;
  real_T t34;
  real_T t36;
  real_T t37_tmp;
  real_T t37;
  real_T t38_tmp;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T t42;
  real_T t43_tmp;
  real_T t46_tmp;
  real_T t45_tmp;
  real_T t45;
  real_T t47_tmp;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t50;
  real_T t51;
  real_T t52;
  real_T out2_tmp;
  real_T t122;
  real_T b_out2_tmp;
  real_T c_out2_tmp;
  real_T d_out2_tmp;
  real_T e_out2_tmp;
  real_T f_out2_tmp;
  real_T g_out2_tmp;
  real_T h_out2_tmp;
  real_T t53;
  real_T t62;
  real_T t54_tmp;
  real_T t55;
  real_T t58;
  real_T t61;
  real_T t64;
  real_T t65;
  real_T t66;
  real_T t68;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T t75;
  real_T t76_tmp;
  real_T t77_tmp;
  real_T t86;
  real_T t97;
  real_T t100_tmp;
  real_T t100;
  real_T t102;
  real_T t104;
  real_T t105;
  real_T t107;
  real_T t108;
  real_T t113_tmp_tmp;
  real_T t113;
  real_T t120_tmp;
  real_T t125;
  real_T t128_tmp;
  real_T t130;
  real_T t131;
  real_T t136;
  real_T t137;
  real_T t140;
  real_T t149;
  real_T t151;
  real_T t153;
  real_T t154;
  real_T t157;
  real_T t158;
  real_T t159;
  real_T t160;
  real_T t163;
  real_T t164;
  real_T t166_tmp;
  real_T t167_tmp;
  real_T t168_tmp;
  real_T t169_tmp;
  real_T t170;
  real_T t171;
  real_T t172_tmp;
  real_T t173_tmp;
  real_T t174;

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 21:11:17 */
  t2 = in1[16] * in1[16];
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  t9 = in2[5] / 2.0;
  t2 = in2[3] / 2.0;
  t3 = in2[4] / 2.0;
  t12 = muDoubleScalarCos(t3);
  t13 = muDoubleScalarCos(t9);
  t14 = muDoubleScalarSin(t2);
  t15 = muDoubleScalarCos(t2);
  t16 = muDoubleScalarSin(t3);
  t17 = muDoubleScalarSin(t9);
  t123 = t12 * t15 * t17;
  t124 = t13 * t14 * t16;
  t20 = t123 + t124;
  t21_tmp = t12 * t14 * t17;
  t21 = t21_tmp / 2.0;
  t2 = t12 * t13;
  t24_tmp = t2 * t14;
  t101 = t15 * t16 * t17;
  t24 = t24_tmp + t101;
  t25_tmp = t2 * t15;
  t25 = t25_tmp / 2.0;
  t2 = t123 / 2.0;
  t3 = t124 / 2.0;
  t35_tmp = t13 * t15 * t16;
  t29_tmp = t21_tmp - t35_tmp;
  t9 = t24_tmp / 2.0;
  t12 = t101 / 2.0;
  t33 = t2 + t3;
  t34 = t9 + t12;
  t36 = t35_tmp / 2.0;
  t37_tmp = t14 * t16 * t17;
  t37 = t37_tmp / 2.0;
  t38_tmp = t21 - t36;
  t39 = t2 - t3;
  t40 = t9 - t12;
  t41 = t21 + t36;
  t42 = t25 + t37;
  t43_tmp = t25_tmp - t37_tmp;
  t46_tmp = t25 - t37;
  t45_tmp = in1[16] * t24;
  t45 = t45_tmp * t46_tmp;
  t47_tmp = in1[16] * t33;
  t47 = t47_tmp * t43_tmp;
  t48 = t20 * t33 * 2.0;
  t49 = t24 * t34 * 2.0;
  t50 = t46_tmp * t43_tmp * 2.0;
  t51 = t20 * t34 * 2.0;
  t52 = t24 * t33 * 2.0;
  out2[0] = 1.0;
  out2[1] = 0.0;
  out2[2] = 0.0;
  out2[3] = 0.0;
  out2[4] = 0.0;
  out2[5] = 0.0;
  out2[6] = 0.0;
  out2[7] = 1.0;
  out2[8] = 0.0;
  out2[9] = 0.0;
  out2[10] = 0.0;
  out2[11] = 0.0;
  out2[12] = 0.0;
  out2[13] = 0.0;
  out2[14] = 1.0;
  out2[15] = 0.0;
  out2[16] = 0.0;
  out2[17] = 0.0;
  out2_tmp = in1[16] * t29_tmp;
  t122 = -in1[16] * t20;
  b_out2_tmp = in1[16] * t43_tmp;
  out2[18] = ((t122 * t34 - t45_tmp * t33) - out2_tmp * (t25 - t14 * t16 * t17 /
    2.0)) - b_out2_tmp * (t21 - t13 * t15 * t16 / 2.0);
  c_out2_tmp = in1[16] * t20;
  t2 = t45_tmp * t38_tmp;
  t3 = out2_tmp * t34;
  t9 = c_out2_tmp * t46_tmp;
  out2[19] = ((t47 - t2) - t3) + t9;
  t12 = c_out2_tmp * t38_tmp;
  t15 = out2_tmp * t33;
  d_out2_tmp = in1[16] * t34;
  out2[20] = ((t45 - t15) - d_out2_tmp * t43_tmp) + t12;
  out2[21] = ((t24 * t38_tmp * -2.0 - t29_tmp * t34 * 2.0) - t20 * t46_tmp * 2.0)
    - t33 * t43_tmp * 2.0;
  t13 = t38_tmp * t43_tmp * 2.0;
  out2[22] = ((t51 + t52) - t29_tmp * t46_tmp * 2.0) - t13;
  out2[23] = ((-t48 + t49) + t50) - t29_tmp * t38_tmp * 2.0;
  e_out2_tmp = in1[16] * t40;
  out2[24] = ((t122 * t41 + t45_tmp * t42) - out2_tmp * t39) + e_out2_tmp *
    t43_tmp;
  f_out2_tmp = in1[16] * t42;
  out2[25] = ((c_out2_tmp * t39 + t45_tmp * t40) - out2_tmp * t41) - f_out2_tmp *
    t43_tmp;
  g_out2_tmp = in1[16] * t41;
  out2[26] = ((t122 * t40 + t45_tmp * t39) - g_out2_tmp * t43_tmp) + f_out2_tmp *
    t29_tmp;
  out2[27] = ((t20 * t39 * -2.0 + t24 * t40 * 2.0) - t29_tmp * t41 * 2.0) + t42 *
    t43_tmp * 2.0;
  out2[28] = ((t20 * t41 * 2.0 - t24 * t42 * 2.0) - t29_tmp * t39 * 2.0) + t40 *
    t43_tmp * 2.0;
  out2[29] = ((t20 * t42 * 2.0 + t24 * t41 * 2.0) + t40 * t29_tmp * 2.0) + t39 *
    t43_tmp * 2.0;
  h_out2_tmp = in1[16] * t38_tmp;
  out2[30] = ((t122 * t33 - t45_tmp * t34) + h_out2_tmp * t29_tmp) + b_out2_tmp *
    t46_tmp;
  out2[31] = ((t45 - t12) - t15) + in1[16] * t34 * (t25_tmp - t37_tmp);
  out2[32] = ((-t47 - t2) - t3) - t9;
  out2[33] = ((t29_tmp * t33 * -2.0 - t34 * t43_tmp * 2.0) + t20 * t38_tmp * 2.0)
    + t24 * t46_tmp * 2.0;
  out2[34] = ((t48 + t49) + t50) + t38_tmp * t29_tmp * 2.0;
  out2[35] = ((-t51 + t52) - t13) + (t21_tmp - t35_tmp) * (t25 - t37) * 2.0;
  t53 = t21_tmp / 4.0;
  t62 = t35_tmp / 4.0;
  t54_tmp = t53 - t62;
  t55 = t25_tmp / 4.0;
  t12 = t123 / 4.0;
  t3 = t124 / 4.0;
  t58 = t12 + t3;
  t9 = t24_tmp / 4.0;
  t2 = t101 / 4.0;
  t61 = t9 + t2;
  t15 = t37_tmp / 4.0;
  t64 = t12 - t3;
  t65 = t9 - t2;
  t66 = t53 + t62;
  t68 = t55 + t15;
  t72 = c_out2_tmp * t54_tmp;
  t73 = out2_tmp * t58;
  t74 = t47_tmp * t38_tmp * 2.0;
  t75 = t55 - t15;
  t76_tmp = t45_tmp * t54_tmp;
  t77_tmp = in1[16] * t61;
  t86 = ((((((c_out2_tmp * t65 + t45_tmp * t64) + d_out2_tmp * t39) + t47_tmp *
            t40) + h_out2_tmp * t42) + g_out2_tmp * t46_tmp) + out2_tmp * t68) +
    b_out2_tmp * t66;
  t47 = c_out2_tmp * t61;
  t48 = t45_tmp * t58;
  t49 = out2_tmp * t75;
  t50 = h_out2_tmp * t39;
  t51 = out2_tmp * t64;
  t52 = t45_tmp * t68;
  t122 = b_out2_tmp * t65;
  t123 = e_out2_tmp * t46_tmp;
  t124 = d_out2_tmp * t42;
  t24_tmp = c_out2_tmp * t66 + t47_tmp * t41;
  t97 = (((((t24_tmp + t50) + t51) - t52) - t122) - t123) - t124;
  t100_tmp = ((t47 + t48) + t49) + b_out2_tmp * t54_tmp;
  t100 = (t100_tmp + t47_tmp * t34 * 2.0) + h_out2_tmp * t46_tmp * 2.0;
  t101 = t33 * t33;
  t102 = in1[16] * t101;
  t104 = t34 * t34;
  t105 = in1[16] * t104;
  t107 = c_out2_tmp * t58;
  t108 = t45_tmp * t61;
  t2 = t47_tmp * t42;
  t3 = t45_tmp * t66;
  t9 = h_out2_tmp * t40;
  t12 = d_out2_tmp * t41;
  t15 = out2_tmp * t65;
  t13 = c_out2_tmp * t68 + in1[16] * t64 * t43_tmp;
  t113_tmp_tmp = in1[16] * t39;
  t45 = t113_tmp_tmp * t46_tmp;
  t113 = (((((t13 + t45) + t2) - t3) - t9) - t12) - t15;
  t120_tmp = b_out2_tmp * t75;
  t125 = (((((t13 - t2) + t3) - t9) - t12) + t15) - t45;
  t128_tmp = in1[16] * (t21_tmp - t35_tmp) * t54_tmp;
  t130 = ((t47 - t48) - t49) + in1[16] * (t25_tmp - t37_tmp) * (t53 - t62);
  t131 = (((((t24_tmp - t50) - t51) + t52) - t122) - t123) + t124;
  t136 = t33 * t41 * 2.0;
  t137 = t34 * t42 * 2.0;
  t140 = ((t20 * t61 * 2.0 + t43_tmp * t54_tmp * 2.0) - t24 * t58 * 2.0) -
    t29_tmp * t75 * 2.0;
  t149 = t101 * 2.0;
  t151 = t104 * 2.0;
  t153 = t33 * t39 * 2.0;
  t154 = t34 * t40 * 2.0;
  t157 = t20 * t65 * 2.0;
  t158 = t24 * t64 * 2.0;
  t159 = t34 * t39 * 2.0;
  t160 = t33 * t40 * 2.0;
  t2 = t20 * t54_tmp * 2.0;
  t3 = t24 * t75 * 2.0;
  t163 = ((t2 + t43_tmp * t61 * 2.0) - t3) - t29_tmp * t58 * 2.0;
  t164 = t42 * t38_tmp * 2.0;
  t166_tmp = t41 * t46_tmp * 2.0;
  t167_tmp = t43_tmp * t66 * 2.0;
  t168_tmp = t20 * t64 * 2.0;
  t169_tmp = t24 * t65 * 2.0;
  t170 = t66 * t29_tmp * 2.0;
  t171 = t38_tmp * t41 * 2.0;
  t172_tmp = t42 * t46_tmp * 2.0;
  t173_tmp = t43_tmp * t68 * 2.0;
  t174 = t41 * t38_tmp * 2.0;
  memset(&out3[0], 0, 18U * sizeof(real_T));
  h_out2_tmp = ((((((out2_tmp * t66 + b_out2_tmp * t68) + h_out2_tmp * t41) +
                   f_out2_tmp * t46_tmp) - t47_tmp * t39) - d_out2_tmp * t40) -
                c_out2_tmp * t64) - t45_tmp * t65;
  f_out2_tmp = b_out2_tmp * t58;
  t21_tmp = t47_tmp * t46_tmp * 2.0;
  out3[18] = (in2[11] * (((((t72 + t73) + t74) - t45_tmp * (t55 - t14 * t16 *
    t17 / 4.0)) - d_out2_tmp * t46_tmp * 2.0) - t77_tmp * t43_tmp) + in2[9] *
              (((((d_out2_tmp * t38_tmp * 2.0 + t76_tmp) - t21_tmp) + out2_tmp *
                 t61) - f_out2_tmp) - c_out2_tmp * (t55 - t14 * t16 * t17 / 4.0)))
    + in2[10] * h_out2_tmp;
  out3[19] = (-t97 * in2[10] - t100 * in2[9]) - in2[11] * (((((((t102 + t105) +
    t107) + t108) - in1[16] * (t38_tmp * t38_tmp)) - in1[16] * (t46_tmp *
    t46_tmp)) - t128_tmp) - t120_tmp);
  t50 = t102 - t105;
  out3[20] = (-in2[9] * ((((((t50 - t107) + t108) + t120_tmp) + in1[16] *
    (t38_tmp * t38_tmp)) - in1[16] * (t46_tmp * t46_tmp)) - t128_tmp) - t125 *
              in2[10]) + t130 * in2[11];
  t51 = t29_tmp * t64 * 2.0 + t43_tmp * t65 * 2.0;
  t52 = t38_tmp * t39 * 2.0;
  t24_tmp = t20 * t66 * 2.0;
  t122 = t40 * t46_tmp * 2.0;
  t123 = t24 * t68 * 2.0;
  t124 = t24 * t61 * 2.0 + t43_tmp * t75 * 2.0;
  t101 = t20 * t58 * 2.0;
  t104 = t29_tmp * t54_tmp * 2.0;
  out3[21] = (-in2[10] * ((((((t51 + t136) + t137) - t52) - t24_tmp) - t122) -
    t123) + t140 * in2[9]) - in2[11] * ((((((t124 + t149) - t151) - t101) - t104)
    + t38_tmp * t38_tmp * 2.0) - t46_tmp * t46_tmp * 2.0);
  t35_tmp = t20 * t75 * 2.0 + t29_tmp * t61 * 2.0;
  t47 = (t35_tmp - t58 * t43_tmp * 2.0) - t24 * (t53 - t62) * 2.0;
  t48 = t153 + t154;
  out3[22] = (in2[9] * t47 - in2[10] * ((((((t48 + t171) + t172_tmp) - t168_tmp)
    - t169_tmp) - t29_tmp * t66 * 2.0) - t173_tmp)) - t163 * in2[11];
  t49 = t29_tmp * t68 * 2.0;
  t13 = ((t2 + t3) - t58 * t29_tmp * 2.0) - t61 * t43_tmp * 2.0;
  t45 = t157 - t158;
  t35_tmp = (t35_tmp + t24 * t54_tmp * 2.0) + t43_tmp * t58 * 2.0;
  t12 = t34 * t38_tmp * 4.0;
  t15 = t33 * t46_tmp * 4.0;
  out3[23] = (in2[9] * t13 - in2[10] * ((((((t45 + t159) - t160) + t164) +
    t167_tmp) - t166_tmp) - t49)) - in2[11] * ((t35_tmp - t12) - t15);
  t9 = t76_tmp + t77_tmp * t29_tmp;
  out3[24] = (-t86 * in2[11] + in2[9] * h_out2_tmp) + in2[10] * ((((t9 +
    t113_tmp_tmp * t42 * 2.0) - e_out2_tmp * t41 * 2.0) - in1[16] * t20 * t75) -
    f_out2_tmp);
  out3[25] = (-t97 * in2[9] + t113 * in2[11]) - in2[10] * ((t100_tmp -
    t113_tmp_tmp * t40 * 2.0) - g_out2_tmp * t42 * 2.0);
  out3[26] = (in2[10] * (((((((t107 - t108) - t120_tmp) + t128_tmp) + in1[16] *
    (t39 * t39)) - in1[16] * (t40 * t40)) + in1[16] * (t41 * t41)) - in1[16] *
    (t42 * t42)) - t125 * in2[9]) + t131 * in2[11];
  h_out2_tmp = ((t33 * t42 * 2.0 + t34 * t41 * 2.0) + t38_tmp * t40 * 2.0) + t39
    * t46_tmp * 2.0;
  t3 = t20 * t68 * 2.0;
  t2 = t24 * t66 * 2.0;
  out3[27] = (t140 * in2[10] + in2[11] * ((((h_out2_tmp - t3) - t2) - t65 *
    t29_tmp * 2.0) - t64 * t43_tmp * 2.0)) - in2[9] * ((((((t51 - t136) - t137)
    + t52) - t24_tmp) + t122) - t123);
  t51 = t38_tmp * t42 * 2.0;
  t52 = t157 + t158;
  out3[28] = (in2[10] * t47 + in2[11] * ((((((t52 + t159) + t160) - t51) -
    t166_tmp) - t49) - t167_tmp)) + in2[9] * ((((((t48 + t168_tmp) + t169_tmp) +
    t170) + t172_tmp) + t174) + t68 * t43_tmp * 2.0);
  t24_tmp = t153 - t154;
  out3[29] = (in2[10] * t13 - in2[9] * ((((((t45 - t159) + t160) + t166_tmp) +
    t167_tmp) - t51) - t49)) + in2[11] * ((((((t24_tmp - t168_tmp) + t169_tmp) -
    t170) + t171) - t172_tmp) + t173_tmp);
  out3[30] = (in2[9] * (((((t72 + t73) + t74) - in1[16] * t24 * t75) - in1[16] *
    t34 * (t25 - t37) * 2.0) - in1[16] * t61 * (t25_tmp - t37_tmp)) + in2[11] *
              ((((t9 - t21_tmp) - in1[16] * t20 * t75) - f_out2_tmp) + in1[16] *
               t34 * (t21 - t36) * 2.0)) - t86 * in2[10];
  out3[31] = (-t100 * in2[11] + t113 * in2[10]) - in2[9] * (((((((t102 + t105) +
    t107) + t108) - in1[16] * (t38_tmp * t38_tmp)) - in1[16] * (t46_tmp *
    t46_tmp)) - in1[16] * t29_tmp * t54_tmp) - in1[16] * t43_tmp * t75);
  out3[32] = (t130 * in2[9] + t131 * in2[10]) + in2[11] * ((((((t50 + t107) -
    t108) - t120_tmp) + t128_tmp) + in1[16] * (t38_tmp * t38_tmp)) - in1[16] *
    (t46_tmp * t46_tmp));
  out3[33] = (-in2[10] * ((((h_out2_tmp + t3) + t2) + t29_tmp * t65 * 2.0) +
    t43_tmp * t64 * 2.0) + t140 * in2[11]) - in2[9] * ((((((t124 - t149) + t151)
    - t101) - t104) - t38_tmp * t38_tmp * 2.0) + t46_tmp * t46_tmp * 2.0);
  out3[34] = (in2[11] * t47 + in2[10] * ((((((t52 - t159) - t160) + t164) +
    t166_tmp) - t49) - t167_tmp)) - t163 * in2[9];
  out3[35] = (in2[11] * t13 - in2[10] * ((((((t24_tmp + t168_tmp) - t169_tmp) +
    t170) - t173_tmp) + t174) - t172_tmp)) - in2[9] * ((t35_tmp + t12) + t15);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF2.c) */
