/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF5.c
 *
 * Code generation for function 'massF5'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF5.h"
#include "error.h"
#include "EOM_data.h"

/* Variable Definitions */
static emlrtRSInfo yc_emlrtRSI = { 20, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo ad_emlrtRSI = { 21, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo bd_emlrtRSI = { 29, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo cd_emlrtRSI = { 30, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo dd_emlrtRSI = { 31, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo ed_emlrtRSI = { 33, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo fd_emlrtRSI = { 34, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

static emlrtRSInfo gd_emlrtRSI = { 46, /* lineNo */
  "massF5",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/code/massF5.m"/* pathName */
};

/* Function Definitions */
void massF5(const emlrtStack *sp, const real_T in1[34], const real_T in2[48],
            real_T out1[36], real_T out2[144], real_T out3[144], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t15;
  real_T t53;
  real_T t17;
  real_T t54;
  real_T t18;
  real_T t21;
  real_T t22;
  real_T out2_tmp;
  real_T t52;
  real_T b_out2_tmp;
  real_T t23;
  real_T t24_tmp;
  real_T t26;
  real_T t27;
  real_T t30;
  real_T t31_tmp;
  real_T t33;
  real_T t35;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t40;
  real_T t41;
  real_T out3_tmp;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* MASSF5 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF5(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     06-Jan-2019 19:05:54 */
  st.site = &yc_emlrtRSI;
  t2 = in1[16] * in1[16];
  st.site = &ad_emlrtRSI;
  t3 = in1[17] * in1[17];
  t2 = in1[15] * (t2 + t3 * 3.0) / 12.0 + in1[15] * t2 / 4.0;
  out1[0] = in1[15];
  out1[1] = 0.0;
  out1[2] = 0.0;
  out1[3] = 0.0;
  out1[4] = 0.0;
  out1[5] = 0.0;
  out1[6] = 0.0;
  out1[7] = in1[15];
  out1[8] = 0.0;
  out1[9] = 0.0;
  out1[10] = 0.0;
  out1[11] = 0.0;
  out1[12] = 0.0;
  out1[13] = 0.0;
  out1[14] = in1[15];
  out1[15] = 0.0;
  out1[16] = 0.0;
  out1[17] = 0.0;
  out1[18] = 0.0;
  out1[19] = 0.0;
  out1[20] = 0.0;
  out1[21] = t2;
  out1[22] = 0.0;
  out1[23] = 0.0;
  out1[24] = 0.0;
  out1[25] = 0.0;
  out1[26] = 0.0;
  out1[27] = 0.0;
  out1[28] = t2;
  out1[29] = 0.0;
  out1[30] = 0.0;
  out1[31] = 0.0;
  out1[32] = 0.0;
  out1[33] = 0.0;
  out1[34] = 0.0;
  out1[35] = in1[15] * t3 / 2.0;
  st.site = &bd_emlrtRSI;
  t9 = in2[21] * in2[21];
  st.site = &cd_emlrtRSI;
  t10 = in2[22] * in2[22];
  st.site = &dd_emlrtRSI;
  t11 = in2[23] * in2[23];
  t12 = ((-t9 - t10) - t11) + 1.0;
  st.site = &ed_emlrtRSI;
  if (t12 < 0.0) {
    b_st.site = &lb_emlrtRSI;
    error(&b_st);
  }

  t2 = muDoubleScalarSqrt(t12);
  t13 = 1.0 / t2;
  st.site = &fd_emlrtRSI;
  t15 = in1[16] * t2;
  t53 = in1[16] * in2[23];
  t17 = in2[23] * 2.0;
  t54 = in2[21] * in2[22];
  t18 = t54 * t13 * 2.0;
  t2 *= 2.0;
  t3 = in2[21] * in2[23] * t13 * 2.0;
  t21 = in2[21] * 2.0;
  t22 = in2[22] * in2[23] * t13 * 2.0;
  memset(&out2[0], 0, 108U * sizeof(real_T));
  out2[108] = 1.0;
  out2[109] = 0.0;
  out2[110] = 0.0;
  out2[111] = 0.0;
  out2[112] = 0.0;
  out2[113] = 0.0;
  out2[114] = 0.0;
  out2[115] = 1.0;
  out2[116] = 0.0;
  out2[117] = 0.0;
  out2[118] = 0.0;
  out2[119] = 0.0;
  out2[120] = 0.0;
  out2[121] = 0.0;
  out2[122] = 1.0;
  out2[123] = 0.0;
  out2[124] = 0.0;
  out2[125] = 0.0;
  out2_tmp = in1[16] * in2[21];
  t52 = out2_tmp * in2[22];
  b_out2_tmp = t52 * t13;
  out2[126] = t53 - b_out2_tmp;
  out2[127] = -t15 + in1[16] * t9 * t13;
  out2[128] = out2_tmp * -2.0;
  out2[129] = t2 + t9 * t13 * 2.0;
  out2[130] = -t17 + t18;
  out2[131] = in2[22] * 2.0 + t3;
  out2[132] = t15 - in1[16] * t10 * t13;
  out2[133] = t53 + b_out2_tmp;
  b_out2_tmp = in1[16] * in2[22];
  out2[134] = b_out2_tmp * -2.0;
  out2[135] = t17 + t18;
  out2[136] = t2 + t10 * t13 * 2.0;
  out2[137] = -t21 + t22;
  out2[138] = out2_tmp - b_out2_tmp * in2[23] * t13;
  out2[139] = b_out2_tmp + out2_tmp * in2[23] * t13;
  out2[140] = 0.0;
  out2[141] = in2[22] * -2.0 + t3;
  out2[142] = t21 + t22;
  out2[143] = t2 + t11 * t13 * 2.0;
  st.site = &gd_emlrtRSI;
  t23 = 1.0 / muDoubleScalarPower(t12, 1.5);
  t24_tmp = out2_tmp * t13;
  t26 = t24_tmp + out2_tmp * t10 * t23;
  t2 = t52 * in2[23] * t23;
  t27 = in1[16] - t2;
  t3 = t53 * t13;
  t30 = t3 + t53 * t10 * t23;
  t31_tmp = b_out2_tmp * t13;
  t33 = t31_tmp + b_out2_tmp * t9 * t23;
  t35 = in1[16] + t2;
  t37 = t3 + t53 * t9 * t23;
  t38 = in2[22] * t13 * 2.0;
  t39 = in2[22] * t9 * t23 * 2.0;
  t40 = in2[21] * t13 * 2.0;
  t41 = t54 * in2[23] * t23 * 2.0;
  t2 = in2[23] * t13 * 2.0;
  t3 = in2[23] * t9 * t23 * 2.0;
  t21 = t38 + t39;
  t22 = in2[21] * t10 * t23 * 2.0;
  t12 = t40 + t22;
  t15 = in2[23] * t10 * t23 * 2.0;
  t17 = t2 + t3;
  t18 = in2[21] * t11 * t23 * 2.0;
  t52 = t2 + t15;
  t53 = in2[22] * t11 * t23 * 2.0;
  t54 = t40 + t18;
  t13 = t38 + t53;
  memset(&out3[0], 0, 126U * sizeof(real_T));
  out3_tmp = t33 * in2[45];
  out3[126] = (-t26 * in2[46] + t27 * in2[47]) - out3_tmp;
  out3[127] = (in2[45] * (t24_tmp * 3.0 + out2_tmp * t9 * t23) + t33 * in2[46])
    + t37 * in2[47];
  out3[128] = in1[16] * in2[45] * -2.0;
  out3[129] = (t21 * in2[46] + t17 * in2[47]) + in2[45] * (t40 + in2[21] * t9 *
    t23 * 2.0);
  out3[130] = (t21 * in2[45] + (t41 + 2.0) * in2[47]) - in2[46] * (t40 - t22);
  out3[131] = ((t41 - 2.0) * in2[46] + t17 * in2[45]) - in2[47] * (t40 - t18);
  out3[132] = (-in2[46] * (t31_tmp * 3.0 + b_out2_tmp * t10 * t23) - t26 * in2
               [45]) - t30 * in2[47];
  out3[133] = (t26 * in2[46] + out3_tmp) + t35 * in2[47];
  out3[134] = in1[16] * in2[46] * -2.0;
  out3[135] = (t12 * in2[46] + (t41 - 2.0) * in2[47]) - in2[45] * (t38 - t39);
  out3[136] = (t12 * in2[45] + t52 * in2[47]) + in2[46] * (t38 + in2[22] * t10 *
    t23 * 2.0);
  out3[137] = ((t41 + 2.0) * in2[45] + t52 * in2[46]) - in2[47] * (t38 - t53);
  out3[138] = (t27 * in2[45] - t30 * in2[46]) - in2[47] * (t31_tmp + b_out2_tmp *
    t11 * t23);
  out3[139] = (t35 * in2[46] + t37 * in2[45]) + in2[47] * (t24_tmp + out2_tmp *
    t11 * t23);
  out3[140] = 0.0;
  out3[141] = ((t41 + 2.0) * in2[46] + t54 * in2[47]) - in2[45] * (t2 - t3);
  out3[142] = ((t41 - 2.0) * in2[45] + t13 * in2[47]) - in2[46] * (t2 - t15);
  out3[143] = (t54 * in2[45] + t13 * in2[46]) + in2[47] * (t2 + in2[23] * t11 *
    t23 * 2.0);
  out4[0] = in1[12];
  out4[1] = in1[13];
  out4[2] = in1[14];
  out4[3] = 0.0;
  out4[4] = 0.0;
  out4[5] = 0.0;
}

/* End of code generation (massF5.c) */
