/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * rjtipF.c
 *
 * Code generation for function 'rjtipF'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "rjtipF.h"

/* Function Definitions */
void rjtipF(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
            real_T s, real_T r_jtip[12])
{
  real_T t2_tmp;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t14;
  real_T t17;
  (void)sp;
  (void)s;

  /* RJTIPF */
  /*     R_JTIP = RJTIPF(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 21:11:28 */
  t2_tmp = in1[4] + in2[2];
  t3 = in2[5] / 2.0;
  t4 = in2[3] / 2.0;
  t5 = in2[4] / 2.0;
  t6 = muDoubleScalarSin(t4);
  t7 = muDoubleScalarSin(t5);
  t8 = muDoubleScalarSin(t3);
  t9 = muDoubleScalarCos(t4);
  t10 = muDoubleScalarCos(t5);
  t5 = muDoubleScalarCos(t3);
  t4 = t6 * t7;
  t14 = t8 * t9 * t10 + t4 * t5;
  t17 = t6 * t10 * t5 + t7 * t8 * t9;
  t3 = t4 * t8 - t9 * t10 * t5;
  t4 = t6 * t8 * t10 - t7 * t9 * t5;
  r_jtip[0] = in2[0];
  r_jtip[1] = in2[0];
  r_jtip[2] = in2[1];
  r_jtip[3] = in2[1];
  r_jtip[4] = t2_tmp;
  r_jtip[5] = t2_tmp;
  r_jtip[6] = in2[0];
  t5 = in1[16] * t14;
  r_jtip[7] = (in2[0] - t5 * t3 * 2.0) - in1[16] * t17 * t4 * 2.0;
  r_jtip[8] = in2[1];
  r_jtip[9] = (in2[1] + t5 * t17 * 2.0) - in1[16] * t3 * t4 * 2.0;
  r_jtip[10] = t2_tmp;
  r_jtip[11] = (((t2_tmp - in1[16] * (t14 * t14)) + in1[16] * (t17 * t17)) +
                in1[16] * (t3 * t3)) - in1[16] * (t4 * t4);
}

/* End of code generation (rjtipF.c) */
