function r_jtip = rjtipF(in1,in2,s)
%RJTIPF
%    R_JTIP = RJTIPF(IN1,IN2,S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jan-2019 17:12:22

l_f_sym = in1(:,17);
l_s_sym = in1(:,5);
q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
q7 = in2(:,7);
q8 = in2(:,8);
q9 = in2(:,9);
q10 = in2(:,10);
q11 = in2(:,11);
q12 = in2(:,12);
q13 = in2(:,13);
q14 = in2(:,14);
q15 = in2(:,15);
q16 = in2(:,16);
q17 = in2(:,17);
q18 = in2(:,18);
t2 = l_s_sym.^2;
t3 = s.^2;
t4 = t2.^2;
t5 = t3.^2;
t6 = q1.*t2;
t7 = l_s_sym.*q2.*t2;
t8 = q3.*t4;
t15 = l_s_sym.*q10;
t16 = q11.*t2;
t17 = l_s_sym.*q12.*t2;
t9 = t15+t16+t17;
t10 = l_s_sym.*q13;
t11 = q14.*t2;
t12 = l_s_sym.*q15.*t2;
t13 = t10+t11+t12;
t18 = l_s_sym.*q16;
t19 = q17.*t2;
t20 = l_s_sym.*q18.*t2;
t14 = t18+t19+t20;
t21 = q4.*t2;
t22 = l_s_sym.*q5.*t2;
t23 = q6.*t4;
t24 = t9.^2;
t25 = t13.^2;
t26 = t14.^2;
t27 = -t24-t25-t26+1.0;
t28 = sqrt(t27);
t29 = q7.*t2;
t30 = l_s_sym.*q8.*t2;
t31 = q9.*t4;
r_jtip = reshape([q1.*t2.*t3+q3.*t4.*t5+l_s_sym.*q2.*s.*t2.*t3,t6+t7+t8,q4.*t2.*t3+q6.*t4.*t5+l_s_sym.*q5.*s.*t2.*t3,t21+t22+t23,l_s_sym.*s+q7.*t2.*t3+q9.*t4.*t5+l_s_sym.*q8.*s.*t2.*t3,l_s_sym+t29+t30+t31,NaN,t6+t7+t8+l_f_sym.*t9.*t14.*2.0+l_f_sym.*t13.*t28.*2.0,NaN,t21+t22+t23+l_f_sym.*t13.*t14.*2.0-l_f_sym.*t9.*t28.*2.0,NaN,l_s_sym+t29+t30+t31-l_f_sym.*t24-l_f_sym.*t25+l_f_sym.*t26-l_f_sym.*(t24+t25+t26-1.0)],[2,6]);
