function out1 = sprdmpDir18(in1,in2,s,ds,t_sym)
%SPRDMPDIR18
%    OUT1 = SPRDMPDIR18(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:34:30

out1 = 1.0;
