function out1 = sprdmpTtu1(in1,in2,s,ds,t_sym)
%SPRDMPTTU1
%    OUT1 = SPRDMPTTU1(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:34:38

out1 = zeros(0,0);
