function out1 = sprdmpKx16(in1,in2,s,ds,t_sym)
%SPRDMPKX16
%    OUT1 = SPRDMPKX16(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:23:29

out1 = 0.0;
