function out1 = sprdmpVd13(in1,in2,s,ds,t_sym)
%SPRDMPVD13
%    OUT1 = SPRDMPVD13(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:23:48

out1 = 0.0;
