function out1 = sprdmpTt2(in1,in2,s,ds,t_sym)
%SPRDMPTT2
%    OUT1 = SPRDMPTT2(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:11:30

out1 = [0.0;1.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
