function out1 = cnstT2(in1,in2,s,ds,t_sym)
%CNSTT2
%    OUT1 = CNSTT2(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:39:33

dl_ = in1(:,19);
l_s1_ = in1(:,16);
l_s2_ = in1(:,17);
t2 = dl_+l_s1_;
t3 = -l_s2_;
t4 = dl_.*2.0e+2;
t5 = l_s1_.*2.0e+2;
t6 = l_s2_.*2.0e+2;
t7 = -t4;
t8 = -t5;
t9 = t2+t3;
t10 = (l_s2_-t2).^2;
t11 = t2.*-2.0e+2+t6;
t12 = exp(t11);
t13 = t12+1.0;
t14 = 1.0./t13;
t15 = t10.*t14;
out1 = [0.0,0.0,0.0,0.0,t15-t2.^2,t15.*(l_s2_.*2.0+t2)-t2.^3,-t15,t14.*(l_s2_-t2).^3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
