function out1 = cnstIn3(in1,in2,s,ds,t_sym)
%CNSTIN3
%    OUT1 = CNSTIN3(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:39:35

D_ = in1(:,33);
P_ = in1(:,31);
dl_ = in1(:,19);
haptic_z_ = in1(:,30);
l_s1_ = in1(:,16);
l_s2_ = in1(:,17);
q9 = in2(9,:);
q10 = in2(10,:);
q11 = in2(11,:);
q12 = in2(12,:);
u9 = in2(28,:);
u10 = in2(29,:);
u11 = in2(30,:);
u12 = in2(31,:);
t2 = dl_+l_s1_;
t3 = -l_s2_;
t6 = dl_.*2.0e+2;
t7 = l_s1_.*2.0e+2;
t8 = l_s2_.*2.0e+2;
t4 = t2.^2;
t5 = t2.^3;
t9 = -t6;
t10 = -t7;
t11 = t2+t3;
t12 = (l_s2_-t2).^2;
t13 = t2.*-2.0e+2+t8;
t14 = exp(t13);
t15 = t14+1.0;
t16 = 1.0./t15;
out1 = -haptic_z_+D_.*(u10.*(t5-t12.*t16.*(l_s2_.*2.0+t2))+u9.*(t4-t12.*t16)-t16.*u12.*(l_s2_-t2).^3+t12.*t16.*u11)+P_.*(t2+q9.*t4+q10.*t5-t12.*t16.*(q9-q11+l_s2_.*q10.*2.0+l_s2_.*q12+q10.*t2-q12.*t2));
