function out1 = sprdmpIn14(in1,in2,s,ds,t_sym)
%SPRDMPIN14
%    OUT1 = SPRDMPIN14(IN1,IN2,S,DS,T_SYM)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-May-2021 20:34:33

out1 = 0.0;
