/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF6.c
 *
 * Code generation for function 'sprdmpF6'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "sprdmpF6.h"

/* Function Definitions */
void sprdmpF6(const emlrtStack *sp, const real_T in1[34], const real_T in2[12],
              real_T s, real_T out1[6], real_T *out2, real_T *out3, real_T *out4,
              real_T *out5, real_T out6[6], real_T out7[6], real_T *out8)
{
  int32_T i;
  static const int8_T iv0[6] = { 0, 0, 0, 0, 0, 1 };

  real_T a;
  real_T b_a;
  real_T c_a;
  real_T t19;
  real_T t19_tmp;
  real_T t7;
  real_T t8;
  (void)sp;
  (void)s;
  for (i = 0; i < 6; i++) {
    out1[i] = iv0[i];
  }

  /* SPRDMPF6 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF6(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     05-Jan-2019 22:47:10 */
  a = in1[2] * in1[2];
  b_a = in1[3] * in1[3];
  c_a = in1[18] * in1[18];
  t19 = muDoubleScalarCos(in1[20]);
  t19_tmp = in1[33] * in1[33];
  t19 = t19_tmp * (t19 * t19);
  t7 = 1.0 / in1[4];
  t8 = 1.0 / in1[33];
  t19 = 1.0 / t19_tmp * (a * a - b_a * b_a) + c_a * c_a * (1.0 /
    muDoubleScalarPower(muDoubleScalarSin(in1[20]), 4.0)) * ((t19 - 1.0) * (t19
    - 1.0)) * 6.0;
  *out2 = in1[1] * in2[5] * t7 * t8 * t19 * 3.1415926535897931 / 6.0;
  *out3 = -in1[10] * in2[11];
  *out4 = 0.0;
  *out5 = in2[5];
  out6[0] = 0.0;
  out6[1] = 0.0;
  out6[2] = 0.0;
  out6[3] = 0.0;
  out6[4] = 0.0;
  out6[5] = in1[1] * t7 * t8 * t19 * 3.1415926535897931 * -0.16666666666666666;
  out7[0] = 0.0;
  out7[1] = 0.0;
  out7[2] = 0.0;
  out7[3] = 0.0;
  out7[4] = 0.0;
  out7[5] = -in1[10];
  *out8 = 1.0;
}

/* End of code generation (sprdmpF6.c) */
