/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF9.c
 *
 * Code generation for function 'cnstF9'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF9.h"

/* Function Definitions */
void cnstF9(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t7;
  real_T t10;
  real_T t13;
  real_T t18;
  real_T t20;
  real_T t21_tmp;
  real_T b_t21_tmp;
  real_T t21;
  real_T t24;
  real_T t26;
  real_T t36;
  real_T t27_tmp;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t37;
  real_T t50;
  real_T t39_tmp;
  real_T b_t39_tmp;
  real_T t39;
  real_T t40;
  real_T t42;
  real_T t43_tmp;
  real_T t43;

  /* CNSTF9 */
  /*     [OUT1,OUT2,OUT3] = CNSTF9(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:06 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t4 = muDoubleScalarSin(t2);
  t7 = t3 * 0.038 - t4 * 0.03;
  t10 = t3 * 0.03 + t4 * 0.038;
  t13 = t3 * 0.015 + t4 * 0.019;
  t2 = t3 * 0.019 - t4 * 0.015;
  t18 = t3 * t13;
  t20 = t4 * t2;
  t21_tmp = t3 * t10;
  b_t21_tmp = t4 * t7;
  t21 = ((t21_tmp / 2.0 + t18) + b_t21_tmp / 2.0) + t20;
  t24 = (in2[86] + t21_tmp) + b_t21_tmp;
  t26 = t3 * t2;
  t36 = t4 * t13;
  t27_tmp = t4 * t10;
  t10 = t3 * t7;
  t2 = ((t10 / 2.0 + t26) - t27_tmp / 2.0) - t36;
  t13 = (in2[84] + t27_tmp) - t10;
  t31 = t3 * t3;
  t32 = t4 * t4;
  t33 = t31 - t32;
  t37 = t4 * t2;
  t50 = t3 * t21;
  t39_tmp = t3 * t24;
  b_t39_tmp = t4 * t13;
  t39 = ((t39_tmp / 2.0 + t37) + b_t39_tmp / 2.0) - t50;
  t40 = t3 * t2;
  t42 = t4 * t21;
  t43_tmp = t4 * t24;
  t24 = t3 * t13;
  t43 = ((t40 + t24 / 2.0) + t42) - t43_tmp / 2.0;
  t2 = t3 * 0.0095 - t4 * 0.0075;
  t13 = t3 * 0.0075 + t4 * 0.0095;
  t21 = ((((t26 - t36) + t10 / 4.0) + t3 * t2) - t27_tmp / 4.0) - t4 * t13;
  t2 = ((((t18 + t20) + t21_tmp / 4.0) + t3 * t13) + b_t21_tmp / 4.0) + t4 * t2;
  t13 = t39_tmp + b_t39_tmp;
  t10 = t43_tmp - t24;
  memset(&out1[0], 0, 84U * sizeof(real_T));
  t7 = t3 * t4;
  out1[84] = t7 * 2.0;
  out1[85] = 0.0;
  out1[86] = t33;
  out1[87] = 0.0;
  out1[88] = 0.0;
  out1[89] = 0.0;
  out1[90] = ((-t4 * t39 + t3 * t43) - t4 * t13 / 2.0) - t3 * t10 / 2.0;
  memset(&out2[0], 0, 84U * sizeof(real_T));
  out2[84] = t33 * in2[193];
  out2[85] = 0.0;
  out2[86] = t7 * in2[193] * -2.0;
  out2[87] = 0.0;
  out2[88] = 0.0;
  out2[89] = 0.0;
  out2[90] = ((-in2[193] * (((((t4 * (((((t40 + t42) - t43_tmp / 4.0) + t24 /
    4.0) - t3 * t21) - t4 * t2) + t3 * t39) + t4 * t43) + t3 * t13 / 4.0) - t4 *
    t10 / 4.0) + t3 * (((((t37 - t50) + t39_tmp / 4.0) + b_t39_tmp / 4.0) - t4 *
                        t21) + t3 * t2)) + t31 * in2[187]) - t32 * in2[187]) -
    t7 * in2[189] * 2.0;
  *out3 = 0.0;
}

/* End of code generation (cnstF9.c) */
