/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF3.c
 *
 * Code generation for function 'cnstF3'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "cnstF3.h"

/* Function Definitions */
void cnstF3(const real_T in2[206], real_T out1[91], real_T out2[91], real_T
            *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t7;
  real_T t10;
  real_T t13;
  real_T t17_tmp;
  real_T t17;
  real_T t18;
  real_T t34_tmp;
  real_T t34;
  real_T t35;
  real_T t19;
  real_T t21;
  real_T t23;
  real_T t25;
  real_T t26_tmp;
  real_T t26;
  real_T t31;
  real_T t32;
  real_T t33;
  real_T t37_tmp;
  real_T t38_tmp;
  real_T t39;
  real_T t41;
  real_T t42_tmp;
  real_T b_t42_tmp;
  real_T t42;

  /* CNSTF3 */
  /*     [OUT1,OUT2,OUT3] = CNSTF3(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:36:01 */
  t2 = in2[90] / 2.0;
  t3 = muDoubleScalarCos(t2);
  t4 = muDoubleScalarSin(t2);
  t7 = t3 * 0.038 + t4 * 0.03;
  t10 = t3 * 0.03 - t4 * 0.038;
  t13 = t3 * 0.015 - t4 * 0.019;
  t2 = t3 * 0.019 + t4 * 0.015;
  t17_tmp = t4 * t7;
  t17 = t17_tmp / 2.0;
  t18 = t4 * t2;
  t34_tmp = t3 * t10;
  t34 = t34_tmp / 2.0;
  t35 = t3 * t13;
  t19 = ((t17 + t18) - t34) - t35;
  t21 = (in2[74] + t34_tmp) - t17_tmp;
  t23 = t3 * t2;
  t25 = t4 * t13;
  t26_tmp = t3 * t7;
  t7 = t4 * t10;
  t26 = ((t26_tmp / 2.0 + t23) + t7 / 2.0) + t25;
  t2 = (in2[72] + t26_tmp) + t7;
  t31 = t3 * t3;
  t32 = t4 * t4;
  t33 = t31 - t32;
  t37_tmp = t3 * t21;
  t38_tmp = t4 * t2;
  t39 = t3 * t26;
  t41 = t4 * t19;
  t42_tmp = t4 * t21;
  b_t42_tmp = t3 * t2;
  t42 = ((t39 + t42_tmp / 2.0) + t41) - b_t42_tmp / 2.0;
  t2 = t3 * 0.0095 + t4 * 0.0075;
  t13 = t3 * 0.0075 - t4 * 0.0095;
  t25 = ((((t23 + t25) + t26_tmp / 4.0) + t3 * t2) + t7 / 4.0) + t4 * t13;
  t7 = ((((t18 - t35) + t17_tmp / 4.0) + t4 * t2) - t34_tmp / 4.0) - t3 * t13;
  t10 = t37_tmp + t38_tmp;
  t21 = t42_tmp - b_t42_tmp;
  memset(&out1[0], 0, 72U * sizeof(real_T));
  t26_tmp = t3 * t4;
  out1[72] = t26_tmp * 2.0;
  out1[73] = 0.0;
  out1[74] = t33;
  memset(&out1[75], 0, 15U * sizeof(real_T));
  t13 = t4 * t26;
  t2 = ((t3 * t19 + t37_tmp / 2.0) + t38_tmp / 2.0) - t13;
  out1[90] = ((-t3 * t42 - t4 * t10 / 2.0) - t3 * t21 / 2.0) - t4 * t2;
  memset(&out2[0], 0, 72U * sizeof(real_T));
  out2[72] = t33 * in2[193];
  out2[73] = 0.0;
  out2[74] = t26_tmp * in2[193] * -2.0;
  memset(&out2[75], 0, 15U * sizeof(real_T));
  out2[90] = ((t31 * in2[175] - t32 * in2[175]) + in2[193] * (((((t4 * (((((t39
    + t41) + t42_tmp / 4.0) - b_t42_tmp / 4.0) - t3 * t25) - t4 * t7) + t4 * t42)
    - t3 * t10 / 4.0) + t4 * t21 / 4.0) - t3 * (((((t37_tmp / 4.0 - t13) +
    t38_tmp / 4.0) + t4 * t25) - t3 * t7) + t3 * (((t17 + t18) - t34) - t35))) -
    t3 * t2)) - t26_tmp * in2[177] * 2.0;
  *out3 = 0.0;
}

/* End of code generation (cnstF3.c) */
