/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF1.c
 *
 * Code generation for function 'massF1'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "massF1.h"
#include "EOM_data.h"

/* Function Definitions */
void massF1(const real_T in2[206], real_T out2[546], real_T out3[546], real_T
            out4[6])
{
  int32_T i;
  real_T t3;
  real_T t2;
  real_T t5;
  real_T t6;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF1 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF1(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:09:24 */
  t3 = in2[90] / 2.0;
  t2 = muDoubleScalarCos(t3);
  t3 = muDoubleScalarSin(t3);
  t5 = t2 * t2;
  t6 = t3 * t3;
  memset(&out2[0], 0, 540U * sizeof(real_T));
  out2[540] = t5 * -0.135 + t6 * 0.135;
  out2[541] = 0.0;
  t3 *= t2;
  out2[542] = t3 * 0.27;
  out2[543] = 0.0;
  out2[544] = t5 + t6;
  out2[545] = 0.0;
  memset(&out3[0], 0, 540U * sizeof(real_T));
  out3[540] = t3 * in2[193] * 0.27;
  out3[541] = 0.0;
  out3[542] = t5 * in2[193] * 0.135 - t6 * in2[193] * 0.135;
  out3[543] = 0.0;
  out3[544] = 0.0;
  out3[545] = 0.0;
}

/* End of code generation (massF1.c) */
