/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF99.c
 *
 * Code generation for function 'sprdmpF99'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM.h"
#include "sprdmpF99.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo wq_emlrtRSI = { 41, /* lineNo */
  "sprdmpF99",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF99.m"/* pathName */
};

static emlrtRSInfo xq_emlrtRSI = { 47, /* lineNo */
  "sprdmpF99",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF99.m"/* pathName */
};

static emlrtRSInfo cr_emlrtRSI = { 77, /* lineNo */
  "sprdmpF99",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF99.m"/* pathName */
};

static emlrtRSInfo dr_emlrtRSI = { 89, /* lineNo */
  "sprdmpF99",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF99.m"/* pathName */
};

static emlrtRSInfo or_emlrtRSI = { 289,/* lineNo */
  "sprdmpF99",                         /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF99.m"/* pathName */
};

/* Function Definitions */
void sprdmpF99(const emlrtStack *sp, const real_T in1[6], const real_T in2[206],
               real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t169;
  real_T t227;
  real_T t15_tmp;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t229;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t197;
  real_T t25;
  real_T t181;
  real_T t223;
  real_T t196;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t44_tmp;
  real_T t168;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t200;
  real_T t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t220;
  real_T t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t58;
  real_T t59;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63_tmp;
  real_T t69;
  real_T a;
  real_T t71;
  real_T a_tmp;
  real_T b_a_tmp;
  real_T b_a;
  real_T t73;
  real_T t77;
  real_T t81;
  real_T t82;
  real_T t83;
  real_T t84;
  real_T t85;
  real_T t86;
  real_T t97_tmp;
  real_T t97;
  real_T t101;
  real_T t106;
  real_T t107;
  real_T t108;
  real_T t112;
  real_T t113;
  real_T t114;
  real_T t115;
  real_T t116;
  real_T t117;
  real_T t118_tmp;
  real_T b_t118_tmp;
  real_T t118;
  real_T t127_tmp;
  real_T t127;
  real_T t130;
  real_T t140;
  real_T t144;
  real_T t145;
  real_T t146;
  real_T t147;
  real_T t160;
  real_T t163;
  real_T t172;
  real_T t174;
  real_T t177;
  real_T t180;
  real_T t183;
  real_T t187;
  real_T t191;
  real_T t199;
  real_T t203;
  real_T t204;
  real_T t206;
  real_T t209;
  real_T t215;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF99 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF99(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     09-Jan-2019 03:14:43 */
  t2 = in2[22] * in2[22];
  t3 = in2[23] * in2[23];
  t4 = in2[21] * in2[21];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &wq_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[23] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[21] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &xq_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t169 = in2[19] - in2[25];
  t227 = in2[20] - in2[26];
  t15_tmp = in2[18] - in2[24];
  t17_tmp = in2[21] * t12;
  t17 = (-in2[20] + in2[26]) + t17_tmp * t169;
  t19 = t169 + t17_tmp * t227;
  t20 = t6 * t169;
  t229 = in2[21] * t227;
  t22_tmp = in2[21] * t169;
  t23_tmp = t6 * t227;
  t197 = in2[22] * t15_tmp;
  t25 = t6 * t15_tmp;
  t181 = in2[23] * t169;
  t223 = in2[22] * t227;
  t196 = t25 + t181;
  t27 = t196 - t223;
  t29_tmp = in2[22] * t12;
  t29 = (-in2[18] + in2[24]) + t29_tmp * t227;
  t31 = t227 + t29_tmp * t15_tmp;
  t44_tmp = in2[23] * t15_tmp;
  t168 = t20 + t229;
  t32 = t168 - t44_tmp;
  t34 = (-t22_tmp + t23_tmp) + t197;
  t35 = in2[29] * 2.0;
  t36 = in2[21] - in2[27];
  t5 = ((-(in2[27] * in2[27]) - in2[28] * in2[28]) - in2[29] * in2[29]) + 1.0;
  t41 = t5;
  st.site = &cr_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[22] - in2[28];
  t43 = in2[23] - in2[29];
  t46_tmp = in2[23] * t12;
  t46 = t15_tmp + t46_tmp * t169;
  t48 = (-in2[19] + in2[25]) + t46_tmp * t15_tmp;
  t49 = in2[27] * 2.0;
  t50_tmp = in2[22] * t6 * 2.0;
  t200 = in2[21] * in2[22];
  t51_tmp = t200 * 2.0;
  t52_tmp = in2[21] * in2[23];
  t52 = t52_tmp * 2.0;
  t220 = in2[22] * in2[23];
  t53_tmp = t220 * 2.0;
  st.site = &dr_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[22] * 2.0;
  t5 = in1[4] / 2.0;
  t58 = muDoubleScalarCos(t5);
  t59 = muDoubleScalarSin(t5);
  t60_tmp = in2[21] * t15_tmp;
  t61_tmp = in2[22] * t169;
  t62_tmp = in2[23] * t227;
  t63_tmp = (t60_tmp + t61_tmp) + t62_tmp;
  t5 = t58 * 0.333 + t59 * 0.036;
  t69 = t58 * 0.036 - t59 * 0.333;
  a = ((t58 * t5 + t59 * t69) - t58 * t58 * 0.333) + t59 * t59 * 0.333;
  t71 = t59 * t5;
  a_tmp = t58 * t59 * 0.666;
  b_a_tmp = t58 * t69;
  b_a = (-t71 + b_a_tmp) + a_tmp;
  t73 = t6 - t41;
  t59 = t220 * t12;
  t77 = (((((t23_tmp + t197) + t6 * t31) + t29_tmp * t27) + t59 * t169) - in2[22]
         * t29) - t22_tmp * 2.0;
  t81 = (((((-t20 + t44_tmp) + t6 * t48) + in2[23] * t46) + t46_tmp * t27) -
         t229 * 2.0) - t59 * t227;
  t82 = (t8 + t11) - 1.0;
  t83 = t7 + t51_tmp;
  t84 = t50_tmp - t52;
  t85 = in2[23] * t17;
  t86 = t17_tmp * t27;
  t97_tmp = in2[22] * t19;
  t97 = ((t63_tmp - t85) - t86) + t97_tmp;
  t101 = muDoubleScalarPower(muDoubleScalarAbs((((((((t77 * in2[125] + t81 *
    in2[126]) + t82 * in2[121]) + t84 * in2[123]) + t83 * in2[128]) - t82 * in2
    [127]) - t83 * in2[122]) - t84 * in2[129]) - t97 * in2[124]), in1[1] - 1.0);
  t106 = t6 * t17;
  t107 = in2[21] * t19;
  t108 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t112 = ((((t196 + t6 * t46) + t46_tmp * t32) + t5 * t227) - in2[23] * t48) -
    t223 * 2.0;
  t113 = (t8 + t10) - 1.0;
  t114 = t9 + t53_tmp;
  t115 = t7 - t51_tmp;
  t116 = in2[21] * t29;
  t117 = t29_tmp * t32;
  t118_tmp = t197 * 2.0;
  b_t118_tmp = t5 * t15_tmp;
  t118 = (((((t22_tmp - t23_tmp) + t106) + t107) + t108) - t118_tmp) -
    b_t118_tmp;
  t127_tmp = in2[23] * t31;
  t127 = ((t63_tmp - t116) - t117) + t127_tmp;
  t130 = muDoubleScalarPower(muDoubleScalarAbs((((((((t118 * in2[124] + t112 *
    in2[126]) + t113 * in2[122]) + t115 * in2[121]) + t114 * in2[129]) - t113 *
    in2[128]) - t114 * in2[123]) - t115 * in2[127]) - t127 * in2[125]), in1[1] -
    1.0);
  t220 = t200 * t12;
  t140 = ((((t168 + t6 * t19) + t17_tmp * t34) + t220 * t15_tmp) - in2[21] * t17)
    - t44_tmp * 2.0;
  t144 = (((((-t25 + t223) + t6 * t29) + in2[22] * t31) + t29_tmp * t34) - t181 *
          2.0) - t220 * t169;
  t145 = (t10 + t11) - 1.0;
  t146 = t50_tmp + t52;
  t147 = t9 - t53_tmp;
  t31 = in2[22] * t48;
  t48 = t46_tmp * t34;
  t44_tmp = in2[21] * t46;
  t160 = ((t63_tmp - t31) - t48) + t44_tmp;
  t163 = muDoubleScalarPower(muDoubleScalarAbs((((((((t140 * in2[124] + t144 *
    in2[125]) + t145 * in2[123]) + t147 * in2[122]) + t146 * in2[127]) - t145 *
    in2[129]) - t146 * in2[121]) - t147 * in2[128]) - t160 * in2[126]), in1[1] -
    1.0);
  t168 = t17_tmp * t36 * 2.0;
  t169 = t29_tmp * t36 * 2.0;
  t46 = in2[28] * 2.0;
  t25 = t5 * 2.0;
  t172 = (t46 + t46_tmp * t36 * 2.0) - t25;
  t174 = t55 + in2[21] * in2[27] * t54 * 2.0;
  t5 = in2[23] * 2.0;
  t177 = t5 + in2[21] * in2[28] * t54 * 2.0;
  t19 = in2[21] * in2[29] * t54 * 2.0;
  t15_tmp = t220 * 2.0;
  t180 = (t35 - t169) + t15_tmp;
  t181 = t41 * 2.0;
  t227 = t4 * t12 * 2.0;
  t183 = (-t168 + t181) + t227;
  t187 = t56 - t19;
  t191 = muDoubleScalarPower(muDoubleScalarAbs(((((t183 * in2[124] + t180 * in2
    [125]) + t187 * in2[132]) - t172 * in2[126]) - t174 * in2[130]) - t177 *
    in2[131]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t196 = t17_tmp * t42 * 2.0;
  t197 = t46_tmp * t42 * 2.0;
  t199 = t55 + in2[22] * in2[28] * t54 * 2.0;
  t200 = in2[22] * in2[27] * t54 * 2.0;
  t4 = in2[21] * 2.0;
  t203 = t4 + in2[22] * in2[29] * t54 * 2.0;
  t204 = (t35 - t15_tmp) + t196;
  t229 = t2 * t12 * 2.0;
  t206 = (t181 - t20) + t229;
  t17 = t59 * 2.0;
  t209 = (t49 - t197) + t17;
  t2 = t5 - t200;
  t215 = muDoubleScalarPower(muDoubleScalarAbs(((((t206 * in2[125] + t209 * in2
    [126]) + t2 * in2[130]) - t204 * in2[124]) - t199 * in2[131]) - t203 * in2
    [132]), in1[1] - 1.0);
  t58 = t46_tmp * t43 * 2.0;
  t220 = t17_tmp * t43 * 2.0;
  t69 = t29_tmp * t43 * 2.0;
  t223 = t55 + in2[23] * in2[29] * t54 * 2.0;
  t29 = t56 + in2[23] * in2[27] * t54 * 2.0;
  t59 = in2[23] * in2[28] * t54 * 2.0;
  memset(&out1[0], 0, 18U * sizeof(real_T));
  out1[18] = t82;
  out1[19] = -t7 - t51_tmp;
  out1[20] = t50_tmp - in2[21] * in2[23] * 2.0;
  out1[21] = ((((t85 + t86) - t61_tmp) - t60_tmp) - t62_tmp) - t97_tmp;
  out1[22] = t77;
  out1[23] = t81;
  out1[24] = (-t8 - t11) + 1.0;
  out1[25] = t83;
  out1[26] = -t50_tmp + t52;
  memset(&out1[27], 0, 82U * sizeof(real_T));
  out1[109] = t7 - in2[21] * in2[22] * 2.0;
  out1[110] = t113;
  out1[111] = -t9 - t53_tmp;
  out1[112] = (((((t22_tmp + t106) + t107) + t108) - t118_tmp) - t23_tmp) -
    b_t118_tmp;
  out1[113] = ((((t116 + t117) - t61_tmp) - t60_tmp) - t62_tmp) - t127_tmp;
  out1[114] = t112;
  out1[115] = -t7 + t51_tmp;
  out1[116] = (-t8 - t10) + 1.0;
  out1[117] = t114;
  memset(&out1[118], 0, 82U * sizeof(real_T));
  out1[200] = t52_tmp * -2.0 - t50_tmp;
  out1[201] = t9 - in2[22] * in2[23] * 2.0;
  out1[202] = t145;
  out1[203] = t140;
  out1[204] = t144;
  out1[205] = ((((t31 + t48) - t61_tmp) - t60_tmp) - t62_tmp) - t44_tmp;
  out1[206] = t146;
  out1[207] = -t9 + t53_tmp;
  out1[208] = (-t10 - t11) + 1.0;
  memset(&out1[209], 0, 85U * sizeof(real_T));
  out1[294] = (t41 * -2.0 + t168) - t227;
  out1[295] = (-t35 + t169) - t15_tmp;
  out1[296] = t172;
  out1[297] = 0.0;
  out1[298] = 0.0;
  out1[299] = 0.0;
  out1[300] = t174;
  out1[301] = t177;
  out1[302] = -t56 + t19;
  memset(&out1[303], 0, 82U * sizeof(real_T));
  out1[385] = (t35 + t196) - t15_tmp;
  out1[386] = (t41 * -2.0 + t20) - t229;
  out1[387] = (-t49 + t197) - t17;
  out1[388] = 0.0;
  out1[389] = 0.0;
  out1[390] = 0.0;
  out1[391] = in2[23] * -2.0 + t200;
  out1[392] = t199;
  out1[393] = t203;
  memset(&out1[394], 0, 82U * sizeof(real_T));
  out1[476] = (in2[28] * -2.0 + t220) - t25;
  out1[477] = (t49 + t69) - t17;
  t5 = t3 * t12 * 2.0;
  out1[478] = (t41 * -2.0 + t58) - t5;
  out1[479] = 0.0;
  out1[480] = 0.0;
  out1[481] = 0.0;
  out1[482] = t29;
  out1[483] = in2[21] * -2.0 + t59;
  out1[484] = t223;
  memset(&out1[485], 0, 61U * sizeof(real_T));
  t227 = (t46 + t25) - t220;
  t229 = (t181 - t58) + t5;
  t20 = (t49 - t17) + t69;
  t58 = t4 - t59;
  t220 = muDoubleScalarPower(muDoubleScalarAbs(((((t229 * in2[126] + t227 * in2
    [124]) + t58 * in2[131]) - t20 * in2[125]) - t223 * in2[132]) - t29 * in2
    [130]), in1[1] - 1.0);
  t5 = a * a + b_a * b_a;
  st.site = &or_emlrtRSI;
  b_sqrt(&st, &t5);
  out2[0] = in1[0] * ((((((t71 + in2[23] * t32) - in2[22] * t34) + in2[21] *
    t63_tmp) + t6 * t27) - a_tmp) - b_a_tmp) * 0.00026666666666666668;
  out2[1] = in1[0] * (((-in2[23] * t27 + in2[21] * t34) + in2[22] * t63_tmp) +
                      t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((t5 + in2[22] * t27) - in2[21] * t32) + in2[23] *
                       t63_tmp) + t6 * t34) * 0.0008;
  out2[3] = in1[0] * (((in2[22] * t43 * 2.0 - in2[23] * t42 * 2.0) + in2[21] *
                       t73 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[23] * t36 * 2.0 - in2[21] * t43 * 2.0) + in2[22] *
                       t73 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[22] * t36 * 2.0 - in2[21] * t42 * 2.0) - in2[23] *
                       t73 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t69 = in1[2] * t82 * t101;
  t59 = in1[2] * t83 * t101;
  t5 = in1[2] * t84 * t101;
  out3[0] = (((((((-in1[2] * t77 * t101 * in2[125] - t69 * in2[121]) + t59 *
                  in2[122]) - in1[2] * t81 * t101 * in2[126]) - t5 * in2[123]) +
               t69 * in2[127]) - t59 * in2[128]) + t5 * in2[129]) + in1[2] * t97
    * t101 * in2[124];
  t69 = in1[2] * t115 * t130;
  t59 = in1[2] * t114 * t130;
  out3[1] = (((((((-in1[2] * t113 * t130 * in2[122] - t69 * in2[121]) + t59 *
                  in2[123]) - in1[2] * t112 * t130 * in2[126]) + in1[2] * t113 *
                t130 * in2[128]) + t69 * in2[127]) - in1[2] * t118 * t130 * in2
              [124]) - t59 * in2[129]) + in1[2] * t127 * t130 * in2[125];
  t69 = in1[2] * t146 * t163;
  t59 = in1[2] * t145 * t163;
  t5 = in1[2] * t147 * t163;
  out3[2] = (((((((-in1[2] * t140 * t163 * in2[124] + t69 * in2[121]) - t59 *
                  in2[123]) - in1[2] * t144 * t163 * in2[125]) - t5 * in2[122])
               - t69 * in2[127]) + t59 * in2[129]) + t5 * in2[128]) + in1[2] *
    t160 * t163 * in2[126];
  out3[3] = ((((-in1[3] * t172 * t191 * in2[126] - in1[3] * t174 * t191 * in2
                [130]) + in1[3] * t180 * t191 * in2[125]) + in1[3] * t183 * t191
              * in2[124]) - in1[3] * t177 * t191 * in2[131]) + in1[3] * t187 *
    t191 * in2[132];
  out3[4] = ((((-in1[3] * t204 * t215 * in2[124] - in1[3] * t199 * t215 * in2
                [131]) + in1[3] * t206 * t215 * in2[125]) - in1[3] * t203 * t215
              * in2[132]) + in1[3] * t209 * t215 * in2[126]) + in1[3] * t2 *
    t215 * in2[130];
  out3[5] = ((((in1[3] * t227 * t220 * in2[124] - in1[3] * t223 * t220 * in2[132])
               - in1[3] * t29 * t220 * in2[130]) + in1[3] * t229 * t220 * in2
              [126]) - in1[3] * t20 * t220 * in2[125]) + in1[3] * t58 * t220 *
    in2[131];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF99.c) */
