/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cnstF7.c
 *
 * Code generation for function 'cnstF7'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "cnstF7.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo rbb_emlrtRSI = { 26,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

static emlrtRSInfo sbb_emlrtRSI = { 27,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

static emlrtRSInfo tbb_emlrtRSI = { 28,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

static emlrtRSInfo ubb_emlrtRSI = { 30,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

static emlrtRSInfo vbb_emlrtRSI = { 35,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

static emlrtRSInfo wbb_emlrtRSI = { 116,/* lineNo */
  "cnstF7",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/cnstF7.m"/* pathName */
};

/* Function Definitions */
void cnstF7(const emlrtStack *sp, const real_T in2[198], real_T out1[91], real_T
            out2[91], real_T *out3)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10_tmp;
  real_T t21;
  real_T t11;
  real_T t14_tmp;
  real_T t15_tmp;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t19_tmp;
  real_T t20;
  real_T t22_tmp;
  real_T t23_tmp_tmp;
  real_T t23_tmp;
  real_T t23;
  real_T t24_tmp;
  real_T t43;
  real_T t25;
  real_T t28;
  real_T t29_tmp;
  real_T b_t29_tmp;
  real_T t30_tmp;
  real_T t31_tmp;
  real_T t31;
  real_T t32_tmp;
  real_T t33_tmp_tmp;
  real_T t33_tmp;
  real_T t33;
  real_T t45;
  real_T t46;
  real_T t34_tmp;
  real_T t35_tmp;
  real_T t36_tmp;
  real_T t37_tmp;
  real_T t48_tmp;
  real_T t38_tmp;
  real_T t39_tmp;
  real_T t40_tmp;
  real_T t41_tmp;
  real_T t293;
  real_T t42_tmp;
  real_T t256;
  real_T t47_tmp_tmp;
  real_T t47_tmp;
  real_T t50_tmp;
  real_T t50;
  real_T t52;
  real_T t54_tmp;
  real_T t55_tmp;
  real_T t56_tmp;
  real_T t57_tmp;
  real_T t58_tmp;
  real_T t64_tmp;
  real_T t65_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61_tmp;
  real_T t62_tmp;
  real_T t63;
  real_T t69;
  real_T t70;
  real_T t252;
  real_T t71_tmp;
  real_T t71;
  real_T t72_tmp;
  real_T b_t72_tmp;
  real_T t73;
  real_T t82;
  real_T t83_tmp;
  real_T t76_tmp;
  real_T t77;
  real_T t78_tmp;
  real_T t78;
  real_T t79_tmp;
  real_T t80;
  real_T t84;
  real_T t81_tmp;
  real_T t85;
  real_T t86;
  real_T t87;
  real_T t88;
  real_T t89;
  real_T t90;
  real_T t91;
  real_T t92;
  real_T t93;
  real_T t97;
  real_T t101;
  real_T t102;
  real_T t208;
  real_T t104;
  real_T t106;
  real_T t108;
  real_T t109;
  real_T t110;
  real_T t113;
  real_T t115;
  real_T t116;
  real_T t215;
  real_T t118;
  real_T t120;
  real_T t123;
  real_T t125;
  real_T t127;
  real_T t130;
  real_T t294;
  real_T t295;
  real_T t132;
  real_T t133;
  real_T t137;
  real_T t143_tmp;
  real_T t143;
  real_T t146;
  real_T t145;
  real_T t148;
  real_T t149;
  real_T t150;
  real_T t151;
  real_T t157;
  real_T t158;
  real_T t159;
  real_T t169;
  real_T t173;
  real_T t174;
  real_T t178;
  real_T t181;
  real_T t207;
  real_T t209;
  real_T out1_tmp;
  real_T b_out1_tmp;
  real_T c_out1_tmp;
  real_T d_out1_tmp;
  real_T e_out1_tmp;
  real_T f_out1_tmp;
  real_T g_out1_tmp;
  real_T h_out1_tmp;
  real_T i_out1_tmp;
  real_T j_out1_tmp;
  real_T k_out1_tmp;
  real_T l_out1_tmp;
  real_T m_out1_tmp;
  real_T n_out1_tmp;
  real_T o_out1_tmp;
  real_T p_out1_tmp;
  real_T q_out1_tmp;
  real_T r_out1_tmp;
  real_T t227;
  real_T t229;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;

  /* CNSTF7 */
  /*     [OUT1,OUT2,OUT3] = CNSTF7(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:50:41 */
  st.site = &rbb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[3] * in2[3];
  st.site = &sbb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[5] * in2[5];
  st.site = &tbb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[4] * in2[4];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &ubb_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[3] * 0.038;
  t8 = in2[4] * 0.03;
  t9 = t6 * 0.038;
  t10_tmp = t8 - t9;
  t21 = t5;
  st.site = &vbb_emlrtRSI;
  b_sqrt(&st, &t21);
  t11 = 1.0 / t21;
  t14_tmp = in2[4] * 0.038 + t6 * 0.03;
  t15_tmp = in2[4] * t10_tmp;
  t16 = in2[3] * 0.03;
  t17 = in2[5] * 0.038;
  t18 = t16 + t17;
  t19_tmp = in2[3] * t18;
  t20 = in2[5] * 0.03;
  t21 = t7 - t20;
  t22_tmp = in2[5] * t21;
  t23_tmp_tmp = in2[3] * in2[4];
  t23_tmp = t23_tmp_tmp * t11;
  t23 = t23_tmp * 0.03;
  t24_tmp = in2[3] * t10_tmp * t11;
  t43 = in2[5] * 0.06;
  t25 = ((t7 + t23) + t24_tmp) - t43;
  t28 = t23_tmp * 0.038;
  t29_tmp = in2[3] * t11;
  b_t29_tmp = t29_tmp * t14_tmp;
  t30_tmp = ((in2[3] * 0.09 + in2[5] * 0.076) + t28) + b_t29_tmp;
  t31_tmp = t2 * t11;
  t31 = t31_tmp * 0.03;
  t32_tmp = t29_tmp * t18;
  t33_tmp_tmp = in2[3] * in2[5];
  t33_tmp = t33_tmp_tmp * t11;
  t33 = t33_tmp * 0.038;
  t45 = in2[4] * 0.076;
  t46 = t6 * 0.06;
  t34_tmp = (((t31 + t32_tmp) + t33) - t45) - t46;
  t35_tmp = t6 * t10_tmp;
  t36_tmp = in2[4] * t14_tmp;
  t37_tmp = in2[5] * t18;
  t48_tmp = in2[3] * t21;
  t38_tmp = ((((-in2[0] + in2[84]) + t35_tmp) + t36_tmp) + t37_tmp) - t48_tmp;
  t39_tmp = in2[3] * t14_tmp;
  t40_tmp = t6 * t18;
  t41_tmp = in2[4] * t21;
  t293 = in2[5] * t10_tmp;
  t42_tmp = ((((in2[1] - in2[85]) + t39_tmp) + t40_tmp) + t41_tmp) - t293;
  t256 = t6 * t14_tmp;
  t47_tmp_tmp = (((in2[2] - in2[86]) + t15_tmp) + t19_tmp) + t22_tmp;
  t47_tmp = t47_tmp_tmp - t256;
  t50_tmp = in2[4] * t11;
  t50 = t50_tmp * 0.03;
  t52 = t50_tmp * 0.038;
  t54_tmp = t6 * (t50 - 0.038);
  t55_tmp = in2[4] * (t52 + 0.03);
  t56_tmp = t50_tmp * t14_tmp;
  t57_tmp = ((t10_tmp + t54_tmp) + t55_tmp) + t56_tmp;
  t58_tmp = t6 * (t52 + 0.03);
  t64_tmp = in2[4] * (t50 - 0.038);
  t65_tmp = t15_tmp * t11;
  t59_tmp = ((t14_tmp + t58_tmp) - t64_tmp) - t65_tmp;
  t60_tmp = in2[3] * (t50 - 0.038);
  t61_tmp = in2[5] * (t52 + 0.03);
  t62_tmp = t50_tmp * t18;
  t63 = (((-t7 + t20) + t60_tmp) + t61_tmp) + t62_tmp;
  t69 = (t6 * t42_tmp + in2[5] * t38_tmp) + in2[3] * t47_tmp;
  t70 = in2[3] * 0.076;
  t252 = in2[4] * in2[5];
  t71_tmp = t252 * t11;
  t71 = t71_tmp * 0.038;
  t72_tmp = in2[5] * t11;
  b_t72_tmp = t72_tmp * t14_tmp;
  t73 = ((-t20 + t70) + t71) + b_t72_tmp;
  t82 = t71_tmp * 0.03;
  t83_tmp = t293 * t11;
  t76_tmp = ((in2[3] * 0.06 + in2[5] * 0.114) - t82) - t83_tmp;
  t77 = in2[4] * 0.06;
  t78_tmp = t3 * t11;
  t78 = t78_tmp * 0.038;
  t79_tmp = t72_tmp * t18;
  t80 = t33_tmp * 0.03;
  t84 = t6 * 0.076;
  t81_tmp = (((t77 + t78) + t79_tmp) + t80) - t84;
  t85 = in2[5] * t6 * 2.0;
  t86 = t2 * 2.0;
  t87 = t3 * 2.0;
  t88 = t6 * 2.0;
  t89 = in2[4] * 2.0;
  t90 = t33_tmp * 2.0;
  t91 = in2[4] * t59_tmp;
  st.site = &wbb_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t92 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t93 = t29_tmp * 0.03;
  t21 = in2[3] * t4 * t92;
  t97 = ((t93 + t29_tmp * (t52 + 0.03)) + t21 * 0.03) + t23_tmp_tmp * t10_tmp *
    t92;
  t101 = ((t29_tmp * 0.038 + t21 * 0.038) + t23_tmp_tmp * t14_tmp * t92) -
    t29_tmp * (t50 - 0.038);
  t102 = t50_tmp * 0.06;
  t5 = in2[4] * t2 * t92;
  t21 = t5 * 0.03;
  t208 = t23_tmp_tmp * in2[5] * t92;
  t104 = t208 * 0.038;
  t106 = (((t102 + t21) + t104) + t23_tmp_tmp * t18 * t92) - 0.076;
  t108 = in2[4] * t34_tmp;
  t109 = t50_tmp * t47_tmp;
  t110 = in2[3] * t30_tmp;
  t113 = ((in2[3] * t57_tmp + in2[5] * t59_tmp) - t6 * t63) - t50_tmp * t42_tmp;
  t115 = 1.0 / (((t2 + t3) + t4) - 1.0);
  t116 = t10_tmp * t11;
  t215 = t2 * t115;
  t118 = ((((t50 + t21) + t116) + t2 * t10_tmp * t92) - t215 * 0.038) + 0.038;
  t120 = t11 * t14_tmp;
  t123 = ((((t52 + t215 * 0.03) + t120) + t2 * t14_tmp * t92) + t5 * 0.038) +
    0.09;
  t125 = t72_tmp * 0.038;
  t127 = t11 * t18;
  t21 = in2[5] * t2 * t92;
  t130 = ((((t29_tmp * 0.15 + t125) + in2[3] * t2 * t92 * 0.03) + t127) + t2 *
          t18 * t92) + t21 * 0.038;
  t215 = in2[5] * t25;
  t294 = t6 * t34_tmp;
  t295 = t29_tmp * t42_tmp;
  t132 = (((t47_tmp + t110) - t215) - t294) - t295;
  t133 = t88 - t31_tmp * 2.0;
  t5 = t33_tmp_tmp * t115;
  t137 = ((t104 + t5 * 0.03) + t33_tmp_tmp * t14_tmp * t92) + 0.076;
  t143_tmp = in2[3] * t3 * t92;
  t143 = (((t29_tmp * 0.076 + t72_tmp * 0.06) + t143_tmp * 0.038) + t21 * 0.03)
    + t33_tmp_tmp * t18 * t92;
  t146 = t208 * 0.03;
  t145 = ((t5 * 0.038 - t146) - t33_tmp_tmp * t10_tmp * t92) + 0.06;
  t148 = in2[4] * t76_tmp;
  t149 = in2[4] * t30_tmp;
  t150 = in2[5] * t34_tmp;
  t151 = t72_tmp * t47_tmp;
  t157 = (((t38_tmp + in2[5] * t76_tmp) + in2[3] * t73) - t6 * t81_tmp) -
    t72_tmp * t42_tmp;
  t158 = t89 + t90;
  t159 = in2[85] * 2.0;
  t21 = t4 * t92;
  t5 = t11 * 0.038 + t21 * 0.038;
  t21 = t11 * 0.03 + t21 * 0.03;
  t169 = ((t127 + in2[3] * t21) + in2[5] * t5) + t4 * t18 * t92;
  t173 = (((((t102 + t116) + in2[4] * t21) + t4 * t10_tmp * t92) + t50_tmp *
           (t52 + 0.03) * 2.0) - t6 * t5) - 0.076;
  t174 = t50_tmp * 0.076;
  t178 = (((((t120 + t174) + t6 * t21) + in2[4] * t5) + t4 * t14_tmp * t92) -
          t50_tmp * (t50 - 0.038) * 2.0) + 0.06;
  t181 = t293 * 2.0;
  t207 = t6 * t59_tmp;
  t208 = in2[4] * t57_tmp;
  t209 = in2[5] * t73;
  t102 = in2[5] * t63;
  t21 = t23_tmp_tmp * 2.0;
  out1[0] = t85 - t21;
  out1[1] = (t86 + t87) - 1.0;
  t5 = in2[3] * t6 * 2.0;
  out1[2] = t252 * -2.0 - t5;
  out1_tmp = t6 * t25;
  b_out1_tmp = t29_tmp * t38_tmp;
  c_out1_tmp = in2[4] * t25;
  d_out1_tmp = in2[3] * t34_tmp;
  e_out1_tmp = t6 * t30_tmp;
  f_out1_tmp = t29_tmp * t47_tmp;
  g_out1_tmp = in2[3] * t25;
  h_out1_tmp = in2[5] * t30_tmp;
  out1[3] = ((((((-in2[5] * (((t149 + t150) - out1_tmp) - b_out1_tmp) + in2[3] *
                  ((((t42_tmp - c_out1_tmp) - d_out1_tmp) - e_out1_tmp) +
                   f_out1_tmp)) + in2[4] * t38_tmp) + in2[3] * t42_tmp) - t6 *
               t47_tmp) + in2[4] * (((t38_tmp + t108) - g_out1_tmp) - h_out1_tmp))
             - t6 * (((((t47_tmp_tmp + t110) - t215) - t256) - t294) - t295)) +
    t29_tmp * t69;
  t294 = t50_tmp * t38_tmp;
  i_out1_tmp = in2[3] * t63;
  j_out1_tmp = t6 * t57_tmp;
  k_out1_tmp = in2[3] * t59_tmp;
  l_out1_tmp = in2[5] * t57_tmp;
  m_out1_tmp = in2[4] * t63;
  out1[4] = ((((((in2[3] * ((((t38_tmp + t91) + t109) - i_out1_tmp) - j_out1_tmp)
                  + in2[3] * t38_tmp) - in2[4] * t42_tmp) - in2[5] * t47_tmp) -
               t6 * t113) - in2[4] * (((t42_tmp - k_out1_tmp) + l_out1_tmp) -
    m_out1_tmp)) - in2[5] * ((((t47_tmp + t207) + t208) + t102) - t294)) +
    t50_tmp * t69;
  t295 = in2[3] * t76_tmp;
  n_out1_tmp = in2[4] * t81_tmp;
  t110 = t6 * t73;
  t47_tmp_tmp = in2[3] * t81_tmp;
  o_out1_tmp = in2[4] * t73;
  p_out1_tmp = in2[5] * t81_tmp;
  q_out1_tmp = t6 * t76_tmp;
  r_out1_tmp = t72_tmp * t38_tmp;
  out1[5] = ((((((in2[5] * ((((t42_tmp - o_out1_tmp) - p_out1_tmp) - q_out1_tmp)
    + r_out1_tmp) + in2[5] * t42_tmp) - in2[4] * t47_tmp) - t6 * t38_tmp) - t6 *
               t157) - in2[4] * (((t47_tmp + t209) - t295) - n_out1_tmp)) + in2
             [3] * (((t148 + t151) - t47_tmp_tmp) - t110)) + t72_tmp * t69;
  memset(&out1[6], 0, 78U * sizeof(real_T));
  out1[84] = -t85 + t21;
  out1[85] = (-t86 - t87) + 1.0;
  out1[86] = t252 * 2.0 + t5;
  out1[87] = 0.0;
  out1[88] = 0.0;
  out1[89] = 0.0;
  out1[90] = 0.0;
  t21 = in2[5] * t4 * t92;
  t215 = ((t72_tmp * 0.03 + t72_tmp * (t52 + 0.03)) + t21 * 0.03) + t252 *
    t10_tmp * t92;
  t5 = ((t125 + t21 * 0.038) + t252 * t14_tmp * t92) - t72_tmp * (t50 - 0.038);
  t293 = in2[4] * t3 * t92;
  t104 = t293 * 0.038;
  t21 = (((t146 + t174) + t104) + t252 * t18 * t92) + 0.06;
  t227 = in2[3] * 2.0 + t71_tmp * 2.0;
  t229 = in2[5] * 2.0 - t23_tmp * 2.0;
  t252 = ((((((((((((((((((in2[86] * -2.0 + t207) + t208) + t209) + t102) + in2
                       [2] * 2.0) + t6 * ((((((t59_tmp + in2[3] * t5) + t50_tmp *
    t81_tmp) + t72_tmp * t63) - in2[5] * t215) - t6 * t21) - t252 * t42_tmp *
    t92)) + t15_tmp * 2.0) + in2[4] * ((((((((((-t8 + t9) + t54_tmp) + t55_tmp)
    + t56_tmp) - t78) - t79_tmp) - t80) + in2[3] * t215) + in2[5] * t5) - in2[4]
    * t21)) + in2[5] * (((((((((((t7 + t60_tmp) + t61_tmp) + t62_tmp) + t71) +
    b_t72_tmp) + in2[4] * t5) + in2[5] * t21) - t6 * t215) - t72_tmp * t59_tmp)
    - t50_tmp * t76_tmp) - t252 * t38_tmp * t92)) + t19_tmp * 2.0) + t22_tmp *
                 2.0) - t295) - n_out1_tmp) - in2[3] * ((((((t76_tmp + t72_tmp *
    t57_tmp) + t50_tmp * t73) + t252 * t47_tmp * t92) - in2[4] * t215) - in2[3] *
    t21) - t6 * t5)) - t256 * 2.0) - t294) - t72_tmp * t113) - t50_tmp * t157) -
    t252 * t69 * t92;
  t78 = t11 * t42_tmp;
  t21 = t3 * t115;
  t256 = ((((t52 + t120) + t104) + t21 * 0.03) + t3 * t14_tmp * t92) - 0.03;
  t87 = ((((t50 + t116) + t3 * t10_tmp * t92) + t293 * 0.03) - t21 * 0.038) -
    0.114;
  t146 = ((((t93 + t127) + t72_tmp * 0.19) + in2[5] * t3 * t92 * 0.038) + t3 *
          t18 * t92) + t143_tmp * 0.03;
  t85 = t11 * t69;
  t86 = t11 * t47_tmp;
  t125 = t88 - t78_tmp * 2.0;
  t209 = (((((((((((((-t148 + t149) + t150) - t151) + t6 * (((((((((((t7 + t20)
    - t23) - t24_tmp) + t71) + b_t72_tmp) + in2[5] * t145) + in2[3] * t137) +
    t72_tmp * t34_tmp) + t29_tmp * t81_tmp) - t6 * t143) - t33_tmp_tmp * t42_tmp
    * t92)) + in2[5] * ((((((t34_tmp + in2[4] * t137) + in2[5] * t143) + t6 *
    t145) + t72_tmp * t25) - t29_tmp * t76_tmp) - t33_tmp_tmp * t38_tmp * t92))
                 + in2[3] * ((((((t81_tmp + in2[3] * t143) + t6 * t137) - in2[4]
    * t145) - t72_tmp * t30_tmp) - t29_tmp * t73) - t33_tmp_tmp * t47_tmp * t92))
                + t110) + t47_tmp_tmp) + in2[4] * ((((((((t16 - t17) + t28) +
    b_t29_tmp) + t82) + t83_tmp) + in2[5] * t137) - in2[4] * t143) - in2[3] *
    t145)) - out1_tmp) - b_out1_tmp) - t72_tmp * t132) - t29_tmp * t157) -
    t33_tmp_tmp * t69 * t92;
  t102 = t89 - t90;
  t293 = t125 * in2[104];
  t294 = in2[3] * in2[102] * 4.0;
  t295 = in2[5] * in2[104] * 4.0;
  t110 = t158 * in2[102];
  t47_tmp_tmp = t227 * in2[103];
  out2[0] = (t293 - t110) - t47_tmp_tmp;
  out2[1] = t294 + t295;
  n_out1_tmp = t229 * in2[103];
  t174 = t102 * in2[104];
  out2[2] = (-t133 * in2[102] - n_out1_tmp) - t174;
  t207 = (in2[1] * -2.0 + t159) + t181;
  t208 = t39_tmp * 2.0;
  t104 = t41_tmp * 2.0;
  t215 = t11 * t38_tmp;
  t5 = t40_tmp * 2.0;
  t21 = ((((((((((((((((((t91 + t108) + t109) - in2[0] * 2.0) + in2[84] * 2.0) +
                      t35_tmp * 2.0) + t36_tmp * 2.0) + t37_tmp * 2.0) + t50_tmp
                   * t132) + t29_tmp * t113) + t23_tmp_tmp * t69 * t92) -
                t48_tmp * 2.0) - g_out1_tmp) - h_out1_tmp) - i_out1_tmp) - in2[4]
            * (((((((((t14_tmp - t31) - t32_tmp) - t33) - t58_tmp) + t64_tmp) +
                  t65_tmp) + in2[3] * t97) + in2[5] * t101) - in2[4] * t106)) -
           in2[3] * (((((((((((-t20 + t23) + t24_tmp) + t60_tmp) + t61_tmp) +
    t62_tmp) + t6 * t101) + in2[4] * t97) + in2[3] * t106) - t50_tmp * t30_tmp)
                      - t29_tmp * t57_tmp) - t23_tmp_tmp * t47_tmp * t92)) -
          in2[5] * ((((((t30_tmp + in2[4] * t101) + in2[5] * t106) + t50_tmp *
                       t25) - t6 * t97) - t29_tmp * t59_tmp) - t23_tmp_tmp *
                    t38_tmp * t92)) - j_out1_tmp) - t6 * ((((((t57_tmp + in2[3] *
    t101) + t50_tmp * t34_tmp) + t29_tmp * t63) - in2[5] * t97) - t6 * t106) -
    t23_tmp_tmp * t42_tmp * t92);
  out2[3] = (((((((in2[3] * in2[100] * 4.0 - in2[3] * in2[184] * 4.0) - t133 *
                  in2[101]) - t158 * in2[99]) + t133 * in2[185]) + t158 * in2
               [183]) - t209 * in2[104]) - in2[102] * ((((((((((((((t207 + in2[3]
    * ((((((((((in2[4] * -0.152 - t6 * 0.12) + in2[4] * t118) + in2[3] * t130) +
    t31_tmp * 0.06) - t86) + t6 * t123) + t33_tmp * 0.076) + t32_tmp * 2.0) -
        t29_tmp * t30_tmp * 2.0) - t2 * t47_tmp * t92)) - t208) - t104) +
    c_out1_tmp * 2.0) + d_out1_tmp * 2.0) - t5) + e_out1_tmp * 2.0) - t85) +
    in2[4] * ((((((in2[5] * -0.12 + t70) + in2[3] * t118) + in2[5] * t123) -
                in2[4] * t130) + t23_tmp * 0.06) + t24_tmp * 2.0)) + in2[5] *
    (((((in2[4] * t123 + in2[5] * t130) - t215) - t6 * t118) + t29_tmp * t25 *
      2.0) - t2 * t38_tmp * t92)) + t6 * (((((((((in2[3] * 0.18 + in2[5] * 0.152)
    - in2[5] * t118) + in2[3] * t123) - t78) - t6 * t130) + t23_tmp * 0.076) +
    b_t29_tmp * 2.0) + t29_tmp * t34_tmp * 2.0) - t2 * t42_tmp * t92)) -
    f_out1_tmp * 2.0) - t29_tmp * t132 * 2.0) - t2 * t69 * t92)) + in2[103] *
    t21;
  out2[4] = (((((in2[103] * (((((((((((((t207 + t85) + in2[3] * ((((((((((t45 +
    t46) + t86) - t64_tmp * 2.0) - in2[3] * t169) - in2[4] * t173) + t58_tmp *
    2.0) - t6 * t178) - t65_tmp * 2.0) + t50_tmp * t57_tmp * 2.0) + t4 * t47_tmp
    * t92)) - t208) - t104) + k_out1_tmp * 2.0) - l_out1_tmp * 2.0) + m_out1_tmp
    * 2.0) - in2[5] * ((((((((((t77 - t84) + t55_tmp * 2.0) + in2[5] * t169) +
    in2[4] * t178) - t215) + t54_tmp * 2.0) - t6 * t173) + t56_tmp * 2.0) -
                        t50_tmp * t59_tmp * 2.0) - t4 * t38_tmp * t92)) - t5) +
    in2[4] * (((((((t43 - t70) + t60_tmp * 2.0) + t61_tmp * 2.0) + in2[4] * t169)
                - in2[3] * t173) - in2[5] * t178) + t62_tmp * 2.0)) + t6 *
    (((((t78 + in2[5] * t173) - in2[3] * t178) + t6 * t169) - t50_tmp * t63 *
      2.0) + t4 * t42_tmp * t92)) + t50_tmp * t113 * 2.0) + t4 * t69 * t92) -
                 t227 * in2[99]) - t229 * in2[101]) - t252 * in2[104]) + t227 *
              in2[183]) + t229 * in2[185]) + in2[102] * t21;
  out2[5] = (((((((in2[5] * in2[100] * 4.0 - in2[5] * in2[184] * 4.0) - t252 *
                  in2[103]) + t125 * in2[99]) - t209 * in2[102]) - t102 * in2
               [101]) - t125 * in2[183]) + t102 * in2[185]) + in2[104] *
    ((((((((((((((((in2[1] * 2.0 - t159) - t181) + t85) - in2[4] * ((((((in2[3] *
    0.152 - t43) + in2[5] * t256) + in2[3] * t87) - in2[4] * t146) + t71_tmp *
    0.076) + b_t72_tmp * 2.0)) - in2[5] * ((((((((((in2[4] * 0.12 - t6 * 0.152)
    + in2[4] * t256) + in2[5] * t146) + t78_tmp * 0.076) - t215) - t6 * t87) +
    t33_tmp * 0.06) + t79_tmp * 2.0) - t72_tmp * t76_tmp * 2.0) - t3 * t38_tmp *
    t92)) + t208) + t104) - o_out1_tmp * 2.0) - p_out1_tmp * 2.0) + t5) -
          q_out1_tmp * 2.0) + in2[3] * (((((t86 - in2[4] * t87) - in2[3] * t146)
            - t6 * t256) + t72_tmp * t73 * 2.0) + t3 * t47_tmp * t92)) + t6 *
        (((((((((in2[3] * -0.12 - in2[5] * 0.228) + t78) - in2[3] * t256) + in2
              [5] * t87) + t6 * t146) + t71_tmp * 0.06) + t83_tmp * 2.0) -
          t72_tmp * t81_tmp * 2.0) + t3 * t42_tmp * t92)) + r_out1_tmp * 2.0) +
      t72_tmp * t157 * 2.0) + t3 * t69 * t92);
  memset(&out2[6], 0, 78U * sizeof(real_T));
  out2[84] = (-t293 + t110) + t47_tmp_tmp;
  out2[85] = -t294 - t295;
  out2[86] = (t133 * in2[102] + n_out1_tmp) + t174;
  out2[87] = 0.0;
  out2[88] = 0.0;
  out2[89] = 0.0;
  out2[90] = 0.0;
  *out3 = 0.0;
}

/* End of code generation (cnstF7.c) */
