/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF2.c
 *
 * Code generation for function 'massF2'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "massF2.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo bh_emlrtRSI = { 16, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

static emlrtRSInfo ch_emlrtRSI = { 17, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

static emlrtRSInfo dh_emlrtRSI = { 18, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

static emlrtRSInfo eh_emlrtRSI = { 20, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

static emlrtRSInfo fh_emlrtRSI = { 23, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

static emlrtRSInfo gh_emlrtRSI = { 31, /* lineNo */
  "massF2",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF2.m"/* pathName */
};

/* Function Definitions */
void massF2(const emlrtStack *sp, const real_T in2[198], real_T out2[546],
            real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF2 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF2(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:21:09 */
  st.site = &bh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[9] * in2[9];
  st.site = &ch_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[10] * in2[10];
  st.site = &dh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[11] * in2[11];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &eh_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[11] * 2.0;
  t28 = in2[9] * in2[10];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &fh_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[9] * in2[11] * t6 * 2.0;
  t12 = in2[9] * 2.0;
  t13 = in2[10] * in2[11] * t6 * 2.0;
  memset(&out2[0], 0, 36U * sizeof(real_T));
  out2[36] = 1.0;
  out2[37] = 0.0;
  out2[38] = 0.0;
  out2[39] = 0.0;
  out2[40] = 0.0;
  out2[41] = 0.0;
  out2[42] = 0.0;
  out2[43] = 1.0;
  out2[44] = 0.0;
  out2[45] = 0.0;
  out2[46] = 0.0;
  out2[47] = 0.0;
  out2[48] = 0.0;
  out2[49] = 0.0;
  out2[50] = 1.0;
  out2[51] = 0.0;
  out2[52] = 0.0;
  out2[53] = 0.0;
  out2[54] = 0.0;
  out2[55] = 0.0;
  out2[56] = 0.0;
  out2[57] = t9 + t2 * t6 * 2.0;
  out2[58] = -t7 + t8;
  out2[59] = in2[10] * 2.0 + t11;
  out2[60] = 0.0;
  out2[61] = 0.0;
  out2[62] = 0.0;
  out2[63] = t7 + t8;
  out2[64] = t9 + t3 * t6 * 2.0;
  out2[65] = -t12 + t13;
  out2[66] = 0.0;
  out2[67] = 0.0;
  out2[68] = 0.0;
  out2[69] = in2[10] * -2.0 + t11;
  out2[70] = t12 + t13;
  out2[71] = t9 + t4 * t6 * 2.0;
  memset(&out2[72], 0, 474U * sizeof(real_T));
  st.site = &gh_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[10] * t6 * 2.0;
  t16 = in2[10] * t2 * t14 * 2.0;
  t17 = in2[9] * t6 * 2.0;
  t18 = t28 * in2[11] * t14 * 2.0;
  t9 = in2[11] * t6 * 2.0;
  t11 = in2[11] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[9] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[11] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[9] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[10] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 57U * sizeof(real_T));
  out3[57] = (t12 * in2[109] + t5 * in2[110]) + in2[108] * (t17 + in2[9] * t2 *
    t14 * 2.0);
  out3[58] = (t12 * in2[108] + (t18 + 2.0) * in2[110]) - in2[109] * (t17 - t13);
  out3[59] = ((t18 - 2.0) * in2[109] + t5 * in2[108]) - in2[110] * (t17 - t28);
  out3[60] = 0.0;
  out3[61] = 0.0;
  out3[62] = 0.0;
  out3[63] = (t7 * in2[109] + (t18 - 2.0) * in2[110]) - in2[108] * (t15 - t16);
  out3[64] = (t7 * in2[108] + t6 * in2[110]) + in2[109] * (t15 + in2[10] * t3 *
    t14 * 2.0);
  out3[65] = ((t18 + 2.0) * in2[108] + t6 * in2[109]) - in2[110] * (t15 - t30);
  out3[66] = 0.0;
  out3[67] = 0.0;
  out3[68] = 0.0;
  out3[69] = ((t18 + 2.0) * in2[109] + t31 * in2[110]) - in2[108] * (t9 - t11);
  out3[70] = ((t18 - 2.0) * in2[108] + t32 * in2[110]) - in2[109] * (t9 - t8);
  out3[71] = (t31 * in2[108] + t32 * in2[109]) + in2[110] * (t9 + in2[11] * t4 *
    t14 * 2.0);
  memset(&out3[72], 0, 474U * sizeof(real_T));
}

/* End of code generation (massF2.c) */
