/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF9.c
 *
 * Code generation for function 'massF9'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "massF9.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo si_emlrtRSI = { 16, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

static emlrtRSInfo ti_emlrtRSI = { 17, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

static emlrtRSInfo ui_emlrtRSI = { 18, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

static emlrtRSInfo vi_emlrtRSI = { 20, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

static emlrtRSInfo wi_emlrtRSI = { 23, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

static emlrtRSInfo xi_emlrtRSI = { 31, /* lineNo */
  "massF9",                            /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF9.m"/* pathName */
};

/* Function Definitions */
void massF9(const emlrtStack *sp, const real_T in2[198], real_T out2[546],
            real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF9 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF9(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:21:16 */
  st.site = &si_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[51] * in2[51];
  st.site = &ti_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[52] * in2[52];
  st.site = &ui_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[53] * in2[53];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &vi_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[53] * 2.0;
  t28 = in2[51] * in2[52];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &wi_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[51] * in2[53] * t6 * 2.0;
  t12 = in2[51] * 2.0;
  t13 = in2[52] * in2[53] * t6 * 2.0;
  memset(&out2[0], 0, 288U * sizeof(real_T));
  out2[288] = 1.0;
  out2[289] = 0.0;
  out2[290] = 0.0;
  out2[291] = 0.0;
  out2[292] = 0.0;
  out2[293] = 0.0;
  out2[294] = 0.0;
  out2[295] = 1.0;
  out2[296] = 0.0;
  out2[297] = 0.0;
  out2[298] = 0.0;
  out2[299] = 0.0;
  out2[300] = 0.0;
  out2[301] = 0.0;
  out2[302] = 1.0;
  out2[303] = 0.0;
  out2[304] = 0.0;
  out2[305] = 0.0;
  out2[306] = 0.0;
  out2[307] = 0.0;
  out2[308] = 0.0;
  out2[309] = t9 + t2 * t6 * 2.0;
  out2[310] = -t7 + t8;
  out2[311] = in2[52] * 2.0 + t11;
  out2[312] = 0.0;
  out2[313] = 0.0;
  out2[314] = 0.0;
  out2[315] = t7 + t8;
  out2[316] = t9 + t3 * t6 * 2.0;
  out2[317] = -t12 + t13;
  out2[318] = 0.0;
  out2[319] = 0.0;
  out2[320] = 0.0;
  out2[321] = in2[52] * -2.0 + t11;
  out2[322] = t12 + t13;
  out2[323] = t9 + t4 * t6 * 2.0;
  memset(&out2[324], 0, 222U * sizeof(real_T));
  st.site = &xi_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[52] * t6 * 2.0;
  t16 = in2[52] * t2 * t14 * 2.0;
  t17 = in2[51] * t6 * 2.0;
  t18 = t28 * in2[53] * t14 * 2.0;
  t9 = in2[53] * t6 * 2.0;
  t11 = in2[53] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[51] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[53] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[51] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[52] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 309U * sizeof(real_T));
  out3[309] = (t12 * in2[151] + t5 * in2[152]) + in2[150] * (t17 + in2[51] * t2 *
    t14 * 2.0);
  out3[310] = (t12 * in2[150] + (t18 + 2.0) * in2[152]) - in2[151] * (t17 - t13);
  out3[311] = ((t18 - 2.0) * in2[151] + t5 * in2[150]) - in2[152] * (t17 - t28);
  out3[312] = 0.0;
  out3[313] = 0.0;
  out3[314] = 0.0;
  out3[315] = (t7 * in2[151] + (t18 - 2.0) * in2[152]) - in2[150] * (t15 - t16);
  out3[316] = (t7 * in2[150] + t6 * in2[152]) + in2[151] * (t15 + in2[52] * t3 *
    t14 * 2.0);
  out3[317] = ((t18 + 2.0) * in2[150] + t6 * in2[151]) - in2[152] * (t15 - t30);
  out3[318] = 0.0;
  out3[319] = 0.0;
  out3[320] = 0.0;
  out3[321] = ((t18 + 2.0) * in2[151] + t31 * in2[152]) - in2[150] * (t9 - t11);
  out3[322] = ((t18 - 2.0) * in2[150] + t32 * in2[152]) - in2[151] * (t9 - t8);
  out3[323] = (t31 * in2[150] + t32 * in2[151]) + in2[152] * (t9 + in2[53] * t4 *
    t14 * 2.0);
  memset(&out3[324], 0, 222U * sizeof(real_T));
}

/* End of code generation (massF9.c) */
