/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * massF10.c
 *
 * Code generation for function 'massF10'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "massF10.h"
#include "error.h"
#include "sqrt.h"
#include "EOM_eq_data.h"

/* Variable Definitions */
static emlrtRSInfo yi_emlrtRSI = { 16, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

static emlrtRSInfo aj_emlrtRSI = { 17, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

static emlrtRSInfo bj_emlrtRSI = { 18, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

static emlrtRSInfo cj_emlrtRSI = { 20, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

static emlrtRSInfo dj_emlrtRSI = { 23, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

static emlrtRSInfo ej_emlrtRSI = { 31, /* lineNo */
  "massF10",                           /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/massF10.m"/* pathName */
};

/* Function Definitions */
void massF10(const emlrtStack *sp, const real_T in2[198], real_T out2[546],
             real_T out3[546], real_T out4[6])
{
  int32_T i;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t9;
  real_T t6;
  real_T t7;
  real_T t28;
  real_T t8;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t17;
  real_T t18;
  real_T t30;
  real_T t31;
  real_T t32;
  emlrtStack st;
  emlrtStack b_st;
  emlrtStack c_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  c_st.prev = &b_st;
  c_st.tls = b_st.tls;
  for (i = 0; i < 6; i++) {
    out4[i] = dv0[i];
  }

  /* MASSF10 */
  /*     [OUT1,OUT2,OUT3,OUT4] = MASSF10(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:21:14 */
  st.site = &yi_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t2 = in2[57] * in2[57];
  st.site = &aj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t3 = in2[58] * in2[58];
  st.site = &bj_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  t4 = in2[59] * in2[59];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t9 = t5;
  st.site = &cj_emlrtRSI;
  b_sqrt(&st, &t9);
  t6 = 1.0 / t9;
  t7 = in2[59] * 2.0;
  t28 = in2[57] * in2[58];
  t8 = t28 * t6 * 2.0;
  t9 = t5;
  st.site = &dj_emlrtRSI;
  b_sqrt(&st, &t9);
  t9 *= 2.0;
  t11 = in2[57] * in2[59] * t6 * 2.0;
  t12 = in2[57] * 2.0;
  t13 = in2[58] * in2[59] * t6 * 2.0;
  memset(&out2[0], 0, 324U * sizeof(real_T));
  out2[324] = 1.0;
  out2[325] = 0.0;
  out2[326] = 0.0;
  out2[327] = 0.0;
  out2[328] = 0.0;
  out2[329] = 0.0;
  out2[330] = 0.0;
  out2[331] = 1.0;
  out2[332] = 0.0;
  out2[333] = 0.0;
  out2[334] = 0.0;
  out2[335] = 0.0;
  out2[336] = 0.0;
  out2[337] = 0.0;
  out2[338] = 1.0;
  out2[339] = 0.0;
  out2[340] = 0.0;
  out2[341] = 0.0;
  out2[342] = 0.0;
  out2[343] = 0.0;
  out2[344] = 0.0;
  out2[345] = t9 + t2 * t6 * 2.0;
  out2[346] = -t7 + t8;
  out2[347] = in2[58] * 2.0 + t11;
  out2[348] = 0.0;
  out2[349] = 0.0;
  out2[350] = 0.0;
  out2[351] = t7 + t8;
  out2[352] = t9 + t3 * t6 * 2.0;
  out2[353] = -t12 + t13;
  out2[354] = 0.0;
  out2[355] = 0.0;
  out2[356] = 0.0;
  out2[357] = in2[58] * -2.0 + t11;
  out2[358] = t12 + t13;
  out2[359] = t9 + t4 * t6 * 2.0;
  memset(&out2[360], 0, 186U * sizeof(real_T));
  st.site = &ej_emlrtRSI;
  b_st.site = &tg_emlrtRSI;
  if (t5 < 0.0) {
    c_st.site = &ug_emlrtRSI;
    error(&c_st);
  }

  t14 = 1.0 / muDoubleScalarPower(t5, 1.5);
  t15 = in2[58] * t6 * 2.0;
  t16 = in2[58] * t2 * t14 * 2.0;
  t17 = in2[57] * t6 * 2.0;
  t18 = t28 * in2[59] * t14 * 2.0;
  t9 = in2[59] * t6 * 2.0;
  t11 = in2[59] * t2 * t14 * 2.0;
  t12 = t15 + t16;
  t13 = in2[57] * t3 * t14 * 2.0;
  t7 = t17 + t13;
  t8 = in2[59] * t3 * t14 * 2.0;
  t5 = t9 + t11;
  t28 = in2[57] * t4 * t14 * 2.0;
  t6 = t9 + t8;
  t30 = in2[58] * t4 * t14 * 2.0;
  t31 = t17 + t28;
  t32 = t15 + t30;
  memset(&out3[0], 0, 345U * sizeof(real_T));
  out3[345] = (t12 * in2[157] + t5 * in2[158]) + in2[156] * (t17 + in2[57] * t2 *
    t14 * 2.0);
  out3[346] = (t12 * in2[156] + (t18 + 2.0) * in2[158]) - in2[157] * (t17 - t13);
  out3[347] = ((t18 - 2.0) * in2[157] + t5 * in2[156]) - in2[158] * (t17 - t28);
  out3[348] = 0.0;
  out3[349] = 0.0;
  out3[350] = 0.0;
  out3[351] = (t7 * in2[157] + (t18 - 2.0) * in2[158]) - in2[156] * (t15 - t16);
  out3[352] = (t7 * in2[156] + t6 * in2[158]) + in2[157] * (t15 + in2[58] * t3 *
    t14 * 2.0);
  out3[353] = ((t18 + 2.0) * in2[156] + t6 * in2[157]) - in2[158] * (t15 - t30);
  out3[354] = 0.0;
  out3[355] = 0.0;
  out3[356] = 0.0;
  out3[357] = ((t18 + 2.0) * in2[157] + t31 * in2[158]) - in2[156] * (t9 - t11);
  out3[358] = ((t18 - 2.0) * in2[156] + t32 * in2[158]) - in2[157] * (t9 - t8);
  out3[359] = (t31 * in2[156] + t32 * in2[157]) + in2[158] * (t9 + in2[59] * t4 *
    t14 * 2.0);
  memset(&out3[360], 0, 186U * sizeof(real_T));
}

/* End of code generation (massF10.c) */
