/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * sprdmpF100.c
 *
 * Code generation for function 'sprdmpF100'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "EOM_eq.h"
#include "sprdmpF100.h"
#include "sqrt.h"

/* Variable Definitions */
static emlrtRSInfo fp_emlrtRSI = { 40, /* lineNo */
  "sprdmpF100",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF100.m"/* pathName */
};

static emlrtRSInfo gp_emlrtRSI = { 46, /* lineNo */
  "sprdmpF100",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF100.m"/* pathName */
};

static emlrtRSInfo kp_emlrtRSI = { 76, /* lineNo */
  "sprdmpF100",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF100.m"/* pathName */
};

static emlrtRSInfo lp_emlrtRSI = { 88, /* lineNo */
  "sprdmpF100",                        /* fcnName */
  "/home/hadi/MEGAsync/Hadi/AutoTMTDyn/Code/AutoTMTDyn/Beta/v1.0/Fabric/code/sprdmpF100.m"/* pathName */
};

/* Function Definitions */
void sprdmpF100(const emlrtStack *sp, const real_T in1[6], const real_T in2[198],
                real_T out1[546], real_T out2[6], real_T out3[6], real_T out4[6])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t166;
  real_T t214;
  real_T t184;
  real_T t17_tmp;
  real_T t17;
  real_T t19;
  real_T t20;
  real_T t208;
  real_T t22_tmp;
  real_T t23_tmp;
  real_T t207;
  real_T t25;
  real_T t213;
  real_T t33_tmp;
  real_T t209;
  real_T t27;
  real_T t29_tmp;
  real_T t29;
  real_T t31;
  real_T t44_tmp;
  real_T t32_tmp;
  real_T t32;
  real_T t34;
  real_T t35;
  real_T t36;
  real_T t41;
  real_T t42;
  real_T t43;
  real_T t46_tmp;
  real_T t46;
  real_T t48;
  real_T t49;
  real_T t50_tmp;
  real_T t215;
  real_T t51_tmp;
  real_T t52_tmp;
  real_T t52;
  real_T t53_tmp;
  real_T b_t53_tmp;
  real_T t54;
  real_T t55;
  real_T t56;
  real_T t57_tmp;
  real_T t58_tmp;
  real_T t59_tmp;
  real_T t60_tmp;
  real_T t61;
  real_T t199;
  real_T t65;
  real_T t69;
  real_T t70;
  real_T t71;
  real_T t72;
  real_T t73;
  real_T t74;
  real_T t85_tmp;
  real_T t85;
  real_T t89;
  real_T t94;
  real_T t95;
  real_T t96;
  real_T t100;
  real_T t101;
  real_T t102;
  real_T t103;
  real_T t104;
  real_T t105;
  real_T t106_tmp;
  real_T b_t106_tmp;
  real_T t106;
  real_T t115_tmp;
  real_T t115;
  real_T t118;
  real_T t128;
  real_T t132;
  real_T t133;
  real_T t134;
  real_T t135;
  real_T t136;
  real_T t137;
  real_T t148;
  real_T t151;
  real_T t158;
  real_T t160;
  real_T t162;
  real_T t165;
  real_T t168;
  real_T t171;
  real_T t175;
  real_T t179;
  real_T t187;
  real_T t191;
  real_T t192;
  real_T t194;
  real_T t197;
  int32_T i;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* SPRDMPF100 */
  /*     [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6,OUT7,OUT8] = SPRDMPF100(IN1,IN2,S) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     08-Jan-2019 02:26:12 */
  t2 = in2[22] * in2[22];
  t3 = in2[23] * in2[23];
  t4 = in2[21] * in2[21];
  t5 = ((-t2 - t3) - t4) + 1.0;
  t6 = t5;
  st.site = &fp_emlrtRSI;
  b_sqrt(&st, &t6);
  t7 = in2[23] * t6 * 2.0;
  t8 = t3 * 2.0;
  t9 = in2[21] * t6 * 2.0;
  t10 = t4 * 2.0;
  t11 = t2 * 2.0;
  st.site = &gp_emlrtRSI;
  b_sqrt(&st, &t5);
  t12 = 1.0 / t5;
  t166 = in2[19] - in2[25];
  t214 = in2[20] - in2[26];
  t184 = in2[18] - in2[24];
  t17_tmp = in2[21] * t12;
  t17 = (-in2[20] + in2[26]) + t17_tmp * t166;
  t19 = t166 + t17_tmp * t214;
  t20 = t6 * t166;
  t208 = in2[21] * t214;
  t22_tmp = in2[21] * t166;
  t23_tmp = t6 * t214;
  t207 = in2[22] * t184;
  t25 = t6 * t184;
  t213 = in2[23] * t166;
  t33_tmp = in2[22] * t214;
  t209 = t25 + t213;
  t27 = t209 - t33_tmp;
  t29_tmp = in2[22] * t12;
  t29 = (-in2[18] + in2[24]) + t29_tmp * t214;
  t31 = t214 + t29_tmp * t184;
  t44_tmp = in2[23] * t184;
  t32_tmp = t20 + t208;
  t32 = t32_tmp - t44_tmp;
  t34 = (-t22_tmp + t23_tmp) + t207;
  t35 = in2[29] * 2.0;
  t36 = in2[21] - in2[27];
  t5 = ((-(in2[27] * in2[27]) - in2[28] * in2[28]) - in2[29] * in2[29]) + 1.0;
  t41 = t5;
  st.site = &kp_emlrtRSI;
  b_sqrt(&st, &t41);
  t42 = in2[22] - in2[28];
  t43 = in2[23] - in2[29];
  t46_tmp = in2[23] * t12;
  t46 = t184 + t46_tmp * t166;
  t48 = (-in2[19] + in2[25]) + t46_tmp * t184;
  t49 = in2[27] * 2.0;
  t50_tmp = in2[22] * t6 * 2.0;
  t215 = in2[21] * in2[22];
  t51_tmp = t215 * 2.0;
  t52_tmp = in2[21] * in2[23];
  t52 = t52_tmp * 2.0;
  t53_tmp = in2[22] * in2[23];
  b_t53_tmp = t53_tmp * 2.0;
  st.site = &lp_emlrtRSI;
  b_sqrt(&st, &t5);
  t54 = 1.0 / t5;
  t55 = t6 * 2.0;
  t56 = in2[22] * 2.0;
  t57_tmp = in2[21] * t184;
  t58_tmp = in2[22] * t166;
  t59_tmp = in2[23] * t214;
  t60_tmp = (t57_tmp + t58_tmp) + t59_tmp;
  t61 = t6 - t41;
  t199 = t53_tmp * t12;
  t65 = (((((t23_tmp + t207) + t6 * t31) + t29_tmp * t27) + t199 * t166) - in2
         [22] * t29) - t22_tmp * 2.0;
  t69 = (((((-t20 + t44_tmp) + t6 * t48) + in2[23] * t46) + t46_tmp * t27) -
         t208 * 2.0) - t199 * t214;
  t70 = (t8 + t11) - 1.0;
  t71 = t7 + t51_tmp;
  t72 = t50_tmp - t52;
  t73 = in2[23] * t17;
  t74 = t17_tmp * t27;
  t85_tmp = in2[22] * t19;
  t85 = ((t60_tmp - t73) - t74) + t85_tmp;
  t89 = muDoubleScalarPower(muDoubleScalarAbs((((((((t65 * in2[121] + t69 * in2
    [122]) + t70 * in2[117]) + t72 * in2[119]) + t71 * in2[124]) - t70 * in2[123])
    - t71 * in2[118]) - t72 * in2[125]) - t85 * in2[120]), in1[1] - 1.0);
  t94 = t6 * t17;
  t95 = in2[21] * t19;
  t96 = t17_tmp * t32;
  t5 = t52_tmp * t12;
  t100 = ((((t209 + t6 * t46) + t46_tmp * t32) + t5 * t214) - in2[23] * t48) -
    t33_tmp * 2.0;
  t101 = (t8 + t10) - 1.0;
  t102 = t9 + b_t53_tmp;
  t103 = t7 - t51_tmp;
  t104 = in2[21] * t29;
  t105 = t29_tmp * t32;
  t106_tmp = t207 * 2.0;
  b_t106_tmp = t5 * t184;
  t106 = (((((t22_tmp - t23_tmp) + t94) + t95) + t96) - t106_tmp) - b_t106_tmp;
  t115_tmp = in2[23] * t31;
  t115 = ((t60_tmp - t104) - t105) + t115_tmp;
  t118 = muDoubleScalarPower(muDoubleScalarAbs((((((((t106 * in2[120] + t100 *
    in2[122]) + t101 * in2[118]) + t103 * in2[117]) + t102 * in2[125]) - t101 *
    in2[124]) - t102 * in2[119]) - t103 * in2[123]) - t115 * in2[121]), in1[1] -
    1.0);
  t208 = t215 * t12;
  t128 = ((((t32_tmp + t6 * t19) + t17_tmp * t34) + t208 * t184) - in2[21] * t17)
    - t44_tmp * 2.0;
  t132 = (((((-t25 + t33_tmp) + t6 * t29) + in2[22] * t31) + t29_tmp * t34) -
          t213 * 2.0) - t208 * t166;
  t133 = (t10 + t11) - 1.0;
  t134 = t50_tmp + t52;
  t135 = t9 - b_t53_tmp;
  t136 = in2[22] * t48;
  t137 = t46_tmp * t34;
  t33_tmp = in2[21] * t46;
  t148 = ((t60_tmp - t136) - t137) + t33_tmp;
  t151 = muDoubleScalarPower(muDoubleScalarAbs((((((((t128 * in2[120] + t132 *
    in2[121]) + t133 * in2[119]) + t135 * in2[118]) + t134 * in2[123]) - t133 *
    in2[125]) - t134 * in2[117]) - t135 * in2[124]) - t148 * in2[122]), in1[1] -
    1.0);
  t29 = t17_tmp * t36 * 2.0;
  t31 = t29_tmp * t36 * 2.0;
  t158 = in2[28] * 2.0;
  t48 = t5 * 2.0;
  t160 = (t158 + t46_tmp * t36 * 2.0) - t48;
  t162 = t55 + in2[21] * in2[27] * t54 * 2.0;
  t5 = in2[23] * 2.0;
  t165 = t5 + in2[21] * in2[28] * t54 * 2.0;
  t166 = in2[21] * in2[29] * t54 * 2.0;
  t44_tmp = t208 * 2.0;
  t168 = (t35 - t31) + t44_tmp;
  t46 = t41 * 2.0;
  t53_tmp = t4 * t12 * 2.0;
  t171 = (-t29 + t46) + t53_tmp;
  t175 = t56 - t166;
  t179 = muDoubleScalarPower(muDoubleScalarAbs(((((t171 * in2[120] + t168 * in2
    [121]) + t175 * in2[128]) - t160 * in2[122]) - t162 * in2[126]) - t165 *
    in2[127]), in1[1] - 1.0);
  t20 = t29_tmp * t42 * 2.0;
  t184 = t17_tmp * t42 * 2.0;
  t17 = t46_tmp * t42 * 2.0;
  t187 = t55 + in2[22] * in2[28] * t54 * 2.0;
  t19 = in2[22] * in2[27] * t54 * 2.0;
  t4 = in2[21] * 2.0;
  t191 = t4 + in2[22] * in2[29] * t54 * 2.0;
  t192 = (t35 - t44_tmp) + t184;
  t215 = t2 * t12 * 2.0;
  t194 = (t46 - t20) + t215;
  t32_tmp = t199 * 2.0;
  t197 = (t49 - t17) + t32_tmp;
  t199 = t5 - t19;
  t2 = muDoubleScalarPower(muDoubleScalarAbs(((((t194 * in2[121] + t197 * in2
    [122]) + t199 * in2[126]) - t192 * in2[120]) - t187 * in2[127]) - t191 *
    in2[128]), in1[1] - 1.0);
  t207 = t46_tmp * t43 * 2.0;
  t208 = t17_tmp * t43 * 2.0;
  t209 = t29_tmp * t43 * 2.0;
  t25 = t55 + in2[23] * in2[29] * t54 * 2.0;
  t213 = t56 + in2[23] * in2[27] * t54 * 2.0;
  t214 = in2[23] * in2[28] * t54 * 2.0;
  memset(&out1[0], 0, 18U * sizeof(real_T));
  out1[18] = t70;
  out1[19] = -t7 - t51_tmp;
  out1[20] = t50_tmp - in2[21] * in2[23] * 2.0;
  out1[21] = ((((t73 + t74) - t58_tmp) - t57_tmp) - t59_tmp) - t85_tmp;
  out1[22] = t65;
  out1[23] = t69;
  out1[24] = (-t8 - t11) + 1.0;
  out1[25] = t71;
  out1[26] = -t50_tmp + t52;
  memset(&out1[27], 0, 82U * sizeof(real_T));
  out1[109] = t7 - in2[21] * in2[22] * 2.0;
  out1[110] = t101;
  out1[111] = -t9 - b_t53_tmp;
  out1[112] = (((((t22_tmp + t94) + t95) + t96) - t106_tmp) - t23_tmp) -
    b_t106_tmp;
  out1[113] = ((((t104 + t105) - t58_tmp) - t57_tmp) - t59_tmp) - t115_tmp;
  out1[114] = t100;
  out1[115] = -t7 + t51_tmp;
  out1[116] = (-t8 - t10) + 1.0;
  out1[117] = t102;
  memset(&out1[118], 0, 82U * sizeof(real_T));
  out1[200] = t52_tmp * -2.0 - t50_tmp;
  out1[201] = t9 - in2[22] * in2[23] * 2.0;
  out1[202] = t133;
  out1[203] = t128;
  out1[204] = t132;
  out1[205] = ((((t136 + t137) - t58_tmp) - t57_tmp) - t59_tmp) - t33_tmp;
  out1[206] = t134;
  out1[207] = -t9 + b_t53_tmp;
  out1[208] = (-t10 - t11) + 1.0;
  memset(&out1[209], 0, 85U * sizeof(real_T));
  out1[294] = (t41 * -2.0 + t29) - t53_tmp;
  out1[295] = (-t35 + t31) - t44_tmp;
  out1[296] = t160;
  out1[297] = 0.0;
  out1[298] = 0.0;
  out1[299] = 0.0;
  out1[300] = t162;
  out1[301] = t165;
  out1[302] = -t56 + t166;
  memset(&out1[303], 0, 82U * sizeof(real_T));
  out1[385] = (t35 + t184) - t44_tmp;
  out1[386] = (t41 * -2.0 + t20) - t215;
  out1[387] = (-t49 + t17) - t32_tmp;
  out1[388] = 0.0;
  out1[389] = 0.0;
  out1[390] = 0.0;
  out1[391] = in2[23] * -2.0 + t19;
  out1[392] = t187;
  out1[393] = t191;
  memset(&out1[394], 0, 82U * sizeof(real_T));
  out1[476] = (in2[28] * -2.0 + t208) - t48;
  out1[477] = (t49 + t209) - t32_tmp;
  t5 = t3 * t12 * 2.0;
  out1[478] = (t41 * -2.0 + t207) - t5;
  out1[479] = 0.0;
  out1[480] = 0.0;
  out1[481] = 0.0;
  out1[482] = t213;
  out1[483] = in2[21] * -2.0 + t214;
  out1[484] = t25;
  memset(&out1[485], 0, 61U * sizeof(real_T));
  out2[0] = in1[0] * (((in2[23] * t32 - in2[22] * t34) + in2[21] * t60_tmp) + t6
                      * t27) * 0.00026666666666666668;
  out2[1] = in1[0] * (((-in2[23] * t27 + in2[21] * t34) + in2[22] * t60_tmp) +
                      t6 * t32) * 0.00026666666666666668;
  out2[2] = in1[0] * ((((in2[22] * t27 - in2[21] * t32) + in2[23] * t60_tmp) +
                       t6 * t34) + 36.0) * 0.0008;
  out2[3] = in1[0] * (((in2[22] * t43 * 2.0 - in2[23] * t42 * 2.0) + in2[21] *
                       t61 * 2.0) - t6 * t36 * 2.0) * -4.2666666666666668E-11;
  out2[4] = in1[0] * (((in2[23] * t36 * 2.0 - in2[21] * t43 * 2.0) + in2[22] *
                       t61 * 2.0) - t6 * t42 * 2.0) * -1.421066666666666E-8;
  out2[5] = in1[0] * (((in2[22] * t36 * 2.0 - in2[21] * t42 * 2.0) - in2[23] *
                       t61 * 2.0) + t6 * t43 * 2.0) * 4.75111111111111E-9;
  t215 = (t158 + t48) - t208;
  t207 = (t46 - t207) + t5;
  t209 += t49 - t32_tmp;
  t208 = t4 - t214;
  t214 = muDoubleScalarPower(muDoubleScalarAbs(((((t207 * in2[122] + t215 * in2
    [120]) + t208 * in2[127]) - t209 * in2[121]) - t25 * in2[128]) - t213 * in2
    [126]), in1[1] - 1.0);
  t20 = in1[2] * t70 * t89;
  t53_tmp = in1[2] * t71 * t89;
  t5 = in1[2] * t72 * t89;
  out3[0] = (((((((-in1[2] * t65 * t89 * in2[121] - t20 * in2[117]) + t53_tmp *
                  in2[118]) - in1[2] * t69 * t89 * in2[122]) - t5 * in2[119]) +
               t20 * in2[123]) - t53_tmp * in2[124]) + t5 * in2[125]) + in1[2] *
    t85 * t89 * in2[120];
  t20 = in1[2] * t103 * t118;
  t53_tmp = in1[2] * t102 * t118;
  out3[1] = (((((((-in1[2] * t101 * t118 * in2[118] - t20 * in2[117]) + t53_tmp *
                  in2[119]) - in1[2] * t100 * t118 * in2[122]) + in1[2] * t101 *
                t118 * in2[124]) + t20 * in2[123]) - in1[2] * t106 * t118 * in2
              [120]) - t53_tmp * in2[125]) + in1[2] * t115 * t118 * in2[121];
  t20 = in1[2] * t134 * t151;
  t53_tmp = in1[2] * t133 * t151;
  t5 = in1[2] * t135 * t151;
  out3[2] = (((((((-in1[2] * t128 * t151 * in2[120] + t20 * in2[117]) - t53_tmp *
                  in2[119]) - in1[2] * t132 * t151 * in2[121]) - t5 * in2[118])
               - t20 * in2[123]) + t53_tmp * in2[125]) + t5 * in2[124]) + in1[2]
    * t148 * t151 * in2[122];
  out3[3] = ((((-in1[3] * t160 * t179 * in2[122] - in1[3] * t162 * t179 * in2
                [126]) + in1[3] * t168 * t179 * in2[121]) + in1[3] * t171 * t179
              * in2[120]) - in1[3] * t165 * t179 * in2[127]) + in1[3] * t175 *
    t179 * in2[128];
  out3[4] = ((((-in1[3] * t192 * t2 * in2[120] - in1[3] * t187 * t2 * in2[127])
               + in1[3] * t194 * t2 * in2[121]) - in1[3] * t191 * t2 * in2[128])
             + in1[3] * t197 * t2 * in2[122]) + in1[3] * t199 * t2 * in2[126];
  out3[5] = ((((in1[3] * t215 * t214 * in2[120] - in1[3] * t25 * t214 * in2[128])
               - in1[3] * t213 * t214 * in2[126]) + in1[3] * t207 * t214 * in2
              [122]) - in1[3] * t209 * t214 * in2[121]) + in1[3] * t208 * t214 *
    in2[127];
  for (i = 0; i < 6; i++) {
    out4[i] = 0.0;
  }
}

/* End of code generation (sprdmpF100.c) */
