%% initialize
close all
clear all
format shorte
clc
pause( 1e-2 )

addpath('./tmtdyn');
addpath('./hll');
addpath('./eom');


%% parameters
l_xz2 = 73e-3 / 5 ;
l_y2 = 0.8e-3 ;
m_2 = 36e-3 / 15 ;

l_x1 = 76e-3 / 2 ;
l_z1 = 30e-3 ;
l_com1 = 135e-3 ;

g = 9.81 ; % gravity

% EBA
E = 1.5e3 ;
mu_pow = 1 ; % < 1: rate thining, > 1: rate thikening
mu_v = 5e1 ;
mu_u = 5e1;
mu_link = 7e-4 ;

phi = - 85 * pi/ 180 ;
 
%% preprocess
G = E_sym / 3 ;
I_2 = 1 / 12 * m_2 * ...
    diag( [ l_y2^2+l_xz2^2 l_xz2^2+l_xz2^2 l_xz2^2+l_y2^2 ] ) ;
J_2 = 1 / 12 * [ l_xz2*l_y2^3 l_xz2^3*l_y2 l_xz2*l_y2^3+l_xz2^3*l_y2 ] ;
a_xy2 = l_xz2 * l_y2 ;
K_v = diag( [ G G E_sym ] ) * a_xy2 / l_xz2 ;
K_u = diag( [ E_sym E_sym G ] ) * diag( J_2 ) / l_xz2 ;


%% robot
tmtdyn()...
    .simulation()... % simulation
        .var('E_sym', E)...
        .var('mu_pow_sym', mu_pow)...
        .var('mu_v_sym', mu_v)...
        .var('mu_u_sym', mu_u)...
        .var('phi_sym', phi)...
        .var('mu_link_sym', mu_link)
        ...
        .eom_derive()...
            .mex()...
            .optimize()...
        .end()...
        .analysis()...
            .dynamic_sim(2)... % what does the 2 mean?
        .end()...
        .post_process()...
            .animate()...
            .user_code()... % what does this do?
        .end()...
    .end()...
    ...
    .g([ 0 0 -g ])...
    ...
    .robot('fabric_pendulum')... % robot
        .body('arm')...
            .with_mass(m_2)...
            .with_centre_of_mass_at([0 0 -l_com1])...
            .with_tip_at(2*l_com)... % is this right or should this be a vector?
        .end()...
        .connected_from_base('arm_hinge')...
            .to_body(1)...
            .with_transformations()...
                .rot_y()...
  		  .init(phi_sym)...
		  .damper()...
		      .visc(mu_link_sym)...
		  .end()...
	        .end()...
            .end()...
        .end()
        .mesh('fabric')...
          .from_file('exp/exp2.iges')...
          .with_tolerance(1e-3)...
          .with_transformations()...
            .rot_y(phi_sym)...
            .trans_z(-l_z1)...
          .end()...
          .body('fabric')...
            .mass(m_2)...
            .inertia(I_2)...
            .with_DOFs()... % used to be joint('fabric_points')
              .with_transformations()...
                .trans([inf inf inf])...
                .rot_type('non_unit_quat')...
                .rot([inf inf inf inf])...
              .end()...
            .end()...
          .end()...
          .joint('fabric_links')...
            .spring()...
                .coeff([ diag( K_v ).' diag( K_u ).' ])...
                .init(nan)... % what does this mean? could we just say .eb_beam()?
            .end()...
            .damper()...
                .visc([ mu_v_sym*ones(1,3) mu_u_sym*ones(1,3) ])...
                .power(mu_pow_sym)...
            .end()...
          .end()...
        .end()...
        .constraint('clip_constraint_1')...
          .from_body(1)...
          .to_body(16)...
          .maintain()...
            .trans([ l_x1 0 -l_z1 ])...
          .end()...
          .fixed_in_x_y_z()... 
        .end()...
        .constraint('clip_constraint_2')...
          .from_body(1)...
          .to_body(14)...
          .maintain()...
            .trans([ -l_x1 0 -l_z1 ])...
          .end()...
          .fixed_in_x_y_z()... 
        .end()...
   .end()...
   .run() ;


